### ISSUE TITLE
Is there any plan to support x64-Windows Lua debug?

### ISSUE THREAD

**Issue by tan-wei** [pkulchenko/ZeroBraneStudio#1000]
For now, the release binaries only support x86 in Windows. All the `dll` files included in `bin\clibs`, `bin\clibs52` and `bin\clibs53` are compiled as x86 binaries. If I want to debug scripts which use x64 libs, it will fail (obviously). For example, debug dissectors with Wireshark-x64 which is compiled with x64 version Lua.

So is there any plan to support x64-Windows? I notice that the release binaries of Linux support both x86 and x64.

By the way, thanks for this great tool.

**Comment by pkulchenko** [comment]
@tan-wei, it is supported, but the binaries are not distributed with the IDE itself. You can get them compiled for Lua 5.1 at this URL: https://download.zerobrane.com/misc/luasec-0.8-openssl-1.1.1c-luasocket-3.0-win64.zip.  I'll update it to include Lua5.2 and Lua5.3 binaries and will update the ticket when it's done.

**Comment by tan-wei** [comment]
@pkulchenko Good news for who have the same requirement. Thanks for your quick response. Hope you have a great day.

**Comment by pkulchenko** [comment]
Also, since you only need luasocket libraries, I have them available in one package for lua 5.1-5.3 versions: https://download.zerobrane.com/misc/luasocket-3.0-win64.zip. If that's all you need, I'll close the ticket.

**Comment by tan-wei** [comment]
@pkulchenko , thanks very much!

**Comment by tan-wei** [comment]
Feel sorry about the missing pre-reading with [the page](https://studio.zerobrane.com/doc-remote-debugging#debugging-of-64bit-applications). Hope someone else who have the same question about x64 support may read this page first.

**Comment by pkulchenko** [comment]
np; I'll update the page to add the link to the compiled libraries.

**Comment by tan-wei** [comment]
Great!
Maybe in next version, these binaries can be distributed with IDE if possible.
