### ISSUE TITLE
Exhaustive documentation of configurables?

### ISSUE THREAD

**Issue by rulatir** [pkulchenko/ZeroBraneStudio#1004]
Where can I find an exhaustive documentation of all settings that can be set through the configuration files?

**Comment by pkulchenko** [comment]
The general settings are listed on this page (https://studio.zerobrane.com/doc-general-preferences) and the editor specific settings are on this page (https://studio.zerobrane.com/doc-editor-preferences). All the settings known to the application should be listed on those pages with the exception of one or two internal ones that I don't plan to document. If you find something not listed there, let me know in this ticket.
