### ISSUE TITLE
Error loading module 'wx' (undefined symbol: lua_tonumber)

### ISSUE THREAD

**Issue by F0Xde** [pkulchenko/ZeroBraneStudio#1005]
I just installed ZeroBrainStudio on Manjaro Linux via the AUR, and every time i try to start it i get this error:
`/usr/bin/lua: error loading module 'wx' from file '/usr/lib/lua/5.3/wx.so':
	/usr/lib/lua/5.3/wx.so: undefined symbol: lua_tonumber
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	src/main.lua:38: in main chunk
	[C]: in ?
`

**Comment by pkulchenko** [comment]
You need to contact the package manager for AUR, as it looks like it's using lua 5.3 to run the IDE, but it requires Lua 5.1 or LuaJIT to run.

You can probably install Lua 5.1 yourself and use it to run the IDE.
