### ISSUE TITLE
Code analysis doesn't consider recursive function unused

### ISSUE THREAD

**Issue by theRealsteveRoll** [pkulchenko/ZeroBraneStudio#1006]
Normally, when there is a local function that is not used anywhere in the code, the code analysis says `unused local function ...`.
However, when a local function calls itself but isn't called anywhere else, the analysis considers it used, and doesn't warn.

**Comment by pkulchenko** [comment]
@theRealsteveRoll, this is a deficiency in lua-inspect library that is used to detect local functions. You may want to switch to using luacheck (add `staticanalyzer.luacheck=true` to the IDE config), which will report this case as: `unused recursive function ...`.
