### ISSUE TITLE
Segmentation fault on start up - Ubuntu 19.04 x64

### ISSUE THREAD

**Issue by dcsoftwaresystems** [pkulchenko/ZeroBraneStudio#1017]
I'm seeing a seg fault on starting zbstudio.sh.  I'm running Ubuntu 19.04 x64 architecture.  This installation ran fine until now.  I recently upgraded the system to 19.04 and since then I'm seeing the SIGSEGV termination.  I cloned the current repo into a new location and started ./zbstudio.sh with the same result.  If you want me to upload a core or apport crash file let me know.

**Comment by pkulchenko** [comment]
@dcsoftwaresystems, thank you for the report. Can you load the core in gdb and run `bt` command? Does it not even open the IDE window? Does it happen on every launch?

**Comment by dcsoftwaresystems** [comment]
Output of gdb:

**Comment by pkulchenko** [comment]
@dcsoftwaresystems, this is not a very informative stack trace. Can you try running the IDE from the upgrade branch (https://github.com/pkulchenko/ZeroBraneStudio/compare/upgrade-binaries-190)? If this still doesn't work, I'll have to install the same version and try to figure out what's going on.

**Comment by dcsoftwaresystems** [comment]
When I run the zbstudio from a desktop link, it pops up the ide window momentarily, but if I run it from the shell it never shows the IDE and exits with SIGSEGV in a few seconds.

**Comment by pkulchenko** [comment]
@dcsoftwaresystems, is this with the upgrade branch?

Can you try running `bin/linux/x64/lua src/main.lua` from the IDE folder (the same folder where zbstudio.sh is located)? There may be some errors reported to the stdout...

**Comment by dcsoftwaresystems** [comment]
First, the upgrade branch does not seg fault and appears to be working normally.  Running the command above from the IDE folder results in the IDE briefly flashing on the screen and then exiting with the shell only displaying "Segmentation fault (core dumped)".

**Comment by pkulchenko** [comment]
Ok; thank you for the update. This should be fixed then when #999 is merged.

**Comment by pkulchenko** [comment]
This has been implemented as part of the changes in #999 that have been merged.
