### ISSUE TITLE
MacOS Catalina - fails to start

### ISSUE THREAD

**Issue by prographo** [pkulchenko/ZeroBraneStudio#1020]
Brand new Mac Book Pro (Catalina), fresh install. Doesn't start.

Doesn't open a window or anything, just instantly aborts. Last line of dmesg:

```
Unsupported 32-bit executable: "/Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua"[IGFB][INFO   ] [Set_attribute] (attribute=' bst', value=0)
```

**Comment by prographo** [comment]
Ok, new Macs don't run 32bit software. You just need to switch your compiler to 64bit and compile.

**Comment by pkulchenko** [comment]
@prographo, you can use the 64bit code from https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190b branch. See ticket #1018 for details. I'll have a release soon, which will incorporate the new 64bit binaries.

**Comment by prographo** [comment]
works !!!!!
