### ISSUE TITLE
A few internationalization support missing in file search results

### ISSUE THREAD

**Issue by yu-tang** [pkulchenko/ZeroBraneStudio#1022]
I found a few internationalization support missing while a localization for personal use.
File search outputs following results to a dedicated pane.

    Search Results: SEARCH_WORD
    Searched for 'SEARCH_WORD'. Found XX instances on XX lines in XX files.

For now, it seems that we have no way to localize these strings for v1.80.

**Comment by pkulchenko** [comment]
@yu-tang, that's correct. Those string are indeed can't be translated right now and it's complicated to implement, as the current implementation only allows for one modified in the translated string, not three. Also, the text in the UI is translated, but this text appears in the editor itself (although it's auto-generated), so I thought that given the challenges with proper translation, it can be left in English for consistency.

I'll review this one more time, but it's likely that it will stay as is for now.

**Comment by yu-tang** [comment]
Thank you for your reply.
I understand your point.

For Japanese users information, see [ja.lua](https://gist.github.com/yu-tang/36376d5964043765dca99715b32e895f) file.

**Comment by pkulchenko** [comment]
@yu-tang, thank you. Do you give the permission to include it in the IDE under the MIT license?

**Comment by yu-tang** [comment]
@pkulchenko Sure, go ahead! That's my pleasure.
