### ISSUE TITLE
Unable to launch after fresh install from AUR on ArchLinux

### ISSUE THREAD

**Issue by ipochto** [pkulchenko/ZeroBraneStudio#1023]
After fresh install from [AUR](https://aur.archlinux.org/packages/zerobrane-studio) zbstudio don't start:

```
$ zbstudio

/usr/bin/lua: error loading module 'wx' from file '/usr/lib/lua/5.3/wx.so':
    /usr/lib/lua/5.3/wx.so: undefined symbol: lua_tonumber
stack traceback:
    [C]: in ?
    [C]: in function 'require'
    src/main.lua:38: in main chunk
```
wxLua installed from git (also from [AUR](https://aur.archlinux.org/packages/wxlua-git))

**Comment by pkulchenko** [comment]
@ipochto, I'm not sure exactly what you setup is (for example, what version of ZeroBrane Studio you are using and why you installed wxlua from git, if it's packaged with ZeroBrane Studio itself), but you seem to be running wxlua (wx.so) compiled for Lua 5.3 from Lua 5.1 (or something along those lines).

**Comment by ipochto** [comment]
>why you installed wxlua from git, if it's packaged with ZeroBrane Studio itself

wxLua was installed as a dependency for zerobrane-studio package.  Moreover, exactly git-version  of wxLua was declared as dependency. Package was build from this source: `https://github.com/pkulchenko/wxlua.git`

If install only zerobrane-studio, without wxlua-git package - it seems zb-s can't find wxlua (which packaged with it). I get this:
```
$ zbstudio 
$ /usr/bin/lua: src/main.lua:38: module 'wx' not found:
	no field package.preload['wx']
	no file 'lualibs/wx.lua'
	no file 'lualibs/wx/wx.lua'
	no file 'lualibs/wx/init.lua'
	no file '/usr/share/lua/5.3/wx.lua'
	no file '/usr/share/lua/5.3/wx/init.lua'
	no file '/usr/lib/lua/5.3/wx.lua'
	no file '/usr/lib/lua/5.3/wx/init.lua'
	no file './wx.lua'
	no file './wx/init.lua'
	no file 'bin/linux/x64/clibs/libwx.so'
	no file 'bin/linux/x64/clibs/wx.so'
	no file '/usr/lib/lua/5.3/wx.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './wx.so'
stack traceback:
	[C]: in function 'require'
	src/main.lua:38: in main chunk
	[C]: in ?
```

Version of zerobrane studio is 1.80. Package building from this source:  `https://github.com/pkulchenko/ZeroBraneStudio/archive/1.80.tar.gz`

**Comment by pkulchenko** [comment]
It's supposed to be here `bin/linux/x64/clibs/libwx.so`; at least in the configuration that ZeroBrane Studio is using on Linux. What is the content of that folder?

**Comment by pkulchenko** [comment]
Also, why are you trying to run zerobrane studio using system lua and system wxlua (they both seem to be using Lua 5.3) instead of the Lua version that comes with the IDE itself (`bin/linux/lua`)?

**Comment by ipochto** [comment]
> Also, why are you trying to run zerobrane studio using system lua and system wxlua (they both seem to be using Lua 5.3) instead of the Lua version that comes with the IDE itself (`bin/linux/lua`)?

I'm just launch `zbstudio` which was generated by make and installed by package manager into `/usr/bin`
It uses system lua - `/usr/bin/lua`:
```
$ cat /usr/bin/zbstudio
#!/bin/bash

if [[ "$(uname -m)" == "x86_64" ]]; then ARCH="x64"; else ARCH="x86"; fi
CWD="$PWD" # save the current directory, as it's going to change

(cd "/usr/share/zbstudio"; /usr/bin/lua src/main.lua zbstudio -cwd "$CWD" "$@") &
```

**Comment by ipochto** [comment]
I just try to launch `zbstudio.sh` from downloaded source. It works. Just opened the folder contained source from git and start `zbstudio.sh` from my home directory, without making package and installing it system wide...
It's very confusing, but content of `zbstudio.sh` is different from `/usr/bin/zbstudio` which was generated by make-utility. It seems problem with packaging and installing it system wide.

**Comment by pkulchenko** [comment]
Yes, the issue seems to be with AUR packaging. Can you also try to uninstall the AUR package and install the Linux package from the download page: https://download.zerobrane.com/ZeroBraneStudioEduPack-1.80-linux.sh. It will do the system-wide install and I expect it to work, but would like to confirm.

**Comment by ipochto** [comment]
>Can you also try to uninstall the AUR package and install the Linux package from the download page: https://download.zerobrane.com/ZeroBraneStudioEduPack-1.80-linux.sh. It will do the system-wide install and I expect it to work, but would like to confirm.

Yes, it works. Thanks

**Comment by pkulchenko** [comment]
Ok, thank you. I'm closing this ticket then, but you may want to link to this discussion from the [AUR](https://aur.archlinux.org/packages/zerobrane-studio) page.

**Comment by alerque** [comment]
@lpochto I'm sorry I never saw you AUR comment (probably a mail server issue because I don't see it even now searching for it) and this issue report got to me either. I've fixed _this_ issue, but now there seems to be another unrelated one. I'd like to skip to 1.90 and get that working instead of 1.80, but this repo hasn't been tagged yet (see #1037). As soon as it is I'll update the AUR packaging again.

**Comment by alerque** [comment]
@pkulchenko If you ever get Arch Linux related issue reported here feel free to ping me and/or assign the issue to me.

**Comment by pkulchenko** [comment]
Thanks @alerque; will do!

**Comment by alerque** [comment]
@ipochto The latest releases of zbstudio builds and runs properly on Arch Linux now. I've just updated the AUR packaging to 1.90. You'll also need to recompile wxlua (to 3.0.0.8) for it to work.

**Comment by ipochto** [comment]
@alerque, Thank you!

**Comment by szemy** [comment]
Hi @alerque! I have just installed zerobrane from AUR on a up-to-date Manjaro laptop. 
First It seemed lua-mobdebug-git was missing, but after installing it: 
lua: /etc/zerobrane-studio/user.lua:13: attempt to index a nil value (global 'path')
stack traceback:
	/etc/zerobrane-studio/user.lua:13: in main chunk
	[C]: in ?
What could be missing?
Thanks!

**Comment by pkulchenko** [comment]
@szemy, something strange is happening in your case, as `user.lua` should accept `path` references (as it's defined for any configuration file with user.lua being one of them). How are you launching the IDE and what's the content of line 13 in user.lua? Could you try removing this user.lua to see if the IDE launches normally?

**Comment by alerque** [comment]
The AUR package had an outdated `user.lua` file from before the current default system version of Lua. I just updated that and the package builds and runs fine again out of the box again.

----

**PSA**: Please stop re-using this old closed issue for everything. If there is a problem with ZBStudio itself open a new issue on this repository. If there is a problem with the AUR packaging please [open a new issue on this repository where the packaging is hosted](https://github.com/alerque/aur). Thanks.

**Comment by szemy** [comment]
@pkulchenko after further investigation, installing lua-coxpcall solved it. Can you includ it in the AUR installation?

**Comment by alerque** [comment]
> installing lua-coxpcall solved it. Can you includ it in the AUR installation?

Already done and included in the pkgrel bump that updates the system Lua paths.

**Comment by szemy** [comment]
So still this fresh install from AUR and a simple  print("Hello World") throws:
Program starting as '"/usr/share/zbstudio/bin/linux/x64/lua" -e "io.stdout:setvbuf('no')" "/tmp/.26mm5A"'.
Program 'lua' started in '/home/tamas/Documents/lua/zb/25_03_31' (pid: 356951).
execvp(/usr/share/zbstudio/bin/linux/x64/lua, -e, io.stdout:setvbuf('no'), /tmp/.26mm5A) failed with error 2!
