### ISSUE TITLE
Debugging: Variable tooltip with binary string content, which is not UTF8

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1025]
Take the following code:
```lua
local A={x="\1\0\0\0",y="\2\0\0\0",z="\0\0\0\xF9"}
local B={x="\1\0\0\0",y="\2\0\0\0",z="\0\0\0\x79"}

io.flush() -- < breakpoint here
```
For B, if I move the mouse pointer over the variable, I get the value shown in a tooltip.
![zbs-tooltip-good](https://user-images.githubusercontent.com/8567887/69526255-1450a180-0f6a-11ea-8908-41b6a49505e3.png)
For A I only get an empty tooltip:
![zbs-screenshot-bad](https://user-images.githubusercontent.com/8567887/69526265-1a468280-0f6a-11ea-9fc7-0bb1527b4cc2.png)

Values ARE shown in the Remote console:
![zbs-console](https://user-images.githubusercontent.com/8567887/69526273-1f0b3680-0f6a-11ea-9bb2-3bda838aae70.png)

I assume the tooltip fails to render the content, if string contains a code, which is not valid Utf8.

**Comment by pkulchenko** [comment]
@jjvbsag, thank you for the report; should be fixed now in the master branch.
