### ISSUE TITLE
Struggles with path to .zbstudio using Windows 10 and domain login.

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1026]
We have some users, which are working on W10 and use a domain login.
Now:

`ZeroBraneStudio.ini` is located at `C:\Users\<username>\AppData\Roaming\ZeroBraneStudio.ini` which is fine.
But `.zbstudio\` is located at `\\<domainserver>\user\<username>\.zbstudio\` which causes trouble.

I could not locate the reference, where path to .zbstudio is created in ZBS.

Is there any posibility to override the path of .zbstudio to have it at 
`C:\Users\<username>\.zbstudio\` ?
or at least at
`C:\Users\<username>\AppData\Roaming\.zbstudio\` ?

Regards

PS: And no, we cannot change windows environment such as `HOMEDRIVE` or `HOMEPATH`, because they are predefined and fixed by IT deparment :-1:

**Comment by pkulchenko** [comment]
@jjvbsag, why do you care where `.zbstudio` folder is located? Is it to place the packages there? There are two commands -- `include` and `package` -- that allow you to specify where the location of (other) configuration files or package folders/files should be, so you can add those to the main config or pass to the launch command using the `-cfg` option. See the [documentation for details](https://studio.zerobrane.com/doc-configuration#configuration-file-commands).

Another option is to set `HOME` variable to point to `C:\Users\<username>\` location (`HOMEDRIVE` and `HOMEPATH` are checked if `HOME` is not set), which will then generate `C:\Users\<username>\.zbstudio\` path.

Feel free to re-open if this doesn't satisfy your needs.

**Comment by jjvbsag** [comment]
@pkulchenko My users _do_ care. Because ZBS behaves different depending on
- "user is logged into domain" => `\\<domainserver>\user\<username>\.zbstudio\`
or 
- "user is not logged into domain" => `C:\Users\<username>\.zbstudio\`

This makes it difficult for them to keep settings, user packages, open project, ...  in sync on both situations. Note: Not all of them are experts...

---

About setting `HOME`:
I will try tomorrow on one of the affected users laptop. But I'm quite sure, IT has disabled these settings.

---

_"Feel free to re-open if this doesn't satisfy your needs."_ 
How this? I have no "re-open" button in GitHub.

Regards

**Comment by pkulchenko** [comment]
> "user is logged into domain" => \\<domainserver>\user\<username>\.zbstudio\
>  or
>  "user is not logged into domain" => C:\Users\<username>\.zbstudio\

Good point; I think using `-cfg` parameter with `package=[[C:\Users\<username>\.zbstudio\]]` passed to it, should do it then.

> How this? I have no "re-open" button in GitHub.

I see `[Reopen and comment]` right next to green `[Comment]` button under the text box.

**Comment by jjvbsag** [comment]
@pkulchenko :clown_face: I believe, you can see `[Reopen and comment]` because you are the **owner** of the project. Me as a :duck: user can not do that.

Because of this we in our company have the workflow:
- user creates issue
- maintainer fixes issue and set's it to "solved"
- user verifies fix and set's it to "still open" or "closed"

**Comment by jjvbsag** [comment]
@pkulchenko just a feedback. Overriding `HOME` in the user requirement was possible and has the wanted effect. So this is now also closed for me.
Regards

**Comment by pkulchenko** [comment]
@jjvbsag, got it; thank you for the update!
