### ISSUE TITLE
Mac 10.15.1 - Zerobrane Crashes

### ISSUE THREAD

**Issue by njligames** [pkulchenko/ZeroBraneStudio#1027]
Hello,
I just updated my Mac and redownloaded Zerobrane.
When I try to launch Zerobrane, the icon bounces once and stops. Failing to launch

This is the log from the console:

Dec  5 19:29:03 njlic-macbook-pro com.apple.xpc.launchd[1] (com.ZeroBrane.ZeroBraneStudio.5596[28959]): Service exited with abnormal code: 1

**Comment by pkulchenko** [comment]
@njligames, see #1020 ticket for solution (also #1019 and #1018). Also make sure you are not launching the IDE from `Documents/`, `Desktop/`, or `Downloads/` folders, as apps can't load dynamic libraries from those locations on Catalina.
