### ISSUE TITLE
Latest github

### ISSUE THREAD

**Issue by prographo** [pkulchenko/ZeroBraneStudio#1030]
MacOS Catalina

~/ZeroBraneStudio$ ./zbstudio.sh
LSOpenURLsWithRole() failed with error -10810 for the file /Users/mrsmith/ZeroBraneStudio/zbstudio/ZeroBraneStudio.app.

**Comment by pkulchenko** [comment]
Are you running the code from the master branch? Yes, it's not going to work; you need to run the code from some of the beta release branches (for example, https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190d). See #1018, #999.

**Comment by prographo** [comment]
Sry, my bad ... and I did this before once, and now I am setting it up for someone else.

**Comment by pkulchenko** [comment]
np; the next release will fully address this issue.
