### ISSUE TITLE
ZeroBrane doesnt start (Mac OS X 10.15.2)

### ISSUE THREAD

**Issue by toropok** [pkulchenko/ZeroBraneStudio#1031]
Hi,

ZeroBrane doesnt start w/ follow error:

```
/Applications/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio: line 10: /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua: Bad CPU type in executable

/Applications/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio: line 10: /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua: Undefined error: 0
```

<img width="323" alt="Screenshot 2020-01-14 at 14 41 06" src="https://user-images.githubusercontent.com/14867014/72323711-eb33ce00-36db-11ea-8ca8-b8a4fafc414c.png">

Did anyone encounter such behavior? 

thanks

**Comment by pkulchenko** [comment]
@toropok, yes, it's a known issue, which will be addressed in the next release. For now you can run the code from one of the beta branches (for example, https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190d). See #1018, #999.
