### ISSUE TITLE
Exclude some dirs from list for the `Go to file` command

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#1032]
I have quite a lot of dirs/files in temp dirs generated by test cases.
So I want to exclude those files from the list.

**Comment by pkulchenko** [comment]
@moteus, see [file exclusion lists](https://studio.zerobrane.com/doc-general-preferences#file-exclusion-lists). They allow you to fully exclude some directories/files from processing by the IDE (`excludelist`) or show them in the tree, but exclude them from fuzzy search (`binarylist`). I'm closing this, as it should address your needs, but feel free to reopen with some example if it doesn't.

**Comment by moteus** [comment]
Thanks for the link and docs.
Its almost what I need. But in fact i need only exclude dirs from fuzzy search but still hant to be able use `Search in files` and see this dir in the project treeview. May be it is possible accomplish via plugins?

**Comment by pkulchenko** [comment]
I don't think this combination is covered right now. I've been considering adding callbacks for commandbar processing, which will allow you to intercept and adjust the list, but it's not going to be included in this (coming) version.

When you say you don't want to see it in the fuzzy search, do you mean you don't want to see those files in the fuzzy search results regardless of their scores?
