### ISSUE TITLE
App started but no window show up (mcOS Catalina)

### ISSUE THREAD

**Issue by HappyGames** [pkulchenko/ZeroBraneStudio#1033]
when i run with ./zbstudio.sh there is no window show up , just a menu on top of the screen
<img width="260" alt="EA2C5A57-1F93-457D-9AAB-21C5DC62B0AB" src="https://user-images.githubusercontent.com/3297604/72403931-b03ea280-378e-11ea-9b43-d16039c6f1af.png">
![image](https://user-images.githubusercontent.com/3297604/72403819-54741980-378e-11ea-808c-771d00013a8b.png)

**Comment by pkulchenko** [comment]
What version of the IDE are you running and from what branch? If you are using one of the releases (<=1.80) or the code from the `master` branch, then it's not going to work as those binaries are 32bit and Catalina requires 64bit code. You'll have to run code from https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190e. See #1018, #999.

**Comment by HappyGames** [comment]
> What version of the IDE are you running and from what branch? If you are using one of the releases (<=1.80) or the code from the `master` branch, then it's not going to work as those binaries are 32bit and Catalina requires 64bit code. You'll have to run code from https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190e. See #1018, #999.

I did download zip from branch all-binaries-190e

**Comment by pkulchenko** [comment]
Can you make sure that you unzipped the archive into one of the folders under you HOME directory and not in Documents/, Downloads/, or Desktop/?
