### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ghost** [pkulchenko/ZeroBraneStudio#1034]
Newest release is over a year old:

https://studio.zerobrane.com

**Comment by pkulchenko** [comment]
I noticed; this is being handled in #999 and other tickets referenced in 1.90 milestone. The beta version is available at https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190e and the release is expected later this month.

**Comment by pkulchenko** [comment]
The changes for the new release has been merged into master and https://studio.zerobrane.com has been updated with the new release.
