### ISSUE TITLE
C2120: 'void' illegal with all types

### ISSUE THREAD

**Issue by Shelim** [pkulchenko/ZeroBraneStudio#1035]
During building wxLua on MSVC 2019 (Windows 10 x64) based on Lua 5.2 and wxWidgets 3.1.6 as win32 app I'm seeing following error message:

    Error	C2120	'void' illegal with all types	wxLuaModule	D:\private\wxLua\modules\wxlua\bit.c	180	

The code fragment is:
```cpp
    if (lua_rawget(L, -2) != LUA_TNIL) {  /* no such field? */
      luaL_error(L, "name conflict for module '%s'", modname);
    }
```

while `lua_rawget` is defined as
```cpp
    LUA_API void lua_rawget (lua_State *L, int idx) {
        StkId t;
        lua_lock(L);
        t = index2addr(L, idx);
        api_check(L, ttistable(t), "table expected");
        setobj2s(L, L->top - 1, luaH_get(hvalue(t), L->top - 1));
        lua_unlock(L);
    }
```

Obviously the function is returning `void`. I removed condition and left only

`     lua_rawget(L, -2)`

Inside `bit.c`

Then it compiled successfully. I am not sure why the change is left there in first place...

**Comment by pkulchenko** [comment]
@Shelim, thank you for the report! This should be reported to the wxlua repo and has already been fixed there just a day ago. See https://github.com/pkulchenko/wxlua/issues/54.
