### ISSUE TITLE
Git repository missing tags for latest release(s)

### ISSUE THREAD

**Issue by alerque** [pkulchenko/ZeroBraneStudio#1037]
I just noticed the website is listing a 1.90 but there are no tags for this release — hence the [Arch Linux packaging](https://aur.archlinux.org/packages/zerobrane-studio/) is silently out of date and can't easily be updated.

Could you tag the missing release point(s) please?

**Comment by pkulchenko** [comment]
The release has already been tagged; I just delayed merging the branch with the tag and pushing it out for a day. This has already been done, so you should see 1.90 on the list of releases/tags.
