### ISSUE TITLE
README.md "Installation" section leads to (github) "HTTP 404"

### ISSUE THREAD

**Issue by jaimet** [pkulchenko/ZeroBraneStudio#1038]
The installation section on
https://github.com/pkulchenko/ZeroBraneStudio/blob/master/README.md
contains a link to
https://github.com/pkulchenko/ZeroBraneStudio/blob/master/releases
which returns an http 404. I *think* that this should point to
https://github.com/pkulchenko/ZeroBraneStudio/releases
(but I am not sure)

**Comment by pkulchenko** [comment]
@jaimet, thank you for the report! Will fix shortly.
