### ISSUE TITLE
Multiline string/comment syntax highlighting works incorrectly

### ISSUE THREAD

**Issue by theRealsteveRoll** [pkulchenko/ZeroBraneStudio#1045]
If you type two left square brackets (`[[`) inside of a multiline comment or string, anything after the end of the multiline part will still be highlighted when it's not supposed to.
For example, if you type this:
```lua
thing = [[ [[ ]]
abcdwxyz = 9
```
It will look like this in the editor:
![image](https://user-images.githubusercontent.com/40004112/77007687-52d0f880-696d-11ea-8fff-75206423b021.png)

**Comment by pkulchenko** [comment]
Yes, it's a defect in Scintilla lexer, which takes inner `[[` as a start of a new multi-line comment (which it's not supposed to do). Unfortunately, there is not much that can be done in the IDE (short of ignoring the issue), as this is the latest Scintilla code that is available in wxwidgets (which is the toolkit that the IDE is built with).
