### ISSUE TITLE
Missing icons in the find form

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#1050]
Ubuntu 18.04.4 LTS, wxWidgets 3.1.4, wxLua 3.0.0.8, Scintilla 3.7.2 
ZBS - current master (1.90)
I did not run install script but just replace `opt/zbstudo` directory.

In the find form some buttons has no images.
![icon_size_24](https://user-images.githubusercontent.com/1804306/79686324-3532cf80-8248-11ea-9718-0d4c46b00967.png)
This is after I enforce iconsize=16 in the `findReplace:createToolbar` method.
![icon_size_16](https://user-images.githubusercontent.com/1804306/79686322-3401a280-8248-11ea-81e0-77be956a4ff7.png)

PS. This is really minr - on the favorites bar shows Lua icon, instead of ZBS.
![icon_zbs](https://user-images.githubusercontent.com/1804306/79687298-079d5480-824f-11ea-9fa8-c7bfc12c577a.png)

**Comment by pkulchenko** [comment]
> I did not run install script but just replace opt/zbstudo directory.

@moteus, I am a bit confused: what did you replace with what? Second question: are you using the system libraries for wxlua/wxwidgets or those bundled with the IDE?

Do you see images if you set `iconsize=24`? What is the scale factor of the monitor (you can check it by using `ide:GetMainFrame():GetContentScaleFactor()` in the console? Also, can you get the result of `ide:GetContentScaleFactor()` in the console?

All the icon images are in `zbstudio/res` folder (in 16/ and 24/ subfolders), so if those are replaced/removed, then that's what you'd see. The images in the search toolbar generally start with `FIND-OPT-`.

**Comment by moteus** [comment]
I forgot to copy the `res` directory. Now all the icons are in place.

But the last problem with the application icon. When I replace the `bin` directory with the one from 1.80 and icons back to `normal`, but with binaries from 1.90 I see the icon from my last screenshot.

**Comment by pkulchenko** [comment]
> But the last problem with the application icon. When I replace the bin directory with the one from 1.80 and icons back to normal, but with binaries from 1.90 I see the icon from my last screenshot.

You are probably missing `zbstudio/res/zbstudio.ico` file or need to reference it (according to `zbstudio/res/zbstudio.desktop` file.

I'm closing this, as I expect it to resolve the issue, but feel free to continue the discussion as needed.
