### ISSUE TITLE
How to check either editor is a valid object

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#1054]
I have a plugin with the next functions
```
local _editor
Package.onEditorUpdateUI = function(self, editor, event)
    if bit.band(event:GetUpdated(), wxstc.wxSTC_UPDATE_SELECTION) > 0 then
        _editor = editor
    end
end

Package.onIdle = function(self)
    if not _editor then return end
    local editor = _editor
    _editor = false
    local color = editor:GetCaretLineBackground()
```
And some time I got error like 
`attempt to index local 'editor' (a userdata value)`
This happen when I close editors quite fast.
Is there any way to check either editor can be used?

**Comment by pkulchenko** [comment]
Yes, you can use `ide:IsValidCtrl(editor)`; it's used in several places in event handlers.
