### ISSUE TITLE
Lua5.4 as a runtime not found wx module

### ISSUE THREAD

**Issue by zuzmo** [pkulchenko/ZeroBraneStudio#1059]
I`ve changed in the the zbstudio.sh startup script 'bin/linux/x64/lua' to 'bin/linux/x64/lua54' and I got the error after the build/build-linux.sh completed.

bin/linux/x64/lua54: src/main.lua:48: module 'wx' not found:
	no field package.preload['wx']
	no file 'lualibs/wx.lua'
	no file 'lualibs/wx/wx.lua'
	no file 'lualibs/wx/init.lua'
	no file '/usr/local/share/lua/5.4/wx.lua'
	no file '/usr/local/share/lua/5.4/wx/init.lua'
	no file '/usr/local/lib/lua/5.4/wx.lua'
	no file '/usr/local/lib/lua/5.4/wx/init.lua'
	no file './wx.lua'
	no file './wx/init.lua'
	no file '/home/zuzmo/.luarocks/share/lua/5.4/wx.lua'
	no file '/home/zuzmo/.luarocks/share/lua/5.4/wx/init.lua'
	no file 'bin/linux/x64/clibs54/libwx.so'
	no file 'bin/linux/x64/clibs54/wx.so'
	no file '/usr/local/lib/lua/5.4/wx.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './wx.so'
	no file '/home/gabor/.luarocks/lib/lua/5.4/wx.so'
stack traceback:
	[C]: in function 'require'
	src/main.lua:48: in main chunk
	[C]: in ?

**Comment by ildar** [comment]
This is trivial: ZBS carries only 1 wx module for the Lua version it works
on.
If you need other wx modules, you can build' em yourself.

**Comment by ildar** [comment]
Also if you build wx module, you should check the Lua version in the build
script you're using.

**Comment by zuzmo** [comment]
> Also if you build wx module, you should check the Lua version in the build script you're using.

I checked, I've built with options "5.4 all". The build-linux.sh script made the proper libs in deps lib, and completed fine, but at startup it doesn't find wx ( wxlua ) module ( there is no package file in the lualibs ).
build output:
"[100%] Built target wxLuaModule
Install the project...
-- Install configuration: "MinSizeRel"
-- Installing: /home/zuzmo/projects/standby-network/ZeroBraneStudio/deps/lib/libwx.so
"

**Comment by zuzmo** [comment]
Oh, fine, i found /bin/linux/x64/clibs/libwx.so and copied into clibs54 folder, and worx$ thanx!
( I suggest to copy the libwx.so originally into the lua build version cfolder in the build script )

**Comment by pkulchenko** [comment]
@zuzmo, @ildar is correct in saying that the IDE only ships with one version of wxlua (built for Lua 5.1), even though it supports building and using other versions as well. The build scripts supplied with the IDE will put those modules in the correct places, so when you build with `5.4 all` options, it should do the right thing.

Having said that, I think there is a confusion that I'd like to address. The IDE itself runs on Lua 5.1 (or LuaJIT), but it allows running and debugging of scripts running any version of Lua (including Lua 5.4). There is really no need to use Lua 5.4 to run the IDE itself, but if you do want that, you only need to change the executable `lua` to `lua54` in zbstudio.sh file (assuming you built wxlua module for lua 5.4 along with Lua 5.4 executables); this has been added in 1c34b02bc.

> no file 'bin/linux/x64/clibs54/libwx.so'

This means that there was no wxlua library in the correct location, which is why the launch has failed.

**Comment by zuzmo** [comment]
@pkulchenko : I made a clean build from the ground ( first delete the bin and deps directory ). Somehow the bin directory was copied by the build script to the '../bin/'. So manually copied back to the install folder and woks fine. Thanks.

**Comment by pkulchenko** [comment]
> Somehow the bin directory was copied by the build script to the '../bin/'. 

I'll check the script. This could have happened if the build script was executed outside of the `build` folder. The expectation there is that it's executed from the `build` folder itself (in which case all the copied files will be in the correct location).

Thank you for the update!

**Comment by pkulchenko** [comment]
@zuzmo, I updated the build scripts, so that they can be used from outside of the build folder.

**Comment by zuzmo** [comment]
There is another minor mention on linux - there were a mark to a proper solution in the startup script, which works everywhere ( with bash ) with soft symlink, i didn`t pushed up .

zbstudio.sh>
----------------------------------------------------------
#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

CWD="$PWD" # save the current directory, as it's going to change

if [[ $(uname) == "Darwin" ]]; then
  # MacOS Sierra throws `error -10810` running with quarantined files even when explicitly allowed
  ATTR="com.apple.quarantine"
  (cd "$DIR"; \
   if [[ $( xattr -pl $ATTR zbstudio 2>&1 ) == $ATTR:* ]]; then xattr -rd $ATTR zbstudio bin; fi; \
   open zbstudio/ZeroBraneStudio.app --args -cwd "$CWD" "$@")
else
  case "$(uname -m)" in
    x86_64)  ARCH=x64;;
    armv7l)  ARCH=armhf;;
    aarch64) ARCH=aarch64;;
    *)       ARCH=x86;;
  esac
  (cd "$DIR"; bin/linux/$ARCH/lua src/main.lua zbstudio -cwd "$CWD" "$@") &
fi
-------------------------------

**Comment by pkulchenko** [comment]
> There is another minor mention on linux - there were a mark to a proper solution in the startup script, which works everywhere ( with bash ) with soft symlink, i didn`t pushed up

@zuzmo, there was something strange with this comment, as it came through in an email, but I don't see it in the ticket comments. What was a problem with soft symlink that you fixed?
