### ISSUE TITLE
Save all open documents shortcut

### ISSUE THREAD

**Issue by EngineerSmith** [pkulchenko/ZeroBraneStudio#1063]
Feature request, or if there's a shortcuts file I can add in the shortcut to it, please inform me.

Been using ZeroBraneStudio with LOVE and not having a shortcut to save all open files that have changes in them has been bugging me for a few months now. This is for ease of life/my workflow; instead of having to click on the save all documents button each time I want to run or close the program. 

Ctrl+Shift+S is what I unconsciously press when I'm editing a file from using other IDEs and text editors rather than just Ctrl+S

**Comment by EngineerSmith** [comment]
Adding `keymap[ID.SAVEALL] = "Ctrl-Shift-S"` to my `cfg/user.lua` solved my issue, odd that it isn't a default part of ZeroBrane

**Comment by pkulchenko** [comment]
@EngineerSmith, that's correct, there is no default shortcut for SaveAll, but you can assign your own, exactly like you did. `Ctrl-Shift-S` is already assigned to `View | Stack Window`, so it's staying there for historical reasons.
