### ISSUE TITLE
When will a new release appear ?

### ISSUE THREAD

**Issue by cata0309** [pkulchenko/ZeroBraneStudio#1064]
Hello ! I am struggling at installing it from source and I want the last version because of some visual bug that was fixed in the mean time ! I was wondering when a new release of Zerobrane will appear !

**Comment by pkulchenko** [comment]
@cata0309, you don't need to install the IDE from source, as it can be run from a cloned copy of the repository. Also, all the changes are in the Lua source files, so if you are interested in any change you'd like to apply to v1.90, you can simply copy over the Lua files (`src/` folder) and it should all work as expected.

Let me know if you still have a problem with it and I can guide you through the process; just include your OS information and details on how the IDE was installed.
