### ISSUE TITLE
Output tabwidth size

### ISSUE THREAD

**Issue by sigzero** [pkulchenko/ZeroBraneStudio#1065]
It doesn't seem to be possible to set the output tab size (new to Lua so maybe it's me).

`print("The Lua version is:",_VERSION)`

The output looks like this:

![output](https://user-images.githubusercontent.com/540937/86177416-9b638a80-baf4-11ea-9409-536b47b373bb.png)

I would like to be able to customize that spacing, if possible.

**Comment by pkulchenko** [comment]
@sigzero, indeed, it's not being explicitly set right now, so uses the default values. I'll consider adding a configuration setting for it.

**Comment by sigzero** [comment]
I did some investigating. This isn't the IDE at all. The Lua print statement is doing it. If I change the print statements to io.write statements the indentation is just what I would expect it to be.

I think this can be closed.

**Comment by pkulchenko** [comment]
@sigzero, thank you for the update. The Lua print statement is responsible for including `tab` in the output, but the IDE is responsible for showing a specific number of spaces for the tab. I still think that either the default should be smaller in the output or that it should be configurable.
