### ISSUE TITLE
In ZeroBraneStudio1.10, for a  lua fragment code, the result of running it is right, but debugging it generates issues 

### ISSUE THREAD

**Issue by WanChuanwei** [pkulchenko/ZeroBraneStudio#1066]
select lua 5.2 for Lua Interpreter.
a lua fragment code is as follows：
f1 = function()
    print("001")
    coroutine.yield()
   return 100
end
print(pcall(f1))
print(002)
if run it, the result maybe is:
false   attempt to yield from outside a coroutine
2
but if debug it using stepping into, when IDE executes the sentence  "coroutine.yield",  the debugging ends. I have tested another lua debugging software, it executes the sentence  "coroutine.yield" and executes "print(002)" next step, the result is same as running the upper lua fragment.

**Comment by pkulchenko** [comment]
@WanChuanwei, thank you for the report. This is a feature of how the debugger is working. See #801 for the details on when this message was introduced, the explanation, and a workaround.

**Comment by WanChuanwei** [comment]
Thank you very much for resolving the problem for me so quickly。
