### ISSUE TITLE
Request for nicer colors

### ISSUE THREAD

**Issue by Antix-Development** [pkulchenko/ZeroBraneStudio#1067]
Would it be possible to have more control over the rendering colors?

It would be nice if functions and variables could have their own colors, instead of just getting the default text color (which they seem to do currently).

**Comment by pkulchenko** [comment]
@Antix-Development, yes, all these colors can be configured and are documented in this section: https://studio.zerobrane.com/doc-styles-color-schemes. For example, putting the following fragment into the config file will make the function calls red:

```lua
styles.indicator.fncall = {st = wxstc.wxSTC_INDIC_TEXTFORE, fg = {240,0,0}}
editor.showfncall = true -- enable styling for function calls
```

The variables of different types need to be configured individually (local, global, and the rest, as documented).

Note that there is an open issue with function calls on table fields (#957).

**Comment by Antix-Development** [comment]
Awesome, thanks for explaining that Paul. I'll start messing about with it

**Comment by pkulchenko** [comment]
@Antix-Development, FYI: the issue in #957 with styling of function calls on fields should be fixed.
