### ISSUE TITLE
LXQt: toolbar height too small

### ISSUE THREAD

**Issue by fbosio** [pkulchenko/ZeroBraneStudio#1068]
# Bug
## Information
   * Operating system: Lubuntu 19.10
      - desktop environment: LXQt 0.14.1
   * ZeroBrane Studio devel; MobDebug 0.706
      - commit 847d4022be780791c83614a7d3ae0857e16f29cf
      - wxWidgets 3.1.4
   * Empty config file
   * No plugins

## How to reproduce this issue
Just run `zbstudio.sh`.

![Screenshot of the graphic issue, the toolbar height looks too small](https://user-images.githubusercontent.com/31016649/87234057-a98e9200-c3a3-11ea-8742-a0486fd141a7.png)

The toolbar height is too small, in such a way that the icons cannot be seen
completely.

## Workaround
Run the following in a shell
```bash
echo 'return {
  onIdleOnce = function(self, app)
    local uimgr = ide:GetUIManager()
    local pane = uimgr:GetPane("toolbar")

    pane.best_size:SetHeight(26)
    uimgr:Update()
  end
}' > ~/.zbstudio/packages/lxqttoolbarworkaround.lua
```

Then, close and open the IDE again.
The toolbar should look well from now on.

## Note
I had a look at the ZeroBrain Studio source code, and I think that something is
going on with the `SettingsRestoreView()` function, called in `main`, but I
don't know exactly what.

**Comment by pkulchenko** [comment]
@fbosio, thank you for the detailed report! I have a couple of questions:

1. How did it get into this situation? Is it reproducible?
2. Is the issue fixed if you use `View | Default Layout`?

>  I think that something is going on with the SettingsRestoreView() function, called in main, but I don't know exactly what.

If you can reproduce the issue, can you add a couple of `ide:Print` commands around 442 in src/editor/settings.lua to show `besth` value, as there is already a workaround for a similar (the same?) problem, but it's not hardcoded to any particular height. I'm curious as to why it may not be catching your case. Thank you.

**Comment by fbosio** [comment]
> @fbosio, thank you for the detailed report!

You're welcome! I really like this project, specially for game development with Löve2D :)
(Regarding that, thank you for [accepting my pull request](https://github.com/pkulchenko/ZeroBranePackage/pull/87)).

> 1\. How did it get into this situation? Is it reproducible?

I just cloned the repository and ran the shell script, and the toolbar showed up like that.
This graphic issue is persistent, if you close ZeroBrane Studio and open it again, the toolbar will look equally thin.

Here's something more, one may

1. hide the toolbar by deselecting `View > Tool Bar`
1. close the IDE
1. open it again
1. show the toolbar by selecting `View > Tool Bar`

and it will look just fine. But that doesn't fix the thing, because the toolbar will be shown the wrong way again if you close and open the IDE once more. Actually, that's why I made the workaround in the first place.

> 2\. Is the issue fixed if you use `View | Default Layout`?

Yes, but temporarily. The issue appears again when I close and open the IDE, like above.

> If you can reproduce the issue, can you add a couple of `ide:Print` commands around 442 in src/editor/settings.lua to show `besth` value, as there is already a workaround for a similar (the same?) problem, but it's not hardcoded to any particular height. I'm curious as to why it may not be catching your case. Thank you.

Glad to read that! And sure, I removed my workaround, added an `ide:Print(besth)` in `src/editor/settings.lua/`, line 443, and here's the output when I run `zbstudio.sh`
```
The API file must be located in a subdirectory of the API directory.
26
```
It seems that the layout engine detects the `besth` value correctly.
However, when I run
```lua
ide:GetUIManager():GetPane("toolbar").best_size:GetHeight()
```
in the Local console, I get
```lua
10
```
I found that the `uimgrlayout` settings override this value on line 445,
because I added an
```lua
ide:Print(string.match(layout, "besth=[^;]+;"))
```
in line 433 and got
```lua
besth=10;
```
but I can't find exactly where that's happening right now.
Does this help?

**Comment by fbosio** [comment]
# Distributions
I repeated my [original test](https://github.com/pkulchenko/ZeroBraneStudio/issues/1068#issue-655282108) in several virtual machines with differente Ubuntu-based distributions, **they all look fine, except Lubuntu.**
So the issue is clearly caused by **something going on with LXQt.**

## Results
- Ubuntu 20.04
    - Desktop environment: GNOME 3.36.1
    - It's OK
- Xubuntu 20.04
    - Desktop environment: XFCE 4.14
    - It's OK
- Lubuntu 20.04
    - Desktop environment: LXQt 0.14.1
    - **the only one that makes the IDE look wrong**
- Kubuntu 20.04
    - Desktop environment: KDE 5.18.4
    - It's OK

# Outputs
So I made a few prints and found that, whatever is causing this issue, is doing it _after_ the `onAppLoad` event. I looked a bit deeper for event callbacks and found the line 27 of `src/editor/gui.lua`.
```lua
toolbar:BestSize(event:GetSize():GetWidth(), ide:GetToolBar():GetClientSize():GetHeight())
```
I added an `ide:Print(ide:GetToolBar():GetClientSize():GetHeight())` and got this
```
26
26
1
1
10
```
Hence, the `wxSizeEvent` gets here, at some point, a window 'client height' of `1`. I added the same print command in Ubuntu, whose desktop environment is GNOME, and the 'client height' is always `26`. My hypothesis is that the desktop environment, _LXQt, is giving the wrong value to wxWidgets_. So maybe this issue belongs to them!

Anyway, thank you, @pkulchenko for your attention!

**Comment by pkulchenko** [comment]
@fbosio, thank for you the detailed analysis! It does look like the issue is with LXQt, as I couldn't reproduce it on my Ubuntu image.

It may be possible to add a workaround though. What if you replace that line 27 with something like this:

```lua
if ide:GetToolBar():GetClientSize():GetHeight() > 1 then
  toolbar:BestSize(event:GetSize():GetWidth(), ide:GetToolBar():GetClientSize():GetHeight())
```

Does it work better? In fact, it should probably be >= 16, which is the minimal icon size anyway.

**Comment by fbosio** [comment]
Nice hack, works like a charm!
