### ISSUE TITLE
MacOS darkmode

### ISSUE THREAD

**Issue by bubach** [pkulchenko/ZeroBraneStudio#1071]
Is there any way for me that off inside the app?  Right now my options are to go light-OS wide - or give up. The dark theme isn't usable.. :/

**Comment by pkulchenko** [comment]
@bubach, you can set a color theme (a light one, for example) and it will stay selected even when the dark mode is set, but it's not going to change the color of the menu, the borders and some other elements, as it's controlled by the underlying toolkit (wxwidgets) and can't be changed in the IDE.

What's not usable in the current theme? Most of the colors can be adjusted, except those I just listed.

**Comment by pkulchenko** [comment]
@bubach, feel free to reopen if you have additional information. I'd be interested to know what specifically is not usable in the dark theme.
