### ISSUE TITLE
How to update API file for corona SDK

### ISSUE THREAD

**Issue by b-and-p** [pkulchenko/ZeroBraneStudio#1073]
Hi, I would like to submit an updated API for corona SDK. Do I need to fork the project first? Sorry, first time attempting to collaborate on GitHub.

**Comment by pkulchenko** [comment]
@b-and-p, yes, you'd need to fork the project and create a pull request with your changes.

Before you do that though, where are you getting the updated SDK documentation from? api/lua/corona.lua file already includes the script that processes `CoronaSDK-APIDOC` file and generates the api structure recognizes by the IDE. Is that the process you are using?

**Comment by b-and-p** [comment]
Yes, I ran your script on current API markdown docs.

**Comment by pkulchenko** [comment]
Cool; you can submit the pull request if you want and I'll merge the changes. Github has instructions here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request. Just make sure you create a separate branch to make a pull request from. What's the source of the corona docs?

**Comment by b-and-p** [comment]
I got the docs here: https://github.com/coronalabs/corona-docs

**Comment by pkulchenko** [comment]
@b-and-p, merged #1074; thanks!
