### ISSUE TITLE
Add support for Lua 5.4

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#1075]
Current work is in the lua54 branch: https://github.com/pkulchenko/ZeroBraneStudio/tree/lua54.

- Build Lua 5.4 for all supported platforms
- Build lpeg and luasec for Lua 5.4 for all supported platforms
- Build luasocket 3.1.0 for all supported platforms
- Build lfs 1.8.0 for all supported platforms

**Comment by ShalokShalom** [comment]
The GitHub README mentions 5.4 support
The homepage omits that
What is correct?

**Comment by pkulchenko** [comment]
The IDE has been tested with Lua 5.4, so it supports it for both running and debugging, but it doesn't provide (yet) a packaged version along with required modules, which is why the homepage is not updated for Lua 5.4 support. This ticket covers all Lua 5.4-related work.

**Comment by stopsopa** [comment]
Attempt to configure debugger for Lua 5.4 with @pkulchenko  help, but still no success:
https://stackoverflow.com/a/76548375

**Comment by pkulchenko** [comment]
Lua 5.4 has been added for Windows and Linux (along with luasec, luasocket, lpeg and lfs).

luasocket has been updated to v3.1.0 for all versions on Windows and Linux.
lfs has been updated to v1.8.0 for all versions on Windows and Linux.

**Comment by pkulchenko** [comment]
Closing as all these changes have been merged into master and released as v2.0.
