### ISSUE TITLE
The IDE required me another useless "end" in my code, eventhough it worked completely fine

### ISSUE THREAD

**Issue by BlaztOne** [pkulchenko/ZeroBraneStudio#1076]
![Error](https://user-images.githubusercontent.com/69741876/90325779-2831ad00-dfaa-11ea-86b6-1c8b749cf0c5.png)

I tried to add some "end" but the IDE said that "end" wasn't needed

![image](https://user-images.githubusercontent.com/69741876/90325794-64fda400-dfaa-11ea-9117-68da64d46049.png)

This function works completely fine after I print the result out

![image](https://user-images.githubusercontent.com/69741876/90325789-4697a880-dfaa-11ea-999f-83d64bcfd080.png)

**Comment by ildar** [comment]
1. Why'd you want the extra end?
2. Lua doesn't require compilation. What does Analyse tell you?
3. If you need some "novice" type help, would you ask at a chat? Guess irc
channels #lua and https://studio.zerobrane.com/community are best choices
IMHO

**Comment by pkulchenko** [comment]
@BlaztOne, I'm closing this issue, but feel free to re-open if you have answers to @ildar's questions and any additional information.
