### ISSUE TITLE
Local console calculate error

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#1078]
`tonumber('2RRVTHNXTR',36)` in Local console should get `281,474,976,710,655(0xffffffffffff)`, but actually get `4294967295`.

When in Remote console (runtime), result is correct.
![image](https://user-images.githubusercontent.com/7419030/92540267-9b130880-f276-11ea-84c2-005350016c99.png)

**Comment by pkulchenko** [comment]
@robertlzj, I don't think there is any issue in the IDE; this is the value that is being returned by LuaJIT (2.0.5).

**Comment by robertlzj** [comment]
Yes, it's not an issue. Every act has its consequence.
But, I think it's counter intuitive, so may hint user when calculate distortion.

**Comment by pkulchenko** [comment]
Agree; it should be addressed in #493 and #490.
