### ISSUE TITLE
Empty stack window in Lua 5.1

### ISSUE THREAD

**Issue by Miksser** [pkulchenko/ZeroBraneStudio#1084]
Hey. I am using Windows 10 and installing Luaforwinodws with Lua 5.1.4.

When I try to use the debugger, it doesn't show me anything in the stack trace. At the same time, the breakpoints are working properly. I read the documentation, tried to change the cpath and path variables, but it didn't help.

Say please, can this be fixed somehow?

[Open image](https://user-images.githubusercontent.com/27306203/96932097-04697680-14c7-11eb-8242-cfe662d49ef8.png)

**Comment by pkulchenko** [comment]
@Miksser, what do you expect to see in the Stack window? I does show that the control is on line 5 in the main script, which is what you'd expect, no?

**Comment by Miksser** [comment]
sorry for long waiting. I expect to see variables and ENV like in lua 5.2 debugger. In Lua 5.1, the values of all variables are hidden =(
[lua 5.1](https://user-images.githubusercontent.com/27306203/97484869-62380b80-196a-11eb-8f0a-6d91d6c1ff47.png)
[lua 5.2](https://user-images.githubusercontent.com/27306203/97484937-767c0880-196a-11eb-8508-4f58642a0786.png)

**Comment by pkulchenko** [comment]
It's because those are global variable and are not part of the stack; only upvalues and local variables are. `_ENV` is part of the stack for Lua 5.2, but _G is not for Lua 5.1, hence the difference. You can add those values you are interested in to Watches to monitor.
