### ISSUE TITLE
Ability to use on an iPad/tablet ?

### ISSUE THREAD

**Issue by nodecentral** [pkulchenko/ZeroBraneStudio#1088]
Hi

Perhaps a long shot, but is there a way to use this from an iPad ?  I’ve looked at VMs and then using VNC, but they are only as good as the VNC client - does anyone have an idea how you would go about making something feel more native on a tablet ?

**Comment by pkulchenko** [comment]
@nodecentral. this requires iOS support in wxwidgets (as the IDE depends on wxwidgets for its GUI cross-platform support), but I don't think it's at the level that allows full support of the features needed/used in the IDE. I may revisit this when the support improves, but at this time I don't think it's going to work unfortunately.
