### ISSUE TITLE
IDE doesn't obey my gtk theme

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#1089]
ZeroBrane studio doesn't obey my gtk theme 
![image](https://user-images.githubusercontent.com/2453707/100050732-ed23ee80-2dce-11eb-88c5-c063e4510dc6.png)

**Comment by ildar** [comment]
Check your GTK3 theme. Also environment info could be helpful : distro, DE?

**Comment by Shadowblitz16** [comment]
I am on zorin os core 15.3
And the distro uses its own themes

**Comment by pkulchenko** [comment]
There is not much I can do, as those colors that GUI is using are coming from whatever reported by GTK3 and there is no way to modify them (all) unfortunately. I've open a ticket some time ago that allows better configuration, but the changes haven't been implemented yet (https://trac.wxwidgets.org/ticket/18614).

**Comment by Shadowblitz16** [comment]
@pkulchenko can we reopen this on a later date?

**Comment by pkulchenko** [comment]
I'm not sure if there is a bug with the colors that wxwidgets is getting, but we can definitely revisit this when the ticket I referenced is implemented and the binaries in the IDE are refreshed to include that logic.

You can still configure the colors in the IDE, just not all of the elements (like menus, borders, tabs, and few other things).

**Comment by Shadowblitz16** [comment]
I thought wxwidgets used gtk on linux cocoa on mac and win32 in windows?
I don't see how its not using my gtk theme

**Comment by pkulchenko** [comment]
It's not clear from the screenshot what happens. Can you run the following commands in the Console and report the results back:

```lua
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_3DFACE):GetAsString()
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_CAPTIONTEXT):GetAsString()
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_INACTIVECAPTIONTEXT):GetAsString()
```

You can also check the discussion in #1024, which dealt with a similar issue. Could you include a screenshot that shows not just the IDE, but also some other application that uses the correct theme colors?

**Comment by Shadowblitz16** [comment]
I ran the commands and they print in order..
```
"white"
"black"
"black"
```

**Comment by pkulchenko** [comment]
So it looks like the colors are correct and somewhat correspond to the colors in other apps (judging by the screenshots). You may argue that the style is different, but picking colors between different managers is a crude method, so I guess this is the best that wxwidgets can do.

If you are talking about tab bar gradient that is present in the IDE, but is not present in the other apps, it can be adjusted (and I've been considering making it configurable). You may try setting `wxaui.wxAuiGenericTabArt = nil` in the config, which will reset the tabbar style.

**Comment by Shadowblitz16** [comment]
@pkulchenko maybe it's time to switch to a flat theme like vs code?
![image](https://user-images.githubusercontent.com/2453707/179902170-778f9043-8434-45d9-89ae-7190bb28e21a.png)
I'm on kde neon now and it still looks awful.
What ui are you using?
