### ISSUE TITLE
Rename error

### ISSUE THREAD

**Issue by qgenesist** [pkulchenko/ZeroBraneStudio#1095]
windows 10 64 bit
Lua 5.1
ZB 1.80 with Analyzer #1093 patch applied

situation is, I have the tree in the left pane, I have several tabs open on the editor, let the current active tab be fred.fh_lua
I go to the tree and rename it fred0.fh_lua
the error will loop until I cancel the windows, and ZB exits. It does appear to rename the file.

*NB: it does not do this in EVERY CASE, it seems random (obviously not, but some confluence of eventsj.

![Untitled](https://user-images.githubusercontent.com/32033615/101404137-d1731a80-389b-11eb-8b43-7206a3716e69.png)

--[[--
  Use this file to specify **System** preferences.
  Review [examples](+C:\Users\user\Downloads\ZeroBraneStudio\cfg\user-sample.lua) or check [online documentation](http://studio.zerobrane.com/documentation.html) for details.
--]]--

autoanalyzer = true
staticanalyzer.infervalue = true
filetree.showchanges = true

console.fontname = 'Courier New'
console.fontsize = 10
default.extension = 'fh_lua'
local luaspec = ide.specs.lua
-- luaspec.exts[#luaspec.exts + 1] = 'fh_lua'
editor.fontname = 'Courier New'
editor.fontsize = 12
editor.specmap.fh_lua = 'fh_lua'
editor.specmap.wlua = 'fh_lua'

editor.autoreload = true
editor.tabwidth = 2
editor.smartindent = true
editor.indentguide = wxstc.wxSTC_IV_LOOKBOTH 
editor.wrapindentmode = wxstc.wxSTC_WRAPINDENT_INDENT

--[[--
  Use this file to specify **User** preferences.
  Review [examples](+C:\ProgramData\ZeroBraneStudio\cfg\user-sample.lua) or check [online documentation](http://studio.zerobrane.com/documentation.html) for details.
--]]--
autoanalyzer = true
staticanalyzer.infervalue = true 
console.fontname = 'Courier New'
console.fontsize = 10
default.extension = 'lua'
filetree.showchanges = true

local luaspec = ide.specs.lua
luaspec.exts[#luaspec.exts + 1] = 'fh_lua'

editor.autoreload = true
editor.fontname = 'Courier New'
editor.fontsize = 12
editor.specmap.fh_lua = 'lua'
editor.specmap.wlua = 'lua'

editor.tabwidth = 2
editor.smartindent = true
editor.indentguide = wxstc.wxSTC_IV_LOOKBOTH --prf
editor.wrapindentmode = wxstc.wxSTC_WRAPINDENT_INDENT --prf

**Comment by pkulchenko** [comment]
Can you retest with 1.90 (which is the latest released version)? I think this issue has been fixed long time ago.

Is there any reason you continue using 1.80?

**Comment by qgenesist** [comment]
W10 64 bit, ZB 1.90 just refreshed before I ran this today 29 Dec 2020:
--[[--
  Use this file to specify **User** preferences.
  Review [examples](+C:\ProgramData\ZeroBraneStudio\cfg\user-sample.lua) or check [online documentation](http://studio.zerobrane.com/documentation.html) for details.
--]]--
autoanalyzer = true
staticanalyzer.infervalue = true 
console.fontname = 'Courier New'
console.fontsize = 10
default.extension = 'lua'
filetree.showchanges = true

local luaspec = ide.specs.lua
luaspec.exts[#luaspec.exts + 1] = 'fh_lua'

ide:GetEditor():SetViewEOL(1)
ide:GetEditor():ConvertEOLs(ide:GetEditor():GetEOLMode())
editor.autoreload = true
editor.fontname = 'Courier New'
editor.fontsize = 12
editor.specmap.fh_lua = 'lua'
editor.specmap.wlua = 'lua'

editor.tabwidth = 2
editor.smartindent = true
editor.indentguide = wxstc.wxSTC_IV_LOOKBOTH 
editor.wrapindentmode = wxstc.wxSTC_WRAPINDENT_INDENT

sorry I took so long to get back to this Paul.  I have spent some time on the code and distilled the problem to this:


  local _fp = rtvpath(_pth)
  local _err, _etxt = os.rename(_fp, _fp)
  if _err == nil then
    _etxt = _etxt:gsub('.-:', '')
    if _etxt == 'Permission denied' 
    and _pth == '*temp' then
      break
      -- 'No such file or directory'
      --  return _fp, _etxt
    end
  end
![Untitled](https://user-images.githubusercontent.com/32033615/103287677-bc743d80-49a8-11eb-944d-57214cc98da7.png)

**Comment by pkulchenko** [comment]
@qgenesist, I pushed a fix for this issue, but it's not related to rename, it's only related to the analyzer (similar to the issue in #1093).

Closing...
