### ISSUE TITLE
"Save As" causes wxLUA error message box pop-up and ZBS application closes

### ISSUE THREAD

**Issue by abramesd** [pkulchenko/ZeroBraneStudio#1096]
I just installed the lasted version 1.90 and when I try to perform a "Save As" I get a wxLUA Running Error.  I have attached screen captures and other information.  This is my first submission so please let me know if I miss providing any information you need.

Windows Environment
Workstation PC running Windows 10 Pro 2020
AMD(FX)-9590 8-core Processor 4.51 GHz
32 GB RAM
64-bit OS

ZeroBrane Studio v1.90
No "user.lua" files

![WindowsPC-Environment](https://user-images.githubusercontent.com/46332931/101918476-683f2000-3b97-11eb-8c9a-8fe43345366d.jpg)
![ZBS-wxLua-runtime-error](https://user-images.githubusercontent.com/46332931/101918534-768d3c00-3b97-11eb-8ad2-bdf81a670172.jpg)
![ZBS-About-Box](https://user-images.githubusercontent.com/46332931/101918536-768d3c00-3b97-11eb-8504-61f50992cafa.jpg)

**Comment by pkulchenko** [comment]
@abramesd, thank you for the report. This appears to be fixed in #1077, so you can get the latest master branch, which already includes the fix (or apply the patch from that ticket).
