### ISSUE TITLE
Tab background color doesn't change with dark theme

### ISSUE THREAD

**Issue by steveRoll-git** [pkulchenko/ZeroBraneStudio#1105]
I'm using xfce and I set a dark theme (specifically "Adwaita-dark") and ZeroBrane Studio looks mostly fine with it, except for the background of tabs:
![image](https://user-images.githubusercontent.com/40004112/109056737-81149780-76e9-11eb-9828-0dba689fad21.png)
This background is a gradient from one color to another, and it seems that the bottom color is not affected by the theme of the WM, and stays gray.
I know this might be an issue with wxwidgets, but I want to know if this can be configured somehow.

**Comment by pkulchenko** [comment]
Yes, this is the property of the GenericTabArt in wxwidgets. You may try changing to Simple or Default tabart by adding the following to the IDE config (use one of the lines):

```
wxaui.wxAuiGenericTabArt = wxaui.wxAuiSimpleTabArt
wxaui.wxAuiGenericTabArt = wxaui.wxAuiDefaultTabArt
```

See [this comment](https://github.com/pkulchenko/ZeroBraneStudio/issues/1024#issuecomment-643791300) (and the follow-up) for the previous discussion.
