### ISSUE TITLE
Windows 10 DARK theme not applying to ZeroBrane Studio 1.90

### ISSUE THREAD

**Issue by aPlanetaryCitizen** [pkulchenko/ZeroBraneStudio#1106]
I saw a few people already having this issue. My Windows 10 dark mode works everywhere but in ZeroBrane.
Checking the colors:

```
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_3DFACE):GetAsString()
"rgb(240, 240, 240)"
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_CAPTIONTEXT):GetAsString()
"black"
wx.wxSystemSettings.GetColour(wx.wxSYS_COLOUR_INACTIVECAPTIONTEXT):GetAsString()
"black"
```
exactly like dexmar here #1101
Any solution to this?

**Comment by pkulchenko** [comment]
as @dexmar noted in #1101: "evidently wxWidgets for Windows is built using Win32 API which is not covered by Microsoft's theming system so as such is not currently able to be themed by the Dark Theme setting in Windows. This can be seen in other Win32 programs: notepad, wordpad, device manager, etc. As that is the case there is no further need to spend any time on this thread". It doesn't seem like there is anything I can do until it's changed in wxwidgets and the binaries are recompiled for the IDE.

Also, there is no need to open a new ticket, as you can just add your comment to the existing ticket that already covers the same topic in detail (even a closed one).
