### ISSUE TITLE
error on find with no active window

### ISSUE THREAD

**Issue by qgenesist** [pkulchenko/ZeroBraneStudio#1107]
![zbERR](https://user-images.githubusercontent.com/32033615/109957261-5064cd00-7caa-11eb-8d6f-f04b6e6884f8.png)
if  find in THIS file is done, and I close that file (not having an active editor file). and then start deleting letters from the find box this error occurs.

find in files works correctly in the same circumstance.

an additional question, why won't ZBS load, work with, and save lua scripts that begin with a $ ?

**Comment by pkulchenko** [comment]
@qgenesist, thank you for the report; should be fixed now.

> why won't ZBS load, work with, and save lua scripts that begin with a $ ?

This is a tricky one; for some reason, the normalization function removes a slash before `$` (at least on Windows). You can try the following in the Console:

```
path = wx.wxFileName("foo/$bar"); path:Normalize(); return path:GetFullPath()
```

No matter what I try, the slash before $ is removed, which produces incorrect path (`foo$bar` in this case).

I can probably "fix" it by prepending the slash back, but it's a bit hackish.

**Comment by pkulchenko** [comment]
@qgenesist, I opened #1108 to deal with the names with $ in them, as it turned out to be an interesting (and separate) issue.
