### ISSUE TITLE
Request: Disable message "Couldn't activate file '………' for debugging; continuing without it." by filter

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1110]
We are developing an application in an embedded device.

Application is located in `/opt/appl` in the device (which maps to `/opt/appl` in current working directory of ZBS)  and remote debugging is really working great. Thank you for this, it's a great help.

But now, if  the application requires other files, e.g `require"libs.utils"`, which is located at `/opt/lua/libs/utils.lua` in the device and is NOT present in ZBS working directory, ZBS shows above error message.

Can we provide a filter (either positive or negative list), which directories to include or exclude from `editor.autoactivate` ?

**Comment by jjvbsag** [comment]
Found out by myself :smile:  `onDebuggerPreActivate` provides required interface. 
**Question**: Is there somewhere a documentation for all `PackageEventHandle`rs giving more information than just the names in `package/sample.lua`

**Comment by pkulchenko** [comment]
> Is there somewhere a documentation for all PackageEventHandlers giving more information than just the names in package/sample.lua

I don't think so, other than implementations in various plugins, as they are all based on that plugin API events described in sample.lua. I can tell you that sample.lua lists all the events that are supported in the codebase and describes parameters as well as some results that will abort subsequent processing (by returning `false` from the event handler).

What other information would you need?

**Comment by jjvbsag** [comment]
Ok, packages information is another issue, I will close this one, because  `onDebuggerPreActivate` solves my problem. Thanks

**Comment by pkulchenko** [comment]
Sounds good; thanks for the update!
