### ISSUE TITLE
Question: Trim EndOfLine on Save ?

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1112]
Is there an option (or a package) to get the following:

On Save File before save is done

- trailing whitespace on line ends are removed
- last line is checked to have an end-of-line terminator

**Comment by pkulchenko** [comment]
@jjvbsag, there is [striptrailingwhitespace package](https://github.com/pkulchenko/ZeroBranePackage/blob/master/striptrailingwhitespace.lua) that does the first thing. You can probably extend it to take care of the second one.
