### ISSUE TITLE
Turning off auto-wrap will cause problems with auto-completion

### ISSUE THREAD

**Issue by UradaSources** [pkulchenko/ZeroBraneStudio#1127]
After making editor.usewrap = fasle in the configuration file, auto-completion will become insensitive. Sometimes it will only read the first character in the word I entered. I tried to delete all plugins and other configurations. Still the same.

It seems to read only the first 2 characters I entered continuously
![image](https://user-images.githubusercontent.com/42081753/136529458-e93ac8d4-75f0-454b-a8b2-fbb5d4f4317f.png)

My version is 1.9, and the context is love2d

**Comment by pkulchenko** [comment]
No problem; nothing to apologize for. Thank you for confirming the fix!
