### ISSUE TITLE
Variable arguments not working as properly

### ISSUE THREAD

**Issue by Kindi-Equinox** [pkulchenko/ZeroBraneStudio#1128]
```
local function func(...)
for k, v in pairs(arg) do
print(k, v)
end
end

func(1,2,3,4,5)
```

Doesn't work. It gives out negative indices and unrelated values.

**Comment by pkulchenko** [comment]
This is not a problem with the IDE. You should be using `{...}` instead of `arg`, as `arg` usage for vararg functions has been deprecated since Lua 5.1: https://www.lua.org/manual/5.1/manual.html#7.1.
