### ISSUE TITLE
Is it possible to style other instances of the current selection?

### ISSUE THREAD

**Issue by jaykyburz** [pkulchenko/ZeroBraneStudio#1131]
For example if I have the word "self" is selected, all instance of self in the current file have an "indicator" applied. 

I have found it useful for quickly spotting typos in Sublime Text.

**Comment by moteus** [comment]
Its possible with plugin
I use this one [findtext.lua](https://github.com/moteus/zbs-package/blob/master/zbstudio/packages/findtext.lua).
This is port from one developed for SciTE with some additions
It looks like
![image](https://user-images.githubusercontent.com/1804306/148082103-784167ca-3d3c-426a-a7f9-e782bd33e8bf.png)

**Comment by pkulchenko** [comment]
@jaykyburz, as @moteus wrote, there are plugins that do this. Use the one he referenced or the one in the package repository ([highlightselected](https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua)).

**Comment by jaykyburz** [comment]
perfect thanks folks.
