### ISSUE TITLE
Keybindings for font scaling

### ISSUE THREAD

**Issue by jaykyburz** [pkulchenko/ZeroBraneStudio#1132]
A tiny issue I just noticed. 

The keybindings for scaling the font are control - and control + but in many popular apps, including browsers and other text editors they are bound to control - and control = so that you don't have to hold the shift key. 

Sorry if its too minor an issue.

**Comment by jaykyburz** [comment]
On on KDE. But to be clear. Ctrl - and Control + work. But every other app I can find is the short cut is control - and control = (so that you don't have to hold shift to get the +)

**Comment by jjvbsag** [comment]
I believe, this also is locale- and system- specific.
For me (linux, german keyboard, where '+' and '-' needs no shift), [Ctrl]+[+] and [Ctrl]+[-] is working perfect in ALL applications, I use including Firefox, Thunderbird, Terminal, Thunar, Scite (only numeric keypad), Krita, ZBS and many more.
Jm2c

**Comment by jaykyburz** [comment]
Thought I had better close out this issue to clean up some of the clutter.

**Comment by pkulchenko** [comment]
Sounds good; thanks @jaykyburz!
