### ISSUE TITLE
source sort error

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#1140]
for sample code
```lua
[[
	1
]]
```
seems sort get complete error on other case, I pull latest already?
sort will get![image](https://user-images.githubusercontent.com/7419030/159603430-41f7cbc5-0dd3-476a-ac4a-3a3beaab000f.png)

**Comment by pkulchenko** [comment]
Why is that wrong? What would you expect? It just sorts the line alphabetically and spaces are before brackets.

**Comment by robertlzj** [comment]
Sorry, I mistook 🤣
