### ISSUE TITLE
fold error in [[..]]

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#1141]
![image](https://user-images.githubusercontent.com/7419030/159603610-e13c3c2b-1724-4d5b-9d26-67e63ed871e5.png)

**Comment by pkulchenko** [comment]
Unfortunately there is nothing I can do about this, as it's controlled by Scintilla, so needs to be reported upstream (if it's not already fixed in subsequent versions; wxwidgets may be incompatible though, as they have different C++ version dependencies).
