### ISSUE TITLE
Update downloadable versions

### ISSUE THREAD

**Issue by hector-vido** [pkulchenko/ZeroBraneStudio#1145]
Is there any chance to update the downloadable versions?

I am saying this because we need to download the repository from **master** to debug openresty modules.

**Comment by pkulchenko** [comment]
Updated the master branch with the new version of mobdebug, which should address the issue.

**Comment by hector-vido** [comment]
Hi @pkulchenko thank you!

I was already debbuging, with no problems, but with a fresh cloned repository. I am concerned with the people that wants to download from https://studio.zerobrane.com/download.
