### ISSUE TITLE
table.move, string.pack, string.unpack are not syntax colored correctly...

### ISSUE THREAD

**Issue by martinfabian** [pkulchenko/ZeroBraneStudio#1159]
The identifiers table.move, string.pack, and string.unpack are not syntax colored in the same way as the other table and string methods. I copied the keywords from spec/lua.lua  (lines 253-287) into ZBS editor, and this is what I see at the end:
![image](https://user-images.githubusercontent.com/699100/216786315-81c59d94-c3f8-40bb-ad04-b582a7ef42ac.png)

The reason for this seems to be that in spec/lua.lua, these identifiers are followed by commas (see line 290 of  https://github.com/pkulchenko/ZeroBraneStudio/blob/master/spec/lua.lua). If the commas are removed, the coloring becomes as expected.

**Comment by pkulchenko** [comment]
Good catch; thank you for the report! Should be fixed now.
