### ISSUE TITLE
The search box should accept Ctrl+A to select all text...

### ISSUE THREAD

**Issue by martinfabian** [pkulchenko/ZeroBraneStudio#1165]
Hitting Ctrl+F opens the search box, and allows to type text to search for. This is as expected.

However, when the search box has focus, typing Ctrl+A just sounds an alarm. I expected the current search string to be selected so that I can replace it by typing something else. At least on Windows, this is the expected behavior.

Could we have that, please?
Thank you
// MVHMF

**Comment by pkulchenko** [comment]
@martinfabian, thank you for the report. I'd expect it to be fixed in the commit I just pushed, but if it still doesn't work for you, let me know.
