### ISSUE TITLE
Zerobrane crash when renaming a file to a name that already exists

### ISSUE THREAD

**Issue by PetervanderVossen** [pkulchenko/ZeroBraneStudio#1169]
PC runs Microsoft Windows 10 Home, Version 10.0.19045 Build 19045
ZeroBrane Studio (2.01; MobDebug 0.805)

When renaming a file (in the Project pane) to a name that already exists, the IDE will crash.
In the example here I tried to rename **func1.lua** to **complex.lua**, not realizing that file already existed.

![zerobrane_issue1a](https://github.com/pkulchenko/ZeroBraneStudio/assets/52909441/e16808d7-35ba-4a1b-9ce1-3ba74d6cd448)

**Comment by pkulchenko** [comment]
@PetervanderVossen, thank you for the report; should be fixed later today.

**Comment by pkulchenko** [comment]
@PetervanderVossen, should be fixed now.

**Comment by PetervanderVossen** [comment]
Wow, tops guys! Many thanks!
Cheers, Peter.
