### ISSUE TITLE
ZBS stops while debugging

### ISSUE THREAD

**Issue by fireymerlin** [pkulchenko/ZeroBraneStudio#1176]
I will be debugging a program.  I'm usually at a break point looking at values in the "watch" window.
ZBS's window will close.
No error message.
This started in late February or early March of 2024.  I was using ZBS version 1.9 when this started.
I have updated to ZBS version 2.01

**Comment by pkulchenko** [comment]
@fireymerlin, is it reproducible on a small file and specific values in the "watch" window? Do you see this on all attempts for that breakpoint and the content of the watch window?

**Comment by fireymerlin** [comment]
I cannot consistently reproduce this.
This particular error always happens at a break point.
I just completed removed "lua for windows" and ZBS including all traces I could find on c: and the registry.  I used a registry cleaning tool (norton nutilities).
I'm going to reload everything and will report if ticket or the other ticket's errors happen.

**Comment by fireymerlin** [comment]
Please close this ticket.
My Dell PC is having hardware issues with the motherboard or harddrive.

**Comment by pkulchenko** [comment]
Closing; thank you for the update!
