### ISSUE TITLE
ZBS error while closing child windows

### ISSUE THREAD

**Issue by fireymerlin** [pkulchenko/ZeroBraneStudio#1177]
I had 5 or more lua files open and two text files.
I was closing some of the lua and the text files by clicking the X in the tab tittle.

Here is the text from the error popup window:
EwxLua Runtime Error

X

X

Lua: Error while running chunk
src/editor/editor.lua:614: attempt to call method
'IndicatorFillRange' (a nil value)
stack traceback:
src/editor/editor.lua:614: in function 'IndicateOne'
src/editor/editor.lua:641: in function
'IndicateSymbols'
src/editor/editor.lua:486: in function
'IndicatelfNeeded'
src/editor/commands.lua:885: in function
<src/editor/commands.lua:878>
[C]: at Ox02859894
sro/main.lua:893: in main chunk
[string "Initializer']:1: in function < [string
"Initializer"]:1>
[C]: in function 'xpcall'
[string "Initializer']:1: in main chunk

OK

Cancel

**Comment by pkulchenko** [comment]
If fails to find `IndicatorFillRange` function that is present in wxlua module included with the IDE. Is it possible you're loading a different wxlua module that doesn't come with the IDE? Can you include a screenshot of the About screen of the IDE?

**Comment by pkulchenko** [comment]
BTW, what do you mean by "child windows"? Can you described the steps you're doing when this error is triggered?

**Comment by fireymerlin** [comment]
I just had the following happen when starting ZBS.
!
![Screenshot 2024-04-08 100311](https://github.com/pkulchenko/ZeroBraneStudio/assets/441778/2e083e01-43b6-4b59-ae28-33218d2f10bc)

I just deleted/uninstalled ZBS and lua for windows.  I deleted the c:\program files(x86)\lua folder.
The only modules I put in the lua folder other than what comes with lua for windows are:
Serpent - from ZBS author
winapi-1.0

Child windows - I mean the tabs across the top for each open file.
![image](https://github.com/pkulchenko/ZeroBraneStudio/assets/441778/23df5b32-8b3b-47e0-9e9a-7184298e2f4d)

**Comment by pkulchenko** [comment]
Thank you for the details. Can you show the content of `Help | About` window?

**Comment by fireymerlin** [comment]
![image](https://github.com/pkulchenko/ZeroBraneStudio/assets/441778/ea5eef79-68ba-42d7-8551-80dd8edf02b1)

**Comment by fireymerlin** [comment]
Please close this ticket.
My Dell PC is having hardware issues with the motherboard and/or harddrive.

**Comment by pkulchenko** [comment]
Closing; thank you for the update!
