### ISSUE TITLE
Wine OSX debug does not find default temporary file

### ISSUE THREAD

**Issue by stuta** [pkulchenko/ZeroBraneStudio#1184]
I start zbstudio in OSX Mojave 10.14.6 with `wine64 zbstudio.exe`.
When I start debugging I get this message:

```
Program starting as '"Z:/Users/xxx/nc/bin/bin_win_x86/lj.exe" -e "io.stdout:setvbuf('no')" "\var\folders\d3\2ld3ksf17nj_jchjs7jpf5vm0000gn\T\.ada4.tmp"'.
Program 'lj.exe' started in 'D:\nc-server' (pid: 56).
Z:/Users/xxx/nc/bin/bin_win_x86/lj.exe: cannot open \var\folders\d3\2ld3ksf17nj_jchjs7jpf5vm0000gn\T\.ada4.tmp: No such file or directory
Program completed in 0.05 seconds (pid: 56).
```

I tried to start zbstudio with `TMPDIR=/Users/xxx wine64 zbstudio.exe`

```
Program starting as '"Z:/Users/xxx/nc/bin/bin_win_x86/lj.exe" -e "io.stdout:setvbuf('no')" "\Users\xxx\.469d.tmp"'.
Program 'lj.exe' started in 'D:\nc-server' (pid: 46).
Z:/Users/xxx/nc/bin/bin_win_x86/lj.exe: cannot open \Users\xxx\.469d.tmp: No such file or directory
Program completed in 0.08 seconds (pid: 46).
```
 Any ideas?

**Comment by pkulchenko** [comment]
@stuta, I'm confused by your configuration. Where does lj.exe come from (as it's not a part of the IDE distribution package)? Does the path "\Users\xxx\.469d.tmp" exist when you launch the debugging? Does "Running" (instead of "Debugging") work? Can you try setting `TMPDIR=Z:/Users/xxx` (with the disk specified)?

**Comment by stuta** [comment]
I did set my luajit (lj.exe) path set in user.lua with path.lua = 'Z:/Users/pasi/nc/bin/bin_win_x86/lj.exe'.

Using TMPDIR=Z:/Users/xxx did work, thanks!. Can I change it in the user.lua?

**Comment by pkulchenko** [comment]
I don't see an easy way to do that, as it's using `AssignTempFileName`, which internally checks TMPDIR, but you can try setting it inside user.lua with `wx.wxSetEnv('TMPDIR', 'Z:/Users/xxx')`

**Comment by stuta** [comment]
Thanks wxSetEnv() did work!
