### ISSUE TITLE
Correct Indentation is not working 100%

### ISSUE THREAD

**Issue by fireymerlin** [pkulchenko/ZeroBraneStudio#1185]
I use ZBS to write lua programs to manipulate data files for the World of Warcraft (WOW) game.  Recently, WOW stopped indenting their data files, so I'm using ctrl-a, ctrl-I a lot.
Frequently, ZBS is not correctly all of the indentation.
Here is an example from a file that has 236 lines.  The following are lines 118 thru 148.  Everything above this was indented correctly.  Lines from 172 to eof were also indented correctly.
	["sets"] = {
		["SCONLEY4"] = {
		},
		["Flold-Mankrik"] = {
		},
		["Hunter"] = {
"Feed_Me",
"GFW_FeedOMatic",
"Lemmos_RefillAmmo",
"ClassicHunterPetInfo",
"PetAbilities",
"PetHealthAlarm",
"Tamed",
		},
		["SCONLEY5"] = {
"FarmHud",
"FarmHud_QuestArrow",
		},
		["Enchanting"] = {
		},
		["Libraries"] = {
"Ace3",
"LibCompress",
"LibDBIcon-1.0",
"LibDropdown-1.0",
"LibNotify-1.0",
"LibProfessions",
"LibQTip-1.0",
		},
		["Zords-Skull Rock"] = {

**Comment by pkulchenko** [comment]
Can you show an example on what you mean by incorrectly? A full file would be helpful as well, as I can't reproduce it on this fragment.

**Comment by fireymerlin** [comment]
This file was opened in ZBS and had no indentation.  I use ctrl+a and then ctrl+i.  I then copied and pasted into pastebin.
https://pastebin.com/ARTWs7Ju

**Comment by fireymerlin** [comment]
Look at the line with ace3 on it and some of the lines following that.  They are not indented correctly.  Let me know if there are options that would cause that.

**Comment by pkulchenko** [comment]
Yes, this is kind of by design. If the strings or lines within comments start in the very first column, they are not going to be reformatted (assuming that's the position you want to keep it in). I realize that it's not always the case, but if you add even one space in front of those lines, they will be re-formatted as expected. See the fragment starting [here](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/menu_edit.lua#L348); you can play with its logic to see what works better.

**Comment by fireymerlin** [comment]
It is not consistent.  All of the lines started in column 1.  The first 100 or so were indented, the rest were not.  It is out of my control since I do not create the file.

**Comment by fireymerlin** [comment]
Also, there are no comments in the file.

**Comment by pkulchenko** [comment]
> It is not consistent. All of the lines started in column 1. The first 100 or so were indented, the rest were not. It is out of my control since I do not create the file.

It's consistent based on the explanation above, as only strings and comments that start in the first column are not re-indented. If you don't like this behavior for strings, you can comment out [this line](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/menu_edit.lua#L350) and all strings should be re-formatted as well.
