### ISSUE TITLE
Feature request: Auto-Start debugger server

### ISSUE THREAD

**Issue by kspes** [pkulchenko/ZeroBraneStudio#139]
I'd like to be able to configure ZBS to auto-start the debugger server on application start.

Also, it would be a good idea to allow stopping the debugger server once it's started, just sayin'.. ;)

**Comment by pkulchenko** [comment]
The plugin is available [here](https://github.com/pkulchenko/ZeroBranePackage/blob/master/autostartdebug.lua); it can also be done from the config file:

```
local G = ...
package { onRegister = function() G.DebuggerAttachDefault() end }
```
