### ISSUE TITLE
Crash when "Close All Pages" used

### ISSUE THREAD

**Issue by joe528** [pkulchenko/ZeroBraneStudio#190]
ZeroBrane always crashes when I try to "Close All Pages"

Here is the report from the Mac:

Process:         lua [11446]
Path:            /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua
Identifier:      ???
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  bash [11445]
User ID:         501

Date/Time:       2013-08-15 04:15:30.935 -0400
OS Version:      Mac OS X 10.8.4 (12E55)
Report Version:  10

Interval Since Last Report:          849092 sec
Crashes Since Last Report:           1
Per-App Interval Since Last Report:  2701717 sec
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      8BE9EBA9-B4B6-A033-73AE-2730B339E1BA

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000006f8d9965

VM Regions Near 0x6f8d9965:
    shared memory          0000000015893000-0000000015c94000 [ 4100K] r--/r-- SM=SHM  
--> 
    __TEXT                 000000008feb0000-000000008fee3000 [  204K] r-x/rwx SM=COW  /usr/lib/dyld

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libwx.dylib                     0x016e336a 0x1000000 + 7222122
1   libwx.dylib                     0x013c7967 0x1000000 + 3963239
2   libwx.dylib                     0x0145bb46 0x1000000 + 4569926
3   libwx.dylib                     0x0145bba1 0x1000000 + 4570017
4   com.apple.CoreFoundation        0x9781884e **CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 30
5   com.apple.CoreFoundation        0x9781878d __CFRunLoopDoObservers + 381
6   com.apple.CoreFoundation        0x977f27f6 __CFRunLoopRun + 886
7   com.apple.CoreFoundation        0x977f201a CFRunLoopRunSpecific + 378
8   com.apple.CoreFoundation        0x977f1e8b CFRunLoopRunInMode + 123
9   com.apple.HIToolbox             0x96f59f5a RunCurrentEventLoopInMode + 242
10  com.apple.HIToolbox             0x96f59bf5 ReceiveNextEventCommon + 162
11  com.apple.HIToolbox             0x96f59b44 BlockUntilNextEventMatchingListInMode + 88
12  com.apple.AppKit                0x9110493a _DPSNextEvent + 724
13  com.apple.AppKit                0x9110416c -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 119
14  com.apple.AppKit                0x910fa5cc -[NSApplication run] + 855
15  libwx.dylib                     0x0129b0fb 0x1000000 + 2732283
16  libwx.dylib                     0x0145bf41 0x1000000 + 4570945
17  libwx.dylib                     0x013c7125 0x1000000 + 3961125
18  libwx.dylib                     0x01051c3e 0x1000000 + 334910
19  liblua.dylib                    0x0000ce50 0x5000 + 32336
20  liblua.dylib                    0x00017ae9 0x5000 + 76521
21  liblua.dylib                    0x0000cf0c 0x5000 + 32524
22  liblua.dylib                    0x00006d81 0x5000 + 7553
23  liblua.dylib                    0x0000c2cb 0x5000 + 29387
24  liblua.dylib                    0x0000c331 0x5000 + 29489
25  liblua.dylib                    0x00006d3e 0x5000 + 7486
26  lua                             0x0000241a 0x1000 + 5146
27  lua                             0x000021ce 0x1000 + 4558
28  liblua.dylib                    0x0000ce50 0x5000 + 32336
29  liblua.dylib                    0x0000cef8 0x5000 + 32504
30  liblua.dylib                    0x00006c3e 0x5000 + 7230
31  liblua.dylib                    0x0000c2cb 0x5000 + 29387
32  liblua.dylib                    0x0000c331 0x5000 + 29489
33  liblua.dylib                    0x00006bb6 0x5000 + 7094
34  lua                             0x00001b05 0x1000 + 2821
35  lua                             0x00001a65 0x1000 + 2661

**Comment by pkulchenko** [comment]
This should be properly resolved by recent commit 63fd2102.
