### ISSUE TITLE
Feature;  add a TODO pane

### ISSUE THREAD

**Issue by Tieske** [pkulchenko/ZeroBraneStudio#21]
showing just a list of comments marked with TODO

**Comment by andrewstarks** [comment]
++1.

This is a great idea and perhaps it could be implemented as something like a filter. That is: a tree view or list of hits that is looking for comments that begin with whatever prefix:
```
----TODO::
--[===[FIXME//
--WARNING--
```

Are all reasonable things to check for. The defining feature is that it is a list that checks for comments that begin with VAR.

Also, this is just the kind of thing that I would set in a project file, if I had such a thing to set things in.... ;)

**Comment by pkulchenko** [comment]
This has been covered by [todo](https://github.com/pkulchenko/ZeroBranePackage/blob/master/todo.lua) and [todoall](https://github.com/pkulchenko/ZeroBranePackage/blob/master/todoall.lua) packages.
