### ISSUE TITLE
Duplicate file names (such as `init.lua`) are ambiguous in tabs

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/ZeroBraneStudio#213]
On OS X version .38:

I have multiple files open. I'm writing a many-file library and my style is to use directory names that match the module name with an `init.lua` file as the starting point.

This leads to many `init.lua` files open, at the same time. I cannot find a way to tell which one I need by looking at the tab (perhaps prepending enough text to show me that it is different), hovering over it with my mouse (hoping it will tool-tip me the full path), highlighting the file in the directory tree if I select it, or anything else that might be helpful.

As it is, I have to mark the top of the file with this information, but then this requires me to scroll to the top of the file.

Am I missing a setting? I was unable to locate one or google for the answer. 

Thanks!

**Comment by pkulchenko** [comment]
This functionality is also available as a [plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/uniquetabname.lua).
