### ISSUE TITLE
Multiple Directories for Project / Project File Config

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/ZeroBraneStudio#223]
When I work on writing libraries, I sometimes work from different directories. This is especially true when I'm using a tool kit and for some reason, in the middle of my project, I need to modify something in that tool kit. 

In these cases, I wish that I could have the tool kit shown as a second root directory in my project view.

Along with this, I'd like a simple Luafile that represented a project to ZBS. In this file, there could be any amount of valid ZBS configuration data, but the primary thing it would contain is the folders that the project should include.

Some thoughts:

* If configuration state is an issue, then reloading ZBS when a new project is opened is fine.

* The hierarchy should be: project -> user -> system, with defaults going from left to right.

* This is a gateway to nested projects. I'm just saying. : ^)

**Comment by pkulchenko** [comment]
@andrewstarks, I've been looking at adding support for folder mapping in the project tree and have been considering several options to how represent those mapped folders. The current favorite is simple:

1. Select "Map folder" from the context menu in the file tree
2. Select folder from the select folder dialog.
3. This folder is added at the top of the folder/file list (as the first child of the project name) with a special icon.
4. (still TBD) You may be able to "rename" that mapped folder, which would simply create an alias for it.

This configuration would be project based. You can also unmap the folder, or map more than one folder; all the mapped folders would be alphabetically sorted and shown before any other folders/files are shown.

This is mainly useful to open those folders to have easy access to their files. I don't see much use for anything else. I haven't decided whether/how to save these additional files when projects are switched (as they are not part of the project tree); they will only be re-opened when you exit and re-launch ZBS.

Would it be sufficient and how else would you use this?

**Comment by pkulchenko** [comment]
@andrewstarks, this has been implemented (`Map Directory` from the popup menu in the file/project tree). Take a look and let me know how it works for you.

**Comment by andrewstarks** [comment]
Very cool. I will give it a shot. I'm not 100% sure that I have your idea properly conceptualized yet. I will play, then report.

**Comment by pkulchenko** [comment]
Sounds good. Note that the mapped folders are not included in fuzzy search. I haven't decided whether to add them or not.
