### ISSUE TITLE
Where's the print command?

### ISSUE THREAD

**Issue by Joymaker** [pkulchenko/ZeroBraneStudio#230]
Can it possibly be that you published an editor without a print command? But on my Mac, MacOS 10.7.5, ZBS 0.39, I can't find a print command of any sort.

If this is a feature yet to be added, please add with it a configuration option that lets me set a different font size for printing than I use for screen viewing. Most IDs have this problem lately: a reasonable font for viewing on the screen comes out looking gigantic in print.

**Comment by pkulchenko** [comment]
@Joymaker, this has been implemented in v1.30. See #540.
