### ISSUE TITLE
Bookmark positions in editor.

### ISSUE THREAD

**Issue by Sergeij2000** [pkulchenko/ZeroBraneStudio#233]
Hi Paul,

after working with ZBS a couple of hours, i'm still impressed how smooth everything is working, especially after the tweaking of the tilde dead key.

A small thing what i'm still missing from Visual Studio (and some other editors): Text markers.

This things are very handy, if you have to jump back and forth between some code segments in one file. The usual key kombination is CTRL-F2 to toggle a text marker, which is displayed in the break point column as a small (bright blue) rectangle. F2 jumps to the next text marker in a file, SHIFT-F2 to the previous one.

It would be great if this could be integrated into one of the future versions.

Thanks

Jo

**Comment by andrewstarks** [comment]
I saw an issue that asked for "TODO" tags and it referenced this. I can see the relation, but I do conceive them as slightly different. So I've deleted my comment there and am appending it here:

-------------------------------
++1.

This is a great idea and perhaps it could be implemented as something like a filter. That is: a tree view or list of hits that is looking for comments that begin with whatever prefix:

----TODO::
--[===[FIXME//
--WARNING--
Are all reasonable things to check for. The defining feature is that it is a list that checks for comments that begin with VAR.

Also, this is just the kind of thing that I would set in a project file, if I had such a thing to set things in.... ;)

**Comment by pkulchenko** [comment]
@andrewstarks, there is a cross-over with #21, but what I'm thinking about is a new Markers/Locations tab [as we discussed on the maillist](https://www.freelists.org/post/zerobrane/Break-point-list,3). It would show a tree with a list of (open) files and all markers in them, including these comments. You'd be able to configure what strings to search for (and that configuration can be set from the project file). I haven't decided whether to have a flat list with "file:line text" or a tree with file names and "line text" as the content; in either case there is going to be an icon corresponding to the type of the marker.
