### ISSUE TITLE
Configuration documentation page

### ISSUE THREAD

**Issue by Marbux** [pkulchenko/ZeroBraneStudio#238]
Re: http://studio.zerobrane.com/doc-configuration.html

I suggest adding to the end of the first paragraph or in a new second paragraph. 

"System-wide and per-user configuration changes to not take effect until the configuration file is saved and the program is relaunched."

Picky but essential detail. It took me about 2 minutes to look for that detail, then having not found it, decided to experiment. 2 minutes times the number of new IDE  users == ?

Best regards,

Paul

**Comment by rulatir** [comment]
Is this still true as of 2019 that ZeroBrane can't detect changes in configuration files and reload them, particularly if the changes are made *in* ZeroBrane?

**Comment by pkulchenko** [comment]
@rulatir, yes, that's still the case, although there have been several improvements that may make the implementation of that change possible. The original plan I had was to re-apply the changes that can be re-applied without restarting the IDE, but if you are okay with a quick restart, then something like this may work (add this snippet to the config file):

```
package {
  onAppLoad = function(self)
    self.files = {
      [ide:GetRootPath(ide.configs.system)] = true,
      [ide:GetRootPath(ide.configs.user)] = true,
    }
  end,
  onEditorPreSave = function(self, editor, filepath)
    if self.files[filepath] then
      ide:DoWhenIdle(function() ide:Restart(true) end)
    end
  end,
  onIdleOnce = function(self)
    -- set monitor on both configuration files: ide.configs.system and .user

    if not wx.wxFileSystemWatcher then return end
    local watcher = wx.wxFileSystemWatcher()
    watcher:SetOwner(ide:GetMainFrame())

    local mask = wx.wxFSW_EVENT_CREATE + wx.wxFSW_EVENT_DELETE + wx.wxFSW_EVENT_RENAME
    local _ = wx.wxLogNull() -- disable error reporting; will report as needed

    for path in pairs(self.files) do
      local dir = wx.wxFileName.DirName(wx.wxFileName(path):GetPath(wx.wxPATH_GET_VOLUME))
      if dir:Exists() and not watcher:Add(dir, mask) then
        ide:Print("Couldn't set watch for configuration file '"..path.."'.")
      end
    end

    ide:GetMainFrame():Connect(wx.wxEVT_FSWATCHER, function(event)
        -- using `GetNewPath` to make it work with rename operations
        if self.files[event:GetNewPath():GetFullPath()] then ide:Restart(true) end
      end)
  end
}
```
