### ISSUE TITLE
Userdata leak during debugging

### ISSUE THREAD

**Issue by marcelvanherk** [pkulchenko/ZeroBraneStudio#241]
Hi Paul,

this script leaks when run from ZBS (as found on 2 dec on github):

a = field()
collectgarbage()

But not when I run it outside ZBS. Any idea? The leak does not occur when I write local a = field().

Marcel

**Comment by pkulchenko** [comment]
Marcel, I've tested with LuaJIT, Lua 5.2, and Lua 5.3, and they all have expected behavior (only one last instance is captured). Only Lua 5.1 shows the leak, so I don't think it's something that is wrong in Mobdebug/ZBS.

Here is the script that works across all those versions:

```lua
if not newproxy then newproxy = function() return setmetatable({},{__gc = 1}) end end
print(a)
a = {1, sentinel = newproxy(true)}
getmetatable(a.sentinel).__gc = function() print("collected 1") end
a = {1, sentinel = newproxy(true)}
getmetatable(a.sentinel).__gc = function() print("collected 2") end
a = {1, sentinel = newproxy(true)}
getmetatable(a.sentinel).__gc = function() print("collected 3") end
collectgarbage()
print("done", collectgarbage("count"))
```
