### ISSUE TITLE
Update love2d.lua for LÖVE 0.9.0

### ISSUE THREAD

**Issue by crumblingstatue** [pkulchenko/ZeroBraneStudio#247]
LÖVE 0.9.0 is officially released.
I also found an updated love_api.lua here: http://love2d.org/forums/viewtopic.php?f=3&t=1796&start=50#p158650

**Comment by pkulchenko** [comment]
@crumblingstatue, I updated the Love2d API for v0.10.0.

**Comment by crumblingstatue** [comment]
> @crumblingstatue, I updated the Love2d API for v0.10.0.

Thank you!
