### ISSUE TITLE
Wrappers

### ISSUE THREAD

**Issue by AndrewShmig** [pkulchenko/ZeroBraneStudio#257]
What do you say if I'll implement following thing https://github.com/AndrewShmig/ZeroBraneStudio/issues/2 ?

I think it's very useful feature, 'cause in AppCode IDE using shortcuts it really speeds up your work.

So, the main idea is to add all these options to submenu and add shortcuts to them + possibility to configure them. 

And the last question I have: whats the best way to check all editor.* methods, all event.* methods and other wx* classes info?

Thank you!

**Comment by pkulchenko** [comment]
Closing this as it's better to be implemented as a plugin if there is interest.
