### ISSUE TITLE
Some kind of plugin-in/support interface

### ISSUE THREAD

**Issue by igame3dbill** [pkulchenko/ZeroBraneStudio#262]
Something like a GIT access to interpreter binaries and configurations, as well as scripts, examples, tutorials, etc.

Like iTunes for Lua.

You can do it, I believe in you.

**Comment by pkulchenko** [comment]
The documentation has been updated to cover various aspects of plugin creation and management; https://studio.zerobrane.com/doc-plugin. Closing...
