### ISSUE TITLE
McAfee Access Protection Errors

### ISSUE THREAD

**Issue by ghost** [pkulchenko/ZeroBraneStudio#304]
With McAfee VirusScan Enterprise 8.8.0.1247, I'm getting several entries for each of the following errors in my Access Protection Log when running ZBS:

```
Blocked by Access Protection rule   [my domain user]    [ZBS install directory]\ZeroBraneStudio\zbstudio.exe    C:\Program Files (x86)\McAfee\Common Framework\McTray.exe   Common Standard Protection:Prevent termination of McAfee processes  Action blocked : Terminate
Blocked by Access Protection rule   [my domain user]    [ZBS install directory]\ZeroBraneStudio\zbstudio.exe    C:\Program Files (x86)\McAfee\Common Framework\UdaterUI.exe Common Standard Protection:Prevent termination of McAfee processes  Action blocked : Terminate
```

Please see this post by a McAfee SME:
https://community.mcafee.com/message/250101#250101

**Comment by pkulchenko** [comment]
Results for v1.10: [zip file](https://www.virustotal.com/en/file/82c19902dafc128dcf5f8a06bb2c162373241ea21b6621a58400e344bf5771ce/analysis/1433546487/) and [exe file](https://www.virustotal.com/en/url/e63827a51d349042402c312b0d660e156e555445f7e2e2937e15538e5f3e0fe6/analysis/1433546361/).
