### ISSUE TITLE
Add Open File By Name (search filename in project)

### ISSUE THREAD

**Issue by qjzy2008** [pkulchenko/ZeroBraneStudio#31]
likeness of Ctrl + Shift + R in eclipse

**Comment by pkulchenko** [comment]
> Ctrl+Shift+O : file search
> Ctrl+Shift+S : symbol search

@sclark39, both of these have been implemented in the current github version; have you had a chance to give them a try?

**Comment by sclark39** [comment]
I've used the file search but not the symbol search. Haven't had my
computer for a month so I haven't checked it out recently but when I did I
remember being irritated that when I hit ESC it would cancel going to the
other file and jump back to the previous one instead. I know I was at least
seeing that behavior with the goto line function. I'll try to check this
out in the coming weeks and give some better (fresher) feedback.

**Comment by pkulchenko** [comment]
> when I hit ESC it would cancel going to the other file and jump back to the previous one instead.

This is by design. You need to hit `Enter` to stay in the selected/new file; `ESC` will return to the original state (and restore the cursor position). I think that's what the most users expect.

> I'll try to check this out in the coming weeks and give some better (fresher) feedback.

Would be great! Thank you.
