### ISSUE TITLE
Feature; Add a dark ui theme

### ISSUE THREAD

**Issue by ThaisRobba** [pkulchenko/ZeroBraneStudio#318]
I don't know how easy or possible this is, but I think it would be an interesting addition to have a dark ui theme (as in, dark tabs, dark borders and so on) that can be easily turned on/off from the user preferences. As an example, a screenshot comparing ZBs bright UI with Atom's dark ui.

![captura de tela de 2014-05-08 22 18 13](https://cloud.githubusercontent.com/assets/597287/2923486/19c2f3ec-d718-11e3-984d-e660c70d3558.png)

**Comment by bergstar** [comment]
I think this feature would make ZeroBrane much better. Maybe a minimalist flat style design / look similar to Visual Studio Code would make it possible to add dark GUI ? Definitely wanted feature.

**Comment by fsinisi90** [comment]
I guess it's still not possible to customize the toolbar, tabs, etc, right? +1 to this!
