### ISSUE TITLE
Support re-indentation of code fragments

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#324]

**Comment by SoniEx2** [comment]
```lua
do
  local str="\""..":\")"
print "test"
end
```

**Comment by pkulchenko** [comment]
@SoniEx2, should be fixed now. Thanks for the report!

**Comment by SoniEx2** [comment]
```lua
do
  x = {
    ["k"] = {[[{
}
]]},
    }
  end
```

**Comment by pkulchenko** [comment]
@SoniEx2, should be fixed now; thanks for the report.

**Comment by SoniEx2** [comment]
```lua
do
  do
    --[[
  end--]]
end
end
```

**Comment by pkulchenko** [comment]
@SoniEx2, I missed the issue you showed in your [earlier comment](https://github.com/pkulchenko/ZeroBraneStudio/issues/324#issuecomment-132377106), but it came up in a different context, so should be fixed now.
