### ISSUE TITLE
[REQ] Shortcut Ctrl+Enter Create new line below current line.

### ISSUE THREAD

**Issue by Jumes** [pkulchenko/ZeroBraneStudio#334]
Hi, most editors support shortcut Ctrl+Enter/Ctrl+Shift+Enter to create new line below/above current line.The ZeroBraneStudio will be efficient, if it supports this feature.Thank you!

**Comment by pkulchenko** [comment]
The plugin is no longer needed as this functionality has been included in the IDE (v1.11+).
