### ISSUE TITLE
Editor font not antialiased on Win8.1 RDP

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#365]
When accessing a computer running ZBS on Windows 8.1 via Remote Desktop, the font in the editor doesn't get the default system anti-aliasing (ClearType or whatever they call it nowadays) and so is quite painful to read:
![zbs_no_cleartype](https://cloud.githubusercontent.com/assets/4388386/4626015/f073d09c-537c-11e4-96a2-b83e2973d959.png)

**Comment by madmaxoft** [comment]
I have retried this with current master (17eaa07c014ae2853e550a93cf118d581bd3e328) and am surprised to see everything fixed: the font is anti-aliased and the block selection is no longer funky. No idea which change fixed it, or whether it could have been caused just by my setup in the first place.

Tried on the wx upgrade branch (768078db17f51c4b3581285a3050ab99a597118f), all ok there as well.

**Comment by pkulchenko** [comment]
@madmaxoft, great to hear! Thanks for the update.

**Comment by madmaxoft** [comment]
I retried with different computers (Win7 Pro RDP server, Win8.1 N client over LAN connection) and this time the font wasn't anti-aliased for either of those commits, but the block selection was okay for both.

So no, even the wx31 upgrade didn't fix the anti-aliasing issue, but it's setup-specific.

**Comment by pkulchenko** [comment]
Interesting; at least the selection is fixed; the anti-aliasing seems to be specific to the client/server configuration/version.
