### ISSUE TITLE
Uncaught lua script exception

### ISSUE THREAD

**Issue by MightyChubz** [pkulchenko/ZeroBraneStudio#383]
There has been a bug or some type of issue I have been having. I've re-installed the program nearly 10 times now, and the issue is that every time I start the program it opens a window saying a Uncaught lua script exception occurred, this is what it says.

src\editor\markup.lua:30: attempt to index local 'styles' (a nil value) stack traceback:
        [string "initializer"]:1: in function '_index'
        src\editor\markup.lua:30: in function 'MarkupAddStyles'
        src\editor\markup.lua:49: in main chunk
        [C]: in function 'dofile'
        src\editor\main.lua:504: in main chunk
        [string "initializer"]:1: in function <[string "initializer"]:1> 
        [C]: in function 'xpcall'
        [string "initializer"]:1: in main chunk

Before this though I was trying to set up a color scheme to use I messed up and didn't noticed it so I went ahead and restarted the IDE, then the exception start popping up. Upon re-installing so many time I think it save things I have done in the setting. Now, to make sure if this is a bug or not I want to ask this question is this caused because of what I did or not?

**Comment by wojoin** [comment]
Open cfg\user.lua and edit it , but it does not work well when I download the latest version of ZeroBrane.
Could you help me to solve it by uninstall zerobrane.This bug always happened when I uninstall/install it.
thanks.

**Comment by pkulchenko** [comment]
@wojoin, I'm not sure what help you need or what bug you reference; can you provide an example of the `user.lua` file that demonstrates the issue?

**Comment by wojoin** [comment]
Thank you so much for your immediate response.
**user.lua** as follow,
```
local G = ...
styles = G.loadfile('cfg/tomorrow.lua')('Monokai')
editor.tabwidth = 4
editor.usetabs = true
editor.usewrap = false
```
and then run ZeroBranc as administrator, but this attempt appears again. I google it all this morning, but there's no good solution.
![image](https://user-images.githubusercontent.com/6468368/42492449-b1c6f8b6-844b-11e8-8553-822d1e3653e4.png)
Thanks for your kindly support.

**Comment by wojoin** [comment]
@pkulchenko Well, I'll try it again when removing the first line. The version of IDE is the latest release, just downloaded this morning. According to your description, maybe my laptop environment has something wrong.

**Comment by pkulchenko** [comment]
You can try with `styles = loadfile('cfg/tomorrow.lua')('Monokai')`, as it should set the expected color, but this won't fix the issue if you still have it.

Maybe you are still running an older version? What does About screen show (F1)?

**Comment by wojoin** [comment]
I'm sure the IDE version is the latest 1.7, I even download it again from GitHub. There's no chance to press F1. There's always that prompt. It's very strange. I try to download the old version and run it.
