### ISSUE TITLE
MAC OS debug and run problem

### ISSUE THREAD

**Issue by tuming1990** [pkulchenko/ZeroBraneStudio#391]
Hi,

I'm running ZBS on MAC OS 10.10.1. The problem is weird and similar with https://github.com/pkulchenko/ZeroBraneStudio/issues/91

When I debug the program, the output is:
Debugging session completed (traced 0 instructions).
Program completed in 6.41 seconds (pid: 76817).
error loading module 'libpaths' from file '/usr/local/lib/lua/5.1/libpaths.so':
	dlopen(/usr/local/lib/lua/5.1/libpaths.so, 6): no suitable image found.  Did find:
	/usr/local/lib/lua/5.1/libpaths.so: mach-o, but wrong architecture
stack traceback:
	[C]: at 0x00091340
	[C]: in function 'require'
	/usr/local/share/lua/5.1/paths/init.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/torch/init.lua:10: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/nn/init.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/unsup/init.lua:1: in main chunk
	[C]: in function 'require'
	doall.lua:27: in main chunk

I tried to add executable path of lua to user.lua, but it doesn't work.
Any help will be appreciated. Thanks!

**Comment by pkulchenko** [comment]
> dlopen(/usr/local/lib/lua/5.1/libpaths.so, 6): no suitable image found. Did find:
/usr/local/lib/lua/5.1/libpaths.so: mach-o, but wrong architecture

ZBS ships with 32bit executables and you are most likely using 64bit so modules; when 64bit module is loaded into 32bit process, you get "mach-o, but wrong architecture" error. The best way to resolve it is to use 64bit lua executable that should be present on your system.

> I tried to add executable path of lua to user.lua, but it doesn't work.

What specifically didn't work? You need to provide more details on what you tried and what (incorrect) results you got. Maillist or IRC may be a better way to resolve this though.
