### ISSUE TITLE
error loading module 'wx' from file 

### ISSUE THREAD

**Issue by HuntTheShunt** [pkulchenko/ZeroBraneStudio#392]
Hi, I have just installed ZeroBraneStudio using ZeroBraneStudioEduPack-0.90-win32.exe on a windows 7 Ultimate 64 bit pc that has a working installation of SciTE.

I get an error...
---------------------------
Uncaught lua script exception
---------------------------
error loading module 'wx' from file 'I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\wx.dll':
	I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\wx.dll:1: '=' expected
stack traceback:
	[string "Initializer"]:1: in function <[string "Initializer"]:1>
	[C]: at 0x66df03e3
	[C]: in function 'require'
	src/main.lua:28: in main chunk
	[string "Initializer"]:1: in function <[string "Initializer"]:1>
	[C]: in function 'xpcall'
	[string "Initializer"]:1: in main chunk
---------------------------
OK   
---------------------------

LUA_PATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac;I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll

I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\ does contain wx.dll with a date of 21/08/2008 11;26 size 2.30mb

Is the problem the spaces in the path to the Lua 5.1?

**Comment by HuntTheShunt** [comment]
Hmm... Nothing to do with spaces in directory names; I have checked using underscores...
---------------------------
Uncaught lua script exception
---------------------------
error loading module 'wx' from file 'I:\My_Radio_Control_stuff\SuffForLua\Lua\5.1\clibs\wx.dll':
	I:\My_Radio_Control_stuff\SuffForLua\Lua\5.1\clibs\wx.dll:1: '=' expected
stack traceback:
	[string "Initializer"]:1: in function <[string "Initializer"]:1>
	[C]: at 0x66df03e3
	[C]: in function 'require'
	src/main.lua:28: in main chunk
	[string "Initializer"]:1: in function <[string "Initializer"]:1>
	[C]: in function 'xpcall'
	[string "Initializer"]:1: in main chunk
---------------------------
OK   
---------------------------

**Comment by HuntTheShunt** [comment]
Putting the last section in quotes allows ZeroBrane Studio to work
LUA_PATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac;"I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll"
Do not know if this messes up anything else yet!

Source for the in quotes idea at http://marc.info/?l=lua-l&m=134686701920287

**Comment by pkulchenko** [comment]
> LUA_PATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac;I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll

This seems like the case of misconfiguration as libraries in dlls should be referenced in LUA_CPATH, not LUA_PATH; try the following:

```
LUA_PATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac
LUA_CPATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll
```

**Comment by HuntTheShunt** [comment]
I should have said I did try...
LUA_CPATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac;I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll

That did not work
now try...
LUA_PATH=I:\My Radio Control stuff\SuffForLua\Lua\5.1\lua\?.luac;"I:\My Radio Control stuff\SuffForLua\Lua\5.1\clibs\?.dll"

This worked.
