### ISSUE TITLE
API description : valuetype not working when multiple values returned

### ISSUE THREAD

**Issue by sladecraven** [pkulchenko/ZeroBraneStudio#394]
For example : 
...
    to_matrix = { 
      type = "method",
      description = "Extracts X and Y component from a 2D vector array in two matrices",
      args = "()",
      returns = "( matrixVX, matrixVY)",
      valuetype = "(matrix, matrix)",
....

In this example, the method returns 2 matrices objects. This does not work with the auto-completion.

**Comment by pkulchenko** [comment]
Yes, that's the current limitation of the auto-complete logic. Unfortunately I don't plan to fix this issue as it requires more complex changes on the other side: assignment analysis also needs to be improved to handle multiple assignments and this is not something that current primitive syntax-based mechanism can handle. I'm tabling it for now.
