### ISSUE TITLE
Adding APIs Regardless of Runtime

### ISSUE THREAD

**Issue by jacobdufault** [pkulchenko/ZeroBraneStudio#396]
I'm toying around with dynamically generating API files and was wondering if they can be registered regardless of the runtime. I'm currently just replacing `baselib` (ie, `ide:AddAPI("lua", "baselib", api)`); I could always load in the existing baselib and then just append to it, but that is rather hacky.

Also, is there a better place for questions like this one?

**Comment by pkulchenko** [comment]
@jacobdufault, not sure what you mean by "dynamically generating", but I just implemented this functionality recently that may be useful for what you are trying to do, but haven't had a chance to document it yet.

You may add `api = {"apiname"}` to the config file and "apiname" API will always be loaded. You can also have `api = {"luadeb" = {"apiname"}}` and "apiname" will only be loaded for "luadeb" interpreter/runtime.

If this still doesn't help, please provide more information about what you are trying to do and I'll try to come with some solution for you.

**Comment by pkulchenko** [comment]
As to where to ask questions, take a look at the community page that has several options: http://studio.zerobrane.com/community.html

**Comment by jacobdufault** [comment]
Okay, thanks.
