### ISSUE TITLE
"Popup" widget opens  in different screen

### ISSUE THREAD

**Issue by sladecraven** [pkulchenko/ZeroBraneStudio#398]
In Linux, with multi-screen setup (2 or 3 screens for example), if ZB is displayed on screen 2, the search window always appear on screen 1 the first time it opens. I guess this is the same for all "popup" widgets. 
Ideally, when this kind of widgets opens, it should be place on the same screen than the editor (IMHO :))

**Comment by pkulchenko** [comment]
@sladecraven, unfortunately I can't control what screen the dialog is opened on (or at least I don't see a way to do this in wxwidgets), but there are a couple of ways to position a dialog and I wonder if some other way may work better. Can you try the same thing with other widgets (like Stack or Watch windows) and if they open in the "wrong" location, move them to the right position, close, and try to re-open to see if the position is saved. Also, if the "saving" of position works, then close ZBS and try to re-open those again to see if the position for Stack/Watch windows is the same as the last time.

If it does work for those, I'll check if I can make Find dialog to behave the same way...

**Comment by sladecraven** [comment]
OK, i will try it next week at work.

BTW, i am sylvain.fabre@inpixal.com , who sponsor you for api help menu :)
I post issues thru my private login, but i am the same person (at least as far as i know :))

Regards, Sylvain.

**Comment by sladecraven** [comment]
I will try it next week at work, thanks.

**Comment by pkulchenko** [comment]
@sladecraven, would be great; thanks.

**Comment by pkulchenko** [comment]
@sladecraven, any update on the behavior of other (Stack/Watch windows)? Thanks!

**Comment by sladecraven** [comment]
Sorry, not time up to now to fully test this.  will try tomorrow.

**Comment by pkulchenko** [comment]
This should be fixed by #416.

**Comment by sladecraven** [comment]
Yes, clear :)
