### ISSUE TITLE
LuaJit 2.1 binaries for Windows

### ISSUE THREAD

**Issue by bratao** [pkulchenko/ZeroBraneStudio#403]
First of all, thank you for this awesome IDE.

I was comparing LuaJit 2.1 against the current 2.0 binaries in Windows dist, and it have some serious performance improvements.

Do you plan to update the dist with a more current LuaJit build, or you will wait for a stable release ?

Thanks !

**Comment by pkulchenko** [comment]
Bruno, thank you for the feedback. 

> Do you plan to update the dist with a more current LuaJit build, or you will wait for a stable release?

I do plan to upgrade, but I'm waiting for Lua 2.1 release to do that. I tested ZBS with 2.1 branch and it all seems to work as expected. You should be able to simply replace lua51.dll with the one from the latest LuaJIT.

I'll update this ticket when the upgrade happens.
