### ISSUE TITLE
Turtle graphics demos crash Lua 5.2 and 5.3

### ISSUE THREAD

**Issue by danccarver** [pkulchenko/ZeroBraneStudio#404]
OS: Windows 8.1 version 6.3 (build 9600)
Steps to reproduce
Install fresh version of ZeroBrane Studio
Make sure Lua 5.2 interpreter is selected
Open and run any file in the turtle-samples directory
Result: Windows error message -- "Lua52.exe has stopped working"
Close error message and select Lua 5.3 interpreter
Open and run any file in the turtle-samples directory
Result: Same error

Turtle demos work correctly under "Lua" interpreter, which I believe is Lua 5.1

Despite the problem, I still find ZeroBrane Studio to be one of the best and most straight-forward IDEs I've ever used. Thank you for all your hard work.

**Comment by pkulchenko** [comment]
@danccarver, thank you for the report! Yes, turtle graphics don't work with Lua 5.2 and Lua 5.3 as they depend on wxwidgets module, and I only include its version compiled against Lua 5.1 (due to its size requirements). I plan on moving wxwidgets dynamic libraries to clibs/ folder, which will make it not available for Lua 5.2 and Lua 5.3 interpreters, but this will have to wait until wxwidgets upgrade (#260).

The workaround is to use the default interpreter with turtle graphics. Do  you have any particular reason to use it with Lua 5.2 or Lua 5.3?

**Comment by danccarver** [comment]
No, I didn't have any particular reason for needing to use 5.2 or 5.3 for
the demo. I just happened to be using 5.2 when I was looking at your
implementation of turtle graphics. Actually now's as good a time as any to
broach another subject. I was going to contact you anyway as I'm writing a
beginning programming tutorial using Lua and I wanted to use ZeroBrane
Studio. As I wanted it to be widely available, especially to kids, I was
hoping to get permission to use ZeroBrane for free, just for the purposes
of the tutorial. I'd also include a recommendation to pay for it if they
continued use of it. I can send you some samples of the tutorial if you
would like. Anyway, that's why I was looking at turtle graphics as it
seemed like it would be fun to use it in parts of the tutorial. If the 5.1
interpreter is default, that shouldn't be a problem.

I have to say that I love using ZeroBrane Studio (and did pay for it).
Thanks for creating it!

**Comment by pkulchenko** [comment]
@danccarver, sure you can use it for free as the license allows you to do. You can simply include the link in your tutorials and the users will be able to download and install ZBS on all supported platforms.

All the examples that use turtle graphics (and as such depends on wxwidgets) will require Lua 5.1, but everything else can use Lua 5.2 or Lua 5.3 as needed. For the purpose of the tutorial I'd focus on those constructs that exist in Lua 5.1, which will make the examples you use to run on any version of Lua.

**Comment by danccarver** [comment]
Thanks! I'll verify it's all consistent with 5.1. Again, thank you for a great product!
