### ISSUE TITLE
zbstudio.exe absolutepath:linenumber -> system cannot find file

### ISSUE THREAD

**Issue by chriscog** [pkulchenko/ZeroBraneStudio#408]
When I try to launch ZBS with a command prompt like:

`zbstudio c:/PortablePrograms/ZeroBraneStudio/src/main.lua:3`

then I get an error in the output window: `Can't open file 'c:/PortablePrograms/ZeroBraneStudio/src/main.lua:3': the system cannot find the file`

It works if I use relative path from the ZBS directory. Forward and back slashes seem not to matter. Quotes also do not help.

(In our case the ZBS is integrated with Unity, and we used to be able to open the files from there, but with this bug it is not working anymore.)

I use the 32 bit zipped ZBS, v0.95, but it was also present in v0.8 (if I recall well). OS: Windows 7 Home Premium SP1, 64 bit, Hungarian version.

**Comment by pkulchenko** [comment]
@chriscog, thank you for the report. Yes, there is indeed an issue, which seems to be related to an earlier fix (2ee95998). I need to figure out how to make both work.

**Comment by pkulchenko** [comment]
@chriscog, should be fixed now; please check.

**Comment by chriscog** [comment]
Works like a charm! Thanks for the fast fix.
