### ISSUE TITLE
Unable to enter Chinese characters directly into the editor

### ISSUE THREAD

**Issue by joe528** [pkulchenko/ZeroBraneStudio#410]
When trying to use a Chinese input method (Zhuyi, the most popular input method for traditional Chinese) to enter Chinese characters into the editor, it somehow prevents the characters to be formed.

I have to copy & paste Chinese characters from other editors into Zerobrane.

Any clue about this issue?

**Comment by pkulchenko** [comment]
@joe528, this seems to be a duplicate of #390, which has some additional information and references to other tickets. Could you provide the details in that ticket? Thanks.
