### ISSUE TITLE
Static analyzer mistakenly reports `first use of unknown field`

### ISSUE THREAD

**Issue by Dmitry-Frantsev** [pkulchenko/ZeroBraneStudio#414]
If closure is a cycle variable, the static analyzer would falsely pop up an error message  when invoking the closure function.
```Lua
local function createObject(name)
  local members = {}
  members.test = function()
    print(name..":test()")
  end
  return members
end

local obj = createObject("obj")
obj.test()                      -- ok

local objs =
{
  createObject("obj1"),
  createObject("obj2")
}

for _,o in ipairs (objs) do
  o.test()                    --!! first use of unknown field 'test' in 'obj'
end
```

**Comment by pkulchenko** [comment]
Dmitry, what version of ZBS are you using? I just ran this on the current master branch in github and only get the following:

```
Analyzing the source code: 1 warning.
untitled.lua:18: local variable 'obj' masks earlier declaration on line 9
```

You should probably get the same result with 0.95 as there haven't been any recent changes.

**Comment by Dmitry-Frantsev** [comment]
Hi.
I am using 0.95 version and I switched off option FAST in the file src\editor\inspect.lua



Среда, 25 февраля 2015, 9:12 -08:00 от Paul Kulchenko <notifications@github.com>:
> 
> Dmitry, what version of ZBS are you using? I just ran this on the current master branch in github and only get the following:
> Analyzing the source code: 1 warning.
> untitled.lua:18: local variable 'obj' masks earlier declaration on line 9
> You should probably get the same result with 0.95 as there haven't been any recent changes.
> —
> Reply to this email directly or  view it on GitHub .
> 



**Comment by pkulchenko** [comment]
That explains it; I'll take a look, although non-FAST version is less frequently used as it generates more verbose output.

Are you getting good results with it? If it becomes useful, I can make the FAST switch into a configuration variable, which will eliminate the need for patching...

**Comment by Dmitry-Frantsev** [comment]
I think the quality of analysis is more important than it's speed. non-FAST analysis is very usefull.
I think you should set non-FAST version of the static analyzer as a default configuration.

**Comment by pkulchenko** [comment]
Does it give you clean output after everything you want to fix is fixed? Do you have code samples you run it on? I tried on the ZBS source and there are still some false positives that I'd like to avoid. I generally prefer to have a clean output (maybe with the exception of having `func(event)` where `event` is unused).

**Comment by Dmitry-Frantsev** [comment]
This issue is the first false positive that I have got for my source code.
I also checked ZBS source and have got a lot of false positives.
If you make FAST option is switchable more people will help you to improve static analyzer.

**Comment by pkulchenko** [comment]
Dmitry, I plan to add the config setting, but I still can't figure out how to fix the original issue you have. This seems to be a limitation of lua-inspect that ZBS is using for some of it static analysis. This is the relevant fragment from `luainspect/init.lua`:

```lua
      if #iter_ast == 1 and iter_ast[1].tag == 'Call' and iter_ast[1][1].value == ipairs then
        for i, var_ast in ipairs(varlist_ast) do
          if i == 1 then set_value(var_ast, T.number)
          elseif i == 2 then set_value(var_ast, T.universal)
          else set_value(var_ast, nil) end
        end
```

It seems like `ipairs` is handled by that fragment, but the type of the value is set as `T.universal`, but not a specific type that the value of `ipairs` has, which leads to the warning.

**Comment by Dmitry-Frantsev** [comment]
Hi Paul.
You are right. It is hard to get the type of the value of `ipairs()` / `pairs()`.
Just disable such error detection for cycle variables.
I think you should ask about this issue Metalua developers.
I have a little experience in Lua.

**Comment by pkulchenko** [comment]
I ended up patching lua-inspect, which should fix the issue. I made it use the value of the first element of the parameter of `ipairs`, so it should work correctly in most cases instead of simply suppressing the error. Give it a try and let me know.

I'm also considering adding a configuration switch to enable this slow mode, but a bit later.

**Comment by Dmitry-Frantsev** [comment]
I have checked your patch. Patch works perfect.
You have patched only ipairs() function but missed pairs() function.
```Lua
local function createObject(name)
  local members = {}
  members.test = function()
    print(name..":test()")
  end
  return members
end

local obj = createObject("obj")
obj.test()                      -- ok

local objs =
{
  createObject("obj1"),
  createObject("obj2")
}

for _,o in pairs (objs) do
  o.test()                    --!! first use of unknown field 'test' in 'obj'
end
'''

**Comment by Dmitry-Frantsev** [comment]
Also  I have found a similar issue. The static analyzer can't determine the type of the argument of ipairs() / pairs() functions when their argument is an argument of a function.
```Lua
local function createObject(name)
  local members = {}
  members.test = function()
    print(name..":test()")
  end
  return members
end

local obj = createObject("obj")
obj.test()                      -- ok

local objs =
{
  createObject("obj1"),
  createObject("obj2")
}

local function f(objects)
	for _,o in ipairs (objects) do
	  o.test()                    --!! first use of unknown field 'test' in 'obj'
	end
end

f(objs)

**Comment by pkulchenko** [comment]
> You have patched only ipairs() function but missed pairs() function.

I saw `pairs` as well, but didn't want to change its handling, simply because there is probably no expectation that its element have the same type and there is no way to get the "first" element (I can use `next`, but this would need to be done based on AST analysis and I'm not sure yet how to do this).

Also, the same problem applies to keys for `pairs`; for `ipairs` it can be set to a number, but for `pairs` this information is not available. The current version simply sets both types to `number` and I haven't changed that. It's easy to apply the same logic to both `pairs` and `ipairs`, but I'm not sure what the implications of that change are.

> The static analyzer can't determine the type of the argument of ipairs() / pairs() functions when their argument is an argument of a function.

I'll take a quick look, but the change applied should work in that context as well, so there may be something else at play. We are getting to the point of diminishing returns, so further changes to this logic may not be warranted.

**Comment by pkulchenko** [comment]
> The static analyzer can't determine the type of the argument of ipairs() / pairs() functions when their argument is an argument of a function.

@Dmitry-Frantsev, I don't think this is easily solvable if at all, as I get this error with or without `f(objs)` call. This is the result of the analysis of the AST itself and at that point there is no information about the type of `objects`. Even if you have a call for `f(objs)`, it doesn't "limit" the type of `objects` in any way (as you may have calls with other types as well), so the warning still makes sense.

I thought lua-inspect had some way to indicate a type using --! notation, but I can't find the documentation on that...

**Comment by pkulchenko** [comment]
@Dmitry-Frantsev, I added the handling of `pairs` as well; the type of the key inferred based on the result of `next` call and the value is based on `t[key]`.

**Comment by Dmitry-Frantsev** [comment]
Hi, Paul.
Your static analyzer works much better but false positive message is preset.
```Lua
local function createObject(name)
  local members = {}
  members.test = function()
    print(name..":test()")
  end
  return members
end

local obj = createObject("obj")
local objs ={  createObject("obj1"),  createObject("obj2") }

obj.test()                            -- ok
objs[1].test()                      -- ok
for _,v in ipairs(objs) do 	
     v.test()			  -- ok
end
for _,v in pairs(objs) do
	v.test()                      -- ok
end
local function f(objects)
	for _,o in ipairs (objects) do
	  o.test()                    --!! first use of unknown field 'test' in 'obj'
	end
end
f(objs)
```
Can you disable all validations of cycle variables for the case when such variables are table or user object whereas an ipairs/pairs function argument is an argument of the current function?

**Comment by pkulchenko** [comment]
> Can you disable all validations of cycle variables for the case when such variables are table or user object whereas an ipairs/pairs function argument is an argument of the current function?

This is discussed in #421.
