### ISSUE TITLE
Bookmark and breakpoint navigation

### ISSUE THREAD

**Issue by srdjan-m** [pkulchenko/ZeroBraneStudio#419]
Currently, clicking bookmark icon sets the bookmark.
Is is possible to have two more options:
1. command clicking bookmark icons to move cursor to the next bookmark
2. shift+command clicking icon to move cursor to the previous bookmark

(the same applies to the breakpoint icon)

**Comment by pkulchenko** [comment]
@srdjan-m, it may be a good idea. Are you thinking about this in addition to `Go to Next Bookmark` and `Go to Previous Bookmark` shortcuts? I don't have this for Breakpoints, but I've been thinking about adding similar menu items for breakpoints as well. Would clicking support still be needed?

Addition of `Go to Next?Previous Breakpoint` would also require changing some of the shortcuts. I've been thinking about changing toggling the bookmark to `F2`, and then go to next would be `Ctrl-F2` (`Ctrl-F9` for breakpoints) and go to previous would be `Shift-F2` (`Shift-F9` for breakpoints). `Break` for debugging would need to be changed for something else as well (as it's using `Shift-F9` currently.

**Comment by srdjan-m** [comment]
Shortcuts will do the job.

**Comment by pkulchenko** [comment]
@srdjan-m, I'm also considering using `Alt-F2` and `Alt-F9` to show a menu of available bookmarks (using the same popup that is used for auto-complete) with one line for each bookmark/breakpoint (gathered from all files). Selecting a particular line will jump to the location of that marker.

**Comment by srdjan-m** [comment]
Great! I know exactly what you want to do. Can't wait to see it in action!

**Comment by pkulchenko** [comment]
@srdjan-m, I added the Markers panel to show bookmarks and breakpoints and also added breakpoint navigation (`Project | Breakpoint` menu). It's in the `markers` branch and it will be merged into master in a day or two. Give it a try when you get a chance and let me know how it works for you.

**Comment by pkulchenko** [comment]
Shortcuts have been extended to cover next/previous for both bookmarks and breakpoints and the panel has been added that shows all breakpoint and bookmarks in currently open files. Closing...
