### ISSUE TITLE
DisplayOutputLn a nil value in src/editor/package.lua

### ISSUE THREAD

**Issue by sladecraven** [pkulchenko/ZeroBraneStudio#420]
It seems that the output.lua functions are not loaded when an error occured when loading packages. It happens on line 255, on a Windows install (latest git version).

**Comment by pkulchenko** [comment]
@sladecraven, how do I reproduce this? I made a syntax error in `sample.lua` package and when I start ZBS I do get `Error while processing file: 'packages\sample.lua:2: attempt to call a number value'.` as expected.

**Comment by pkulchenko** [comment]
It seems that this only happens when a package fails to load an image. What package is this failing on? You probably need to do all the loading of resources from `onRegister` handler, not from the body of the package.

**Comment by pkulchenko** [comment]
@sladecraven, any additional information on this? Do you still get this error if you load resources from `onRegister`.

**Comment by sladecraven** [comment]
The issue happens only in Windows, with no packages in the 'packages/" folder. Moroever, theonly packages developped on our side is already loading resources from the onRegister call. 
Any idea ?

**Comment by pkulchenko** [comment]
@sladecraven, no, no idea so far. Do you have a package I can reproduce this on? Can you simplify your package (as long as it still fails) and send it to me? (address in the profile).

**Comment by sladecraven** [comment]
I dump the args given to ide:CreateImageList and  when it fails, the group argument is "PROJECTFOLDER". Does it helps ?

**Comment by pkulchenko** [comment]
> I dump the args given to ide:CreateImageList and when it fails, the group argument is "PROJECTFOLDER". Does it helps ?

Not really, as the I don't use that argument anywhere in my code, so it's something that you call it with. Do you have a (simplified) version of your plugin that shows the issue?

**Comment by pkulchenko** [comment]
@sladecraven, any further info on this? Do you have a plugin I can reproduce this on?

**Comment by sladecraven** [comment]
I finnally patch locally the package.lua file, in order to test the presence of DisplayOutputLn or not. 
This issue happens even with no plugins at all in the packages/ folder, so i am a bit lost :)

**Comment by pkulchenko** [comment]
Ok, how do I reproduce it on a fresh clone of ZBS repository? I  
haven't been successful in reproducing it. Can you describe the steps?

>

**Comment by pkulchenko** [comment]
Any additional info on this? I'd like to fix it (or at least figure out what's going on), but need help with reproducing it...

**Comment by sladecraven** [comment]
![error](https://cloud.githubusercontent.com/assets/1085008/6904044/a8e466e4-d71e-11e4-95f4-fdfecc3937c0.png)
I remove my patch and here is the full error message. I remove also all my plugins+interpreter+api, so it looks like a completly fresh ZB install.

**Comment by sladecraven** [comment]
I investigate a bit more, it seems to break when searching for "FILE-NORMAL-START"

**Comment by pkulchenko** [comment]
Correct; I get the same message if I delete that file, but it should be present for you. It's been added by #01ef6648 and should be located in `zbstudio/res/16/FILE-NORMAL-START.png`. Is the file missing for you?

**Comment by sladecraven** [comment]
Great, solved !
I do not know why the files was not available in win32 installation. Anyway, it works now, thanks!

**Comment by pkulchenko** [comment]
@sladecraven, I'm puzzled by why it wouldn't be available. Are you sure you installed ZBS form one of the archives on the project site? I just checked and this file is in the .zip archive for v1.0. Since ZBS wouldn't even start without that file, I'd expect to see many more reports about this issue and yours was the only one I saw.
