### ISSUE TITLE
Static analyzer in non-FAST mode mistakenly reports about unknown field of the argument of the current function.

### ISSUE THREAD

**Issue by Dmitry-Frantsev** [pkulchenko/ZeroBraneStudio#421]
Static analyzer in non-FAST mode mistakenly reports about unknown field of the argument of the current function.
```Lua
local function sss(str)
  print(str:match("Test"))   -- first use of unknown field 'match'
end
```
You should disable any checking for function arguments.

**Comment by pkulchenko** [comment]
@Dmitry-Frantsev, this should be implemented now. Note that it doesn't solve the problem described in #414, which I'm not going to worry about as its proper solution requires a much deeper analysis of type inferences. This change also doesn't check explicitly for `self` as most of `self` uses are likely to involve metatables anyway, which would generate a lot of false positives.

Give it a try and let me know.
