### ISSUE TITLE
F10 key opens right-click menu, can't assign anything else - ZB 0.95 - Debian Linux

### ISSUE THREAD

**Issue by greescom** [pkulchenko/ZeroBraneStudio#423]
Pressing F10 key opens right-click menu instead of stepping through code. Shift-F10 is similarly affected. Ctrl-F10 works fine.

No biggie, I just reassigned the step functions to F11.

**Comment by pkulchenko** [comment]
@greescom, yes, I know about the conflict and have been thinking about re-assigning it by default, but it's been familiar to users on other systems, so I'm not sure if I want to do this.

I plan some changes to the menus in the next version, which may lead to shortcut changes and may update this one as well. The workaround is to re-assign them as you did.
