### ISSUE TITLE
Windows (Project, Stack, etc) not remembering widths/heights - ZB - 0.95, Debian - Linux

### ISSUE THREAD

**Issue by greescom** [pkulchenko/ZeroBraneStudio#424]
if you resize one of the docked windows then hide & re-show the window it will open at the adjusted height/width for a split second then jump back to the default.

This is particularly problematic for the project & stack windows as I have them docked at the sides & the default size cuts off important info so I have to resize every time.

Thanks!

**Comment by pkulchenko** [comment]
Yes, there is indeed an issue and I've tried to put a workaround for it, but it seems like it's a defect in wxAUIManager (or its handling of pane positions) in wxwidgets. I'll see if this can be fixed somehow, but so far none of my attempts worked and I don't have high hopes on coming up with a workaround.

**Comment by pkulchenko** [comment]
@greescom, I wonder if your windows are larger than 300px wide. I found a workaround that I can probably apply, but it still resets to 300px when the panel is wider than that (sizes smaller than 300px are managed correctly with the fix). It's interesting that if you re-open ZBS after changing the panel size, it will restore it with the correct sizes, so the issue is only when you hide/show the panels.

**Comment by greescom** [comment]
Yes, I see the same behaviour: it's fine when opening/closing but resets on hide/view.
My panes are larger than 300px, the stack window is usually around 700px wide.
Is there anyway to change the default sizes for the different panes? That way a good baseline could be set so it wouldn't be an issue anymore, I imagine most people have them set to the same size most of the time.

**Comment by pkulchenko** [comment]
@greescom, this should be fixed now. Note though that the size of the panes is still limited to 1/3 of the overall window size. I can use [SetDockSizeConstraint](http://docs.wxwidgets.org/trunk/classwx_aui_manager.html#a2754fa329a4d62467d6ce28840730743) to change that if needed.

Let me know how the changes work for you.

**Comment by greescom** [comment]
Thanks for that, it's much better now.

It works perfectly when ZB is fullscreen. Some issues with the stack panel
resizing when ZB is half the screen width, but not a huge deal I don't
think.

Aran.

**Comment by pkulchenko** [comment]
Aran, try running `ide:GetUIManager():SetDockSizeConstraint(0.8,0.8)` from the Local console and see if those issues go away.

**Comment by greescom** [comment]
Yes, it works perfectly with that applied!

**Comment by pkulchenko** [comment]
ok; thank you for the update. I'll consider setting it in the code.
