### ISSUE TITLE
Move line up and down

### ISSUE THREAD

**Issue by aiker** [pkulchenko/ZeroBraneStudio#426]
Please, implement line swap up/down feature. For example binded to Shift+Crtl+Up, Shift+Ctrl+Down like in Sublime Editor.

**Comment by srdjan-m** [comment]
https://github.com/pkulchenko/ZeroBranePackage/blob/master/moveline.lua

**Comment by pkulchenko** [comment]
Thanks @srdjan-m. @aiker, you can use the plugin that @srdjan-m has referenced.

There is probably also a way to do this with `editor.keymap` and `MOVESELECTEDLINESUP` and `MOVESELECTEDLINESDOWN` methods of Scintilla, but, if you are on OSX, it's going to conflict with the current selection extension settings.
