### ISSUE TITLE
F6 target does not transfer to dragged editor tab

### ISSUE THREAD

**Issue by ajbrouwer** [pkulchenko/ZeroBraneStudio#427]
In ZBS 1.00, open two scripts in separate editor tabs. Drag the editor tab that does not have focus to the other side of the one that has focus. This will switch the position of the tabs, give the dragged tab cursor focus, and brings it to front. However, when hitting F6, the script in the tab that previously had focus will be run.

**Comment by pkulchenko** [comment]
@ajbrouwer, thank you for the report. I'll check what may be going on.

**Comment by pkulchenko** [comment]
@ajbrouwer, should be fixed not; take a look.

**Comment by ajbrouwer** [comment]
Indeed, after patching the problem disappeared.

**Comment by pkulchenko** [comment]
This effect is related to [wxwidgets issue #15071](http://trac.wxwidgets.org/ticket/15071) and the earlier patch c383889 provides a workaround for it.
