### ISSUE TITLE
Wrong indent

### ISSUE THREAD

**Issue by SoniEx2** [pkulchenko/ZeroBraneStudio#428]
```
--[[
#if !defined(lua_popen)	/* { */
  --]]
  local test
```

What is going on here?!

**Comment by pkulchenko** [comment]
I think it's mistreating `{`. If you remove that curly bracket, the indentation becomes correct. I'll check why the logic is not taking into account that it's inside a comment (as it should).

**Comment by pkulchenko** [comment]
It's a bug triggered by `#` at the beginning of the line. Since it's a special markup, it's not recognized as a comment, which applies incorrect processing to the subsequent lines (they are considered to be inside an `if ` statement). Will push a fix shortly.
