### ISSUE TITLE
Rename all instances may not rename all instances

### ISSUE THREAD

**Issue by ajbrouwer** [pkulchenko/ZeroBraneStudio#430]
In ZBS 1.00, right click on the first foo, select "rename all instances", and notice the last instance not being renamed:
local foo, bar
if x > y then
	foo, bar = x, y
else
	bar, foo = x, y
end

**Comment by pkulchenko** [comment]
@ajbrouwer, this appears to be the result of an issue with the loose parser as `bar` in `foo, bar` and `foo` in `bar, foo` are not recognized as the same variables that are already defined (and as the result are not replaced). I'll check what may be going on.

**Comment by pkulchenko** [comment]
@ajbrouwer, should be fixed now; thanks for the report.
