### ISSUE TITLE
No WM_CLASS Set

### ISSUE THREAD

**Issue by S0lll0s** [pkulchenko/ZeroBraneStudio#437]
Currently, WM_CLASS is set to `"lua", "Lua"` A fitting WM_CLASS would allow people in scriptable deskop environments to have Zbstudio automatically appear on a specific screen or workspace.

I hover don't know whether this is possible with wxLua (though it should be!)

**Comment by pkulchenko** [comment]
Sol, how do I check WM_CLASS or where is it set by the app? I could find any reference to it or the values you see in wxlua sources, so not sure how I can modify it... What value would you expect to see?

**Comment by madmaxoft** [comment]
I suppose @S0lll0s meant the "window class name", in WinAPI this is the `WNDCLASS.lpszClassName` member: https://msdn.microsoft.com/en-us/library/windows/desktop/ms633576(v=vs.85).aspx . This can be used to identify specific application windows, since each application is expected to register its own name for each window type it is using.

**Comment by S0lll0s** [comment]
On linux you can use `xprop` to inspect a window, the two values will be listed near the bottom.

**Comment by pkulchenko** [comment]
Hm, I'm not sure what I can do for this one. I'm using `zbstudio/res/zbstudio.manifest` on Windows and an installation script on Linux (here is a related ticket #359). Is there anything in particular I need to do?

**Comment by S0lll0s** [comment]
I doubt that it would be set there, as WM_CLASS needs to be set at runtime AFAIK. It is the same "type" of information as the window title text.

**Comment by pkulchenko** [comment]
I don't see any reference to WM_CLASS in winapi module or in wxwidgets sources, so it's unlikely I can do anything about it, unless you can find a way to set it.
