### ISSUE TITLE
Can't input '^' character on OSX

### ISSUE THREAD

**Issue by rm-code** [pkulchenko/ZeroBraneStudio#439]
When I try to write the ^ character ZeroBrane doesn't react at all.

This is on the latest ZBS version and under OSX 10.10.3.

**Comment by pkulchenko** [comment]
@rm-code, have this behavior changed recently for you? Are you on some sort of international keyboard (as this works for me on US keyboard)? Do you think it may be related to #232 and #113?

**Comment by rm-code** [comment]
@pkulchenko It seems like this indeed is a duplicate of #113 (I'm on a german keyboard though). I'll follow the workaround you posted in the other ticket.

**Comment by pkulchenko** [comment]
ok; thank you for the update. Closing as duplicate.
