### ISSUE TITLE
Small multi-cursor working improvement

### ISSUE THREAD

**Issue by S0lll0s** [pkulchenko/ZeroBraneStudio#440]
I don't know if this is off-limits because it's a Scintilla feature or not, but it would be great if you could add another cursor with `CTRL+up`/`down` just like with `CTRL+click`, for example if I want to change

    {
      { 1, 2, 3 },
      { 1, 2, 3 },
      { 1, 2, 3 },
      { 1, 2, 3 }
    }

to 
    {
      { 1, 2, 3, 4 },
      { 1, 2, 3, 4 },
      { 1, 2, 3, 4 },
      { 1, 2, 3, 4 }
    }

I would place the initial cursor behind the first 3, then press `CTRL+DOWN` 4 times and then type `, 4`

**Comment by cipri-tom** [comment]
Use Alt + Shift + Down to achieve this.

**Comment by S0lll0s** [comment]
Oh nice! didn't know about that.
