### ISSUE TITLE
Can't save file which tab was dragged

### ISSUE THREAD

**Issue by DenisKolodin** [pkulchenko/ZeroBraneStudio#443]
If I drag tab with file's content to another place than save hotkey disabled on this tab.

**Comment by pkulchenko** [comment]
Denis, are you testing with the latest master? I can't reproduce this and it was probably fixed by c383889d (#427), so if you are using some older version, please retest with the master branch.

**Comment by pkulchenko** [comment]
@DenisKolodin, let me know if you had a chance to test on the current master version, or at least check what version you are using: `Help | About` or `git describe` if you are running the IDE from a cloned repository.

**Comment by DenisKolodin** [comment]
I tested this on both "ZeroBrane Studio (1.00; MobDebug 0.613)" and "master". I've seen this bug only on release (not master) many times, but I can't reproduce it every time.
I'll try to work with master and let you know if bug persists.

**Comment by pkulchenko** [comment]
@DenisKolodin, any update on this? If you haven't seen it with #427 fix, I'm going to close this.

**Comment by DenisKolodin** [comment]
No bug with fix. Thank you!

**Comment by pkulchenko** [comment]
Good; thanks for the update.
