### ISSUE TITLE
Pressing SHIFT-F3 with highlighted text crashes editor

### ISSUE THREAD

**Issue by stuartcarnie** [pkulchenko/ZeroBraneStudio#445]
OS: Yosemite 10.10.3
commit: ee35d4b

Steps:

1. highlight some text
2. press SHIFT-F3
3. program crashes

**Comment by pkulchenko** [comment]
Stuart, thank you for the report. Should be fixed now.

**Comment by stuartcarnie** [comment]
Indeed it is, thanks!
