### ISSUE TITLE
Changing package.cpath on first line causes crash

### ISSUE THREAD

**Issue by dbaileychess** [pkulchenko/ZeroBraneStudio#447]
This is an odd one.

1. New .lua file
2. Place on line one: package.cpath = package.cpath.."/?.dll"
3. Highlight second instance of "package.cpath.."
4. Ctrl-X
5. Move cursor to after "/?.dll"
6. Type: ..
7. Ctrl-V
8. Hit backspace (causes crash)

It appears to only happen when the context menu window appears.

Step 4: can be Ctrl-C as well.

**Comment by pkulchenko** [comment]
Derek, thank you for the report; I can confirm the issue. Looking into this...

**Comment by pkulchenko** [comment]
Just to confirm, you do see auto-complete popup when you press backspace as it crashes, right?

**Comment by dbaileychess** [comment]
Yes, that window is visible. If I hit 'Escape' to close the window and hit
backspace, it works.

Take Care,

    Derek

**Comment by pkulchenko** [comment]
Derek, thank you for the detailed report; should be fixed now.
