### ISSUE TITLE
Debugger start / termination causes ZBS to request focus

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#449]
Since I upgraded (to 140fdcb101f14152dcd894723cc21f29f369c129 from an ancient version several months old), ZBS tries to get to the front every time a MobDebug session is activated. This is rather disruptive to my work, is there a way to configure it not to do that?

My current workflow is:
1. Write some plugin code in ZBS
2. Start debugging in the MCServer interpreter (starts a new console window with the server)
3. MCServer loads my plugin, ZBS window flashes to request focus.
4. Test out the plugin (usually in a browser) and discover something I need to change
5. Code the change in ZBS, while the server is still running
6. Issue a `reloadplugins` command in the server, which unloads and reloads the script file, thus terminating and restarting the debug session
7. ZBS window flashes to request focus
etc.

If it was possible to configure this focus stealing either via configuration, or as a property of the interpreter, that would be great.

**Comment by pkulchenko** [comment]
I can probably add `requestattention` setting, but I wasn't planning on it. Is it too effective in drawing attention to ignore? ;)

**Comment by madmaxoft** [comment]
Unfortunately yes. Especially when the behavior is not exactly deterministic. Sometimes it goes to front and steals focus successfully, at other times it just stays in the background and flashes on the taskbar. Both are rather unpleasant and the uncertainty which one will be selected makes this terrible.

**Comment by pkulchenko** [comment]
> Especially when the behavior is not exactly deterministic. Sometimes it goes to front and steals focus successfully, at other times it just stays in the background and flashes on the taskbar.

I noticed that as well, but I can assure you that the code executed is always the same; I do occasionally get different reaction from Windows and I'm not sure what's causing it.

Even in the case when RequestAttention is disabled, I do get the focus switch on the very first time I run it and all subsequent runs (in the same launch) and future launches then execute as expected (without focus switch).

**Comment by madmaxoft** [comment]
I believe the different reaction is due to Windows - the BringToFront feature has been long misused by so many various programs that Windows started to manipulate the API, so that programs won't steal focus, but still they needed it for their own apps, so they kept some way of doing it, and now the system is so confused about it that it's no longer consistent.

I don't get any focus switches since I've disabled the attention requesting. It now works perfectly fine. Thanks.

**Comment by madmaxoft** [comment]
One disadvantage is that with your change the debugger won't request attention when it makes sense- when a breakpoint is hit. I've added a PR that splits the `requestattention` option into two - one for the start (which is useless in my opinion) and one for the breakpoint.

**Comment by pkulchenko** [comment]
> I've added a PR that splits the requestattention option into two - one for the start (which is useless in my opinion) and one for the breakpoint.

Yes, I saw the PR, but it may be easier to just make `requestattention` to mean "only during debugging start" (and disable it for breakpoints). Why is it useless for the start? Isn't it what you wanted in the first place?

**Comment by madmaxoft** [comment]
I meant that requesting attention on debugging start seems pretty useless to me. It only makes sense for a breakpoint. But I don't know all use-cases, perhaps someone needs that feature.

**Comment by pkulchenko** [comment]
It was added in aaf77230 to avoid the situation when the debugging is started in the IDE, but it's not visible to the user and it looks like the application hangs. I've had several questions related to that and as the result added debugger activation to make it more visible.
