### ISSUE TITLE
Replace dialog not closed on Esc when focus in editor

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#450]
I think that while the focus is in the editor, the Esc key should in turn close these, whichever is found, in this order:
- Code completion
- Find / replace dialog
- Output / console (this one should have a config option to disable closing by esc)

**Comment by pkulchenko** [comment]
Code completion and tooltips are already closed by Esc; I'll think about adding Find/Replace dialog to close on Esc. There is also full screen mode that is closed on Esc.

Output/Console is not likely to work this way as it's already a bit adaptive. If you set `activateoutput=false` and only open it when the debugging is started, it will disappear when debugging is stopped (similar to how it happens to Stack and Watch windows).

**Comment by pkulchenko** [comment]
This is now done in the following order:

* Code completion or a tooltip
* Find / replace dialog
* Closing full screen

**Comment by madmaxoft** [comment]
Works nicely, thanks.
