### ISSUE TITLE
Unable to click < or > buttons multiple times on tab-bar without moving mouse off

### ISSUE THREAD

**Issue by stuartcarnie** [pkulchenko/ZeroBraneStudio#452]
If you click it once to scroll left or right, you must move mouse away to click again

**Comment by pkulchenko** [comment]
What OS? I don't see this issue on Windows...

**Comment by stuartcarnie** [comment]
I was seeing it on OS X; let me try it again and report back

**Comment by pkulchenko** [comment]
@stuartcarnie, I've tested on OSX 10.2 and it does look like the button stays pressed, but it doesn't prevent me from clicking it again. The button becomes "non-pressed" when the mouse is moved or when there are no more tabs (which disabled the button).

**Comment by pkulchenko** [comment]
@stuartcarnie, have you been able to reproduce this?

**Comment by stuartcarnie** [comment]
If not recording a video, I can reproduce it practically every time. I have to move the mouse for the button to rise and then I can click to move to the next tab.

**Comment by pkulchenko** [comment]
Stuart, weird. What version of OSX are you on? Although it's unlikely to be OSX-version-related, I've seen some differences after upgrade, so it would be interesting to know what you are using.

Unfortunately, this is something that is controlled by wxwidgets, so there is not much I can do to fix it, but I'll link it to wxwidgets upgrade ticket (#260) to double check during the upgrade. Deferring...

**Comment by stuartcarnie** [comment]
Sounds good, @pkulchenko. I will subscribed to #260 and re-test. 

I I could remap CTRL+TAB and CTRL+⇧+TAB to move back and forward through the tabs, I wouldn't care so much anyhow. Is this possible today?

**Comment by stuartcarnie** [comment]
Great stuff, @pkulchenko !
