### ISSUE TITLE
Lua 5.3 string.packsize

### ISSUE THREAD

**Issue by andreashofer123** [pkulchenko/ZeroBraneStudio#453]
In the Lua53 interpreter that comes with ZeroBraneStudio, the string.packsize function is missing.

print(string.packsize)  -> nil

The one that I compiled from recent sources from the Lua website does have the function as documented.

**Comment by pkulchenko** [comment]
@andreashofer123, this is probably because the IDE packages the beta version of Lua 5.3 that was available at that time (and there were few changes since that version). I didn't expect it to be the issue, simply because those users that care about those changes can build their own version and configure ZBS to use it. I'll probably upgrade the version, but you should be able to do it yourself by running `(cd build; sh build-win32.sh lua 5.3)`; replace the name of the script with -macosx or -linux, depending on your platform. I'll update the build scripts to reference the release version shortly.

**Comment by andreashofer123** [comment]
Hello Paul,

Thanks for your reply.
I thought it was because of a beta version. I just wanted to bring that to
your attention.

For the time being, I am fixing this by using the struct.dll, which does
the same thing for older Lua version, and add a line string.packsize =
(require"struct".packsize) to the script.

I also tried to simply copy my Lua53.exe and Lua53.dll to the ZBS bin
directory (I am using Windows), but it crashed Lua when I tried to debug
step a lua script. Is there something special I need to configure?

Best regards,
Andreas


2015-05-01 0:11 GMT+02:00 Paul Kulchenko <notifications@github.com>:

**Comment by pkulchenko** [comment]
> I also tried to simply copy my Lua53.exe and Lua53.dll to the ZBS bin directory (I am using Windows), but it crashed Lua when I tried to debug step a lua script. Is there something special I need to configure?

Hm, no. The version I'm using is in no way special; although I do have my own build file, it's mostly to allow the lua version to be used as a dependency for other modules and to put it into a proper place in the IDE.

I updated the build scripts and tested them on Windows. You should be able to run `(cd build; sh build-win32.sh lua 5.3)` and it will put the files into the right places in the IDE. Let me know if these files work for you. I'm not sure why the files you compiled yourself may not work.

The only thing that comes to mind is the debugging dependency, which uses luasocket I compiled for Lua 5.3, but I don't think the ABI has changed between the beta and the release versions. Try separately running and debugging the scripts using your own version to see if you may be able to run, but not debug the script.

**Comment by andreashofer123** [comment]
> The only thing that comes to mind is the debugging dependency, which uses
luasocket I compiled for Lua 5.3

That was it. I also replaced the luasocket dlls and now it works.

Thank you!

By the way, I just made a donation to support your project. Perhaps I can
talk my boss into making another donation from our company. I use ZBS a lot
and it is very useful for me.

2015-05-01 8:11 GMT+02:00 Paul Kulchenko <notifications@github.com>:

**Comment by pkulchenko** [comment]
> By the way, I just made a donation to support your project. Perhaps I can talk my boss into making another donation from our company. I use ZBS a lot and it is very useful for me.

Thank you!

So, it didn't work with the included luasocket and the version of Lua 5.3 you compiled? Can you try the build command I suggested as I worked for me (with the included luasocket for Lua 5.3)?

**Comment by andreashofer123** [comment]
> So, it didn't work with the included luasocket and the version of Lua 5.3
you compiled?

Exactly.
When I used my Lua with your winsock the debugger did not work.
When I use my Lua with my compiled winsock the debugger works.

> Can you try the build command I suggested

I will have to install a lot of tools first in order to run that build
script.
Perhaps I can try this weekend.
I am ashamed to admit, but I used VisualStudio to compile the lua source
code.
I know I am a bit late making the transition to Linux for developing. Maybe
I should just do it and struggle for a month or so...
Maybe this might explain some incompatibility?



2015-05-01 8:41 GMT+02:00 Paul Kulchenko <notifications@github.com>:

**Comment by pkulchenko** [comment]
> I am ashamed to admit, but I used VisualStudio to compile the lua source code. ... Maybe this might explain some incompatibility?

Most likely; I have everything compiled using gcc.

> I will have to install a lot of tools first in order to run that build script. Perhaps I can try this weekend.

I'll probably have the binaries updated by that time...

**Comment by pkulchenko** [comment]
@andreashofer123, you were right, compiled luasocket doesn't work with the updated lua 5.3 (probably because of the changes in the list of available functions), so it needs to be re-compiled as well. You can build all the files using `(cd build; sh build-win32.sh lua luasocket 5.3)`.

Since you don't have the environment set up, I've pushed those updated files to the [lua-5.3-release](https://github.com/pkulchenko/ZeroBraneStudio/tree/lua-5.3-release) branch.

Let me know when you clone the branch as I plan to upgrade these binaries at a later time.

**Comment by andreashofer123** [comment]
Just to confirm: Your new compiled version from the release branch works.
It also works with my compiled socket dll and vice versa, my compiled lua53.dll works with your sockets.
As you suspect, probably some changes in the dll interface, not the compiler.

**Comment by pkulchenko** [comment]
ok; good. Thank you for confirming this. I'll update the ticket when the branch is merged...

**Comment by pkulchenko** [comment]
@andreashofer123, should be fixed now in the master branch. Take a look and let me know if you notice any issues.

**Comment by andreashofer123** [comment]
Hello Paul,

Thank you so much!
I really like the new features.
Keep up the good work.

Best regards,
Andreas

2015-10-05 7:30 GMT+02:00 Paul Kulchenko <notifications@github.com>:
