### ISSUE TITLE
Some small delay when typing in the main editor

### ISSUE THREAD

**Issue by joe528** [pkulchenko/ZeroBraneStudio#456]
I am using v1.0 and sometimes I can feel a little delay when typing in the main window.

This kind of delay has never been felt/observed before 1.0

My mac is pretty new (2015 iMac 4k) that I just bought two months ago. I don't think the hardware makes the difference.

This delay is very small, but when you are coding and typing, you can feel there is some "unusual" delay in between and that's annoying. 

I monitor the CPU usage. When typing, the CPU usage by ZBS can be as high as 30-40%.

![screen shot 2015-05-06 at 12 06 24 pm](https://cloud.githubusercontent.com/assets/5201083/7487397/41418c64-f3e9-11e4-9763-ea79199583f1.png)

**Comment by joe528** [comment]
I have a feeling that ZBS has become too strong for me. The first thing I love about ZBS is the light-weight feeling but it seems getting heavier each version.

**Comment by pkulchenko** [comment]
@joe528, I'm striving to make sure that added functionality doesn't cause any performance degradation, but occasionally some additional work is needed (like with added outline refresh) and I monitor the changes to make sure it is still light.

I reviewed the changes in the last two versions (1.0 and 0.95), but don't see what might have contributes to the degradation you see. I tested on the current version and get about 14-20% CPU utilization with 15 opened tabs when typing in one of the tabs on a 4-year old MacBook Pro running OSX 10.2. It does jump to 32% for me when typing in a large file, which is attributed to the auto-analyzer work (which needs to re-parse the fragment affected by the changes).

You can disable auto-analyzer (set `autoanalyzer=false`) in the config to see if it makes any difference in your case; you will not have global/local variable navigation and the outline support if you do.

I'll also consider adding an "inactivity" delay that would trigger the analyzer, which would eliminate any delay you may see during typing (the tradeoff is that the analyzer results and the related indicators will be delayed).

I don't see anything else that may help in this case...

**Comment by joe528** [comment]
The editing file is not really big, just under 500 lines of code and there are only 4 tabs opened.

It seems no more delay if I set autoanalyzer=false

**Comment by pkulchenko** [comment]
Thank you for the update; I'll take a look at how to make the analyzer to start after a small delay.

**Comment by pkulchenko** [comment]
@joe528, can you test the current master branch to see the if the small delay is gone? I've made several changes to the internal parser and I'd expect those to slightly improve performance as well.
