### ISSUE TITLE
Some files with content are blank when opened

### ISSUE THREAD

**Issue by daviddoria** [pkulchenko/ZeroBraneStudio#458]
When opening text files (.lua, .txt, etc.) in ZeroBrane Studio, sometimes they open and appear to be blank. I can have a terminal open and check the contents (with 'more file.txt'), and they are certainly not blank. Has anyone had an issue like this? I'm not sure how to provide more information, but I'd be happy to do so if there are any ideas!

**Comment by pkulchenko** [comment]
David, what version of ZBS and what OS are you using? There used to be an issue with displaying the content when the file had invalid UTF8 characters, but it was fixed a very long time ago. Can you make the shortest text fragment that exhibits this issue available online somewhere (gist or paste it)?

**Comment by daviddoria** [comment]
When looking for a version number, I realized that what we have installed is actually a fork (https://github.com/soumith/zbs-torch). If you'd prefer to close this bug and have me move my question there I can do that. I'm actually not sure how to report a version number for you?

The OS is on Red Hat 7.

I stripped one of the files that was showing this behavior down to a single character ('a'), and it still opens and is displayed as blank.

**Comment by pkulchenko** [comment]
Can you try opening the same file in ZBS? If it works in ZBS and doesn't work in zbs-torch, we can move the discussion there, but I'll still take a look...

> I stripped one of the files that was showing this behavior down to a single character ('a'), and it still opens and is displayed as blank.

You mentioned that some files open correctly and some do not. Can you take one of the files that opens and reduce it to a small chunk of text, maybe to the same character `a` and check if it still opens? Maybe it's a permission problem or a problem with something related to the path, but not to the content?

**Comment by daviddoria** [comment]
I cloned ZBS and it seems to behave the same way. I played with one of the working files as you suggested and here's what I found. When the contents are:

----------------------------------------------------------------------
-- This script demonstrates how to define a couple of different
-- models:
--   + 2-layer neural network (MLP)
--
----------------------------------------------------------------------

require 'torch'   -- torch
require 'nn'      -- provides all sorts of trainable modules/layers

----------------------------------------------------------------------
-- parse command line arguments
--if not opt then
--   print '==> processing options'
--   cmd = torch.CmdLine()

It opens correcty -I can see all of the contents. However, if I get rid of the second half so that the contents are

----------------------------------------------------------------------
-- This script demonstrates how to define a couple of different
-- models:
--   + 2-layer neural network (MLP)
--
----------------------------------------------------------------------

require 'torch'   -- torch
require 'nn'      -- provides all sorts of trainable modules/layers

Then it appears empty when I open it.

**Comment by pkulchenko** [comment]
I don't have Red Hat 7 VM to try it on, but I have Fedora, which is probably closest I can get to it. Do you by any chance have other Linux machine you can try this on? So far, I have no idea what may be going on as both files open correctly for me on all (non-Linux) machines I tried it on. I'll try on Fedora shortly.

> However, if I get rid of the second half so that the contents are 'broken' (at the same gist), then it appears empty when I open it.

One more thing to try; if you paste the "broken" gist content into a ZBS tab and save it from ZBS, are you able to see the content after you open it again?

And to make sure that the "gisted" content exhibits the same issue, can you copy "broken" content into a file and doublecheck that it still fails to open correctly in ZBS? I just want to make sure that what you gisted is indeed "broken" and that it's not a matter of some strange end-of-line encoding or something like that.

Thank you for the follow-up on this and my apologies for all the additional questions. This looks quite puzzling, so at this point I can only try to figure out what's going on.

**Comment by daviddoria** [comment]
- Do you by any chance have other Linux machine you can try this on?

I tried it on a different machine (redhat 6), and everything works as expected. The redhat 7 machine I am actually using over ssh (with X forwarding) if that makes a difference? Tthere is no physical access to the machine so I can't try it any other way.

- One more thing to try; if you paste the "broken" gist content into a ZBS tab and save it from ZBS, are you able to see the content after you open it again?

I am not. It is there when I save, but gone when I reopen. However, it does the same disappearing trick when I copy "working" into the ZBS tab and save/reopen it. However, if I open the file in a text editor and save it (without changing anything), then open it again in ZBS, the contents are visible.

- Thank you for the follow-up on this and my apologies for all the additional questions. This looks quite puzzling, so at this point I can only try to figure out what's going on.

No problem - thanks for your help!

**Comment by pkulchenko** [comment]
> I tried it on a different machine (redhat 6), and everything works as expected. The redhat 7 machine I am actually using over ssh (with X forwarding) if that makes a difference? Tthere is no physical access to the machine so I can't try it any other way.

I wouldn't expect X forwarding to make any difference in this case, but I'm shooting in the dark here. When you said it worked on redhat 6, did you try on the machine itself or did you use the same configuration (with X forwarding) you have in the other case?

You can try to read the same file in the console to see if the content is actually retrieved correctly. For example, try these steps:

1. Right click on the tab with a "broken" file and select `Copy Full Path`.
2. Run `text = FileRead([[<<copied full path here>>]])` in the console.
3. `#text` should show the length of the content that was read.
4. `#GetEditor():GetText()` will show the length of the text in the current (broken) editor tab
5. `GetEditor():SetText(text)` will set the text to the content that was read from the file

We can try few other things, but I think this may provide some additional information as to where the issue may be.

**Comment by daviddoria** [comment]
On Redhat 6 I was on the physical machine. 

text = FileRead("/path/to/data/inverse/2_model.lua")
#text
0

but when I look at the file in another editor or cat it on a terminal it looks fine. Very, very odd.

**Comment by pkulchenko** [comment]
ok, we may be getting closer. Since it reads 0 bytes, but doesn't return any errors (the result would be `nil` if there was an error in reading the file), it may be related to getting the length of the file incorrectly (although it has never failed previously).

Can you try running the following: `wx.wxFile("/path/to/data/inverse/2_model.lua", wx.wxFile.read):Length()`. It should print the size of the file, but may also print 0.

If it does print 0, I'm interested in what's being returned by `wx.wxFile("/path/to/data/inverse/2_model.lua", wx.wxFile.read):Read(1000)`.

I'm also interested in what's being returned by `io.open("/path/to/data/inverse/2_model.lua"):read("*a")`. If this one doesn't show the right content (which would be very odd), try running it outside of ZBS. I think this will give us all the information we need.

**Comment by daviddoria** [comment]
I think you're on to something. Here are the three outputs you requested:

wx.wxFile("/path/to/data/inverse/2_model.lua", wx.wxFile.read):Length()
0
wx.wxFile("/path/to/data/inverse/2_model.lua", wx.wxFile.read):Read(1000)
347	"----------------------------------------------------------------------\n-- This script demonstrates how to define a couple of different\n-- models:\n-- + 2-layer neural network (MLP)\n-- \n----------------------------------------------------------------------\n \nrequire 'torch' -- torch\nrequire 'nn' -- provides all sorts of trainable modules/layers\n \n"

io.open("/path/to/data/inverse/2_model.lua"):read("*a")
"----------------------------------------------------------------------\n-- This script demonstrates how to define a couple of different\n-- models:\n-- + 2-layer neural network (MLP)\n-- \n----------------------------------------------------------------------\n \nrequire 'torch' -- torch\nrequire 'nn' -- provides all sorts of trainable modules/layers\n \n"

**Comment by pkulchenko** [comment]
> I think you're on to something. Here are the three outputs you requested:
> wx.wxFile("/path/to/data/inverse/2_model.lua", wx.wxFile.read):Length()
> 0

Yes, that's clearly wrong, but the issue seems to be in wxwidgets somewhere. How about `wx.wxFileSize("/path/to/data/inverse/2_model.lua")` and `wx.wxFile("/path/to/data/inverse/2_model.lua"):SeekEnd()`? I'm trying to figure out what to replace the current code with...

There are couple of interesting comments in the Length() method in wxwidgets:

```
    // we use a special method for Linux systems where files in sysfs (i.e.
    // those under /sys typically) return length of 4096 bytes even when
    // they're much smaller -- this is a problem as it results in errors later
    // when we try reading 4KB from them
#ifdef __LINUX__
    struct stat st;
    if ( fstat(m_fd, &st) == 0 )
    {
        // returning 0 for the special files indicates to the caller that they
        // are not seekable
        return st.st_blocks ? st.st_size : 0;
    }
    //else: failed to stat, try the normal method
#endif // __LINUX__
```

I'm not sure what's failing in this case, but it's possible that this is why 0 is returned (although I don't know why 552 bytes is better than 437).

**Comment by daviddoria** [comment]
wx.wxFileSize("/path/to/data/inverse/2_model.lua")
347

wx.wxFile("/path/to/data/inverse/2_model.lua"):SeekEnd()
347

If it matters, this is a GPFS file system.

**Comment by pkulchenko** [comment]
ok, I'll have a fix shortly, but this may be a problem with GPFS, not wxwidgets. If you try running `require('lfs').attributes("/path/to/data/inverse/2_model.lua")`, you'll get the number of `blocks` and it's probably 0 for "broken" files, whereas it should probably be 1. If it's 0, that's why `Length()` returns 0 (to avoid reading from char-based files).

**Comment by daviddoria** [comment]
require('lfs').attributes("/path/to/data/inverse/2_model.lua")
{access = 1431366729, blksize = 4194304, blocks = 0, change = 1431364876, dev = 38, gid = 1036, ino = 69064747, mode = "file", modification = 1431364876, nlink = 1, permissions = "rwxrwxr-x", rdev = 0, size = 347, uid = 127860} --[[table: 0x40c8ead8]]

By "char-based" files, do you mean text files? I guess I'm not sure why it would want to avoid reading those?

**Comment by pkulchenko** [comment]
> By "char-based" files, do you mean text files? I guess I'm not sure why it would want to avoid reading those?

No, I was thinking about char-special files/devices; according to the comment in that wxwidgets fragment I included earlier, the authors were trying to protect against reading files in `/sys` that may report incorrect length and then block or return errors on the subsequent reading.

In my case I'll switch to using the size as reported by the file system, which should return correct data.

**Comment by pkulchenko** [comment]
David, should be fixed now; please check. Thank you for the reporting and for the help with troubleshooting. You can migrate the patch to your version of ZBS-torch.

**Comment by daviddoria** [comment]
Works like a charm. Thank you for the quick help!
