### ISSUE TITLE
MoonScript?

### ISSUE THREAD

**Issue by kirbyfan64** [pkulchenko/ZeroBraneStudio#459]
Even though this is a Lua editor, MoonScript is pretty insanely close.

**Comment by pkulchenko** [comment]
@kirbyfan64, definitely ;). There is already support for MoonScript development. See this [plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/moonscript.lua) and this [description](http://notebook.kulchenko.com/zerobrane/moonscript-debugging-with-zerobrane-studio).

**Comment by kirbyfan64** [comment]
@pkulchenko I feel smart. :O

IMO, the home page should at least briefly mention it. Unless I missed that, too...

**Comment by pkulchenko** [comment]
There is mentioning of Moonscript in the section on general Lua debugging with a link to the blog post ;). I welcome suggestions on how to make it more prominent.
