### ISSUE TITLE
about large files

### ISSUE THREAD

**Issue by hhrhhr** [pkulchenko/ZeroBraneStudio#460]
Faced with the strange behavior of Lua 5.3 when opening large files (> 2 GB) (Win7 x64), it is impossible to work with numbers > *2147483647*:
````
d:\>E:\devel\ZeroBraneStudioEduPack-1.10-win32\bin\lua53.exe
Lua 5.3.0 (beta)  Copyright (C) 1994-2014 Lua.org, PUC-Rio
> r = io.open("bigfile.bin", "rb")
> r:seek("end")
-1
````
but if I use the same Lua in IDE, then everything is fine:
````
Welcome to the interactive Lua interpreter. Enter Lua code and press Enter to run it.
Use Shift-Enter for multiline code.  Use 'clear' to clear the shell output and the history.
Prepend '=' to show complex values on multiple lines. Prepend '!' to force local execution.
r = io.open("bigfile.bin", "rb")
r:seek("end")
3473798781
````

question: how it is done in IDE, that **file:seek()** work correctly with large files?

**Comment by pkulchenko** [comment]
ZBS is using LuaJIT internally and I can confirm that LuaJIT works as expected while both Lua 5.2 and Lua 5.3 return `-1` in this case. You may want to ask on the lua maillist as I'm a bit puzzled by this (all the interpreters are compiled for 32bit).

**Comment by pkulchenko** [comment]
It seems like the support for large files needs to be enabled explicitly on Windows: http://lua-users.org/lists/lua-l/2015-05/msg00370.html

**Comment by pkulchenko** [comment]
@hhrhhr, should be fixed now in the master branch.

**Comment by hhrhhr** [comment]
i'm very happy )
