### ISSUE TITLE
Analysis ignores API when analyzing a string

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#463]
When using the `AnalyzeString()` function, there's no way to provide the filename, and thus the analyzer doesn't fetch any API descriptions. This causes the string to report each API usage as unknown global.

**Comment by pkulchenko** [comment]
Hm, API descriptions are not taken into account at all during static analysis. Why is that an issue for `AnalyzeString`?

**Comment by madmaxoft** [comment]
They must be, because there's a difference in output when I use the Project -> Analyze command from the menu (which uses `AnalyzeFile()`) and my custom MCServer analysis (which uses `AnalyzeString()`) - in the first case the API symbols are not reported, in the second they are.
I think this is the relevant code in ZBS:
https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/inspect.lua#L46-L50

**Comment by pkulchenko** [comment]
You are right; I forgot about that part being added. So it seems `AnalyzeString` needs to be extended to take an optional filename as the second parameter. I'll add that.
