### ISSUE TITLE
Segfault on Ubuntu 14.04

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#464]
This has been reported by at least two users; there has been a somewhat similar report on ArchLinux (#425), but that one seems to be related to launching a new process during debugging and the crashes on Ubuntu happen sporadically during typing.

To assist with troubleshooting of this issue, the following steps may help:
- Enable saving of a core dump file by running: `ulimit -c unlimited`.
- Run ZBS as you'd do normally.
- When the crash happens, locate the `core` file either in `/opt/zbstudio` or in the current folder if running from a cloned repository.
- Change directory to the location of the core file.
- Run `gdb bin/linux/x64/lua core`; this will start gdb and will load the core file.
- Execute `bt` command in gdb, which will show the back trace when the issue happens.

Please include the stack trace from the crash, especially if you get different stack traces on different occasions.

**Comment by naturally-intelligent** [comment]
Thanks Paul, I'll try this out!

**Comment by pkulchenko** [comment]
Any additional information will help! Thanks!

**Comment by pkulchenko** [comment]
@naturally-intelligent, pushed couple of stability fixes, so would be interested if you still see the crashes (and their stack traces). Thanks!

**Comment by pip010** [comment]
I think I have same issue, first time running it was crushing constantly but now it took me ~48h to crash. Not sure if same. See attached coredump:
https://drive.google.com/file/d/0B0VFLi23PR9pYno0T1I1QTNxdGM/view?usp=sharing
on Ubuntu 14.04LTS
amd64
SIGSEGV
Cannot access mem 0x0
Hope it helps. I will try running from source.

**Comment by pkulchenko** [comment]
@pip010, thank you for the report. Can you try running `gdb bin/linux/x64/lua core` and then `bt` to get the stack trace in gdb? You may need to change directory to the location of the core file.

Also, were you running v1.10? If so, try running from the latest master snapshot.

**Comment by naturally-intelligent** [comment]
Got a core dump.  Now, I had to launch with this command (stripped from .sh file) for the ulimit command to take in the same terminal:

./bin/linux/x64/lua src/main.lua

**Comment by naturally-intelligent** [comment]
Reading symbols from bin/linux/x64/lua...(no debugging symbols found)...done.
[New LWP 26588]
[New LWP 26611]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/linux/x64/lua src/main.lua'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x2e0000004e) at malloc.c:2929
2929	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x2e0000004e) at malloc.c:2929
#1  0x00007fd9625f3297 in wxString::~wxString() () from bin/linux/x64/libwx.so
#2  0x00007fd96260e184 in wxLua_wxAuiToolBarItem_delete_function(void**) ()
   from bin/linux/x64/libwx.so
#3  0x00007fd9626d09c0 in wxluaO_deletegcobject(lua_State*, int, int) ()
   from bin/linux/x64/libwx.so
#4  0x00007fd9626c5fe4 in wxlua_wxLuaBindClass__gc(lua_State*) ()
   from bin/linux/x64/libwx.so
#5  0x000000000042d46e in ?? ()
#6  0x0000000000430c1c in ?? ()
#7  0x0000000000430ee2 in ?? ()
#8  0x0000000000431482 in ?? ()
#9  0x00000000004317e9 in ?? ()
#10 0x0000000000410f3d in lua_gc ()
#11 0x00000000004799c9 in ?? ()
#12 0x000000000042d46e in ?? ()
#13 0x000000000041093b in lua_pcall ()
#14 0x00007fd9626d3cbf in wxLuaState::LuaPCall(int, int) ()
   from bin/linux/x64/libwx.so
#15 0x00007fd9626c70dd in wxLuaEventCallback::OnEvent(wxEvent*) ()
   from bin/linux/x64/libwx.so
#16 0x00007fd9626c719e in wxLuaEventCallback::OnAllEvents(wxEvent&) ()
   from bin/linux/x64/libwx.so

**Comment by naturally-intelligent** [comment]
Another crash:
#0  __GI___libc_free (mem=0x2e0000004e) at malloc.c:2929
#1  0x00007fd9625f3297 in wxString::~wxString() () from bin/linux/x64/libwx.so
#2  0x00007fd96260e184 in wxLua_wxAuiToolBarItem_delete_function(void**) () from bin/linux/x64/libwx.so
#3  0x00007fd9626d09c0 in wxluaO_deletegcobject(lua_State*, int, int) () from bin/linux/x64/libwx.so
#4  0x00007fd9626c5fe4 in wxlua_wxLuaBindClass__gc(lua_State*) () from bin/linux/x64/libwx.so
#5  0x000000000042d46e in ?? ()
#6  0x0000000000430c1c in ?? ()
#7  0x0000000000430ee2 in ?? ()
#8  0x0000000000431482 in ?? ()
#9  0x00000000004317e9 in ?? ()
#10 0x0000000000410f3d in lua_gc ()
#11 0x00000000004799c9 in ?? ()
#12 0x000000000042d46e in ?? ()
#13 0x000000000041093b in lua_pcall ()
#14 0x00007fd9626d3cbf in wxLuaState::LuaPCall(int, int) () from bin/linux/x64/libwx.so
#15 0x00007fd9626c70dd in wxLuaEventCallback::OnEvent(wxEvent*) () from bin/linux/x64/libwx.so
#16 0x00007fd9626c719e in wxLuaEventCallback::OnAllEvents(wxEvent&) () from bin/linux/x64/libwx.so
#17 0x00007fd962963214 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from bin/linux/x64/libwx.so
#18 0x00007fd962963388 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from bin/linux/x64/libwx.so
#19 0x00007fd9629642de in wxEvtHandler::TryHereOnly(wxEvent&) () from bin/linux/x64/libwx.so
#20 0x00007fd962964341 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from bin/linux/x64/libwx.so
#21 0x00007fd9629643bd in wxEvtHandler::ProcessEvent(wxEvent&) () from bin/linux/x64/libwx.so
#22 0x00007fd96280a421 in wxAppBase::SetActive(bool, wxWindow*) () from bin/linux/x64/libwx.so
#23 0x00007fd96283ad75 in wxFrameBase::OnInternalIdle() () from bin/linux/x64/libwx.so
#24 0x00007fd9628949a7 in wxWindowBase::SendIdleEvents(wxIdleEvent&) () from bin/linux/x64/libwx.so
#25 0x00007fd9627f339f in wxFrame::SendIdleEvents(wxIdleEvent&) () from bin/linux/x64/libwx.so
#26 0x00007fd96280a36d in wxAppBase::ProcessIdle() () from bin/linux/x64/libwx.so
#27 0x00007fd9627b7ce7 in wxApp::DoIdle() () from bin/linux/x64/libwx.so
#28 0x00007fd9627b7d82 in ?? () from bin/linux/x64/libwx.so
#29 0x00007fd95f0b1b6d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fd95f0b1f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fd95f0b2272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007fd961610747 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#33 0x00007fd9627c155c in wxGUIEventLoop::Run() () from bin/linux/x64/libwx.so
#34 0x00007fd9628ec888 in wxAppConsoleBase::MainLoop() () from bin/linux/x64/libwx.so
#35 0x00007fd962647543 in ?? () from bin/linux/x64/libwx.so

**Comment by pkulchenko** [comment]
@naturally-intelligent, @pip010, pushed a fix that removed forced garbage collection, which should eliminate this issue. I still want to find a proper place for it, but for now want to have better stability.

Feel free to re-open if you see again a crash on the latest master; my apologies for the inconvenience.

**Comment by naturally-intelligent** [comment]
So far so good, no crashes lately.

**Comment by pkulchenko** [comment]
Good to hear; thanks for the update!
