### ISSUE TITLE
"doc-editor-keyboard-shortcuts" has a spurious note for OS X users.

### ISSUE THREAD

**Issue by IonoclastBrigham** [pkulchenko/ZeroBraneStudio#466]
The following is found at the bottom of the page:

    **Note for Mac OSX users**: in all these editor commands `Ctrl` means `Ctrl` key and not `Cmd` key as is mapped for menu commands.

I just tested this with the latest code from github master, and this is definitely not true. *All* of the shortcuts listed as `Ctrl-SOMETHING` actually map to `Cmd-SOMETHING` on OS X 10.8.5, *except* for the shortcuts for navigating your open tabs. Those ones actually are `Ctrl-TAB`, etc.

My first impulse was to just remove the note altogether, until I realized the tab navigation shortcuts were an exception. Not sure how to call this out correctly; perhaps a note at the top telling OS X users that `Ctrl` is pronounced "Command" for them, with another note down by the tab navigation entries calling out those exceptions?

If there's a consensus here (or an executive decision by @pkulchenko) I am more than happy to make a pull request. Else, anyone with write access is welcome to do it themselves.

**Comment by pkulchenko** [comment]
@IonoclastBrigham, thanks for the note. You are correct; fixed.

**Comment by IonoclastBrigham** [comment]
Actually, the `PgUp` and `PgDn` tab-navigation shortcuts also use the `Ctrl` key on a mac. In `src/editor/editor.lua` on [lines 1205 and 1210](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/editor.lua#L1205-L1214) explicitly checks for the `Ctrl` key in conjunction with either `Tab` / `PgDn` or `Shift-Tab` / `PgUp`. I've tested this and confirmed this is the behavior it displays.

It's probably best not to amend the commit just in case anyone's pulled the doc branch in the mean time, so another update to clarify this point is probably in order.

**Comment by pkulchenko** [comment]
Agree; fixed.
