### ISSUE TITLE
Lua error trying to drag files into directories in project view

### ISSUE THREAD

**Issue by IonoclastBrigham** [pkulchenko/ZeroBraneStudio#468]
When trying to drag a file in the project tab to a different directory the the tree, the following error is observed:

```
Lua: Error while running chunk
src/editor/filetree.lua:267: attempt to index local 'cache' (a nil value)
stack traceback:
	src/editor/filetree.lua:267: in function 'renameItem'
	src/editor/filetree.lua:703: in function <src/editor/filetree.lua:693>
	[C]: at 0x01051beb
	src/main.lua:706: in main chunk
	[C]: at 0x00001c80
```

This behavior is consistently reproducible on OS X 10.8.5, though I don't know this is Mac-specific. Possibly fixed by #260?

**Comment by pkulchenko** [comment]
@IonoclastBrigham, thank you for the report! Should be fixed now.
