### ISSUE TITLE
Autocomplete list is sorted alphabetically instead of by closest match

### ISSUE THREAD

**Issue by IonoclastBrigham** [pkulchenko/ZeroBraneStudio#469]
An example screenshot:

![completions](https://cloud.githubusercontent.com/assets/7422100/7791817/0849968c-025c-11e5-865c-beab2d2f0f36.png)

With `acandtip.strategy` set to the default of `2`, typing in `ret` brings up the completion list pictured above. While all of the given options do indeed have the three letters `r-e-t`, in that order, `return` seems pretty clearly to be the best possible option and should be sorted to the top of the list.

**Comment by pkulchenko** [comment]
I was just looking at the same results yesterday. I'll check what may be going on as I think it was working before.

**Comment by pkulchenko** [comment]
@IonoclastBrigham, should look better now. I've added taking the distance between the characters into account and ignoring the trailing characters, which was skewing the results previously.

**Comment by IonoclastBrigham** [comment]
Ok, so this is definitely an improvement. But consider the case where you type in `r-e`, with ZBS configured to search completions after 2 characters (which I think is the default).

    =CreateAutoCompList(GetEditor(), "re")
    "require return rawequal repeat rawget rawlen rawset"

`repeat` comes *after* `rawequal`. This makes sense, because the current pattern used for sorting does a greedy match for "not R followed by an E", which means the first 'E' in `repeat` gets consumed.

Seems to me it would be desirable to sort all items with an exact substring prefix match to the front of the list, descending by the length of the prefix, with simple alphanumeric collation for equal-length prefix matches. So for example, where we see:

    =CreateAutoCompList(GetEditor(), "ret")
    "return rawget rawset repeat"

...we would instead hope to see `"return repeat rawget rawset"`, where:

* `return` is first, because it has the longest prefix match of 3 ("ret"),
* `repeat` is next, because it has a prefix match length 2, and
* `rawget` and `rawset` come last because they both have a prefix match length 1, and 'g' sorts before 's'

I've created [a pull request](https://github.com/pkulchenko/ZeroBraneStudio/pull/471) that I'd like a review of. It implements this sorting order, and (I think) simplifies the code a little. In particular, I have updated the test, which it passes, but I'm not sure this covers all of the corner cases.

**Comment by pkulchenko** [comment]
> Seems to me it would be desirable to sort all items with an exact substring prefix match to the front of the list, descending by the length of the prefix, with simple alphanumeric collation for equal-length prefix matches.

That's a very good point; thank you for bringing it up! I should have included that change in my earlier patch.

I need to review the pull request in more detail (I'll comment in that ticket), but it seems like the effect you are describing can be achieved by making the pattern to be a non-greedy one. 

With the patch below applied I get:

```
> CreateAutoCompList(GetEditor(), "re")
"repeat require return rawequal rawget rawlen rawset"
```

This doesn't affect the results for "ret", which still suffer from not checking the prefix, so the update is still need to get `repeat` before `raw...`.

```
diff --git a/src/editor/autocomplete.lua b/src/editor/autocomplete.lua
index 6311c89..3561292 100644
--- a/src/editor/autocomplete.lua
+++ b/src/editor/autocomplete.lua
@@ -623,7 +623,7 @@ function CreateAutoCompList(editor,key,pos)
             num = num + 1
             local l = c:lower()..c:upper()
             -- don't include trailing characters
-            return "["..l.."]" .. (num < max and "([^"..l.." ]*)" or "")
+            return "["..l.."]" .. (num < max and "([^"..l.." ]-)" or "")
           end)

         table.sort(apilist,function(a,b)
 ```

**Comment by IonoclastBrigham** [comment]
I actually tried this first, too, and came to a similar conclusion. So I reverted it and changed the algorithm in a bigger way.
