### ISSUE TITLE
FileList shows CPP files with LUA icon

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#470]
When setting a project to a folder that contains both `.lua` and `.cpp` files, the `.cpp` files have the Lua icon. This makes it rather difficult to locate the `.lua` files in the list (I don't want to hide the `.cpp` files because my Lua scripts are working with them).
`.h` files behave in the same manner as `.cpp` files - they, too, have a Lua icon.

**Comment by pkulchenko** [comment]
Mattes, true; ZBS uses .lua icon for all the files with "known" extensions (and in this case .cpp and .h files are included in "known" extensions). What do you propose to do? I'd rather not to have a separate icon for each extension.

I'll see if I can generate some of those icons dynamically, but this may be problematic for a couple of reasons, although this would resolve this and similar issues.

**Comment by madmaxoft** [comment]
Dynamic icons would be really nice. Just have the extension written over the basic file icon, and use a color that is generated by hashing the extension (so that different extensions have different colors).

If that's not possible, is there a way to override the "known" extension list, so that `.cpp` files are not included in it?

**Comment by pkulchenko** [comment]
> Dynamic icons would be really nice. Just have the extension written over the basic file icon, and use a color that is generated by hashing the extension (so that different extensions have different colors).

I like this idea; I'll try it shortly...

> If that's not possible, is there a way to override the "known" extension list, so that .cpp files are not included in it?

That wouldn't be an easy change, but I'll consider it if dynamic icons are not going to work for some reason.

**Comment by pkulchenko** [comment]
Mattes, I ran into a strange issue with wxwidgets that doesn't allow me to draw a text over a bitmap loaded from a file. Here is the simplest example I could come up with that is not working:

```lua
require "wx"

local bitmap = wx.wxBitmap("icon.png")
local mdc = wx.wxMemoryDC()
local font = wx.wxSWISS_FONT
font:SetPointSize(6)

mdc:SelectObject(bitmap)
mdc:SetFont(font)
mdc:SetTextForeground(wx.wxRED)
mdc:DrawText("lua", 2, 3)
mdc:SelectObject(wx.wxNullBitmap)
bitmap:SaveFile('done.png', wx.wxBITMAP_TYPE_PNG)
```

Copy any of the png files from ZBS into `icon.png` and look at the result (`done.png`). What I see on Windows is the transparent area where the "lua" text should be. If I replace `wxBitmap("icon.png")` with `wxBitmap(16,16)`, I get "lua" text in red over black background. I don't need to save, but I get the same result when showing the bitmap instead of saving.

Any idea on what I'm doing wrong? It's probably something simple, but I can't figure out what it is...

**Comment by pkulchenko** [comment]
Another example; comment the marked line out to get "lua" text over transparent background:

```lua
require "wx"

local bitmap = wx.wxBitmap(16, 16)
local mdc = wx.wxMemoryDC()
local font = wx.wxSWISS_FONT
font:SetPointSize(7)

mdc:SelectObject(bitmap)
mdc:SetFont(font)
mdc:SetBackground(wx.wxBLACK_BRUSH)
mdc:Clear()
mdc:DrawBitmap(wx.wxBitmap("icon.png"), 0, 0, true) -- comment this out
mdc:SetTextForeground(wx.wxRED)
mdc:DrawText("lua", 1, 2)
mdc:SelectObject(wx.wxNullBitmap)

local mask = wx.wxMask(bitmap, wx.wxBLACK)
bitmap:SetMask(mask)
bitmap:SaveFile('done.png', wx.wxBITMAP_TYPE_PNG)
```

**Comment by madmaxoft** [comment]
As far as I know, your second piece of code is the right way to do it - you need to create a temporary bitmap for holding the DC's contents, and then draw the file icon there. So the second snippet should be working, isn't it?

**Comment by pkulchenko** [comment]
Yes, it should be working, but doesn't work for some reason. I haven't tested on other platforms yet, so don't know if it's Windows-specific or something deeper in wxwidgets.

**Comment by madmaxoft** [comment]
I have found some bits of information scattered around the web that wxMSW doesn't like alpha-channel too much. And indeed when I saved the `icon.png` file as a 24-bit PNG without alpha channel, the code started to work. Since you're masking anyway, this might be the way to go.

**Comment by pkulchenko** [comment]
Are you saying you got it working? What was the exact change I can try?

**Comment by madmaxoft** [comment]
Yes, it's working for me, I didn't modify the code, I only modified the input image. Here's a working version that you can try: http://mc-server.xoft.cz/SynthBitmap/

A note if you decide to go further: The extensions are not limited to 3 chars, for example Visual Studio uses `.vcxproj` and `.filters` extensions, which simply don't fit onto the icon.

**Comment by pkulchenko** [comment]
Of course it works; you cheated ;). You removed transparency from the source bitmap, but I need it, so that the target bitmap still preserves the transparency. I still can't figure out how to draw it correctly when the source bitmap has alpha transparency "on" (and neither `wxImage:ClearAlpha()` nor `wxImage:ConvertAlphaToMask()` are available in this version of wxlua).

**Comment by madmaxoft** [comment]
Of course, that's the point, removing the transparency helped the issue exactly because the transparent images cannot be drawn in wxMSW. But the final image has a mask, so it does have the transparency again, it should be possible to use it.

**Comment by pkulchenko** [comment]
Yes, I got that, but is there a combination of wxwidgets calls that removes the transparency from the files that have them (I don't want to modify the files I have)? I even tried to go pixel by pixel, but that didn't work either...

**Comment by madmaxoft** [comment]
I have found none, but then, you don't have a good source image anyway, so you might as well add a new one, exactly as this function needs it.

**Comment by pkulchenko** [comment]
Yes, I can do that, but I was hoping to find a solution I can use in other places as well. I'll come back to this after #260, which will add those missing methods.

**Comment by pkulchenko** [comment]
@madmaxoft, it seems like the issue with transparency we discussed in this ticket is a [wxwidgets issue #14403](http://trac.wxwidgets.org/ticket/14403). I'll retest following wxwidgets upgrade.

**Comment by pkulchenko** [comment]
@madmaxoft, I got the extensions shown in the icons and also added picking a color based on the extensions. It's not always distinct for different extensions, but you can set your own color in the mapping for a particular extension (and it should work well out of the box for various extensions I tried).

**Comment by madmaxoft** [comment]
The font is somewhat funky, but I guess that's not a big issue. I think the color picking is unfortunate, two extensions that are close to each other lexically are close together color-wise, too. For example, `.cmd` and `.cmake` files are both blue. I suppose some kind of a hash would have been more distinctive for this. Still, it's good enough :)

Thanks.

**Comment by pkulchenko** [comment]
> I suppose some kind of a hash would have been more distinctive for this. Still, it's good enough :)

@madmaxoft, I tried to come up with some hash, but the problem is not just the hash, it's the mapping of that hash to the colors that are (1) distinct enough, so different extensions have different colors, and (2) visible on that background. I tried to map the hash results to HSV colors (as it allows to work with hue and keep SV constant), but it wasn't still good enough. If you can come up with a better logic, I'll definitely consider it ;).
