### ISSUE TITLE
Feature; switch Output tab to front on error

### ISSUE THREAD

**Issue by ajbrouwer** [pkulchenko/ZeroBraneStudio#472]
In ZBS 1.10, when the Local Console or Watch tabs are at the front, a compile error resulting from running a script will be displayed in the Output tab, but this tab remains hidden. In this case, it would be helpful were the Output tab to be switched to front. It would be more helpful yet were the error to be highlighted there.

Consider other conditions for which bringing the Output tab to front may be the preferable behaviour, e.g. a runtime error.

**Comment by pkulchenko** [comment]
This could be useful, but it's problematic for a couple of reasons. I tried to check for the error code from the process, but Lua interpreters always return 0 (unless there is explicit `os.exit()` call with a different value), even when there is a run-time error. I'd prefer to stay away from analyzing the text in the Output panel, which makes the detection of errors difficult.

I may add Output filtering in the future, which will allow the user to set up an action or modify the Output to suit their needs. For now, something like this in the config file will enable you to activate the output each time something is printed there:

```
local G = ...
package {
  onAppLoad = function()
    local DOL = G.DisplayOutputLn
    G.DisplayOutputLn = function(...) G.ActivateOutput() DOL(...) end
  end
}
```

You can customize it further by checking the string value being added.

**Comment by ajbrouwer** [comment]
Hi Paul,

Thanks. Works for me.

Excellent how customizable ZBS is. I have accumulated a few configurations and packages by now, and as it is all just lua scripts, the configurability has not burned the GUI or required learning a new thing.

With kind regards / Met vriendelijke groeten,

Albert-Jan

**Comment by pkulchenko** [comment]
@ajbrouwer, good to hear it's working well for you. Just a small warning; since it's using two internal functions, their API may change in the future. I generally try to limit all public API calls to methods of the `ide` object, but there are still some areas that are not covered by the API, so that's why I offered this solution.
