### ISSUE TITLE
Undocumented shortcuts?

### ISSUE THREAD

**Issue by pnon10s** [pkulchenko/ZeroBraneStudio#475]
Pardon my ignorance. I occasionally accidentally collapse all sections of code and have not found documentation to (un)collapse code.

!. What are the shortcuts and where are they documented?

2. Side issue: I haven't found a way to refresh the Project View without closing/opening ZeroBrane.

Thanks for your help, Rocky
--love zerobrane, have donated

**Comment by pkulchenko** [comment]
@pnon10s, I welcome suggestions on where these can be documented, but I'd rather not duplication shortcuts from the menu in the documentation.

> I occasionally accidentally collapse all sections of code and have not found documentation to (un)collapse code.

If you mean Fold/Unfold, then the same shortcuts does both (`F12`). It actually has three positions: (1) collapse all top level branches, which shows you the overall structure of the file, (2) remove all comment/text lines at the top level, which leaves only collapsed branches, and (3) expand everything. Step 2 may be skipped if there are no comment/text lines.

> I haven't found a way to refresh the Project View without closing/opening ZeroBrane.

There are several ways: (1) v1.10+ includes "Refresh" menu item in the project tree popup menu, (2) you can always collapse/expand a particular branch, which will refresh it, (3) if you are on Windows, you can install [Refresh Project](https://github.com/pkulchenko/ZeroBranePackage/blob/master/refreshproject.lua) plugin, which will keep the project tree auto-refreshed by monitoring file system changes.

> What are the shortcuts and where are they documented?

In general, all the shortcuts are documented in `src/editor/keymap.lua`; these are the same shortcuts you see in the menu, so they are not in the documentation. You can also check [this page](http://studio.zerobrane.com/doc-editor-keyboard-shortcuts) for editor shortcuts.

I should probably add the first two answers to the FAQ.

**Comment by pnon10s** [comment]
Yup. F12 next to backspace. Been playing piano for 60 years and still hit double keys sometimes. Never would have guessed 'fold' hidden in a sub-menu without trying everything.

Also, I got stuck on the idea that if closing/opening the project window didn't refresh, nothing else would (didn't see the popup menu til now). I should have guessed that the project window was hidden and not really closed.

I learned a few things. I hope something here might help you help others. No need to answer this. 

Thanks! Rocky

**Comment by pkulchenko** [comment]
These are good points; ability to discover how to do things is an issue. I do plan to add fuzzy search for menu items and configuration settings (similar to how fuzzy search works for files and symbols).

This would (in the future) allow you to type "fold" and see the menu items related to that (and possible configuration settings as well).

I still think that project tree refresh should be covered in the FAQ. Also, there is [tips-and-tricks document](http://studio.zerobrane.com/doc-tips-and-tricks) that includes features not covered elsewhere (although it needs to be updated with recently added features).
