### ISSUE TITLE
ctrl g is very slow on linux

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#476]
freezes zerobrane up to 5 seconds and when it does show up it isnt focused

using debian and lxde

**Comment by pkulchenko** [comment]
That's very strange and there shouldn't be any processing as this just take a line number. It shouldn't even check the current file. Is it consistent? How about `Ctrl-P` and `Ctrl-G`; are they equally slow?

**Comment by CapsAdmin** [comment]
ctrl p is fine

**Comment by pkulchenko** [comment]
@CapsAdmin, should be fixed now; thank you for the report.
