### ISSUE TITLE
Multiline tab indenting is very slow

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#477]
seemed to be last time i tried zerobrane as well (a year or two ago)

**Comment by pkulchenko** [comment]
@CapsAdmin, how many lines are we talking about (both selected and in the file)? I tried on several files and didn't see much slowdown...

**Comment by CapsAdmin** [comment]
just by guessing 50 lines is 1.5 sec, 100 is 3 sec etc

**Comment by pkulchenko** [comment]
@CapsAdmin, should be much faster now on multi-line changes. Let me know if you notice any issues with it.
