### ISSUE TITLE
Enable compile and analyze during launched process

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#479]
i see no reason for these to be disabled when launching a process

my project will reload lua files as i edit them so this gets in the way and as i understand some of the supported intepreters may allow this

is there maybe something i need to enable?

ps: sorry if im making duplicate requests. im on a unstable 3g connection on my phone

**Comment by pkulchenko** [comment]
@CapsAdmin, do you propose to enforce static analysis when running/debugging?

**Comment by CapsAdmin** [comment]
the compile and analyze option under project is greyed out during debug and
run. the user chooses when to run these tools but im not allowed by the
editor. so i propose that we should be allowed to do this whenever as it
doesn't (or shouldn't?) interfere with anything

**Comment by pkulchenko** [comment]
Oh, I misunderstood. Yes, it makes sense. I'll check why it's disabled when running/debugging.

**Comment by pkulchenko** [comment]
The only issue I see so far is that the Output panel is cleared when `Compile` or `Analyze` are used. Is that a problem?

**Comment by pkulchenko** [comment]
Enabled both compilation and static analysis, but I may still disable clearing of the Output window during running/debugging. What do you think?

**Comment by CapsAdmin** [comment]
yeah that makes sense

**Comment by pkulchenko** [comment]
ok; I'll update both to keep the output when running/debugging.
