### ISSUE TITLE
minor live analyzer issues

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#480]
there should be a tooltip when hovering over underlined words. i don't know what the dotted underline means but i guessed the straight underline means unused or unknown variable.

~~i have my own globals. how should i tell zerobrane about these?~~ (the uhro3d plugin shows me how) maybe there should be an option to disable checking globals?

~~how can i also completely turn off these underlines?~~ (figured it out in the docs)

**Comment by pkulchenko** [comment]
@CapsAdmin, this is an interesting suggestion about tooltips for global/local variables. Dotted underline means a local variable; straight is global; dashed means this local variable is shadowing some other local variable at the same scope; and strike-out means that this local variable is being shadowed by some other local variable.

To disable indicators, set any of them to `nil`; you can selectively disable some of them.

**Comment by pkulchenko** [comment]
@CapsAdmin, probably not for the underlined words as the tooltip becomes too chatty and a bit annoying. I think I'll make sure I cover the indicators in the documentation.

**Comment by pkulchenko** [comment]
Updated FAQ to add [details on scope indicators](http://studio.zerobrane.com/doc-faq#what-are-the-dotted-and-dashed-lines-under-variable-names).
