### ISSUE TITLE
add ULL and LL number annotation support for the analyzer (luajit)

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#482]
the compiler supports it but the analyzer doesn't

**Comment by pkulchenko** [comment]
It's not just the analyzer, as the loose parser also needs to take that into account.

Where is the documentation on these numbers in LuaJIT?

**Comment by CapsAdmin** [comment]
see bottom of http://luajit.org/ext_ffi_api.html
