### ISSUE TITLE
suggesion: complete portability

### ISSUE THREAD

**Issue by SammaySarkar** [pkulchenko/ZeroBraneStudio#483]
is there an option to gain complete portablility, so that settings that would be normally written to homepath are instead placed in,say, a 'usr' folder in the application's folder?

**Comment by pkulchenko** [comment]
@SammaySarkar, there is `ini` option that allows you to specify the location of the ini file. You can pass that option as a command-line parameter (`-cfg "ini=/my/zbs.ini"`), which will configure the IDE to use it. See the [documentation](http://studio.zerobrane.com/doc-general-preferences) for details.

One possible improvement is to allow a relative path, as currently only the absolute path will overwrite the folder (the relative path is interpreted as relative to the "default" location).

I think there has to be three choices: (1) absolute path (with an optional file name): sets new location, (2) relative path with a file name: sets new location relative to the "default" one, (3) relative path without a file name: sets new location relative to the current ZBS folder.

**Comment by SammaySarkar** [comment]
> I think there has to be three choices: ...

right, relative paths should be relative to zbstudio. Plus a 4th choice: if a 'portable' file exists beside zbstudio executable, save settings in zbs folder by default.

> there is ini option that allows you to specify the location of the ini file. You can pass that option as a command-line parameter (-cfg "ini=/my/zbs.ini"), 

Thanks! I wrote that setting right into my system-wide settings file.

**Comment by pkulchenko** [comment]
So, it seems like the logic is going to be as follows:

1. if `ini` value is a filename with no path, the open it in the same location as the current .ini file location, but with a different name.
2. if `ini` value is an absolute filename, then open it with that filename.
3. if `ini` value is a relative filename, then open it relative to ZBS folder.

I haven't decided yet what to do if only a filepath (without a filename) is provided and it may be not supported.

@SammaySarkar, I'm not sure about the 4th choice; looks like too much "magic". I think you can easily emulate that with providing zbportable batch/shell file that runs zbstudio with the `cfg` option set as needed.

**Comment by SammaySarkar** [comment]
:smiley: okay.

**Comment by pkulchenko** [comment]
Will push tomorrow; just need to add a couple of checks...

**Comment by pkulchenko** [comment]
@SammaySarkar, should be all done now. Give it a try.

**Comment by SammaySarkar** [comment]
one problem
````lua
ini = "./zbs.ini"     -- creates in app folder. OK
ini = "zbs.ini"       -- creates in defaultpath. OK
ini = "./ini/zbs.ini" -- creates in [pre-existing] app/ini/ folder. OK
ini = "ini/zbs.ini"   -- creates in [pre-existing] app/ini/ folder. not OK
````

**Comment by pkulchenko** [comment]
> ini = "ini/zbs.ini"   -- creates in [pre-existing] app/ini/ folder. not OK

@SammaySarkar, this is by design. Only values that include just the file names will be created in the default path; all other relative values that include path will be created relative to the IDE folder. Absolute paths will be absolute.

I think it's easier to manage and explain as technically there is no difference between `ini/zbs.ini` and `./ini/zbs.ini`.

**Comment by SammaySarkar** [comment]
Alright. All :+1:  then. Thank you.
