### ISSUE TITLE
How to jump to a breakpoint in another script file 

### ISSUE THREAD

**Issue by xzzh999** [pkulchenko/ZeroBraneStudio#484]
Hi,bigcow,here's my situation:  I have a folder which have many lua script files(they are all in one folder),when i debuging them, i found the breakpoint only hit in the entry script, i can't jump to another
break point which in another script file, like this followed:
   
     "c++ app" --->"entry.lua"         -- <breakpoint worked>
                     --->"test.lua"           -- <breakpoint not worked>
here "entry.lua" called a function in "test.lua",and in c++ app i use a wrapped lua_pcall to call "entry.lua".
(forgive pool ENL)

please help, thank you~

**Comment by pkulchenko** [comment]
@xzzh999, check the [FAQ item on breakpoints](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered).

Please don't open ticket if you have a question; there are [better ways to handle that](https://studio.zerobrane.com/community). The tickets are for issues and enhancements.

**Comment by xzzh999** [comment]
Thank you very much, finally i solved the problem. At the begining i already look checked the FAQ links you given but still have no idea, then i read the issues list, found the relative link: #212 .

I add "debugger.verbose = true" to "user.lua", and found i choosed the wrong directory(i choosed the lua script folder), i should choose the lua vm (the .exe's running folder), then everything works fine. Thanks!

**Comment by pkulchenko** [comment]
@xzzh999, thank you for the update. I added `debugger.verbose=true` to the [FAQ item](http://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered).
