### ISSUE TITLE
Separate actions of  ID.STARTDEBUG button (F5).

### ISSUE THREAD

**Issue by johnd0e** [pkulchenko/ZeroBraneStudio#486]
The button (and corresponding command in Project menu) has combined action: Start or continue debugging.

But due to specific of my project I need only one action - "continue", and start command is useless.
Is it possible to implementate separate "continue" action?

**Comment by pkulchenko** [comment]
@johnd0e, you probably mean `ID.STARTDEBUG`, not `ID.RUN`. If the start command is useless, why does it get in the way? Why would you want to change that?

If the debugging has already been started, then the action will only be limited to continue, which is what you want.

I think part of the changes you want to make stem from the fact that you may want to start debugging from the outside of the IDE (for example, from a FAR plugin); you may have more control over what happens in the IDE if you have your own interpreter that deals with these cases.

If you provide details about specific use cases you want to handle, I may be able to suggest how to handle it better.

**Comment by johnd0e** [comment]
> you probably mean ID.STARTDEBUG

My bad (


> If the start command is useless, why does it get in the way?

Because I press it sometimes accidently (when not pay attention that debugging is not started).
And I cannot remove it from toolbar as it's second action (continue) is essential.


> If you provide details about specific use cases you want to handle, I may be able to suggest how to handle it better.

I am mostly happy with my current setup.
To start debugging I use macro in FAR manager (I also have other macros [there](http://forum.farmanager.com/viewtopic.php?p=117004#p117004)).

**Comment by pkulchenko** [comment]
> Because I press it sometimes accidently (when not paying attention that debugging is not started yet).
> And I cannot remove it from toolbar as it's second action (continue) is essential.

You can overwrite `UPDATEUI` handler for the button, which will disable it when the debugging is not started and only enable during debugging to handle your case.

Also, as I suggested, if you have your own interpreter, you can ignore "start debugging" command, which means that you don't need to modify any of the handlers. It would have some other benefits too and [can be implemented as a plugin](http://studio.zerobrane.com/doc-plugin#registering-an-interpreter).

**Comment by johnd0e** [comment]
> You can overwrite UPDATEUI handler for the button

How should I do it? (I tried to find it in sources, but it seems belong to wx)

**Comment by pkulchenko** [comment]
Here is a short example:

```lua
ide:GetMainFrame():Connect(ID.STARTDEBUG, wx.wxEVT_UPDATE_UI, function(event)
  event:Enable(mycondition and true or false)
end)
```
