### ISSUE TITLE
add a way to hide the menu bar

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#488]
many editors have this. you can usually unhide the menubar by pressing alt

ide:GetMainFrame():GetMenuBar():Hide() and :Show() seems to work fine

**Comment by pkulchenko** [comment]
Elias, unfortunately, there is no good consistent way to do this. `Hide`/`Show` combination doesn't work on Windows. The recommended way to do this is to use `ide:GetMainFrame():SetMenuBar(wx.wxMenuBar())`, but in either case hiding the menu bar disables any shortcuts that a linked to the menu bar (even if they are present in other places, like toolbars).

The only way I see to keep using the shortcuts is to assign them to the accelerator table (`wxAcceleratorTable`) for the main frame, but this is cumbersome as wxwidgets doesn't provide a way to get the current values from the accelerator table, so it only works one way. This is complicated by the fact that plugins may add their own menu items and those need to be transferred to the accelerator table as well.

In the end, it may be doable, but it's quite a bit of work for little benefit.
