### ISSUE TITLE
Wrong underline in table definitions

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#492]
When a table definition contains a reference to a global value, the next key gets the wrong underline:
![zbs_bad_underline](https://cloud.githubusercontent.com/assets/4388386/8263023/7ad5922a-16d7-11e5-955d-608811cba91a.png)
My expectation is that `valuec` should have no underline at all.

**Comment by pkulchenko** [comment]
Mattes, thank you for the report. It's a bit of a tricky case, but should be fixed now. I also fixed couple of related cases.
