### ISSUE TITLE
'Go to function definition' context menu option?

### ISSUE THREAD

**Issue by pnon10s** [pkulchenko/ZeroBraneStudio#494]
1. How about a context menu option to go to the function definition when a function call is right-clicked?

2. I like auto-suggest but, quite often, when I hit line return I get an autocomplete instead of the line return I was expecting. Is highlighting the first suggestion really the most efficient behavior? (maybe it is, what do I know?)

**Comment by pkulchenko** [comment]
> How about a context menu option to go to the function definition when a function call is right-clicked?

@pnon10s, it's already available as `Go To Definition (on line X)`, but only for functions in the same file. 

> I like auto-suggest but, quite often, when I hit line return I get an autocomplete instead of the line return I was expecting. Is highlighting the first suggestion really the most efficient behavior?

I think this is what most users expect. I can probably check for `Shift-Enter` or `Ctrl-Enter` and don't do any substitution.

**Comment by madmaxoft** [comment]
Quite frankly the auto-suggest doesn't work too well. Consider the following code:
```lua
local name = obj:GetName()
local namelen = #name
```
As soon as I type this out, ZBS gives me an autosuggest list with only "namelen" in it, so when I press enter to go to the next line, it actually changes my code to the nonsensical `local namelen = #namelen`

**Comment by pkulchenko** [comment]
Mattes, what are you proposing? I can think only of two options: (1) Allow `Shift-Enter` to close without selecting (I need to check if I can detect that), and (2) Hide auto-complete if what's typed matches one of the options (this will hide it after `name`, but will show again after `namel`).

Any other ideas?

**Comment by pkulchenko** [comment]
Another option is to include `name` in the suggestions even when `name` is already typed (this option is currently hidden), which will allow you to use `Enter` to select it.

**Comment by pnon10s** [comment]
When I right-click on a function call, 'Rename All Instances' lights up but 'Go To Definition' never lights up. I do everything in one file. I have never seen 'Go To Definition' lit up.

I will hit space before line return if i don't want autocomplete. But, if there were an option to click or have to hit down arrow before the first suggestion highlights, I would probably check it.

Thanks

**Comment by pnon10s** [comment]
P.S. 'Rename All Instances' is great. It has made my code a lot cleaner. The auto-suggest is handy then so that I don't choose an existing name.

**Comment by madmaxoft** [comment]
I think `name` should be included in the suggestions, too.

**Comment by pkulchenko** [comment]
I tried it both ways and I think it's better to hide auto-complete after typing a matching word (`name` in this case). This has already been implemented; will push shortly.

**Comment by pkulchenko** [comment]
Using `Shift-Enter` when auto-complete popup is shown will emulate enter and ignore the selection.

**Comment by pnon10s** [comment]
I can't figure out why 'Go To Definition' never highlights. Thanks - Rocky

**Comment by pkulchenko** [comment]
@pnon10s, I'll need a specific example; you are probably trying to use it with global functions, which don't have "definitions".

**Comment by pnon10s** [comment]
I want to right-click myfunction and jump to the function definition.
. . .
myfunction()
. . . 
function myfunction()
end

**Comment by pkulchenko** [comment]
You will be able to do this if it's a local function. Global functions don't have "definitions". If you have the following and click on `myfunction`, you'll be able to jump to its definition:

```lua
local function myfunction()
end
...
myfunction()
```

**Comment by pnon10s** [comment]
This is not that important and getting out of hand, but if you're interested:

1. When I put 'local' in front of a function, 'Go To Definition' only lights up if I click reference calls which come AFTER the definition and not BEFORE.
2. I cannot make many of my functions local because then VLC (the compiler) cannot see into the functions for VLC requests.
3. Without understanding the definition of 'definition', I don't see why ZeroBrane can't just jump to any 'function myfunction() end' definition in the current file from any reference call in the file.

I can live without this. Thanks for all your help.

**Comment by pkulchenko** [comment]
> When I put 'local' in front of a function, 'Go To Definition' only lights up if I click reference calls which come AFTER the definition and not BEFORE.

Right; you can't use it if the reference is before the definition.

> I cannot make many of my functions local because then VLC (the compiler) cannot see into the functions for VLC requests.

This is not mutually exclusive; what I usually do is the following:

```lua
local function mylocalfunction()

end
...
mylocalfunction()
...
myglobalfunction=mylocalfunction
```

I put all the *interface* functions at the bottom and it makes it clear what API is exposed and also makes all references to work as you expect.

> Without understanding the definition of 'definition', I don't see why ZeroBrane can't just jump to any 'function myfunction() end' definition in the current file from any reference call in the file.

Because it's not possible to confirm that this is the "definition" that is going to be used. What if you have another global function with the same name in a different file? With locals I can at least do the analysis and find a properly scoped definition.

I'm not saying this is not going to change, just provide rationale for the decisions that have been made so far.

**Comment by pkulchenko** [comment]
BTW, there is also `Outline` tab (next to the `Project` tab) that shows all functions in the current file, which allows for easy navigation. You can move that panel somewhere else too.

**Comment by pnon10s** [comment]
yes, i use that panel. but ZeroBrane has allowed me to make my program so complex that i forget where everything is. haha. and since it is an 'outline', you can't sort the function list in it.

what i'll do is highlight the function call, press ctrl-f and then type 'n ' in front of the name before searching. good enough. thanks

**Comment by pkulchenko** [comment]
@pnon10s, you can have the outline functions sorted (`outline.sort=true`); see the [outline configuration options](http://studio.zerobrane.com/doc-general-preferences#outline).

> what i'll do is highlight the function call, press ctrl-f and then type 'n ' in front of the name before searching. good enough.

This works, but I have a much better option for you. When you are on a function call, click `Ctrl-B` (fuzzy search for symbols). Usually the first option is where the definition is (if it's in the same file). It even recognizes functions defined as table fields (it uses the same information as the outline). I plan to make it work across the files too, which should give you everything you need.

**Comment by pnon10s** [comment]
that all works. thanks! case closed.

**Comment by pnon10s** [comment]
this might drive you crazy. sorry.

my file has almost 100 functions. often, i want to go to a function in the outline that has no references currently in my code view. if i remember the exact name, i wish the functions were alphabetical. if i remember the grouping i put it in, i wish the functions were in appearance order. in other words, i wish i could dynamically change the order of the outline.

iust saying. thanks.

**Comment by pkulchenko** [comment]
It shouldn't be difficult to change the order. You can write a simple plugin that will attach the following to a shortcut:

```lua
ide.config.outline.sort=not ide.config.outline.sort; OutlineFunctions(ide:GetEditor())
```

This will change the sorting and refresh the current panel using that sorting; for testing purposed you can simply run this code in the local console. Note that `OutlineFunctions` is not in the public API, so it may change in the future.

You can look at the package repository for examples on how to create a new menu item for this. If it works well, I can probably add it to the popup menu in the Outline.

**Comment by pkulchenko** [comment]
@pnon10s, I added ability to toggle sorting from the popup menu in the outline. Let me know how it works.

**Comment by pnon10s** [comment]
I added the highlighted code to ids.lua and outline.lua, but it can't find the function SetStatus.

We're getting close...

**Comment by pkulchenko** [comment]
@pnon10s, you don't need to add any code; you can get the current version from github (for example, clone the repository or get the zip file) and it should all work. `SetStatus` method has been added recently, so you need the version from the current master branch.

**Comment by pnon10s** [comment]
All the new features have really helped my searches. Thank you very much.

**Comment by pnon10s** [comment]
I put dummy functions in the outline to act as spacers.
local function z______mygroup______ ; end  -- spacer
Much easier on my brain when searching the outline. Switching sort is awesome.
