### ISSUE TITLE
tabs and toolbar pixelated on retina display.

### ISSUE THREAD

**Issue by alikoubeissi** [pkulchenko/ZeroBraneStudio#497]
Hey, I just installed the IDE and the tabs and toolbar are pixelated. I'm running it on Mid 2014 Macbook pro 15.4".

It's not really a big issue but it's very annoying. Is there anything that can be done in the configuration files or something?

**Comment by pkulchenko** [comment]
@alikoubeissi, could you post a screenshot? Doesn't need to be the entire screen; just enough to see the toolbar, a tab, and a fragment of the editor in the tab?

Also, could you try with a [newer version of wxlua](https://download.zerobrane.com/libwx-osx-3.1.0.zip) to see if it makes any difference? Just replace that file in the `bin` folder and restart the IDE.

**Comment by alikoubeissi** [comment]
@pkulchenko thank you for the prompt reply. I will download wxlua and try it out. Here's a screenshot ![screenshot]( http://i.imgur.com/OK8wASX.png)

**Comment by pkulchenko** [comment]
Yes, I see it; the update may change the tabs, but not the toolbar. The toolbar requires double-resolution images, but I remember that I ran into issues when I attempted to include them. I'll check what the issue was.
