### ISSUE TITLE
how to switch interpreters in Linux?

### ISSUE THREAD

**Issue by Henry214** [pkulchenko/ZeroBraneStudio#502]
HI, all,

I am new to the tool. I see many tutorials saying that one can change interpreters by the following:
Start the debugger server from "Project->Start Debugger Server"
Change the interpreter to Torch-7 "Project->Lua Interpreter->Torch-7" 
...

However,  I find no "project" and any common icons such as File, Edit... (http://notebook.kulchenko.com/images/zerobrane-studio-in-black.png)

I use ubuntu14.04. Any hints?
thanks
Henry

**Comment by gogoprog** [comment]
Do you mean you have no "Project" menu in the top menu bar?

Because there is in the screenshot you gave

**Comment by Henry214** [comment]
In my case, no "Project" menu in the top menu bar.
That screenshot is not mine. I just put it to show the normal case I see from other sites.

My screenshot is as follows:
https://goo.gl/9EZUTZ

Any hints?
Thanks

**Comment by madmaxoft** [comment]
Isn't this the normal Ubuntu behavior that it hides the menubar / moves it to the top of the screen? If you move your mouse over to the very top of the screen, does the menu appear there?

**Comment by Henry214** [comment]
It works! Never thought that the menubar hided there. 
Thank you all !!
henry
