### ISSUE TITLE
Unknown global variable 'arg' during analysis

### ISSUE THREAD

**Issue by DenisKolodin** [pkulchenko/ZeroBraneStudio#503]
During analysis this working script:

    print(arg[1])

I catch the message:

    Analyzing the source code: 1 warning.
    ..\argtest.lua:1: first use of unknown global variable 'arg'

This way it works:

    print(_G.arg[1])

Maybe add **arg** as extra exclusion?

**Comment by pkulchenko** [comment]
Done; thank you for the report.
