### ISSUE TITLE
Switchable decimal/hexadecimal format for integer representation inside Watch window

### ISSUE THREAD

**Issue by TylerD83** [pkulchenko/ZeroBraneStudio#504]
Hi,
since I utilize ZeroBrane Studio and Lua scripts in order to interact with hardware modules, I sometimes would like to watch integer values in hexadecimal format. It would be great if the integer representation could be switched between decimal/hexadecimal format in one of the next ZBS updates.

**Comment by pkulchenko** [comment]
>  I sometimes would like to watch integer values in hexadecimal format. It would be great if the integer representation could be switched between decimal/hexadecimal format in one of the next ZBS updates.

@TylerD83, add the following to the config file and all the numbers during debugging will be shown in hexadecimal format:

```lua
debugger.init = [[
  local mdb = require('mobdebug')
  mdb.origline, mdb.line = mdb.line, function(v) return mdb.origline(v, {numformat = "0x%x"}) end
]]
```

To switch back you'll need to reset `debugger.init` back to an empty value. This will affect all the numbers shown in the Watch, Stack, tooltips, and Remote Console windows.

**Comment by pkulchenko** [comment]
With a bit more effort it may be possible to make a plugin to add a new menu item to the watch or the main menu (to switch between hex/decimal numbers).
