### ISSUE TITLE
Linux: Crash after creating files/folders

### ISSUE THREAD

**Issue by zorfmorf** [pkulchenko/ZeroBraneStudio#506]
Whenever I create a new file or folder via zbstudio, it will soon crash afterwards with the following error message (the warning is from startup, but I included it, incase it might be relevant):

    12:54:33: Warning: Mismatch between the program and library build versions detected.
    The library used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8), and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
    
    ** (lua5.2:1186): CRITICAL **: murrine_style_draw_box: assertion 'width >= -1' failed

I'm running version 1.10. under a 64 bit archlinux.

**Comment by pkulchenko** [comment]
Thank you for reporting. There have been several similar/related tickets (#425, #464) and I'd expect the issue to be resolved with the fixes linked in the tickets. If you can check and confirm using the current master branch, it would be great.
