### ISSUE TITLE
Comment/Uncomment not reversible

### ISSUE THREAD

**Issue by ajbrouwer** [pkulchenko/ZeroBraneStudio#509]
Given script:
----8><---snippy----snappy-----
foo = 1
--bar = 2
----8><---snippy----snappy-----
Highlight/select the first line (with foo) with the cursor position starting from its start and moving the cursor during selection to the start of the second line (with baz), Press CTRL-u. Notice the foo line getting commented out. Press CTRL-u again. Notice both lines getting uncommented.

**Comment by pkulchenko** [comment]
@ajbrouwer, thank you for the report; should be fixed now.
