### ISSUE TITLE
Coding Question and Concern

### ISSUE THREAD

**Issue by Cooolaid** [pkulchenko/ZeroBraneStudio#511]
Why my code gets smacked up all the way to the left. ?
I am trying to get my code to indent ,  as shown in this picture example.

http://i.imgur.com/sb9ROgN.jpg

But it does NOT do that, it also does NOT have the lines on the left with the [-] and [+]
to open and close certain blocks of scripts.

It bunches all the code to the left like this example.
http://i.imgur.com/cMkZihg.jpg

How do I make the code indent properly on its own and also be able to open & 
close blocks of code the [-] and [+] ??
Notepad++ does it with ease without any hitch.
Notepad++ indents the code automatically where its suppose to go.
But for some odd reason, zerobrane pushes all the code im handling and are all bunched up to the left.
Makes things a bit confusing to find certain scripts when all the code is smacked up to the left.

I did press TAB twice to move it, but seems to just get worse.

please help.
thank you.

**Comment by pkulchenko** [comment]
@Cooolaid, what system are you on? What do you have in your configuration file? This doesn't look like a proportional font and that's probably why the indent looks so short.

In general, if you simply want to ask a question, there is [a maillist, an email, and an IRC channel](https://studio.zerobrane.com/community), which are better ways than opening a ticket.

**Comment by Cooolaid** [comment]
Im sorry, im still learning github and how to do thing.
If i messed things up in github im sorry.

BTW, Im using Windows 7 x64 bit SP1.

This is what I have in my \cfg\user.lua
http://i.imgur.com/ru7XzR3.jpg

**Comment by pkulchenko** [comment]
Try commenting out `editor.fontname` line. I think you may not have `MonoSpace` font installed, so wxwidgets loads some substitute font, which is not a monospace font.

**Comment by Cooolaid** [comment]
ok, did that. It helped some and the font is a lot better too. :)

Now how do I get those long vertical lines with the (plus and minus) symbols buttons next to the line numbers to come back,  
so I can close and open certain blocks of code ? like this picture 
https://i.imgur.com/sb9ROgN.jpg

**Comment by pkulchenko** [comment]
Comment out `editor.fold = false` line; the default is true. You'll find all the preferences and their default values in the documentation here: https://studio.zerobrane.com/documentation#preferences.

**Comment by Cooolaid** [comment]
Yaya.! its back.  :)
I wish Zerobrane came with several Dark Theme packages. Because I believe all this started because I downloaded a Dark Theme for ZeroBrane. And the 3rd party theme messed everything up.
I wish you would make dark themes and put it as part of the Zerobrane package.

So things like this are prevented when users want a dark theme for their editor. :)



Also thank you so very much for helping me.
Its one of the main reasons why I use Zerobrane, people are so helpful here. and nice :)

**Comment by pkulchenko** [comment]
Sure; it does come with several dark themes; you are using one of them -- `TomorrowNight` -- and there are few others. You don't need to download anything else to use it, but may customize the colors if you want.

Thanks for the feedback ;).
