### ISSUE TITLE
Gideros integration not working with ZeroBrane Studio 1.10 and Gideros v2015.08

### ISSUE THREAD

**Issue by mydoghasworms** [pkulchenko/ZeroBraneStudio#512]
I am trying out ZeroBrane Studio 1.10 and Gideros v2015.08.

When trying to start a Gideros project with either "Execute the current project/file (F6)" or "Run as Scratchpad (Ctrl-F6)", it brings up the Gideros Player briefly then shuts it down again. Nothing else happens. In the Output window there is the following:

```
Found multiple .gproj files in the project directory; ignored 'C:\Program Files (x86)\Gideros\Examples\Graphics\Bird Animation\gfx\'.
Found multiple .gproj files in the project directory; ignored 'C:\Program Files (x86)\Gideros\Examples\Graphics\Bird Animation\Bird Animation.gproj'.
Program starting as '"C:\Program Files (x86)\Gideros\GiderosPlayer.exe"'.
Program 'GiderosPlayer.exe' started in 'C:\Program Files (x86)\Gideros\Examples\Graphics\Bird Animation' (pid: 1176).
Starting the player and waiting for the bridge to connect at 'C:\Program Files (x86)\Gideros\Tools\gdrbridge.exe'.
Couldn't connect after 15 attempts. Try again or check starting the player manually.
Program completed in 4.92 seconds (pid: 1176).
```

Here I took one of the examples that runs normally under Gideros Studio. I don't know why the log says that there is more than one .gproj file, because there isn't.

**Comment by pkulchenko** [comment]
Martin, there is indeed a bug in ZeroBrane Studio that has been fixed in 48e8d33c (unfortunately after v1.10 was released). You can either grab the change from that commit or apply the following patch to the Gideros interpreter:

```diff
diff --git a/interpreters/gideros.lua b/interpreters/gideros.lua
index 3313020..98290e5 100644
--- a/interpreters/gideros.lua
+++ b/interpreters/gideros.lua
@@ -64,7 +64,7 @@ return {
 
     -- find *.gproj file in the project directory
     local file
-    for _, proj in ipairs(FileSysGetRecursive(self:fworkdir(wfilename), false, "*.gproj")) do
+    for _, proj in ipairs(FileSysGetRecursive(self:fworkdir(wfilename), false, "*.gproj", {folder = false})) do
       if file then
         DisplayOutputLn("Found multiple .gproj files in the project directory; ignored '"..proj.."'.")
       end
```

I can't test right now, but the either patch should work. My apologies for the inconvenience.

**Comment by mydoghasworms** [comment]
Thanks very much!

**Comment by mydoghasworms** [comment]
Great, I just tested it and it works. Many thanks.

**Comment by pkulchenko** [comment]
Good; thank you for the update.

**Comment by chrisfoulds** [comment]
I have just installed the latest Gideros and latest ZeroBrane and I am getting the same problem:

Program starting as '"C:\Program Files (x86)\Gideros\GiderosPlayer.exe"'.
Program 'GiderosPlayer.exe' started in 'C:\Users\Chris\Documents\workspace\Gideros\PseudoRacer\PseudoRacer' (pid: 4560).
Starting the player and waiting for the bridge to connect at 'C:\Program Files (x86)\Gideros\Tools\gdrbridge.exe'.
Couldn't connect after 15 attempts. Try again or check starting the player manually.
Program completed in 4.97 seconds (pid: 4560).

The player does open and remains open.

Is there a new issue or is this back ?

**Comment by pkulchenko** [comment]
@chrisfoulds, when you say "the latest ZeroBrane", do you mean v1.30 or the current master branch from the repository?

It's probably not the same issue as it's working for others, but you may try running `gdrbridge isconnected` from another terminal (while the player is open) to see if it returns the expected result (`1`), because this is what the script is checking for. Maybe there were some recent changes to the `gdrbridge` that modified this output.

**Comment by chrisfoulds** [comment]
V1.3.0 .
I have just found if I launch Zerobane , then start a player then press Play it works.
But if Zerobane starts the player I get the error - weird. Anyway it is a workaround that works for me!

**Comment by pkulchenko** [comment]
Hm, interesting. And the IDE starts the same player on the same machine, right?

Just in case, what version of Gideros are you using?

**Comment by pkulchenko** [comment]
And what's the output of `gdrbridge isconnected` when the IDE fails to connect?
