### ISSUE TITLE
Output Window Clone -- Not auto scrolling when Normal Window Closed

### ISSUE THREAD

**Issue by bluetardis** [pkulchenko/ZeroBraneStudio#513]
When the Output / Console Window is open, the Window Clone performs as expected. 

Example (Working)
-have both Output Window/Console and Output Window Clone Visible
-execute an app (eg corona)
-make a change and refresh the simulator
-both windows will autoscroll to eof

Example (bug)
-have just Output Window Clone Visible
-execute an app (eg corona)
-make a change and refresh the simulator
-the text updates but doesn't autoscroll to eof.

Minor gripe but it would be awesome if this could be fixed.

**Comment by pkulchenko** [comment]
@bluetardis, should be fixed now; take a look. I also fixed an issue with the initial size of the clone with `Output` is closed, but it requires running the latest master. If you want to use an earlier version of the IDE, then grab the result of the previous commit.

**Comment by bluetardis** [comment]
Works perfectly - once the clone window is resized.  (it starts as a blip - just big enough to show the Window Manager Raise/Lower/Fullscreen etc.)

appreciate the rapid response

**Comment by pkulchenko** [comment]
> it starts as a blip - just big enough to show the Window Manager Raise/Lower/Fullscreen etc.

This should be fixed by the second commit, but this requires using the master branch version. Did you try it with that commit as well?

**Comment by bluetardis** [comment]
I believe so...

PB-SYD-001:ZeroBraneStudio peterbishop$ date

Mon 17 Aug 2015 10:19:10 AEST

PB-SYD-001:ZeroBraneStudio peterbishop$ git status

On branch master

Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

PB-SYD-001:ZeroBraneStudio peterbishop$

PB

Peter Bishop
------------------------------------------
peter@bluetardis.com.au
+61-(0)412-27-2793

**Comment by pkulchenko** [comment]
Yes, the master branch looks current, but how about the plugin you are using?

I just pushed one more upgrade that fixes the version number in the plugin; if you pull the changes, you should see v0.3 of the plugin, which should fix that issue as well.

**Comment by bluetardis** [comment]
I am missing something - now new changes coming through and my version of
"outputclone.lua" is 0.1 is /packages...

PB

Peter Bishop
------------------------------------------
peter@bluetardis.com.au
+61-(0)412-27-2793

**Comment by pkulchenko** [comment]
Should be v0.3: https://github.com/pkulchenko/ZeroBranePackage/blob/master/outputclone.lua#L8

**Comment by bluetardis** [comment]
Deleted and recloned Packages and its all sweet - all working!!!

PB

Peter Bishop
------------------------------------------
peter@bluetardis.com.au
+61-(0)412-27-2793

**Comment by pkulchenko** [comment]
ok; good. Thanks for the update!
