### ISSUE TITLE
show position in outline window

### ISSUE THREAD

**Issue by keszegh** [pkulchenko/ZeroBraneStudio#515]
it would be goood if zbs could highlight in the outline window the funtion which contains the line the cursor currently is on in the editor window.

**Comment by pkulchenko** [comment]
@keszegh, I think I got it all working; just need few more finishing touches. I'm considering scrolling the function in the Outline into view, but need to play with it as it may generate too many movements in the Outline...

**Comment by keszegh** [comment]
great, that was fast, thanks. the scrolling might be not so important after all if it gets confusing.

**Comment by pkulchenko** [comment]
@keszegh, just pushed the changes; give it a try. It's turned `on` by default, but can be disabled with `outline.showcurrentfunction=false`.

**Comment by keszegh** [comment]
after testing, i think perhaps the scrolling would be useful contrary to what i said. also the 'highlight' should be more easily visible, e.g. an inverted background color or something like that. besides these it works perfectly.

**Comment by pkulchenko** [comment]
I'll need to give scrolling a try, but just need to make sure it's not too "jumpy". Inverted background color may be a bit problematic; I think bold is visible enough with different color settings.

**Comment by keszegh** [comment]
i think it is even ok if it jumps there, if scrolling back and there is messy.
now if the current function is out of the outline window then we do not see it at all, that's what is not so good.
about highlighting, i use zen color scheme and i think that a background highlight (in this scheme it's in fact darker) for the line of the current function (just like the one for the current line in the main window) would improve a lot the time i need to find where it is.

**Comment by pkulchenko** [comment]
@keszegh, I pushed several changes that should improve the highlighting. Let me know how it works for your color scheme.

The scrolling is not going to work. I've tried different options, but none of them work well. You can try this diff yourself:

```diff
diff --git a/src/editor/outline.lua b/src/editor/outline.lua
index 4d8ce25..ea0b595 100644
--- a/src/editor/outline.lua
+++ b/src/editor/outline.lua
@@ -560,6 +560,10 @@ local package = ide:AddPackage('core.outline', {
             cache.line = nil
           end
           ctrl:SetItemBold(item, val)
+          if val then
+            ctrl:ScrollTo(item)
+            ctrl:SetScrollPos(wx.wxHORIZONTAL, 0, true)
+          end
         end, cache.fileitem, true)
     end,
   })
```

Since the selected functions should be much easier to see now, I'm not sure any further changes would be needed.

**Comment by keszegh** [comment]
the highlight now is very easily visible, perfect.
the scrolling is also good, much better to use now than without scrolling. sometimes i noticed that the outline window also scrolled left-right occasionally, whereas i would prefer that the contents of it stick to the left while scrolling, but the top-down scrolling was flawless. so overall i prefer it with this diff to scroll than without but it's up to you (perhaps make it a flag in cfg to allow 'experimental scrolling of outline window' would be best?).
thanks for your efforts.

**Comment by pkulchenko** [comment]
Right, that left-right scrolling is what I don't like and I don't have any way to avoid it if I use wxwidgets functions that to positioning in the tree control. Even if I explicitly say "scroll to the left 0 position", it still stays scrolled to the right. This only happens when the item is too long to fit in the current window, so the control (reasonably) attempts to make it more visible, but I don't see a way to disable it.

There is still a more complicated alternative that I want to briefly explore, but if it doesn't look good, I probably leave it as is (without scrolling).

**Comment by pkulchenko** [comment]
@keszegh, I added the jumping to the current function using a workaround that doesn't do any horizontal shifts.

**Comment by keszegh** [comment]
now it's perfect. thanks again.

**Comment by madmaxoft** [comment]
I'm afraid 26f0a6bd4cf7dc3209912ae197226fad5a99097d has introduced some problems. Whenever I move my cursor now, the function in which it lands gets bolded and gray-backgrounded in the outline; but it stays bold most of the time when moving to another function. Only sometimes the highlight disappears on some functions, but still stays on others.
![outline-too-bold](https://cloud.githubusercontent.com/assets/4388386/9624485/b3c8c84e-514d-11e5-8f44-2bed41a0ddbe.png)
(Running clean ZBS 14d55bdfe392001027a35a6326e6d1418f64eeda on Windows 7 64-bit)

**Comment by pkulchenko** [comment]
@madmaxoft, I've been testing on Windows 10 and haven't seen this effect, but should be able to test on Windows 7 later today.

I can think of two reasons for this behavior: (1) `UnslectAll` for some reason is not working in your case, and (2) there is something wrong with the logic that identifies start/end positions for the functions.

You can check the former by running `ide.outline.outlineCtrl:UnselectAll()` in the Console to see if it removes the selection from all the items in the outline (just make sure that it's already visible as the effect should be immediate). You can check the latter by testing on some different (simpler) file to see if you get the same issue.

**Comment by pkulchenko** [comment]
Another way to get more information is to click on one of the functions in the outline when you have multiple selected. Does it remove the selection from all the functions except the one you clicked on and its parents?

**Comment by madmaxoft** [comment]
It seems that `UnselectAll()` doesn't do anything - there was no visual change in the control whatsoever. I verified that indeed the console commands are working, by trying out `CollapseAll()` and that did have an immediate effect, the nodes collapsed as expected.

I'm using the non-Aero look of the system, "Windows Classic" theme. Perhaps that could be of significance. Unfortunately it is no longer available in Win8+.

Clicking on a function does toggle the control wildly, I *think* it selects *most* of the functions defined before the clicked function, but not always all of them.
I even found a scenario when clicking a function removes the gray background from all items, but some (random) items still stay bolded.

**Comment by pkulchenko** [comment]
ok, I'll check with the same theme when I get access to my win7.

> I think it selects most of the functions defined before the clicked function, but not always all of them.

This may still indicate that the parsing is not working correctly. Have you had a chance to test on a (much) simpler example with fewer functions to see if it works as expected? For example, load `src/editor/outline.lua` and navigate its functions...

**Comment by madmaxoft** [comment]
The outline.lua file behaves wrong as well.

**Comment by pkulchenko** [comment]
As a workaround, you can set `outline.showcurrentfunction=false`, which should turn all these effects off.

It's also possible that there something wrong with multiple selection in the control; then the remedy is to only keep one selection, but this will only highlight the current function and nothing else (and the bolding will still be incorrect).

**Comment by pkulchenko** [comment]
> The outline.lua file behaves wrong as well.

This means that there is something different with the control. Could you apply this diff:

```diff
diff --git a/src/editor/outline.lua b/src/editor/outline.lua
index 401da91..6bac7e8 100644
--- a/src/editor/outline.lua
+++ b/src/editor/outline.lua
@@ -561,7 +561,7 @@ local package = ide:AddPackage('core.outline', {
       -- scan all items recursively starting from the current file
       eachNode(function(ctrl, item)
           local func = cache.funcs[ctrl:GetItemData(item):GetData()]
-          local val = edpos >= func.pos and (not func.poe or edpos <= func.poe)
+          local val = edpos >= func.pos and (func.poe and edpos <= func.poe)
           if edline == editor:LineFromPosition(func.pos)+1
           or (func.poe and edline == editor:LineFromPosition(func.poe)+1) then
             cache.line = nil
```

**Comment by madmaxoft** [comment]
That diff has broken everything, the wrong bolding and selection are still present, but now the current function is *usually* neither bolded nor selected.

**Comment by pkulchenko** [comment]
@madmaxoft, I tested with both Windows Classic and Windows Standard (as well as with the default Viste scheme) and it all works as expected for me. I will probably switch to only one selection, but since the bolding doesn't work as well, there is something with the logic or the file. The "bold" attribute is set for each item on every re-paint, so when the state is changed in the outline, it means that every item was checked and set bold or not bold.

I can't think of a reason why it wouldn't work. Let's do this. Open the `outline.lua` file and click on several first functions at the top, one-by-one. Do you get any incorrect bolding? On all the machines I tested it on, it works as expected. If you get the wrong results here, we can add `prints` to see if there is something wrong with the data or with the changing of attributes in wxwidgets (or maybe with redrawing after changing the attributes).

**Comment by pkulchenko** [comment]
@madmaxoft, @keszegh, I've updated the hightlight to only select one item (the current function). Should still be enough for visibility, but may help with some of the issues that @madmaxoft sees.

**Comment by pkulchenko** [comment]
Mattes, I'm still in the dark on what may be causing the issue you see as I haven't been able to reproduce it. If you still see it on the latest code, maybe we can try couple of things in `zerobrane` on freenode IRC (as it's going to be simpler than ticket comments).

**Comment by pkulchenko** [comment]
@madmaxoft, the issue you saw should be fixed, but I also pushed the change that we discussed earlier, as it correctly handles the case when the spec file doesn't provide any information on where the functions end. Let me know if you notice any issues you saw previously with this latest code. Thanks!

**Comment by madmaxoft** [comment]
I haven't come across any problems ever since the fixes. Thanks.
