### ISSUE TITLE
Moonscript Syntax Highlighting Issue

### ISSUE THREAD

**Issue by edgardmota** [pkulchenko/ZeroBraneStudio#516]
I'm having some issues on Moonscript syntax highlighting using ZeroBrane Studio 1.10. The editor sometimes "gets lost" during edition. When this happens, every line from the problem on is colorized as a string. The problem happens and disappears  eventually, after some edition. I really can't say what causes it or makes it recover.

**Comment by pkulchenko** [comment]
@edgardmota, there is not much I can do about it as it's implemented by the editing component, Scintilla. If you can reproduce it, I can try to figure out what goes wrong and at least let the author of Scintilla know, so that it can be fixed there and included in the IDE.
