### ISSUE TITLE
Select interpreter by first line in lua script

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#517]
I have several projects, which uses different interpreters. Furthermore I have projects, where different files use different interpreters. Currently this is a pain with zbstudio, because after changing the project or the start-script in a project, I always have to manually select the correct interpreter.

Lua itself supports the unix-Feature of a socalled "shebang"-line, If the first line of a script starts with #!, Lua will ignore it. On the other side, unix shells parse this line and invoke the selected interpreter ¹). I'd like to have zbstudio to do the same thing.

**So here is my feature request:**
*"Have an option to automatically select the interpreter via the shebang-line. "*

I realized it as a new interpreter call SheBang, which acts as a wrapper to the other interpreters known by zbstudio. Here is my code.

```lua
--
-- fill in with replacements, because zbstudio interpreter names are not the standard
--
local replacements=
{
	lua="luadeb",
	lua51="luadeb",
	lua52="luadeb52",
	lua53="luadeb53",
}

--
-- this is the shebang interpreter definition
--
return {
  name = "SheBang",
  description = "SheBang",
  frun = function(self,wfilename,rundebug)
    local filepath = wfilename:GetFullPath()
	local fd=assert(io.open(filepath))
	local firstline=fd:read()
	fd:close()
	local name=assert(firstline:match("#!(%S+)")):gsub(".*/","")
	name=replacements[name] or name
	local interpreter=ide.interpreters[name] or error("no interpreter "..name)
	return interpreter:frun(wfilename, withdebugger)
 end,
  hasdebugger = true,
  fattachdebug = function(self) DebuggerAttachDefault() end,
  scratchextloop = false,
  unhideanywindow = true,
}

```
Please review it, any feedback is welcome. I'd be happy to have this added to one of the next zbstudio release

¹) Examples
```lua
#!/usr/bin/lua
require"somemodule"
::::
```
or
```lua
#!/home/myself/bin/myspecialluart
api:dosomething{parameter=123}
::::
```

**Comment by pkulchenko** [comment]
@jjvbsag, it's an interesting idea! Although selection of the interpreter is only a problem when you switch a project for the first time (as its configuration will be saved after that), it may still be useful.

I'd suggest to make it a plugin, which should only take a couple of tweaks to [register an interpreter](https://studio.zerobrane.com/doc-plugin#registering-an-interpreter) and add it to the [plugin repository](https://github.com/pkulchenko/ZeroBranePackage) for others to use by sending a pull request.

**Comment by jjvbsag** [comment]
**pkulchenko**
>Although selection of the interpreter is only a problem when you switch a project for the first time (as its configuration will be saved after that)

I don't think, you understood the issue itself. We have one project with several lua-scripts
* some-appl.lua : an application, which requires **a specific lua interpreter** (e.g. ApplRuntime.exe)
* liba.lua, libb.lua,... : some modules, which should be able to work standalong (e.g lua.exe)
* test-liba.lua, test-libb.lua, ... : unit tests for the libraries, which **must** be run with a standard lua (lua.exe)

This cannot be solved by a projectwide interpreter selection, but only with an interpreter selection by file. For this I believe the shebang is the best solution.

**Comment by pkulchenko** [comment]
@jjvbsag, did you get it working from a plugin or do you still need a help with it?

**Comment by jjvbsag** [comment]
I'm fine, thanks. My SheBang interpreter solves my problem for now (also on Windows ;-). I will take a look at the Project Settings plugin, you mentioned in #518, when I'm less busy with the current job.

I'm only unsure about
```lua
  hasdebugger = true,
  fattachdebug = function(self) DebuggerAttachDefault() end,
  scratchextloop = false,
  unhideanywindow = true,
```
Because these should be wrapped to the interpreter selected by the shebang, which I believe must be done via a metatable lookup. I have an idea how to improve this and would comeback to you when verified.

**Comment by pkulchenko** [comment]
@jjvbsag, yes, metatable lookup should work. In fact, it's already used in the IDE, just not with those fields: take a look at `ide.proto.Interpreter` in `src/editor/proto.lua`.

When you have it working, send a pull request to the plugin repo or update this ticket if you have any further questions. Closing as you are on the right track...
