### ISSUE TITLE
Save project settings in a project file

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#518]
**pkulchenko** (in #517)
>Although selection of the interpreter is only a problem when you switch a project for the first time (as its configuration will be saved after that)

That is one of the issues, we have with zbstudio (we dont have many others, we like it very much). 

Interpreter (and maybe other project settings. are there any?) is stored *somewhere* (where?), but not in the project itself. Because of this, when PersonA creates a project, selected an interpreter, then puts the project into some version management system (subversion, git,...), and then PersonB fetches the project from the vms, he has no info about the correct interpreter and - after retriving the information somehow - must select it again manually. So, from this point of view zbstudio is not very well suited for collaboration of multiple people on one project.

We would strongly prefer a solution, where **all** project relevant settings are stored in a file located *inside* the project. (e.g. *projectname*.zbstudio) so this can be committed to the vms too. This "project file" could also be associated with zbstudio, so clicking on a *.zbstudio file in a filemanager would open zbstudio with the correct project (and interpreter) selected.

**Comment by pkulchenko** [comment]
@jjvbsag, there is already [Project Settings plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/projectsettings.lua), which allows to apply the same settings you can set from `user.lua`, but on a project-by-project basis. This doesn't help directly with the interpreter as its configuration is saved separately, but you can force it to be set to a particular value.

There may be a way to set the default value using `interpreter='foo'` in the project config, but I need to check on a couple of things to see how to enable it.

**Comment by pkulchenko** [comment]
@jjvbsag, I pushed the change that allows to put `interpreter = 'foo'` in the project config file and that interpreter will be used as a default for new projects. Those projects that have already been configured, will keep their values and those that got the new default value can still be changed.
