### ISSUE TITLE
Code analysis and "unknown globals" which are defined elsewhere

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#520]
I have an issue with the code analysis and I wonder, how to solve it.

Given a lua module **utils.lua**
```lua
#!/usr/bin/lua
require"strict"
local sprintf=string.format
local function printf(...)
	io.write(sprintf(...))
	io.flush()
end
_G.printf=printf
```
and a main script **main.lua**
```lua
#!/usr/bin/lua
require"strict"
require"utils"

printf("VERSION=%q\n",_VERSION)
```

when I run Project/Analyse on "main.lua", I get
```text
.../main.lua:5: first use of unknown global function 'printf'
```

Question: *Is there a way to get the code analysis to detect, that printf is defined in utils and thus is known?*

**Comment by pkulchenko** [comment]
Try with `staticanalyzer.infervalue = true` in the config as described in [static analyzer](https://studio.zerobrane.com/doc-general-preferences#static-analyzer) section. This takes globals from other files into consideration and also does "field" analysis, but it likely to be noticeably slower as it does more processing.

**Comment by jjvbsag** [comment]
Thanks, this works fine for the example given above, but not with this one
**COLORS.lua**
```lua
RED=0xFF0000
GREEN=0x00FF00
BLUE=0x0000FF
```
**ex2.lua**
```lua
require"COLORS"
print("RED=",RED)
```
gives :`ex2.lua:2: first use of unknown global variable 'RED'`

Changing **COLORS.lua** to
```lua
_G.RED=0xFF0000
_G.GREEN=0x00FF00
_G.BLUE=0x0000FF
```
does not change it.

**Comment by pkulchenko** [comment]
Hm, I used the same script you posted previously and added `RED`, `GREEN` to it and prepending `_G` worked for me. I'll check on whether it's possible to make it work without prepending `_G` table reference.

**Comment by jjvbsag** [comment]
New observation:
running zbstudio 1.10 on Windows 7: analyzing returns "no warnings"
running zbstudio 1.10 on Kubuntu14.04LTS : analyzing returns "first use of unknown global variable"
This is independent of using _G or not.

**Comment by CapsAdmin** [comment]
I'm using kubuntu and I can confirm it's not working here either.

**Comment by pkulchenko** [comment]
@jjvbsag, @CapsAdmin, are you saying that the same code is analyzed differently on Windows and Kubuntu? Running the same version of the IDE? This would be really strange, but I'll check.

Are you trying (on Kubuntu) with the same script you posted in this ticket earlier?

**Comment by CapsAdmin** [comment]
I tried it on windows now and it's the same. 

I get ``first use of unknown field 'IsGBufferReady' in 'render'`` but if i do ``ctrl b`` and type `render.IsGBufferReady`` it's found.

I added ``staticanalyzer.infervalue = true`` to my config and ``print(ide.config.staticanalyzer.infervalue)`` in local console prints true.

**Comment by jjvbsag** [comment]
Ok, it's a bit of confusing. But now I think, I have found the basic issue. Code-Analysis seems to have some kind of *memory*. That makes it hard to reproduce and can leed to wrong conclusions.

Because of this you have to *carefully* repeat the following steps to reproduce:

Given the following files in one folder.
**COLORS.lua**
```lua
RED=0xFF0000
GREEN=0x00FF00
BLUE=0x0000FF
```
**ex2.lua**
```lua
require"COLORS"
print("RED=",RED)
```
* Open one file in zbstudio
* Project / Project Directory / Set from Current File
* Leave zbstudio (!)
* Start zbstudio again

zbstudio should now wake up inside the directory where the two files reside

* open COLORS.lua
* F7 (compile) ¹)  > `100% success rate`
* Shift+F7 (analyze) > `no warnings.`
* open ex2.lua
* F7 (compile)  > `100% success rate`
* Shift+F7 (analyze) > `first use of unknown global variable 'RED'`

OK, that's what we know.

* now change **COLORS.lua** to
```lua
_G.RED=0xFF0000
_G.GREEN=0x00FF00
_G.BLUE=0x0000FF
```
* save COLORS.lua
* F7 (compile)  > `100% success rate`
* Shift+F7 (analyze) > `no warnings.`
* open ex2.lua
* F7 (compile)  > `100% success rate`
* Shift+F7 (analyze) > `no warnings.`

SO, now everything seems ok. BUT

* now change **COLORS.lua** back to
```lua
RED=0xFF0000
GREEN=0x00FF00
BLUE=0x0000FF
```

* save COLORS.lua
* F7 (compile)  > `100% success rate`
* Shift+F7 (analyze) > `no warnings.`
* open ex2.lua
* F7 (compile)  > `100% success rate`
* Shift+F7 (analyze) > `no warnings.`  (??!??)

NOW, this is the confusing point. Code, which was analysed with `unknown global variable` before, is now analysed with `no warnings`

I have verified this with zbstudio 1.10 on win and linux, behaviour is the same on both platforms. The observation mentioned before seems to be irritated by the memory-behaviour of zbstudio

I hope, this will help you to find the cause of this issue

Regards Jørgen


¹) F7 (compile) may not be necessary, but it is helpful to distinguish the analyze messages.

**Comment by pkulchenko** [comment]
@jjvbsag, good catch! There is `clear_cache` method in luainspect that I should probably be using. I'll see if that fixes the issue.

This should at least eliminate the inconsistencies between the changes and subsequent runs.

**Comment by pkulchenko** [comment]
@jjvbsag, @CapsAdmin, both of the issues should be fixed: (1) purging of the cached modules, and (2) taking globals without `_G` into account.

Let me know if you notice any issues.

**Comment by jjvbsag** [comment]
@pkulchenko Looks good for me now ¹) 

Thanks, regards Jørgen

¹) manually copied your changes into my installation. Is there something like a "daily build installer" ?

**Comment by pkulchenko** [comment]
> manually copied your changes into my installation. Is there something like a "daily build installer" ?

No, there is not yet ;). Since you can run the IDE from a cloned repository, some users use that as the "upgrade" method. In most other cases copying .lua files is enough to upgrade (although not all the .lua files are in the `src` folder as there are also `api`, `spec`, `lualibs`, and other folders).
