### ISSUE TITLE
Lua 5.3 core not recognizing Lua 5.3 functions...

### ISSUE THREAD

**Issue by MaxKielland** [pkulchenko/ZeroBraneStudio#521]
The math functions defined in Lua 5.3 returns "attempt to call field '...' (a nil value)", even if Lua 5.3 is selected in the ZeroBrane Project menu when using the local console window.

Example:
x = 23
print(math.type(x))
print(math.tointeger(x))

**Comment by pkulchenko** [comment]
@MaxKielland, what platform? I'm getting `integer 23` as expected when `Run` the file (on Windows).

**Comment by MaxKielland** [comment]
I'm running on 64bit Windows 7 Professional SP 1.
Note that I didn't _run_ a script, I typed it in the Local Console window at the bottom.

**Comment by pkulchenko** [comment]
Right; it won't work from the Console as those commands are (currently) executed with the same interpreter tat runs the IDE itself. There are two related tickets that may address this (#493 and #490), so I'm closing this one.

**Comment by pkulchenko** [comment]
@MaxKielland, just to clarify one thing as it may not be clear from a cursory reading of this ticket. This issue only applies to the Local console, as **when you debug your script using Lua 5.3**, all the commands in the (Remote) console are executed in the context of your application so all Lua 5.3 commands will work. So the current workaround is to start debugging, run your Lua 5.3 commands, and then abort the debugging. This is not ideal and the other tickets I mentioned are expected to address this.
