### ISSUE TITLE
Save modified files on analyze code

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#524]
Related to #520 : There should be an option to automatically save all modified files, when invoking the code analyzer.
Without this the analyzer will refer to the saved, but old file content.

**Comment by pkulchenko** [comment]
There is `editor.saveallonrun` option, which I can probably extend to save all when using running static analyzer. Since the "default" analyzer only checks the current file, I'll probably do the save when both `infervalue` and `saveallonrun` are checked.
