### ISSUE TITLE
Request for a "daily build installer"

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#527]
Taken from #520 to have a separate issue to track
@jjvbsag :
>manually copied your changes into my installation. Is there something like a "daily build installer" ?

@pkulchenko :
> No, there is not yet ;). Since you can run the IDE from a cloned repository, some users use that as the "upgrade" method. In most other cases copying .lua files is enough to upgrade (although not all the .lua files are in the src folder as there are also api, spec, lualibs, and other folders).

It would be nice to have a "bleeding edge installer" for download

**Comment by madmaxoft** [comment]
I don't think this needs any action. Simply git-cloning this repo makes a full install; updating then consists of a simple `git pull`.

Things are a bit more involved if you fork your own copy (in order to publish PRs), but it's still manageable:
```
git checkout master
git fetch --all
git rebase upstream/master
```

**Comment by jjvbsag** [comment]
@madmaxoft : I don't agree.

**Using GIT (or subversion or similar) requires some knowledge.**

This is not practical for people, who shall just be "Lua-Programmers" to use zbstudio in a given context. (Especially if they are located behind a tight firewall)

**Disk usage**

Using GIT or Subversion requires a big footprint on the disk
* svn co trunk => ~116MB
* git clone => ~147MB

In contrast the installation
* zbstudio installed on windows ~16MB
* zbstudio installed on linux ~35MB

**Comment by bluetardis** [comment]
But once you have performed the original clone, the actual git pull is
negligible - only the size of any changes.   If you are behind a firewall
how do you update?

PB

Peter Bishop
------------------------------------------
peter@bluetardis.com.au
+61-(0)412-27-2793

**Comment by madmaxoft** [comment]
Everyone who calls themselves programmer should know some git basics. Writing code without a source control is foolish at the very least.

As for disk usage, in the days of terabyte disks and gigabytes eaten by program installations, I don't think some 150 MiB is gonna hurt anyone.

**Comment by pkulchenko** [comment]
I tend to agree with Mattes and Peter; if you a beginner, you can always start with a packaged version (which are available for all supported platforms) and if you need a bleeding edge version, then you probably should be using git (or at least can get a zipped download of the current version).

Having said that, it would be nice to have a way to upgrade, as this would also allow package upgrades, but I don't know of an easy and cross-platform way to do that.

**Comment by jjvbsag** [comment]
>Having said that, it would be nice to have a way to upgrade, as this would also allow package upgrades, but I don't know of an easy and cross-platform way to do that. 

Hmm. I believe, I could manage some kind of lua-script doing a
* download the zip
* loop over all files in the zip
 * if file in zip is newer than existing in installation then copy

The much better solution would be to retrieve a log of changes and download only the touched file since the last version. I know, git would do this. The trick is to create a filter to only transfer the platform relevant files.

I must sleep over it before continuing ;-)

**Comment by pkulchenko** [comment]
That's roughly how it should go, but there are many small details that get in the way. For example, it's not possible to update dynamic libraries on Windows when they are in use, so it requires an external launcher to swap those. Any access over https requires openssl library (if used with luasec), which (potentially) runs into crypto export restrictions.

One would also need some sort of notification mechanism to check for updates (which would require phoning home) and then a process to check the current version and upgrade. And the process has to work on three different platforms and have a mechanism to rollback in case something goes wrong. I have the steps that I think are needed to enable it, but being able to "clone" things is so much easier that I haven't found enough need to embark on implementing this ;).
