### ISSUE TITLE
trying to compare nil with a number

### ISSUE THREAD

**Issue by ppioter** [pkulchenko/ZeroBraneStudio#529]
I have encountered this issue when working with ZBS on one specific file, it was causing ZBS to crash, offending code:

editor.lua @ line 473:   if this and token.fpos > pos and this == token.at+1 then break end

I don't know which variable was nil, I just fixed it by applying extra nil checks

editor.lua @ line 473:   if this and token.fpos and pos and token.fpos > pos and this == token.at+1 then break end

**Comment by pkulchenko** [comment]
@ppioter, thank you for the report. I guess it can only be `token.fpos`, but if that's the case, there are several other places in the same function that may need to be patched.

Do you by any chance have the fragment this error was happening on?

**Comment by ppioter** [comment]
@pkulchenko, I didn't preserve the file unfortunately(pretty lame of me, I know...), when I come across any bugs in the future I will try to make a proper report:)

**Comment by pkulchenko** [comment]
@ppioter, no problem. One more question, what was the last action that led to the issue? Were you doing `Ctrl-DblClick` on a variable? 

Also, don't forget to take a screenshot with the error, as it shows a stack trace and not just the place for the error.

**Comment by ppioter** [comment]
...it was like couple of weeks ago, so I'm not 100% sure, I think was trying to select a piece of code in order to copy it and then program was crashing.
I will remember to take screenshot next time

**Comment by pkulchenko** [comment]
> ...it was like couple of weeks ago, so I'm not 100% sure, I think was trying to select a piece of code in order to copy it and then program was crashing.

and the error was pointing to line 473 that you fixed?

**Comment by ppioter** [comment]
exactly, I got the error message pointing to this line

**Comment by pkulchenko** [comment]
This is a strange one, so the screenshot will definitely help. `pos` can't be `nil` as it's passed as `pos+1` in all three cases where this function is used. `fpos` shouldn't be `nil` either as it's the starting position of the tokens in the file and I have been unable to come up with a test to trigger this condition. I only found one case where the token position is `nil`, but this happens at the end of file and is not added to the list of tokens.

**Comment by pkulchenko** [comment]
@ppioter, I added position information to the end-of-file marker, which *may* fix this, but since I have not been able to reproduce, I'm not certain about it. If you see the issue again, please re-open the ticket and provide the stack trace. Thank you.

**Comment by ppioter** [comment]
@pkulchenko, that sounds good!, I will remove code edit from ZBS on my computer and perhaps the error will show up again one day. 
Thanks for the great software!

**Comment by pkulchenko** [comment]
Sounds good. I also suggest applying the patch I pushed (or just using the latest master branch) as it would give us additional information if you see things not working. Thanks!
