### ISSUE TITLE
Can't read contents of symlinked file in windows

### ISSUE THREAD

**Issue by halfnelson** [pkulchenko/ZeroBraneStudio#530]
In windows if I create a symlink to a file and try to open the file in ZBS it gives me no errors but a blank file. I can write into the editor and save and it will overwrite the contents of the symlinked file correctly. I tracked this down to the wx.wxFileSize(fname) in FileRead returning 0 for symlinked files on windows. To work around this for now I have added 
```lua
if not length then
    length = file:SeekEnd()
    file:Seek(0)
  end
```

to skip the wx.wxFileSize check based on the outcome of a previous ticket in may where you changed it from file:length()

**Comment by pkulchenko** [comment]
@halfnelson, how are you creating the link? I've tried to create a hardlink and everything works as expected:

```
mklink /H hardlink.lua link.lua
```

I can open and edit `hardlink.lua` file.

**Comment by halfnelson** [comment]
Not using hardlink just a symlink. So ditch the /H

**Comment by pkulchenko** [comment]
Tried that as well on the master branch (`mklink softlink.lua link.lua`) and no issues so far. All three files (`link.lua`, `softlink.lua`, and `hardlink.lua`) can be opened and edited in the IDE just fine. Tested on Windows 8.1. Anything I'm missing?

**Comment by bluetardis** [comment]
Double check permissions unless you are local admin. Especially if you want zerobrane in a location other than your home folders.

**Comment by halfnelson** [comment]
I can edit the files and save new content. But it doesn't show existing
content. Win 10, master branch

**Comment by pkulchenko** [comment]
Yes, it shows the content correctly for me. I'll see if I can find win10 machine nearby. Do you have Win7 or Win8 you can test this on? I want to make sure it's not version dependent.

**Comment by halfnelson** [comment]
I am at work and I have win 8.1 here, I will test it now

**Comment by halfnelson** [comment]
8.1 here same behaviour.
steps
 
 * Create test file "test" with contents "hello zbs"
 * Open admin cmd prompt and navigate to directory with test file
 * `mklink testlink test`
 * `symbolic link created for testlink <<===>> test`
 * open folder with test files in it in zbs
 * open test file and confirm contents "hello zbs"
 * open testlink and confirm empty file shown

**Comment by pkulchenko** [comment]
hm, interesting. I think I walked through those steps, but let me try these exact ones...

**Comment by halfnelson** [comment]
![image](https://cloud.githubusercontent.com/assets/551284/10060970/62b23592-6298-11e5-8b70-c3c82c4eeca1.png)

**Comment by halfnelson** [comment]
![image](https://cloud.githubusercontent.com/assets/551284/10060980/7e440ac4-6298-11e5-815e-dd5b5b205f3c.png)

**Comment by pkulchenko** [comment]
It's a bit more puzzling now; I can see that `FileSize` returns 0 for those links, but the files are loaded as expected. I still have things to look at, so will update after I figure out what's going on here.

Are you sure you are on the latest master? I updated `FileRead` function some time ago (when improving support for large files) such that it actually doesn't check for the file size when opening them (it just reads them while there is something to read) and that's probably why I don't see this issue. There is still something to fix, as I found another potential issue while looking at the code, but the files are still loaded and edited without issues. Are you using a cloned version of the repository? What does `git describe` show?

**Comment by halfnelson** [comment]
was on 1.10 exe but will clone

**Comment by halfnelson** [comment]
Works with master!, my apologies, I had the problem with 1.10.exe and patched it locally, then decided to use latest master since there are other changes to the source I wanted to make and want this to be under VC. I must have preemptively applied the patch to util.lua without re-testing.

**Comment by pkulchenko** [comment]
ok; cool! Thanks for the update. There is still one small change I want to make related to this ticket.
