### ISSUE TITLE
SH Spec

### ISSUE THREAD

**Issue by rfajfar** [pkulchenko/ZeroBraneStudio#534]
I tried to write a shell script spec.

I've put the sh.lua file inside the `~.zbstudio/spec` folder.

I've also added `load.specs(function(file) return file:find('spec[/\\]sh%.lua$') end)` to the `user.lua` configuration file.

It does not work so I guess the lexer I selected via `lexer = wxstc.wxSTC_LEX_SH` is wrong. Tried `_BASH` and `_SHELL` too :smile: but nothing seems to exist :sob: 

Whats the right lexer name for sh/bash and can I find a full list of available lexers somewhere?

**Comment by pkulchenko** [comment]
@rfajfar, the following works for me:

```lua
-- author: Paul Kulchenko
---------------------------------------------------------

return {
  exts = {"sh"},
  lexer = wxstc.wxSTC_LEX_BASH,
  apitype = "sh",
  linecomment = "#",
  stylingbits = 5,

  lexerstyleconvert = {
    text = {wxstc.wxSTC_C_IDENTIFIER,},

    lexerdef = {wxstc.wxSTC_C_DEFAULT,},
    comment = {wxstc.wxSTC_C_COMMENT,
      wxstc.wxSTC_C_COMMENTLINE,
      wxstc.wxSTC_C_COMMENTDOC,},
    stringtxt = {wxstc.wxSTC_C_STRING,
      wxstc.wxSTC_C_CHARACTER,
      wxstc.wxSTC_C_VERBATIM,},
    stringeol = {wxstc.wxSTC_C_STRINGEOL,},
    preprocessor= {wxstc.wxSTC_C_PREPROCESSOR,},
    operator = {wxstc.wxSTC_C_OPERATOR,},
    number = {wxstc.wxSTC_C_NUMBER,},

    keywords0 = {wxstc.wxSTC_C_WORD,},
    keywords1 = {wxstc.wxSTC_C_WORD2,},
  },

  keywords = { [[ ]] },
}
```

Save it as `spec/bash.lua` and you don't need any other changes; don't forget to restart the IDE and you can now open shell files and they should be properly styled. Although it won't work in `.zbstudio` folder as specs need to be in the main `spec` folder. I'll show a bit later today how to make it a plugin.

In terms of the lexers, I don't see a comprehensive list anywhere, but you can get [Scintilla source code](http://www.scintilla.org/SciTEDownload.html) and look at `scintilla/lexers` folder. You'll see `LexBash.cxx` there and at the very bottom of the file, you'll see `SCLEX_BASH` constant. This maps to `wxstc.sxSTC_LEX_BASH`, so you were right with your guess.

**Comment by rfajfar** [comment]
Thank you :+1:

**Comment by pkulchenko** [comment]
I should probably have a generic plugin that enables all the specs that Scintilla supports. This way you don't need to add individual files.
