### ISSUE TITLE
API auto-complete

### ISSUE THREAD

**Issue by rfajfar** [pkulchenko/ZeroBraneStudio#535]
I wrote a lib I use for Firebase communication. Now I also wrote a API for ZBS. It works but I have a problem.

Lets say the api looks for **firebase** which has the type **lib**. As long as I do not require it like `local firebase = require('firebase')` autocomplete works, when I do it however it stops working. Did I misunderstand something? Is this only meant for libraries that do not need to be required and always work under the same name like **love** for example?

**Comment by pkulchenko** [comment]
@rfajfar, I'll need to check; can you make the API file available somewhere?

There was a recent commit (69d2788b) that added rudimentary support for handling `require` in auto-complete and it's possible that it has broken something. Can you try with the current master and the version before that commit? You can do `git checkout b4656ca0` (this is the commit before the `require` changes).

**Comment by rfajfar** [comment]
The API is nothing special https://gist.github.com/rfajfar/45293688a7376fce1c9a

Then I've added it to the /opt/zbstudio/interpreters/luabase.lua file to the return api table so that it looks like this `api = {"baselib", "firebase"}`

**Comment by rfajfar** [comment]
Tested with the latest version from the repository. Works perfectly. You can close the issue :smile:

**Comment by pkulchenko** [comment]
ok; cool. Thanks for the update.

**Comment by rfajfar** [comment]
@pkulchenko By the way, the way I'm adding my API to the default **luabase** interpreter, is that alright or is there another better way?

**Comment by pkulchenko** [comment]
yes, there is a better way ;): you can use `api` config setting: https://studio.zerobrane.com/doc-general-preferences#custom-apis

So, in your case you can use `api = {luadeb = 'firebase'}` and it will be loaded for `luadeb` interpereter.

**Comment by rfajfar** [comment]
@pkulchenko Awesome! Thanks :+1:
