### ISSUE TITLE
Append auto-complete API

### ISSUE THREAD

**Issue by rokf** [pkulchenko/ZeroBraneStudio#537]
Can I somehow append to the `love2d` auto-complete API without changing the `love2d.lua` file? I'd like to append functions from the `LÖVE for Android` binding, like `love.touch.getTouch()` for example.

`user.lua`:
I tried adding it like `api = {"love-android"}` but then the regular love2d API disappears. If I do it like `api = {love2d = "love-android"}` then the regular one works, `love-android` does not.

The `love-android.lua` file is available here: https://github.com/rfajfar/zerobrane-studio-apis/blob/master/love-android.lua

**Comment by pkulchenko** [comment]
@rfajfar, that's an interesting issue. I need to think on how this can be done. Maybe the `api` setting has to merge the results, but then what if you want to *replace* the API instead of merging?

Still, I think the need to merge is probably more popular than to replace...

**Comment by pkulchenko** [comment]
@rfajfar, I may need to add `onApiLoad` call to provide a hook to extend/update the loaded API, which will allow you to add your own elements to it. The existing `api` command will still be available to replace an api or add a new one.

**Comment by rm-code** [comment]
@rokf @pkulchenko FYI the android port is part of the official LÖVE releases since 0.10.0 (Dec 2015) and its documentation has been integrated in [LÖVE-API](https://github.com/love2d-community/love-api) shortly after.

**Comment by pkulchenko** [comment]
@rm-code, are you saying that this ticket is less of a priority now? It's good, as I'm still unclear on the best way to implement this.

Given that the love2d API has been updated 6 months ago, I think it's a time to do another refresh.

**Comment by pkulchenko** [comment]
@rm-code, @rokf, I've updated Love API to 0.10.1.

It's not a complete fix for this issue (as there is still no easy way to "merge" one API with another one with the same name), so this will stay on the back burner until I (or someone else) will get a chance to review it again.

**Comment by rm-code** [comment]
Is this a problem with ZeroBrane or is it something we can fix in the https://github.com/love2d-community/love-api?

**Comment by rokf** [comment]
@rm-code The idea was that it would be possible to extend an API in ZBS, so its not bound to LŐVE directly.
