### ISSUE TITLE
Could not read console input

### ISSUE THREAD

**Issue by zohooo** [pkulchenko/ZeroBraneStudio#538]
When using ZeroBrane Studio 1.10 on Windows 7, I found that after running the following code
````lua
local text = io.read()
io.write("output: " .. text)
````
I could not input in the builtin console of ZeroBrane Studio.

**Comment by pkulchenko** [comment]
@zohooo, Do you mean you couldn't input anything using the Output window? You need to "print" or output something to the console first to "unlock" it: https://studio.zerobrane.com/doc-faq#how-to-accept-keyboard-input-for-applications-started-from-the-ide

**Comment by zohooo** [comment]
I cound not understand why I need to "unlock" it first? Is it possible for ZBS console to accept input without any output? When using Notepad++ with NppExec plugin, it is possible to do it.

**Comment by pkulchenko** [comment]
@zohooo, this is mostly to prevent unwanted editing of the content in the Output window, so the window is switched to "editable" only after some output to it. It's not a hard requirement, but I've seen more than one time users messing the content of the window by inadvertent edits.

I'll check if I can relax that requirement a bit.

**Comment by pkulchenko** [comment]
@zohooo, I removed that requirement; check the current version as it should work for you.

**Comment by zohooo** [comment]
It works well. Thanks.
