### ISSUE TITLE
File / Print

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#540]
Have I missed something or is there really no print command in zbstudio? If there is, I didn't find it. I had to copy'n'paste to Scite for printing :-1: 

I would suggest to have
* **File / Print...** : to print the the file in the current active tab.
* If there is a selection active, only the selected range should be printed.
* There should also be a method to print the "Output" or "Local console" tab.

**Comment by pkulchenko** [comment]
@jjvbsag, it's not too difficult to add printing, the main issue is with the preview, as it requires its own dialog, a set of icons, and the canvas drawing logic. If you are only thinking about printing (without a preview), then it's easier, but there are still couple of configuration options and it's not clear how to change them:

(1) magnification; some users prefer smaller fonts; this can be partially addressed by zooming in the editor.
(2) color vs black/white mode
(3) line wrapping
(4) removing bold/italic from styled text in the editor
(5) line numbers (add or not)
(6) margins
(7) header/footer with page numbers

I'm sure there are other things to thing about or configure (these are just what I have in my notes). At the very minimum, it seems like two options may be needed: `print.magnification` and `print.header`/`print.footer` (possibly setting the format, like `"filename\tdate\tpagenumber"` or something along those lines).

**Comment by madmaxoft** [comment]
I think those options really warrant a "print setup" dialog. You don't want to set them in the config, start ZBS, print a page, find out something's wrong, edit the config, re-launch ZBS and try again.

**Comment by jjvbsag** [comment]
> (possibly setting the format, like "filename\tdate\tpagenumber" or something along those lines).

Just refering to the print.header/print.footer topic. I'd suggest to use some kind of template method.
I always use something similar to the following example:

```lua
local function apply(template,data)
	return template:gsub("{{(%w+)}}",data)
end

local print=
{
	header="{{title}}\t{{page}}/{{pages}}",
	footer="{{filename}}\t{{date}}",
}

local data=
{
	title="This is the title",
	filename="example.lua",
	date=os.date("%Y%m%d-%H%M%S"),
	pages=3,
}

for page=1,data.pages do
	data.page=page
	io.write("--begin-of-page--\n")
	io.write(apply(print.header,data),"\n")
	io.write("some content","\n")
	io.write("some content","\n")
	io.write("some content","\n")
	io.write("some content","\n")
	io.write(apply(print.footer,data),"\n")
	io.write("--end-of-page--\n")
end
```

Output:

```
--begin-of-page--
This is the title	1/3
some content
some content
some content
some content
example.lua	20151013-142813
--end-of-page--
--begin-of-page--
This is the title	2/3
some content
some content
some content
some content
example.lua	20151013-142813
--end-of-page--
--begin-of-page--
This is the title	3/3
some content
some content
some content
some content
example.lua	20151013-142813
--end-of-page--
```

**Comment by pkulchenko** [comment]
> I think those options really warrant a "print setup" dialog. You don't want to set them in the config, start ZBS, print a page, find out something's wrong, edit the config, re-launch ZBS and try again.

@madmaxoft, I think it's fine for some options (like magnification and color/wrapping mode), but it's better to set others (like margins) from a dialog. Even that it somewhat problematic as some systems (OSX) don't allow setting of margins from their page setup dialog.

> Just refering to the print.header/print.footer topic. I'd suggest to use some kind of template method.
I always use something similar to the following example:

@jjvbsag, yes, that's very close to what I have in mind and to the mechanism that the IDE already provides: https://studio.zerobrane.com/doc-general-preferences#formats. I plan to add the current date/time and page/pages. You can add any other text, so something like this `%S\t%D\t%p/%P` in the header will give you filename, current timestamp, and `page/pages`. You can split this between footer/header any way you want and add your own text.

I've got most of the printing working, but can't yet figure out how to make it take the paper size into account. It works find with the default I set (Letter or A4), but doesn't seem to take any changes into account. It does look nice when printed (much better than I expected).

**Comment by pkulchenko** [comment]
@jjvbsag, @madmaxoft, I pushed the changes to `printing` branch: https://github.com/pkulchenko/ZeroBraneStudio/tree/printing. I think everything required has been implemented and I'd be interested in feedback.

The selection and the printing of Output/Console windows should work as well. You can also disable/update header and footer (the footer is off by default). I removed indicators as they were cluttering the page and added bolding for the keywords.

**Comment by jjvbsag** [comment]
Checked out printing branch on Kubuntu14.04, start with bash zbstudio.sh
Open a lua-script, Select File/Print => wxLua Runtime Error : 
```
Lua: Error while running chunk
src/editor/print.lua:124: attempt to get length of upvalue 'pages' (a nil value)
stack traceback:
	src/editor/print.lua:124: in function <src/editor/print.lua:118>
	[C]: in function 'Print'
	src/editor/print.lua:172: in function <src/editor/print.lua:145>
	[C]: at 0x7fb0522f6502
	src/main.lua:730: in main chunk
	[C]: at 0x004054e8
```
after Continue a Printing dialog showed up. Printing then created one page of paper, but not very pretty (I will try to find a scanner in the office and then attach a scan)

**Comment by jjvbsag** [comment]
Same test on Windows7x64 : Printing is fine and works as expected :+1:

**Comment by pkulchenko** [comment]
Ugly ;)

Yes, I tested on Win. Seems like `printOut:OnPreparePrinting` is not called on Ubuntu for some reason.

Can you apply this diff and check on Ubuntu again? Thanks!

```diff
diff --git a/src/editor/print.lua b/src/editor/print.lua
index 121e005..95378b2 100644
--- a/src/editor/print.lua
+++ b/src/editor/print.lua
@@ -116,6 +116,7 @@ local function connectPrintEvents(printer, printOut)
   end
   function printOut:HasPage(pageNum) return pages[pageNum] ~= nil end
   function printOut:GetPageInfo()
+    if not pages then printOut:OnPrintPage() end
     local printDD = printer:GetPrintDialogData()
     -- due to wxwidgets bug (http://trac.wxwidgets.org/ticket/17200), if `to` page is not set explicitly,
     -- only one page is being printed when `selection` option is selected in the print dialog.
```

**Comment by jjvbsag** [comment]
Error message changes to
```
Lua: Error while running chunk
src/editor/print.lua:16: attempt to index local 'dc' (a nil value)
stack traceback:
	src/editor/print.lua:16: in function 'printScaling'
	src/editor/print.lua:53: in function 'OnPrintPage'
	src/editor/print.lua:119: in function <src/editor/print.lua:118>
	[C]: in function 'Print'
	src/editor/print.lua:173: in function <src/editor/print.lua:146>
	[C]: at 0x7fd887fd9502
	src/main.lua:730: in main chunk
	[C]: at 0x004054e8
```
then zb is killed with memory error

**Comment by pkulchenko** [comment]
Ok, how about this one instead?

```diff
diff --git a/src/editor/print.lua b/src/editor/print.lua
index 121e005..e5d5fd9 100644
--- a/src/editor/print.lua
+++ b/src/editor/print.lua
@@ -116,6 +116,7 @@ local function connectPrintEvents(printer, printOut)
   end
   function printOut:HasPage(pageNum) return pages[pageNum] ~= nil end
   function printOut:GetPageInfo()
+    if not pages then return 1, 9999, 1, 9999 end
     local printDD = printer:GetPrintDialogData()
     -- due to wxwidgets bug (http://trac.wxwidgets.org/ticket/17200), if `to` page is not set explicitly,
     -- only one page is being printed when `selection` option is selected in the print dialog.
```

I think there is a problem with printing logic in GTK, as it calls `GetPageInfo` before it provides any chance to calculate the number of pages (and then still calls `GetPageInfo` at the right place again):

```c
bool wxGtkPrinter::Print(wxWindow *parent, wxPrintout *printout, bool prompt )
{
    if (!printout)
    {
        sm_lastError = wxPRINTER_ERROR;
        return false;
    }

    // Let's correct the PageInfo just in case the app gives wrong values.
    int fromPage, toPage;
    int minPage, maxPage;
    printout->GetPageInfo(&minPage, &maxPage, &fromPage, &toPage);
    m_printDialogData.SetAllPages(true);
```

**Comment by jjvbsag** [comment]
Nope :-(

```
*** Error in `bin/linux/x64/lua': double free or corruption (out): 0x00007f01680011d0 ***
zbstudio.sh: line 15:  2215 Aborted                 (core dumped) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"
```

Maybe you should get you a VmWare machine with Linux for trying yourself.

**Comment by pkulchenko** [comment]
Most definitely; I have bunch of Linux VMs; they are on the machine that is not available at the moment. Thanks for all the help! I'll try myself tomorrow...

**Comment by pkulchenko** [comment]
@jjvbsag, I tested the last fix on Ubuntu 14.04 and don't get any crashes. The results are similar to the image you sent, but it does work (in terms of the printing/preview).

**Comment by pkulchenko** [comment]
I've posted the details of this issue on Linux to [wx-dev maillist](http://article.gmane.org/gmane.comp.lib.wxwidgets.devel/164882) and [scintilla-user maillist](https://groups.google.com/forum/#!topic/scintilla-interest/ZpDD0Qllzx8).

**Comment by pkulchenko** [comment]
I've merged these changes to master, but disabled printing on Linux until I figure out what's going on there.
