### ISSUE TITLE
Bring Gideros Player to front

### ISSUE THREAD

**Issue by AntixSoftware** [pkulchenko/ZeroBraneStudio#548]
When Gideros player is launched on pressing F5, the player currently gets placed behind the ZeroBrane window. This should be reversed so it appears in front of the ZeroBrane window.

After about 3 months of having to click the players icon on my windows taskbar every time I press F5, I'm getting ready to throw a wobbly :)

**Comment by pkulchenko** [comment]
Is it on Windows? I don't think I have any control over that as all the interactions are through `gdrbridge` executable. I *might* be able to find it by the window name and bring it to the front, but it's not foolproof.

Do you know what is the window class for the gideros player? I'll see if I can come up with something if it's on Windows...

**Comment by AntixSoftware** [comment]
Yep I'm running Windows 8.1 x64. I don't know anything about the windows class for Gideros Player sorry.

Just looking at what happens now it seems that Gideros Player gets launched, then ZB brings its own window back to front. Maybe the easier solution is to have an option to not bring ZB to front when launching an external program like Gideros Player?

**Comment by pkulchenko** [comment]
> Just looking at what happens now it seems that Gideros Player gets launched, then ZB brings its own window back to front. Maybe the easier solution is to have an option to not bring ZB to front when launching an external program like Gideros Player?

This should only happen when the application is stopped in the debugger (for example, on a breakpoint). If the application is simply running, it should not get the IDE back to front. I'll get the latest Gideros to check myself.

**Comment by pkulchenko** [comment]
@AntixSoftware, does this happen only during debugging or does the same thing happen when you run the application (`F6`)? When it happens during debugging, does your application get suspended or does it continue to run? If the application is stopped in the debugger, then it's the expected result, but if the application is running, then it should bring the IDE up front.

If the application is indeed suspended in the debugger, you may need to check that you don't have `debugger.runonstart=false` in the config or that you are not using an old version of the IDE as it should run the project being debugged by default (it should not be stopped when you launch the debugger).

**Comment by AntixSoftware** [comment]
I checked and if I have "require("mobdebug").start()" at the top of my code, the player starts, then ZB pops back to front.

If I don;t have the debug requre, the player starts and remains the topmost window.

**Comment by pkulchenko** [comment]
@AntixSoftware, you need to add `debugger.requestattention=false`; see [debugger options](https://studio.zerobrane.com/doc-general-preferences#debugger) and #449 for the related discussion.

It will still request attention when the application is stopped on a breakpoint...

**Comment by AntixSoftware** [comment]
Awesome, that worked a treat! :)

**Comment by madmaxoft** [comment]
Glad I'm not the only one who found the "feature" disturbing :)

**Comment by pkulchenko** [comment]
@madmaxoft, maybe we need a compromise here: when the debugging is just starting (as in the case we are discussing), I can just blink it in the taskbar without bringing it to focus. You can still use the configuration setting to remove the blinking, but at least by default the focus is not going to be switched and there is still a hint for those who may be confused why their application is "blocked".

**Comment by pkulchenko** [comment]
@AntixSoftware, @madmaxoft, I think I found a way to make it work for all the cases without any additional configuration settings. I pushed a change that should enable this and `debugger.requestattention` is no longer needed (it was removed; I'll update the docs shortly).

Please let me know that it works for you when you get a chance to test it. Basically, it should not request attention unless the application is suspended in the debugger (when the debugging starts).
