### ISSUE TITLE
Context Menu for Outline Pane

### ISSUE THREAD

**Issue by AntixSoftware** [pkulchenko/ZeroBraneStudio#549]
When working with very large files, the outline pane can become very cluttered (to collapse everything in the outline pane in my current project takes 84 mouseclicks!!). Would it be possible for the Outline pane to have a context menu with 2 options...

1. Expand all
2. Collapse All

Maybe other useful options could go in there too.

**Comment by pkulchenko** [comment]
I assume both of these options are for the item you click on. Any particular reason for this functionality? I don't mind adding it, but would like to better understand what's behind the request. The items are going to be expanded again when you switch between tabs. Why is this clutter? You can hide anonymous functions and configure the list only to show the current file: https://studio.zerobrane.com/doc-general-preferences#outline

**Comment by AntixSoftware** [comment]
Hiding anonymous functions doesn't seem to help in my case. Either that, or I'm doing something wrong.

With nearly 40,000 lines of code in my largest source file in my current project, the outline window is very large. I have localized many functions within functions and the outline window is way more useable when they are all collapsed. 

I don't mind having to re-collapse everything every time I switch between source files, as long as its only a couple of clicks, not 84 :)

My suggestion would just make navigating large code files easier. I dunno, maybe its a dumb idea.

**Comment by pkulchenko** [comment]
So, you'd still prefer to see one level of functions, just not the entire hierarchy?

**Comment by pkulchenko** [comment]
@AntixSoftware, try this version and add `outline.showcompact=true` to the config. I think may like the effect.

No additional menu items as they wouldn't help in your case: the tree would be re-expanded on every tab switch, so you'd still be constantly collapsing it. With this setting it should behave as you'd expect it to.

**Comment by AntixSoftware** [comment]
Wow. Thanks! That's so cool :)
