### ISSUE TITLE
Can't donate money to ZeroBrane

### ISSUE THREAD

**Issue by hanoixan** [pkulchenko/ZeroBraneStudio#551]
Two problems actually. I attempted to email this to webmaster@zerobrane.com, but that got booted back at me: 

    Sorry, we were unable to deliver your message to the following address.

    <webmaster@zerobrane.com>:
    Remote host said:
    550 5.1.1 <webmaster@zerobrane.com>: Recipient address rejected: User unknown in virtual     alias table
    [RCPT_TO]

And before that I had attempted to donate some money to ZeroBrane, and your Stripe popup failed on me:

    Software error:

    malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Server closed connec...") at /home/soaplite/lib//BusinessStripe.pm line 558
    For help, please send mail to the webmaster (webmaster@zerobrane.com), giving this error message and the time and date of the error.

**Comment by pkulchenko** [comment]
@hanoixan, thank you for the report; let me check on both of these...

**Comment by pkulchenko** [comment]
@hanoixan, I've fixed the redirect and the Stripe error looked like something transient as I was able to complete the transaction without issues. You may try again; thanks!

**Comment by hanoixan** [comment]
Yes, the Stripe transaction went through now. Weird! It could have been caused by me putting the full year in for my expiration date, because I caught myself doing that the second time around, but I don't think you have any control over that :)
Thanks for your hard work on a great piece of software. -- 


     On Saturday, November 7, 2015 2:38 PM, Paul Kulchenko <notifications@github.com> wrote:
   
 

 @hanoixan, I've fixed the redirect and the Stripe error looked like something transient as I was able to complete the transaction without issues. You may try again; thanks!—

**Comment by pkulchenko** [comment]
Thank you for the update and for the support!
