### ISSUE TITLE
Interpreter=busted misbehaves

### ISSUE THREAD

**Issue by ildar** [pkulchenko/ZeroBraneStudio#552]
Simple
https://github.com/Olivine-Labs/busted/blob/master/spec/test_runner/interface_spec.lua
in ZBS:
> Program starting as '"/usr/bin/busted" --output=TAP "/tmp/.private/ildar/.yG6Pnt"'.
> Program 'busted' started in '/tmp/busted-2.0.rc11-0/spec/test_runner' (pid: 7855).
> 1..0
> Program completed in 0.55 seconds (pid: 7855).

I don't understand this output.
But running in the console shows correctly:
> $ busted --output=TAP interface_spec.lua
> ok 1 - does a describe does 1000 its
> ok 2 - does a describe does 1000 its
> ...
> ok 1000 - does a describe does 1000 its
> 1..1000

**Comment by pkulchenko** [comment]
@ildar, does this only happen when you are debugging the script? When you are using `Run`, it should show the actual file name instead of using a temporary file and I'd be interested to see if that works.

**Comment by ildar** [comment]
Indeed Running works fine.

**Comment by pkulchenko** [comment]
I think this is caused by one level of indirection that the IDE needs to setup for debugging to work, but this fails because `describe` is not defined in the global namespace.

Basically, create `dofile_spec.lua` in the same folder as `interface_spec.lua` and add `dofile [[.\interface_spec.lua]]` to it. I'm getting `Failure message: .\interface_spec.lua:1: attempt to call global 'describe' (a nil value)` when trying to run busted on it. This is the same error you'd get from the "original" script, but it's not see as it's "printed" and is "eaten" by busted.

One workaround is to use Run if you don't need to debug and add `require('mobdebug').start()` manually to your script if you need debugging. I guess something has changed in the environment handling inside busted as this used to be working. I don't have a better solution yet.

**Comment by pkulchenko** [comment]
@ildar, what Lua version are you using to run busted?

**Comment by ildar** [comment]
5.1 classic lua interpreter (system, installed to /usr/bin/lua)

**Comment by pkulchenko** [comment]
@ildar, can you try the following diff:

```diff
diff --git a/interpreters/busted.lua b/interpreters/busted.lua
index 0fb271e..45f1213 100644
--- a/interpreters/busted.lua
+++ b/interpreters/busted.lua
@@ -29,35 +29,28 @@ return {
       end
     end
 
-    local file
+    local file = wfilename:GetFullPath()
+    local helper
     if rundebug then
       -- start running the application right away
-      DebuggerAttachDefault({runstart = ide.config.debugger.runonstart == true})
-      local code = (
-[=[xpcall(function() io.stdout:setvbuf('no')
-    require('mobdebug').start(); dofile [[%s]]
-  end, function(err) print(debug.traceback(err)) end)]=])
-        :format(wfilename:GetFullPath())
+      DebuggerAttachDefault({runstart = ide.config.debugger.runonstart ~= false})
       local tmpfile = wx.wxFileName()
       tmpfile:AssignTempFileName(".")
-      file = tmpfile:GetFullPath()
-      local f = io.open(file, "w")
+      helper = tmpfile:GetFullPath()..".lua" -- busted likes .lua files more than .tmp files
+      local f = io.open(helper, "w")
       if not f then
-        DisplayOutputLn("Can't open temporary file '"..file.."' for writing.")
+        DisplayOutputLn("Can't open temporary file '"..helper.."' for writing.")
         return 
       end
-      f:write(code)
+      f:write("require('mobdebug').start()")
       f:close()
     end
 
-    file = file or wfilename:GetFullPath()
-
-    local options = ide.config.busted and ide.config.busted.options
-      or "--output=TAP"
-    local cmd = ('"%s" %s "%s"'):format(busted, options, file)
-    -- CommandLineRun(cmd,wdir,tooutput,nohide,stringcallback,uid,endcallback)
+    local options = ide.config.busted and ide.config.busted.options or "--output=TAP"
+    local cmd = ('"%s" %s %s "%s"'):format(busted, options, helper and "--helper="..helper or "", file)
+     -- CommandLineRun(cmd,wdir,tooutput,nohide,stringcallback,uid,endcallback)
     return CommandLineRun(cmd,self:fworkdir(wfilename),true,false,nil,nil,
-      function() if rundebug then wx.wxRemoveFile(file) end end)
+      function() if helper then wx.wxRemoveFile(helper) end end)
   end,
   hasdebugger = true,
   fattachdebug = function(self) DebuggerAttachDefault() end,
```

It should fix debugging for the scripts (but you need to set a breakpoint if you want to stop in the script or use `Break`).

**Comment by ildar** [comment]
yep, works as you say. Thanks!

**Comment by pkulchenko** [comment]
@ildar, pushed the changes; thanks for the report!
