### ISSUE TITLE
Can't input any characters when creating a new line, OS is ubuntu 64 bit, chinese version.

### ISSUE THREAD

**Issue by liyheart** [pkulchenko/ZeroBraneStudio#553]
Hi, I can't input any characters when creating a new line, OS is ubuntu 64 bit, chinese version.
When I press Shift twice, it gets normal. However, if i canceled any input, it can't receive any input once more.

**Comment by pkulchenko** [comment]
@liyheart, I've tried on Ubuntu 64bit, but don't see this effect. Do you have a non-chinese version to try on? Also, what version of the IDE are you running?

**Comment by pkulchenko** [comment]
I'd need more information to go by to look at this. Can you reproduce on a non-chinese version? What do you mean by "cancel the input"? Do you have any popups on the screen?

I'm closing this for now, but feel free to re-open if you have more information on this...
