### ISSUE TITLE
Edit/Source/Comment generates invalid code

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#554]
Given the following snippet:

```lua
local LIST_OF_FILES=
{
[[c:\users\myself\file-a.txt]],
[[c:\users\myself\file-b.txt]],
[[c:\users\myself\file-c.txt]],
[[c:\users\myself\file-d.txt]],
[[c:\users\myself\file-e.txt]],
[[c:\users\myself\file-f.txt]],
}
```
which is perfect legal lua-code

Now comment some lines of this using [Ctrl]+[U]
Result is:
```lua
local LIST_OF_FILES=
{
[[c:\users\myself\file-a.txt]],
[[c:\users\myself\file-b.txt]],
[[c:\users\myself\file-c.txt]],
--[[c:\users\myself\file-d.txt]],
--[[c:\users\myself\file-e.txt]],
--[[c:\users\myself\file-f.txt]],
}
```
which gives errors `unexpected symbol near ','`  ¹)

I'd suggest to use `"--~ "` as comment string (as Scite does), which avoids this problem:
```lua
local LIST_OF_FILES=
{
[[c:\users\myself\file-a.txt]],
[[c:\users\myself\file-b.txt]],
[[c:\users\myself\file-c.txt]],
--~ [[c:\users\myself\file-d.txt]],
--~ [[c:\users\myself\file-e.txt]],
--~ [[c:\users\myself\file-f.txt]],
}
```
gives `Compilation successful;`

BTW: This would also allow to toggle Scite comments in or away

¹) You can even see it in the Markdown formatting. The trailing ',' is black and not gray.

**Comment by pkulchenko** [comment]
@jjvbsag, good catch! I'm not sure about `--~`, but adding/removing `-- ` (with a space in the end) should work in this case? I'd prefer not to have too many special cases, but maybe the space only needs to be added when commenting out text without indentation (and then only removed when it's one space following the comment... Need to think about it.

**Comment by pkulchenko** [comment]
I looked at several options, but they all are too lua-specific and I'd like that logic to stay generic and to only rely on `spec.linecomment` value if possible. Maybe the `linecomment` value needs to change from `--` to `-- ` (with a space added); the only downside I see is that something like `--!` or `--text` will not get uncommented, but this may be a feature. Also, `--[[` will not get uncommented either, which is a good thing.

**Comment by jjvbsag** [comment]
What I like about the SciTE comment: I can easily tell, which comment were intentionally added by me while writing code and which comments were done using the comment function in SciTE. And I can comment code including comments. Example:
```lua
--
-- my simple printf function
--
```

Comment in SciTE gives:
```lua
--~ --
--~ -- my simple printf function
--~ --
```
This can be easily identified and uncommented again in a stable manner.

Comment the first snippet in zbs gives
```lua

 my simple printf function

```
This is really an uncomment and not stable at all, because recommenting then gives.
```lua

-- my simple printf function

```
In my understanding pressing [Ctrl]+[U] twice shall *always* return to the state before.

**Comment by pkulchenko** [comment]
I can see the reasoning, but then you can't uncomment "normal" comments unless they include `--~`. What to do about that?

I have to check the commenting logic as when you have three lines selected, all three should be commented out (then you'd get three lines commented in the end as you'd expect).

**Comment by jjvbsag** [comment]
Another observation (but this is depending on my personal preferences)
My settings are (in zbs. In SciTE I have similar settings)
```
editor.tabwidth = 4
editor.usetabs  = true
```
With the SciTE Comment, which has a length of 4 characters, Tab-intendation is visual stable during comment/uncomment. I like this. Commenting in zbs (with a 2 characters comment) gives visual clutter...

**Comment by jjvbsag** [comment]
"normal" comments include TEXT and not CODE. At least in my sources :innocent: So there is no sense in uncommenting them. I use the comment function *only* to temporary disable code already written. And for this the SciTE comment is perfect for me. Also, because it is recognizable as "temporary comment". 

You mentioned `spec.linecomment` . Is it possible to override this in user.lua? This would be good enough for me.
Regards

**Comment by pkulchenko** [comment]
Sure: `(...).ide.specs.lua.linecomment = "--~ "` in the config. Maybe that's the fix?

**Comment by pkulchenko** [comment]
Maybe I should expose `ide` in the config to avoid the workaround with passing `_G` as `...`...

**Comment by jjvbsag** [comment]
> Sure: (...).ide.specs.lua.linecomment = "--~ " in the config. Maybe that's the fix?

Thanks, that's perfect for me.
Regards

**Comment by pkulchenko** [comment]
Ok; closing this one then. Those who need to use a different comment indicator can use `(...).ide.specs.lua.linecomment = "--~ "` in the config.
