### ISSUE TITLE
Feature request: add project specific packages

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#555]
Referring to #107 
`projectsettings.lua` allows to read configuration details from `<projectdir>/.zbstudio/user.lua`.
Would it be possible to extend this to load packages from `<projectdir>/.zbstudio/packages/*.lua` ?

**Comment by pkulchenko** [comment]
I think it's possible. Curious, what kind of packages do you load on a project-basis? Or is this to keep the packages in the repo and check them out along with the other code?

**Comment by jjvbsag** [comment]
We have for example packages to download our code into embedded devices. The method for downloading (ftp, tftp, proprietary protocol, http put) varies with the embedded device and is useless for *all* other projects except the one for the device.
It would be nice to have the download package in the project, where it is checked in together with other code.
Second benefit: A developer, which checks out the code, will get the package activated without the need to copy some files into ~/.zbstudio/packages or similar.

**Comment by pkulchenko** [comment]
ok; thanks for the details.

**Comment by jjvbsag** [comment]
One more use for this: Add project/device specific api entries, while project is opened

**Comment by pkulchenko** [comment]
If I understand correctly, you mean that the changes in the project config file would be applied without restarting, no? If so, it's different issue and will be resolved when the processing of config files without restarting will be added (in general).

**Comment by jjvbsag** [comment]
Sorry, if I was unclear.

What I'd wish, is
* I start zbs
* I select a project, then
 * packages from `<projectdir>/.zbstudio/packages/*.lua` will be loaded ¹). This will allow me to
   * Add project/device specific menu entries and dialogs to zbs (to allow Download, edit parameters like ipaddress of device, Remote control, etc)
 * definitions of `<projectdir>/.zbstudio/api/*/*.lua` are autoloaded or can be loaded from the packages. This will allow me to
   * Have tooltips and autocomplete for the project lua-code, which is intended to run in the device and use device specific functions (which are published by the api file)
* Of course, when I select another project, this stuff must be unloaded in a proper way via onUnRegister 


¹) I would appreciate also to load `<projectdir>/.zbstudio/packages/*/*.lua`, this would allow to collect a package + associated files (e.g. icon files) into one folder per package

**Comment by pkulchenko** [comment]
> definitions of <projectdir>/.zbstudio/api/*/*.lua are autoloaded or can be loaded from the packages. This will allow me to Have tooltips and autocomplete for the project lua-code, which is intended to run in the device and use device specific functions (which are published by the api file)

That's correct, but not needed, since you can load API definitions from a plugin (which is a recommended way anyway): https://studio.zerobrane.com/doc-plugin#registering-an-api

> I would appreciate also to load <projectdir>/.zbstudio/packages/*/*.lua, this would allow to collect a package + associated files (e.g. icon files) into one folder per package

I thought about it, but I think one level of packages is fine. You can still have `packages/mypackage.lua` and `packages/mypackage/otherfiles...` and load the files from that location.

**Comment by jjvbsag** [comment]
> ... since you can load API definitions from a plugin 

Understood and accepted

> You can still have packages/mypackage.lua and packages/mypackage/otherfiles... and load the files from that location.

But this makes it *very* difficult to retrieve shared packages from a subversion repository via `svn:external` properties (which we use quite heavy). It's easy and common to include subdirs via `svn:external`, but to require *two* externals (one for `packages/mypackage.lua` and a second for `packages/mypackage/otherfiles`) is uncommon and error prone.

**Comment by pkulchenko** [comment]
> But this makes it very difficult to retrieve shared packages from a subversion repository via svn:external properties (which we use quite heavy). It's easy and common to include subdirs via svn:external, but to require two externals (one for packages/mypackage.lua and a second for packages/mypackage/otherfiles) is uncommon and error prone. 

That's a good point; I need to think about possible options. Maybe something like this: (1) store the entire `packages` folder in the repo (may not fit your `svn:external` structure), (2) allow to set `packages` folder from the config, so you can set it to `{'packages/mypackage1', 'packages/mypackage2'}`, and (3) add an option to enable packages loaded recursively. You probably don't like (1) and I don't quite like (3), which leaves us with (2), but it looks like a hack.

Maybe another option, somewhat similar to (2), is to allow `package` command to take a string as a parameter (instead of the table), which will indicate location for the package. This will allow you to store packages in arbitrary locations, which is something that was already asked about. This way you can add to the config the following (and still have other files in the same folder):

```lua
package "mypackage1/mypackage1.lua"
package "mypackage2/mypackage2.lua"
```

I think I'd prefer this option so far...

**Comment by jjvbsag** [comment]
> store the entire packages folder in the repo (may not fit your `svn:external` structure)

No, does not fit at all. We use `svn:external` as a kind of softlink to several libraries stored in the repository, which we combine via `svn:external` to fulfill the project needs.

Example: (not real yet, but should make the intention quite clear):
**Project a**
```
download-via-http ^/zbs/packages/download-via-http/trunk
api-for-processor-a ^/zbs/packages/api-for-processor-a/trunk
api-for-display-x ^/zbs/packages/api-for-display-x/tags/release2
```
**Project b**
```
download-via-ftp ^/zbs/packages/download-via-ftp/trunk
api-for-processor-b ^/zbs/packages/api-for-processor-b/tags/release1
api-for-display-x ^/zbs/packages/api-for-display-x/trunk
api-for-display-y ^/zbs/packages/api-for-display-y/trunk
```
---

> This way you can add to the config the following ...

With `config` do you refer to `<projectdir>/.zbstudio/user.lua` ? 
Or `<projectdir>/.zbstudio/packages/config.lua` ?
Or (best) either of both? Anyway, this would be an acceptable solution for me, as I then can refer to the above named externals. May I assume, relative path will be prepended with `<projectdir>/` ? or `<projectdir>/.zbstudio/packages/` ?

**Comment by pkulchenko** [comment]
> No, does not fit at all. We use svn:external as a kind of softlink to several libraries stored in the repository, which we combine via svn:external to fulfill the project needs.

Right; that's what I thought.

> With config do you refer to <projectdir>/.zbstudio/user.lua ?
> Or <projectdir>/.zbstudio/packages/config.lua ?
> Or (best) either of both?

`<projectdir>/.zbstudio/user.lua`, but you can specify a different name using `projectsettings.filename` setting (which accepts a table with files to load as configs).

> Anyway, this would be an acceptable solution for me, as I then can refer to the above named externals. May I assume, relative path will be prepended with <projectdir>/ ? or <projectdir>/.zbstudio/packages/ ?

Relative paths will be relative to the location of the config file the command is issued from. You can still use relative paths as in `package "../packages/download-via-ftp/trunk/whatever.lua"` if you want to.

**Comment by jjvbsag** [comment]
Ok, looking forward for your implementation  :thumbsup:

Regards, Jørgen (first snow in our city yesterday)

**Comment by jjvbsag** [comment]
> `<projectdir>/.zbstudio/user.lua`, but you can specify a different name using `projectsettings.filename` setting (which accepts a table with files to load as configs).

 :question: :question: :question: So I configure in `<projectdir>/.zbstudio/user.lua` not to use `<projectdir>/.zbstudio/user.lua` but to use `<projectdir>/.zbstudio/config.lua`  :question: :question: :question: This looks for me like a paradoxon. Or do you refer to `~/.zbstudio/user.lua` ? This is no good. 

Our goal is a simplest possible startup:
* Install zbs
* Checkout a project
* Open project in zbs
* Start working.

No tweaking in `~/.zbstudio/user.lua`, no need to edit or to copy *anything*

So I have to stay with `<projectdir>/.zbstudio/user.lua` but thats OK for me.

**Comment by pkulchenko** [comment]
> Or do you refer to ~/.zbstudio/user.lua ? This is no good. 

Yes, I refer to `~/.zbstudio/user.lua`. Why is it no good? You'd need to have `projectsettings` package in the IDE packages anyway, so why not add its settings to the system/user config file?

> So I have to stay with <projectdir>/.zbstudio/user.lua but thats OK for me.

Right; this will work as well.

**Comment by pkulchenko** [comment]
@jjvbsag, this should work now with the pushed changes. You should be able to specify `package "file.lua"` or `package "path/file.lua"` or even `package "path/"` to get package(s) loaded from those files/folders. This will work from both global and package configs and should respect absolute and relative (to the location of the config file) paths, which should enable you to do what you originally wanted.

**Comment by jjvbsag** [comment]
@pkulchenko First tests looks fine, I now have to implement the details to verify in deep.

Just to understand, please correct me if wrong.

I've added `package "packages/MyTest/"` to `<projectdir>/.zbstudio/user.lua`. Because auf this `<projectdir>/.zbstudio/packages/MyTest/*.lua` will get loaded. 

In each `*.lua` a package should be returned, from which then
* `self:onRegister()` and 
* `self:onProjectLoad()` will be called (in that order). 

On Changing/Closing the project 
* `self:onProjectClose()` and 
* `self:onUnRegister()` will be called. 

The method `self:onProjectPreLoad()` will **not** be called at any time. (This is coherent for me and not a problem) I'd just like to get confirmed, this is intentionally.

**Comment by pkulchenko** [comment]
> I've added package "packages/MyTest/" to <projectdir>/.zbstudio/user.lua. Because auf this <projectdir>/.zbstudio/packages/MyTest/*.lua will get loaded. 

Correct; that's what I'd expect.

> The method self:onProjectPreLoad() will not be called at any time. (This is coherent for me and not a problem) I'd just like to get confirmed, this is intentionally.

Yes, this is the limitation due to how `projectsettings` plugin works (it loads the config in `onProjectPreLoad`) and how the events are handled (the list of handlers is taken before the events are processed, so when a new plugin is loaded, the same event from that plugin is not executed). This can probably be fixed with some work, but since this plugin is the only one using `onProjectPreLoad`, I don't plan to change that.
