### ISSUE TITLE
Fail on require IUP

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#558]
Reports `..\ZeroBraneStudio\bin\lua.exe: attempt to call a nil value` on `require 'iuplua'` (*path* is correct).
**[IUP](http://webserver2.tecgraf.puc-rio.br/iup/)** comes from **[LuaForWindows](https://github.com/rjpcomputing/luaforwindows)** (LfW).
Code could be execute correctly using **SciTE4Lua** (which is integrated in LfW too).

I found it happens when use default **Lua interpreter** *Lua*, and it not happened when use the *LuaForWindows* one.
I don't know the difference of interpreter and IUP library between zeroBrane studio and LfW. Means, if there is some specific on interpreter and/or libraries of LfW. (I find #276 mentioned about project folder)

Currently use LfW interpreter is fine for me. Report this, hoping nothing is wrong excpet my ignorant.

Thanks for your great work!! Thank you!!

**Comment by pkulchenko** [comment]
@robertlzj, IUP DLL has a dependency on other DLLs that should be in the `clibs` folder of L4W and if those DLLs are not found, then you may see the error you get (although I'm getting `module 'iuplua' not found` on the line that does `require "iuplua"`). Can you make sure you have `LUA_DEV` environment variable pointing to the location of L4W? If you do, it should add `LUA_DEV/clibs` location to `PATH` such that those additional DLLs are properly loaded.

If you already have that, then it's probably something else. How does your script look like? Why does the error message not show the line number on which it fails?

**Comment by robertlzj** [comment]
Oh, No~ I can't reproduct the problem. Since maybe I update the iup library and update the environment of `LUA_PATH`.
Gonig on this, just for a record.

The **path** should be correct already. The `require` could find the `iuplua` module, if not it will prompt `not found` (and gives some paths which it queried) as yours. I had tested to change the file name to get the prompt above.

There was some **stack** information (sorry, I can't reproduct them now, I should record them before).With about 3 levels, from the bottom *main [C]* to `require` (which gives the line number) then the top one *C function* (a loader?).
The **sciprt** is exactly any(?) examples from iup.

I'm afraid to leavle the topic in suspense. Hope it could be useed next time. Thank you anyway! : )

**Comment by pkulchenko** [comment]
I agree; if it wasn't loading the dependency DLLs, it would have shown `module 'iuplua' not found`. I can't say what may be going on and if you get the same issue again, please reopen the ticket.
