### ISSUE TITLE
Remote debugging of mashape kong doesn't work

### ISSUE THREAD

**Issue by drdwo** [pkulchenko/ZeroBraneStudio#560]
I did'nt succeed to use a windows machine for (remote) debugging mashape kong, see http://www.infoq.com/news/2015/04/kong 

Deployed mashape kong in a vagrant linux ubuntu image https://github.com/Mashape/kong-vagrant 
started from virtual box using windows 7/64 as host. Remote debugging using Zerobrane on the host (Windows 7) works in principle - so it seems there is no fundamental configuration issue. 

Zerobrane shows:

Debugger server started at 5820:8172.
Mapped remote request for '/usr/local/lib/luarocks/rocks/kong/0.5.2-1/' to 'F:\dev\5.1\'.
Debugging session started in 'F:\dev\5.1\'.

I set breakpoints in bin/kong (the entry point) and in kong/cli/start.lua and set editor.autoactivate = true

After starting kong at the ubuntu vagrant image I can successfully remote debug the entry point, the bin/kong (lua) file until its last line:

-- Load and execute desired command
require(commands[cmd])

In stack window I see commands[cmd] is kong.cli.start (as expected).

If I continue kong starts ignoring the breakpoint in kong.cli.start.

If I step in I get a message

"Couldn't activate file '/usr/local/share/lua/5.1/luarocks/loader.lua' for debugging; continuing without it."

which is strange since a mapping from /usr/local/share/lua/5.1/luarocks/loader.lua to F:\dev\5.1\luarocks\loader.lua
should be possible, since the file is there.  

Non-remote debugging (on a Unix machine) of the same scenario works, but kong cannot be installed on windows so here we depend on remote debugging.

**Comment by pkulchenko** [comment]
> Mapped remote request for '/usr/local/lib/luarocks/rocks/kong/0.5.2-1/' to 'F:\dev\5.1\'.
> I set breakpoints in bin/kong (the entry point) and in kong/cli/start.lua and set editor.autoactivate = true

Are these two files (`bin/kong` and `kong/cli/start.lua`) under `kong/0.5.2-1/` directory?

> which is strange since a mapping from /usr/local/share/lua/5.1/luarocks/loader.lua to F:\dev\5.1\luarocks\loader.lua should be possible, since the file is there. 

That's not how it works. Only files under the initial directory (`/usr/local/lib/luarocks/rocks/kong/0.5.2-1/` in your case) are going to be mapped.

Have you looked at [this FAQ answer](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered)? I'd be especially interested in the result returned by `debug.getinfo(1,"S").source` from the script where you don't see breakpoints working.

I'd also need to know full paths to the kong.cli.start (where breakpoints are not working) on both Linux and Windows systems.

**Comment by drdwo** [comment]
Thanks for the fast reply.

In fact with your hint I got it working.
Problem was that mashape kong has its entry point (the kong lua script) at a completely different location than the other lua files. I was clever enough to copy this file at the host machine,
but not in  the vagrant image. So it works now.

May be you could extend the blog about openresty debugging by a short section about mashape kong (which uses openresty). Just explain the source mapping mechanism for remote debugging
and give a hint that the lua entry file  (/usr/local/lib/luarocks/rocks/kong/0.5.2-1/bin/kong) needs to be copied both at the image and at the source so that it is under the same
source root at both places. Another useful hint would be how to mount the sources from the host to the correct position in the image (which works and is cool). This way you can do kong debugging on a windows machine.

Cheers Dietmar

Von: Paul Kulchenko
Antworten an: pkulchenko/ZeroBraneStudio
Datum: Samstag, 28. November 2015 um 22:53
An: pkulchenko/ZeroBraneStudio
Cc: Dietmar Wolz
Betreff: Re: [ZeroBraneStudio] Remote debugging of mashape kong doesn't work (#560)


Mapped remote request for '/usr/local/lib/luarocks/rocks/kong/0.5.2-1/' to 'F:\dev\5.1\'.
I set breakpoints in bin/kong (the entry point) and in kong/cli/start.lua and set editor.autoactivate = true

Are these two files (bin/kong and kong/cli/start.lua) under kong/0.5.2-1/ directory?

which is strange since a mapping from /usr/local/share/lua/5.1/luarocks/loader.lua to F:\dev\5.1\luarocks\loader.lua should be possible, since the file is there.

That's not how it works. Only files under the initial directory (/usr/local/lib/luarocks/rocks/kong/0.5.2-1/ in your case) are going to be mapped.

Have you looked at this FAQ answer<https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered>? I'd be especially interested in the result returned by debug.getinfo(1,"S").source from the script where you don't see breakpoints working.

I'd also need to know full paths to the kong.cli.start (where breakpoints are not working) on both Linux and Windows systems.

**Comment by pkulchenko** [comment]
> May be you could extend the blog about openresty debugging by a short section about mashape kong (which uses openresty). 

I agree; I'll add a note to the post. Closing this one...

**Comment by pkulchenko** [comment]
Dietmar, would you be interested to extend what you wrote above into a bit more detailed explanation and I'll make it into a blog post with your name on it?

**Comment by drdwo** [comment]
Hi Paul,
ok, I can write a more detailed explanation what I did. Need a few days, I am quite busy with other stuff now.
Then you can review it, because I am not sure I always choose the optimal path.

One thing is, that I first was able to debug into the starting of kong, but the real interesting part is
debugging plugin activity during a managed web service call from outside.

Only after moving the require('mob debug‘) into the executed method it worked:

package.path = package.path .. ";/opt/zbstudio/lualibs/?/?.lua;/opt/zbstudio/lualibs/?.lua"
package.cpath = package.cpath .. ";/opt/zbstudio/lualibs/bin/linux/x64/?.so;/opt/zbstudio/bin/linux/x64/clibs/?.so"

--require('mobdebug').start("192.168.1.181")

local _M = {}

function _M.execute(conf)
  require('mobdebug').start("192.168.1.181")
  if conf.say_hello then
    ngx.log(ngx.ERR, "============ Hello World! ============")
    ngx.header["Hello-World"] = "Hello World!!!"
  else
    ngx.log(ngx.ERR, "============ Bye World! ============")
    ngx.header["Hello-World"] = "Bye World!!!"
  end
end

return _M

May be because the execution here is not triggered by the initial loading of the plugin, but there it is triggered by the web service call.
But may be there is another solution.

So what I plan to do is a small tutorial how to create and debug a hello world plugin using windows host and a vagrant linux virtual box image
hosting kong.

Cheers Dietmar



Von: Paul Kulchenko
Antworten an: pkulchenko/ZeroBraneStudio
Datum: Montag, 30. November 2015 um 23:20
An: pkulchenko/ZeroBraneStudio
Cc: Dietmar Wolz
Betreff: Re: [ZeroBraneStudio] Remote debugging of mashape kong doesn't work (#560)


Dietmar, would you be interested to extend what you wrote above into a bit more detailed explanation and I'll make it into a blog post with your name on it?

**Comment by pkulchenko** [comment]
> May be because the execution here is not triggered by the initial loading of the plugin, but there it is triggered by the web service call. But may be there is another solution.

I think it may happen if `execute` method is executed in a separate coroutine. Coroutines are not debugged by default, but this can be enabled if you add `require('mobdebug').on()` call to it (starting debugging from that coroutine will have a similar effect). I have coroutine debugging briefly covered in the documentation: https://studio.zerobrane.com/doc-lua-debugging#coroutine-debugging.

**Comment by drdwo** [comment]
Thx for the hint, will try. But anyway, debugging works so I can start to write the blog text.

Von: Paul Kulchenko
Antworten an: pkulchenko/ZeroBraneStudio
Datum: Dienstag, 1. Dezember 2015 um 16:59
An: pkulchenko/ZeroBraneStudio
Cc: Dietmar Wolz
Betreff: Re: [ZeroBraneStudio] Remote debugging of mashape kong doesn't work (#560)


May be because the execution here is not triggered by the initial loading of the plugin, but there it is triggered by the web service call. But may be there is another solution.

I think it may happen if execute method is executed in a separate coroutine. Coroutines are not debugged by default, but this can be enabled if you add require('mobdebug').on() call to it (starting debugging from that coroutine will have a similar effect). I have coroutine debugging briefly covered in the documentation: https://studio.zerobrane.com/doc-lua-debugging#coroutine-debugging.

**Comment by drdwo** [comment]
Hi Paul,
short update on my blog plans:
My company (Talend) decided they want to host the blog entry here at Talend, but we will not publish without considering your feedback.
Expect a first version for review beginning of next week. We will slightly extend the scope, it will handle creation + debugging of a sample
kong plugin using Zerobrane + SoapUI + Vagrant both on windows 7/64 (will work probably also on newer versions) and MacOS „El Capitan“.

Cheers Dietmar

Von: Paul Kulchenko
Antworten an: pkulchenko/ZeroBraneStudio
Datum: Dienstag, 1. Dezember 2015 um 16:59
An: pkulchenko/ZeroBraneStudio
Cc: Dietmar Wolz
Betreff: Re: [ZeroBraneStudio] Remote debugging of mashape kong doesn't work (#560)


May be because the execution here is not triggered by the initial loading of the plugin, but there it is triggered by the web service call. But may be there is another solution.

I think it may happen if execute method is executed in a separate coroutine. Coroutines are not debugged by default, but this can be enabled if you add require('mobdebug').on() call to it (starting debugging from that coroutine will have a similar effect). I have coroutine debugging briefly covered in the documentation: https://studio.zerobrane.com/doc-lua-debugging#coroutine-debugging.

**Comment by pkulchenko** [comment]
> My company (Talend) decided they want to host the blog entry here at Talend, but we will not publish without considering your feedback. Expect a first version for review beginning of next week. We will slightly extend the scope, it will handle creation + debugging of a sample kong plugin using Zerobrane + SoapUI + Vagrant both on windows 7/64 (will work probably also on newer versions) and MacOS „El Capitan“.

Sounds good; just update the ticket when you have the draft and I'll review it. Thanks.

**Comment by drdwo** [comment]
Hi Paul,
attached is a draft of the blog entry.
I have written it in our company Wiki exported to pdf+docx, we will create an online blog after review (and then I will update the ticket).

Cheers Dietmar

Von: Paul Kulchenko
Antworten an: pkulchenko/ZeroBraneStudio
Datum: Mittwoch, 2. Dezember 2015 um 20:12
An: pkulchenko/ZeroBraneStudio
Cc: Dietmar Wolz
Betreff: Re: [ZeroBraneStudio] Remote debugging of mashape kong doesn't work (#560)


My company (Talend) decided they want to host the blog entry here at Talend, but we will not publish without considering your feedback. Expect a first version for review beginning of next week. We will slightly extend the scope, it will handle creation + debugging of a sample kong plugin using Zerobrane + SoapUI + Vagrant both on windows 7/64 (will work probably also on newer versions) and MacOS „El Capitan“.

Sounds good; just update the ticket when you have the draft and I'll review it. Thanks.

**Comment by pkulchenko** [comment]
Dietmar, I don't think attachments go through github mail system. You can send it to me directly (to the email in my profile).
