### ISSUE TITLE
result of #{nil, ..} differ from Reference Manual

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#562]
>2.5.5 - The Length Operator
>>The **length** of a table t is defined to be any integer index `n`, ... moreover, if `t[1]` is `nil`, `n` can be zero.

`#{nil, 0}` should return 0, but it equals 2.

Also, I found the strange behaviour of `table.remove` used on table with hold index, which is different from before. Different **interpreter**?
Test on Lua 5.1 with default Interperter of zeroBrane. Windows 7 64bit.

**Comment by pkulchenko** [comment]
@robertlzj, that's a Lua feature, not something that is controlled by the IDE. The default interpreter is LuaJIT (2.0.3 as of now), so there are some slight differences from Lua 5.1 interpreter. You can always set the interpreter you prefer by using `path` settings: https://studio.zerobrane.com/doc-general-preferences#interpreter-path
