### ISSUE TITLE
Rename instance works incorrectly in some case when code collapsed

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#564]
local b
	do
		if true then
			b = 1
		end
	end

Collapse `do` block, then rename `b` would see the problem.

**Comment by pkulchenko** [comment]
Thank you for the report; I'll take a look at what's going on.

**Comment by pkulchenko** [comment]
@robertlzj, should be fixed now. Let me know if it doesn't checks out in your tests.
