### ISSUE TITLE
Navigate selected instances works incorrectly if only contain one instances

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#565]
a = 1
	b = 2

Select and seach `b` , then Ctrl+DblClick `a`, using F3, will navigate between previous search - here is `b`.

Sorry, I report so many trivial and unimportant blemish.:grimacing:

**Comment by pkulchenko** [comment]
Confirm the issue. No worries about "unimportant blemish"; thank you for the reports as it has to work as expected.

**Comment by pkulchenko** [comment]
@robertlzj, this should be fixed now, but there is a small side-effect: when you select variable `a`, the search is set to search for `a`, which may find other instances of this (in addition to being a variable `a`). It's the result of using `FindNext/Prev` for two things, but I think it's a small price to pay as it only happens with one instance.
