### ISSUE TITLE
Include LFS DLL for lua 5.2 and 5.3

### ISSUE THREAD

**Issue by ajbrouwer** [pkulchenko/ZeroBraneStudio#566]
In the Windows install, bin/clibs has a lfs.dll. But bin/clibs52 and bin/clibs53 do not. Given that LFS is probably the most frequently required library beyond the standard libraries, including lfs for 5.2 and 5.3 will make ZBS function out-of-the-box in a markedly more batteries-includes fashion without adding much bloat.

**Comment by pkulchenko** [comment]
I'm on the fence about this. Yes, lfs doesn't require much space, but it still requires compilation for all supported platforms (for consistency) and updates for module versions. I've been avoiding adding libraries for the sake of having them (all the libraries included are used by the IDE itself), but I agree that lfs is small and widely used, so it may warrant an exception. I'll think about it.

**Comment by pkulchenko** [comment]
@ajbrouwer, I pushed an update to the build script, which should build lfs for Lua 5.2 (`cd build; bash build-win32.sh lua 5.2 lfs`) and Lua 5.3 (`cd build; bash build-win32.sh lua 5.3 lfs`). It will build and install DLLs in the right place.

Note that it will only work in the script that you are starting from the IDE. If you need to run them outside of the IDE, you'll need to copy the libraries to the folder where your scripts are.

**Comment by ksoo** [comment]
Does this require building ZeroBrane Studio from source?  So the downloadable ZeroBrane Studio 1.30 does not include those 5.2 and 5.3 lfs dlls?

**Comment by pkulchenko** [comment]
Yes, the downloadable version doesn't include those files, but you can build them using the build scrips in the repository (assuming you have dev tools installed, like gcc).

You can get the build scripts from the build folder in the repository; just copy the script for your platform in the `build` folder and run the commands in my earlier message. For example, to build lfs for Lua 5.3 on Windows run: `cd build; bash build-win32.sh lua 5.3 lfs`. This will build the lfs library and put it in the correct folder to use from the IDE.

I do have them built and I plan to include them in the future, but this needs to be done for all the platforms and I haven't done it yet. Let me know if you just need the DLLs and I'll make them available somewhere.

**Comment by ksoo** [comment]
Actually yeah, I would really appreciate if I could just get the 5.2 dll
from you.

I'm making space and downloading minGW and preparing to go through it all,
but I might be able to skip all that and just get back to my actual project
if I have the lfs dll.  The 'constant table overflow' problem of 5.1 is
holding up the project.

And a million thanks for creating such an awesome Lua IDE, blogs, and being
such an awesome developer in general. Been a huge fan.


Kelvin Soo
VP Software Engineering

NeuroSky • Body and Mind. Quantified.
125 S Market St #900 • San Jose, CA 95113
*M* +852 9682-0309
E kelvin@neurosky.com

Check out our NEW website!  www.neurosky.com


*"This email may contain confidential and privileged material for the sole
use of the intended recipient(s). Any review, use, distribution or
disclosure by others is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply email and delete all copies
of this message."*

**Comment by pkulchenko** [comment]
@ksoo, I pushed lfs DLLs for Lua 5.2 and Lua 5.3 to [lfs-win32](https://github.com/pkulchenko/ZeroBraneStudio/tree/lfs-win32) branch. You can simply copy them to the same location in your IDE installation (or copy them to your project).

**Comment by pkulchenko** [comment]
@ksoo, @ajbrouwer: this has been implemented in the wxwidgets31x-upgrade branch for all supported platforms.
