### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by SoniEx2** [pkulchenko/ZeroBraneStudio#567]
Can you add support for [XDG Base Directory](http://standards.freedesktop.org/basedir-spec/latest/index.html)?

**Comment by pkulchenko** [comment]
@SoniEx2, what would this affect and why would this be needed?

wxlua/wxwidgets interface limits me in a couple of ways (for example, I can specify the config file name, but not the folder where to store the config files) and whatever is available can be achieved with setting `init` settings value, so someone can probably write a wrapper around the launcher to provide settings based on environment variables.

**Comment by SoniEx2** [comment]
Well, first, I have way too many dotfiles in my home, and it makes it harder to use when you're not hiding dotfiles (which I don't, because of files such as `.gitignore`).

The main use case is to help me organize my home which is currently made up of 70% dotfiles and 30% important stuff.

**Comment by pkulchenko** [comment]
Hm, you should be able to configure what files to hide with either [file exclusion lists](https://studio.zerobrane.com/doc-general-preferences#file-exclusion-lists) or using `Hide '.ext' files` in the project tree menu.

**Comment by SoniEx2** [comment]
That's not system-wide.

**Comment by pkulchenko** [comment]
Why not? Exclusion list can be configured per instance, but you can also now "include 'file.lua'" in configuration files, which allows you to easily shared config files even across different instances.

I find it easier and more straightforward than adding XDG support.

**Comment by SoniEx2** [comment]
That won't exclude files on the other programs, only on ZBS.

**Comment by pkulchenko** [comment]
I'm confused: adding support for XDG in ZBS wouldn't exclude files in other programs either. Or am I missing something?

**Comment by SoniEx2** [comment]
They won't be placed directly in my home dir.

**Comment by pkulchenko** [comment]
@SoniEx2, I'm still confused; what files won't be placed in your home dir?

**Comment by SoniEx2** [comment]
The `.zbstudio`.

**Comment by pkulchenko** [comment]
They don't need to be. You can add a wrapper around zbstudio.sh that will set `HOME` variable to whatever value you need. You can also set `ini` configuration setting (possibly in the same wrapper using `-cfg "ini = 'whatever'"`) to store the configuration file wherever you need.
