### ISSUE TITLE
__tostring used in watch / stack window

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#569]
```
local table = setmetatable({},{__tostring = function(self) return 'my table' end})
table[1] = table
table[table] = 2	--watch window will only shows 'table = "my table"'.
```
Could the user specified name by `__tostring` only be used to replace the **address** (like `[[table: 0x123]]` which is meanless), especially when used as key (like `table[table] = 2`).
And so the table could **expanded**.

**Comment by pkulchenko** [comment]
It's a duplicate of #457. See the comments there and let's continue in that ticket.
