### ISSUE TITLE
Problem with project-related interpreters

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#570]
This is related to #555 and project specific packages.

Let's assume I have a package file `<projectdir>/.zbstudio/myinterpreters.lua`
```lua
local IA = { name = "IA", description = "interpreter IA" }
local IB = { name = "IB", description = "interpreter IB" }

return {
	name = "myinterpreters",
	onRegister = function(self)
		ide:AddInterpreter("IA",IA)
		ide:AddInterpreter("IB",IB)
	end,

	onUnRegister = function(self)
		ide:RemoveInterpreter("IA")
		ide:RemoveInterpreter("IB")
	end,
}
```

loaded via  `<projectdir>/.zbstudio/user.lua`
```lua
package"myinterpreters.lua"
```

Then I can select the interpreter `IA` or `IB` via menu `Project`/`Lua Interpreter`.
Works as expected so far...

**BUT** when I close ZBS and open it again, then I get the message:
`Can't find interpreter 'IA'; using the default interpreter instead.`

I didn't investigate very deeply, but I believe `ProjectSetInterpreter()` must be called, *after* project settings have been loaded.

> latests zbs from master on kubuntu 14.04LTS

**Comment by pkulchenko** [comment]
@jjvbsag, this should be fixed now. I also fixed keeping the interpreter when switching between projects (without restarting the IDE).

You may see the question mark after the interpreter name on the list of projects (like `IA?` or `IB?`). This happens because these interpreters are not loaded when the other project is selected, so it's not possible to get their attributes (and the IDE doesn't know if they are valid or not), so it only displays their filename along with a question mark. You should still be able to switch to those projects and a proper interpreter will be selected (as long as the project config loads those interpreters).

**Comment by jjvbsag** [comment]
>  I also fixed keeping the interpreter when switching between projects (without restarting the IDE).

(I can not verify before begin of next year) If I understand correctly, then I don't believe this is what developers want. In my point of view the selection of an interpreter belongs to the "project related settings".

I have 
* project "DameonXyTestClient" which has interpreter "Lua For Windows"
* project "DeviceABCApplication" which has interpreter "DeviceAbc Lua"
* project "JustSomeExperiments" which has interpreter "lua5.3"

When I switch from one project to another, I'd expect ZBS to switch to the interpreter last selected in that project. Because of this `IA?` can never happen, because it can only be selected in a project, where interpreter `IA` is available.

If you argue, you'll need *your* behaviour of interpreter-keeping, then I'd suggest to have a setting parameter in user.lua `ide.xxxx.switchinterpreterwithproject` set to `true` for my kind and to `false` for your kind of behaviour.

Regards Jørgen

**Comment by pkulchenko** [comment]
> When I switch from one project to another, I'd expect ZBS to switch to the interpreter last selected in that project. Because of this IA? can never happen, because it can only be selected in a project, where interpreter IA is available.

It's going to work *exactly* like you are describing, but you are missing one scenario. Imaging you have project "MyProject" which has interpreter "IA", but it's only added from the project config file. When you switch project to "JustSomeExperiments", "IA" interpreter is unloaded, so there is nothing in the system about it, but "MyProject" is still displayed on the list. Previously you'd see "?" in the interpreter field for it, now you'll see "IA?". I just wanted to explain the question mark after the interpreter name, which simply means that this particular interpreter is not known to the system at this time.

**Comment by jjvbsag** [comment]
Ok, I think I misunderstood the words *"keeping the interpreter when switching between projects"*. 
As I said, I will check next year - sounds like a long time but really it's only two weeks ;-)

So, for now  :notes: *I wish you a Merry Christmas and a Happy New Year*  :notes:

Regards Jørgen

**Comment by pkulchenko** [comment]
Jørgen, Merry Christmas and happy holidays to you as well!

Let me know how it works for you when you get a chance to try it.

**Comment by jjvbsag** [comment]
@pkulchenko Updated from master and works as expected. Thanks, regards and have a nice year.

**Comment by pkulchenko** [comment]
Great; thank you for the confirmation!
