### ISSUE TITLE
Code analysis and tagging function parameters as optional

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#571]
Simple question: How to I tag a function parameter as optional?

Example:
```lua
function divide(a,b)
	b=b or 2	-- default value
	return a/b
end

print(divide(15,3))
print(divide(15))
```
this runs perfect giving the output
> 5
> 7.5

But code analysis complains
> divide.lua:7: function 'divide': Too few arguments; expected 2 but got 1.

**Comment by pkulchenko** [comment]
I don't see a way to configure this, but luainspect should support hints in comments, so maybe they can be used in this case. I don't plan to do anything about it at the moment, but patches are welcome ;).
