### ISSUE TITLE
Change suggestion : Session information in a project related file

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#572]
> Session configuration
> Some configuration information that needs to be preserved between launches ... in %APPDATA%\ZeroBraneStudio.ini ... in $HOME/.ZeroBraneStudio on Linux.

Instead of filling this file with more and more session data, I'd suggest to save the
**_project related_ session information**
in a file `<projectdir>/.zbstudio/session.lua`. 

this should include at least
* from `[package/core.findreplace]` the items `slist`, `rlist`, `flist`
* from `[package/core.filetree]` the items `startfile`
* from `[package/core.outline]` the items `symbols` and `ignoredirs`
* everything in `[projectsession/*]`
* (I'm sure, I have not mentioned all ;-) 

Benefit's I can see
* If you rename/move a project, then session details won't get lost any more
* If you delete a project, then session details will get cleaned up automatically
* No performance loss, when you have lot's of project sessions stored ¹)
* Reading and writing data from/to lua is more lua-style then using the proprietary ini-file format.
* I also believe this will finally simplify some code in ZBS.
* I even believe `[package/core.outline]` `symbols` may blowout windows ini file specification due extreme long lines.

Saving project related information in a file located inside the project is good-practice for many IDEs ( e.g. `codelite` => `<projectdir>/.codelite/` with `compilation.db`,`project.session`, `project.tags` ...)

**and for the remaining stuff**
You already use `%HOMEDRIVE%%HOMEPATH%\.zbstudio\` resp. `~/.zbstudio/` for packages and user.lua. Why don't put the remaining data into another file (e.g. `zbstudio.lua`) *inside* this `.zbstudio` folder? Then I can find it in *one* place. Currently on my windows I find `ZeroBraneStudio.ini` at `C:\Users\MyUserName\AppData\Roaming`, but `.zbstudio`-folder at `P:\` .

Regards Jørgen

¹) I know, lua is fast enough anyway :-)

**Comment by pkulchenko** [comment]
I think it would be an overkill to split this information into multiple files (and for a little gain in my opinion), but you should be able to achieve a very close result by using project-specific .ini file. You can simply provide a batch file that will start the IDE and store the configuration in a local ini file using [ini config option](https://studio.zerobrane.com/doc-general-preferences#general) that can be passed on the command line.
