### ISSUE TITLE
Step over will step into tail call

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#573]
```
function g()
end
function f()
	return g()	--use 'step over' will 'step into' function 'g' (instead of jump out function 'f').
end
f()
```
'Lua' interpreter. zeroBrane Studio 1.20.

**Comment by pkulchenko** [comment]
What Lua interpreter?

**Comment by robertlzj** [comment]
'Lua' the default one? from IDE.

**Comment by pkulchenko** [comment]
I think there is not much I can do. I've tested with all Lua interpreters and the result is exactly the same. I think it simply happens because the tail call doesn't create a new call stack, but replaces the existing one (which is the idea behind tail calls) and since it's the same call frame, when the check is made it matches the expected call stack depth (the "step over" call simply stops at the first Lua statemet the same stack level).

**Comment by robertlzj** [comment]
I checked `debug.sethook` recently, there seems to be some info could be used.
> When the hook is called, its first parameter is a string describing the event that has triggered its call: "**call**", "**return**" (or "**tail return**", when simulating a return from a tail call),   
  
  
Or **lines** (`currentline`) from `debug.getinfo` could help?
I saw changes from _"f at line **5** (defined at test.lua:**3**)"_ to _"f at line **2** (defined at test.lua:**1**)"_, where 'f' is re-used, but **line** changed (there is a lot of *lines* in `lua_getinfo` :smile: ) .

**Comment by pkulchenko** [comment]
Right, I'm aware of "tail return", but in this case "tail call" is needed and it's only added in Lua 5.3 as far as I remember. I checked the stack trace depth and it doesn't change when that call happens, which leads to the results you see.

The fact that `currentline` has changed is not helping here as I can only check against the stack depth; plus any additional checks may affect performance for the debugger.

**Comment by robertlzj** [comment]
Eh..Lua has *tail call* at least from **5.1**. :grimacing: 
Yes. *stack trace depth* doesn't change, the function's name doesn't neigther. So check from them isn't sufficient.

I think only in this **case** - when user uses **step over** to debug which might jump out current function, could `sethook` for current function to get "return" or "tail return".
And maybe not to do these additional check on lines.

**Comment by pkulchenko** [comment]
> Eh..Lua has tail call at least from 5.1.

Yes, I meant that debug hook events don't mark tail calls as tail calls. The event is "call" in this case; only Lua 5.2+ added "tail call" (and remove "tail return"):

Lua 5.3 and Lua 5.2:

```c
  static const char *const hooknames[] =
    {"call", "return", "line", "count", "tail call"};
```

Lua 5.1:

```c
  static const char *const hooknames[] =
    {"call", "return", "line", "count", "tail return"};
```

> I think only in this case - when user uses step over to debug which might jump out current function, then could sethook for current function to get "return" or "tail return"

I don't think it helps to jump out of the current function as we didn't get into a new function yet and when we do, we shouldn't stop there. There are probably ways to deal with it (for example, skip any "call" events when doing "step over"), but they all complicate logic for other cases and this seems to be a rare corner case to worry about.

**Comment by robertlzj** [comment]
Oh, I see "tail return" and "tail call".
>Lua 5.1 debug.sethook
>> "call", "return" (or "**tail return**", when simulating a return from a **tail call**), 

Doesn't *tail call* is only a new name of *tail return*? I confuse with them.
Or, *tail return* happens when return from *tail call*...

OK. I agree *this seems to be a rare corner case to worry about*. Thank you.
