### ISSUE TITLE
Request: Auto expand collapsed code block when debug

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#575]
Currently when debug, step may jump into a **collapsed** code block - a `function`, `do`, `then` etc, and **indicator** will 'hidden', so often I lose my active line. And need to **expand** each block manually.
Could **auto** expand it in this case.
Or, more intelligence - use **step into** to expand it, and use **step over** to run until the next line that not collapsed?

**Comment by pkulchenko** [comment]
@robertlzj, I added auto-expanding those collapsed blocks; thanks for the report.
