### ISSUE TITLE
Highlight all other instances of a word

### ISSUE THREAD

**Issue by Tribeam** [pkulchenko/ZeroBraneStudio#576]
When you highlight a single word, all other instances of that word are also highlighted.
This is called 'Smart Highlighting' in Notepad++.
Here's a gif better explaining it using a default love2d config file: https://dl.dropboxusercontent.com/u/49758621/smart_highlight.gif

Not really an important feature, but I've found it useful is some cases.

**Comment by pkulchenko** [comment]
@Tribeam, sure; try this plugin: https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua. See the discussion here: http://www.freelists.org/post/zerobrane/Feature-Request-Highlight-Current-Word,10
