### ISSUE TITLE
Shooting not working in LOVE-samples/shooter

### ISSUE THREAD

**Issue by maacl** [pkulchenko/ZeroBraneStudio#578]
The error appears to be in this function:

```
function love.keyreleased(key)
  if (key == " ") then
    shoot()
  end
end
```

which should check for "space" instead of " ".

I am on Windows 7 using ZeroBraneStudioEduPack-1.20-win32 and LOVE 0.10.0 Super Toast.

**Comment by pkulchenko** [comment]
I'll update the example, but this was only changed in a recently released 0.10 version ("In version 0.9.2 and earlier this is represented by the actual space character ' '." per https://love2d.org/wiki/KeyConstant)
