### ISSUE TITLE
package loadlib crash in local console Lua 5.3

### ISSUE THREAD

**Issue by bondhan** [pkulchenko/ZeroBraneStudio#579]
Hi,

I developed my own dll containing libraries, it run and worked peacefully in the code editor, however when I tried to run it on console it crashed. This is the command:

package.loadlib("LuaSmartCardLibrary.dll", "luaopen_card")()

Some dump:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	zbstudio.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5563c858
  Fault Module Name:	Lua53.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	56114c7f
  Exception Code:	c0000005
  Exception Offset:	0000145b
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by pkulchenko** [comment]
> Fault Module Name: Lua53.dll

You seem to have a library that depends on Lua53.dll and you can't load Lua53.dll from Local console as it already has Lua51.dll loaded (it's actually LuaJIT DLL, but it has the same ABI as Lua51.dll). If you want to play in the console using Lua53, just switch to Lua53 interpreter and start debugging on some simple Lua script.

It may be possible in the future to run custom interpreters from the console (see #490 and #493 tickets), but it hasn't been implemented yet.
