### ISSUE TITLE
Running scripts all together in sequence

### ISSUE THREAD

**Issue by bondhan** [pkulchenko/ZeroBraneStudio#580]
Hi,

Do you plan for ZBS to be able to run the scripts all together in sequence for example:

```
folder_root:
         00.script_init
         01.script_execute
         02.script_closing
         second_folder_:
                    00.another_script:
                    01.another...

```

then the user just need to right click on the folder (in this case folder_root) and click execute. It will then execute the script one by one into the same VM of Lua (based on how it was sorted?).  

Thanks.

**Comment by madmaxoft** [comment]
Hi,
we use a similar setup for our project, Cuberite (www.cuberite.org) and the easiest solution is to use a custom interpreter for the project. Here's the interpreter code for our project: https://github.com/madmaxoft/ZeroBranePackage/blob/master/cuberite.lua

**Comment by bondhan** [comment]
Hi @madmaxoft 

Thanks. 

I copied the cuberite.lua to the packages folder, would you kindly tell me how to use it? Because I search around if there is any option to execute the whole files in the tree but could not find it.

**Comment by pkulchenko** [comment]
@bondhan, I don't plan to have anything specific in the IDE to support this particular case, but there are several options to enable that. One of them is to have your own interpreter, as @madmaxoft suggested. Another one is to have a launch script -- the script you write that uses lfs or something similar to get the list of scripts to execute according to your criteria (using `dofile`, `os.execute`, or whatever else works for you) -- and then mark that script as the start script in the IDE (right click on the file in the Project tree and select `Set As Start File`). Now when you initiate running or debugging, it will always start from that script, so you should get the expected effect as if you are running all those scripts.

Another option, which may be useful if you only need this occasionally, is to make a short plugin and add toolbar/menu item that executes that logic for combining the script; see the documentation here: https://studio.zerobrane.com/doc-plugin#example-adding-a-menu-item-and-a-toolbar-button-that-run-make

In general, if you have a question, it's better to [use the maillist or the IRC channel](https://studio.zerobrane.com/community).
