### ISSUE TITLE
Unknown SCRIPT subcommand or wrong # of args.

### ISSUE THREAD

**Issue by rawsoft** [pkulchenko/ZeroBraneStudio#581]
When I try to run any script with Redis on my localhost on windows I get the following message.

Unknown SCRIPT subcommand or wrong # of args.
Program completed in 0.03 seconds (pid: 376504).

any ideas how to solve this?

**Comment by pkulchenko** [comment]
@rawsoft, are you running the correct version of Redis server? I believe you should be running 3.2 (which is in beta now).

**Comment by pkulchenko** [comment]
@rawsoft, have you checked if you use the Redis version that supports debugging?
