### ISSUE TITLE
Project / Command Line Parameters... are not preserved

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#583]
When I enter some parameters at `Project`/`Command Line Parameters`, I'd expect them to be preserved on a per-project basis.

When I enter parameters, close ZBS and restart ZBS they are gone.
When I enter parameters, then select another project and then return to the first project, parameters are gone too. 
This is sad.

**Comment by pkulchenko** [comment]
This is probably too late for the next release, but shouldn't be too difficult to do in one after it. Thank you for the suggestion.

**Comment by itamarhaber** [comment]
:+1:

**Comment by jjvbsag** [comment]
@pkulchenko As this is a NiceToHave and no blocker, scheduling this issue for 1.40 is fine for me
Thanks

**Comment by pkulchenko** [comment]
@jjvbsag, @itamarhaber, this functionality has been added. Give it a try and let me know how it works for you.

**Comment by itamarhaber** [comment]
@pkulchenko works great, thank you :+1: 

However, no good deed goes unpunished :smiling_imp:: #610

**Comment by jjvbsag** [comment]
Tested with current master.
Simple  script:
```lua
for i=0,#arg do
	print(i,arg[i])
end
```
Running gives
```text
0	/home/joergen/Lua/zbstudio-args/show-args.lua
```
Entering `abc def "ghi jkl"` in Commandline parameters gives
```
0	/home/joergen/Lua/zbstudio-args/show-args.lua
1	abc
2	def
3	ghi jkl
```
- Closing ZBS, 
- Reopen ZBS,
- Run
```
0	/home/joergen/Lua/zbstudio-args/show-args.lua
1	abc
2	def
3	ghi jkl
```
Fine :+1:
- Changing to another project
- Returning to this project,
- Run
```text
0	/home/joergen/Lua/zbstudio-args/show-args.lua
```
This needs more work :back:

**Comment by pkulchenko** [comment]
@jjvbsag, I can't reproduce this; I tried switching to projects that have interpreters that support command line parameters and those that don't support command line parameters, but switching projects doesn't remove the command line parameters for me. Can you try one more time and provide more details on what interpreters are used and what steps you go through? Thanks.

**Comment by jjvbsag** [comment]
@pkulchenko I'm a bit busy at the job. I will provide more info as soon as possible...
Regards

**Comment by jjvbsag** [comment]
Ok, now I did the testing (on a clean Win7 VM)
# Preparation
- install ZeroBraneStudio-master into C:\bin\ZeroBraneStudio-master
- create `c:\lua\proj-a\show-args.lua` (with above simple test script)
- add to project list via "Set project dir from current file"
- create `c:\lua\proj-b\show-args.lua`
- add to project list via "Set project dir from current file"

# Test
- select `proj-a`   ¹)
- Enter Project/Commandline parameter... `parameter-a`
- run script
```
0	C:\lua\proj-a\show-args.lua
1	parameter-a
```
- select `proj-b`
- Enter Project/Commandline parameter... `parameter-b`
- run script
```
0	C:\lua\proj-b\show-args.lua
1	parameter-b
```
- select `proj-a`
- run script
```
0	C:\lua\proj-a\show-args.lua
1	parameter-b
```
Expected to show `parameter-a`

Ok, this may be because there is no projectsettings.lua 
So 
- exit zbs
- download `projectsettings.lua` and install into C:\bin\ZeroBraneStudio-master\packages
- restart zbs.

# New test
- select `proj-a`  
- Enter Project/Commandline parameter... `parameter-a`
- run script
```
0	C:\lua\proj-a\show-args.lua
1	parameter-a
```
- select `proj-b`
- Enter Project/Commandline parameter... `parameter-b`
- run script
```
0	C:\lua\proj-b\show-args.lua
1	parameter-b
```
- select `proj-a`
- run script
```
0	C:\lua\proj-a\show-args.lua
```
Expected to show `parameter-a`, but now the commandline parameter is lost. :cry: 

Hope, this helps you to find the problem. Regards Jørgen

¹) Selecting project is done with the `Recent projects` dropdownlist icon.

**Comment by jjvbsag** [comment]
PS: Interpreter is the builtin `Lua`-interpreter all the time

**Comment by pkulchenko** [comment]
> Expected to show parameter-a

@jjvbsag, this is by design. The current mechanism doesn't track command line by project; it just stores it between restarts as is. It may be possible to extend it to be per-project in the future, but so far I have made no attempt to do that as I wasn't sure if it's ever needed.

I'll check what's going on with the project settings.

**Comment by jjvbsag** [comment]
Ok, understood. The please file this a a feature request.
