### ISSUE TITLE
Runtime error when trying to open file on Mac OS

### ISSUE THREAD

**Issue by OttoRobba** [pkulchenko/ZeroBraneStudio#587]
1 - Fresh install
2 - Pressed CMD+P
3 - Runtime error
![screen shot 2016-01-22 at 10 26 52 am](https://cloud.githubusercontent.com/assets/597287/12510654/ab03f30e-c0f2-11e5-9132-ce6ce7eba092.png)

**Comment by pkulchenko** [comment]
@OttoRobba, I can only reproduce this if `styled.text.fg` or `styles.caretlinebg.bg` is set to `nil`. Do you have something to that effect in your config file?

If the default or correct styles are used, I don't get any errors. Could you confirm?

**Comment by OttoRobba** [comment]
Hmm yes, that was it! I had set the bg but in the process clobbered the fg.
Thank you Paul! :+1:

**Comment by pkulchenko** [comment]
Good; thank you for confirming that. I plan on adding a check to avoid throwing an error in a case like this.
