### ISSUE TITLE
Allow user preferences to select font style other than normal, bold and italic

### ISSUE THREAD

**Issue by spicykaiju** [pkulchenko/ZeroBraneStudio#588]
It would be really nice if you could add a "editor.fontstyle" configuration option, for users who utilise fonts that have styles other than "normal" "bold" and "italic".

For example, from the below "Input Mono" font, I would like to do the following:

```
editor.fontname = "Input Mono"
editor.fontstyle = "Thin"
```

![screen shot 2016-01-23 at 16 09 20](https://cloud.githubusercontent.com/assets/384978/12530845/e86c7032-c1eb-11e5-93ae-8a24a4a672d7.png)

**Comment by pkulchenko** [comment]
I agree, it would be interesting, but I don't see a way to provide that information when a font is loaded in wxwidgets. Here is the [wxfont description](http://docs.wxwidgets.org/trunk/classwx_font.html) and here is the [list of supported styles](http://docs.wxwidgets.org/trunk/interface_2wx_2font_8h.html#ab8f87d0b928ad1f8cba7d1c01f5f7a55). I'll ask on the maillist, but don't think there is a way in the API.

Have you tried specifying font name as `"Input Mono Thin"`?

**Comment by spicykaiju** [comment]
Yup, I tried with ```"Input Mono Thin"``` however this does not resolve to the target font. The "Thin" label is a reference to the type. It would be cool if this worked however!

**Comment by pkulchenko** [comment]
Thank you; I emailed [wx-users mail list](https://groups.google.com/d/msg/wx-users/mfPzIIsjEi8/sbf_GUHAAgAJ); we'll see what the responses are.

**Comment by pkulchenko** [comment]
@spicykaiju, do you know if these styles are different sub-fonts or is this just a matter of setting font weight? I suspect is the former, so the only thing that was recommended, that may be relevant to this issue ([ticket #9302](http://trac.wxwidgets.org/ticket/9302)), may not help in this case, as this enhancement would only allow to set the weight (and even that still needs to be tested and included in wxwidgets). I'm just trying to see if this would even help in your case and if would be worth spending time on...

**Comment by pkulchenko** [comment]
@spicykaiju, closing for now as this is unlikely to happen until this is implemented in wxwidgets.
