### ISSUE TITLE
Add support direct support for LuaDoc Comments

### ISSUE THREAD

**Issue by HAJ523** [pkulchenko/ZeroBraneStudio#589]
1.) Add support to generate LuaDoc comment based on function signature with TODO replacement strings.

Example of potential TODO replacement for a function:
```Lua
--- (TODO Function resume)
-- (TODO Additional description)
-- @param row (TODO Parameter description)
-- @param col (TODO Parameter description)
-- @param ht (TODO Parameter description)
-- @param wd (TODO Parameter description)
-- @return obj (TODO Return description)
function class:new(row, col, ht, wd)
  return obj
end
```
(Note: From the example how the comment pulls in the parameter names and return name. If there were multiple returns i would expect to see 1 line for each. providing the parameter name if one exists makes reading the code afterwards easier.)

Allow for these types of comments to be auto added to the top of new files created such that you can allow "class" definition comments.

Example of potential "class" definition comments
```Lua
-- @class (TODO Class name)
-- @author (Config Specifiable string)
-- @release  (Project Specifiable String)
-- @description (TODO Class description)
```
(Note: Allow for project level strings to be replaced in all files when they are updated. This will prevent the user needing to increment all file versions manually.)

2.) (Optional) Add support to generate documentation directly from ZeroBrane. This should generate the appropriate HTML files to a specified directory in the project along with an index page.

3.) (Optional) Add support to open this documentation directly in ZeroBrane such that a user could open the documentation of a tag written from right click on the file in the project view.

**Comment by pkulchenko** [comment]
@HAJ523, for the first item, do you mean something like moving cursor to the function definition, applying a shortcut (or selecting an item from a menu) and getting LuaDoc text populated before the function based on the name, parameters and return values?

**Comment by HAJ523** [comment]
@pkulchenko, Yes or alternatively also allow these to be applied to an entire file.

**Comment by pkulchenko** [comment]
Alex, I'm not likely to work on this in the near future, but it shouldn't stop you from trying to make a plugin out of it. I can help with some suggestions and ideas and am open to extending the API if needed to support this.

Basically, you can use a simple syntax checks if you want to get the function definition from the current line, but handling "return" is trickier, as you need to find all the returns in that function. You can probably use information where functions start and end (similar to how it's done in `outline.lua` where the current function is marked in the outline, which requires knowing where the functions starts and ends). If you get to that point, I can check on how to expose this information to the plugins...
