### ISSUE TITLE
REQ: Add "alien" to zbs

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#592]
See http://alien.luaforge.net/ for details. 
I use alien quite often to access windows libraries (as shown in https://github.com/pkulchenko/ZeroBraneStudio/files/38723/dump-windows-clipboard.txt regarding #556).

Missing **alien** is one of the last things keeping me at LuaForWindows as an interpreter.
(The other thing is iup/im/cd, but as you are stuck to wx I hardly dare to ask for them ;-)

**Comment by jjvbsag** [comment]
addendum: I'd also like to have alien on linux, just if there was any doubt ...

**Comment by pkulchenko** [comment]
I'm not sure what kind of support is needed. You should always be able to load modules from your folder even without using LuaForWindows interpreter, just set `package.path/cpath` correctly.

**Comment by jjvbsag** [comment]
For me alien is a kind of standard module as bit, lfs, socket,... 
So I would like to have alien in a vanilla ZBS install. 
Of course **I** can install the required devtools for win,linux,... and build alien for myself. But for the people, I want to push to use zbs as a development tool, I'd better argue "install zbs and you have all you need"

**Comment by CapsAdmin** [comment]
Just out of curiosity have you tried LuaJIT's FFI library? And if you have why are you still using alien?

**Comment by jjvbsag** [comment]
We started using alien, because it was available with LuaForWindows a long time ago. 
We continue using alien, because there is a lot of existing code, which would have to be rewritten, verified and tested again before using ffi.

Yes, I have checked ffi and as far as I can see, a switchover would be possible. But it would require a reasonable amount of work, which I just don't get time/money for at the moment.

**Comment by pkulchenko** [comment]
@jjvbsag, I plan to first include lfs and luasec modules that are in high demand; I also have plans for using luasec in ZBS itself, so it would be needed anyway.

I'm deferring this as I don't plan to include "alien" in the next release or two, but will consider options for packaging binary modules as plugins, which should allow for simple installation (when the package manager is available).

**Comment by pkulchenko** [comment]
@jjvbsag, FWIW, you can get alien installed (at least on Windows) if you add luadist package and then call `luadist.install "alien"` from the Console. You can then use "alien" either directly from the Console or from the scripts you run from ZBS (but only if luadist package is installed). It works well for all luadist packages, but some of the binary ones are outdated. You can compile your own though if you have mingw or VS configured.
