### ISSUE TITLE
Zbstudio starts at unreachable screen position - Windows

### ISSUE THREAD

**Issue by 1linux** [pkulchenko/ZeroBraneStudio#593]
If I leave zbstudio with a screen position on the very right, and fire up zbstudio again on a small display ( eg laptop´s builtin display ), the program screen might be invisible. You then have to manually edit the Ini-file.

Example:
`    [MainFrame]`
`    s=0`
`    x=2147`
`    y=23`
`    w=1268`
`    h=860`

This is bad on a 1440x900 display :-)
Maybe zbstudio could check if screen coordinates are in visible range at startup?

Regards Helmut

**Comment by pkulchenko** [comment]
@1linux, this is an interesting problem. Yes, I think it should take the current display size into account and reset the position if it's outside of the range. Let me see what I can do...

**Comment by pkulchenko** [comment]
@1linux, I added a fix for this; the logic is only triggered in one-display configuration and will re-center the window (after adjusting its size) if any of its side is outside of the current screen. Give it a try.

**Comment by madmaxoft** [comment]
@paul, did you take into account that maximizing a window on Windows stretches it several pixels outside the screen? I did some preliminary tests and it seems that a maximized window doesn't lose its position after the change, but I just want to be sure it's been considered :)

**Comment by pkulchenko** [comment]
@madmaxoft, yes, maximized is saved as its own state, so the window is restored Maximized with the size/position being ignored in that case.

**Comment by 1linux** [comment]
Works perfectly for me. Thank you!
