### ISSUE TITLE
Toolbar disappear after switching from FullScreen mode and stopping debugging

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#594]
### Procedure to reappear the problem: 
Run debug under full screen, when script pause at breakpoint, toggle to cancel full 
screen, then when debug finished, the Toolbar disppeared.

**Comment by pkulchenko** [comment]
Thank you for the report; will fix shortly.

**Comment by pkulchenko** [comment]
@robertlzj, this should be fixed.
