### ISSUE TITLE
Context menu after AppsKey has different enable/disable states than menu after right-click

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#596]
In 'Local console' window, **popup content menu** from **AppsKey** (menu key) on keyboard and from **mouse right-click** are not consistent.
Their popup menu's **appearance** are the same, except the enable / disable state, and underline indicator for hotkey.
It puzzled me a lot, for I can't copy by using AppsKey.

PS: Can't use Ctrl-C to copy from 'Local console' window too.
Currently only find mouse right-click menu could do it.

**Comment by pkulchenko** [comment]
I don't have `AppsKey` on my keyboard to try and none of the emulations I tried (`Shift-F10` or similar) work. I'll need to find a keyboard this works on.

I can't confirm the issue with `Ctrl-C`; copying from `Local Console` works as expected for me (select text, hit `Ctrl-C`, move cursor, hit `Ctrl-P`, copies selected text as expected).

**Comment by robertlzj** [comment]
I tried again.
Operations at '**Output**' sub tab-window is OK.
Problem still exist at '**Local console**'.

Menu from `Shift-F10` is the same as right-click. Except, using `Shift-F10` the selection will lose ,and the cursor will be active.
I think it's the problem - the selection lose. So does` Ctrl-C `to copy.

**Comment by pkulchenko** [comment]
I agree; I think that's why you see different enable/disable states. I generate the menus in exactly the same way when AppsKey or right click is used (it's the same event, so I don't even see the difference in the application). When this happens, `Ctrl-C` obviously won't work; but it should still work if you use `Ctrl-C` (or `Ctrl-Ins`) without opening the context menu.

Closing as there is nothing I can do to change this behavior.

**Comment by robertlzj** [comment]
**additional**: 
In my layout, the output window is float (not fixed).
In this case, `Ctrl-C` still won't work (lose selection) in 'Local console' which won't open context menu.

**Comment by pkulchenko** [comment]
@robertlzj, I'm confused about Output/Local console window floating. It can only be moved with the entire panel. Can you post a screenshot (along with the popup menu)? You can grab it using `PrntScr` button and then crop the screen to leave only the app window.

**Comment by robertlzj** [comment]
Eh...Sorry, the **float**, means **undock**, which is oppesite of stick.
So, need I capture the screenshot? :smile: 

With a little more test.
1. In undock Local console window, `Ctrl-C` will focus to the interactive line at bottom, and lose selection nothing copied.
2. **AppsKey** menu is the same as right click menu on cursor in last line for interactiving without selection.

**Comment by pkulchenko** [comment]
Got it; I'll look at (1), but there is nothing I can do for (2) if using AppsKey removes selection.

**Comment by robertlzj** [comment]
Yes, thank you. I think all the problems are the same matter - When the window is undock, key click will de-select and active cursor for inputing.

**Comment by pkulchenko** [comment]
@robertlzj, the copying should be fixed now for the floating panel. There is still a small inconsistency between docked and floating when trying to paste into read-only text, but I'm going to ignore that.
