### ISSUE TITLE
Can't assign keyboard shortcuts for context menu items

### ISSUE THREAD

**Issue by Ryan1729** [pkulchenko/ZeroBraneStudio#597]
I looked [in the docs](http://studio.zerobrane.com/doc-editor-keyboard-shortcuts) and in [editor.lua](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/keymap.lua) and I couldn't find a way to map context menu items like "Go to Definition" and "Rename all instances" to keyboard shortcuts.

Also the existing "Go to Definition" shortcuts Ctrl/Cmd+Alt+Click and Alt-Left only seem to be documented in the changelog.

**Comment by pkulchenko** [comment]
@Ryan1729, this indeed is not available now as context menu shortcuts are not available. This is limited by the toolkit design that allows shortcuts to only work for menu items and for items registered in the shortcut table.

It may be possible to expose those items or add them to the global shortcut table, but this also requires the callback functionality to work in the global context. I'll keep the ticket open for now as I'd like to take a look at what's needed to enable this.

Good point on the documentation; I'll need to find a place for this in the documentation. Any suggestions? Where would you look for it?

**Comment by Ryan1729** [comment]
[This](http://studio.zerobrane.com/doc-editor-keyboard-shortcuts) was the first place I went to when I looked for any existing shortcuts for the context menu.

**Comment by pkulchenko** [comment]
Interesting; these are only for editor component itself, so anything added in the IDE itself would not be on this list. I should probably add a note to that effect (although the difference may be confusing to users).

Basically, all menu shortcuts would not be on this list, so I guess shortcuts for some functionality, like `Cmd-Click`, which are not in the menu, *could* be on this page. I need to think about proper placing of that information; maybe *general* shortcuts page and *editor* shortcuts page, similar to how it's done for preferences.

**Comment by pkulchenko** [comment]
Related ticket #405.

**Comment by pkulchenko** [comment]
@Ryan1729, this has been added in the current master branch. The documentation for how this can be done is available here: https://studio.zerobrane.com/doc-general-preferences#key-mapping

So far this is enabled for those items that appear on the editor context menu: `ID.GOTODEFINITION, ID.RENAMEALLINSTANCES, ID.REPLACEALLSELECTIONS, ID.QUICKADDWATCH, ID.QUICKEVAL, ID.ADDTOSCRATCHPAD`. Let me know if you run into any issues.

**Comment by Ryan1729** [comment]
I tried defining keymaps for a few of those and everything's working great so far!
