### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by denisdemais** [pkulchenko/ZeroBraneStudio#605]
Hi! ZBS is pretty cool! congratulations.

1. move line using <ctrl-up or down>  (like notepad++)
2. inform encode file (ansi, utf-8, ...) + EOL (win, unix, osx) @ status line
3. highlight and replace all occorences of selected word (like notepad++)
4. supporte / shortchut to 'build using makefile' at current directory / project --- (i'm uses a makefile, compiles, test then upload)
5. project file configuration
6. add support to 'special' (custom) lua interpreter
7. some basic integration/support with git 
8; some basic integration/support with xUnit (lunit, busted - i.e.)
9. anti-aliased ttf/fonts
10. ident 'lines' issue when don't have tabs (the line broken)

**Comment by pkulchenko** [comment]
@denisdemais, thank you for the feedback.

> move line using (like notepad++)

Using what? ;)

> inform encode file (ansi, utf-8, ...) + EOL (win, unix, osx) @ status line

only utf-8 encoding is supported and EOLs can be mixed; also it takes a while to scan/analyze them on large files.

> highlight and replace all occorences of selected word (like notepad++)

There is [highlight selected](https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua) plugin.

>  supporte / shortchut to 'build using makefile' at current directory / project --- (i'm uses a makefile, compiles, test then upload)

You can easily add your own; for example: https://studio.zerobrane.com/doc-plugin#example-adding-a-menu-item-and-a-toolbar-button-that-run-make

> project file configuration

There is [project settings](https://github.com/pkulchenko/ZeroBranePackage/blob/master/projectsettings.lua) plugin that supports that.

>  add support to 'special' (custom) lua interpreter

There are ways to add interpreters that do what you need; there is also [plugin API to register an interpreter](https://studio.zerobrane.com/doc-plugin#registering-an-interpreter).

> some basic integration/support with git 8; some basic integration/support with xUnit (lunit, busted - i.e.)

Busted is already supported as one of the interpreters you can switch to. Version control integration has already been requested (#165), but hasn't been implemented yet.

> anti-aliased ttf/fonts

This is too low level for the IDE; are there any specific issues? On what platform?

> ident 'lines' issue when don't have tabs (the line broken)

Specific examples?

**Comment by CapsAdmin** [comment]
I assume you mean move line as in notepad++ move line with ctrl+shift up/down

https://github.com/pkulchenko/ZeroBranePackage/blob/master/moveline.lua

**Comment by denisdemais** [comment]
@CapsAdmin yes, is it! (i will check this, i don't know about packages in ZBS)

@pkulchenko:
move line using (like notepad++)
In notepad++ we can move selected line(s) using to down <ctrl-down> or up <ctrl-up>

anti-aliased ttf/fonts
  his is too low level for the IDE; are there any specific issues? On what platform?
TFT/LCD all high resolutions the font are 'poor' quality visually + DPI

Specific examples?
![image](https://cloud.githubusercontent.com/assets/13302670/13677918/e359e94a-e6ca-11e5-87da-4f44c5bbd51c.png)

i will check for solutions recomended!
thanks for any!

**Comment by pkulchenko** [comment]
> TFT/LCD all high resolutions the font are 'poor' quality visually + DPI

Hm, I'm using the IDE on a hidpi screen under Windows8 and don't see any issues with the fonts (and I don't see 'poor' quality on your screenshot either).

> if line is 'blank' (don't have tabs or spaces) the 'ident guide line' is hided

set `editor.indentguide = wxstc.wxSTC_IV_LOOKBOTH`; see `editor.indentguide` documentation on [this page](https://studio.zerobrane.com/doc-editor-preferences).

I'm closing this as most of these requests can be answered with existing plugins and for others, there are existing tickets. We can continue the discussion on the font quality here...
