### ISSUE TITLE
Uncaught Lua Script Exception ZB 1.30 [64 bit Windows 7]

### ISSUE THREAD

**Issue by Capital-EX** [pkulchenko/ZeroBraneStudio#607]
When trying to run ZeroBrane 1.30 on 64 bit Windows 7 the following error appears:

>**Uncaught Lua Script Exception**
>src/editor/style.lua:383: attempt to index field 'varglobal' (a boolean value)
>stack traceback:
>>[string "Initializer"]:1: in function '__index'
>>src/editor/style.lua:383: in function 'StylesApplyToEditor'
>>src/editor/output.lua:34: in main chunk
>>[C]: in function 'dofile'
>>src/main.lua:624: in main chunk
>>[string "Initializer"]:1: in function <[string "Initializer"]:1>
>>[C]: in function 'xpcall'
>>[string "Initializer"]:1: in main chunk

**Comment by pkulchenko** [comment]
@Capital-EX, it seems like you have something in the config file that sets `varglobal` indicator to a boolean value instead of it being a table with `st`, `bg`, `fg`, and other fields. Try running with the empty configuration file and see if you still have the issue; if not, check the config file for `varglobal` assignments.

**Comment by pkulchenko** [comment]
@Capital-EX, I still think it's a misconfiguration (and would like you to confirm), but I added a check for the indicator value being tables (as expected), so it should no longer fail in this case.

**Comment by Capital-EX** [comment]
sorry about the delay.
Running Zerobrane without tomorrow.lua lets the program open without any errors.

**Comment by pkulchenko** [comment]
@Capital-EX, there has to be something else too: if I simply add `styles = loadfile('cfg/tomorrow.lua')('Tomorrow')` to the config, then 1.30 loads without any errors. Do you have something else in the config?

**Comment by Capital-EX** [comment]
I found my error. It appears at some point I mistakenly changed styles.indicator.varglobal to a Boolean value.

**Comment by pkulchenko** [comment]
ok; good. The change I checked in should fix the issue as well.
