### ISSUE TITLE
Command line parameters shouldn't be cleared on Escape

### ISSUE THREAD

**Issue by itamarhaber** [pkulchenko/ZeroBraneStudio#610]
Even before #583, but now more than ever, I find that I open the dialog only for reviewing the parameters. Esc is instinctive but destructive.

**Comment by pkulchenko** [comment]
@itamarhaber, I noticed the same thing, but unfortunately `wxGetTextFromUser` doesn't distinguish between entering an empty string (with `OK`) and using `Cancel`/`Escape` (it returns an empty string in both cases). I'll see if I can find a more flexible method.

**Comment by pkulchenko** [comment]
@itamarhaber, should be fixed now.

It may make sense to show the parameters (at least the beginning of them) next to the interpreter name in the bottom right corner (in the Status bar)... Need to think about it.

**Comment by itamarhaber** [comment]
Figured as much but still wanted to point it out - https://github.com/pkulchenko/ZeroBraneStudio/commit/515d3fd6c315080eb75359e2e2309dcadfc0d271 works great for me.

**Comment by pkulchenko** [comment]
Sounds good; thanks for bringing it up! ;)
