### ISSUE TITLE
filter out commented search results

### ISSUE THREAD

**Issue by keszegh** [pkulchenko/ZeroBraneStudio#612]
it would be useful to be able to search for only results that are 'active', that is, not in comments.

**Comment by pkulchenko** [comment]
Should be doable; do you have many occurrences that happen to be in the comments? Do you have an example to share?

**Comment by keszegh** [comment]
well, often i just comment out a code i don't need temporarily and then sometimes it's left there being obsolete for a long time as i forget to/don't want to delete it completely. 
also i have many lines of this type:
-- print(some debug info) 
which i uncomment whenever i need that debug info and then comment back after i'm done with the tests, except if i forget. so it would be useful if i could search e.g. for all uncommented prints before a release to comment all of them.

i'm not sure if an example code will help a lot, but i can send you privately one. i have (ugly coded) files where half of the code is commented out, as i improved the code but was not yet prepared to delete completely the earlier variants. and now i'm lazy to go through them to see what is surely unneeded by now.

**Comment by pkulchenko** [comment]
I think this explanation is sufficient. I'll consider adding a toolbar button and the corresponding logic to skip matches in comments (and probably the markup as well).

**Comment by pkulchenko** [comment]
@keszegh, I started working on this functionality, but realized that it's going to be problematic for several reasons: to identify which match is in a comment, the document needs to be styled first, which requires loading its spec (based on the extension) and takes time to do. It may be still possible to do this for the search in the current document, but I'm not sure how worthwhile it is. Closing for now...

**Comment by CapsAdmin** [comment]
I've had a similar issue with my project and I try to separate  do `if mylib.debug then print(some debug info) end` though this has a runtime overhead.

**Comment by keszegh** [comment]
@pkulchenko , thanks for trying it though.
@CapsAdmin, not that it makes my request completely obsolete, but since my post i learned that at least e.g. in Gideros we can easily get rid of prints using macros like this: 
print @ |--|
see http://giderosmobile.com/forum/discussion/6621/lua-built-in-macro#Item_4 for more details about macros in lua.
