### ISSUE TITLE
documentation colon preceeding comment should be -- instead

### ISSUE THREAD

**Issue by gitshub** [pkulchenko/ZeroBraneStudio#613]
Perhaps lines like this in the documentation
    outputshell.fontname = "Courier New": set font name.
should be
    outputshell.fontname = "Courier New"-- set font name.
because people sometimes copy and paste them into configuration files

**Comment by pkulchenko** [comment]
@gitshub, this is an interesting suggestion; I agree that it may be better for copying and will check how it looks on the page.

**Comment by pkulchenko** [comment]
@gitshub, in my opinion, the colon looks better; it's possible to add `--` and hide it with something like the following, which will make ` -- ` invisible, but still included in the copied content, but it's difficult to add to the page and to maintain:

```html
`activateoutput = true`<span style="display:inline-block;width:0;color:white"> -- </span>: text...
```

Still thinking...

**Comment by pkulchenko** [comment]
@gitshub, I'll keep things the way they are for now. While `--` could be a bit more useful, multi-line config copying is rarely needed and the colon still looks better in my opinion.
