### ISSUE TITLE
non UTF-8 system

### ISSUE THREAD

**Issue by denisdemais** [pkulchenko/ZeroBraneStudio#615]
Hi. ZBS is a 'lua on the rocks' ide.

is possible set the ZBS to:
- force to open/save file encoded with ANSI + Unix EOL?

**Comment by pkulchenko** [comment]
Yes and no. The IDE is insensitive to EOL markers, but will report if the same file has "mixed" line encodings. You can open and edit the file with Unix encodings and edit it without issues and you can also specify the default EOL to be used (so you can set LF to be used on Windows for example) by setting `editor.defaulteol` value; see [editor preferences](https://studio.zerobrane.com/doc-editor-preferences) in the documentation.

ANSI encoding is a tricky one. Currently the IDE only supports UTF-8 encoding and there is no plan to change that, so any non-UTF-8 compliant text will need to be changed to comply for it to be editable. There are several tickets that describe what will need to be done to support non-UTF-8 valid encoding in the editor: #556, #543, and #260. Most of the work has already been done as part of #556 and the rest will be done in #260. I'm closing this one as a duplicate, but you can subscribe to those tickets to monitor and if there is any issue not covered by them, feel free to discuss in this ticket.

**Comment by pkulchenko** [comment]
Just to add more details on the EOL handling. If the file opened has Unix EOL (LF), then all the new lines in that file will use the same EOL marker (doesn't matter what system it's opened on); the same is true about CRLF EOL marker. So the IDE will use the same EOL marker as is already used in the file.

In those cases where there is ambiguity (mixed EOLs used in one file), the IDE will report this and will use the value set by `editor.defaulteol` or (if not set), then the "native" EOL for that system (LF on Linux/OSX and CRLF on Windows). You can see the EOL markers by running `ide:GetEditor():SetViewEOL(1)` in the Local Console.
