### ISSUE TITLE
Click margin to fold/unfold

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#616]
The margin include empty column part (not the explict fold flag).
Then it will more convenient to fold/unfold without exact click.
And support hotkey is much nice! Fold/Unfold current / all child, etc.

**Comment by pkulchenko** [comment]
@robertlzj, do you mean clicking on the line to fold/unfold? I can probably add this.

For the hotkey, do you mean using something like Shift-F12 to fold/unfold the current line? There is already F12 hotkey to fold/unfold everything.

**Comment by robertlzj** [comment]
Yes, I mean click on the vertical line of fold margin, which within fold head flag and end.
`F12` will toggle all the folder, but sometimes need to fold/unfold some of them, like current range.
If there is hotkey for this purpose (operate on special rang like folder contain caret), then mouse click is  simplify.

**Comment by pkulchenko** [comment]
I added `Shift-Click` on the margin to un/fold the current line/block. I didn't want to do simple click as I think I had that before and some users complained about missing the margin and folding inadvertently.

I also added `Shift-F12` to un/fold the current line/block (so `Shift` is used in both places, which should be easier to remember). You can change the shortcut if you want by assigning keymap to `ID.FOLDLINE`.
