### ISSUE TITLE
Tab order differ in subfield tabs when switch

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#617]
When there are more than one subfields (tab groups docked horizontally).
Here assume 2 subfield tab groups, Currently, the tab in newer one, will inherit its order ID, which should be new order according to its actual group.
So, when switch between tabs, like using Ctrl+PgUp/PgDn, the active tab order is muddledness, maybe, left - right - right -left - ..

**Comment by pkulchenko** [comment]
I'll take a look, but I think it's controlled by `wxAuiTabCtrl` in wxwidgets, so not much I can do about it.

**Comment by pkulchenko** [comment]
@robertlzj, this looks like a deficiency in wxwidgets logic as it navigates over tabs in some "internal" order, so when the tabs are re-arranged, they still keep their internal ids and the navigation happens in that order. It might be possible to improve it, but the public API doesn't provide access to `wxAuiTabCtrl` component that is needed for that, so it's not going to be easy/possible to improve with the current design.
