### ISSUE TITLE
Click error of coroutine in Output prompt not jump to the right line

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#620]
When debug in coroutine with "require('mobdebug').on()", click error in Output prompt will jump to coroutine entrance (coroutine.wrap), which the actual position is expected.
Output prompt shows like "x.lua:100 : x.lua:10: ..error message" where line 10 is the actual position (here is a upvalue function).

**Comment by pkulchenko** [comment]
@robertlzj, can you show the full output (including the stack trace and the error message)?

**Comment by robertlzj** [comment]
```
local function f()
		error''
	end
	local cf = coroutine.wrap(function()
			require('mobdebug').
			f()
		end)
	cf()
--[[
D:\Program Files\ZeroBraneStudio-master\bin\lua.exe: G:\Users\Administrator\Documents\Lua\test.lua:8: G:\Users\Administrator\Documents\Lua\test.lua:2: 
stack traceback:
	[C]: in function 'cf'
	G:\Users\Administrator\Documents\Lua\test.lua:8: in main chunk
	[C]: at 0x00402a57
]]
```

**Comment by pkulchenko** [comment]
@robertlzj, I pushed a change that should be able to handle this case; give it a try.
