### ISSUE TITLE
Step over (fold) line

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#621]
Now, step over just works for one operate (function call, assignment) per time.
I think step over jump to next line, or next unfold line is better.
Sometimes, there are plenty of related function calls in one line, like `a(b(c())) and d(..) ..`, so step over is a little verbose if just want to jump to the next line.

**Comment by pkulchenko** [comment]
@robertlzj, I understand that it may be convenient in some cases, but this is something that LuaJIT interpreter does and I think it makes sense, especially given that you may have different statements/expressions on one line. If you really want to just go to the next line, there is `Project | Run To Cursor` (`Ctrl-Shift-F10`), which is also available from the context menu in the editor.
