### ISSUE TITLE
how to do ?

### ISSUE THREAD

**Issue by denisdemais** [pkulchenko/ZeroBraneStudio#622]
Hi.
How i can add a button to invoke a custom shell (like bash, powershell or cmd) from current project/diretory.

i. e., call a ''git bash here''

**Comment by pkulchenko** [comment]
Here is the example from the documentation: https://studio.zerobrane.com/doc-plugin#example-adding-a-menu-item-and-a-toolbar-button-that-run-make

It's better to ask questions using the [maillist, IRC, or an email](https://studio.zerobrane.com/community), than a github ticket.
