### ISSUE TITLE
Project menu tree is corrupted

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#623]
I just wanted to test #583 but ran into another problem.
What i did
- Take a clean Win7 VM
- Fetch current zbs-master and extract to "C:\bin\ZeroBraneStudio-master"
- Start zbstudio.exe
Now I wantet to test the #583 issue, but I could not.
The menu entry for "Project/Command Line parameters..." shows the submenu for selecting the project directory
The menu entry for "Project/Project directory" showes the submenu for selecting the interpreter. :cry: 

![wrong command line parameters](https://cloud.githubusercontent.com/assets/8567887/14231238/ce494dfc-f97b-11e5-82f1-5a661baa1fa7.png)
![wrong project directory menu](https://cloud.githubusercontent.com/assets/8567887/14231240/d2d06824-f97b-11e5-9e27-1ec5caf3b590.png)

**Comment by pkulchenko** [comment]
@jjvbsag, for some reason assigning icons to menu items caused them to be displayed incorrectly on Win7 and Win10 (but not on win8). I pushed a fix that completely changed that logic (b87fef58), which fixed it on Win10, so I'd expect it to be fixed on Win7 as well. Could you pull the changes and check again? Thanks.

**Comment by jjvbsag** [comment]
@pkulchenko Quick check on Win7: Menu is ok now.

I will see if I can verify #583 later in the evening...
Regards

**Comment by pkulchenko** [comment]
ok, thanks for checking. Closing...
