### ISSUE TITLE
elseif should be collapsible too

### ISSUE THREAD

**Issue by keszegh** [pkulchenko/ZeroBraneStudio#626]

**Comment by pkulchenko** [comment]
@keszegh, I don't think it's possible with the current lexer as it's handled in Scintilla as part of the C/C++ code, so not easily modifiable. I'm working on adding LPeg-base lexer, which uses Lua-based lexers, so there is going to be more flexibility in the future.

Having said that, I'm not sure if it's even possible with Scintilla folding mechanism, as you probably want to be able to fold `elseif` to the end (or to the next `elseif`), but still be able to fold the entire `if` when clicking on `if` fold. This requires those lines to have a weird level structure (as the folding is done based on table of levels returned by line), so it may not be flexible enough to support your use case.

**Comment by keszegh** [comment]
it should fold to the next elseif/end i guess. and yes, the whole if should be foldable too. but if it's more or less impossible, then of course it's not a crucial feature. thanks for explaining.
