### ISSUE TITLE
Add some instructions to the install script for linux

### ISSUE THREAD

**Issue by mark0978** [pkulchenko/ZeroBraneStudio#628]
May want to print these out at the end of the install script.

For ubuntu you might need:
sudo apt-get install libgtk2.0.0 wx-common xdg-utils 

For RHEL7 you might need:
sudo yum install xdg-utils compat-wxGTK3-gtk2 dejavu-lgc-sans-fonts

**Comment by pkulchenko** [comment]
@mark0978, did the IDE not run on RHEL without `compat-wxGTK3-gtk2`? Also, I don't think `wx-common` is needed as it seems to be using wxwidgets 2.8.x version instead of 2.9.5 bundled with the IDE (or 3.1.x soon).

Did it not run without `xdg-utils`? I did run the install scripts on several "clean" installations and didn't see any errors from them. Are you trying to address any specific issues?

**Comment by mark0978** [comment]
Could be the VMs I have access to are "server" instead of desktop.  On
ubuntu, it had to have xdg-utils, I think on RHEL it might not have been
needed.

Trying to make it easier for newcomers to just pick it up and run with it.

I'll re-run mytests later today or tomorrow, but I do think I had to add
those packages to make it run.

I do know the font was required, without it, all the characters were square
boxes.

**Comment by ghost66** [comment]
Mr. Pkulchenko,

I have this error when I try to run ZeroBraneStudioEduPack-1.30-linux.sh in Ubuntu 12.04.
"ZeroBraneStudioEduPack-1.30-linux.sh: 1: eval: ./install.sh: Permission denied"
Can You help me ?

**Comment by pkulchenko** [comment]
@ghost66, you need to use "sudo" to install in system folders. If you don't want to use sudo, you can download the archive from the repository and run the IDE from the current folder (it has a portable configuration that doesn't modify anything in the system).

**Comment by mark0978** [comment]
No @ghost66, the problem is the script isn't executable when you download it.  Two possibilities:

chmod +x ZeroBraneStudioEduPack-1.30-linux.sh
or
bash ZeroBraneStudioEduPack-1.30-linux.sh

You don't need sudo

**Comment by ghost66** [comment]
![tela](https://cloud.githubusercontent.com/assets/3221736/14480096/0133a91a-00fc-11e6-94d1-cbf9d0ea2519.png)

ok mark0978 but how you can see above, the error still occurring.
I followed what  pkulchenko  said and I can run the app now.
Thanks
