### ISSUE TITLE
Not able to step into Torch functions (nn.SpatialContrastiveNormalization) while doing remote Debugging

### ISSUE THREAD

**Issue by jaiabhayk** [pkulchenko/ZeroBraneStudio#629]
Please let me know how to REMOTE debug the torch packages such as "nn" etc, together with my custom application. I understand ZeroBraneStudio can map the application's (running in remote machine) source code files using name in the project directory in the ZeroBraneStudio (running in local machine). But what about the torch packages such as "nn" etc, how these are mapped ?

Detailed Steps to reproduce:-
===========================
1) Application is running on remote machine (REDHAT):- remote.com
2) Install ZeroBraneStudio on local machine (MacOSx):- local.com
3) Copy the code to run from:-
https://github.com/torch/tutorials/tree/master/2_supervised
4) Edit the file doall.lua inside the directory 2_supervised and put the very first line as require('mobdebug').start('local.com') (or ip address instead of local.com)
5) Copy the same code to both remote and local machines.
6) Start Zerobrane and Go to project and select the 2_supervised as project directory and start debug server
7) Put Breakpoint inside 1_data.lua at line 203, where it shows something like:-
normalization = nn.SpatialContrastiveNormalization(1, neighborhood, 1):float();
8)  Run the code on the remote machine:-
remote.com> th  doall.lua (cd to the directory 2_supervised copied in step 2)
9) The debuggin works fine as long as I am navigating insdie the files in the directory 2_supervised. But if I try to go inside the torch packages like  nn.SpatialContrastiveNormalization, it does not inside them. I have tried copying the entire nn direcotry insdie my current directiory (2_supervised) but it did not help.

**Comment by pkulchenko** [comment]
@jaiabhayk, did you try to open the Lua file from nn package that you want to step into?

Does any of the following suggestions apply: https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered? I'd be especially interested in the output from `debug.getinfo(1,"S").source` if you can put it in that `nn` file you want to step into.

**Comment by jaiabhayk** [comment]
Output of debug.getinfo(1,"S").source when i put that inside the SpatialContrastiveNormalization.lua file's init method:-
@/remotemachine/jaiabhay/torch/install/share/lua/5.1/nn/SpatialContrastiveNormalization.lua

**Comment by jaiabhayk** [comment]
Do you think I need to create exaclty same file structure on my local machine as well ?

**Comment by jaiabhayk** [comment]
Basically these files (nn package) are outside the scope of the project directory on my Remote machine (i.e, these are installed torch libraries on my remote machine)

**Comment by jaiabhayk** [comment]
FYI, I figured out a work around for that:-
Need to create exact file system as on the remote machine (and not the file system relative to the project directory). i.e, If I create the following local files system:-

/remotemachine/jaiabhay/torch/install/share/lua/5.1/nn/

instead of creating

<LocalProjectDirectory>//remotemachine/jaiabhay/torch/install/share/lua/5.1/nn/

It works fine.

**Comment by pkulchenko** [comment]
@jaiabhayk, right, I was going to suggest that. Basically, for all the files that are outside of the project directory, the path has to match on both machines.

**Comment by jaiabhayk** [comment]
Thanks for your help.

-Abhay
