### ISSUE TITLE
No XP style of controls by using wx.dll under Windows 7 and later

### ISSUE THREAD

**Issue by paserra** [pkulchenko/ZeroBraneStudio#631]
Zerobrane studio is an amazing IDE but lacks of the possibility of design GUI interfaces.
Because it is based on wxLua (but with the powerful luajit engine),  the wxFormBuilder may be used for this purpose.
I've tryed and it works very well... the only bad news is that the wxLua interface uses old style controls under Windows 7 when launched by lua.exe (luajit) engine. I've tried to write a custom lua.exe windows manifest file without success.
My question is: it could be possible to recompile lua.exe for showing wx controls in XP style without loosing the possibility to update the luajit engine by overwriting the lua51.dll with a new version?
Thank you.
Pier Andrea.

**Comment by pkulchenko** [comment]
@paserra, what manifest settings are we talking about? How did you try to apply them? You can run `mt` command to apply a manifest to an existing file if you want to test the result: `mt.exe -manifest "lua.exe.manifest" -outputresource:"lua.exe;#1"`.

**Comment by paserra** [comment]
Hi Paul,
try this code:
`----------------------------------------------------------------------------
-- Lua code generated with wxFormBuilder (version Jun 17 2015)
-- http://www.wxformbuilder.org/
----------------------------------------------------------------------------

-- Load the wxLua module, does nothing if running from wxLua, wxLuaFreeze, or wxLuaEdit
package.cpath = package.cpath..";./?.dll;./?.so;../lib/?.so;../lib/vc_dll/?.dll;../lib/bcc_dll/?.dll;../lib/mingw_dll/?.dll;"
require("wx")

UI = {}


-- create MyFrame1
UI.MyFrame1 = wx.wxFrame (wx.NULL, wx.wxID_ANY, "za", wx.wxDefaultPosition, wx.wxSize( 500,300 ), wx.wxDEFAULT_FRAME_STYLE+wx.wxTAB_TRAVERSAL )
	UI.MyFrame1:SetSizeHints( wx.wxDefaultSize, wx.wxDefaultSize )
	
	UI.gSizer1 = wx.wxGridSizer( 0, 5, 0, 0 )
	
	UI.m_button1 = wx.wxButton( UI.MyFrame1, wx.wxID_ANY, "MyButton", wx.wxDefaultPosition, wx.wxDefaultSize, 0 )
	UI.m_button1:SetToolTip( "sdsdsd sdsd sds" )
	
	UI.gSizer1:Add( UI.m_button1, 0, wx.wxALL, 5 )
	
	UI.m_button2 = wx.wxButton( UI.MyFrame1, wx.wxID_ANY, "MyButton", wx.wxDefaultPosition, wx.wxDefaultSize, 0 )
	UI.gSizer1:Add( UI.m_button2, 0, wx.wxALL, 5 )
	
	UI.m_textCtrl1 = wx.wxTextCtrl( UI.MyFrame1, wx.wxID_ANY, "kkk", wx.wxDefaultPosition, wx.wxDefaultSize, 0 )
	UI.gSizer1:Add( UI.m_textCtrl1, 0, wx.wxALL, 5 )
	
	UI.m_slider1 = wx.wxSlider( UI.MyFrame1, wx.wxID_ANY, 50, 0, 100, wx.wxDefaultPosition, wx.wxDefaultSize, wx.wxSL_HORIZONTAL )
	UI.gSizer1:Add( UI.m_slider1, 0, wx.wxALL, 5 )
	
	UI.m_gauge1 = wx.wxGauge( UI.MyFrame1, wx.wxID_ANY, 100, wx.wxDefaultPosition, wx.wxDefaultSize, wx.wxGA_HORIZONTAL )
	UI.m_gauge1:SetValue( 0 ) 
	UI.gSizer1:Add( UI.m_gauge1, 0, wx.wxALL, 5 )
	
	
	UI.MyFrame1:SetSizer( UI.gSizer1 )
	UI.MyFrame1:Layout()
	
	UI.MyFrame1:Centre( wx.wxBOTH )
	
	-- Connect Events
	
	UI.m_button1:Connect( wx.wxEVT_COMMAND_BUTTON_CLICKED, function(event)
	--implements pippo
	UI.m_textCtrl1.AppendText(UI.m_textCtrl1,"e")
	event:Skip()
end )

  UI.MyFrame1:Show()
  
wx.wxGetApp():MainLoop()
`
Under Windows the controls are represented in OLD STYLE.

If you add a manifest to the lua.exe the problem is solved but Zerobrane studio freezes.

I've tryed this by using resource Hacker software:

ResHacker.exe -addoverwrite lua.exe, lua.exe, lua.manifest,24,1,1033

**Comment by pkulchenko** [comment]
What's the content of `lua.manifest`?

**Comment by paserra** [comment]
This is the cntent of the manifest associated with the last version of luajit.exe (compiled with mingw32).

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="*"
    name="Lua"
    type="win32"
/>
<description>LuaJIT</description>
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="*"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
	<security>
		<requestedPrivileges>
			<requestedExecutionLevel level="asInvoker" uiAccess="false" />
		</requestedPrivileges>
	</security>
</trustInfo>
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
	<application>
		
		<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
		
		<supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
		
		<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
		
		<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
		
		<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
	</application>
</compatibility>
</assembly>
`

**Comment by paserra** [comment]
sorry for the bad format:
This is the link to download the exe/manifest files:
https://github.com/luapower/luajit/archive/2.1.0-beta2.zip

it works very weel without the zerobrane frontend

**Comment by pkulchenko** [comment]
@paserra, I looked through the manifest, but I'm a bit confused by what the problem is. When you add this manifest to `lua.exe`, it should have no impact on the IDE, as the IDE currently doesn't use `lua.exe` to launch; it uses `zbstudio.exe`, which loads the lua DLL and runs a wrapper that (effectively) executes `src/main.lua`. When you say that the IDE freezes, how exactly does this happen?

Also, you should be able to use an external manifest `lua.exe.manifest` (you don't need to embed it). Unfortunately the work that I'm doing for the wxwidgets upgrade (#260) also added embedded manifests for Lua executables in the `bin/` directory, which will have precedence over external manifests. You should still be able to use the `mt` tool to update the embedded manifest as I suggested earlier.

**Comment by pkulchenko** [comment]
@paserra, I think I've been able to reproduce what you are describing. The IDE doesn't freeze, but there is some strange "overlay" over it, which intercepts some of the clicks. You can still stop the application by using `Shift-F5`. I'm looking into this...

**Comment by pkulchenko** [comment]
@paserra, should be fixed now in the master branch. Either pull the new changes or just copy that line to your IDE instance. Let me know if this doesn't address the issue.

**Comment by paserra** [comment]
@pkulchenko now works like a charm.  Now it is possible to use wxFormBuilder with good visual results also under win32.
Thank you Paul!
Pier Andrea

**Comment by pkulchenko** [comment]
ok, good. Thank you for the update.
