### ISSUE TITLE
"Resource temporarily unavailable" when doing multiple files search replace on linux

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#633]
This has been a thing for a long time now and it happens on and off. Sometimes it helps restarting zerobrane. It's been happening on fedora, kubuntu 15 and 16, opensuse, laptop with kubuntu etc. If it matters I'm a KDE user and have been using the latest packages for that.

```
.....
.....
Searched for ':explode'. Found 33 instances on 33 lines in 19 files.

Review the changes and save this preview to apply them.
You can also make other changes; only lines with : will be updated.
Context lines (if any) are used as safety checks during the update.

/media/caps/ssd_840_120gb/goluwa/src/lua/examples/shaderbuilder2.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/examples/code_statistics.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/examples/2d/lua_editor.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/autorun/google.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/autorun/console_commands.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/language.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/input.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/structs.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/profiler.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/network/network.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/gmod/gmod.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/audio/chatsounds.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/graphics/surface/fonts/love.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/graphics/surface/fonts/freetype.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/graphics/render/mesh_builder.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/graphics/render/global_shader_code.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/extensions/debug.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/utilities/utility.lua: Resource temporarily unavailable
/media/caps/ssd_840_120gb/goluwa/src/lua/libraries/lovemu/lovemu.lua: Resource temporarily unavailable

Updated 0 lines in 0 files.
```

**Comment by pkulchenko** [comment]
@CapsAdmin, I noticed the same thing, but I'm at a loss as to why this would be happening or how to avoid this. It looks like it's been happening for a long time, but the error/warning message was added relatively recently, so this is why it may look like a new thing.

I haven't seen this to happen on Windows or OSX and it looks like it only appears if a (relatively large) number of files is being replaced. The first replacements may go without issues, but the subsequent once may generate the error you see. I tried adding a delay, but it doesn't eliminate the issue. Restarting helps, but then it may happen on other files.

When I saw this, I checked what other processes may be using the file and it's just the IDE. It does look like a wxwidgets issue, but I see other users reporting this with other editors in a similar situation ([one example](http://stackoverflow.com/questions/26245853/error-on-file-save-opening-output-file-resource-temporarily-unavailable)), so it may still be a file system issue. Even if it's a wxwidgets issue, I can't imagine what kind of issue is that, as it's the same process that opened the file, so why would the system complain that the file is unavailable?

**Comment by pkulchenko** [comment]
@CapsAdmin, could you try the following patch:

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index 90eae2d..ac8eb8f 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -1247,7 +1247,12 @@ local package = ide:AddPackage('core.findreplace', {
             end
             if lines > 0 and not mismatch then -- save the file
               local ok
-              ok, err = FileWrite(fname, oveditor:GetTextDyn())
+              for attempts = 1, 3 do
+                ok, err = FileWrite(fname, oveditor:GetTextDyn())
+                if ok or err ~= "Resource temporarily unavailable" then break end
+                ide:Print("Couldn't save file "..fname..": "..err)
+                wx.wxMilliSleep(500) -- wait for 0.5s before another attempt
+              end
               if ok then files = files + 1 end
             end
           end
```

I'll remove the message in the final version, but I wanted to keep it there just to see if there is an issue and the patch helped to work through it. Thanks.

**Comment by pkulchenko** [comment]
@CapsAdmin, did adding a retry help?

**Comment by CapsAdmin** [comment]
I haven't had the issue lately but I remember trying multiple times manually which didn't work.

**Comment by pkulchenko** [comment]
@CapsAdmin, yes I remember re-trying it manually and couldn't get consistent results either.

Do you mean that you continue using search/replace and haven't seen this issue or that you haven't used it recently? I'd very much like to do something to address this ticket, but I'm out of the options at the moment, so if the patch doesn't help, I think we can close it.

**Comment by pkulchenko** [comment]
@CapsAdmin, I pushed a small change that may help with this issue. Closing, but please re-open if you have any new instances of this happening again.
