### ISSUE TITLE
Markdown header does not work in -- Comments

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#634]
Assume the following code
```lua
--[[
#header
**bold**
_italic_
`code`
--]]

--------------------------------------------------
-- #header
-- **bold**
-- _italic_
-- `code`
--------------------------------------------------
```
you'll get the following formatting

![zerobrane-markdown](https://cloud.githubusercontent.com/assets/8567887/14855026/5cbbbd58-0c92-11e6-8b6e-5b7c7639f72f.png)

Thus, all markdown is working in `--[[...--]]`  and `-- ...` style comments, only header does not work in the second one

(tested with zerobrane 1.30 and trunk)

**Comment by pkulchenko** [comment]
This is by design; the idea is that any markdown fragment will be shown the same way in a regular markdownn editor/processor. `-- # header` would not be.
