### ISSUE TITLE
Tooltip is not shown in case with space

### ISSUE THREAD

**Issue by DenisKolodin** [pkulchenko/ZeroBraneStudio#635]
Autocomplete shows when I stick together function's name and left paren:
`myfunc(`

But autocomplete never shows when I type:
`myfunc (`
or 
`myfunc {`
or
`myfunc "`

These are valid syntax to call functions, but I have to press Ctrl+T.

**Comment by pkulchenko** [comment]
@DenisKolodin, it's not auto-complete; you probably mean the tooltip not being shown. I'll take a look.

**Comment by pkulchenko** [comment]
@DenisKolodin, I added handling of the spaces, but `{` and `"` are not going to be supported in this case as it's too Lua-specific and the tooltip can still be shown manually.

**Comment by DenisKolodin** [comment]
@pkulchenko Thank you! The best IDE I've ever used!

**Comment by pkulchenko** [comment]
Good to hear! ;)
