### ISSUE TITLE
The resize margin is too small by default (bordersize = 2)

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#637]
On KDE it's 4 pixels and on windows it's 8 pixels. Perhaps it should default to the OS's default size if there's any?

2 pixels okay if you're using a mouse but it's near impossible with a track pad

**Comment by pkulchenko** [comment]
@CapsAdmin, yes, it's possible to keep the default, but I'm not sure I want to do it on all platforms as I still prefer the smaller value at least on Windows. I'll test on OSX/Linux and see if I can keep the platform default.

You can try the following patch to see if it makes the things more convenient:

```diff
diff --git a/src/main.lua b/src/main.lua
index badee27..ad54dcd 100644
--- a/src/main.lua
+++ b/src/main.lua
@@ -174,7 +174,7 @@ ide = {
     symbolindexinactivity = 2, -- seconds
     filehistorylength = 20,
     projecthistorylength = 20,
-    bordersize = 2,
+    bordersize = iswindows and 2 or nil,
     savebak = false,
     singleinstance = false,
     singleinstanceport = 0xe493,
```

**Comment by pkulchenko** [comment]
@CapsAdmin, the defaults look a bit ugly on OSX (as it's really wide, I think it may be 8 or something close), so I'm thinking about simply setting the default value to 4.

Also, you can change it in the config to make it work better for you. Or are you concerned that it may be inconvenient for others by default?

**Comment by CapsAdmin** [comment]
I've changed it to 4 myself. It's more about the default value for others.

**Comment by pkulchenko** [comment]
ok, I'll probably increase it to 3, but 4 still looks a bit too large by default. When 3 is still too small, the usets can update `bordersize` as you did.
