### ISSUE TITLE
Another Intendation issue

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#639]
Ok, currently im writing some lua cgi scripts and have another indentation problem. Given the following code
```lua
if x then
	print("A")
	print([[var onerror=function(x){
	log(x);
}]])
	print("B")
end
```
After "Correct indentation" this changes to
```lua
if x then
	print("A")
	print([[var onerror=function(x){
	log(x);
}]])
print("B")
end
```
so `print("B")` is on wrong indentation level now. This is ugly on long code, because all the rest indentation is one level to less.

**Comment by pkulchenko** [comment]
I'll see if this case can be handled automatically, but long comments are difficult to deal with (as the indentation code doesn't do full syntax analysis). The workaround is to reformat like this:

```lua
if x then
  print("A")
  print([[var onerror=function(x){
  log(x);
}
  ]])
  print("B")
end
```

**Comment by jjvbsag** [comment]
Thanks for the workaround. Maybe some day I will take a look at the parser and try to contribute a "syntax aware" indentation :cake:

**Comment by pkulchenko** [comment]
@jjvbsag, should be fixed in the master branch. Thank you for the report.
