### ISSUE TITLE
"Updated path normalization" breaks loading packages via user

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#640]
cb8b9a63498cc7fa7a2f0a5ec3ceea2252fa9d88 breaks loading packages via user.lua as diskussed in #555. Before the commit a script like
```lua
package"SVN" -- located in ~/.zbstudio/packages/SVN/svn.lua
package "packages/Device/Download.lua" -- located in <currentproject>/.zbstudio/packages
```
work fine. When updating the commit, I get
```
Can't find 'SVN' to load package from.
Can't find 'packages/Device/Download.lua' to load package from.
```

**Comment by pkulchenko** [comment]
@jjvbsag, are you sure you referenced the correct commit? That commit has nothing to do with "updated path normalization" and can't break package loading. Or do you mean that it may be one of the earlier commits before that one?

**Comment by jjvbsag** [comment]
@pkulchenko No, I did not. Sorry, but due firewall restriction (and my own matter of habit, I admin) I do only update via svn, not git.This makes it difficult for me to find the right references.
The commit message was
`Updated path normalization to keep leading up-directory references in relative paths.`
Should be commit cb8b9a63498cc7fa7a2f0a5ec3ceea2252fa9d88

**Comment by pkulchenko** [comment]
ok; that makes sense. This was the commit to avoid dropping leading up-dir references (like `../foo` turning into `foo`). I'll check why the package loading was affected.

**Comment by pkulchenko** [comment]
@jjvbsag, can you replace `local rel, rest = p:match("(%.[/\\.]*[/\\])(.*)")` with `local rel, rest = p:match("^(%.[/\\.]*[/\\])(.*)")` in `src/util.lua` to see if this fixes the issue. I think the anchoring in the template may be missing.

**Comment by jjvbsag** [comment]
@pkulchenko I'm at home now, I will try early tomorrow (about 08:00CEST) in the office.

**Comment by jjvbsag** [comment]
Just to say that:
> (like `../foo` turning into `foo`).

This is NOT the same! think of:
```
>ls .
foo
>ls ..
foo
>ls foo
foo/file-in-one-foo-dir
>ls ../foo
../foo/file-in-another-foo-dir
```

If you'd say

> `somewhere/../foo` turning into `foo`, 

or 

> `somewhere/./foo` turning into `somewhere/foo`, 

then I'd agreee

**Comment by pkulchenko** [comment]
@jjvbsag, this should be fixed now. I suspect that `package "SVN"` never worked (or if it worked, it was only by accident) as the main location was never checked from project configs (as it's assumed that packages from that location are already loaded when the IDE is started).

**Comment by jjvbsag** [comment]
:+1: Confirmed, after a complete update it's working again. Thanks

> I suspect that package "SVN" never worked

It works, sorry if I was unclear.
`package"SVN"` is in `~/.zbstudio/user.lua` and
`package "packages/Device/Download.lua"` is in `<currentproject>/.zbstudio/user.lua`

Regards Jørgen
