### ISSUE TITLE
Overwrite Shortcut Ctrl+R on Windows

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#642]
Placing `keymap[ID.RUN] = "Ctrl-R"`  in `cfg/user.lua` works as expected in Linux and OS X but not in Windows.

In Windows, I need to comment out the line in `src/editor/keymap.lua` that assigns `Ctrl-R` for the re-assignment to work.

Version: 1.30

**Comment by pkulchenko** [comment]
@qubodup, I think it's only a coincidence that it works on Linux/OSX, but not on Windows, as the order in which the IDs are assigned depends on how `pairs` is executed and it may be system-dependent (and vary between runs).

To make it work reliably, you need to clear the current setting for `Ctrl-R` and assign it to the new ID:

```
keymap[ID.RUN] = "Ctrl-R"
keymap[ID.REPLACE] = nil
```

If you want to use more OSX-like shortcuts, you may want to add `include "xcode-keys.lua"` to your config file as it will load mappings based on XCode shortcuts.

**Comment by qubodup** [comment]
Thanks!

Is it however safe to assume that `keymap[ID.REPLACE] = nil` in `cfg/user.lua` will be executed after `keymap[ID.REPLACE] = Ctrl+R` in `src/editor/keymap.lua` and will overwrite the original configuration? Or is this also depending on unknown factors?

**Comment by pkulchenko** [comment]
Yes; all configuration changes are executed after the initial default assignments.
