### ISSUE TITLE
Option to disable opening of output on "Run" action

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#643]
This is a feature/enhancement request. Purpose: minimize UI distractions.

Allow an option to disable the automatic opening of the output bar when the RUN shortcut is used to  keep the text area as it is and not pop-in a new UI element.

**Comment by pkulchenko** [comment]
Try adding `activateoutput = false`; see [general preferences](https://studio.zerobrane.com/doc-general-preferences#general) for more.

**Comment by qubodup** [comment]
Thanks!
