### ISSUE TITLE
Run a program without error-checking

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#645]
In https://studio.zerobrane.com/doc-getting-started#running-programs it says:

> To execute a program you can select Project | Run menu command. This will run your program in a separate process using the interpreter you selected to run it; by default this is the Lua interpreter, which executes your code in LuaJIT. The Output window will show the output of the program (if any) and some messages from the IDE that detail what script is being executed and from what directory.

I have LÖVE selected and try to run the following code:

```
x
```

This code is obviously broken. Instead of getting a love2d bluescreen however, I get a message in the output window:

```
Compilation error on line 1:
.../main.lua:1: '=' expected near '<eof>'
```

I was hoping for the user to get the same experience as if they were running their source code in any other unfiltered way with love2d.

Is the result expected? Or is it because how the love2d interpreter was written (I don't understand the code that seems to be responsible for running the code in it).

Interestingly enough, when running as a scratchpad, I can run broken code to see love's bluescreen.

If it's intended behavior: is it possible to simply turn it off via config file? If not, I'll just use scratchpad or adapt to using the output window instead of love's bluescreen.

The use case is using zbstudio in beginner (game) programming workshops for writing your first game using love2d. These workshops come with a software package that includes love, all what's needed to create an Android .apk, and a text editor (basically a future version of [LoveToAndroid](https://love2d.org/forums/viewtopic.php?t=80513) )

**Comment by pkulchenko** [comment]
hm, it's a bit unusual, but there is a way to enable what you want; try adding the following to the config:

```lua
ide.interpreters.love2d.skipcompile=true
```

`skipcompile` turns off the compilation check before running the script. You can still execute the check with `F7`/`Compile`.
