### ISSUE TITLE
Unclear possible values for some configuration options

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#647]
Some options on https://studio.zerobrane.com/doc-general-preferences have `nil` as default and no other example, for example:

>interpreter = nil: set the default interpreter used for new projects (1.11+).

I wanted to make LÖVE the default and found out after trial and error that I had to write "love2d" (with quotes) as a value. However I am not sure whether this is the file name without '.lua' or if that string refers to the variable love2d definied around the top of the `love2d.lua` file.

Perhaps you could clarify in the description?

Actually, this might have been the only case where it's not clear. It's easy to guess that you need a boolean for

>showmemoryusage = nil: display memory usage stats in the Status bar (1.11+).

**Comment by pkulchenko** [comment]
Both have been clarified; thanks!
