### ISSUE TITLE
Add preference to toggle watch and stack windows to auto-open when debugging is started

### ISSUE THREAD

**Issue by georgerbr** [pkulchenko/ZeroBraneStudio#650]
In much the same way that they are auto-hidden after debugging is finished.

I read through the documentation but couldn't find whether such a preference already exists.

**Comment by pkulchenko** [comment]
This should happen automatically, without any preferences: if you open watch or stack windows after you start debugging, then they will be auto-closed when the debugging is done and auto-opened when you start the debugging again. This state is *not* saved between the launches, so next time you start the debugging, simply open stack/watch windows you need and they will be auto-closed/-opened during the same session.

**Comment by georgerbr** [comment]
Thanks for answering in such short notice!
What I would like the IDE to do is to persist this between launches, i.e. not have to manually open the stack/watch windows after I start debugging.

**Comment by pkulchenko** [comment]
@georgerbr, you can try adding the following snippet to the config file (it's actually a plugin, but can be registered from the config):

```lua
package {
  onAppLoad = function(self)
    local debugger = ide:GetDebugger()
    for panel, val in pairs(self:GetSettings()) do
      if debugger.toggleview[panel] ~= nil then debugger.toggleview[panel] = val end
    end
  end,
  onAppClose = function(self)
    self:SetSettings(ide:GetDebugger().toggleview)
  end,
}
```

You'll need to use the latest master or wait for the next release. It's using undocumented debugger fields, so it's not guaranteed to work in the future, but for now should have the desired effect.

**Comment by georgerbr** [comment]
Works great, thanks!

**Comment by pkulchenko** [comment]
@georgerbr, good; thank you for the update. Just need to mention that the settings are saved based on the default name of the package, so if you add some other package before it in the config, you'll need to re-save the settings (as the default name includes the position to keep it unique).
