### ISSUE TITLE
Generate local variable from global library variable used

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#652]
Like, `local pairs, iparis = pairs, iparis`.
Could used in module, or optimize global variable to local/upvalue in general.
Act on current file, or current active/selection function/do scope.

**Comment by pkulchenko** [comment]
Not sure about this. There may be enough information in the token list generated by the parser to find global variables, but tracking of start/end positions for all the blocks is not being done (although there are `Scope` and `EndScope` ops in the token list). There is somewhat similar logic in the `outline.lua`, but it only tracks start/end positions at the function level (you may check `outlineRefresh` functions) and it uses internal structures that I'd rather not expose as they are subject to change.

You can definitely give making it a plugin a shot, but I wont be working on this any time soon as there are other items that may have bigger impact.
