### ISSUE TITLE
Select scope

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#653]
Select function scope/block (from `(local) function` to `end`) by double click function name in outline, or marge.
Also, `do` / `if` / `for` .. `end` if possible.
Then it would be easier to move, indent, search in selection, etc.

**Comment by pkulchenko** [comment]
It's a bit problematic to do it by itself, but it may be possible to combine with folding; for example, Shift-Click to fold (on the `[+]` or `[-]`) would instead select the block. I realize that it may be the most convenient, but it's probably the best I can do.

**Comment by pkulchenko** [comment]
@robertlzj, I enabled selection of the current block by using `Ctrl+click` in the fold margin. Give it a try.
