### ISSUE TITLE
ZBS doesn't show errors in gideros

### ISSUE THREAD

**Issue by Papirosnik** [pkulchenko/ZeroBraneStudio#655]
Used vesions:
ZBS - 1.30
mobdebug - 0.628 (also tried 0.6371)
Gideros - 2016.04

I put` a = a / 0` at the first line in my code and GiderosStudio shows:
_attempt to perform arithmetic on global 'a' (a nil value)_

ZBS in this case shows nothing, gideros player just silently dies and I see in the output windown only:
_Debugging session completed (traced 0 instructions)._

How to catch errors in ZBS with Gideros?

**Comment by pkulchenko** [comment]
You may need to try the version from the master branch as there was a change to add the support for showing errors (721c8fa6), but it was introduces after 1.30 was released. This will be included in the next release.

As an alternative, you can try copying `interpreters/gideros.lua` from the master branch to your installation.

**Comment by Papirosnik** [comment]
Сopying interpreters/gideros.lua fixes this trouble.
But there is a little inconvenience. An error message is still invisible until you close the gideros player window. Let me explain this in few little steps:
1) An error has occured.
2) Error message is still invisible. The only way to know that something goes wrong is empty white backround in gideros player window (btw, I use zbs on win-7 64 bit).
3) Close that crashed gideros player window.
4) Eventually error messages appear in the output windows.

It would be nice to see errors immediatly when an error occurs.
Anyway thanks for the help.

**Comment by pkulchenko** [comment]
I see, but there is not much that can be done about it as it's how it's reported by the Gideros Player.
