### ISSUE TITLE
Whitespaces bg color on selection

### ISSUE THREAD

**Issue by Papirosnik** [pkulchenko/ZeroBraneStudio#657]
I used to use visible whitespaces in code editors.
Zerobrane allows this too (via editor.whitespace = true in user.lua),
Also I can set color for them (e.g. whitespace = {fg = H'BBBBBB'} in tommorow.lua)
But can't find the way to set background color for whitespace chars in selected lines.
In this case whitespace chars don't change their color to the color of selection and selected block looks a bit ugly (with many gaps and indents). In the current line howewer, they change their background color.

I see '_sel_' attribute [here](https://studio.zerobrane.com/doc-styles-color-schemes). 
But it seems can be applied only to folded out text (sel: color of the selected block (only applies to folds?)
It would be nice to give us an ability to change bg color of whitespace chars for selected block too.
Either such feature is already implemented and I just missed it?

**Comment by pkulchenko** [comment]
> In this case whitespace chars don't change their color to the color of selection and selected block looks a bit ugly (with many gaps and indents). In the current line howewer, they change their background color.

@Papirosnik, this doesn't happen to me. In my case the background over whitespaces is the same as over the rest of the selection (with whitespaces having small colored dots). What's the version of the IDE are you using and on what platform? Can you post a screenshot of the gaps you are describing?

**Comment by pkulchenko** [comment]
`sel` is indeed is only currently for the folds. It's the color of the current block shown as the change in the fold line color.

**Comment by Papirosnik** [comment]
![ss2](https://cloud.githubusercontent.com/assets/1651549/16053665/773d0780-3272-11e6-8590-c716a3a841bc.PNG)

it's happening on both my pc: win7 and win10 64bit, zbs 1.3.0, modofied user.lua and tomorrow.lua see in attached archive...
[go.zip](https://github.com/pkulchenko/ZeroBraneStudio/files/314607/go.zip)

**Comment by pkulchenko** [comment]
@Papirosnik, this should be fixed now. This seems to be cause by setting background on whitespace characters, so I removed that setting. You can still set it if needed, but it's no longer enforced in tomorrow.lua.

BTW, you don't need to modify tomorrow.lua to set your own colors. You can set them after selecting a style; for example, `styles.whitespace = {fg = {255, 0, 0}}` will set whitespaces to red.
