### ISSUE TITLE
Add history and selection for command line parameters

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#665]

**Comment by Fuzzlix** [comment]
I like it! Thanks a lot :)

**Comment by pkulchenko** [comment]
@Fuzzlix, sounds good; thanks for the idea.

**Comment by Fuzzlix** [comment]
One notice: After entering a empty commandline, the popup menu in the status line does not show up.

**Comment by pkulchenko** [comment]
@Fuzzlix, this is by design; when there is no command line parameter specified, the popup behaves as it used to (it only switches the interpreter). When the command line parameter is specified, it allows you to change it by selecting from the list of previous values or to set a new value.

I think it's the least confusing option, otherwise clicking on empty space to the right of the interpreter label would trigger a command line menu. I realize that it doesn't allow to set a new value when the current one is empty (at least not using the menu), but you can still assign a shortcut to the dialog if you need to do it frequently.

**Comment by Fuzzlix** [comment]
Thats is ok for me. Thank you :)
