### ISSUE TITLE
Cannot handle lua files as registered editor (OSX)

### ISSUE THREAD

**Issue by kgignatyev** [pkulchenko/ZeroBraneStudio#666]
When I try to open some.lua file on OSX from Finder as 'open With' then ZeroBrane is grayed out because it does not declare that it can handle lua files. When I instruct OSX to show me all the applications I can select ZB but when it is opened it does not open file I selected.

**Comment by pkulchenko** [comment]
I've added several changes to the manifest that should address this (in the wxwidgets31x-upgrade branch); the commit is linked in #248 (don't want to link it directly as it's likely to change after rebase).

You can check out the upgrade branch and give it a try. That commit should enable both dragging files to the dock and using "Open With" functionality. I think the reason that "Open With" from Finder doesn't work is that the app doesn't handle the OpenFiles event that OSX sends (but the upgrade branch does this).

**Comment by kgignatyev** [comment]
Where are build instructions for OSX?

**Comment by pkulchenko** [comment]
You actually don't need to build anything as the required binaries are all included. You only need to (1) clone the repository, (2) run `git checkout wxwidgets31x-upgrade`, and (3) run `./zbstudio.sh`. This will run the IDE from the cloned repository and will even use your config, so it should all work the same way (plus several improvements in the upgrade branch).

(The build scripts/instructions are in the `build/` folder in the repo. There is `build-<platform>.sh` script for each supported platform.)

**Comment by kgignatyev** [comment]
build/build-macosx.sh 
Usage: build/build-macosx.sh LIBRARY...
does not build IDE

running from ./zbstudio.sh did not help Finder to open file in it ZB and unlikely help to launch it when it is not running

**Comment by pkulchenko** [comment]
You'd need to run `cd build; ./build-macosx.sh wxwidgets lua wxlua` to build wxlua library that the IDE depends on. There is no separate "build the IDE" step as it simply runs the Lua interpreter using the wxlua library (as the IDE itself is in Lua).

I don't have my Macbook to try it on, but as far as I remember, running ./zbstudio.sh would process the app manifest, which will allow Finder to recognize the app as registered for several extensions (it accepts .lua, but reports as supporting other extensions as well).

**Comment by pkulchenko** [comment]
Closing as this should be fixed by #260.
