### ISSUE TITLE
new preference for filetree window (hide/show files in project view)

### ISSUE THREAD

**Issue by gmax79** [pkulchenko/ZeroBraneStudio#668]
please add preference for filetree window -> filter function to hide/show files and directories in project view, like this:

filetree.filter = function(path, type)
  if path=='Debug' and type=='Dir' then return false end -- hide Debug dir
  return true
end

It is very necessary for large projects. Thanks.

**Comment by pkulchenko** [comment]
This is what [exclusion list](https://studio.zerobrane.com/doc-general-preferences#file-exclusion-lists) is for: try adding `table.insert(excludelist, "Debug/")` to your config file.
