### ISSUE TITLE
Run-time error in custom RPM package using wxwidgets 2.8.12

### ISSUE THREAD

**Issue by Mailaender** [pkulchenko/ZeroBraneStudio#669]
I created an RPM package for @openSUSE https://build.opensuse.org/package/show/home:Mailaender:branches:devel:languages:lua/zerobranestudio which sadly doesn't start and I have no idea why:

```
lua5.1: src/editor/package.lua:607: attempt to compare nil with number
stack traceback:
	src/editor/package.lua:607: in function 'AddIndicator'
	src/editor/style.lua:363: in function 'StylesApplyToEditor'
	src/editor/output.lua:34: in main chunk
	[C]: in function 'dofile'
	src/main.lua:618: in main chunk
	[C]: ?
```

**Comment by pkulchenko** [comment]
@Mailaender, what version of wxlua, wxwidgets and ZeroBrane Studio are you using? It's possible that either `wxstc.wxSTC_INDIC_CONTAINER` or `wxstc.wxSTC_INDIC_MAX` is not defined in your wxlua version, which would cause this error (I'm not sure exactly which one as the line number points to a different location in my code and it's likely that both are not defined).

In the version of wxlua I'm using (2.8.12.3) I see both of them defined in bindings/wxwidgets/wxstc_stc.i (assuming you are compiling with wxwidgets 2.9.5+):

```
#if %wxchkver_2_9_5
#define wxSTC_INDIC_STRAIGHTBOX
#define wxSTC_INDIC_DASH
#define wxSTC_INDIC_DOTS
#define wxSTC_INDIC_SQUIGGLELOW
#define wxSTC_INDIC_DOTBOX
#define wxSTC_INDIC_MAX
#define wxSTC_INDIC_CONTAINER
#endif //%wxchkver_2_9_5
```

**Comment by Mailaender** [comment]
I compiled wxLua 2.8.12.3.r252 from SVN compiled with wxWidgets 2.8.12 so shall I downgrade wxLua to the released 2.8.12.3 snapshot or upgrade wxWidgets to 3.0.2?

**Comment by pkulchenko** [comment]
You can use the same version of wxlua you used (2.8.12.3), but you'd need to use wxwidgets 2.9.5+. I used to maintain 2.8.x compatibility, but dropped it some time ago as I no longer even have binaries to test it on and the results vary between platforms as different minor versions of 2.8.x are being used.

If it comes down to just those two settings, I can probably add them to the IDE itself, but I suspect it's more than that.

Also wxLua versioning is a bit confusing as wxlua 2.8.12 supports wxwidgets 2.8, 2.9, 3.0, and 3.1.

**Comment by pkulchenko** [comment]
@Mailaender, also see earlier discussion on 2.8 compatibility in #128.

**Comment by Mailaender** [comment]
This runs fine with wxWidgets 3.0.2 so I mark this as a problem on my end.

When looking at the https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zerobrane-studio I also found out that this requires a make step which I skipped (as Alt Linux doesn't build anything).

It currently fails due to
```
[   54s] CMake Error at CMakeLists.txt:35 (message):
[   54s]   Lua module "wx" is not found
[   54s] Call Stack (most recent call first):
[   54s]   CMakeLists.txt:105 (check_lua_module)
```

although `%{_libdir}/lua/5.2/wx.so` is packaged so I am stuck there.

**Comment by Mailaender** [comment]
Finally resolved that as: https://sourceforge.net/p/wxlua/bugs/36/ seems to be a wxlua problem.

**Comment by pkulchenko** [comment]
> although %{_libdir}/lua/5.2/wx.so is packaged so I am stuck there.

@Mailaender, I didn't realize you were trying to compile and run ZeroBrane Studio using Lua 5.2. I have never tested this configuration and not sure it's going to work as the wx library is assumed to be for lua 5.1, so it will be put by the build scripts in the location for lua 5.1 libraries. It *may* still work, but it's likely to be a coincidence.

Just to avoid any confusion related to lua versions: the IDE supports running/debugging applications for Lua 5.1, 5.2, and Lua 5.3, but the IDE itself runs on Lua 5.1 compatible interpreter (Lua or LuaJIT).

**Comment by Mailaender** [comment]
Thanks for the heads up. The description is a bit confusing there. I figured that out by trial and error. Arch Linux uses Lua 5.2 and they even include a patch into wxlua that makes it incompatible with Lua 5.1, but it was a matter of replacing `LUA_OK` with `0` to fix it.

As most of the dependencies were only available in 5.1 I also chose that for openSUSE. My final results:

* https://build.opensuse.org/request/show/412755
* https://build.opensuse.org/request/show/412756

**Comment by pkulchenko** [comment]
@Mailaender, I'm interested in that LUA_OK patch. Why was it incompatible with Lua 5.1?

**Comment by Mailaender** [comment]
`LUA_OK` was added in Lua 5.2 as it seems.

**Comment by pkulchenko** [comment]
indeed. 5.1 only has the comment: `/* thread status; 0 is OK */`

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/view_file/devel:languages:lua/wxlua/wxlstate.patch should be Lua 5.1 compatible.
