### ISSUE TITLE
feature request: being able to set (defeault) execution file to run instead of currently open file

### ISSUE THREAD

**Issue by kgignatyev** [pkulchenko/ZeroBraneStudio#674]
Use case: I have file that call module I am developing that does testing of functionality but my main focus is on the module file where I change things and want to run it to verify. It is inconvenient to switch to a different tab and run from there, would be nice to 'pin' a caller file as file to be executed/debugged on Fx to eliminate need to switch tabs

**Comment by pkulchenko** [comment]
Right; this is already available. Go to the file/project tree, right click on the file and select `Set as Start File`. This file will be used as the start file for those interpreters that recognize the setting. You can then set a different file or unset the file from the same menu. It's a per-project setting.

**Comment by kgignatyev** [comment]
Great! Thank you!
