### ISSUE TITLE
Project Interpreters Issue

### ISSUE THREAD

**Issue by tastyminerals** [pkulchenko/ZeroBraneStudio#675]
I have just cloned **ZeroBraneStudio** to use it in combination with **Torch** library and to my disappointment there is no option for **lua5.1** interpreter (Torch default) via "Project -> Lua Interpreter -> ".
Why there is no "Lua 5.1" when there is "Lua 5.2, Lua 5.3" and what is the purpose of having plain "Lua"?
Also, what is the purpose of having all three options when in `user.lua` you can set my own paths? Does UI selection override `user.lua` and with what? There is no Lua Interpreter option for **Torch** either so how do I set it?

Ok, I opened up `user.lua` and set the paths like this:
```
path.lua = [[/home/tastyminerals/torch/install/bin/luajit]]
path.lua51 = [[/usr/bin/lua5.1]]
--path.lua52 = [[/usr/bin/lua5.2]]
path.lua53 = [[/usr/bin/lua]]
path.torch = [[/home/tastyminerals/torch/install/bin/th]]
```

But when I select plain "Lua" via "Project -> Lua Interpreter -> Lua" and hit **F6** the output window shows that 
```
/home/tastyminerals/torch/install/bin/luajit: /home/tastyminerals/dev/sync-repo/lstm_grips_tutorial.lua:7: module 'rnn' not found:
	no field package.preload['rnn']
	no file '/usr/share/lua/5.3/rnn.lua'
	no file '/usr/share/lua/5.3/rnn/init.lua'
	no file '/usr/lib/lua/5.3/rnn.lua'
	no file '/usr/lib/lua/5.3/rnn/init.lua'
	no file './rnn.lua'
	no file './rnn/init.lua'
	no file './rnn.lua'
	no file './rnn/init.lua'
	no file './lua/rnn.lua'
	no file './lua/rnn/init.lua'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/lualibs/rnn/rnn.lua'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/lualibs/rnn.lua'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/lualibs/rnn/rnn/init.lua'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/lualibs/rnn/init.lua'
	no file '/usr/lib/lua/5.3/rnn.so'
	no file '/usr/lib/lua/5.3/loadall.so'
	no file './rnn.so'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/bin/linux/x64/librnn.so'
	no file '/home/tastyminerals/dev/ZeroBraneStudio/bin/linux/x64/clibs/rnn.so'
stack traceback:
	[C]: in function 'require'
	/home/tastyminerals/dev/sync-repo/lstm_grips_tutorial.lua:7: in main chunk
	[C]: at 0x562f331068e0
Program completed in 0.03 seconds (pid: 21168).
```

So, how does it work in ZeroBraneStudio? :)

**Comment by pkulchenko** [comment]
> Why there is no "Lua 5.1" when there is "Lua 5.2, Lua 5.3" and what is the purpose of having plain "Lua"?

Lua5.1 interpreter (actually LuaJIT) is used by default, so Lua is the interpreter used by default to minimize confusion for new users who don't care about a particular version.

> Also, what is the purpose of having all three options when in user.lua you can set my own paths? Does UI selection override user.lua and with what?

It is to allow the user to use specific executables when those interpreters are selected. For example, you may want to use the Lua 5.2 interpreter that is included with the IDE, but may want to use the executable from your file system for Lua 5.3.

> There is no Lua Interpreter option for Torch either so how do I set it?

You need to install the [Torch plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/torch7.lua); see the instructions here: http://notebook.kulchenko.com/zerobrane/torch-debugging-with-zerobrane-studio.
