### ISSUE TITLE
Please let me edit while executing!

### ISSUE THREAD

**Issue by Joymaker** [pkulchenko/ZeroBraneStudio#676]
It has always frustrated me that in this editor I can't edit program text while the program is running.  Why?  Because it would be really helpful to be able to tweak the graphics code for the next run WHILE THE SIMULATOR WINDOW IS VISIBLE!  No other IDE I have ever used in any context has ever had this restriction, and it seems really unnecessary.  Yes, debugging after editing could lead to line confusion; let me face that if I so choose.  I JUST WANTED TO EDIT COORDINATES!!!  Please make this an option.

**Comment by pkulchenko** [comment]
Your wish is my command: `debugger.allowediting = true` ([docs](https://studio.zerobrane.com/doc-general-preferences#debugger)).

The default is set to mostly minimize the confusion for novice users.
