### ISSUE TITLE
Process DPI awareness issues on Windows

### ISSUE THREAD

**Issue by sherief** [pkulchenko/ZeroBraneStudio#680]
On High-DPI displays on Windows 10, the process declares itself as System DPI Aware yet doesn't scale the toolbar icons appropriately. A simple solution would be to declare the process as DPI Unaware in which case Windows will scale the entire window appropriately, or a better solution would be to scale the toolbar icons appropriately on high DPI displays.

**Comment by pkulchenko** [comment]
@sherief, can you post a screenshot of how it looks in your case (along with some other details, like window size and zoom level)? I'm using a HighDPI display with Windows 8 and the toolbar icons look large enough to be easily clickable.

I can't really turn DPI awareness off as it negatively impacts the fonts and some other screen elements.

**Comment by sherief** [comment]
![capture](https://cloud.githubusercontent.com/assets/1711646/17288137/4c079bda-5788-11e6-81de-cc41e243c84b.PNG)

Attached. UI scaling at 175% on Windows 10. Is that sufficient info?

**Comment by pkulchenko** [comment]
I see; yes, it would be good to address this, but there are several pieces that are missing to fix this: (1) wxwidgets doesn't support @2x resolution files on Windows (similar to how it's done on OSX), so this code will need to be added to image loading when DPI changes are detected (see this [discussion on wx-users for details](https://groups.google.com/forum/#!topic/wx-users/wR0MFpEAVX4))  and (2) high-resolution images for the toolbar will need to be drawn and included in the package. This would be nice to have, as this would also allow using these images on OSX, but I don't plan to work on this given the current priorities, so I'll defer this.

**Comment by pkulchenko** [comment]
This should be addressed in the next release. See #999.

**Comment by sherief** [comment]
Thanks!

**Comment by pkulchenko** [comment]
@sherief, the beta version is available at https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190e; give it a try and let me know if you run into any issues with it.

**Comment by pkulchenko** [comment]
This has been implemented as part of the changes in #999 that have been merged.
