### ISSUE TITLE
Little problem with syntax highlighting (Gideros)

### ISSUE THREAD

**Issue by Papirosnik** [pkulchenko/ZeroBraneStudio#683]
See attached screenshot. 
Why color of the 'self' keyword is different when semicolon and dot signs are used after it?
What could the problem be and is there a way to fix this via local user settings?
![capture](https://cloud.githubusercontent.com/assets/1651549/17431141/22912358-5b01-11e6-8b92-17f2139379ae.JPG)

**Comment by pkulchenko** [comment]
@Papirosnik, I don't think this is supported by the Lua lexer in Scintilla (the editor component the IDE uses). I asked a [similar question recently](https://groups.google.com/forum/#!topic/scintilla-interest/OJrAJ2fnjdM) and the answer from the author was that it's set by the lexer; in this case, the lexer treats `:` as the delimiter, but not `.` (as you can select things like `io.open`, in which case the entire fragment gets selected).
