### ISSUE TITLE
Some issues with using the arrow keys to navigate the file tree under linux

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#686]
Note that windows here means using zerobrane on Linux under wine.

When you press any arrow key the entire file tree view being scrolled which becomes a little confusing. This does not happen in wxwidget's tree control demo on linux nor does it happen in zerobrane on windows.

If you select an entry in the file tree, press left and the entry is a folder it should collapse the folder. If the folder is already collapsed or the entry is a file it should jump to the entry's parent. On Linux however this does happen in wxwidget's tree control demo so I'm reporting the bug there as well.

If you press right on an already expanded folder it should jump to the first child of that folder. This does happen on Linux but if you keep pressing it'll go to the next child again. I don't know if this is expected behavior because it does not happen on windows. In wxwidget's tree control demo nothing happens.

**Comment by pkulchenko** [comment]
@CapsAdmin, are these new issues (after recent updates) or old issues that you just noticed? Does the same behavior happen in both the master and wxwidgets31x-upgrade branches?

I presume the scrolling only happens when the filetree is active (and not when the focus is on the editor tab or other panels), right?

**Comment by CapsAdmin** [comment]
I'm not sure but I think it's always been like that. The scrolling only happens when the tree is focused yes.

I'll try with 3.1 when I get home.

**Comment by CapsAdmin** [comment]
The new wxwidgets does not have the scrolling issue nor does the right arrow behavior happen. Sorry I should have tested with the latest version before writing this issue.

The other issues remain but I think that's on wxwidget.

**Comment by pkulchenko** [comment]
@CapsAdmin, thank you for checking with the upgrade branch; closing this one as it should be resolved by #260.

I presume by "other issues" you mean #636 (Slow resizing) and #633 (Resource unavailable when replacing)? Or is there something else?

**Comment by pkulchenko** [comment]
Agree; I like the Windows behavior better, but you are right as it's something coded in wxwidgets.

I'll see if I can change it with KEY_PRESS handler.

**Comment by pkulchenko** [comment]
@CapsAdmin, give the following patch a try (this is against the upgrade branch as it uses a method not available before the upgrade). There are several tree controls in the app, so they all need to behave the same way.

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index b5d729d..0840bd2 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -1134,7 +1134,7 @@ local function stringifyKeyIntoPrefix(name, num)
 end
 
 local function debuggerCreateStackWindow()
-  local stackCtrl = wx.wxTreeCtrl(ide.frame, wx.wxID_ANY,
+  local stackCtrl = ide:CreateTreeCtrl(ide.frame, wx.wxID_ANY,
     wx.wxDefaultPosition, wx.wxSize(width, height),
     wx.wxTR_LINES_AT_ROOT + wx.wxTR_HAS_BUTTONS + wx.wxTR_SINGLE
     + wx.wxTR_HIDE_ROOT + wx.wxNO_BORDER)
@@ -1220,7 +1220,7 @@ local function debuggerCreateStackWindow()
 end
 
 local function debuggerCreateWatchWindow()
-  local watchCtrl = wx.wxTreeCtrl(ide.frame, wx.wxID_ANY,
+  local watchCtrl = ide:CreateTreeCtrl(ide.frame, wx.wxID_ANY,
     wx.wxDefaultPosition, wx.wxSize(width, height),
     wx.wxTR_LINES_AT_ROOT + wx.wxTR_HAS_BUTTONS + wx.wxTR_SINGLE
     + wx.wxTR_HIDE_ROOT + wx.wxTR_EDIT_LABELS + wx.wxNO_BORDER)
diff --git a/src/editor/filetree.lua b/src/editor/filetree.lua
index 02ea252..f57b373 100644
--- a/src/editor/filetree.lua
+++ b/src/editor/filetree.lua
@@ -740,7 +740,7 @@ local function treeSetConnectorsAndIcons(tree)
 end
 
 -- project
-local projtree = wx.wxTreeCtrl(ide.frame, wx.wxID_ANY,
+local projtree = ide:CreateTreeCtrl(ide.frame, wx.wxID_ANY,
   wx.wxDefaultPosition, wx.wxDefaultSize,
   wx.wxTR_HAS_BUTTONS + wx.wxTR_SINGLE + wx.wxTR_LINES_AT_ROOT
   + wx.wxTR_EDIT_LABELS + wx.wxNO_BORDER)
diff --git a/src/editor/markers.lua b/src/editor/markers.lua
index 9334a8e..1b6f61f 100644
--- a/src/editor/markers.lua
+++ b/src/editor/markers.lua
@@ -116,7 +116,7 @@ end
 
 local function createMarkersWindow()
   local width, height = 360, 200
-  local ctrl = wx.wxTreeCtrl(ide.frame, wx.wxID_ANY,
+  local ctrl = ide:CreateTreeCtrl(ide.frame, wx.wxID_ANY,
     wx.wxDefaultPosition, wx.wxSize(width, height),
     wx.wxTR_LINES_AT_ROOT + wx.wxTR_HAS_BUTTONS + wx.wxTR_HIDE_ROOT + wx.wxNO_BORDER)
 
diff --git a/src/editor/outline.lua b/src/editor/outline.lua
index bbe3945..511be5a 100644
--- a/src/editor/outline.lua
+++ b/src/editor/outline.lua
@@ -261,7 +261,7 @@ end
 local function createOutlineWindow()
   local REFRESH, REINDEX = 1, 2
   local width, height = 360, 200
-  local ctrl = wx.wxTreeCtrl(ide.frame, wx.wxID_ANY,
+  local ctrl = ide:CreateTreeCtrl(ide.frame, wx.wxID_ANY,
     wx.wxDefaultPosition, wx.wxSize(width, height),
     wx.wxTR_LINES_AT_ROOT + wx.wxTR_HAS_BUTTONS
     + wx.wxTR_HIDE_ROOT + wx.wxNO_BORDER)
diff --git a/src/editor/package.lua b/src/editor/package.lua
index a15fd05..d7528ba 100644
--- a/src/editor/package.lua
+++ b/src/editor/package.lua
@@ -472,6 +472,26 @@ function ide:CreateStyledTextCtrl(...)
   return editor
 end
 
+function ide:CreateTreeCtrl(...)
+  local ctrl = wx.wxTreeCtrl(...)
+  if not ctrl then return end
+
+  -- LeftArrow on Linux doesn't collapse expanded nodes as it does on Windows/OSX; do it manually
+  if ide.osname == "Unix" and ide:IsValidProperty(ctrl, "GetFocusedItem") then
+    ctrl:Connect(wx.wxEVT_KEY_DOWN, function (event)
+        local keycode = event:GetKeyCode()
+        local mod = event:GetModifiers()
+        local item = ctrl:GetFocusedItem()
+        if keycode == wx.WXK_LEFT and mod == wx.wxMOD_NONE and item:IsOk() and ctrl:IsExpanded(item) then
+          ctrl:Collapse(item)
+        else
+          event:Skip()
+        end
+      end)
+  end
+  return ctrl
+end
+
 function ide:LoadFile(...) return LoadFile(...) end
 
 function ide:CopyToClipboard(text)
```

**Comment by CapsAdmin** [comment]
Sorry for the late response but the big update solved this for me. Thanks!
