### ISSUE TITLE
Love2D:Can't find 'main.lua' file in the current project folder. 

### ISSUE THREAD

**Issue by vlad-mal** [pkulchenko/ZeroBraneStudio#69]
When I try to run any of the examples (Examples from ZeroBrane Studio) Love2d, then the error is: "Can't find 'main.lua' file in the current project folder."

WinXP SP3.
ZeroBrane Studio (0.33; using MobDebug 0.502)
Love2D: 0.8.0

Thanks.

**Comment by cmmjava** [comment]
Thanks！ That is ok ！

**Comment by StuffyMcMuffins** [comment]
whenever I try to make a main.lua file it says "error: operation not permitted
