### ISSUE TITLE
outline/project view should be able to divide into left/right.

### ISSUE THREAD

**Issue by chansey97** [pkulchenko/ZeroBraneStudio#691]
It seems the outline/project view can't be draged to right side, but most of programmer like divide this to left and right. 
It can make programmer see both of these at the same time.

**Comment by pkulchenko** [comment]
You can drag the outline tab out, which will make it a standalone window that you can dock to any position.

You can also undock the entire panel and re-dock it where you want. Just double click on the tab background and it will undock the window.

I'll make sure it's covered in the documentation.

**Comment by chansey97** [comment]
It works now, thanks. 
I forgot double click.
