### ISSUE TITLE
Attempt to perform arithmetic on field wxFSW_EVENT_CREATE

### ISSUE THREAD

**Issue by sladecraven** [pkulchenko/ZeroBraneStudio#693]
With git head, Linux and Windows, in file filetree.lua, line 920

Idea ?

**Comment by pkulchenko** [comment]
@sladecraven, not sure how it's possible using the binaries included as they should define these variables on all the platforms. Can you check the version of wxwidgets in the `Help | About` window? Can you also check the value of `wx.wxFileSystemWatcher` in the Local console?

I'll add a check for these constants as I'd still like to make it work for earlier version of wxlua, which may not have them set, but it should definitely work with the binaries included.

**Comment by sladecraven** [comment]
Understood ! We are launching ZB from a local copy, not directly from the git clone. And an old wx.dll/.so was still there. I synchronized both folders and now its work. 
Thanks for the hint :)

**Comment by pkulchenko** [comment]
For those who may also come across this issue: it may happen if you install 1.40 over the previous version, which will have both wxlua libraries present and the old one (which doesn't have these new constants defined) may get used. Simply install v1.40 into a new folder to avoid this issue.
