### ISSUE TITLE
Move cursor to current breakpoint

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#694]
I'm pretty used to other IDEs moving their cursor to the line with the breakpoint when the debuggee hits the breakpoint. Could ZBS do that as well? Is it possible to implement this feature in a separate package?

**Comment by pkulchenko** [comment]
@madmaxoft, do you mean having an option that moves the cursor to the current line when the breakpoint is activated (or enabling it as a plugin)?

There was a related feature request (which may achieve the same result) to add a shortcut to move the cursor (and scroll to) the current line marker (the green arrow) during debugging.

**Comment by madmaxoft** [comment]
Just to be sure we're on the same language :) If by "activating" you mean "when the program runs and hits a breakpoint, the IDE is brought to front and the breakpoint file is displayed", then yes, that's exactly what I'm after. It feels weird that the correct location is shown but the cursor is "left behind" on a different line.

No, it's not about a shortcut, it's about doing this automatically each time a breakpoint is hit. Of course, it could be an option or even a package, if you don't think the functionality is universally wanted.

**Comment by pkulchenko** [comment]
> If by "activating" you mean "when the program runs and hits a breakpoint, the IDE is brought to front and the breakpoint file is displayed", then yes, that's exactly what I'm after.

Yes, that's how I interpreted it ;).

**Comment by pkulchenko** [comment]
@madmaxoft, try `debugger.linetobreakpoint = true`. I didn't quite like the effect, so I'm keeping it off by default.

**Comment by madmaxoft** [comment]
Works great, thanks
