### ISSUE TITLE
Drag drop does not work with Dolphin or Thunar file manager on Linux

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#696]
It might be an issue with wxlua or wxwidgets but it's a feature that I really miss.

**Comment by pkulchenko** [comment]
@CapsAdmin, which of the d-n-d doesn't work? I've tested the one that was implemented in #177 and it seemed to work in my case (Ubuntu 12.04). Maybe it depends on the Linux version and the file manager... What's your environment?

**Comment by CapsAdmin** [comment]
I'm using kde neon (based on ubuntu 16) which has the latest kde desktop. The filemanager is dolphin.

**Comment by CapsAdmin** [comment]
It does work with the nautilus file manager but it does not work in thunar or dolphin.

**Comment by pkulchenko** [comment]
I wonder if the format is different for the dropped content, so that's why it's not recognized.

Can you apply the following diff to get the dropped content printed (line numbers may be a bit different as I have some changes that haven't been pushed, but you should be able to find the right spot):

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 25f33b1..bf32111 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -1401,6 +1408,7 @@ function CreateEditor(bare)
   elseif ide.osname == "Unix" then
     editor:Connect(wxstc.wxEVT_STC_DO_DROP, function(event)
         local dropped = event:GetText()
+ide:Print(dropped)
         -- this event may get a list of files separated by \n (and the list ends in \n as well),
         -- so check if what's dropped looks like this list
         if dropped:find("^file://.+\n$") then
```

**Comment by CapsAdmin** [comment]
With dolphin dragging a file to zerobrane reveals an X icon as if it's not allowed. With thunar there's nothing happening.

Neither of them prints anything.

**Comment by pkulchenko** [comment]
@CapsAdmin, seems to be a dolphin/thunar problem (at least going by [other reports](https://bugs.chromium.org/p/chromium/issues/detail?id=42494)). See if the workaround with `Ctrl` works in your case. Probably not much else I can do.

**Comment by pkulchenko** [comment]
@CapsAdmin, did you check the report I mentioned and did you try with `Ctrl`? I don't think there is anything I can do to affect this.

**Comment by CapsAdmin** [comment]
I did and holding ctrl does not have an effect in zerobrane but it does have an effect in chrome. 

I understand. This is something that should be reported to in wxwidgets or gtk maybe.
