### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#70]

**Comment by pkulchenko** [comment]
@inigosola, @bartoleo, @toiffel, @riidom, @Fringale, @Yonaba, @cosmotect, @evandro-costa: I updated all language files with some new messages. Please take a look and see if any of the translations need to be updated. Thank you!

**Comment by pkulchenko** [comment]
@inigosola, @bartoleo, @toiffel, @riidom, @Fringale, @Yonaba, @cosmotect, @evandro-costa: I added one more batch of language file updates. Those messages that require pluralization have `{}` instead of `nil` values. Please take a look and see if any of the translations need to be updated. Thank you!

**Comment by bartoleo** [comment]
I'm working on italian translation, I have a doubt, what do you mean with 'Map Directory'?

**Comment by pkulchenko** [comment]
@bartoleo, thank you for working on the update. `Map Directory` (there is also `Unmap Directory`, which you will only see if you have mapped directories) is a function in the file tree that allows you to "map" external directories into it to make them appear as if it's a directory in that location of the tree. Sort of like a virtual directory or a directory symlink that only exists inside the IDE.

**Comment by bartoleo** [comment]
Ok, thank you
Il 01/ott/2015 17:06, "Paul Kulchenko" <notifications@github.com> ha
scritto:

**Comment by Yonaba** [comment]
Would you mind giving much more explanation on the "Start File" feature ?

**Comment by pkulchenko** [comment]
@Yonaba, sure: `Start File` identifies the file that will be used when the user does `Run`/`Debug` instead of the currently selected file. This helps in those cases when you have a large project that you always run from, let's say, `main.lua` and you want this to happen even when you are editing some other file.

**Comment by riidom** [comment]
Hi, two questions please:
a) the {} get replaced with something like {"Found one instance.", "Found %d instances.", right?
b) what means "run to cursor"? Something like "start program and stop at cursor position"? Or am I on the wrong path here.
Many thanks.

**Comment by Yonaba** [comment]
@riidom 
Just some assumptions of mine...
>a) the {} get replaced with something like {"Found one instance.", "Found %d instances.", right?

Yes, definitely. it gets better if you do not forget the enclosing curly brace "}" at the end. The first element in the array will be the singular form, and the second one will be the plural form. Just like [here](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/cfg/i18n/en.lua#L3).

>b) what means "run to cursor"? Something like "start program and stop at cursor position"? Or am I on the wrong path here.

I just think this feature is mostly related to debugging purposes. Yes, you are almost correct, it will define the cursor location just like a breakpoint for debugging and run the actual code up to the cursor position. Similar to [Visual Studio](http://dailydotnettips.com/2013/09/05/use-run-to-cursor-and-save-time-while-debugging/)'s feature.

**Comment by riidom** [comment]
@Yonaba :
thanks a lot Roland :)

**Comment by madmaxoft** [comment]
I'd like to point out that some languages will need even more complicated handling than singular / plural. 

For example in Czech, due to declension (https://en.wikipedia.org/wiki/Declension) the counts of `2`, `3`, and `4` use a different gramattical case.
Even worse, it's not limited to those three counts, but to some (but not all) compound numbers:
`10*N + 2`, `10*N + 3` and `10*N + 4` use a different case than `10*N + 5+`, except for when `N mod 10 == 1`; similarly, `10*N + 1` uses a singular form except for when `N mod 10 == 1`.

For this reason, the easiest way of handling this is to completely avoid phrases such as `%d items found` and instead use `Items found: %d` which is universal for all counts.

**Comment by pkulchenko** [comment]
@riidom, yes, Roland is correct about `{}` in terms of pluralization. I decided to show defaults for normal strings as `nil` and defaults for the values that require different strings because of pluralization as `{}`, so it should be easy to find the file now.

@madmaxoft, that's true, but it should already be handled with the current approach. Russian is similar to Czech in this regard, so I'm quite familiar with the situation.

The way it's done in ZBS is that the value of `[0]` element is a function that returns an index based on the count passed to it. So, in "simple" languages, it looks like `return c == 1 and 1 or 2`, which means, take first element when count is 1 and second element in all other cases, which produces `"%d instance"` vs `"%d instances"`.

In Russian the function is more complicated, as it produces three different indexes, so Russian translation table requires three elements. I have some documentation on this in the [translation section](https://studio.zerobrane.com/doc-translation), but can expand it if needed.

**Comment by madmaxoft** [comment]
Thanks for the explanation, I missed that documentation bit.

**Comment by bartoleo** [comment]
made pull request #536

**Comment by pkulchenko** [comment]
@inigosola, @bartoleo, @riidom, @Fringale, @Yonaba, @cosmotect, @evandro-costa: updated language files with several new messages (not much since the last release); as before you only need to look for `nil` values.

There is a tab added (`Markers`) that shows breakpoints and bookmarks, so there are several messages related to that tab. Let me know if you have any questions; thank you for all your help!

**Comment by pkulchenko** [comment]
@inigosola, @bartoleo, @riidom, @Fringale, @Yonaba, @cosmotect, @evandro-costa: I updated language files with few new messages; as before you only need to look for nil values.

Thank you for your regular help with translations!

**Comment by bartoleo** [comment]
made Pull request #681
