### ISSUE TITLE
Outline and Project panes won't undock / dock to the right edge

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#700]
I have the Outline and Project panes docked on the left, Outline underneath Project. I wanted to move the Outline pane to the right edge of the main window, but it won't. It seems impossible to undock either of the two panes into a free-floating tool window, and they won't dock to anywhere else than the left edge of the main window.

This seems to be Windows-specific, as it only happens on both of my Windows machines (Win7, Win8.1), but on my Linux machine (Ubuntu Xenial) it works perfectly.

**Comment by pkulchenko** [comment]
@madmaxoft, I can't reproduce either issue. I can undock Outline and move/redock Project tab without problems on Win8.1.

Just to make sure we are talking about the same sequence:
1. To move Outline: drag the tab out to a free space; this will create a free-floating window with one tab (Outline) in it. Then dock that window to the desired location.
2. To move Project: double click on the tab space, which will turn the panel into a free-floating window. Dock that window to the desired location.

**Comment by madmaxoft** [comment]
Yes, those are the steps I took, the free-floating window is not created.

If it makes any difference, I'm on commit 8caf544d989f7ec443920955b5793dd33e8316f4 and have a few packages installed:
- analyzeall
- cuberite
- edgemark
- striptrailingwhitespace
- wordwrapmenu

Before attempting the re-dock, I have the Outline panel in the left dock underneath the Project panel:
![unredockable-panels](https://cloud.githubusercontent.com/assets/4388386/19047938/579b1168-89a4-11e6-8bd6-a877280bcc0a.png)

**Comment by pkulchenko** [comment]
@madmaxoft, you are right, I forgot to mention that. There was a bug in wxwidgets that led to an application crash when the tab was dragged from a split notebook (when it was a single tab), so I added a check to prevent that. So to drag a tab out you need to first merge it back together with the "Project" tab.

It does appear to be working with the latest wxwidgets code (after the upgrade), so it's possible that this restriction can be relaxed. You can try the following patch:

```diff
diff --git a/src/editor/gui.lua b/src/editor/gui.lua
index 666b6d1..04ceb17 100644
--- a/src/editor/gui.lua
+++ b/src/editor/gui.lua
@@ -449,9 +449,11 @@ local function addDND(notebook)
           notebook:SetWindowStyleFlag(flags - wxaui.wxAUI_NB_TAB_SPLIT)
         end

-        -- don't allow dragging out single tabs from tab ctrl
-        -- as wxwidgets doesn't like removing pages from split notebooks.
-        if tabctrl:GetPageCount() == 1 then return end
+        if ide.wxver < "3.0" then
+          -- don't allow dragging out single tabs from tab ctrl
+          -- as wxwidgets doesn't like removing pages from split notebooks.
+          if tabctrl:GetPageCount() == 1 then return end
+        end

         local label = notebook:GetPageText(selection)
         local pane = ide:RestorePanelByLabel(label)
```

**Comment by madmaxoft** [comment]
I tried the patch, now I am able to drag the Outline panel into a separate floating window and re-dock it to the right edge of the window. However, once docked there, it's stuck. I can't undock it anymore, and I can't undock the Project panel either. The only thing I can do is drag the Outline onto the Project panel and they will merge as a tabbed panel. Then I can un-dock the Outline back into a floating window again. I guess it's better than before, though still not ideal.

**Comment by pkulchenko** [comment]
> However, once docked there, it's stuck. I can't undock it anymore, and I can't undock the Project panel either.

Mattes, no, this behavior didn't change: you just need to double click the tab background to undock the panel. It's been this way since we removed the captions on those panels in an earlier redesign.
