### ISSUE TITLE
problem with arg variable

### ISSUE THREAD

**Issue by meltinglava** [pkulchenko/ZeroBraneStudio#703]
according to https://www.lua.org/pil/5.2.html

> The three dots (...) in the parameter list indicate that the function has a variable number of arguments. When this function is called, all its arguments are collected in a single table, which the function accesses as a hidden parameter named arg. Besides those arguments, the arg table has an extra field, n, with the actual number of arguments collected. 

but running this code in ZBS
```lua
local function printT (...)
	local indentMark = " "
	local function printTable (k,indent)
		if not indent then indent = "" else indent = indent..indentMark:rep(4) end
		for key, val in pairs(k) do
			if type(val) == "table" then
				print(indent..key)
				printTable(val,indent)
			else
				print(indent..key..": "..type(val).."\n",val)
			end
		end
	end
	if type(arg) == "table" then
		printTable(arg)
	else
		print(arg)
	end
end
a = "adf \n asdfsadf asdf\n adssa df"
printT(a:find("\n"))
```
the output from ZBS is compleatly different from what i get in the console (lua 5.1.5)
it returns 2 filepaths, a name to a function and "-e"
saw some issues discusting this issue thow not with the use of `arg` as `...` passed to a func. I know there are easy workarouds, thow I think it is sad that ZBS should stay away from the lua manual

**Comment by pkulchenko** [comment]
@meltinglava, I don't think it's a problem with ZeroBrane Studio. The `arg` syntax you are describing is not in Lua 5.1 (at least not mentioned in [Function Definitions](http://www.lua.org/manual/5.1/manual.html#2.5.9)); you may be able to access it from Lua 5.1 interpreter as it's compiled with 5.0 compatibility by default, so it seems like it's there, even though it's not Lua 5.1 feature.

Also, ZBS is using LuaJIT internally (as its Lua 5.1 interpreter) and it explicitly [doesn't support this syntax](http://luajit.org/faq.html):

> Q: Why do I get this error: "attempt to index global 'arg' (a nil value)"?
> Q: My vararg functions fail after switching to LuaJIT!
>     LuaJIT is compatible to the Lua 5.1 language standard. It doesn't support the implicit arg parameter for old-style vararg functions from Lua 5.0.
>     Please convert your code to the [Lua 5.1 vararg syntax](http://www.lua.org/manual/5.1/manual.html#2.5.9).
