### ISSUE TITLE
Auto move the Cursor to the first visual line of collapsed block after collapse

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#704]
Currently, after collapse, the cursor is flooded among the block which can't be display.
Which is inconvenient to edit / navigate continuously.

**Comment by robertlzj** [comment]
Currently, after collapse, the cusor is flooded amount among the block which can't be display.

**Comment by pkulchenko** [comment]
It's an interesting suggestion, but I'm not sure about it. I looks straightforward when only one block is collapsed, but what if you use "Fold All" and "Unfold All"? The cursor will end up in a different location where it was initially. Besides, if the cursor is hidden in the folded block, as soon as you move it up/down, it will re-appear, so it's not usually an issue, no?

**Comment by robertlzj** [comment]
>    if the cursor is hidden in the folded block, as soon as you move it up/down, it will re-appear

Yes it's "as soon as you move it up/down, it will re-appear
", but the **position** of cusor is not accord with intuition.
When collapse a folder with cusor in it.
Need to click `up` two times to move it up before the first line of the block.
Need to click `down` then `up` to move it the line next to the block.
The first click *just* makes it re-appear.
If repeat manipulate for collapsing and editing sequentially, then it's a little inconvenient.

**Comment by pkulchenko** [comment]
What I can do is to make Shift-F12 (Fold the current line) to do that as it's guaranteed to only fold one block (so there is no confusion when multiple blocks are folder). I think this will make it work well together with editing from the keyboard.

**Comment by robertlzj** [comment]
Yes, I think it's exact the request. Thanks~~
