### ISSUE TITLE
Request: indent collapsed block by 'Tab' its first line

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#705]
Currently, 'Tab' the first display line of collapsed block will only get the first line of block indented.
Indent the whole block will be grateful.

I found could do this by `ctrl+click`. See #653 - Select scope . Thanks!

**Comment by pkulchenko** [comment]
Yes, I think `Ctrl-Click` and then de-indent is the best way as it makes it more visible and less "magical".
