### ISSUE TITLE
Toggle un/fold sub block

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#706]
Such as 'shift-click' on folder margin to toggle descendants folder.
Currently, could only toggle current line or all.
If there is many level of amount folders, it will be many and misellaneous with trifles to do this.

**Comment by pkulchenko** [comment]
@robertlzj, can you give an example of how this would work? Do you mean to fold the parent level? By using `Shift-Click` several times (without even moving the cursor) you can easily achieve that. Or maybe I misunderstood your request?

**Comment by robertlzj** [comment]
Currently, `Shift+Click` do nothing.
I mean, to toggle *descendants* folder between fold/unfold, by `Shift+Click` its *parent*.
Like "Fold/Unfold All", but olny act on one folder's *children*. 
I think “Fold/Unfold Sub" is much flexible. Sometimes user could fold sub folders, then unfold level by level with a glimpse of sibling levels.

**Comment by pkulchenko** [comment]
You may be running an older version; in my version `Shift-Click on the fold margin` folds the current fragment, which may be what you want. This was implemented in #616, as you requested ;).

**Comment by robertlzj** [comment]
Sorry, `Shift+Click` on folder margin will toggle fold/unfold at current level. But not the purpos of this topic.

Fold current line will hide all its children. Unfold it will makes them un-hide **and** *keeping* their folder status.

Here, I mean "**Fold Descendant**" - to toggle *all the children* to fold them all, not *one line*. Then user could unfold each one level by level.

> Just like "Fold/Unfold All", but olny act on one folder's children.

After "**Fold All**", all of the folder is folded, *not* only the top level folder. It's different from "**Fold Line**".

`Fold Descendant` from top / root equals `Fold All`.

**Comment by pkulchenko** [comment]
@robertlzj, I changed the behavior of `Ctrl-Shift-FoldMarginClick` to toggle the fold of the current and all children lines. So, clicking it twice will fold/unfold all children, but if you click it once to fold and then unfold just the parent, you'll see all the children still folded.

I like this behavior as it gives the user the flexibility of un/folding the current block or the current block plus its children.

**Comment by robertlzj** [comment]
Yes! Yes! Thank you~~

**Comment by robertlzj** [comment]
- `Shift+Ctrl+F12` not work as expect. Keyboard user would like hotkeys.
 - Also, item in menu 'Edit\Source' is miss. Then user could assign hotkey themself.

**Comment by pkulchenko** [comment]
Right; the items need to be added to the menu.

> how about `Shift+Click` at the +/- flag to do this?

I don't want to overload `Shift` with too many combinations. I think I'll stick with the current combination.
