### ISSUE TITLE
Love game: breakpoint not hit.

### ISSUE THREAD

**Issue by YPakhomau** [pkulchenko/ZeroBraneStudio#709]
I tried to run simple hello world game, set breakpoints, started debugging. But they were not hit. Entire process on video:
https://youtu.be/fiWQ9JZFQ7c

Please help me, i want to try Love engine, but cannot debug right now.

Raw lua debug is working.

**Comment by YPakhomau** [comment]
False alarm - i didn't this in Love:
if arg[#arg] == "-debug" then require("mobdebug").start() end

**Comment by pkulchenko** [comment]
Right; you need to add that line to start the debugger. It's covered under [debugging](https://studio.zerobrane.com/documentation#debugging) section (Love2d debugging link).
