### ISSUE TITLE
Vertical line marker support

### ISSUE THREAD

**Issue by pixeljetstream** [pkulchenko/ZeroBraneStudio#711]
Similar to http://superuser.com/questions/414209/notepad-80-character-line-marker
would be nice to set the line marker via settings file

**Comment by madmaxoft** [comment]
There's an EdgeMark package exactly for that: https://github.com/pkulchenko/ZeroBranePackage/blob/master/edgemark.lua

**Comment by pkulchenko** [comment]
@pixeljetstream, @madmaxoft is correct, you can use edgemark and if you need a different value than the default 80, you can use `edgemark = {column = 60}` or something similar in the config.
