### ISSUE TITLE
Clicking on parameter tooltip crashes the IDE

### ISSUE THREAD

**Issue by CetoBasilius** [pkulchenko/ZeroBraneStudio#712]
Clicking on the parameter tip crashes the app. To reproduce, type `require(` and the tip will show up. If you click the tooltip, the app crashes.

I am using the master branch, on commit 13f5b18, using macOS Sierra, 10.12.1

The image below specifies what tooltip i am talking about:
<img width="422" alt="screen shot 2016-11-20 at 12 27 06 pm" src="https://cloud.githubusercontent.com/assets/4663385/20465176/ef88d8d2-af1c-11e6-92c9-19fb2a59924b.png">

**Comment by madmaxoft** [comment]
This doesn't happen on my Windows machine, I assume it's something MacOS-specific.

**Comment by pkulchenko** [comment]
@CetoBasilius, thanks for the report; I'll take a look.

**Comment by CetoBasilius** [comment]
[Here](https://gist.github.com/CetoBasilius/9c0c6489bf17898bc753b54ef6aa6eed) is my user configuration.

**Comment by pkulchenko** [comment]
This looks like a wxwidgets bug as if I replace `libwx.dylib` with the one from 1.30, the issue goes away. I'll try to trace it in wxwidgets, but since it was a recent upgrade, I don't plan another one in the near future (and there wasn't any new wxwidgets release since the upgrade).

Linking to #260 to track.

**Comment by pkulchenko** [comment]
I opened a [pull request for wxwidgets](https://github.com/wxWidgets/wxWidgets/pull/595) that should fix this (when merged and when wxwidgets/wxlua upgraded).

**Comment by pkulchenko** [comment]
[The PR has been merged into wxwidgets](https://github.com/wxWidgets/wxWidgets/pull/595#event-1423389175), so this should be fixed with the next wxwidgets upgrade.

**Comment by pkulchenko** [comment]
@CetoBasilius, this should be resolved with the changes in #999.

**Comment by pkulchenko** [comment]
This has been implemented as part of the changes in #999 that have been merged.
