### ISSUE TITLE
File naming with remote debugging

### ISSUE THREAD

**Issue by MichaelSenko** [pkulchenko/ZeroBraneStudio#713]
Not sure if this is a bug, or just normal Windows behavior.  Using remote debugging (Win 7 for ZeroBrane Studio) to another processor (Linux) with the Debugger Server, if there's confusion with capitalization (TEST.lua vs. Test.lua) on the two sides of the wire, breakpoints will not trigger.  Oddly, manual break points and stepping through the file seems to work fine with capitalization mismatches.

**Comment by pkulchenko** [comment]
You are right, this may not work if the Linux source has `Test.lua`, but the breakpoint on Windows (in the IDE) is set on `TEST.lua` file.

It would work as expected if the IDE was on Linux and the application on Windows, but when the IDE submits the breakpoint from Windows in the wrong case, the application on Linux doesn't "know" what the correct case is and it was deemed to be "expensive" to do this on every check, so the expectation is that the file opened in the IDE will have the expected capitalization for cross-platform debugging.

Is there any reason why the capitalization is different in your case?

**Comment by pkulchenko** [comment]
@MichaelSenko, btw, what do you mean by "manual break points"? The stepping always works as it doesn't rely on breakpoints.

**Comment by MichaelSenko** [comment]
I didn’t write the code, but if I had to guess, I would say the capitalization issue was a convenience issue for typing.  When fetching files using a console on the remote system, the file name is capitalized before being passed back, and then the Windows side capitalizes all files during the search of what’s available in the Lua source directory.

In our case, the remote system thinks it is running TEST.lua, while the file in Windows that ZeroBrane Studio can’t find is Test.lua, but based on your description below, this should still fail.

**Comment by MichaelSenko** [comment]
While the debugger is running, click on the Pause button (“Break execution at the next executed line of code”).  This will break as expected and pop up the appropriate file with the cursor at the appropriate line.  I guess this works because Windows is ignoring the capitalization, and thus can find the file.

**Comment by pkulchenko** [comment]
> In our case, the remote system thinks it is running TEST.lua, while the file in Windows that ZeroBrane Studio can’t find is Test.lua, but based on your description below, this should still fail.

That's strange as this is precisely the case that should be handled correctly on the case-insensitive system. Do you have `editor.autoactivate=true` set in the configuration file (as described in [this section](https://studio.zerobrane.com/doc-editor-preferences))?

I've tested several cases and all of them work as expected on Windows. You can test this yourself by running something like the following in the Local Console:

```lua
ide:GetDebugger():ActivateDocument([[Full\path\to\file\including\name.lua]], 3)
ide:GetDebugger():ActivateDocument([[Full\path\to\file\including\NAME.lua]], 3)
```

This will only work if the file is already opened or if `editor.autoactivate=true` is set.

What *may* be happening is that the breakpoint may be not firing because of the name mismatch, but if it *is* triggered, the file should be activated on Windows regardless of how the name is spelled. You may want to check [Why breakpoints are not triggered](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered) if you haven't seen it already, but I think in this case it may be a case mismatch.

**Comment by MichaelSenko** [comment]
Hi Paul,

                I started at your breakpoint FAQ and worked my way down the list one by one.  The hint on verbose mode for the debugger is what allowed me to figure out the problem.  I saw the caps mismatch in the console.

I think it actually all makes sense, but it may be my naïve point of view.  When clicking on break in the GUI, I believe a command for break on next line is sent and no file name matching is required.  The remote system breaks and returns information on the file and line where the break occurred.  This comes back as TEST.lua, and since Windows is case-insensitive, it succeeds in pulling up Test.lua (I have autoactivate=true).  When setting a specific breakpoint, Windows sends a message saying break at line N in file Test.lua.  The remote system being case sensitive can’t find a matching file, and thus doesn’t obey the break command.  I’ve confirmed that the break never occurred, and not that the GUI just didn’t recognize the break.

Thanks
Mike

**Comment by pkulchenko** [comment]
Mike, I think this works exactly as you described. Windows is case-insensitive, but case-preserving, so you should be able to rename `Test.lua` to `TEST.lua` to see if this fixes the breakpoints set from the IDE. You can do the rename right from the project tree; just click on the file when it's selected (or use `F2`) to switch to the edit mode and update its name.

**Comment by MichaelSenko** [comment]
That is exactly what I did to confirm the problem.  Now the challenge of convincing people that we should stop mangling the capitalization.

Thanks for the clarifications

**Comment by pkulchenko** [comment]
@MichaelSenko, I updated the FAQ to cover this case as well.
