### ISSUE TITLE
Some Chinese character shows messy character when paste

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#714]
Such as:
- For some normal Chinese character like `象`, the result from paste becomes un-normal - `a|x8C|`. 
Some character like `字` are normal in paste.

For these characters didn't work correctly like `象`,  there is some addtion test:
- Copy from IDE and paste to other editor like *notepad* is normal.
- Copy from normal and paste to the IDE is un-normal.
- Input from IME is normal.

**Comment by pkulchenko** [comment]
Yes, I'm aware of this issue, but I have not been able to fix this and [bringing it up on the wxwidgets mail list](https://groups.google.com/forum/#!msg/wx-dev/61a6yK7JYxw/utzdsLpnCAAJ) did not lead to any resolution. I've added logic to the IDE to mitigate it, but some characters that have a specific number of bytes are copied incorrectly if it's the first character in the string being copied. If you capture one more character before it, then both will be copied correctly (assuming the first character doesn't suffer from the same issue).

The [fragment that implements this logic is here](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/src/editor/package.lua#L368-L396); if you find a way to make it work better, I'll definitely incorporate it (the current implementation is more of a hack).
