### ISSUE TITLE
"Pay with Card" not work in Edge/IE11 in Win10

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#715]
or some remote sites like google service was not available from my location..

**Comment by pkulchenko** [comment]
@robertlzj, what exactly fails? I tried in Edge on Win10 machine and the payment dialog is displayed correctly and entering invalid card number is reported properly (which requires form submission and validation). Please reopen and provide some additional details if it's still not working for you.

**Comment by robertlzj** [comment]
After click Pay with Card, nothing happens in Edge.
Now in IE of win10 1703, a dialog shows asking for entering card informations which I feel not safe.
So, is there any PayPal account people can use directly?
