### ISSUE TITLE
Ctrl Up/Down will move Caret when scroll out edge

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#716]
Normally, `Ctrl Up/Down` will **scroll** up/down without changing caret and selection.
But, when the caret will scroll out top/bottom of editor's visual edge, using `Ctrl Up/Down`, the selection will be *deselection*, and the caret will **move** up/down, seems to ensure it is inside visual edge. Where only **scroll** is expected.

**Comment by pkulchenko** [comment]
This is not something that the IDE handles as this functionality is provided by Scintilla. Even if you call `ide:GetEditor()::LineScrollUp()` programmatically, it will have the same effect as what you see using the cursor. I think the idea is that the cursor stays on the screen, so when scrolling, Scintilla moves the cursor when it comes to the boundary of the screen. If you find how to re-configure it to get the behavior you want, I'll consider it.
