### ISSUE TITLE
Inspect variable as the stack selected

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#717]
Currently,
```lua
function b()
	local var=2	--1. break here
end
function a()
	local var=1	--2. inspect variable by hover at 'var' show the value of the local one of function 'b',
			--which is nil at the breakpoint above. Expect to show value 1 as the stack view shows
	b()
end
a()
```

And for the recursion function or new instance of the same name function call, maybe shows variable at the environment as same as the one *select level* in 'Stack View' is better than the *top level* of stack.

**Comment by pkulchenko** [comment]
The tooltip only relies on the name of the variable and as the result has no information to get the value from the correct stack frame. While it may be possible to identify a proper frame, it's going to be quite complex as it would require static analysis plus the request for a particular stack frame (which is not supported by the debugger). It *may* be possible to get the value from the already reported stack frame, but it's a hack, as the stack view may not be displayed/requested and it would still require a static analysis to identify the function that the requested variable "belongs" to and where that function is in the stack frame.

I'm not going to implement this, but patches are welcome ;).
