### ISSUE TITLE
debugging in Wine issue: lowercase filename vs mixed case filename

### ISSUE THREAD

**Issue by marcelvanherk** [pkulchenko/ZeroBraneStudio#718]
Hi Paul,

Long time no speak. Still using ZBS happily day after day, since 1.5 year in Manchester. 

I was playing with running my medical (Windows) software under Wine on Debian, controlled by ZBS from Linux. Works fine but Lua breakpoints often don't trigger. The cause is that the Windows Lua DLL (5.1.4) returns the filename in lowercase, while it was sent with mixed case, e.g. (example verbose debugging typed over, on different PC):

debugger sent: run @/home/marcel/Desktop/test.lua
..
debugger received: /home/marcel/desktop/test.lua 3 nil

It took me a while to see the lowercase 'd'. If I move the script to an all lowercase path or debug a Linux binary, ZBS works fine. Any ideas for a fix?

The issue is I believe in ActivateDocument, which tests the file exists, even though it is open in the editor.

regards,

Marcel

**Comment by pkulchenko** [comment]
> debugger sent: run @/home/marcel/Desktop/test.lua
> debugger received: /home/marcel/desktop/test.lua 3 nil

Marcel, just to make sure I understand the issue: is this the verbose output on the Linux machine running the IDE while the application is running in Wine? What is the full file name of the file opened in the IDE?

If the problem is indeed with the Lua interpreter converting the filenames into lower case, there is not much I can do, other than maybe adding an option to make case-insensitive comparison in editor when activating files. The ActivateDocument is using "SameAs" function that makes sure that two paths are the same, but clearly `Desktop/test.lua` and `desktop/test.lua` are *not* the same on Linux even though they are the same on Windows.

**Comment by marcelvanherk** [comment]
Hi Paul,

indeed this is the verbose output of the Linux machine running the IDE. An option that can be enabled through the interpreter to make (open file) activation case insensitive would be a perfect solution. I guess it could be of interest to others remote debugging between systems with different case sensitivity.

Regards,

Marcel

**Comment by pkulchenko** [comment]
Marcel, try the following patch and let me know if it works for you; you'll need to add `debugger.ignorecase=true` to the config to enable case-insensitive matching in the IDE.

```lua
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index 5863318..eb23f26 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -343,9 +343,10 @@ function debugger:ActivateDocument(file, line, activatehow)
 
   if PackageEventHandle("onDebuggerPreActivate", debugger, file, line) == false then return end
 
-  local activated
+  local activated = false
   local indebugger = file:find('mobdebug%.lua$')
   local fileName = wx.wxFileName(file)
+  local fileNameLower = wx.wxFileName(file:lower())
 
   for _, document in pairs(ide.openDocuments) do
     local editor = document.editor
@@ -353,6 +354,7 @@ function debugger:ActivateDocument(file, line, activatehow)
     -- when checking for the content remove all newlines as they may be
     -- reported differently from the original by the Lua engine.
     if document.filePath and fileName:SameAs(wx.wxFileName(document.filePath))
+    or ide.config.debugger.ignorecase and fileNameLower:SameAs(wx.wxFileName(document.filePath:lower()))
     or content and content:gsub("[\n\r]","") == editor:GetTextDyn():gsub("[\n\r]","") then
       ClearAllCurrentLineMarkers()
       if line then
```

**Comment by marcelvanherk** [comment]
Hi Paul,

just tested the patch and it works brilliantly - thanks!. 

However, I wondered if ide.config is the right place to store the setting: it is maybe too global, as it would affect all debuggers at once. it would be nice if an interpreter can turn ignorecase on and off; maybe through fattachdebug which calls DebuggerAttachDefault.

regards,

Marcel

**Comment by pkulchenko** [comment]
Marcel, I agree, it's a possibility, although I still think that most users would add it to the config if needed (although in your case it may be easier to add to the interpreter itself). Try with this patch (on top of the earlier one):

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index c328014..e224893 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -343,7 +343,7 @@ function debugger:ActivateDocument(file, line, activatehow)
 
   if PackageEventHandle("onDebuggerPreActivate", debugger, file, line) == false then return end
 
-  local activated
+  local activated = false
   local indebugger = file:find('mobdebug%.lua$')
   local fileName = wx.wxFileName(file)
   local fileNameLower = wx.wxFileName(file:lower())
@@ -353,8 +353,10 @@ function debugger:ActivateDocument(file, line, activatehow)
     -- either the file name matches, or the content;
     -- when checking for the content remove all newlines as they may be
     -- reported differently from the original by the Lua engine.
-    if document.filePath and fileName:SameAs(wx.wxFileName(document.filePath))
-    or ide.config.debugger.ignorecase and fileNameLower:SameAs(wx.wxFileName(document.filePath:lower()))
+    local ignorecase = ide.config.debugger.ignorecase or (debugger.options or {}).ignorecase
+    local filePath = document:GetFilePath()
+    if filePath and (fileName:SameAs(wx.wxFileName(filePath))
+      or ignorecase and fileNameLower:SameAs(wx.wxFileName(filePath:lower())))
     or content and content:gsub("[\n\r]","") == editor:GetTextDyn():gsub("[\n\r]","") then
       ClearAllCurrentLineMarkers()
       if line then
@@ -406,8 +408,7 @@ function debugger:ActivateDocument(file, line, activatehow)
         -- breakpoints that have been set based on its filepath;
         -- if the content has been matched, then existing breakpoints
         -- need to be removed and new ones set, based on the content.
-        if not debugger.editormap[editor] and document.filePath then
-          local filePath = document.filePath
+        if not debugger.editormap[editor] and filePath then
           local line = editor:MarkerNext(0, BREAKPOINT_MARKER_VALUE)
           while filePath and line ~= -1 do
             debugger:handle("delb " .. filePath .. " " .. (line+1))
```

You can now specify `ide:GetDebugger():SetOptions({ignore = true})` (`ide:GetDebugger():SetOptions()` replaced `DebuggerAttachDefault`, although the old function is still available for compatibility, but will be removed in the future.). `SetOptions` is available since 1.40, so you can switch to using it.

**Comment by marcelvanherk** [comment]
Hi Paul,

this makes sense. I will try it tonight.

Marcel

**Comment by marcelvanherk** [comment]
Hi Paul,

just tested and this works fine. Just to make sure, in my interpreter I need to replace (in two places: fattachdebug and frun)):

DebuggerAttachDefault({redirect = "c"})

by (for compatibility with old ZBS versions, we widely use 1.10)

if ide:GetDebugger().SetOptions then
  ide:GetDebugger():SetOptions({ignorecase = true; redirect = "c"})
else
  DebuggerAttachDefault({redirect = "c"})
end

Marcel

**Comment by pkulchenko** [comment]
Marcel, that's correct; thank you for checking. I'll get that change in then.
