### ISSUE TITLE
 Zerobrane 1.5 (portable) crash when i try to launch in Windows

### ISSUE THREAD

**Issue by DJuego** [pkulchenko/ZeroBraneStudio#720]
Thank you for Zerobrane! 

I am an absolutely newbie with lua and I want to test Zerobrane.  So i have got the "ZeroBraneStudioEduPack-1.50-win32.zip" (portable version of Zerobrane). My OS is  Windows 10 x64. 

However... :-(

![captura](https://cloud.githubusercontent.com/assets/1956212/21162228/464d17a4-c184-11e6-85b9-7a367fd6e67b.png)

I am unable to launch Zerobrane 1.5. What is wrong? Am I the only affected one? 

Thank you in advance! ;-)

DJuego

P.S: Previously, i have had the 1.40 version of Zerobrane. Perhaps a conflict with a hidden previous setting... ?

**Comment by pkulchenko** [comment]
@DJuego, thank you for the report. You'll need to re-download the package from the website as the issue was fixed yesterday (commit 53fc3f0). Please re-open if it's still not fixed.
