### ISSUE TITLE
Toolbar doesn't render properly on HiDPI display

### ISSUE THREAD

**Issue by juur** [pkulchenko/ZeroBraneStudio#721]
![capture](https://cloud.githubusercontent.com/assets/2140626/21573684/3e0700ce-cedf-11e6-8d46-db21c30d3520.JPG)

**Comment by pkulchenko** [comment]
What screen resolution and application window size do you have? If your screen size >1500, then `toolbar.iconsize` should be set to 24, which will show large icons. You can set it manually in the config as `toolbar.iconsize=24` (see https://studio.zerobrane.com/doc-general-preferences#toolbar for details).

Do you use magnification? I have a HiDPI display, but I don't see this effect on Win8.

**Comment by juur** [comment]
![capture](https://cloud.githubusercontent.com/assets/2140626/21576988/e86444a8-cf40-11e6-9ef7-579d063e5bc5.JPG)
![capture2](https://cloud.githubusercontent.com/assets/2140626/21577000/9248a37e-cf41-11e6-9179-c0e312d3b8b9.PNG)

Sorry I had been playing with iconsize, so they were even smaller!

However, I think they are still too small. 

The first image is from my HiDPI PC: Windows 10, desktop is 3840x2160. If you compare that with Windows 8.1 1366x768 (the second image), the icons go from being larger than the text height to lower than the text height. In Windows 10 I have the text size set to 200% (if this is what you mean by magnification), otherwise everything is tiny and I can't read it.

**Comment by pkulchenko** [comment]
This seems to be a wxwidgets limitation to auto-scale bitmaps (along with the lack of large bitmaps in the IDE); here are some relevant discussions about toolbar scaling and HiDPI support in general: https://groups.google.com/d/msg/wx-dev/7FA_eSmkpEc/bNWWjbJcCQAJ, https://groups.google.com/d/msg/wx-dev/lEmT4UxugWg/MDAjmfpMCgAJ, https://groups.google.com/d/msg/wx-dev/mHa_w5HxZ40/p7kudfFzAvAJ.

What you can try to do is to create `zbstudio\res\48` folder and add a PNG icon with 48x48 size (just pick one of the names from `zbstudio\res\24` folder, for example, `FILE-OPEN.png`) and set `toolbar.iconsize=48` in the config. Only one icon will be shown, but at least you will be able to check if it has the right size or not.

Also, what does running `ide:GetMainFrame():GetContentScaleFactor()` return in your case? `2.0`?

**Comment by juur** [comment]
```
ide:GetMainFrame():GetContentScaleFactor()
[string "ide:GetMainFrame():GetContentScaleFact..."]:1: wxLua: Unable to call an unknown method 'GetContentScaleFactor' on a 'wxFrame' type.
	[C]: in function '__index'
```

**Comment by juur** [comment]
I tried taking some of the 16x16 images and increasing them in size 300%:
![image](https://cloud.githubusercontent.com/assets/2140626/21579055/b879e976-cf92-11e6-8b7d-7db8d419100a.png)
Then changed my `user.lua`:
![image](https://cloud.githubusercontent.com/assets/2140626/21579057/c9be9bb4-cf92-11e6-97b7-f800120ae63d.png)
However, it seems to get worse:
![image](https://cloud.githubusercontent.com/assets/2140626/21579059/d7063c5a-cf92-11e6-99cf-b807bf15c43d.png)
Doesn't this code in gui.lua break that?
```
local function tbIconSize()
  -- use large icons by default on OSX and on large screens
  local iconsize = (tonumber(ide.config.toolbar and ide.config.toolbar.iconsize)
    or ((ide.osname == 'Macintosh' or wx.wxGetClientDisplayRect():GetWidth() >= 1500) and 24 or 16))
  if iconsize ~= 24 then iconsize = 16 end
  return iconsize
end
```

**Comment by juur** [comment]
If I edit that bit of code to say:

`if (iconsize ~= 24 and iconsize ~= 48) then iconsize = 16 end`

Then I get a sensible sized (if a little 8-bit) icon. With a teeny-tiny-nearly-unusable drop down:

![image](https://cloud.githubusercontent.com/assets/2140626/21579068/8ee1f2f6-cf93-11e6-9ae8-d713962372ed.png)

**Comment by pkulchenko** [comment]
> ide:GetMainFrame():GetContentScaleFactor()
> [string "ide:GetMainFrame():GetContentScaleFact..."]:1: wxLua: Unable to call an unknown method 'GetContentScaleFactor' on a 'wxFrame' type.

Hm, you seem to be using an old version of the IDE then; try upgrading to 1.40 or 1.50 to see if you get any different result.

> Then I get a sensible sized (if a little 8-bit) icon.

Right; you did everything correctly. If there is a set of 48x48 icons, then they can probably used in a situation like this one.

> With a teeny-tiny-nearly-unusable drop down:

Yes, the size of the dropdown is a separate issue, but you are right, it's not scaled properly with the size of the toolbar. I'll probably open a wxwidgets ticket for this.
