### ISSUE TITLE
Lua 5.3 incompatibilities

### ISSUE THREAD

**Issue by deining** [pkulchenko/ZeroBraneStudio#722]
I just came across two minor quirks, that I would like to report:

a) quick-start.lua, line 52+53

```
-- %d placeholder truncates real numbers
print(("%d"):format(1.5)) --> 1
````
b) programming lessons, lesson 13-format.lua, line 12:

`print(('A bulb rated for 2200 hours will last %d years'):format(2200/6/365))`

With lua interpreter set to 5.3, you get an error in both cases:

`bad argument #1 to 'format' (number has no integer representation)`

Thanks for eliminating this and thanks for providing such an excellent program!

**Comment by pkulchenko** [comment]
@deining, thank you for the report and the feedback! For the first error, did you mean the line with `format(1.5)` instead, as I don't get any error on the first example, but get it on the second with the Lua 5.3 interpreter shipped with the IDE?

**Comment by deining** [comment]
@pkulchenko thanks for commenting almost immediately. Yes, it is the line with `format(1.5)`, of course. I corrected my initial comment already.
