### ISSUE TITLE
In which file does ZBS remember text cursor position?

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#724]
Hello,

ZBS is good at remembering the line in which the cursor was before the app was closed. It restores cursor position on start.

Where is this stored (on Windows)? In learn-game-programming package ( https://qubodup.itch.io/startgamedev ) with ZBS as the text editor, I would like the cursor to be in line 4 on first start, below the comments, if that is possible.

It seems like it's not stored in the application folder, so I probably can't make it portable - I couldn't find edited files using http://stackoverflow.com/a/17616134/188159 - but hopefully I'm wrong?

**Comment by pkulchenko** [comment]
@qubodup, you can find the details on the file location in the [session configuration section](https://studio.zerobrane.com/doc-general-preferences#session-configuration).

You *can* make it portable, as you can specify an alternative location for the `ini` file; check the `ini` setting in the [general settings section](https://studio.zerobrane.com/doc-general-preferences#general).

You can also pass not only a file, but also line/position in the file when you are launching the IDE, so this may be an option in your case as well; I have the following description in the README file, but it should probably also be in the documentation: "If you are loading a file, you can also request the cursor to be set on a particular line or at a particular position by using `filename:<line>` and `filename:p<pos>` syntax (0.71+)."

I think this should be sufficient for what you are trying to do, but if not, feel free to re-open and continue the discussion.
