### ISSUE TITLE
Can't start remote debugging

### ISSUE THREAD

**Issue by KaiFengGame** [pkulchenko/ZeroBraneStudio#725]
file:       /.../ZeroBraneStudio/lualibs/socket.lua
line:12  local socket = require("socket.core")

i can't find core.lua in socket folder.  
i just find core.dll in /.../ZeroBraneStudio/bin/

How did it work "socket.core" To core.dll ???

thanks

**Comment by pkulchenko** [comment]
`socket.core` is mapped to `socket\core.dll` as one of the paths by `require`. What exactly is the problem? 

It's usually better to use one of the channels on the [community page](https://studio.zerobrane.com/community) page to ask questions.

**Comment by pkulchenko** [comment]
The actual core.dll file is in the `bin/clibs` folder for Lua 5.1 and in `clibs52` and `clibs53` folders for other versions.

**Comment by KaiFengGame** [comment]
thank you :)
