### ISSUE TITLE
Debug error

### ISSUE THREAD

**Issue by yuanshucong** [pkulchenko/ZeroBraneStudio#726]
I was debugging a torch helloworld on a ubuntu server and the debug won't work.

Output:
Program starting as '"/home/lab-yuan.shucong/ZeroBraneStudio/bin/linux/x64/lua" -e "io.stdout:setvbuf('no')" "/tmp/.xky3me"'.
Program 'lua' started in '/home/lab-yuan.shucong' (pid: 16144).
Program completed in 66.75 seconds (pid: 16144).

But the program runs fine.
The first time i run debug, it works fines and stops at breakpoints, but the next day it just won't work.
And i configured the torch environment in the Pereference->Setting:User, but it seems without configuring it, the program can still find torch library.

**Comment by pkulchenko** [comment]
@yuanshucong, I'm a bit confused, where is the error you refer to in the subject?

If the debugging doesn't start, make sure that you have `require('mobdebug').start()` in your script you want to debug. Also make sure that you start the debugger server in the IDE (Project | Start Debugger Server) if you "Run" the program (instead of launching it as "Debug").

If the debugging is still not working, add `debugger.verbose=true` line to the config, restart the IDE, and start the debugging. The Output window will have details of the debugging session, which you may paste here.

**Comment by yuanshucong** [comment]
@pkulchenko , thank you for reply. I am new to coding.

Firstly, I git Zerobrane on my linux home (after login). It's not remote debug, so i double is it right to launch as "Debug" instead of "Start Debugger Server"

Then i added "require('mobdebug').start()", and launch it as "Execute the current Project/f6" and "Start and continue debuging/f5"

for "Execute the current Project/F6" : it seems the program got stucked. For it could have be executed in seconds.  After about 1min
It Outputs:
Program starting as '"/home/lab-yuan.shucong/torch/install/bin/th" "/home/lab-yuan.shucong/untitled.lua" '.
Program 'th' started in '/home/lab-yuan.shucong' (pid: 3845).
/home/lab-yuan.shucong/torch/install/bin/luajit: /home/lab-yuan.shucong/untitled.lua:3: Debugger connection closed
stack traceback:
	[C]: in function 'error'
	...an.shucong/ZeroBraneStudio/lualibs/mobdebug/mobdebug.lua:681: in function '__index'
	/home/lab-yuan.shucong/untitled.lua:3: in main chunk
	[C]: in function 'dofile'
	...cong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Program completed in 70.89 seconds (pid: 3845).


for "Start and continue debuging/f5",it makes no difference, after some minutes
It outputs:
Program starting as '"/home/lab-yuan.shucong/torch/install/bin/th" "/tmp/.X7yfPY" '.
Program 'th' started in '/home/lab-yuan.shucong' (pid: 42174).
Program completed in 24.25 seconds (pid: 42174).

And by the way,where is config? Is it (Edit | Pereference | Settings:user?)

**Comment by yuanshucong** [comment]
@pkulchenko It seems it's the problem with my machine. I was writing the above comments and suddenly Chrome is gone. After i reopen it  It seems the machine load back to some previous state. Now everything works fine.
But i still wonder where is the config.

**Comment by pkulchenko** [comment]
> Now everything works fine.

Sounds good; thank you for the update.

> i still wonder where is the config.

Yes, it's accessed with `Edit | Preferences | Settings:User`
