### ISSUE TITLE
Segmentation fault when running with lua 5.2

### ISSUE THREAD

**Issue by d9k** [pkulchenko/ZeroBraneStudio#727]
Hello!
Ubuntu 16.04 x64 system.

When I try to launch Zerobrane Studio with lua 5.2 (command `bin/linux/x64/lua52 src/main.lua` on the cloned repository directory). I see `segmentation fault (core dumped)` error. Do ZeroBraneStudio compatible with lua 5.2 interpreter?

Also tried to empty out `~/.zbstudio/user.lua` config, still segfault.
How can I investigate the problem?

**Comment by pkulchenko** [comment]
You can run lua52 **from** ZeroBrane Studio, but you can't run ZeroBrane Studio itself with Lua52 as some of the required modules (like wxlua) only run with Lua51. Why would you want to run the IDE itself using Lua52?

**Comment by d9k** [comment]
@pkulchenko, thanks for the quick response!
1) I would like to see lua 5.2 at the local console
2) Auto-completion for lua 5.2 modules members doesn't work (but debug of lua 5.2 code works if I choose `Project->Lua interpreter->Lua 5.2`).

Sorry if I misunderstand something, I'm new to Zerobrane Studio and lua.

**Comment by pkulchenko** [comment]
> Auto-completion for lua 5.2 modules members doesn't work 

Which of the members are missing?

> but debug of lua 5.2 code works if I choose Project->Lua interpreter->Lua 5.2

Right, that's how it's supposed to work.

> I would like to see lua 5.2 at the "Local console"

Yes, there are plans to handle it as described in #490 and related tickets, but this is not available yet.

A quick workaround is to start a debugging session using Lua 5.2 interpreter (like you do) and they use Remote console to run your Lua 5.2 commands.

**Comment by d9k** [comment]
> Which of the members are missing?
For example, I have `lfs` luarock installed for lua 5.2.

When I type in

```
require 'lfs'
lfs.
```

autocompletion doesn't show up.
autocompletion
autocompletion

**Comment by pkulchenko** [comment]
> autocompletion for lfs.* functions doesn't show up.

Yes, it's not going to work unless someone provides [API descriptions](https://studio.zerobrane.com/doc-api-auto-complete) for lfs (and other 3-rd party libraries).

It's not related to Lua 5.2 or any other interpreter selected as the autocomplete descriptions are version-agnostic.
