### ISSUE TITLE
Pasting text freezes IDE (MacOS with DocumentMap)

### ISSUE THREAD

**Issue by CetoBasilius** [pkulchenko/ZeroBraneStudio#728]
I don't know what is causing it as it seems pretty random, and cannot replicate it all the time. Today it happened twice in a row when pasting --------------------------------------------- on a line without text. It has already happened more than 10 times in this week. Always when pasting stuff. 

The IDE just hangs unresponsive and the cursor never stops spinning. I have to force close it and restart it.

I am using macOS Sierra 10.12.2 (16C67), latest ZeroBrane master commit, fe7993e.

[Here is my configuration](https://gist.github.com/CetoBasilius/9c0c6489bf17898bc753b54ef6aa6eed)

**Comment by pkulchenko** [comment]
@CetoBasilius, thank you for the report. I tested on my MacBook (using your config), but haven't been able to reproduce unfortunately. I'm still running 10.10.5 and will try to find a newer machine to test on (as I don't plan an upgrade at this moment).

The context of the file in which you are pasting may matter; if it happens on more or less the same file, can you include the content of the file (feel free to email it to me or email me a private link to it).

Does it happen when you paste that line with dashes? Does it freeze on any other text?

You may try running [dtruss](https://opensourcehacker.com/2011/12/02/osx-strace-equivalent-dtruss-seeing-inside-applications-what-they-do-and-why-they-hang/); maybe it will help to find what it's hanging on.

**Comment by pkulchenko** [comment]
@CetoBasilius, any additional details? Does this still happen? I have not been able to reproduce and am interested in any additional information you may provide (or the content of the file it happens on)...

**Comment by CetoBasilius** [comment]
I've managed to reproduce it. It does not happen all the time but so far out of 30 tries i got it to hang around 20 times. Here is the file it crashes on:

https://gist.github.com/CetoBasilius/72ed8e6d1f35417388776ab5e5e7fc0d

Now, the way i managed to reproduce it is not the way it always happens.

Steps to reproduce 1:
1) Open welder.lua and another file
3) Close the IDE
4) Open the IDE
5) Paste the dashed line on empty line (For example line 50)

Steps to reproduce 2:
1) Switch from another file to welder.lua (Using the tabs)
2) Paste the dashed line on empty line (For example line 50)

Steps to reproduce 3:
1) Save welder.lua without changes
2) Go to another file tab
3) Go back to welder.lua
4) Paste the dashed line on empty line (For example line 50)

Steps to reproduce 4:
1) Open welder.lua
2) Paste dashed line on empty line
3) if it does not crash, press undo (cmd + Z) multiple times

Sometimes it is as easy as opening up the IDE and pressing cmd+v (paste)

I tried using dtruss but it seems to only output info about the .sh, which i imagine is useless.

I also made a video of the bug in action: https://www.youtube.com/watch?v=IrIEMlp0L_c
It does not show on the video, but my mouse pointer was actually the rainbow rolling circle thing.

**Comment by pkulchenko** [comment]
@CetoBasilius, very interesting; thank you for the detailed update! I do see this happening on the video and will try to reproduce locally to see what's going on.

Do you see anything useful from the stack trace in the crash report? I can provide a debug version of the wx library as it's usually where most of the stack trace is and it can have critical details.

**Comment by pkulchenko** [comment]
@CetoBasilius, try as I may, but I haven't been able to reproduce this even a single time. I also asked another user with access to MacOS Sierra, but no success there either (and we tested it on the file you provided, using the same config, and following your instructions).

Does this happen with any other text you are pasting (that doesn't have `-`)? What plugins do you have installed? Maybe there is something in those plugins that does analysis on the pasted text, which runs into some corner case in regex processing?

In terms of dtruss, you need to run it on the binary itself, not on the shell script. You can run the IDE using the following command (assuming you are running it from a cloned copy):

```sh
export DYLD_LIBRARY_PATH=`pwd`/bin; bin/lua src/main.lua
```

To add dtruss, just modify the line that launches `bin/lua` and it should work.

**Comment by pkulchenko** [comment]
@CetoBasilius, any details on the plugins you are using? I'm close to making a release and would prefer to know what's causing this issue if we can get to the bottom of it.

**Comment by riidom** [comment]
I have a similar (maybe same) issue (Ubuntu 17.04), after tab-switch and pasting a few lines of code it freezes, but doesn't crash, it gets responsive after ~5 seconds.
I am pretty sure one of the plugins is causing that. Renamed my packages folder so ZBS wouldn't find any of them, and tried to reproduce a few times - no success.
I try to narrow down the list, but maybe @CetoBasilius you can check the list of plugins I have activated and see which ones you use as well, overlaps should be hot candidates then.

* cloneview.lua
* editorautofocusbymouse.lua
* TODO.lua
* documentmap.lua
* filetreeoneclick.lua
* uniquetabname.lua

**Comment by pkulchenko** [comment]
@riidom, does this mean that it's documentmap causing this issue, per your update? What version of the plugin are you using?

**Comment by riidom** [comment]
It is version 0.30

**Comment by pkulchenko** [comment]
Yes, it's the latest one. @CetoBasilius, do you also have documentmap plugin installed by any chance?

@riidom, can you try the following patch for the plugin and look at the numbers reported when the hang happens?

```diff
diff --git a/documentmap.lua b/documentmap.lua
index 99fa49e..36231fa 100644
--- a/documentmap.lua
+++ b/documentmap.lua
@@ -226,7 +226,9 @@ return {
   onEditorPainted = function(self, editor)
     if editormap and editor == editorlinked and needupdate then
       needupdate = false
+local s = os.clock();
       sync(editorlinked, editormap)
+ide:Print("DM editorPainted/sync", os.clock(), os.clock()-s)
     end
   end,
 }
```

Keep in mind that the output can be quite noisy as it will be reported on scrolling and other events, so try to minimize actions after pasting.

**Comment by pkulchenko** [comment]
@riidom, @CetoBasilius, can you check if the same issue happens with the new binary files (the link is at the top of #999 ticket)? Thank you.

**Comment by riidom** [comment]
@pkulchenko downloaded the linked binary, added document map plugin, pasted some things.. also the line of "-------" mentioned in the first post here.. no crash at all
Though I'm on Kubuntu not MacOs.

**Comment by pkulchenko** [comment]
Sounds good; thank you for checking!

**Comment by pkulchenko** [comment]
Closing; please re-open if the issue happens again.
