### ISSUE TITLE
Please add support llthreads

### ISSUE THREAD

**Issue by Mirocow** [pkulchenko/ZeroBraneStudio#733]
subject: https://github.com/moteus/lua-llthreads2

**Comment by pkulchenko** [comment]
@Mirocow, you should be able to use llthread library with any application you are running from ZBS. Did you run into any specific issues?

**Comment by pkulchenko** [comment]
@Mirocow, feel free to re-open if you have specific details on what doesn't work or what you mean by "adding support".
