### ISSUE TITLE
String containing \255 breaks watch display

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#734]
If a variable is in the watch window and is a string containing a `\255` character, the watch window breaks - it doesn't display the variable name nor value anymore. If such a value is part of a table that is in the watch window, the table's name fails to display, but the value is displayed correctly. When attempting to edit the watched expression, the variable name displays properly in the edit-box and can be changed without problems. This behavior seems unrelated to Lua interpreter (observed both in `Lua` and `Cuberite - Debug` interpreters). Tested only on Windows 7 Pro and 8.1 Pro N, both affected.

To reproduce, debug this code:
```lua
local testVal = "\255"
local testVal2 = { testKey = "\255" }
```
Add `testVal` and `testVal2` as watched expressions.

In the screenshot below, the first watch is for `testVal` and the second is for `testVal2`:
![watch_255](https://cloud.githubusercontent.com/assets/4388386/22882281/9be31ae2-f1ea-11e6-8d97-bfbb4914df47.png)

**Comment by madmaxoft** [comment]
Note that the Stack window seems unaffected by this, it shows both values correctly.

**Comment by pkulchenko** [comment]
@madmaxoft, thank you for the report. Should be fixed now. Also fixed copying values with invalid UTF-8 sequences.
