### ISSUE TITLE
running code caused laptop to heat up

### ISSUE THREAD

**Issue by yehudaclinton** [pkulchenko/ZeroBraneStudio#735]
This is the first time using zerobrane i'd like to thank you guys.
So i clicked "run as scratchpad" which ran my simple program. But then when started adding a loop my laptop started getting really hot with the fan blowing full speed. Yes i didnt realize scratchpad makes it run live which caused it to loop forever until i type "end". I would suggest perhaps there should be auto-stopper as soon as the user starts adding text to code. or maybe a warning somewhere

**Comment by pkulchenko** [comment]
@yehudaclinton, yes, it will continue running your code with every change (with a small delay). You can pause that execution (using the pause button on the toolbar or menu `Project | Break`), make your changes, and then continue by using continue button or menu `Project | Continue` / `F5`. This gives you the flexibility you need while editing your code.

Another option is to make a small syntax error (as the code won't be executed if there is a syntax error) and then "fix" it after you are done with the changes to let the code to be applied and executed.

**Comment by yehudaclinton** [comment]
thank you so much
plan on donating in the future
