### ISSUE TITLE
Sort tables in Watch window

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#738]
When a table is displayed in the Watch window, it would be great if the members were alpha-sorted. Currently, they all come in a random (Lua-implementation-specific, I guess) order, so searching for one value is rather cumbersome.

**Comment by pkulchenko** [comment]
@madmaxoft, I explored this earlier with Stack updates I'm working on and the results look utterly confusing: non-numerical keys are likely to be shown first and numerical keys are shown out of order (as they don't have their index for readability and are sorted based on their values). In any case it doesn't look (at least not in the general case).

**Comment by pkulchenko** [comment]
If you want to experiment with it, here is the diff (the line numbers may be off, but you get the idea on where to add it):

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index 58b393c..a010aec 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -1541,6 +1541,7 @@ local function debuggerCreateWatchWindow()
         num = num + 1
         if num > maxnum then break end
       end
+      watchCtrl:SortChildren(item_id)
       watchCtrl:Thaw()
       return true
     end)
```
