### ISSUE TITLE
Change the default debug shortcut keys

### ISSUE THREAD

**Issue by senisioi** [pkulchenko/ZeroBraneStudio#741]
I would suggest to change the default debugging shortcuts to something similar to other IDEs (e.g. [eclipse](https://shortcutworld.com/en/Eclipse/win/all#link_11) or [visualstudio](https://msdn.microsoft.com/en-us/library/aa239052(v=vs.60).aspx)) 

I know this is customizable, but having the default step over with Shift + F10 requires pressing two keys for one step and it also collides with the Ubuntu Shift F10 key which opens the context menu by default.

**Comment by pkulchenko** [comment]
I generally don't mind, but (1) it's difficult to agree on what works on all supported platforms (for example, OSX uses F11 for system-related shortcuts, similar to Shift-F10 on Ubuntu), (2) there is already some consistency with `step` commands (they are all related to F10), (3) it's relatively easy to reassign, (4) if it's changed by default on only Linux/Ubuntu, it needs to be documented as such. I'd be more inclined to include `eclipse` and `VS` shortcut files (similar to already included `cfg/xcode-keys.lua`) to setup keys for those familiar with other environments. This way users can simply add `include "eclipse"` to the config to get the keys remapped to familiar combinations.

If you are interested, you can check xcode-keys and provide similar shortcuts for other IDEs. If not, I'd close it for now.

**Comment by senisioi** [comment]
Good point, I will create a pull request with an eclipse shortcut configuration.

**Comment by pkulchenko** [comment]
Merged #742. Closing...

**Comment by cxw42** [comment]
For anyone else who finds this issue, to make Shift+F10 usable in the debugger, apply the fixes from:

- [here](https://bbs.archlinux.org/viewtopic.php?pid=1077127#p1077127) for GTK2, and
- [here (same thread)](https://bbs.archlinux.org/viewtopic.php?pid=1017546#p1017546) for GTK3.

This worked for me on Lubuntu 20.04.

**Comment by pkulchenko** [comment]
@cxw42, thank you for the hint! Copying the solutions here in case the link disappears:

For gtk-2 apps add this in ~/.gtkrc-2.0

```
binding "NoKeyboardNavigation" {
        unbind "<shift>F10"
}
class * binding "NoKeyboardNavigation"
```

For gtk-3 apps like gnome-terminal and nautilus I created a new file: ~/.config/gtk-3.0/gtk.css

```
@binding-set NoKeyboardNavigation {
	unbind "<shift>F10"
}

* {
	gtk-key-bindings: NoKeyboardNavigation
}
```

You have to close _all_ terminal windows for the changes to be in effect.
