### ISSUE TITLE
macOS Sierra run zbstudio.sh error

### ISSUE THREAD

**Issue by Relvin** [pkulchenko/ZeroBraneStudio#743]
My computer version is 10.12.3,I run "sh zbstudio.sh" error; Error message is 
"
sh zbstudio.sh 
LSOpenURLsWithRole() failed with error -10810 for the file /Users/relvin/Downloads/ZeroBraneStudio-1.40/zbstudio/ZeroBraneStudio.app.
"

**Comment by pkulchenko** [comment]
@Relvin, thank you for the report; can you try running the following command:

```
(cd /Users/relvin/Downloads/ZeroBraneStudio-1.40; DYLD_LIBRARY_PATH=/Users/relvin/Downloads/ZeroBraneStudio-1.40/bin bin/lua src/main.lua)
```

It may provide more details about the error to the standard output.

Also, did you install from the .dmg package you downloaded from the website or in some other way? Can you try on v1.50 (after trying the suggestion above as I'm still interested in why it's failing)?

**Comment by pkulchenko** [comment]
@Relvin, do you have any update based on my suggestions?

**Comment by pkulchenko** [comment]
@Relvin, I think I have a fix for this issue. I don't have MacOS Sierra to test on, but can you try the following patch:

```diff
diff --git a/zbstudio.sh b/zbstudio.sh
index cfab16d..4a0bec8 100755
--- a/zbstudio.sh
+++ b/zbstudio.sh
@@ -4,7 +4,7 @@
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 if [[ $(uname) == 'Darwin' ]]; then
-  (cd "$DIR"; open zbstudio/ZeroBraneStudio.app --args "$@")
+  (cd "$DIR"; zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio "$@")
 else
   case "$(uname -m)" in
 	x86_64) ARCH=x64;;
diff --git a/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio b/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio
index 230655b..a65110c 100755
--- a/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio
+++ b/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ZBS_PATH=${0%/*/*}
-if [ ! -d $ZBS_PATH ]; then ZBS_PATH=${PWD%/*}; fi
+if [[ "$ZBS_PATH" != /* ]]; then ZBS_PATH="${PWD%}/$ZBS_PATH"; fi
 ZBS_BIN="$ZBS_PATH/ZeroBraneStudio/bin"
 if [[ ! -e "$ZBS_BIN/libedit.3.dylib" && ! -e /usr/lib/libedit.3.dylib ]]
 then ln -s /usr/lib/libedit.2.dylib "$ZBS_BIN/libedit.3.dylib"; fi
```

Also see the discussion about `error -10810` in #729.

**Comment by pkulchenko** [comment]
@Relvin, I pushed the fix for it. You can clone or download a new version and give it a try.

**Comment by fsinisi90** [comment]
Hi @pkulchenko! Thanks for this amazing app.

I'm having the same issue described here by @Relvin, I'm getting the error `LSOpenURLsWithRole() failed with error -10810 for the file /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app` when trying to execute the file `zbstudio.sh` in macOS Mojave 10.14.4.

I've tried making the file executable but it didn't work:

```
sudo chmod +x zbstudio/ZeroBraneStudio.app
sudo chmod +x zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio
```

Any idea of what else could I try? Many thanks in advance.

**Comment by pkulchenko** [comment]
@fsinisi90, can you try the following command to see if it works:

```sh
(cd /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio/bin bin/lua src/main.lua)
```

I don't have that version of macOS to try on, but will see if I can get access to one to test...

**Comment by fsinisi90** [comment]
I've changed the first path to `/Users/MyUser/HyStudio` because it wasn't finding bin/lua. Now I'm getting this error:

```
MacBook-Pro:HyStudio Vero$ (cd /Users/MyUser/HyStudio; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio/bin bin/lua src/main.lua)
bin/lua: line 1: lua.app/Contents/MacOS/lua: No such file or directory
Saving session...
...saving history...truncating history files...
...completed.
```

**Comment by fsinisi90** [comment]
I've changed the first path to `/Users/MyUser/HyStudio` because it wasn't finding bin/lua. Now I'm getting this error:

```
MacBook-Pro: $ (cd /Users/MyUser/HyStudio; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio/bin bin/lua src/main.lua)
bin/lua: line 1: lua.app/Contents/MacOS/lua: No such file or directory
Saving session...
...saving history...truncating history files...
...completed.
```

**Comment by pkulchenko** [comment]
Hm, I don't have my Mac at the moment, but try this then:

```
(cd /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/ZeroBraneStudio; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin bin/lua src/main.lua)
```

**Comment by fsinisi90** [comment]
I've tried in three different ways with the same result:

```
(cd /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/ZeroBraneStudio; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin bin/lua src/main.lua)
-bash: cd: /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/ZeroBraneStudio: Not a directory
bin/lua: line 1: lua.app/Contents/MacOS/lua: No such file or directory

(cd /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio/bin bin/lua src/main.lua)
-bash: cd: /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio: Not a directory
bin/lua: line 1: lua.app/Contents/MacOS/lua: No such file or directory

(cd /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app; DYLD_LIBRARY_PATH=/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio/bin bin/lua src/main.lua)
-bash: bin/lua: No such file or directory
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by pkulchenko** [comment]
@fsinisi90, strange. Can you post the result of `ls -l -R /Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents/`?

**Comment by fsinisi90** [comment]
Yes, of course:

```
-rw-r--r--  1 MyUser staff  3762 Apr 17 17:13 Info.plist
drwxr-xr-x  3 MyUser staff    96 Apr 17 17:13 MacOS
drwxr-xr-x  3 MyUser staff    96 Apr 17 17:13 Resources
-rw-r--r--  1 MyUser staff     8 Apr 17 17:13 ZeroBraneStudio

/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents//MacOS:
total 8
-rwxr-xr-x  1 MyUser staff  412 Apr 17 17:13 ZeroBraneStudio

/Users/MyUser/HyStudio/zbstudio/ZeroBraneStudio.app/Contents//Resources:
total 56
-rw-r--r--  1 MyUser staff  26935 Apr 17 17:13 zbstudio.icns
```

**Comment by pkulchenko** [comment]
@fsinisi90, this doesn't look right, as ZeroBraneStudio should be a folder and in your case it's a file. How did you install the application? Did you get it copied from the installation package (provided as .dmg file)?

**Comment by fsinisi90** [comment]
No, as I've said in my first comment I'm trying to execute ZeroBrane by cloning the repository, without the .dmg file (I've made some changes to the app, that's why).

**Comment by pkulchenko** [comment]
Ok, that would explain it. Can you try executing it from the "original" clone of the repository? It does work for me, so maybe the changes you made somehow affected that part of the setup?

**Comment by fsinisi90** [comment]
Thanks for the suggestion, that wasn't exactly the problem but it helped me to look into the right direction. 

I've found that, even with **exactly the same files**, it's working if I clone the project from a public repository and not from a private repo. I'm still not exactly sure why, but it seems like some crazy Mac permissions issue. After cloning from a private repo, when I try to execute `./zbstudio.sh` it gives me "permission denied". Then only after running `sudo chmod -R 755 .` inside the main folder, it gives me the `LSOpenURLsWithRole() failed with error -10810` error.

Any idea of why could this happen?

**Comment by pkulchenko** [comment]
No idea, but what do you mean by cloning from a private repo? You mean your own one that you cloned from ZBS repo?

So, does this mean that it runs correctly when cloned from a private repository, but fails with one of those two errors from the "private" one?

**Comment by fsinisi90** [comment]
I have a public fork, that one runs fine. I've also created a private repo, with exactly the same files. When I clone the private repo it throws the error.

**Comment by fsinisi90** [comment]
Well, seems like all began when copied the files in Windows... I'm still not exactly sure why, but it's solved now. Thanks for the help!
