### ISSUE TITLE
Mixed case file name on autoactivated files shown as lower case (Windows)

### ISSUE THREAD

**Issue by freestylealan** [pkulchenko/ZeroBraneStudio#744]
when editor.autoactivate = true and you are stepping through debug, automatically opened files with mixed case names are shown on the tab as all lower case.

Alan Barker.

alan.barker@freestyleiot.com

**Comment by pkulchenko** [comment]
Alan, can you provide some more details? How exactly the names look like and how do you load the files? The file names are indeed converted to lowercase in the debugger on Windows (to make breakpoints work regardless of the spelling), but it should have no effect on the names of the files loaded in the IDE.

In my case, if I have `D:\foo\Bar.lua` and try to do `LoadFile("D:\fOO\bAR.lua")`, it is loaded with the tab named `Bar.lua` (as it's normalized to the actual file name in the file system). This is the same method that is used when the files are activated (at least on Windows). I'm running this on Win8, but it should work on other Windows systems as well.

**Comment by freestylealan** [comment]
Hi Paul,

You’re quick!
I see I didn’t provide enough info, and I should know better.  I didn’t want to bother you with what is a small thing, but here are more details.

Below is a screenshot of the Window, running on Win7 and with ZBS 1.50.

I am debugging, and have stepped through code which started in a file called device.lua, then into FragmentedMessageMgr.lua, and then into fragmentedMessage.lua

As you can see below, the tabs show all in lower case.  My instinctive concern was mainly if debug is stopped and the file modified and saved, it might create a new file.

I have the following in system settings:

--[[--
  Use this file to specify **System** preferences.
  Review [examples](+C:\Users\barkera\Downloads\ZeroBraneStudio\cfg\user-sample.lua) or check [online documentation](http://studio.zerobrane.com/documentation.html) for details.
--]]--
staticanalyzer.infervalue = true
editor.autoactivate = true -- for remote debugging
--debugger.verbose=true



[cid:image001.png@01D2935C.9B8EFF80]

**Comment by pkulchenko** [comment]
The image didn't go through (probably because you emailed it). I follow the same scenario and can't reproduce the issue; maybe it's different on Win7?

Can you run the following from the Local console:

```lua
local f = wx.wxFileName([[d:/full/path/to/existing-file-with-wrong-capitalization.lua]]); f:Normalize(); return f:GetFullPath()
```

If that doesn't work, can you try `wx.wxFileName([[d:/full/path/to/existing-file-with-wrong-capitalization.lua]]):GetLongPath()` instead? Please make sure you use the existing file name, otherwise you just get the same string back.

**Comment by freestylealan** [comment]
Hi Paul,

Tried local console with and without the capitalization.  Not sure what the result means:

local f = wx.wxFileName([[C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fragmentedmessage.lua]]); f:Normalize(); return f:GetFullPath()
C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fragmentedmessage.lua
local f = wx.wxFileName([[C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fragmentedMessage.lua]]); f:Normalize(); return f:GetFullPath()
C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fragmentedMessage.lua

Have also attached jpg of screenshot.

**Comment by pkulchenko** [comment]
Alan,

It seems like you just get the same string back, regardless of how it's in the file system. Can you run the following command: `wx.wxFileName([[C:\Users\barkera\documents\projects\smartgit\APL-LMT-G01\Applets\SRC\fRAGmentedmessage.lua]]):GetLongPath()`?

> Have also attached jpg of screenshot.

Github doesn't seem to parse images attached to the email; you may need to use their web interface to attach the image, but I think I know what you are trying to show ;).

**Comment by freestylealan** [comment]
local f = wx.wxFileName([[C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fRAGmentedmessage.lua]]); f:Normalize(); return f:GetFullPath()
C:\Users\barkera\Documents\Projects\SmartGit\APL-LMT-G01\Applets\src\fRAGmentedmessage.lua

**Comment by freestylealan** [comment]
![zbs_filename](https://cloud.githubusercontent.com/assets/1581991/23491717/178bb0ac-ff54-11e6-87ec-1ed069cc6f38.jpg)

**Comment by freestylealan** [comment]
Sorry closed accidentally

**Comment by pkulchenko** [comment]
Can you also try this other command: `wx.wxFileName([[C:\Users\barkera\documents\projects\smartgit\APL-LMT-G01\Applets\SRC\fRAGmentedmessage.lua]]):GetLongPath()`

**Comment by freestylealan** [comment]
wx.wxFileName([[C:\Users\barkera\documents\projects\smartgit\APL-LMT-G01\Applets\SRC\fRAGmentedmessage.lua]]):GetLongPath()
"C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\fRAGmentedmessage.lua"

**Comment by pkulchenko** [comment]
So it seems like the nomalization on Win7 just doesn't do anything. I'll try to find Win7 machine to see if I can find a workaround, but it does work on newer Windows versions, so not sure how much time I want to spend on this.

Can you also run the following: `FileSysGetRecursive([[C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\]])`? It should give you a list of names as a table and I'm interested if they have proper capitalization or not.

**Comment by pkulchenko** [comment]
Actually, need to remove double slashes: ``FileSysGetRecursive([[C:\Users\barkera\documents\Projects\SmartGit\APL-LMT-G01\Applets\src\]])`

**Comment by freestylealan** [comment]
Fair enough.  It’s not a big deal.

FileSysGetRecursive([[C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\]])
{"C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\defines.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\device.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\deviceMgr.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\fragmentedMessage.lua",
"C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\FragmentedMessageMgr.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\loradef.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\lorautils.lua", "C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\main.lua",
"C:\\\\Users\\\\barkera\\\\documents\\\\Projects\\\\SmartGit\\\\APL-LMT-G01\\\\Applets\\\\src\\\\responses.lua"} --[[table: 0x069b1fc0]]

**Comment by freestylealan** [comment]
Yeah, sorry, in the middle of something.

FileSysGetRecursive([[C:\Users\barkera\documents\Projects\SmartGit\APL-LMT-G01\Applets\src]])
{"C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\defines.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\device.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\deviceMgr.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\fragmentedMessage.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\FragmentedMessageMgr.lua",
"C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\loradef.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\lorautils.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\main.lua", "C:\\Users\\barkera\\documents\\Projects\\SmartGit\\APL-LMT-G01\\Applets\\src\\responses.lua"} --[[table: 0x033ad260]]

**Comment by pkulchenko** [comment]
Ok; good. These seem to be a properly capitalized names, so I might be able to come up with a workaround.

**Comment by freestylealan** [comment]
Cool, thanks!

**Comment by pkulchenko** [comment]
@freestylealan, can you apply the following patch to see if this fixes the issue for you:

```diff
diff --git a/src/editor/commands.lua b/src/editor/commands.lua
index 7d94328..4654571 100644
--- a/src/editor/commands.lua
+++ b/src/editor/commands.lua
@@ -41,13 +41,18 @@ end
 
 function LoadFile(filePath, editor, file_must_exist, skipselection)
   filePath = filePath:gsub("%s+$","")
-  filePath = wx.wxFileName(filePath)
-  filePath:Normalize() -- make it absolute and remove all .. and . if possible
-  filePath = filePath:GetFullPath()
 
   -- if the file name is empty or is a directory, don't do anything
   if filePath == '' or wx.wxDirExists(filePath) then return nil end
 
+  filePath = FileNormalizePath(filePath)
+  -- on some Windows versions, normalization doesn't return "original" file name,
+  -- so detect that and use LongPath instead
+  if ide.osname == "Windows" and wx.wxFileExists(filePath)
+  and FileNormalizePath(filePath:upper()) ~= FileNormalizePath(filePath:lower()) then
+    filePath = FileGetLongPath(filePath)
+  end
+
   -- prevent files from being reopened again
   if (not editor) then
     local doc = ide:FindDocument(filePath)
diff --git a/src/util.lua b/src/util.lua
index 4dea31d..fa79a04 100644
--- a/src/util.lua
+++ b/src/util.lua
@@ -281,6 +281,34 @@ function MergeFullPath(p, f)
     or nil)
 end
 
+function FileNormalizePath(path)
+  local filePath = wx.wxFileName(path)
+  filePath:Normalize()
+  filePath:SetVolume(filePath:GetVolume():upper())
+  return filePath:GetFullPath()
+end
+
+function FileGetLongPath(path)
+  local fn = wx.wxFileName(path)
+  local vol = fn:GetVolume():upper()
+  local volsep = wx.wxFileName.GetVolumeSeparator(vol:byte()-("A"):byte()+1)
+  local sep = string.char(wx.wxFileName.GetPathSeparator())
+  local dir = wx.wxDir()
+  local dirs = fn:GetDirs()
+  table.insert(dirs, fn:GetFullName())
+  local normalized = vol..volsep
+  while #dirs > 0 do
+    dir:Open(normalized)
+    if not dir:IsOpened() then return path end
+    local p = table.remove(dirs, 1)
+    local ok, segment = dir:GetFirst(p)
+    if not ok then return path end
+    normalized = normalized..sep..segment
+    dir:Close()
+  end
+  return normalized
+end
+
 function CreateFullPath(path)
   local ok = wx.wxFileName.Mkdir(path, tonumber(755,8), wx.wxPATH_MKDIR_FULL)
   return ok, not ok and wx.wxSysErrorMsg() or nil
```

**Comment by freestylealan** [comment]
All seems good except for the last line of FileGetLongPath:

dir:Close()

It crashes on that line, but works ok if I comment it out.

The wxDir doc does not list a Close method

![zbs_crash](https://cloud.githubusercontent.com/assets/1581991/23883776/55c21f74-08bd-11e7-9a4b-a5ad0d41a070.jpg)

I am running ZBS 1.50

**Comment by freestylealan** [comment]
Any specific tests you would like me to do ?  

I have just opened a few mixed case files with the wxDir:Close() commented out and checked the tabs

**Comment by freestylealan** [comment]
Hi Paul, here is the help/about on my Win7 install.  Maybe I have a path to an older wxLua;  I'll check.

![zbs_version](https://cloud.githubusercontent.com/assets/1581991/23884446/d100cfc0-08c0-11e7-914b-2f5ccd62a3dc.jpg)

wx.wxDir():Close() 
[string "wx.wxDir():Close() "]:1: wxLua: Unable to call an unknown method 'Close' on a 'wxDir' type.
	[C]: in function '__index'

**Comment by pkulchenko** [comment]
Somehow you have wxwidgets 2.9.5, but it should be wxwidgets 3.1.1. Check if you have bin/wx.dll and delete it. You might have installed 1.50 into the same folder where you had an older version of ZBS; the newer version has a new location for the dll, which is what created that conflict in your case.

**Comment by pkulchenko** [comment]
The new location is `bin\clibs\wx.dll`.

**Comment by freestylealan** [comment]
Yup, you are spot on.  I deleted the bin/wx and reinstated that line and it's fine, and I did indeed update ZBS that way.  My bad.  You still want me to use the modified code ?

**Comment by pkulchenko** [comment]
Yes, as this is what I'd commit (as I'd still like it to work with older version of wxlua/wxwidgets as well). Thanks!

**Comment by freestylealan** [comment]
Ok, no worries, will do.  Got a meeting, might not be able to test before tomorrow AM our time.

**Comment by pkulchenko** [comment]
@freestylealan, I pushed the changes that should fix this issue. The fix is slightly different from what I shown earlier, but the main idea is the same. Let me know how it works for you.

**Comment by freestylealan** [comment]
That's cool Paul, sorry for the delay;  just finished a day and a half of Agile training.  I'll get onto it soon.
