### ISSUE TITLE
what libraries need to be recompiled to make zbs work on arm?

### ISSUE THREAD

**Issue by WarpspeedSCP** [pkulchenko/ZeroBraneStudio#745]
Can you please tell me what libraries I would need to compile to replace the bundled x86 libraries with arm ones?

To clarify, I'm using ubuntu in a chroot env on my phone, which has an arm64 cpu. I want to make sure that zbs uses 64 bit binaries, hence the question.

**Comment by pkulchenko** [comment]
@WarpspeedSCP, you only need to recompile `wxlua` and `luasocket` libraries (the rest are optional unless you use some other components, like lexlpeg, lfs, and others).

If you have the development environment setup, you can run `(cd build; ./build-linux.sh lua wxwidgets wxlua luasocket)`, which should compile all these modules you need for your platform.

You can check #382 and #599 for related discussions/details.

**Comment by WarpspeedSCP** [comment]
Much appreciated.

**Comment by WarpspeedSCP** [comment]
in case anyone has trouble with wxwidgets on aarch64, just get the latest versions of config.sub and config.guess and put them in the wxwidgets folder. it should build then.

**Comment by pkulchenko** [comment]
@WarpspeedSCP, thank you for the update; so it all worked with the current setup after you built it? Or did you need to do some other updates similar to what was done for armhf/armv7l?

Just in case someone is searching for this using keywords, aarch64 is also known as ARMv8 or ARM64.

**Comment by WarpspeedSCP** [comment]
Also, wxlua needed Lua to be compiled with -fPIC; I had added 4 lines to build-linux.sh to add aarch64 support - 


    aarch64)
		FPIC="-fPIC"
		ARCH="aarch64"
		;;

This allowed everything to build successfully. 
I also needed to make changes to main.lua and zbstudio.sh to reflect the arch change. 

However, right now, when I run zbs, this is what happens-

    android@localhost:~/Desktop/ZeroBraneStudio-master$ bin/linux/aarch64/lua: error loading
    module 'wx' from file 'bin/linux/aarch64/clibs/libwx.so':
	    bin/linux/aarch64/clibs/libwx.so: undefined symbol: wx_png_init_filter_functions_neon
    stack traceback:
    	[C]: ?
    	[C]: in function 'require'
    	src/main.lua:35: in main chunk
    	[C]: ?

 I stopped working on it after that, do you have any ideas for fixing this?

**Comment by pkulchenko** [comment]
@WarpspeedSCP, according to [this ticket](https://github.com/davisking/dlib/issues/262), it seems like you may need to have `contrib/arm-neon` folder from libpng, but it's not packaged with libpng that ships with wxwidgets, so you may need to copy it manually (just make sure it's from the same version).

I'm also interested in your main.lua and zbstudio.sh changes.

**Comment by WarpspeedSCP** [comment]
Well, all I did was add an entry into the archtype table for aarch64 in main.lua, and also a case for aarch64 in zbstudio.sh.

**Comment by WarpspeedSCP** [comment]
Well, just adding aarch64 to the archtype table in main.lua and adding a case for aarch64 in zbstudio.sh is enough.

**Comment by WarpspeedSCP** [comment]
I'm rebuilding it from scratch, will it work if I copy over the libpng sources directly into the build/wxWidgets/src/png directory? 

I have disabled the git lines in build-linux.sh for wxWidgets and wxLua, and manually downloaded and edited stuff to make it work.

**Comment by pkulchenko** [comment]
> just adding aarch64 to the archtype table in main.lua and adding a case for aarch64 in zbstudio.sh is enough.

I figured this much, but it would be nice to see the exact diff as I'm not sure what is being returned by uname on your platform. Thank you.

> I'm rebuilding it from scratch, will it work if I copy over the contrib and arm directories from libpng sources into the build/wxWidgets/src/png directory?

I believe so, although I'm not sure how files from png/contrib/arm-neon get to the main tree (maybe they need to be copied manually?)

**Comment by WarpspeedSCP** [comment]
well, uname returns aarch64 on my phone, and I just used that. however, now, I have encountered a very puzzling situation-

the bin/linux/aarch64/clibs directory isn't a directory, it's a file!
It behaved well the first time, but after I decided to redo everything, it has all fallen to pieces.

**Comment by pkulchenko** [comment]
@WarpspeedSCP,

> the bin/linux/aarch64/clibs directory isn't a directory, it's a file!
> It behaved well the first time, but after I decided to redo everything, it has all fallen to pieces.

Hm, can't say what might have caused this; I've never seen it before. You may still have all the files in `build/deps/lib` folder, so the easiest way would probably be to drop the file, make it a folder and copy the libraries. Worst case scenario, you'd need to rebuild the libraries.

Here is the diff I came up with; does this looks like what you have:

```diff
diff --git a/build/build-linux.sh b/build/build-linux.sh
index 5325247..31235c9 100755
--- a/build/build-linux.sh
+++ b/build/build-linux.sh
@@ -15,6 +15,10 @@ case "$(uname -m)" in
 		FPIC="-fpic"
 		ARCH="armhf"
 		;;
+        aarch64)
+		FPIC="-fpic"
+		ARCH="aarch64"
+		;;
 	*)
 		FPIC=""
 		ARCH="x86"
diff --git a/src/main.lua b/src/main.lua
index 0cf18fa..da04632 100644
--- a/src/main.lua
+++ b/src/main.lua
@@ -18,8 +18,12 @@ if islinux then
   local file = io.popen("uname -m")
   if file then
     local machine=file:read("*l")
-    local archtype= { x86_64="x64", armv7l="armhf" }
-    arch = archtype[machine] or "x86"
+    local archtype= {
+      x86_64  = "x64",
+      armv7l  = "armhf",
+      aarch64 = "aarch64",
+    }
+    arch = archtype[machine] or arch
     file:close()
   end
 end
diff --git a/zbstudio.sh b/zbstudio.sh
index 2924b3f..4a8aa94 100755
--- a/zbstudio.sh
+++ b/zbstudio.sh
@@ -11,9 +11,10 @@ if [[ $(uname) == "Darwin" ]]; then
    open zbstudio/ZeroBraneStudio.app --args "$@")
 else
   case "$(uname -m)" in
-	x86_64) ARCH=x64;;
-	armv7l) ARCH=armhf;;
-	*)	ARCH=x86;;
+    x86_64)  ARCH=x64;;
+    armv7l)  ARCH=armhf;;
+    aarch64) ARCH=aarch64;;
+    *)       ARCH=x86;;
   esac
   (cd "$DIR"; bin/linux/$ARCH/lua src/main.lua zbstudio "$@") &
 fi
```

**Comment by WarpspeedSCP** [comment]
> Here is the diff I came up with; does this looks like what you have:

yes, that is exactly what I did.

I fixed the other issue by manually creating the clibs folder in aarch64. I think what happened was that the script created a file called clibs in the aarch64 directory, and dumped the contents of whatever was built into that file (not sure, though).

**Comment by WarpspeedSCP** [comment]
> @WarpspeedSCP, according to this ticket, it seems like you may need to have contrib/arm-neon folder from libpng, but it's not packaged with libpng that ships with wxwidgets, so you may need to copy it manually (just make sure it's from the same version).

how would I go about building wxwidgets without neon support, seeing as that seems to have worked in the case you mentioned?

**Comment by pkulchenko** [comment]
@WarpspeedSCP, I think you can copy files from contrib/arm-neon to the main folder as it should just overwrite the files with matching names, but I don't have a machine to test it on and, as you said, it may not be fully ready for aarch64.

**Comment by WarpspeedSCP** [comment]
I'll just try it without the `--libpng=builtin` option.

**Comment by WarpspeedSCP** [comment]
Okay, it works!

Is builtin libpng support required? because zbs works regardless.

**Comment by pkulchenko** [comment]
When you build it yourself, probably not, as you'd be relying on the libpng library you have in your host system, but because the IDE is distributed as a compiled library on several platforms, I'm including libpng to minimize the conflicts. I like this approach better than messing with arm-neon folders...

**Comment by WarpspeedSCP** [comment]
I figured as much. Thank you for the help.
