### ISSUE TITLE
Request: XML Features - Comments and XML Validation

### ISSUE THREAD

**Issue by Face2k** [pkulchenko/ZeroBraneStudio#746]
Currently Zerobrane only supports "line-start" comment characters like 

`// this is a comment`
 or 
`-- some commented code`

XML needs surrounding comment characters like

`<!-- <myXMLElement>some values</myXMLElement>-->`

Would be nice if **xml comment** and **xml validation** feature can be added to one of the next versions.

**Comment by pkulchenko** [comment]
@Face2k, how are you enabling XML syntax highlighting? If you are using [xml plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/xml.lua), it does recognize XML comments, but it has no support for XML validation and it's not planned.
