### ISSUE TITLE
error loading module 'wx'

### ISSUE THREAD

**Issue by cyan07** [pkulchenko/ZeroBraneStudio#748]
I want to use torch to test some images. After installing torch7, I was installing the zbstudio.sh .Sadly,the errors have appeared. I feel depressed ,can you help me? I will appreciate your help so much.
The errors as follow:
haichao@cama-HP840:~/zbs-torch$ ./zbstudio.sh
haichao@cama-HP840:~/zbs-torch$ bin/linux/x64/lua: error loading module 'wx' from file 'bin/linux/x64/
libwx.so':	/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_glib_get_unicode_funcs
stack traceback:
	[C]: at 0x004820e4
	[C]: in function 'require'
	src/main.lua:35: in main chunk
	[C]: at 0x004054e8

**Comment by pkulchenko** [comment]
What operating system do you use? What does `uname -a` returns?

**Comment by cyan07** [comment]
Linux cama-HP840 4.4.0-70-generic #91-Ubuntu SMP Wed Mar 22 12:47:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pkulchenko** [comment]
I'm not sure what version Ubuntu that is, but it seems to be pre-installed by HP, so I'm not sure why that symbol is not resolved (it's not something that the IDE requests). You may try to upgrade libpango to see if that fixes the issue (I see at least [one commit](https://mail.gnome.org/archives/commits-list/2015-June/msg05190.html) that removes the usage of that function).
