### ISSUE TITLE
outline.showonefile = true causes ZBS crash on Mac

### ISSUE THREAD

**Issue by grotly** [pkulchenko/ZeroBraneStudio#749]
I noticed that if I include in the user preferences the line

          outline.showonefile = true

then ZBS crashes whenever I try to close a tab. I am on ZBS 1.50 on El Capitan. Below I pasted some details. 

Process:               lua [1873]
Path:                  /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua
Identifier:            com.ZeroBrane.ZeroBraneStudio
Version:               1.50 (???)
Code Type:             X86 (Native)
Parent Process:        ??? [1872]
Responsible:           lua [1873]
User ID:               505

Date/Time:             2017-04-01 21:35:14.750 +0200
OS Version:            Mac OS X 10.11.6 (15G1217)
Report Version:        11
Anonymous UUID:        68D8EC26-A05F-8343-A95C-1BA2A24CCF95

Sleep/Wake UUID:       FADB6BEB-0AE8-4213-903F-A4AB9E7D507B

Time Awake Since Boot: 7500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0:
--> 
    __TEXT                 0000000000001000-0000000000003000 [    8K] r-x/rwx SM=COW  /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua.app/Contents/MacOS/lua

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libwx.dylib                   	0x01d16097 0x1800000 + 5333143
1   libwx.dylib                   	0x01ce34c5 0x1800000 + 5125317
2   libwx.dylib                   	0x01894393 0x1800000 + 607123
3   liblua.dylib                  	0x000093a0 0x7000 + 9120

Thread 1:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x956287fa kevent_qos + 10
1   libdispatch.dylib             	0x953fb7ea _dispatch_mgr_invoke + 234
2   libdispatch.dylib             	0x953fb3be _dispatch_mgr_thread + 52

Thread 3:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 4:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 5:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x9562049a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x9561f884 mach_msg + 68
2   com.apple.CoreFoundation      	0x91709d16 __CFRunLoopServiceMachPort + 214
3   com.apple.CoreFoundation      	0x91709121 __CFRunLoopRun + 1521
4   com.apple.CoreFoundation      	0x917088c6 CFRunLoopRunSpecific + 390
5   com.apple.CoreFoundation      	0x9170872b CFRunLoopRunInMode + 123
6   com.apple.AppKit              	0x9b55bdde _NSEventThread + 291
7   libsystem_pthread.dylib       	0x98326780 _pthread_body + 138
8   libsystem_pthread.dylib       	0x983266f6 _pthread_start + 155
9   libsystem_pthread.dylib       	0x98323f7a thread_start + 34

Thread 7:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 8:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 9:
0   libsystem_kernel.dylib        	0x95627d5e __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9832634b _pthread_wqthread + 1289
2   libsystem_pthread.dylib       	0x98323f56 start_wqthread + 34

Thread 10:

Thread 11:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x95627726 __select + 10
1   com.apple.CoreFoundation      	0x9174af60 __CFSocketManager + 912
2   libsystem_pthread.dylib       	0x98326780 _pthread_body + 138
3   libsystem_pthread.dylib       	0x983266f6 _pthread_start + 155
4   libsystem_pthread.dylib       	0x98323f7a thread_start + 34

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0x00000001  ebx: 0x00668580  ecx: 0x00000000  edx: 0x00000001
  edi: 0x00000000  esi: 0x002d88bc  ebp: 0xbfffe888  esp: 0xbfffe870
   ss: 0x00000023  efl: 0x00010246  eip: 0x01d16097   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x00000000
  
Logical CPU:     0
Error Code:      0x00000006
Trap Number:     14

**Comment by pkulchenko** [comment]
@grotly, thank you for the report; checking...

**Comment by pkulchenko** [comment]
@grotly, can you try the following patch:

```diff
diff --git a/src/editor/outline.lua b/src/editor/outline.lua
index bcb349c..75fea4f 100644
--- a/src/editor/outline.lua
+++ b/src/editor/outline.lua
@@ -128,7 +128,7 @@ local function outlineRefresh(editor, force)
   -- add file
   local filename = ide:GetDocument(editor):GetTabText()
   local fileitem = cache.fileitem
-  if not fileitem then
+  if not fileitem or not fileitem:IsOk() then
     local root = ctrl:GetRootItem()
     if not root or not root:IsOk() then return end
 
@@ -293,7 +293,7 @@ local function createOutlineWindow()
         if not parent:IsOk() then return end
       end
       -- activate editor tab
-      local editor = onefile and GetEditor() or ctrl:GetItemData(parent):GetData()
+      local editor = onefile and ide:GetEditor() or ctrl:GetItemData(parent):GetData()
       local cache = caches[editor]
       if editor and cache then
         -- move to position in the file
@@ -370,7 +370,9 @@ end
 local function eachNode(eachFunc, root, recursive)
   local ctrl = outline.outlineCtrl
   if not ctrl then return end
-  local item = ctrl:GetFirstChild(root or ctrl:GetRootItem())
+  root = root or ctrl:GetRootItem()
+  if not (root and root:IsOk()) then return end
+  item = ctrl:GetFirstChild(root)
   while true do
     if not item:IsOk() then break end
     if eachFunc and eachFunc(ctrl, item) then break end
@@ -443,9 +445,15 @@ local package = ide:AddPackage('core.outline', {
       local cache = caches[editor]
       local fileitem = cache and cache.fileitem
       caches[editor] = nil -- remove from cache
-      -- if one file is shown, then only clear outline if the current editor is being closed
-      if (ide.config.outline or {}).showonefile and editor ~= ide:GetEditor() then return end
-      if fileitem then outline.outlineCtrl:Delete(fileitem) end
+
+      if fileitem and fileitem:IsOk() then
+        local ctrl = outline.outlineCtrl
+        if (ide.config.outline or {}).showonefile then
+          ctrl:DeleteChildren(fileitem)
+        else
+          ctrl:Delete(fileitem)
+        end
+      end
     end,
 
     -- handle rename of the file in the current editor
@@ -605,6 +613,7 @@ local package = ide:AddPackage('core.outline', {
       -- scan all items recursively starting from the current file
       eachNode(function(ctrl, item)
           local func = cache.funcs[ctrl:GetItemData(item):GetData()]
+          if not func then return end
           local val = edpos >= func.pos and func.poe and edpos <= func.poe
           if edline == editor:LineFromPosition(func.pos)+1
           or (func.poe and edline == editor:LineFromPosition(func.poe)+1) then
```
