### ISSUE TITLE
Whenever i try to make a main.lua file, it says Error: operation not permited

### ISSUE THREAD

**Issue by StuffyMcMuffins** [pkulchenko/ZeroBraneStudio#750]

**Comment by pkulchenko** [comment]
@StuffyMcMuffins, how exactly are you creating the file? What version of the IDE are you using? What platform are you running it on? Do you have anything in your configuration (user.lua) file and have you tried without any configuration settings? Does it work for other files you are trying to create? Do you have a screenshot of the error message?

You need to provide more details to allow troubleshooting this issue and don't open multiple tickets for the same issue.

**Comment by StuffyMcMuffins** [comment]
![image](https://cloud.githubusercontent.com/assets/26841243/24616496/4849a95a-185f-11e7-90d2-c004867d1d56.png)

that is the screen shot. I'm using love-ide. I don't know how to check my configuration file I was watching a video by Lost RD and episode 3. I was doing everything correctly, but then when he made the path I could not add semi-colons, idk if that is the problem. If I make a new folder that is not through LOVE, then it will allow me to make a file that says main.lua. But once I have a file through LOVE, hello world, it give me that error

**Comment by pkulchenko** [comment]
It doesn't have anything to do with ZeroBrane Studio, as you are using Atom, so you'll need to ask in Atom or Love forums.
