### ISSUE TITLE
run/debug quits on Windows 10

### ISSUE THREAD

**Issue by decuant** [pkulchenko/ZeroBraneStudio#752]
I'm the administrator and the installation was successful,then I modified the user.lua to have the same color setup and that's it.

I cannot run the application or debug it. it simply quits reporting a running time of 0.1xxx
then I tried to setup some breakpoints and I discovered that I can run/debug the application if I have the current window open on the main.lua file, which means that if I have 2 windows open, say main.lua and window.lua, if my current window is on window.lua the application will jump to main.lua to request a debugger launch and then will quit. if I do the same thing from main.lua every breakpoint I had setup works fine and the application runs correctly.

**Comment by pkulchenko** [comment]
Having two instances of the IDE is not likely to work (as they will be using the same debugger port and will run into conflicts). Make sure you have only one instance running and the firewall doesn't block access to port 8172.

**Comment by decuant** [comment]
Hello Paul, I had not 2 instances at the same time, just 2 tabs open. 

I solved the high dpi problem as you taught me, now I right clicked on the file list and set main.lua to be the start file (I'm on a new laptop with a clean install)

now the application runs correctly and I can debug it, dpi are correct too.

thank you very much, I'll close the issue

**Comment by pkulchenko** [comment]
Oh, right; if you are editing in multiple tabs, but want to always start debugging from a particular file, then use "Set as Start File" from the menu in the Project window (as you did). You can also use `debugger.runonstart=true` if you don't want the debugger to pause on the first statement that is being debugged.
