### ISSUE TITLE
High DPI on Windows 10, a not aware app

### ISSUE THREAD

**Issue by decuant** [pkulchenko/ZeroBraneStudio#753]
when I run my application from within the IDE it uses some setup that it's not correct for me

apart from the toolbar problem, of which I have read, zero brane is launching my application as if it is High DPI aware, which is not, then all my fixed size windows and text are unusable

if I launch the application from the shell everything is ok

is there any parameter I can use to disable it?

**Comment by pkulchenko** [comment]
Hm, it should be the same whether it's launched from the IDE or the command line, assuming you are using `bin/lua.exe`.  The hidpi setting is in the manifest added to lua.exe, so you can either specify your own version of lua (using `path.lua` [setting](https://studio.zerobrane.com/doc-general-preferences#interpreter-path)) by pointing to the version of Lua you are using when you run from the command line or replace `bin/lua.exe` with a "regular" version of lua.exe from Lua 5.1 (the former is a better way to deal with it).

**Comment by decuant** [comment]
I did the modification on user.lua and it works ok now, thank you

user.lua

path.lua = 'C:/wxLua/bin/lua.exe'
