### ISSUE TITLE
View state resets after running the project

### ISSUE THREAD

**Issue by Playermet** [pkulchenko/ZeroBraneStudio#754]
It's pretty useful to hide Output/Console window for code editing, especially when using monitor with small height resolution. But after running the project it showed and stays visible even after execution stopped. So it is necessary to hide windows again and again after every debug running.

It would be very nice to separate windows states for code editing and debugging mode, to prevent unnecessary windows toggling.

**Comment by pkulchenko** [comment]
You can set `activateoutput=false` to achieve the desired effect. When autoactivation is disabled, the Output/Console window will be shown during debugging and hidden after the debugging is done.

**Comment by Playermet** [comment]
Thanks!
