### ISSUE TITLE
Windows: ZBS either can't debug, or won't run at all

### ISSUE THREAD

**Issue by Zueuk** [pkulchenko/ZeroBraneStudio#756]
I had an error like this
> error loading module 'socket.core' from file 'C:\ZeroBraneStudio/bin/clibs/socket\core.dll':
> %1 is not a valid Win32 application.

and fixed it by replacing the said dll with a 64-bit version provided in the issue #500.

This worked for some time, but now I have a similar error every time I try to start ZBStudio:
![default](https://cloud.githubusercontent.com/assets/5717247/24871451/b019d70a-1e2a-11e7-8839-360c910a0ff1.png)

Restoring the old dll makes it work, but obviously debugging now gives the same error as before.

**Comment by pkulchenko** [comment]
@Zueuk, you shouldn't change the library to a 64bit one as it's used by ZeroBrane Studio itself (and since it's a 32bit application, you get the error); you should put the 64bit libraries in the folder of your application and set the `package.path` and `package.cpath` to reference that location. Everything should work in terms of running/debugging after that.

I'll update the documentation to cover this.

**Comment by Zueuk** [comment]
Instruction unclear, getting "lua module 'copas' not found" now.

I'm using Torch located in C:\SomePath\Torch, which has luajit.exe in Torch\bin, but apparently I have to launch it using Torch\luarocks\systree\bin\th.bat
Where should I put core.dll, and which path should I put in package.(c)path (that's in ~/.zbstudio/user.lua - right?)

**Comment by pkulchenko** [comment]
> Instruction unclear, getting "lua module 'copas' not found" now.

@Zueuk, this is probably because you replaced whatever path/cpath you had, but you only need to prepend the cpath to 64bit luasocket libs **in your application** to make sure they are loaded instead of 32bit libs:

```lua
package.cpath="d:/path/to/64bit/clibs/?.dll;"..package.cpath
```

> Where should I put core.dll, and which path should I put in package.(c)path (that's in ~/.zbstudio/user.lua - right?)

Doesn't matter where you put it as long as it's the same that you set in `package.cpath`. This goes into your script before you call the debugger (not in user.lua settings).

**Comment by Zueuk** [comment]
Ok... Apparently I don't understand something about Lua debugging.
I want to debug some random Lua script in ZBStudio. Who is going to execute this line, if "Start debugging" starts before the 1st script line?

Another thing: I printed the existing package.cpath, and it already has a lot of Torch-related directories in it. I tried putting the 64-bit core.dll in these, but the result is the same as before.

**Comment by pkulchenko** [comment]
You are correct; I assumed you are starting the application from outside of the IDE or from the IDE using Run/F6 command. It's not going to work the way I suggested when you are using F5/Debug, so the current workaround is to use Run command (and include `require('mobdebug').start()` command explicitly in your script).

> Another thing: I printed the existing package.cpath, and it already has a lot of Torch-related directories in it. I tried putting the 64-bit core.dll in these, but the result is the same as before.

This should work as long as the path with your 64bit core.dll is the first one being picked up by the `require`. You can check how the paths are searched by running `package.searchpath("socket.core", package.cpath)` from the Local console.

**Comment by Zueuk** [comment]
Aha! So it was looking for "socket/core.dll", not just the dll.
Moved it into the subdir and now debugging seems to be working.
Thanks!

**Comment by pkulchenko** [comment]
Sounds good; will make sure it's covered in the documentation.

**Comment by xianzhiliao** [comment]
replace socket 64 still have problems
![image](https://cloud.githubusercontent.com/assets/11209617/25366260/18f3eeec-29a1-11e7-93fd-51d54fd22406.png)

**Comment by pkulchenko** [comment]
@xianzhiliao, you should not be replacing modules in the IDE folders as some of them are used by the IDE itself (and in this case you replaced a 32bit module with a 64bit version, which caused a conflict and the error).

You should put the modules into its own folder where your application can access them.
