### ISSUE TITLE
Why don’t I see print output in the Output window?

### ISSUE THREAD

**Issue by zhengy** [pkulchenko/ZeroBraneStudio#757]
I can debug with zbs successful, but I can't see all the print output in the Output window,   I have already
add   io.stdout:setvbuf("no")   to my lua file,    but  it can't work !

**Comment by pkulchenko** [comment]
What *do* you see in the Output window? What version of the IDE are you running? On what platform? How do you start the application (from the IDE or externally; running or debugging)?

**Comment by zhengy** [comment]
The IDE version is  1.50,  platform is  window7 x86_64.   I use it in "Start Debugger Server" mode to debug unity slua .   The log can all show in unity console after debug, but nothing in IDE Output window.

**Comment by pkulchenko** [comment]
If you don't start the application *from* the IDE, there is no way to redirect the output from the application, so it's not going to show in the Output window. It may still possible to redirect the output **during debugging** and you can set `debugger.redirect="r"` in the settings to see if it works for you (see the [debugger settings](https://studio.zerobrane.com/doc-general-preferences#debugger)).
