### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by omrysendik** [pkulchenko/ZeroBraneStudio#761]
If I start ZBS (ZeroBraneStudio) without sudo, I can't save the files I edit.
If I start it with sudo, it doesn't recognize the packages I installed with luarocks.

**Comment by pkulchenko** [comment]
@omrysendik, what are the permissions on the folder you are trying to save the files to? The IDE doesn't do anything with the permissions, so if the current user can save the files, you will be able to save them from the IDE.

When you use sudo, check the environmental variables as LUA_PATH and LUA_CPATH are probably not set, which will make the modules installed with luarocks not to be found.
