### ISSUE TITLE
string.gfind not found using default lua interpreter

### ISSUE THREAD

**Issue by janardhannarayana** [pkulchenko/ZeroBraneStudio#764]
I am using string.gfind for splitting the strings in my function, but string doesn't have the gfind function definition. 

string
{byte = function() --[[..skipped..]] end, char = function() --[[..skipped..]] end, dump = function() --[[..skipped..]] end, find = function() --[[..skipped..]] end, format = function() --[[..skipped..]] end, gmatch = function() --[[..skipped..]] end, gsub
= function() --[[..skipped..]] end, len = function() --[[..skipped..]] end, lower = function() --[[..skipped..]] end, match = function() --[[..skipped..]] end, rep = function() --[[..skipped..]] end, reverse = function() --[[..skipped..]] end, sub = function()
--[[..skipped..]] end, upper = function() --[[..skipped..]] end} --[[table: 0x40f0a5a0]]

**Comment by pkulchenko** [comment]
`string.gfind` is obsolete in Lua 5.1: https://www.lua.org/manual/5.1/manual.html#7.2; use `string.gmatch` instead.
