### ISSUE TITLE
No 64bit version?

### ISSUE THREAD

**Issue by concatime** [pkulchenko/ZeroBraneStudio#766]
Hi. I searched for a version of ZeroBrane Studio 64bit with 64bit Lua also, but find nothing. Is It on the ToDo list? Or may seem useless? Why I'm I searching for 64? Cause I want to use the internal lua provided as main lua in my pc, but it's only 32 bits.

**Comment by pkulchenko** [comment]
@concatime, you don't need 64bit version of the IDE to debug 64bit applications on windows. You just need to set the interpreter to use 64bit version of Lua (following the instructions for `path.lua` here: https://studio.zerobrane.com/doc-general-preferences#interpreter-path) and then reference 64bit libraries that may be needed for debugging. See this sections in the documentation for details: https://studio.zerobrane.com/doc-remote-debugging#debugging-of-64bit-applications.

**Comment by pkulchenko** [comment]
Also see #756.
