### ISSUE TITLE
Multi Instance isn't working Mac OSX (10.11.6)

### ISSUE THREAD

**Issue by ioneyed** [pkulchenko/ZeroBraneStudio#767]
I cannot get the tips for running multiple instances to work, it keeps the same window open.

Tried the following commands:

`open ZeroBraneStudio.app --args -cfg "singleinstance=false"`
`./zbstudio.sh --args -cfg "singleinstance=false"`

(src: https://studio.zerobrane.com/doc-tips-and-tricks#run-multiple-instances-of-the-ide)

Ideally I just want to be able to open multiple project folders in the same single IDE but multi-instance IDE was the next best solution.

**Comment by pkulchenko** [comment]
@ioneyed, the IDE on MacOS doesn't use `singleinstance` logic as the app uniqueness is controlled by the OS itself. You can add `-n` option to the launch script to suppress this logic:

```diff
diff --git a/zbstudio.sh b/zbstudio.sh
index 4a8aa94..c1ca85f 100755
--- a/zbstudio.sh
+++ b/zbstudio.sh
@@ -8,7 +8,7 @@ if [[ $(uname) == "Darwin" ]]; then
   ATTR="com.apple.quarantine"
   (cd "$DIR"; \
    if [[ $( xattr -pl $ATTR zbstudio 2>&1 ) == $ATTR:* ]]; then xattr -rd $ATTR zbstudio bin; fi; \
-   open zbstudio/ZeroBraneStudio.app --args "$@")
+   open -n zbstudio/ZeroBraneStudio.app --args "$@")
 else
   case "$(uname -m)" in
     x86_64)  ARCH=x64;;
```

Alternatively, you should be able to use `open -n ZeroBraneStudio.app`.

I'll need to update the documentation as `--args` is no longer needed with zbstudio.sh as it's already included in the script.

Keep in mind that the different instances of the IDE will be sharing the same ini file, which may lead to the last instances you close overwriting the config, so you may want to pass `ini` parameter to have a designated ini file for each instance.

If you want to show different project directories for navigation and access purposes, you can use "directory mapping" from the project tree: right click in the project tree and select "Map Directory". This will add the directory to the top of the list and you can then expand it and navigate its files.

**Comment by ioneyed** [comment]
Both of your suggestions worked however the multi-instance is a bit odd because it doesn't register it under the same namespace in Mac to allow the "window" selection via ``Cmd + ` `` like other applications. However the `Map` directory does exactly what I was looking for as it allows me to view multiple code bases in a IDE for comparison/lookups/etc.
