### ISSUE TITLE
Add support for LuaCheck

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#768]
The reason I'd like to support ![LuaCheck](https://github.com/mpeterv/luacheck) is because it's more feature complete and can handle cases ![LuaInspect](https://github.com/davidm/lua-inspect) can't.

![I've added initial support for this in in my fork](https://github.com/CapsAdmin/ZeroBraneStudio)

To enable this set `staticanalyzer.luacheck` in config to true or table to configure it.

In this implementation ![I pass an environment based on the APIs  the current Lua interpreter uses to its options.](https://github.com/CapsAdmin/ZeroBraneStudio/blob/03c3d9f75eab8d87a42920f09e08fe7dea5a4984/src/editor/inspect.lua#L12-L37)

In addition to passing the API environment I would also like to add defined globals from other files but I'm not sure how to go about doing this. Maybe something from outline.lua?

I've ![disabled some warnings that might be too excessive](https://github.com/CapsAdmin/ZeroBraneStudio/blob/03c3d9f75eab8d87a42920f09e08fe7dea5a4984/src/editor/inspect.lua#L45-L49)

I think LuaCheck can report multiple errors in some cases but I've made it ![only report the first error](https://github.com/CapsAdmin/ZeroBraneStudio/blob/03c3d9f75eab8d87a42920f09e08fe7dea5a4984/src/editor/inspect.lua#L52-L57) because of how it was previously structured.

Overall the implementation is a lot more simple. I didn't add checking for duplicate warnings but it should be easy to do. It will also ignore cases like an unused function argument is called "_" internally.

@mpeterv

**Comment by pkulchenko** [comment]
@CapsAdmin, looks very good; thank you!

Can you move it into a branch, so that I can pick it without impacting your master?

**Comment by pkulchenko** [comment]
@CapsAdmin, merged; you'll need to force-push your master to get the latest changes. Thanks!

**Comment by pkulchenko** [comment]
@CapsAdmin, I noticed one thing with the switch between analyzers: it can only be done on startup; I think this implementation can be improved by checking for the current value of the setting and re-configuring if the value is different. This should allow switching the analyzer at run time without restarting.

**Comment by stuta** [comment]
How can I change defaults for Luacheck? I created .luacheckrc -file in my project main level but it does not seem to work. I would prefer options in user.lua file than .luacheckrc -file.

**Comment by pkulchenko** [comment]
@stuta, `staticanalyzer.luacheck` accepts configuration table as the value (https://studio.zerobrane.com/doc-general-preferences#static-analyzer), which includes `options` table with the values as described in [luacheck documentation](http://luacheck.readthedocs.io/en/stable/config.html). So for example, `staticanalyzer.luacheck = {options = {max_line_length = false}}` should work.

**Comment by stuta** [comment]
Sorry, I did not read the line well.

Now I have:
staticanalyzer.luacheck = {
	std = "_G"
}

When I run luacheck on code "aa = 1" I get "setting non-standard global variable aa". After restart zbs still gives "Analyzing the source code: no warnings."

**Comment by pkulchenko** [comment]
Try: `staticanalyzer.luacheck = { options = {std = "_G"} }` (you are missing "options" table). I'll update the documentation with examples.

**Comment by stuta** [comment]
Thanks, works perfectly.

**Comment by doodoori2** [comment]
Does it support luacheck inline options?
I want to explicitly remove 'unused parameter warnings' for some specific functions.
I know that replacing the variable name to _ will ignore that warnings. 
but I want to keep the argument name meaningful.

**Comment by pkulchenko** [comment]
It should. It applies the regular luacheck processing, so it should handle these options (as long as the included version supports them). Are you running into any issues with it?

**Comment by moteus** [comment]
What is the best way to define luacheck options per project?
I have several projects and I have separate settings for them.
I use luacheck as part of my auto-tests and I use now config file
but ZBS ignores it.

**Comment by pkulchenko** [comment]
@moteus, you should be able to do this using `staticanalyzer.luacheck` option (https://studio.zerobrane.com/doc-general-preferences#static-analyzer) in combination with [projectsettings plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/projectsettings.lua).

**Comment by doodoori2** [comment]
Sorry.
I did not know about the staticanalyzer.luacheck option. 
I thought using luacheck is default. 
The luacheck inline option works fine.
