### ISSUE TITLE
FixUTF8 might make ZBStudio crash 

### ISSUE THREAD

**Issue by 1linux** [pkulchenko/ZeroBraneStudio#772]
See function "markersRefresh()" in markers.lua, line 74 in Version 1.60:

```
for _, edmarker in ipairs(getMarkers(editor)) do
    local line, markertype = unpack(edmarker)
    local text = ("%d: %s"):format(line+1, FixUTF8(editor:GetLineDyn(line)))
    ctrl:AppendItem(fileitem, text:gsub("[\r\n]+$",""), image[markertype:upper()])
end
```

Seems "FixUTF8()" returns a nil value in rare cases.
My quick fix was changing line 67 to
`    local text = ("%d: %s"):format(line+1, FixUTF8(editor:GetLineDyn(line)) or '')
`

Case might be, when in a line holding a breakpoint, there is an UTF-char like "xDC". Really a rare case :-)

**Comment by pkulchenko** [comment]
@1linux, thank you for the report! There was indeed an issue that has been fixed in 68641c17.
