### ISSUE TITLE
Appearance highlighting

### ISSUE THREAD

**Issue by Greilachelous** [pkulchenko/ZeroBraneStudio#774]
Right now I didn't find appearance highlighting in ZeroBrane. 
It would be a nice help.

**Comment by pkulchenko** [comment]
I'm not sure what `appearance` is. It should probably be reported upstream to Scintillua project as the IDE is using its lexers for. Also see #773 for related resources and details.

**Comment by Greilachelous** [comment]
Thank you for your quick answer.
It's quit simple: if we click on a word, editor highlights all identical words in the script.

**Comment by pkulchenko** [comment]
@Greilachelous, got it. There is already a [highlightselected plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua) that does this.

**Comment by Greilachelous** [comment]
I came to tell you I've just found it and close the issue. :)
Thank you.

**Comment by Greilachelous** [comment]
Sorry, where can I change the style of highlightened texts e.g. if I don't want an empty box style highlighting, rather a colored one without frames?

**Comment by pkulchenko** [comment]
There is no one without frames, but there is a colored box that may look better; try replacing `wxSTC_INDIC_BOX` with `wxSTC_INDIC_ROUNDBOX` in the plugin.

I'll update it to take configuration values for the indicator and the color.

**Comment by Greilachelous** [comment]
Thank you!

**Comment by Greilachelous** [comment]
Just a private technical question: What editor color style you prefer as an experienced programmer? Dark styles or white styles or what?

**Comment by pkulchenko** [comment]
I'd say white and light styles, like the default style in the IDE or Solarized light style.

**Comment by Greilachelous** [comment]
Thank you! :)
