### ISSUE TITLE
openwithdefault plugin activates on known extensions, which causes multiply instances to launch

### ISSUE THREAD

**Issue by Greilachelous** [pkulchenko/ZeroBraneStudio#775]
If we use filetreeoneclick plugin, when we accidentally click double on a file in the projekttree, two more editor instances will be opened with that file on top of the original one.

**Comment by pkulchenko** [comment]
Everything directly plugin related should be opened as an issue in the Packages repository (you don't need to move this ticket there).

I don't see this effect on Windows: the Activate event is only called once and even when the same file is activated multiple times, only one copy should be loaded in the IDE. What OS are you running it on and what other plugins do you have? Maybe there is some interaction with other plugins that is causing this effect? Can you try with only filetreeoneclick plugin?

**Comment by Greilachelous** [comment]
OS: Ubuntu 16.04 lts
OK. You're right. It was the with `openwithdefault` interaction.
If I changed the **line 12** in `openwithdefault.lua` to `if ft and ext ~= '.lua' then`, then worked well, though I don't really know if it can cause some other issue in the future with `.lua` extensions.

**Comment by pkulchenko** [comment]
Yes, `openwithdefault` is used for any extension, including .lua and others. I think they should be excluded by checking against the list in `ide:GetKnownExtensions()`.

**Comment by Greilachelous** [comment]
Would be fine.

**Comment by pkulchenko** [comment]
Updated `openwithdefault` to skip activation on known extensions.
