### ISSUE TITLE
Torch7 debugging doesn't show the described output result

### ISSUE THREAD

**Issue by Greilachelous** [pkulchenko/ZeroBraneStudio#776]
Following the [Torch debugging documentation](http://notebook.kulchenko.com/zerobrane/torch-debugging-with-zerobrane-studio) I expected the result:
![image](https://user-images.githubusercontent.com/8689085/28306950-88451ffe-6ba1-11e7-9c89-852acb401405.png)
**But I get:**
![image](https://user-images.githubusercontent.com/8689085/28306723-b6e24ac2-6ba0-11e7-9d1b-374ff643745f.png)

Ubuntu 16.04.2 LTS 64-bit

**Comment by pkulchenko** [comment]
I don't see much difference. The first screenshot shows the result of evaluating `data` in the console, which you didn't run in the second screenshot. I'd assume that if you type `data` and hit Enter, you'd get the same result as in the first screenshot.

**Comment by Greilachelous** [comment]
@pkulchenko It's my bad, but I misunderstood the documentation quite a bit. It wasn't obvious for me - maybe because I've just come from **Python/Spyder** environment-, that I have to type `data` in the `Remote Console`, because I was known by me as `Interactive Console`.

**Comment by pkulchenko** [comment]
@Greilachelous, correct, it's Interactive Console, but the tab changes between `Local Console` and `Remote Console` to indicate when commands are executed in the application you are debugging (`Remote Console`) or in the interpreter in the IDE (`Local Console`).

You can also switch the context while doing debugging by prepending `!`, which will force command to be executed in `Local Console`.

**Comment by Greilachelous** [comment]
@pkulchenko Oh, thank you, another bit of knowledge. 

One more thing, I don't want to overcharge needlessly your issue section.
In the above mentioned environment the `self` variable (there it's called `instance`) was separately styled with other color etc. I know that, this is a `lua` environment and here we don't use the `class` notation explicitly in the code, but the essence is the same. I found it quite useful and I think `lua` code would be more readable as well with this enhancement to sign explicitly, that `self.someparentvariable` is a `variable` of the parent class. What do you think?
![image](https://user-images.githubusercontent.com/8689085/28338195-778cdf0a-6c08-11e7-8cf6-1fba91e906fb.png)
