### ISSUE TITLE
Instant "self" style changing option

### ISSUE THREAD

**Issue by Greilachelous** [pkulchenko/ZeroBraneStudio#777]
The `self` variable as designated in `/opt/zbstudio/spec/lua.lua` 's last section (there it's called `instance`) was separately styled with other color etc. in other environment (Python/Spyder). I know that, this is a lua environment and here we don't use the class notation explicitly in the code, but the essence is the same. I found it quite useful and I think lua code would be more readable as well with this enhancement to sign explicitly, that `self.someparentvariable` is a variable of the parent class. 
![28338195-778cdf0a-6c08-11e7-8cf6-1fba91e906fb](https://user-images.githubusercontent.com/8689085/28363299-4dda9350-6c80-11e7-8198-c1ef3edd017f.png)

**Comment by pkulchenko** [comment]
@Greilachelous, you can do it by creating a new slot for `self` and assigning it a new style. Something like this should work:

```lua
local luaspec = ide.specs.lua
local num = #luaspec.keywords
-- take a new slot in the list of keywords (starting from 1)
luaspec.keywords[num+1] = 'self'
-- remove 'self' from the list where it's currently assigned
luaspec.keywords[2] = luaspec.keywords[2]:gsub(' self', '')
-- assign new style to the added slot (starting from 0)
styles["keywords"..num] = {fg = {240, 0, 0}, b = true, i = true}
```

It will make `self` bold, italic, and red. This is based on this example in the docs: https://github.com/pkulchenko/ZeroBraneStudio/blob/master/cfg/user-sample.lua#L146-L155.

**Comment by Greilachelous** [comment]
@pkulchenko, you are awesome, Paul, thank you. 
I made it sooner, but with some hack of lua.lua and your solution much more clear obviously.
Though my the problem was there and in your solution too, that when I add a `.` to the keyword i.e. `self.`, the keyword lost its style. So I couldn't declare like this:
![image](https://user-images.githubusercontent.com/8689085/28393542-920ffd46-6ce7-11e7-945a-8776a11d19ba.png)
That was the point, when I turned to you. :)

**Comment by pkulchenko** [comment]
> self.somevariable -- doesn't work

I think it's the limitation of the Lua lexer in Scintilla as it seems to be lexing `foo.bar` as one group. It looks like it's used in situations when you may want to stype `io.open` or `table.concat` together, but this prevents `self` to be styled correctly in `.` expressions.

One workaround would be to do it yourself, using something similar to highlightselected plugin, but instead find and style all instances of `self` in the text.

I **may** look at adding a special type of indicator for implicit `self` variables, but it's likely to be for implicit ones only (which may actually work for you). Given that the indicators currently support text colors, you *will* be able to make it red, but you *won't* be able to bold or italicize it.

**Comment by Greilachelous** [comment]
Thank you, Paul. Don't worry about the indicator one, I may find some solution.

**Comment by Greilachelous** [comment]
@pkulchenko I sticked around in ZB codes and Scintilla documentation and I think right now that the lexer limitation is in somewhere in tailor-made ZB lexer code. In this moment I can't still say exactly where, because I found `lexer.lua`, `lua.lua`, and `lua_lexer_loose.lua` files. Perhaps` lexer.lu`a is Scintilla's AI, `lua.lua` is the lua lexer, and the third is some dependency for some ZB code.
Could you, please make me clear this part of the code interaction or dependencies?

**Comment by pkulchenko** [comment]
`lexer.lua` is Scintillua's code (not Scintilla's), `lua.lua` is the code that configures Scintilla processing, and `lua_lexer_loose.lua` is the code that the IDE is using for outline, index, and indicator processing, but it's not used for styling. The last part is what I'm thinking about extending to support `self` indicators.

The handling of keywords, which is what is used to style `self` and other identifiers is handled by Scintilla. The IDE only configures that usage, but I don't see anything that would not allow handling of `self.` in the IDE code. I think this comes from the lexer in Scintilla itself (I can point you to its code if you want to take a look).

**Comment by Greilachelous** [comment]
Thank you for the description and yes I was a bit confused, Scintilla was a base tool for lexers written in C I guess, and Scintillua is a kind of higher level tool for lexer creating using Scintilla's libraries.
Yes, I'd like to take it a look. It is just a habit of mine to solve (almost) Mission Impossible things. :)

**Comment by pkulchenko** [comment]
Scintillua is an interesting project as it uses a drop-in Scintilla lexer to implement its own lexers in Lua (it provides a "generic" lexer for Scintilla, but delegates all the real work to lex and style to its own Lpeg/lua-based lexers). This is what the IDE is using to style non-Lua file formats.

The current lexer code for Scintilla should be here: https://github.com/LuaDist/scintilla/blob/master/lexers/LexLua.cxx#L197-L198; I marked the two lines that may be relevant to our discussion.

**Comment by Greilachelous** [comment]
Thank you very much, I'm looking at it.

**Comment by Greilachelous** [comment]
@pkulchenko Paul, could you please tell me, where and what form links LexLua.cxx to IDE (or to lexer or to whatever)?

**Comment by pkulchenko** [comment]
Sure. It's part of the Scintilla code, which is included in wxwidgets, which is compiled to binary (library) form and included in wxlua, which is then compiled to binary (dynamic library) form and is loaded by the IDE.

The scripts that do all this are in the `build/` folder (for each of the supported platform). If you want to compile your own changes, you'll need to clone wxwidgets manually (take the command from the build file), make your changes, and comment out the clone command and the `rm` command at the end of wxwidgets and wxlua sections (as you will probably want to compile it multiple times) and then run the build script. It will put the generated DLL in the right place for the IDE to use.

**Comment by Greilachelous** [comment]
Thank you very much for the extensive information, so if I took it well on linux in /opt/zbstudio/bin/linux/x64/clibs the .so files will be the according dynamic library files at the end of the process?

**Comment by pkulchenko** [comment]
no; it will be under `bin/linux/x64/clibs/` in the clone of the repo from which you run the build scripts. All the paths in the build scripts will be generated relative to the repo from which you run it. You can then copy the generated .so to whatever location you need.

**Comment by Greilachelous** [comment]
Sure, I meant the same, sorry if I wasn't clear. Thank you!

**Comment by Greilachelous** [comment]
Sorry, one more question: Why IDE doesn't not use scintillas Lpeg/lua-based lexer for .lua files and how can we use its lexer for .py files?

**Comment by pkulchenko** [comment]
You don't need to do anything for .py files as the lexlpeg lexer should be used for all extensions listed in `editor.specmap` that don't have explicit specs (which are only present for Lua and C files).

The reason these Lpeg-based lexers are not used for .lua files is that there are some features that haven't been mapped to them yet and because it was too risky to make the switch as these lexers haven't been extensively tested on all supported platforms yet.

**Comment by Greilachelous** [comment]
Got it. Thank you. :)

**Comment by pkulchenko** [comment]
@Greilachelous, here is the patch that I mentioned earlier that enables styling of `self` with indicators, similar to the styling for global/local variables. You won't be able to make it italic or bold, but you can change the color and apply any other indicator you want: https://studio.zerobrane.com/doc-styles-color-schemes#indicators

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 104e244..2ceb5eb 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -426,6 +426,7 @@ local indicator = {
   FNCALL = ide:GetIndicator("core.fncall"),
   LOCAL = ide:GetIndicator("core.varlocal"),
   GLOBAL = ide:GetIndicator("core.varglobal"),
+  SELF = ide:GetIndicator("core.varself"),
   MASKING = ide:GetIndicator("core.varmasking"),
   MASKED = ide:GetIndicator("core.varmasked"),
 }
@@ -588,7 +589,7 @@ function IndicateAll(editor, lines)
   end
 
   local cleared = {}
-  for _, indic in ipairs {indicator.FNCALL, indicator.LOCAL, indicator.GLOBAL, indicator.MASKING} do
+  for _, indic in ipairs {indicator.FNCALL, indicator.LOCAL, indicator.GLOBAL, indicator.MASKING, indicator.SELF} do
     cleared[indic] = pos
   end
 
@@ -622,7 +623,7 @@ function IndicateAll(editor, lines)
     -- indicate local/global variables
     if op == 'Id'
     and (var and indic.varlocal or not var and indic.varglobal) then
-      IndicateOne(var and indicator.LOCAL or indicator.GLOBAL, lineinfo, #name)
+      IndicateOne(var and (var.self and indicator.SELF or indicator.LOCAL) or indicator.GLOBAL, lineinfo, #name)
     end
 
     -- indicate masked values at the same level
diff --git a/src/editor/style.lua b/src/editor/style.lua
index 756a24d..1f8f0ba 100644
--- a/src/editor/style.lua
+++ b/src/editor/style.lua
@@ -85,6 +85,7 @@ function StylesGetDefault()
       varglobal = {},
       varmasking = {},
       varmasked = {},
+      varself = {},
       searchmatch = {},
     },
   }
@@ -368,6 +369,7 @@ function StylesApplyToEditor(styles,editor,font,fontitalic,lexerconvert)
 
     local fncall = ide:AddIndicator("core.fncall")
     local varlocal = ide:AddIndicator("core.varlocal")
+    local varself = ide:AddIndicator("core.varself")
     local varglobal = ide:AddIndicator("core.varglobal")
     local varmasking = ide:AddIndicator("core.varmasking")
     local varmasked = ide:AddIndicator("core.varmasked")
@@ -377,6 +379,8 @@ function StylesApplyToEditor(styles,editor,font,fontitalic,lexerconvert)
     editor:IndicatorSetForeground(fncall, wx.wxColour(unpack(type(indic.fncall) == type{} and indic.fncall.fg or {128, 128, 255})))
     editor:IndicatorSetStyle(varlocal, type(indic.varlocal) == type{} and indic.varlocal.st or wxstc.wxSTC_INDIC_DOTS or wxstc.wxSTC_INDIC_TT)
     editor:IndicatorSetForeground(varlocal, wx.wxColour(unpack(type(indic.varlocal) == type{} and indic.varlocal.fg or defaultfg)))
+    editor:IndicatorSetStyle(varself, type(indic.varself) == type{} and indic.varself.st or wxstc.wxSTC_INDIC_TEXTFORE)
+    editor:IndicatorSetForeground(varself, wx.wxColour(unpack(type(indic.varself) == type{} and indic.varself.fg or {255, 0, 0})))
     editor:IndicatorSetStyle(varglobal, type(indic.varglobal) == type{} and indic.varglobal.st or wxstc.wxSTC_INDIC_PLAIN)
     editor:IndicatorSetForeground(varglobal, wx.wxColour(unpack(type(indic.varglobal) == type{} and indic.varglobal.fg or defaultfg)))
     editor:IndicatorSetStyle(varmasking, type(indic.varmasking) == type{} and indic.varmasking.st or wxstc.wxSTC_INDIC_DASH or wxstc.wxSTC_INDIC_DIAGONAL)
```

**Comment by Greilachelous** [comment]
@pkulchenko Thank you for your work!

**Comment by Greilachelous** [comment]
@pkulchenko 
I've just managed to solve the **"self"** problem:
![image](https://user-images.githubusercontent.com/8689085/28750207-bf9059e2-74e3-11e7-81a7-87d12e12bdf9.png)
If you think, it would be useful for Zbrane, I gladly describe the solution based on wxwidget's (Scintilla's) code modification.

**Comment by pkulchenko** [comment]
@Greilachelous, yes, please include the diff in this ticket. You may also bring it up on scintilla maillist (https://groups.google.com/forum/#!forum/scintilla-interest) to if the fix can be accepted upstream.
