### ISSUE TITLE
Request: [LINUX ]Keep in dock option with Plank Dock

### ISSUE THREAD

**Issue by cpeosphoros** [pkulchenko/ZeroBraneStudio#779]
I don't even know how to implement that, but some applications have a "Keep in dock" option with their icons in Plank, some don't. ZB is one of those which doesn't.

Plank can be found here: https://launchpad.net/plank

**Comment by pkulchenko** [comment]
@cpeosphoros, I think it's probably too tool/platform specific to be integrated into the IDE. It seems like you may only need to copy/move the .desktop file to get the desired effect:

> I have found that Plank will only read or see programs fully if the .desktop file of any program is in /usr/share/applications.
> user-specific/non-system desktop-files should be put in "~/.local/share/applications"

This is based on the discussion here: https://answers.launchpad.net/plank/+question/253704

Note that this is likely to work only with the packaged version of the IDE as it provides .desktop file (although it's also available in zbstudio/res/zbstudio.desktop).
