### ISSUE TITLE
Autocomplete on assert

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#780]
When I call functions with known return types, autocomplete works fine.
Example:
```lua
local fd=io.open("test","r")
fd:
```
I get a popup with close,flush,lines,read,write,...

When I do the same with assert (which is a very common style in lua) ¹)
```lua
local fd=assert(io.open("test","r"))
fd:
```
autocomplete fails.

It would be very nice to get this working...

¹) See https://www.lua.org/pil/8.3.html

**Comment by pkulchenko** [comment]
@jjvbsag, should handle the `assert` now.

**Comment by jjvbsag** [comment]
@pkulchenko : manual patched my installation and it works fine now. Thanks

**Comment by pkulchenko** [comment]
Cool; thanks for the update.
