### ISSUE TITLE
No unistaller on Windows

### ISSUE THREAD

**Issue by Hekkaryk** [pkulchenko/ZeroBraneStudio#784]
Please either provide information how to safely uninstall Zero Brane Studio or include an uninstaller (there is no entry in Add/Remove Programs).

**Comment by pkulchenko** [comment]
There is nothing to uninstall on Windows as there is no modifications to the registry that are done during the installation and you can simply remove the directory that the IDE is installed to. The only change that is made outside of the installation directory is the shortcut that is created in `Start Menu/Programs`.

I'll update the README to mention this.

**Comment by Hekkaryk** [comment]
Thank you for fast reply - cheers!
