### ISSUE TITLE
Correct Indentation misbehaves

### ISSUE THREAD

**Issue by Hekkaryk** [pkulchenko/ZeroBraneStudio#785]
![screenshot_1](https://user-images.githubusercontent.com/10469839/28725146-e2b3abd6-73bc-11e7-8ec2-c5c163f3493f.jpg)
While using Correct Indentation (automatic code formatting is my only point of interest) I noticed that it does not work properly. Most notably, at random point of method call block level of indentation gets randomly increased.
This is not expected behaviour of such tool.

**Comment by pkulchenko** [comment]
> Most notably, at random point of method call block level of indentation gets randomly increased.
> This is not expected behaviour of such tool.

Your code is misformatted `{Ingredient(Ingredient("spidergland", 1)}` (you probably have additional `Ingredient(` call, which makes parenthesis unbalanced. You should not expect proper formatting on syntactically incorrect code.

**Comment by Hekkaryk** [comment]
Ah yes, thank you for pointing that out - my bad.
