### ISSUE TITLE
Request: Add "Set As Start File" and "Unset '%s' As Start File" to EditorNotebookTabs context menu

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#790]
This would be quite handy, if you have a huge project with hundred of files. Always have to navigate to a file in the project tree to change the start file is cumbersome if you already have the files in question in the editor tabs.

---
I tried self to add 
```lua
	{ ID_SETSTARTFILE, TR("Set As Start File") },
        { ID_UNSETSTARTFILE, TR("Unset '%s' As Start File"):format(startfile or "<none>") },
```
at 
```lua
notebook:Connect(wxaui.wxEVT_COMMAND_AUINOTEBOOK_TAB_RIGHT_UP
```
and started with
```lua
notebook:Connect(ID_SETSTARTFILE, wx.wxEVT_COMMAND_MENU_SELECTED,
    function()
      unsetStartFile()
      setStartFile(GetDocument(GetEditor(selection)):GetFilePath())
      saveSettings()
    end)
  notebook:Connect(ID_UNSETSTARTFILE, wx.wxEVT_COMMAND_MENU_SELECTED,
    function()
      unsetStartFile()
      saveSettings()
    end)
```
but then I struggled with the cross references in ZeroBrane. I believe, it would be a 10-minute-job for you who knows your child to complete the work.

Regards

**Comment by pkulchenko** [comment]
This is an interesting suggestion; I'll consider adding "Set As Start File" as it requires the file to be selected, but don't see a reason to add `Unset`, as it can be executed from any file (maybe only for consistency).

**Comment by pkulchenko** [comment]
It's not likely to be a 10-minute job as it requires refactoring of some of the methods to make them available to the handlers in the tab menu ;).

**Comment by jjvbsag** [comment]
OK. As I said, it's your child, you know it best. 👍 

BTW: It would also be níce to have some optical indication in the Tabs, which file is the current start file (maybe by adding an icon?)

Regards

**Comment by pkulchenko** [comment]
@jjvbsag, added to the tab menu; give it a try.

**Comment by jjvbsag** [comment]
Back at home, tested the master and works fine for me. Thanks

**Comment by pkulchenko** [comment]
@jjvbsag, great; thank you for the confirmation!
