### ISSUE TITLE
I keep making unwanted unicode characters

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#791]
This is has been happening since I started using zerobrane but it's one of those things I've gotten a bit used to but probably should report. It's probably related to keyboard layout or the way I type.

When making the `~` symbol I have to press `alt-gr + [a key left of enter] space` to make it appear but if I don't press space then I'll make `≃` which is at least visible. But sometimes I can make `\194` which is invisible in the editor. It happens occasionally that I'll index or assign variables with a hidden \194 character and then wonder why it doesn't work 

```lua
local str = "v ~= d" for i = 1, #str do print(str:byte(i,i)) end
118
194 << this one
160
126
61
32
100
```

![](http://i.imgur.com/8Dq9Z1u.png)

(v is supposed to be highlighted)

I think having a way of automatically stripping unicode characters from lua code (outside of strings and comments) or a warning of some sort would solve this problem.

**Comment by pkulchenko** [comment]
Actually, there is probably something else going on. `\194\160` is decimal representation of utf-8 character [No-Break-Space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) and it is visible as a space between `v` and `~=` (its hex code is `0xC2 0xA0 (c2a0)`).

There is probably something else going on as I don't see any issues with variable marking or execution when this character is present in the source file.

**Comment by CapsAdmin** [comment]
I figured out how I make it. It's by holding altgr and pressing space.

Because of my keyboard layout I need to hold altgr to make these symbols "{}[]~" and so if i accidentally press any other key it will make unwanted symbols. The nobreak space character is the most annoying as it's not visible.

**Comment by pkulchenko** [comment]
I can probably make show-unicode plugin to mark those symbols with indicators, but why is this a problem? That unicode symbol is valid and doesn't "break" the script when running/debugging, right?

**Comment by pkulchenko** [comment]
Another option would be to extend `striptrailingwhitespace` plugin and convert those space-like utf-8 characters to spaces upon save.

**Comment by CapsAdmin** [comment]
The problem is that `local foo = 1` is not the same as `local foo = 1`. Although it is valid Lua it's something that seems to happen only in ZeroBrane for some reason. It is my fault but I'm not sure how to stop doing this by accident.

**Comment by jjvbsag** [comment]
@CapAdmin You should try to fix the problem at its root. Either change/edit your keyboard layout, causing '~' not to be a deadkey any more. Or use a tool like AutoHotkey to make a better shortcut for '~'.
☕️

**Comment by pkulchenko** [comment]
@CapsAdmin, I'll experiment a bit to see if we can catch this in `onCharAdded` event to highlight those characters, but you may also want to consider @jjvbsag's suggestion ;).

**Comment by pkulchenko** [comment]
@CapsAdmin, I wonder what is shown in `onEditorCharAdded` event when that unicode character is added; can you add the following to the config to check:

```
package {
  onEditorCharAdded = function(self, editor, event)
    ide:Print(editor:GetCurrentPos(), event:GetKey())
  end,
}
```

If you know the set of conditions to detect the desired characters, you can update the example below to mark them with a particular indicator:

```
package {
  onEditorCharAdded = function(self, editor, event)
    ide:Print(editor:GetCurrentPos(), event:GetKey())
    -- update this --vvv-- check to detect desired unicode characters
    if event:GetKey() > 255 or string.char(event:GetKey()) ~= 'a' then return end
    if not self.indic then
      local indicname = "utf8char"
      ide:AddIndicator(indicname)
      self.indic = ide:GetIndicator(indicname)
    end
    local indicator = self.indic
    local cfg = self:GetConfig()
    local pos = editor:GetCurrentPos()-1
    local style = bit.band(editor:GetStyleAt(pos),31)
    local color = cfg and type(cfg.color) == "table" and #(cfg.color) == 3 and
      wx.wxColour((table.unpack or unpack)(cfg.color)) or editor:StyleGetForeground(style)
    editor:IndicatorSetStyle(indicator, cfg and cfg.indicator or wxstc.wxSTC_INDIC_STRIKE)
    editor:IndicatorSetForeground(indicator, color)
    editor:SetIndicatorCurrent(indicator)
    editor:IndicatorFillRange(pos, 1)
  end,
}
```

**Comment by CapsAdmin** [comment]
Note that this is a Linux specific issue. On Windows I would use ctrl alt (alt-gr also works but ctrl alt is less awkward) to make the symbols mentioned earlier but this doesn't work on Linux. I have to use alt-gr. I would say the core root of this problem is the Norwegian keyboard layout. In general it sucks for programming as many languages were designed to be written with the English keyboard layout.

As for the second package example, this is valid Lua, but some tools think it's invalid or don't handle it properly. Errors can occur at runtime.

For instance:
`local foo = 5 if foo == 5 then print("ok") end` >> ok
`local foo = 5 if foo == 5 then print("ok") end` >> nothing

The second one has a space break character after foo so it's a nil global.

break space character: `2	160`
≃ character: `5	8771` (also the syntax check on type package errors `syntaxcheckontype.lua:32: bad argument #1 to 'char' (invalid value)`)

Kate does this slightly highlighted underline for the space character which seems like a good solution to spot unusual space characters. (that's the main issue here, that I can't tell the difference)
![](http://i.imgur.com/c21mse1.png)

ZeroBrane: 
![](http://i.imgur.com/YDbozKF.png)

I think a perfect solution for me is to not allow any weird symbols outside of strings and comments. (is it possible to check if you're inside a string?) 
And for a start I would translate any strange space characters to normal space.

**Comment by jjvbsag** [comment]
> Note that this is a Linux specific issue.

For Linux there are keyboardmap-editors available, so you could create your very own keyboard layout. What about putting all the critical chars `[`, `]`, `{`, `}`, `~` ... on the numerical keypad, so there would be no need for `Alt-Gr` any more? Just trying to be more creative...

**Comment by pkulchenko** [comment]
> Kate does this slightly highlighted underline for the space character which seems like a good solution to spot unusual space characters. (that's the main issue here, that I can't tell the difference)

@CapsAdmin, that's exactly what the fragment above should do; I just wasn't sure what code to use. Try this one:

```
package {
  onEditorCharAdded = function(self, editor, event)
    if event:GetKey() ~= 160 then return end
    if not self.indic then
      local indicname = "utf8char"
      ide:AddIndicator(indicname)
      self.indic = ide:GetIndicator(indicname)
    end
    local indicator = self.indic
    local cfg = self:GetConfig()
    local pos = editor:GetCurrentPos()-1
    local style = bit.band(editor:GetStyleAt(pos),31)
    local color = cfg and type(cfg.color) == "table" and #(cfg.color) == 3 and
      wx.wxColour((table.unpack or unpack)(cfg.color)) or editor:StyleGetForeground(style)
    editor:IndicatorSetStyle(indicator, cfg and cfg.indicator or wxstc.wxSTC_INDIC_STRIKE)
    editor:IndicatorSetForeground(indicator, color)
    editor:SetIndicatorCurrent(indicator)
    editor:IndicatorFillRange(pos, 1)
  end,
}
```

> also the syntax check on type package errors syntaxcheckontype.lua:32: bad argument #1 to 'char' (invalid value)

Thanks; will fix.

**Comment by pkulchenko** [comment]
Elias, did you make any progress with the package I suggested earlier? I'd expect it to strike out No-Break-Space, but can't test this locally unfortunately.

**Comment by CapsAdmin** [comment]
Sorry I forgot to close but yes it's all fine now. :)
