### ISSUE TITLE
gideros glsl files syntax highlighting

### ISSUE THREAD

**Issue by keszegh** [pkulchenko/ZeroBraneStudio#794]
it would be good if in gideros mode the glsl (and hlsl) files could be also syntax highlighted.

**Comment by pkulchenko** [comment]
There is already glsl lexer; you may try adding `editor.specmap.glsl = "glsl"` and it should work for all files with `.glsl` extensions.

**Comment by keszegh** [comment]
thanks, that works perfectly.

**Comment by pkulchenko** [comment]
There are already mappings for `.glslf` and `.glslv` extensions, so it's possible to add `.glsl` as well, but there is no specific extension for glsl files, so I may leave it as is for now. Closing...
