### ISSUE TITLE
Runtime error during tootip showing with Gideros set as interpreter

### ISSUE THREAD

**Issue by paul-reilly** [pkulchenko/ZeroBraneStudio#796]
Windows 10 x64 with ZBS 1.60, empty User and System config files. Empty file using Gideros interpreter.

Typing:

    stage:addChild(a.b(

Results in a runtime error. Okaying continues execution of the program, Cancel or escape exits.

**Comment by pkulchenko** [comment]
Thanks for the report; checking...

**Comment by pkulchenko** [comment]
@paul-reilly, should be fixed now.

**Comment by paul-reilly** [comment]
That does fix it, thank you very much for the fast response!
