### ISSUE TITLE
Minor indentation issue

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#797]
I cant remember, where this occured in real source to me, but I at least want to report this funny behavior. So I reconstructed a small example, where I could reproduce it

This is indented correctly by ZBS
```lua
TEXT="a b c"
for w in TEXT:gmatch"%S+" do
	print(w)
end
```

This one not (observe the missing space before the do):
```lua
for w in TEXT:gmatch"%S+"do
print(w)
end
```

Both are legal code

**Comment by pkulchenko** [comment]
Interesting case; should be fixed now (along with a couple of similar ones).
