### ISSUE TITLE
How do I make "ZeroBrane Studio" style permanent

### ISSUE THREAD

**Issue by tastyminerals** [pkulchenko/ZeroBraneStudio#798]
In `user.lua` I currently have the following setup:
```lua
-- set theme
styles = loadfile('cfg/tomorrow.lua')('TomorrowContrast')
stylesoutshell = styles -- apply the same scheme to Output/Console windows
styles.auxwindow = styles.text -- apply text colors to auxiliary windows
styles.calltip = styles.text -- apply text colors to tooltips
```

But I prefer "ZeroBrane Studio" style more. I am only able to pick it via `scheme-picker.lua`. How to make it permanent?

**Comment by pkulchenko** [comment]
@tastyminerals, you can simply remove these 4 lines and you should get the default "ZeroBrane Studio" style.
