### ISSUE TITLE
[My fault] Dot in LUA_(C)PATH(_5_3) of environmental variables

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#802]
> The Dot '.' for path/cpath in `LUA_PATH`/`LUA_CPATH`/`LUA_CPATH_5_3` would be replaced to 'ZeroBrane Studio\ZeroBraneStudio\myprograms', not the folder of **zbstudio.exe** nor **lua53.exe**.
> It's hard to notice this, when where I want to add '53' suffix for `require'iuplua'` to 'iuplua53' by append LUA_CPATH like `.\bin\clibs53\?53.dll;` or `.\clibs53\?53.dll;`.
> 
> I didn't find an easy way neither by modify environmental variables nor package.cpath, and have to use absolute path... So 😭 
> 
> 

Sorry, I should set Project directory first. "ZeroBraneStudio\myprograms" is the default one.

**Comment by pkulchenko** [comment]
> Sorry, I should set Project directory first. "ZeroBraneStudio\myprograms" is the default one.

Yes, it's set to the current project directory, such that if you put the library binaries there, they should be found as if you ran the Lua interpreter from that folder.
