### ISSUE TITLE
Path of loader like 'A.B' failed

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#803]
I use `require'iup.iuplua'` for `iuplua53.dll` (I use `LUA_CPATH_5_3` to add suffix `53` like `.\?53.dll`) which relay on `iup.dll`, and they are in the same directory `iup` (and many other related `iup_XXX.dll`s inside).
The require/loader would auto expand 'A.B' for 'A\B' (in windows), and *could* find `iuplua53.dll` in `iup` directory, but failed to load `iup.dll` prompting 'can't find the specific module'.
1. If use  `require'iup\\iuplua'` has the same case.
2. If not use `iup` directory and use `require'iuplua'` only, it is fine. So I think there is something wrong?

---

Find that:
1. `iup.dll` should near with `lua.exe`, and can't with `iuplua.dll` (even `require'iuplua'` without `iup` directory)
2. Can't use `require'iup.iuplua'` to indicate `iuplua.dll` under `iup` directory.

Don't know why, so 😞

---
Also find:

> Require translates the dot into another character, usually the system's directory separator. 
After the translation, require searches for the resulting name like any other name.
> in `<Programming in Lua 4th Edition \ Submodules and Packages>`

But maybe can't use like this for C libraray as it means `luaopen_a_b`?

**Comment by pkulchenko** [comment]
This doesn't seem to be an issue with the IDE, but rather a feature of how Windows searches for dynamic libraries. When you don't have a sub-directory, then your libraries are all in the same folder, which is set to be the current folder by the IDE and, as the result, the windows loader can find the libraries there as it's one of the locations it checks.

When the iup libraries are in the subfolder, the Lua interpreter can still find the libraries you load with `require`, but other DLLs that they depend upon can't be found as the Windows doesn't "know" that it needs to check that folder. See [this page](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx), especially the "Standard Search Order for Desktop Applications" section.

The easiest way to fix is to add the path in which `iup.dll` resides to `PATH`. You don't need to do it permanently, as you can set it from the script that you use to launch the application or start the IDE.

**Comment by robertlzj** [comment]
I see, it's about **dynamic libraries search method** of *Windows* (not the *IDE* nor *Lua* interpret) especially for "other DLLs that they depend upon".

---
Success by using `PATH` environment variable, it's easy:

> With `.\iup\iup.dll`, `.\iuplua\iuplua51.dll`, `.\lua.exe`, `.\test.lua`
> ```bat
> set Path=.\iup
> lua.exe test.lua
> ```
> ```lua
> package.cpath='.\\iuplua\\?51.dll;'
> require'iuplua'
> ```
> 

But can't use
```lua
package.cpath='.\\iuplua\\?.dll;'
require'iuplua51'
```
Saying "error loading module 'iuplua51'".
Means? error to load `iup.dll`, and must keep module name `iuplua` clean, as it would be used inside `iuplua.dll`?

**Comment by pkulchenko** [comment]
> But can't use

```lua
package.cpath='.\\iuplua\\?.dll;'
require'iuplua51'
```

> Saying ( found but ) "error loading module 'iuplua51'". Means? error to load iup.dll, and must keep module name iuplua clean, as it would be used inside iuplua.dll?

This doesn't work for a different reason. When Lua loads a module with require, it looks for `luaopen_modulename` function in the module to execute, so when you load it as `iuplua`, it looks for `luaopen_iuplua` and finds it (even though it's in iuplua51.dll file), but when you load it as iuplua51, it looks for `luaopen_iuplua51` function and fails to find it (which triggers the message you get).

**Comment by robertlzj** [comment]
Oh, I see. Module name used for search _file_ name is different from executing of _entrance_ name.
Thank you ~~~
