### ISSUE TITLE
Feature Request. Enhance  Auto Complete Identifier for discontinuous match

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#805]
Dscontinuous match means: 'ac' matches '...a...c...'

Tried some work:
> Find function `CreateAutoCompList` in `src\editor\autocomplete.lua`.
> Add some functions like bellow - replace from `if var:find(key, 1, true) == 1` to `if match(var,key)` - would work, but *only* for local/global variables. Not sure mechanism for other identifier.
> ```'lua
> function match(var,key)
> 	local find,sub=string.find,string.sub
> 	local pos_var,pos_key,len_key=1,1,#var+1
> 	while pos_var<len_key do
> 		pos_var=find(var,sub(key,pos_key,pos_key+1),pos_var,true)
> 		if not pos_var then return false end
> 		pos_key,pos_var=pos_key+1,pos_var+1
> 	end
> 	return true
> end
> ```
> Test:
> ```'lua
> local var='abc'
> assert(
> 	false==match(var,'x')
> 	and true==match(var,'a')
> 	and true==match(var,'ab')
> 	and true==match(var,'abc')
> 	and false==match(var,'abcd')
> 	and true==match(var,'b')
> 	and true==match(var,'bc')
> 	and false==match(var,'bcd')
> )
> ```

Some more sort work could be done to list close matches first.

**Comment by pkulchenko** [comment]
This is exactly how it currently works with the exception that the first character in the match is anchored at the first position, so `pit` matches `print`, but `it` doesn't. I think this is fairly typical and expected as the first character is usually what is being typed first.

If you want real fuzzy matching, you can use `Search | Navigate | Insert Library Function` and type `int` there; it will offer `print` as the first choice.

**Comment by robertlzj** [comment]
Hum, yes, it works for API keyword already.
But other identifier not, and very strange, with the function added above some identifier could auto complete in some case. Seems I didn't understand the work way of `autocomplete.lua`.  😕

**Comment by pkulchenko** [comment]
Can you give an example? Maybe it doesn't work for a different reason?

**Comment by robertlzj** [comment]
```lua
local objectNewCore
objectNew=nil
```
Now, expecting type of `oNC` to be expand to `objectNewCore`, `oN` to `objectNew` + `objectNewCore`.
But currently need to type all the word `objectNew` especially `objectNewCore` is in front of `objectNew` in the list and when there is many items in the list so don't want to use array key.

**Comment by pkulchenko** [comment]
Yes, the variables are handled a bit differently; the variables are filtered using direct match, so `onc` will not match `objectNewCore`. 

It implements what's described as `strategy=0` in the documentation: https://studio.zerobrane.com/doc-general-preferences#auto-complete-and-tooltip. It applies to the auto-complete API suggestions, but the variables are suggested using the simplest (and fastest) strategy.

I'll consider implementing similar strategies for variables, but it's likely that the default will stay as the current (simplest) method.

**Comment by robertlzj** [comment]
Yes, I have found "direct match" strategy as mentioned above in my tries.
That is `if var:find(key, 1, true) == 1`, and some?many other things I don't understand yet.
>  And simply replace it to my `match(var,key)` above won't help of couse. It's more complex as there are some strategy I just know. 

Maybe `strategy = 1` satisfied if fit variables.
About the strategy, I think support only context related content for fuzzy match is fast?

**Comment by pkulchenko** [comment]
That's the right place to check and it would need to be modified to support more complex strategies.

Fuzzy match is not a good fit here as it's going to be too expensive, but implementing strategies 1 or 2 should be possible.

**Comment by robertlzj** [comment]
Nice, can't to wait~

**Comment by pkulchenko** [comment]
This has been implemented, but is disabled by default. You can use `acandtip.symbols=2` in the config to enable.

**Comment by robertlzj** [comment]
Seems not work. I switch on `acandtip.symbols = true` from first, now change to `acandtip.symbols = 2` didn't affect.
~~Is there any inter rely between them?~~ I use only `acandtip.symbols` in `user.lua` but still not work.
I search `acandtip.symbols` in IDE, find there is one instance in `autocomplete.lua` which use it as condition but only determine if it is `true`.

**Comment by pkulchenko** [comment]
Did you (1) apply the patch, (2) add `acandtip.symbols=2` to the config, (3) start the IDE, (4) type `onc` on line 3 after the following two lines?

```
local objectNewCore
objectNew=nil
```

**Comment by robertlzj** [comment]
Sorry, I didn't apply the patch.
Test OK.

There is a little discount on strategy, and some more expand ( just my lateral thinking, hope could help ):
- Seems didn't support method 1.
- I think **case sensitive** is usefull too.
	If user use upper case, it should be matched explicitly with the same case.
	So `oNC` won't get `oxxnxxc`.
	Similar, if contain both, and the lower case pattern after upper case should be matched explicitly by case.
	So `aBc` will match `aBxc` and won't match `aBC` or `aBDc`.
- I disable `:gsub("(%w)", function(s) return "["..s:lower()..s:upper().."]" end)` for walkaround.
	Hope release version could change.
	
Without consideration of speed, I think one flexible and auto adjustment **strategy** is nice ( and enough? ).
- Use less count but high identifiable property to refer to whole target.
- Continued with `aBc`, it could match from high **priority** to low.
	That is: `aBc`, `aBC` / `aB_c`, `aBDc`.
	In fact `c` could be some suffix, like plural, like `Gi` for `GetTransporting`  distinguish from `GetTransported`.

**Comment by pkulchenko** [comment]
Yes, it doesn't support method 1 as I ran into issues putting it into one pattern. I don't think it's worth doing it as 0 and 2 should be sufficient.

I think make things case sensitive for the upper case is a good idea, but lowercase should match the upper case as well. Adding the priority would complicate things a bit, so I'm not sure I'd apply it here, but I do have something similar implemented in the command bar.

**Comment by robertlzj** [comment]
Yes, a little more complicate, but if strategy is universal to apply, and interface is abstract enough, then it will be easy to migrate and use. 😄

**Comment by pkulchenko** [comment]
Updated to enable case-sensitive matching for uppercase characters.
