### ISSUE TITLE
Debugging fails after missing mobdebug when LUA_PATH_5_3 is set

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#806]
I'm not sure how and why, ZBS‘s debug won't work, prompting can't find 'mobdebug', and list the search paths, not contain 'lualibs\mobdebug'.
- Could Run, can't Debug.
- Olny in Lua 5.3, not in Lua (5.1)

Tried:
- Unpack & overwrite install package again / Delete `LUA_PATH` , same result.
- Use an old version, success. Then the lasted version success too.
- Also, when both version opened, Output of first open one will get 'Debugging session' information, even start debug from the later one.  

Just mention, meaningless, hope won't happen.

**Comment by pkulchenko** [comment]
I'm not sure why it wouldn't find `mobdebug`, but I'd need to see how exactly you run them and what the content of the Output window in each of the instances.

You need to make sure you set different port numbers in each instance, otherwise the debugging won't work, as described here: https://studio.zerobrane.com/doc-faq#how-do-i-start-two-zerobrane-studio-instances-to-debug-two-applications-at-the-same-time

**Comment by robertlzj** [comment]
I didn't set any configures. Because I start two ZBS just by chance for checking the problem above, not really with any demand. And the two ZBS are different version.
I think there won't be any permanent effect to each other after close both and open only single one. So I think it's meaningless.
But now the new version IDE can't start debug for lack of `mobdebug` ~~if didn't open an older version~~.
Still record bellow:
1. Open new version (MobDebug 0.7) with default file, F5 to debug.
> ```
> Program starting as '"C:\ProgramFiles\ZeroBraneStudio\bin\lua53.exe" -e "io.stdout:setvbuf('no')" "C:\Users\ROBERT~1\AppData\Local\Temp\.A765.tmp"'.
> Program 'lua53.exe' started in 'C:\Users\RobertLin\OneDrive\文档' (pid: 24660).
> C:\ProgramFiles\ZeroBraneStudio\bin\lua53.exe: C:\Users\ROBERT~1\AppData\Local\Temp\.A765.tmp:1: module 'mobdebug' not found:
> 	no field package.preload['mobdebug']
> 	no file '.\mobdebug.lua'
> 	no file '.\mobdebug53.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\lua\mobdebug.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\lua\mobdebug\init.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\mobdebug.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\mobdebug\init.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\..\share\lua\5.3\mobdebug.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\..\share\lua\5.3\mobdebug\init.lua'
> 	no file '.\mobdebug.lua'
> 	no file '.\mobdebug\init.lua'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin/clibs53/mobdebug.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\mobdebug.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\..\lib\lua\5.3\mobdebug.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\loadall.dll'
> 	no file '.\mobdebug.dll'
> 	no file '.\mobdebug.dll'
> 	no file '.\mobdebug53.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\clibs\mobdebug53.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\clibs53\mobdebug.dll'
> 	no file 'C:\ProgramFiles\ZeroBraneStudio\bin\clibs53\mobdebug53.dll'
> stack traceback:
> 	[C]: in function 'require'
> 	C:\Users\ROBERT~1\AppData\Local\Temp\.A765.tmp:1: in main chunk
> 	[C]: in ?
> Program completed in 0.04 seconds (pid: 24660).
> ```
2. Open old version (MobDebug 0.634) with default file, F5 to debug.
   - Output on old version IDE
![image](https://user-images.githubusercontent.com/7419030/30517130-cf8bfe9e-9b87-11e7-99ee-23e8f12bb03a.png)
   - Output on new version IDE (follow result of step 1)
![image](https://user-images.githubusercontent.com/7419030/30517133-ee171326-9b87-11e7-8e6d-5bcbe674aee2.png)
There is some line miss place as #807 

3. Still can't debug on new version IDE this time however remain or close old version.

And, there maybe something special for me.

> Because the _run_ / _start folder_ of IDE seems can't be put under path contain non-ASCII characters, I use symbol link from its actual folder which path contain non-ASCII to a simplified path with pure ASCII. But 

I think this wont harm, and everything is fine ago.

**Comment by pkulchenko** [comment]
```
        no file '.\mobdebug.lua'
	no file '.\mobdebug\init.lua'
	no file 'C:\ProgramFiles\ZeroBraneStudio\bin/clibs53/mobdebug.dll'
```

If I remove `mobdebug.lua` completely, then the following is shown for me:

```
	no file './lua/mobdebug.lua'
	no file './lua/mobdebug/init.lua'
	no file 'D:\users\paul\ZeroBraneStudio\lualibs/mobdebug/mobdebug.lua'
	no file 'D:\users\paul\ZeroBraneStudio\lualibs/mobdebug.lua'
	no file 'D:\users\paul\ZeroBraneStudio\lualibs/mobdebug/mobdebug/init.lua'
	no file 'D:\users\paul\ZeroBraneStudio\lualibs/mobdebug/init.lua'
	no file 'D:\users\paul\ZeroBraneStudio\bin/clibs53/mobdebug.dll'
```

Note that there are checks for `lualibs/mobdebug/*`, because that's where it's expected to be and in your case it's not present.

Can you try the following:
1. Check if you get the same issue with Lua 5.2 interpreter.
2. Run the following script with Lua 5.3 interpreter (Run, not Debug):

```
print(package.path)
print(os.getenv('LUA_PATH'))
```

**Comment by robertlzj** [comment]
Yes, I noticed the searching path missed.
1. Run Lua 5.3
> ```
> .\?.lua;.\?53.lua;C:\ProgramFiles\ZeroBraneStudio\bin\lua\?.lua;C:\ProgramFiles\ZeroBraneStudio\bin\lua\?\init.lua;C:\ProgramFiles\ZeroBraneStudio\bin\?.lua;C:\ProgramFiles\ZeroBraneStudio\bin\?\init.lua;C:\ProgramFiles\ZeroBraneStudio\bin\..\share\lua\5.3\?.lua;C:\ProgramFiles\ZeroBraneStudio\bin\..\share\lua\5.3\?\init.lua;.\?.lua;.\?\init.lua;
> ;;./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/init.lua
> ```
1. Run Lua, Lua 5.2 is fine

> ```
> ;.\?.lua;C:\ProgramFiles\ZeroBraneStudio\bin\lua\?.lua;C:\ProgramFiles\ZeroBraneStudio\bin\lua\?\init.lua;;./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/init.lua
> ;;./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/?/init.lua;C:\ProgramFiles\ZeroBraneStudio\lualibs/?/init.lua
> ```
>

**Comment by pkulchenko** [comment]
Do you have `LUA_PATH_5_3` set outside of the IDE by any chance?

**Comment by robertlzj** [comment]
Yes, I have. Just add it days around for checking `iuplua.dll`, `iup.dll` problem #803.
Haha, that it is the problem?!

**Comment by pkulchenko** [comment]
Yes, I think it takes precedence over LUA_PATH settings and the IDE adds there debugging paths, so they end up not seen by the Lua 5.3 interpreter. I'll have to think if this needs to be handled better to avoid this problem in the future...

No, I think LUA_CPATH is fine.

**Comment by pkulchenko** [comment]
I pushed several changes that should fix the debugging even when `LUA_PATH_5_3` or `LUA_PATH_5_2` variables are set.
