### ISSUE TITLE
Error when script has empty line at the beginning of script

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#807]
![image](https://user-images.githubusercontent.com/7419030/30512098-be154558-9b19-11e7-806a-d8358c74eadd.png)
When Run, error line prompted is correct.

**Comment by pkulchenko** [comment]
I can't confirm this; I have exactly the same script and get the following after starting debugging and then using F5:

```
Program completed in 0.77 seconds (pid: 6452).
程序/测试.lua:5: assertion failed!
stack traceback:
	[C]: in function 'assert'
	程序/测试.lua:5: in main chunk
Debugging session completed (traced 0 instructions).
```

I get the same result when I'm stepping through the file...

**Comment by robertlzj** [comment]
I press F5 directly, seems every position (actual stop position of breakpoint) give by debugger is miss placed some lines as many as beginning empty lines.

I'll test next time after my system reboot. Close and re-open IDE won't solve this.

Also I still have #806 issue, the new version IDE can't start debug for lack of `mobdebug` if didn't open an older version. Maybe related.

**Comment by pkulchenko** [comment]
What settings do you have in `user.lua`? Where do you have a breakpoint? Can you describe *exact* steps? For example, this is what I've done:

1. Open the file with the script shown above (5 lines, first two lines are empty).
2. Press F5; the green cursor is shown on line 3
3. Press F5; the script finishes and the message from failed assert shows line 5, as expected

> Also I still have #806 issue, the new version IDE can't start debug for lack of mobdebug if didn't open an older version. Maybe related.

I don't think so, as it fails to load the debugger, not run it.

**Comment by robertlzj** [comment]
I disable `user.lua` ( by changing file name ) to narrow down the possibilities.
1. Open ZBS with default last file and its breakpoint at line 5.
![image](https://user-images.githubusercontent.com/7419030/30518229-6ec144a2-9baa-11e7-9461-6ea274c81df8.png)
2. F5 to start debug, and get break at line 3.
![image](https://user-images.githubusercontent.com/7419030/30518235-86a40cc6-9baa-11e7-93da-0c1919fb4511.png)
3. Click Step Into, two times, get pointer at line 3 all the time, get 'assertion failed' in Output windows, and debug complete.
![image](https://user-images.githubusercontent.com/7419030/30518252-d43eae64-9baa-11e7-9b37-5ce6f2451507.png)
Lua, Lua 5.2, Lua 5.3 all the same result.

**Comment by pkulchenko** [comment]
This is very strange and the only thing I can suspect is something funky with line endings. Can you run this command in the console and include a screenshot with the line endings: `ide:GetEditor():SetViewEOL(1)`?

Can you also email me the file you are testing it on as there may be something else in the file that is not visible on the screenshot?

Also, when you set `debugging.verbose=true` in the config, what do you see in the output window after stepping to line 5?

**Comment by robertlzj** [comment]
And this only happen in Debug. In Run, assertion line position giving is correct.
Run 
![image](https://user-images.githubusercontent.com/7419030/30518369-befc9fb2-9bae-11e7-8746-9db9a1a33390.png)

Some new test with _different_ empty line.

> - Open ZBS 
> ![image](https://user-images.githubusercontent.com/7419030/30518323-7f371ff2-9bad-11e7-9b45-d59077a6f324.png)
> - F5 
> ![image](https://user-images.githubusercontent.com/7419030/30518325-88422592-9bad-11e7-9afb-2a083b402724.png)
> - F10
> ![image](https://user-images.githubusercontent.com/7419030/30518326-91760656-9bad-11e7-8447-b96911772723.png)
> - F10 Complete
> ![image](https://user-images.githubusercontent.com/7419030/30518327-a5b17556-9bad-11e7-9dae-3b51dfdc2a80.png)
> 
Other case only different empty lines.

> - Open
> ![image](https://user-images.githubusercontent.com/7419030/30518347-3b70a364-9bae-11e7-9db3-fb37519385b0.png)
> - F5 
> ![image](https://user-images.githubusercontent.com/7419030/30518352-4a23d64c-9bae-11e7-901e-5d9d28876ef8.png)
> - F10
> ![image](https://user-images.githubusercontent.com/7419030/30518353-520b1cbc-9bae-11e7-992d-2edd175fbe4b.png)
> - F10 Complete
> ![image](https://user-images.githubusercontent.com/7419030/30518356-5b8f7a08-9bae-11e7-97c8-e4ee9ccc1cd6.png)

- Result of `ide:GetEditor():SetViewEOL(1)`
![image](https://user-images.githubusercontent.com/7419030/30518334-cf47e526-9bad-11e7-8754-9fde4d112073.png)
- Result of `debugging.verbose=true`
Nothing special on the latest test. 
![image](https://user-images.githubusercontent.com/7419030/30518363-a1b4f904-9bae-11e7-9b7e-01ac8e714948.png)

**Comment by pkulchenko** [comment]
> Result of debugging.verbose=true

My apologes, this should be `debugger.verbose=true` (and restart the IDE).

**Comment by robertlzj** [comment]
Result of `debugger.verbose=true`
![image](https://user-images.githubusercontent.com/7419030/30518430-a3bd4a60-9bb0-11e7-84ef-fcefb190bd7f.png)

**Comment by pkulchenko** [comment]
I have been able to reproduce this, but it is indeed related to the previous issue as the file loading failed in your case ("cannot open file...") and wasn't failing in my case, so the different branches in the debugger were used.

There was an issue with handling code fragments that started with spaces (when they were not loaded from a file), which should be fixed with the following patch (line numbers may be a bit off, but close):

```diff
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index 23a4705..40510c2 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -1401,9 +1404,9 @@ local function handle(params, client, options)
       elseif command == "reload" then
         client:send("LOAD 0 -\n")
       elseif command == "loadstring" then
-        local _, _, _, file, lines = string.find(exp, "^([\"'])(.-)%1%s+(.+)")
+        local _, _, _, file, lines = string.find(exp, "^([\"'])(.-)%1%s(.+)")
         if not file then
-           _, _, file, lines = string.find(exp, "^(%S+)%s+(.+)")
+           _, _, file, lines = string.find(exp, "^(%S+)%s(.+)")
         end
         client:send("LOAD " .. tostring(#lines) .. " " .. file .. "\n")
         client:send(lines)
```

**Comment by robertlzj** [comment]
Nice, pass test.
