### ISSUE TITLE
Can't capture __gc invoking in debug

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#808]
```lua
a=setmetatable({},{__gc=function()
		print'GC'
	end})
a=nil
collectgarbage("collect")
print'Done'
```

Will never break at __gc. Can't Step into neither.
![image](https://user-images.githubusercontent.com/7419030/30545434-2adeef9c-9cbc-11e7-8bc2-d6ced7e63ece.png)

**Comment by pkulchenko** [comment]
This is because Lua doesn't generate `debug.hook` calls from `__gc` handlers. It is easy to verify with the following script:

```lua
a=setmetatable({},{__gc=function()
    print'GC'
	end})
a=nil
debug.sethook(function(...) print(...) end,"clr")
collectgarbage("collect")
print'Done'
```

I get no events generated on line 2:

```
return	nil
line	6
call	nil
GC
return	nil
line	7
call	nil
call	nil
return	nil
Done
return	nil
return	nil
return	nil
```

This looks to be "by-design", as I get the same results in Lua 5.2 and Lua 5.3 interpreters I checked.

**Comment by robertlzj** [comment]
Although there is no GC event for debug, but I think IDE could still jump to that line where error happens at the line in __gc function as normal fails told by debugger.

```lua
setmetatable({},{__gc=function() assert(false) end})
collectgarbage("collect")
```
Line 1 will trigger assertion failed as showing bellow, but double click it from Output window didn't navigate to that line.
`error in __gc metamethod (C:\Users\...\issue.lua:1: assertion failed!)`

**Comment by pkulchenko** [comment]
> error in __gc metamethod (C:\Users\...\issue.lua:1: assertion failed!)

Is this how the path really looks or did you remove some of the characters? What Lua version interpreter is that? Usually, when long names are trimmed, `...` is added at the beginning, but in this case its looks to be in the middle...

**Comment by robertlzj** [comment]
Haha, I removed some path. You're so  careful.

Lua 5.3

Currently debug died silently, and something wrong happened in GC, where I use assert.
From Local console I can see `error in __gc metamethod (C:\Users...\N.lua:436: assertion failed!)` after using `collectgarbage("collect")`, but no any other sign, debug just die without error prompt.

**Comment by pkulchenko** [comment]
I get this in the Output, which is what I'd expect (also Lua 5.3):

```
Debugging session started in 'D:\users\paul\somepath\'.
error in __gc metamethod (gc2.lua:1: assertion failed!)
stack traceback:
	[C]: in function 'collectgarbage'
	gc2.lua:2: in main chunk
Debugging session completed (traced 0 instructions).
```

Although this only happens if you get the script started from the IDE; if the script is started outside of the IDE, then the output goes to the console (unless redirected), so won't be seen in the IDE.

**Comment by robertlzj** [comment]
Yes, I'll get complete message from Output
```
Debugging session started in 'C:\Users\RobertLin\OneDrive\文档\'.
Program completed in 0.41 seconds (pid: 23336).
error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!)
stack traceback:
	[C]: in function 'collectgarbage'
	C:\Users\RobertLin\OneDrive\文档\issue.lua:2: in main chunk
Debugging session completed (traced 0 instructions).
```

I mean double click `error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!)` won't jump to line 1 as other usually do.

And I update some doubt when debug died silently, I'll have a try first.

**Comment by pkulchenko** [comment]
> I mean double click error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!) won't jump to line 1 as others usually do.

I've tried on various files (including those in a folder with a similar name) and it works for me.

Can you apply the following patch to see what name is being activated and the result:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index 59e83ad..fa8ca50 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -372,6 +372,7 @@ local function activateByPartialName(fname, jumpline, jumplinepos)
     or FileTreeFindByPartialName(fname)
 
   local editor = LoadFile(name or fname,nil,true)
+ide:Print("activate", name, fname, editor)
   if not editor then
     local ed = GetEditor()
     if ed and ide:GetDocument(ed):GetFileName() == (name or fname) then
```

**Comment by robertlzj** [comment]
Using sample
```lua
setmetatable({},{__gc=function() assert(false) end})
collectgarbage("collect")
```
Get output
```
Program 'lua53.exe' started in 'C:\Users\RobertLin\OneDrive\文档' (pid: 32136).
Debugging session started in 'C:\Users\RobertLin\OneDrive\文档\'.
Program completed in 0.47 seconds (pid: 32136).
error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!)
stack traceback:
	[C]: in function 'collectgarbage'
	C:\Users\RobertLin\OneDrive\文档\issue.lua:2: in main chunk
Debugging session completed (traced 0 instructions).
```
- Click line `error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!)
` get, `activate	nil	error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua	nil`
- Click line `C:\Users\RobertLin\OneDrive\文档\issue.lua:2: in main chunk
` get, `activate	C:\Users\RobertLin\OneDrive\文档\issue.lua	C:\Users\RobertLin\OneDrive\文档\issue.lua	userdata: 0647f688 [wxStyledTextCtrl(06939848, 526)]`
- Click other lines wont get anything.

**Comment by robertlzj** [comment]
Tried again with default (empty) `user.lua`. The same result as above.
- Picture:![image](https://user-images.githubusercontent.com/7419030/30649294-7c1a1a8e-9e52-11e7-975f-75bb653fd18d.png)
- Text:
  ```
  Debugging session started in 'C:\Users\RobertLin\OneDrive\文档\'.
  error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua:1: assertion failed!)
  stack traceback:
  	[C]: in function 'collectgarbage'
  	C:\Users\RobertLin\OneDrive\文档\issue.lua:2: in main chunk
  Debugging session completed (traced 0 instructions).
  Program completed in 1.95 seconds (pid: 23236).
  activate	nil	error in __gc metamethod (C:\Users\RobertLin\OneDrive\文档\issue.lua	nil
  activate	C:\Users\RobertLin\OneDrive\文档\issue.lua	C:\Users\RobertLin\OneDrive\文档\issue.lua  	userdata: 05026d10 [wxStyledTextCtrl(052e6e20, 526)]
  ```
And, when Run, with the patch could get similar.
- Picture: ![image](https://user-images.githubusercontent.com/7419030/30649476-f4be7282-9e52-11e7-9871-e1c5b4284c70.png)
- Text: (Can't copy/paste which has messy characters)

**Comment by pkulchenko** [comment]
It happens because of the "error in __gc method" message in the error as it's different from the error format in all other cases. The last two lines in this path should fix this:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index 59e83ad..ce30baf 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -391,16 +391,14 @@ local function activateByPartialName(fname, jumpline, jumplinepos)
 end
 
 local jumptopatterns = { -- ["pattern"] = true/false for multiple/single
-  -- <filename>(line,linepos):
-  ["%s*(.-)%((%d+),(%d+)%)%s*:"] = false,
-  -- <filename>(line):
-  ["%s*(.-)%((%d+).*%)%s*:"] = false,
   --[string "<filename>"]:line:
   ['.-%[string "([^"]+)"%]:(%d+)%s*:'] = false,
-  -- <filename>:line:linepos
+  -- <filename>:line:linepos -- this is used in some analyzers, like LuaCheck
   ["%s*(.-):(%d+):(%d+):"] = false,
   -- <filename>:line:
   ["%s*(.-):(%d+)%s*:"] = true,
+  -- error in __gc metamethod (<filename>:line:...
+  ["%((.-):(%d+)%s*:"] = false,
 }
 
 out:Connect(wxstc.wxEVT_STC_DOUBLECLICK,
```

**Comment by robertlzj** [comment]
Yes, it works. Thank you~
