### ISSUE TITLE
AppsKey not work correctly

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#809]
I use keyboard AppKey to pop context right menu.
But it is not the same as right click.
I select a identifier ( both was highlight by plugin `highlightselected.lua` ) , and try to rename all the instance, but only one was operated.
- Use AppKey
![image](https://user-images.githubusercontent.com/7419030/30545520-737af660-9cbc-11e7-9d02-5224cf4c1685.png)
- Use right click
![image](https://user-images.githubusercontent.com/7419030/30545731-14051606-9cbd-11e7-9c25-bfad9a77c0fe.png)

Not to carp, not big problem really, and hope easy to fix.

**Comment by pkulchenko** [comment]
This usually means that no variables could be found in the reported position.

Could you apply the following patch and show me the results reported when the right click and the AppKey are used:

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 5a9ea78..cb8fb6b 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -1469,6 +1469,7 @@ function CreateEditor(bare)
       local point = editor:ScreenToClient(event:GetPosition())
       -- capture the position of the click to use in handlers later
       pos = editor:PositionFromPoint(point)
+ide:Print(pos, point:GetX(), point:GetY())
 
       local _, _, instances = getPositionValues()
       local occurrences = (not instances or #instances == 0) and ""
```

**Comment by robertlzj** [comment]
Using example above.
- AppKey always get `0	-275	-100`
- Right click changes, like `3	100	11`, `0	81	12`.

**Comment by pkulchenko** [comment]
> AppKey always get 0 -275 -100, no matter where is the mouse.

Yes, that's what I suspected, it seems to be reported at the top-left corner of the application, so it always matches position 0 in the editor, which is probably not where you'd expect it to be.

You can test the following patch to see if it produces better behavior. When the reported position is outside the editor, the current cursor position will be used:

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 5a9ea78..6ab50d7 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -1469,6 +1469,7 @@ function CreateEditor(bare)
       local point = editor:ScreenToClient(event:GetPosition())
       -- capture the position of the click to use in handlers later
       pos = editor:PositionFromPoint(point)
+      if pos == 0 and (point:GetX() < 0 or point:GetY() < 0) then pos = nil end
 
       local _, _, instances = getPositionValues()
       local occurrences = (not instances or #instances == 0) and ""
```

**Comment by robertlzj** [comment]
Test OK!
Thank you!

**Comment by pkulchenko** [comment]
Just to track it, this appears to be a wxwidgets issue discussed in this ticket: https://trac.wxwidgets.org/ticket/17969
