### ISSUE TITLE
Local console didn't work the same way in Some case compare to main code

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#810]
- ```lua
  setmetatable({},{__gc=function() print'GC' end})
  collectgarbage("collect") --break here then use Local console
  --Lua 5.3
  ```
  Set break point at line 2, when break, call `collectgarbage("collect")` from Local console, this won't trigger __gc, but the same fragment at main code line 2 in next step will do.

- This case is different!
  ```Lua
  setmetatable({},{__gc=function() print'GC' end})
  _=1,2 --Need two? multiple assignments, strange...
  collectgarbage("collect")
  ```
  Which can trigger GC from Local console using `collectgarbage("collect")`.

**Comment by pkulchenko** [comment]
The Local console is executed using LuaJIT interpreter, which doesn't implement __gc even when Lua5.2 compatibility is turned on. You'll get the same result if you run this script using "Lua" interpreter in the IDE (which is really LuaJIT).

**Comment by robertlzj** [comment]
OK. But in case 2 above, `collectgarbage("collect")` used at Local Console take effect..

Just repeat. A simplified sample
```lua
setmetatable({},{__gc=function() print'GC' end})
_=1,2 --break here then use Local console 'collectgarbage("collect")'
    --  Need two? multiple assignments, strange...
```

**Comment by pkulchenko** [comment]
No, if you are debugging, then it's not Local, but Remote console and any command is executed in the context of the application, which in this case running Lua 5.2 or Lua 5.3 (depending on your Interpreter settings). If you set it to Lua 5.1, then `GC` is not printed for me.

**Comment by robertlzj** [comment]
Oh, sorry, I mean 'Remote console' in debug. I had confused/mistook all of them to 'Local console'.
All the code discussed above is in IDE, expect a few used in Console after break in debug.

So, the issue is established, after I have change all of them from title to comments.
That is, Remote console running in the context is not equal to run it directly in IDE content. Such as (again but a little simplified):
```lua
setmetatable({},{__gc=function() print'GC' end})
_=1	--Single assignments used to compare with next line.
_=2,3--Need two? multiple assignments.
-- Set break after previous line, then call 'collectgarbage("collect")' in Remote console, won't cause GC
print'anthing here is OK just after multiple assignments.'
-- Set break / Step after previous multiple assignments, then call 'collectgarbage("collect")' in Remote console, will cause GC
collectgarbage("collect")
--Lua 5.3
```

**Comment by pkulchenko** [comment]
I get GC printed when I stop on the `print...` line (whether by stepping or using a breakpoint) and run `collectgarbage("collect")` in the Remote console.

In general, it's not too surprising that there are some differences between running commands in the Console and executing them in a script as each command you run gets evaluates using "loadstring" and then executed, which has a different memory layout than executing a script, so may have different GC results.

**Comment by robertlzj** [comment]
Yes, you get "GC printed when I stop on the `print...` " is based on fragment `_=2,3` and won't in other case like single assignment or so.
 
This problem begins from using `collectgarbage("collect")` in Remote console won't work which I didn't realize, then it could work in some case like multiple assignments. So confused.
Now I think I can't rely on Remote console in some? case.

**Comment by pkulchenko** [comment]
I think there are going to be *some* differences (for example, because of the `loadstring` evaluation I mentioned earlier), but I'm not sure how much it's an issue.

**Comment by robertlzj** [comment]
I didn't realize when and where I began to suffer similar problem, at least from Lua 5.1.
In serious case, even when sometimes scripts used are stand alone - all based basic Lua lib (without debug lib).
- Just put **one more breakpoint** will cause different result ( one normal, one failed )!
- Test case will fail in **random** when Run! eg: Run about 10 times fails once.

However, these cases expose some problem in my script, usually something depend on GC ?
Fortunately, they all been found and fixed, but a little pain to debug ( like `collectgarbage("collect")` said above).

The key maybe is **GC time** and (or?) order, which will change by debug, console or each run.
Leave issue next time on specific question.
