### ISSUE TITLE
lexical scope display error on global var in function.

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#811]
![image](https://user-images.githubusercontent.com/7419030/30733506-cbd4be46-9fa9-11e7-9bf9-21d941bed840.png)
The underline style of `b` should be the same as `a`.
```lua
local a=a
local b={function() return b end}
```

**Comment by pkulchenko** [comment]
It's related to the parser component (lua_parser_loose) bringing local variables into scope on the next statement, which is not correct here as the next statement can be part of a function defined in a table (even `local b = function() return b end` is handled incorrectly). I looked at fixing it, but it doesn't seem to be straightforward, so I'm going to table it unless it's becoming a problem. It only impacts the styling as the static analyzer handles this situation correctly.
