### ISSUE TITLE
module 'image' not found:

### ISSUE THREAD

**Issue by chowkamlee81** [pkulchenko/ZeroBraneStudio#812]
I am able to run using command line via 
a) th
b) require 'image'
using console iam able to run but using Zerobrane after selecting  interpretter as lua, not able to run.
Why is this so? Kindly suggest

**Comment by robertlzj** [comment]
Can't found module?
- What's the error message.
- Check path at run time, use `print(package.path, package.cpath)` or so.
- Maybe there are two case. `require` can't find file, or found but can't load ( can't found its sub outter module )
- Choose project directory. Not just open a lua file then run, if there need some work directory.

You mean Local console?
It actually use LuaJIT ( Lua 5.1 ) which may be different from interpreter select for project.

**Comment by pkulchenko** [comment]
@chowkamlee81, if you are using Torch, you should install the torch module and have the interpreter selected. See this page for instructions: http://notebook.kulchenko.com/zerobrane/torch-debugging-with-zerobrane-studio

**Comment by pkulchenko** [comment]
@chowkamlee81, did any of the suggestions help?
