### ISSUE TITLE
MacOS High Sierra Multiple Window Error.

### ISSUE THREAD

**Issue by Disco88** [pkulchenko/ZeroBraneStudio#813]
If you already have a zerobrane window open in high Sierra, and you click on on lua file to open it in zerobrane (directly clicking on the file, not opening it within zb). It first opens another instance of zerobrane, then shortly after the application will fail to respond. Sometimes you cant even force quit the application. 

1. Open a lua file in zerobrane
2. Try to open another lua file by clicking on it in finder.
3. It won't open the lua file in the already running instance of zb.

**Comment by pkulchenko** [comment]
@Disco88, interesting. The IDE as singleinstance check disable on OSX as it's supposed to disallow launching multiple instances of the same application, but maybe it needs to be re-enabled.

Can you try if the same issue happens with (1) dragging the file over the icon in the Dock (2) adding `singleinstance=true` to the config and restarting the IDE?

**Comment by Disco88** [comment]
Certainly interesting, 

So, dragging the file over the dock icon produces the same result.

and setting singleinstance=true gives me the same multiple instance result as well.

**Comment by Disco88** [comment]
I should add that the built in file open within zb works perfectly fine. It's only when you are adding by either dragging a file on the icon, or opening directly from a file in macOS.

**Comment by pkulchenko** [comment]
> and setting singleinstance=true gives me the same multiple instance result as well.

Did you close all instances of the IDE after making the change?

**Comment by Disco88** [comment]
I did, I also tried a fresh install of the IDE as well.

**Comment by pkulchenko** [comment]
I've tested on Yosemite (10.10.5) and it works as expected: double clicking on a file in Finder activates already running instance and loads the file there (running the current master branch version).

Are you running the IDE from a cloned version of the repository or from the downloaded .dmg file (v1.60)?

I've tried to figure out any recent changes with respect to handling single instances in High Sierra, but haven't found anything interesting yet.

**Comment by Disco88** [comment]
Yep so I tested zerobrane on another Mac that is on High Sierra and it appears to have the same problem. My Mac's that are on Sierra or earlier don't have the problem. So it appears to only be a High Sierra problem. 

I'm using the 1.60 dmg. Should I try the git repo?

**Comment by pkulchenko** [comment]
Thank you for an update. I'll see if I can find High Sierra to test on. I couldn't find anything online about changes in single instance handling on High Sierra, so if you notice something, please update the ticket.

**Comment by pkulchenko** [comment]
@Disco88, I asked one of the users to test and High Sierra and he can confirm the issue, although it doesn't seem to be limited to ZBS as the same issue can be seen in SublimeText3 (but not in VS Code). Both ZBS and ST3 also work as expected on Sierra, so there seem to be some changes in the OS that led to this behavior change. I'm reviewing Info.plist files, but don't have any suggestions on how to fix it yet.

**Comment by pkulchenko** [comment]
@Disco88, I have been able to reproduce this issue, but don't have a fix yet. It does seem to be related to the way the Lua interpreter is started from a shell script and I'm continue searching for a solution for this issue.

**Comment by pkulchenko** [comment]
@Disco88, I think I found the fix. I pushed a change that fixed that issue for me (tested on several computers with High Sierra). I suggest to restart the computer after pulling the changes (or installing the patch) if you have already started a "broken" version of the IDE after the last restart (as there is something being cached in the OS).

**Comment by pkulchenko** [comment]
> I'm using the 1.60 dmg.

Since you are using the dmg, you will need to apply the fix (a3ef1c2) manually. Open `/Applications/ZeroBraneStudio.app/Contents/MacOS/ZeroBraneStudio` script and make the necessary changes on the last line. Restart the computer before or after making the changes.

**Comment by Disco88** [comment]
Thanks, fix worked great. Keep up the good work!

**Comment by pkulchenko** [comment]
Thanks for the update!
