### ISSUE TITLE
ZBS migration to Lua 5.3

### ISSUE THREAD

**Issue by ildar** [pkulchenko/ZeroBraneStudio#814]
Is the move from Lua 5.1 to 5.3 scheduled? Just asking.

**Comment by pkulchenko** [comment]
@ildar, Lua 5.3 is already supported by the IDE. Do you mean using Lua 5.3 to run the IDE itself? It's not planned, but it shouldn't be too difficult, as there has been some work done to support Lua 5.2 and I have already updated wxlua to support 5.3 as well. I just don't see much of a reason as you can still use Lua 5.1 to run the IDE itself and debug any Lua application running Lua 5.1-5.3.

(It's better to use the [maillist or IRC](https://studio.zerobrane.com/community) for questions.)

**Comment by ildar** [comment]
So you can help with this? https://sourceforge.net/p/wxlua/bugs/37/
Please publish your patch.

**Comment by pkulchenko** [comment]
Sourceforge seems to be down, so I don't know the details of that bug, but the changes that I made have [already been published](https://github.com/pkulchenko/wxlua/commit/d81ae23e3150216b1e8e316c88032d76cc9f9e28) and are part of the [branch for wxlua I'm using/developing](https://github.com/pkulchenko/wxlua/commits/wxwidgets311).

**Comment by ildar** [comment]
Oh! Nice! Thanks a lot!

**Comment by pkulchenko** [comment]
@ildar, I'm closing per my earlier comment, but let me know if you run into issues compiling it.
