### ISSUE TITLE
the path include gbk code can't active

### ISSUE THREAD

**Issue by fkeujjpdc** [pkulchenko/ZeroBraneStudio#817]
i wan't load a lua file:  C:\Users\16062501\Desktop\通用测试主板进度及二次开发说明-17-8-25\ATE_PRO\1.lua

but the path include chinese
ZeroBraneStudio output error "can't active the file"
![image](https://user-images.githubusercontent.com/24837307/31304952-f06dfafc-ab60-11e7-92d7-c9cc4e9ffe52.png)
![image](https://user-images.githubusercontent.com/24837307/31304966-41a645f0-ab61-11e7-841c-a18a0038d1e0.png)
@robertlzj
how can i load lua file that the path include chinese

**Comment by fkeujjpdc** [comment]
thanks for your reply,i patch this code.it occur another error,

![image](https://user-images.githubusercontent.com/24837307/31377892-29a75624-addc-11e7-8889-e9ddcdb72af1.png)


it semms that file is a nil data when call FixUTF8.
@pkulchenko

**Comment by pkulchenko** [comment]
Ok, this should be a better patch:

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index 5beff18..29c95b9 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -826,6 +826,9 @@ local function nameOutputTab(name)
   if index ~= wx.wxNOT_FOUND then nbk:SetPageText(index, name) end
 end
 
+local ok, winapi = pcall(require, 'winapi')
+if not ok then winapi = nil end
+
 function debugger:handle(command, server, options)
   local debugger = self
   local verbose = ide.config.debugger.verbose
@@ -843,6 +846,12 @@ function debugger:handle(command, server, options)
   -- only set suspended if the debugging hasn't been terminated
   debugger:UpdateStatus(debugger.server and "suspended" or "stopped")
 
+  -- some filenames may be represented in a different code page; check and re-encode as UTF8
+  local codepage = ide:GetCodePage()
+  if codepage and file and FixUTF8(file) == nil and winapi then
+    file = winapi.encode(codepage, winapi.CP_UTF8, file)
+  end
+
   return file, line, err
 end
 ```

**Comment by fkeujjpdc** [comment]
thanks very much,the patch worked well, but the breakpoints can't work,i can use step and setp into debug the program,but  when it set breakpoint and clicked "start or continue debugging" button ,the program can't break   

![image](https://user-images.githubusercontent.com/24837307/31418954-85631e14-ae6b-11e7-863c-3f2cdacb27c6.png)

**Comment by pkulchenko** [comment]
> but the breakpoints can't work,i can use step and setp into debug the program,but when it set breakpoint and clicked "start or continue debugging" button ,the program can't break

I think it's because the path provided by the IDE is in UTF8 encoding, but the one provided by the debugger is in the 936 codepage, so the match doesn't work. It *may* be possible to address this, but unfortunately, I don't know in what case the mis-encoded filename is reported, so it's difficult to say when exactly the file name should be provided in a different encoding. I may be able to encode it all the time when breakpoints are set (assuming the `codepage` setting is configured), but I'm not sure if it's going to break something or not.

I'll commit the current patch and will think if there is a way to re-encode the filename as well.

**Comment by pkulchenko** [comment]
@fkeujjpdc, here is the patch you can check to see if it fixes the breakpoint issue:

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index 29c95b9..81e5f00 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -37,6 +37,17 @@ local BREAKPOINT_MARKER_VALUE = 2^BREAKPOINT_MARKER
 
 local activate = {CHECKONLY = "checkonly", NOREPORT = "noreport", CLEARALL = "clearall"}
 
+local ok, winapi = pcall(require, 'winapi')
+if not ok then winapi = nil end
+
+local function encodeUTF8ToCodepage(file)
+  local codepage = ide:GetCodePage()
+  if codepage and file and winapi then
+    file = winapi.encode(winapi.CP_UTF8, codepage, file)
+  end
+  return file
+end
+
 local function serialize(value, options) return mobdebug.line(value, options) end
 
 local function displayError(...) return ide:GetOutput():Error(...) end
@@ -399,8 +410,8 @@ function debugger:ActivateDocument(file, line, activatehow)
         if not debugger.editormap[editor] and filePath then
           local line = editor:MarkerNext(0, BREAKPOINT_MARKER_VALUE)
           while filePath and line ~= -1 do
-            debugger:handle("delb " .. filePath .. " " .. (line+1))
-            debugger:handle("setb " .. file .. " " .. (line+1))
+            debugger:handle("delb " .. encodeUTF8ToCodepage(filePath) .. " " .. (line+1))
+            debugger:handle("setb " .. encodeUTF8ToCodepage(file) .. " " .. (line+1))
             line = editor:MarkerNext(line + 1, BREAKPOINT_MARKER_VALUE)
           end
         end
@@ -452,7 +463,7 @@ function debugger:reSetBreakpoints()
       local filePath = document.filePath
       local line = editor:MarkerNext(0, BREAKPOINT_MARKER_VALUE)
       while filePath and line ~= -1 do
-        debugger:handle("setb " .. filePath .. " " .. (line+1))
+        debugger:handle("setb " .. encodeUTF8ToCodepage(filePath) .. " " .. (line+1))
         line = editor:MarkerNext(line + 1, BREAKPOINT_MARKER_VALUE)
       end
     end
@@ -826,9 +837,6 @@ local function nameOutputTab(name)
   if index ~= wx.wxNOT_FOUND then nbk:SetPageText(index, name) end
 end
 
-local ok, winapi = pcall(require, 'winapi')
-if not ok then winapi = nil end
-
 function debugger:handle(command, server, options)
   local debugger = self
   local verbose = ide.config.debugger.verbose
@@ -1111,6 +1119,7 @@ function debugger:Break(command)
 end
 function debugger:breakpoint(file, line, state)
   local debugger = self
+  file = encodeUTF8ToCodepage(file)
   if debugger.running then
     return debugger:handleDirect((state and "asetb " or "adelb ") .. file .. " " .. line)
   end
```

This is against the latest master that includes the fix I showed earlier, so you may want to pull the changes first.

This is likely not the change I'll submit, but I want to see if it makes it any better with the breakpoints. The reason why it's likely incomplete is that it also affects valid file names, which is not ideal.

**Comment by fkeujjpdc** [comment]
I'm sorry it took so long to reply to you，i patch this code and test it. it work well.thanks very much!

**Comment by pkulchenko** [comment]
@fkeujjpdc, Thanks for checking! Just to confirm, so everything in the debugger, including the breakpoints work as expected after the patch is applied?

**Comment by fkeujjpdc** [comment]
yes,the breakpoints worked as expected
