### ISSUE TITLE
Runtime error when closing document via API

### ISSUE THREAD

**Issue by paul-reilly** [pkulchenko/ZeroBraneStudio#818]
I have a runtime error with a plugin I'm writing when I try to use the document Close() method from an onEditorKeyDown event handler. 

![runtime-error-close-via-api](https://user-images.githubusercontent.com/7894100/31415588-3ec24bc8-ae1c-11e7-8355-5dcd9b13e031.PNG)

Here is a simple plugin that should hopefully reproduce the issue....

      return {
        name = "Crash on close",

        onEditorKeyDown = function(self, editor, event)
          -- only act on full stop
          if event:GetKeyCode() ~= 46 then return true end -- 46 = . with modifiers pressed
          local doc = ide:GetDocument(editor)
          if doc ~= nil then
            doc:Close()
          end
          -- consumes event
          return false
        end
    }

**Comment by pkulchenko** [comment]
Should be fixed now; thanks for the report!

**Comment by paul-reilly** [comment]
Holy smoke, that was quick - thanks, that's it working now!
