### ISSUE TITLE
Strange navigation in the Outline tree (xubuntu 16.04)

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#819]
I have a strange issue with the outline tree. To reproduce it, I wrote small "code generators"

Code generator `write-many-functions.lua` looks like this:
```lua
local fd=assert(io.open("many-functions.lua","w"))
for i=1,200 do
	fd:write("function Function",i,"()\n\tprint('Function",i,"')\nend\n\n")
end
fd:close()
```
and generates `many-functions.lua`, which looks like this:
```lua
function Function1()
	print('Function1')
end

function Function2()
	print('Function2')
end

function Function3()
	print('Function3')
end

function Function4()
	print('Function4')
end

function Function5()
	print('Function5')
end
:::
```
When I open `many-functions.lua` in ZBS and enter the Outline view, I can click on any function,
=> the function will be shown in the editor and will be selected in the Outline tree
GOOD :+1: 

---
Now the bad case:

Code generator `write-many-methods.lua` looks like this:
```lua
local fd=assert(io.open("many-methods.lua","w"))
fd:write("PACKAGE={}\n")
fd:write("STATUS={}\n")
for i=1,200 do
	fd:write("function PACKAGE:Function",i,"()\n")
	fd:write("STATUS.callback",i,"=function()end\n")
	fd:write("end\n\n")
end
fd:close()
```
the output `many-methods.lua` looks like this:
```lua
PACKAGE={}
STATUS={}
function PACKAGE:Function1()
STATUS.callback1=function()end
end

function PACKAGE:Function2()
STATUS.callback2=function()end
end

function PACKAGE:Function3()
STATUS.callback3=function()end
end
:::
```
Now, if I open `many-methods.lua` in ZBS and click on any function in the Outline tab, then the editor will go to the function, but:
- the function is not selected in the Outline tab :confused:
- the Outline tab always scrolls to the top location :rage: 

This makes it very hard to navigate in a modules with nested methods.

I hope, the given examples will help you to analyze the problem :beer: 
Regards

**Comment by pkulchenko** [comment]
@jjvbsag, are you using the latest master branch? I can't reproduce this issue, but there used to be a related bug, which was fixed some time ago (8ceda532).

**Comment by jjvbsag** [comment]
YES, latest master branch. But on Linux (xubuntu 16.04 LTS). On Windows everything seems fine.

@pkulchenko FYI: Will be offline from Fr. until Su.

**Comment by pkulchenko** [comment]
Interesting; I'll check on Ubuntu.

**Comment by pkulchenko** [comment]
@jjvbsag, I tried on Ubuntu (although a slightly different version from yours), but can't reproduce this issue. Do you have any plugins installed? Can you try without any plugins and on the default configuration (no user.lua changes) just to make sure it happens on the default checkout as well? Thanks.

**Comment by jjvbsag** [comment]
I'm really confused :confused:  :confused:  :confused:  :confused: 
Came back to work after a really nice weekend and now everything works as expected ?!?!?!
I will monitor it for one or two more days. If everything stays fine, I will close this.
Sorry for any inconvenience...

**Comment by pkulchenko** [comment]
@jjvbsag, any update on this? You can close if it has been working so far for you.

**Comment by jjvbsag** [comment]
@pkulchenko I will do some final checks on monday and then I'll close.

**Comment by jjvbsag** [comment]
Closing this, as it's not reproducible with current ZBS. But I will continue to have an eye on this.
