### ISSUE TITLE
Reload package without leaving ZBS ?

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#820]
While developing packages for ZBS the workflow now is

- Open ZBS
- Change Project directory to package folder
- Change package code
- Close ZBS
- Open ZBS
- Change Project directory to real project folder
- Evaluate package function
- Close ZBS

Even, when running multiple instances of ZBS, you always have to close and open ZBS to load the changed package code and surely you will wake up in the wrong project directory.

Is there any way to do an unload/reload package from inside ZBS without the need to close ZBS?
I think of the following sequence:

- call PACKAGE:onProjectClose()
- call PACKAGE:onUnRegister()
- delete any PACKAGE reference in ZBS and collect garbage
- load package again using the normal package loading function.

Possible? Any constraints?

**Comment by madmaxoft** [comment]
There will most likely be some remains that cannot be cleared when unloading. If the package sets a value somewhere (such as a UI color, for example), such a change cannot be "unloaded" reasonably, so the reload won't be the same as a fresh load.

**Comment by jjvbsag** [comment]
@madmaxoft yes, I'm aware of this. But when I work on code e.g. in onProjectLoad() or in onEditorSave(), it would be handy being able just to replace a package with an updated one.

@pkulchenko Or - Paul - do you have any "best practice" recommendations for developing packages?

**Comment by pkulchenko** [comment]
There is `ide:Restart(true)`, which restarts the IDE without asking to save, which I sometimes use after plugin changes; you can link it to a shortcut and given short restart time it should be fairly painless.

There is also a PR for hotreload plugin (https://github.com/pkulchenko/ZeroBranePackage/pull/49), which is probably along the lines of what you were thinking. The only reason I haven't merged it yet is that I've been working on `Reload` method for plugins (and a way to detect the changes monitoring the files), but it's taking longer than expected, so I may end up merging it as is.

**Comment by jjvbsag** [comment]
@pkulchenko now I'm coming back to the topic.

I tried `ide:Restart(true)` in the local console. Quite nice.

I also tried the plugin mentioned in  ( pkulchenko/ZeroBranePackage#49 ) , but it had issues with #555, if packages are not loaded from the standard path. I could fix this by replacing 
```lua
local fpath = ide:GetPackagePath() .. fname 
```
with
```lua
local fpath = doc:GetFilePath()
```
but then I get strange errors on reloading the package:
```txt
/home/joergen/.zbstudio/packages/SVN/svn.lua:25: first use of unknown field 'ToDouble'
/home/joergen/.zbstudio/packages/SVN/svn.lua:60: first use of unknown field 'gsub'
/home/joergen/.zbstudio/packages/SVN/svn.lua:65: unused local variable 'zbs_svn_plugin_id'; consider removing or replacing with '_'
/home/joergen/.zbstudio/packages/SVN/svn.lua:93: unused local variable '_child_id'; consider removing or replacing with '_'
/home/joergen/.zbstudio/packages/SVN/svn.lua:96: unused local variable '_clicked_item_id'; consider removing or replacing with '_'
/home/joergen/.zbstudio/packages/SVN/svn.lua:97: unused local variable 'TMP'; consider removing or replacing with '_'
```
This looks to me, as if the analyzer had been run over the package ?!?!?! How can this happen?

(after that my package crashes with an wx error in onUnRegister, but thats my own issue)

**Comment by pkulchenko** [comment]
> I also tried the plugin mentioned in ( pkulchenko/ZeroBranePackage#49 ) , but it had issues with #555, if packages are not loaded from the standard path. 

Yes, it's a deficiency of the package registration, as it only checks the default location for the package. I plan to address this.

> but then I get strange errors on reloading the package:

These are warnings from the static analyzer. Are you saying you don't call these and they somehow get triggered? This would indeed be strange. Is this reproducible? I can take a look then.

**Comment by jjvbsag** [comment]
> These are warnings from the static analyzer. Are you saying you don't call these and they somehow get triggered? 

Found it! In reloadplugin.lua there are the lines.
```lua
	local errors = analyze(fpath)
	if errors ~= 0 then return end
```
Does it try to do a syntax check by this? Should better be replaced by a call to Compile or directly use loadstring?

**Comment by pkulchenko** [comment]
I think so; yes, for some reason it tries to call Analyze. Maybe it's because @cpeosphoros wanted to make sure that if there are any (potential) issues, he's aware of them.

**Comment by jjvbsag** [comment]
@pkulchenko @cpeosphoros : I did the following changes and now `reloadplugin.lua` does exactly, what I want. Closing the issue for me.

```diff
--- reloadplugin.lua.orig	2017-11-03 10:07:51.930174137 +0100
+++ reloadplugin.lua	2017-11-03 10:10:51.080763885 +0100
@@ -51,6 +51,7 @@
 	local editor = ide:GetEditorWithFocus()
 	if not editor then print("Error: No editor.") return end
 	local doc = ide:GetDocument(editor)
+	if not doc then print("Error: No doc.") return end
 	if doc:IsNew() then print("Error: New document.") return end
 	if doc:IsModified() and not doc:Save() then
 		print("Error: Document not saved.")
@@ -61,17 +62,20 @@
 	if extension ~= "lua" then print("Error: Not a .lua file.") return end
 	local _package = ide:GetPackage(name)
 	if not _package then print ("Error: Package not registered.") return end
-	--local fpath = doc:GetFilePath()
-	local fpath = ide:GetPackagePath() .. fname
-	local errors = analyze(fpath)
-	if errors ~= 0 then return end
+	local fpath = doc:GetFilePath()
 	printf("Loading %s.", fname)
-	local ok, package = doFile(fpath)
+	local ok,package,message=pcall(loadfile,fpath)
 	if not ok then
 		print(package)
+		print("Error: (1) Not a valid plugin.")
+		return
+	end
+	if not package then
+		print(message)
 		print("Error: Not a valid plugin.")
 		return
 	end
+	printf("Calling %s.", fname)
 	ok, package = pcall(package)
 	if not ok then
 		print(package)
```
