### ISSUE TITLE
Stop button for "Find in files"

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#822]
if you - by accident or by intend - start a search with the "Find in files" bar in a huge directory tree (worst case: '/' on unix or "C:\" on windows), ZBS is unreactive until all directories have been parsed.
CodeLite has a Stop-Button for this, it would be very nice, if ZBS had this too :beer:

**Comment by pkulchenko** [comment]
@jjvbsag, it does accept `Escape` during search, which will abort the current search going on, but it doesn't stop the search during the phase when the directories are being scanned (and it may take some time during the scan of a very large folder). I've tried several times to "yield" occasionally, so that the GUI can check for keyboard events, but it slows down the rest of the processing and is still difficult to process to react properly to those key events (as there is currently no mechanism to signal to the directory scanner that the process should be aborted).

I may consider adding a hard stop at some pre-configured number of files (which can be changed from the config), which should at least avoid the situation of waiting for `/` scan to be completed, but for now the workaround is to not scan `/` or `C:` ;). I've tested on large folders (up to 100,000 files) and the scan performs sufficiently fast, but scanning root folders may involve millions of files (and is likely to be a mistake), so can probably be capped.

**Comment by pkulchenko** [comment]
@jjvbsag, does hitting `ESC` work for you to abort the search? I've tried on several large folders and it does work as expected.

**Comment by pkulchenko** [comment]
One more thing: the search results are shown (if any) while the folders are being scanned and the folder names are shown on the right side of the find/replace bar, which makes the progress more visible, but there is no hint about the `Esc` shortcut (although it does work).

**Comment by pkulchenko** [comment]
I think I figured out what happened. When the search is started for the first time, the focus is switched to the search results tab, which makes `Esc` not to work there. You can still switch to the find panel and then use `Esc` or close the search results tab, which will abort the search.

**Comment by jjvbsag** [comment]
@pkulchenko I think this needs a deeper discussion.

**Response time**

First of all there are three topics which could cause problems in the parsing of files itself.

- huge directories (directories with a big amount of entries)
- deep directories (directory trees with a big number of levels)
- huge files

While the first 2 has an impact while iterating the tree, the last one comes into view while really searching. My solution for the first always was to have an "overall" counter, and then yield the api at e.g. every 1000 hit. Something like this (just example, no real or tested code)

```lua
local function process_dir(topdir,func)
	local yieldcnt=0
	local function pd(dir)
		for entry in lfs.dir(dir) do
			yieldcnt=yieldcnt+1
			if yieldcnt>=1000 then
				gui:refresh()
				yieldcnt=0
			end
			local path=entry.."/"..dir
			if lfs.attributes(path)=="directory" then
				pd(path)
			else
				func(path)
			end
		end
	end
	pd(topdir)
end
```

this guarantees a quite constant responsiveness independent of issue 1 and 2, and has only a small overhead.

**Gui design**
The problem with ESC is - apart from the focus problem - you have to know about it. A Stop button is self documenting - this is why I asked for it - and has no focus problem. It will focus, when you click. 

**Finally, to answer your question**

Searching for `/home/proj/; *.lua` (has about 1.1M directories with about 11M files, of which about 28k are lua files) for a string, which only has a hit on two files, gives me 

- one reaction after 2m16s
- a second reaction after 5m19s
- normal working again after 5m55s

All the time in between ZBS just is dead. Hitting ESC or close the search results tab just isn't possible.

The problem is, you only give a "yield" to the GUI on a search _HIT_, not while parsing the directory tree. Please consider the above approach to allow GUI to react. You could make the 1000 in `yieldcnt>=1000` make a default, which can be tweaked in user.lua

**Comment by pkulchenko** [comment]
@jjvbsag, good points. I don't think a new config setting is needed, but it may be good to yield and refresh on each directory (in addition to the matches).

Here is the patch that implements that and also adds a message that Escape will close the panel (although may need to update it to "Use `Escape` to abort" or something like that):

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index 19c5aa3..79b5cfb 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -440,14 +440,25 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
     text = text:gsub("%w",function(s) return "["..s:lower()..s:upper().."]" end)
   end
 
+  local function yield()
+    ide:Yield() -- give time to the UI to refresh
+    -- the IDE may be quitting after Yield or the tab may be closed,
+    local ok, mgr = pcall(function() return ide:GetUIManager() end)
+    -- so check to make sure the manager is still active
+    -- and check that the search results tab is still open
+    return ok and mgr:GetPane(searchpanel):IsShown() and ide:IsValidCtrl(self.reseditor)
+  end
+
   local files = coroutine.wrap(function()
-      ide:GetFileList(startdir, subdirs, mask, {yield = true, folder = false, skipbinary = true})
+      ide:GetFileList(startdir, subdirs, mask, {yield = true, skipbinary = true})
     end)
   while true do
     local file = files()
     if not file then break end
 
-    if checkBinary(GetFileExt(file)) ~= true then
+    if IsDirectory(file) then
+      if not yield() then return false end
+    elseif checkBinary(GetFileExt(file)) ~= true then
       self.curfilename = file
       local filetext, err = FileRead(file, firstReadSize)
       if not filetext then
@@ -459,17 +470,7 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
           self.oveditor:SetTextDyn(filetext)
 
           if self:FindAll(onFileRegister) then self.files = self.files + 1 end
-
-          -- give time to the UI to refresh
-          ide:Yield()
-          -- the IDE may be quitting after Yield or the tab may be closed,
-          local ok, mgr = pcall(function() return ide:GetUIManager() end)
-          -- so check to make sure the manager is still active
-          if not (ok and mgr:GetPane(searchpanel):IsShown())
-          -- and check that the search results tab is still open
-          or not ide:IsValidCtrl(self.reseditor) then
-            return false
-          end
+          if not yield() then return false end
         end
       end
     end
@@ -633,7 +634,8 @@ function findReplace:RunInFiles(replace)
     end
   end
 
-  self:SetStatus(TR("Searching for '%s'."):format(findText))
+  self:SetStatus(TR("Searching for '%s'."):format(findText)
+    .." "..TR("Use %s to close."):format("`Escape`"))
   wx.wxSafeYield() -- allow the status to update
 
   local startdir, mask = self:GetScope()
```

Give it a try and let me know how it works on your large folders.

**Comment by jjvbsag** [comment]
Sorry, could not apply the patch.
Where your patch says
```diff
   local files = coroutine.wrap(function()
-      ide:GetFileList(startdir, subdirs, mask, {yield = true, folder = false, skipbinary = true})
+      ide:GetFileList(startdir, subdirs, mask, {yield = true, skipbinary = true})
     end)
```
the master has
```lua
  local files = coroutine.wrap(function()
      FileSysGetRecursive(startdir, subdirs, mask, {yield = true, folder = false, skipbinary = true})
    end)
```
But I trust in you 🙂 . If it works at your site, just commit everything and I will verify on monday at work.

Have a nice weekend.

**Comment by pkulchenko** [comment]
Indeed. I had some pending changes that I just pushed, so the patch should apply now.

**Comment by jjvbsag** [comment]
@pkulchenko yes, now the patch can be applied. But without effect. I believe, this is because
```lua
  if IsDirectory(file) then
      if not yield() then return false end
```
does not trigger, because `ide:GetFileList()` does not return _any_ folders at all. Even if `folder=true` is passed as option, because - if I understand your code - in `FileSysGetRecursive` at
```lua
      if optfolder and ismatch(fname..sep, inmasks, exmasks) then
        report((optpath and fname or fname:gsub(pathpatt, ""))..sep)
      end
```
the folder (e.g. `/home/proj/example1`) is matched against the patter (e.g `*.lua`) which will almost never hit

**Comment by pkulchenko** [comment]
> does not trigger, because ide:GetFileList() does not return any folders at all.

You are right; the test I had was on `*` mask, which was catching all the folders. Here is a better patch:

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index cc4e96e..e4d03ec 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -440,12 +440,25 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
     text = text:gsub("%w",function(s) return "["..s:lower()..s:upper().."]" end)
   end
 
+  local function yield()
+    ide:Yield() -- give time to the UI to refresh
+    -- the IDE may be quitting after Yield or the tab may be closed,
+    local ok, mgr = pcall(function() return ide:GetUIManager() end)
+    -- so check to make sure the manager is still active
+    -- and check that the search results tab is still open
+    -- return `nil` to abort processing if one of the checks fails
+    return ok and mgr:GetPane(searchpanel):IsShown() and ide:IsValidCtrl(self.reseditor) or nil
+  end
+
   local files = coroutine.wrap(function()
-      ide:GetFileList(startdir, subdirs, mask, {yield = true, folder = false, skipbinary = true})
+      ide:GetFileList(startdir, subdirs, mask, {
+          yield = true, folder = false, skipbinary = true, ondirectory = yield
+        })
     end)
   while true do
     local file = files()
-    if not file then break end
+    if file == false then return false end -- aborted processing
+    if file == nil then break end -- out of files to process
 
     if checkBinary(GetFileExt(file)) ~= true then
       self.curfilename = file
@@ -459,17 +472,7 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
           self.oveditor:SetTextDyn(filetext)
 
           if self:FindAll(onFileRegister) then self.files = self.files + 1 end
-
-          -- give time to the UI to refresh
-          ide:Yield()
-          -- the IDE may be quitting after Yield or the tab may be closed,
-          local ok, mgr = pcall(function() return ide:GetUIManager() end)
-          -- so check to make sure the manager is still active
-          if not (ok and mgr:GetPane(searchpanel):IsShown())
-          -- and check that the search results tab is still open
-          or not ide:IsValidCtrl(self.reseditor) then
-            return false
-          end
+          if not yield() then return false end
         end
       end
     end
@@ -633,7 +636,8 @@ function findReplace:RunInFiles(replace)
     end
   end
 
-  self:SetStatus(TR("Searching for '%s'."):format(findText))
+  self:SetStatus(TR("Searching for '%s'."):format(findText)
+    .." "..TR("Use %s to close."):format("`Escape`"))
   wx.wxSafeYield() -- allow the status to update
 
   local startdir, mask = self:GetScope()
diff --git a/src/util.lua b/src/util.lua
index 999337e..3666eda 100644
--- a/src/util.lua
+++ b/src/util.lua
@@ -164,8 +164,14 @@ function FileSysGetRecursive(path, recursive, spec, opts)
         report((optpath and fname or fname:gsub(pathpatt, ""))..sep)
       end
 
-      if recursive and ismatch(fname..sep, nil, exmasks)
-      and (not optondirectory or optondirectory(fname) ~= false)
+      -- `optondirectory` may return:
+      -- `true` to traverse the directory and continue
+      -- `false` to skip the directory and continue
+      -- `nil` to abort the process
+      local ondirectory = optondirectory and optondirectory(fname)
+      if optondirectory and ondirectory == nil then return false end
+
+      if recursive and ismatch(fname..sep, nil, exmasks) and (ondirectory ~= false)
       -- check if this name already appears in the path earlier;
       -- Skip the processing if it does as it could lead to infinite
       -- recursion with circular references created by symlinks.
@@ -174,7 +180,7 @@ function FileSysGetRecursive(path, recursive, spec, opts)
       end
 
       num = num + 1
-      if optmaxnum and num >= optmaxnum then break end
+      if optmaxnum and num >= optmaxnum then return false end
 
       found, file = dir:GetNext()
     end
@@ -187,16 +193,20 @@ function FileSysGetRecursive(path, recursive, spec, opts)
       end
 
       num = num + 1
-      if optmaxnum and num >= optmaxnum then break end
+      if optmaxnum and num >= optmaxnum then return false end
 
       found, file = dir:GetNext()
     end
     -- wxlua < 3.1 doesn't provide Close method for the directory, so check for it
     if ide:IsValidProperty(dir, "Close") then dir:Close() end
+    return true
   end
-  while #queue > 0 do getDir(table.remove(queue)) end
+  while #queue > 0 and getDir(table.remove(queue)) do end
 
-  if optyield then return end
+  if optyield then
+    if #queue > 0 then coroutine.yield(false) end -- signal aborted processing
+    return
+  end
 
   if optsort then
     local prefix = '\001' -- prefix to sort directories first
```

**Comment by jjvbsag** [comment]
With this patch zbstudio fails to start with a message
```
---------------------------
Uncaught lua script exception
---------------------------
src/util.lua:214: attempt to index global 'shadow' (a nil value)
stack traceback:
	[string "Initializer"]:1: in function '__newindex'
	src/util.lua:214: in function 'GetFileList'
	src/main.lua:203: in function 'loadToTab'
	src/main.lua:238: in function 'LoadInterpreter'
	src/main.lua:518: in main chunk
	[string "Initializer"]:1: in function <[string "Initializer"]:1>
	[C]: in function 'xpcall'
	[string "Initializer"]:1: in main chunk
---------------------------
OK   
---------------------------
```
but after changing src/util.lua:212
```lua
    local prefix = '\001' -- prefix to sort directories first    	local shadow = {}
```
to
```lua
    local prefix = '\001' -- prefix to sort directories first    
    local shadow = {}
```
your patch works. ZBS is reactive, ESC works and I can even continue to edit files, while the search is active. Great! :+1:

**Comment by pkulchenko** [comment]
> but after changing src/util.lua:212

Yes, these two should be on two different lines (and they are in my copy); not sure what happened, but it's possible that the patch is missing new line on the last line, which made them merge together.

> your patch works. ZBS is reactive, ESC works and I can even continue to edit files, while the search is active. Great! 

Sounds good; I'll get the patch in along with a couple of other search-related improvements.

**Comment by jjvbsag** [comment]
> Yes, these two should be on two different lines (and they are in my copy); not sure what happened, but it's possible that the patch is missing new line on the last line, which made them merge together.

I'm sure, patches should be posted as attachment and not by copy'n'paste.  (use `.TXT` as file extension) This would avoid such problems I hope.

> I'll get the patch in along with a couple of other search-related  improvements.

Looking forward for your next commit, Thanks! 🍺

**Comment by jjvbsag** [comment]
@pkulchenko Now with https://github.com/pkulchenko/ZeroBraneStudio/commit/e7447983aae9c90291b8a6381adec7970427b84a it's _really_ nice 
:beer: + :pizza: + :tulip: !!!

**Comment by pkulchenko** [comment]
@jjvbsag, good to hear; thanks for the update! I also added more detailed status messages, so the search progress is more visible now.

**Comment by jjvbsag** [comment]
@pkulchenko I did some more testing. I repeated the test case

> Searching for `/home/proj/; *.lua` (has about 1.1M directories with about 11M files, of which about 28k are lua files) 
> - one reaction after 2m16s

The first hit with the current version occurs after ~ 8m30, so there is a penalty of roughly 275%. Then I applied this:
```diff
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -439,9 +439,13 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
   if text and not self:GetFlags().MatchCase then
     text = text:gsub("%w",function(s) return "["..s:lower()..s:upper().."]" end)
   end
-
+  local count=0
   local function yield(dir)
-    if dir then self:SetStatus(TR("Searching in '%s'."):format(dir:gsub(startdir,""))) end
+       count=count+1
+       if count>=100 then
+               if dir then self:SetStatus(TR("Searching in '%s'."):format(dir:gsub(startdir,""))) end
+               count=0
+       end
 
     ide:Yield() -- give time to the UI to refresh
     -- the IDE may be quitting after Yield or the tab may be closed,
```
Only every 100th dir is shown to the user, which is still quite fast.
After that the first hit occurred after 2m42s, which is a penalty of 19%. This seems to be a good value for gaining a better responsiveness.

---
One more point:
`dir:gsub(startdir,"")` will fail to replace, if startdir has pattern matching characters, e.g `/home/my-projects`, or will even assert
```
Lua: Error while running chunk
src/editor/findreplace.lua:465: src/editor/findreplace.lua:446: malformed pattern (missing ']')
stack traceback:
	[C]: in function 'files'
	src/editor/findreplace.lua:465: in function 'ProcInFiles'
	src/editor/findreplace.lua:650: in function 'RunInFiles'
	src/editor/findreplace.lua:922: in function <src/editor/findreplace.lua:919>
	[C]: at 0x7fa36b17f1bd
	src/main.lua:844: in main chunk
	[C]: at 0x00404f08
```
for a startdir like `/home/test-[abc`.
You should quote startdir before the use in gsub

**Comment by pkulchenko** [comment]
> You should quote startdir before the use in gsub

Good point on escaping the path; I'll fix that.

In terms of the first suggestion; so the issue now is that the status is updated *too frequently*? if that's the case, I'll probably add a similar check, but will make it time-based rather than count-based.

**Comment by pkulchenko** [comment]
@jjvbsag, can you rerun your test with the following patch:

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index 9470600..ea9b842 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -440,8 +440,13 @@ function findReplace:ProcInFiles(startdir,mask,subdirs)
     text = text:gsub("%w",function(s) return "["..s:lower()..s:upper().."]" end)
   end
 
+  local lastupdate = os.clock()
   local function yield(dir)
-    if dir then self:SetStatus(TR("Searching in '%s'."):format(dir:gsub(startdir,""))) end
+    local now = os.clock()
+    if now-lastupdate < 0.250 then return true end
+    lastupdate = now
+
+    if dir then self:SetStatus(TR("Searching in '%s'."):format(dir:gsub("^"..q(startdir),""))) end
 
     ide:Yield() -- give time to the UI to refresh
     -- the IDE may be quitting after Yield or the tab may be closed,
```

Note that it already includes a fix for the other issue as well.

I set the threshold to 250ms, but it's a trade-off between the UI being more responsive and the search taking longer on large directories (as you observed, as it's refreshes UI more frequently than needed).

**Comment by jjvbsag** [comment]
@pkulchenko The last patch works like a charm (benchmark takes ~2m10s ¹), although 0.25 feels a bit slowly for me. I'd prefer 0.1, but this is only my personal opinion.

¹) don't give to much on the seconds, they vary +/- 20s between repeated runs.

**Comment by pkulchenko** [comment]
I updated the check to be after 100ms and also added forced update after a match, so this should work better now.

**Comment by jjvbsag** [comment]
@pkulchenko one more minor fix. If traversing tree reaches a directory, which cannot be opened, search is aborted with a message "Cancelled by the user."
The following patch fixes this:
```diff
--- a/src/util.lua
+++ b/src/util.lua
@@ -150,7 +150,7 @@ function FileSysGetRecursive(path, recursive, spec, opts)
     dir:Open(path)
     if not dir:IsOpened() then
       if TR then ide:Print(TR("Can't open '%s': %s"):format(path, wx.wxSysErrorMsg())) end
-      return
+      return true
     end
 
     -- recursion is done in all folders if requested,
```

**Comment by pkulchenko** [comment]
Good catch; thanks!
