### ISSUE TITLE
Not able to find interpreters torch7 not qlua-luajit in zbstudio settings

### ISSUE THREAD

**Issue by ChidanandKumarKS** [pkulchenko/ZeroBraneStudio#823]
Not able to find interpreters torch7 not qlua-luajit in zbstudio settings

I have installed torch using luarocks install torch
my executable in bin directory contains
json2lua  
luajit 
luarocks-admin
qlua
  torch-activate
lua2json 
 luarocks
  mdcat

Iam not able to execute "require('torch')" using zbstudio ide but iam able to execute "require('torch')"  using console based operaion using th command.

Kindly suggest

**Comment by pkulchenko** [comment]
> Not able to find interpreters torch7 not qlua-luajit in zbstudio settings

@ChidanandKumarKS, you need to install [torch7 plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/torch7.lua).
