### ISSUE TITLE
Commandline usage: Open file fails when no path (or only a relative path) provided

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#829]
Tested on linux (ubuntu 16.04) and windows (win7/x64 pro)

zbstudio fails to open a file in the current directory, if not the complete path is passed as argument.
Example on linux
```sh
mkdir ~/Example
cd ~/Example
echo "print(1+2)" >example.lua
zbstudio example.lua
```
message from zbstudio `Can't open file 'example.lua': No such file or directory`
```sh
zbstudio ~/Example/example.lua
```
does the job, but it quite annoying, if you have long paths like (e.g.)
`/home/myprojects/github/project1/example23.1/appl-json.lua`

The same is true for all relative paths
```sh
mkdir libs
echo "return true"> libs/utils.lua
zbstudio libs/utils.lua
```
`Can't open file 'lib/utils.lua': No such file or directory`

**Comment by pkulchenko** [comment]
Yes, I'm aware of this issue and it's indeed the same as #830. This is an artifact of the way that the script on Linux is working (although there is a somewhat similar issue on Windows as well).

There are several ways to deal with this issue, but none of them is too appealing. The main reason for it is that the libraries and all other files are loaded relative to the root directory of the IDE, so it's convenient to change into it, but this makes the relative paths not work as the original directory is lost (and the relative paths no longer work, as you observed).

**Comment by jjvbsag** [comment]
Ok, I understand the cause and did a little test. This works fine:

```diff
diff --git a/zbstudio.sh b/zbstudio.sh
index 4a8aa94..cafbfe9 100755
--- a/zbstudio.sh
+++ b/zbstudio.sh
@@ -3,12 +3,20 @@
 # Thanks to StackOverflow wiki (http://stackoverflow.com/a/246128)
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
+argc=$#
+argv=("$@")
+for (( i=0; i<$#; i++ )) ; do
+    if [ -e "${argv[i]}" ] ; then
+        argv[i]=$(realpath "${argv[i]}")
+    fi
+done
+
 if [[ $(uname) == "Darwin" ]]; then
   # MacOS Sierra throws `error -10810` running with quarantined files even when explicitly allowed
   ATTR="com.apple.quarantine"
   (cd "$DIR"; \
    if [[ $( xattr -pl $ATTR zbstudio 2>&1 ) == $ATTR:* ]]; then xattr -rd $ATTR zbstudio bin; fi; \
-   open zbstudio/ZeroBraneStudio.app --args "$@")
+   open zbstudio/ZeroBraneStudio.app --args "${argv[@]}")
 else
   case "$(uname -m)" in
     x86_64)  ARCH=x64;;
@@ -16,5 +24,5 @@ else
     aarch64) ARCH=aarch64;;
     *)       ARCH=x86;;
   esac
-  (cd "$DIR"; bin/linux/$ARCH/lua src/main.lua zbstudio "$@") &
+  (cd "$DIR"; bin/linux/$ARCH/lua src/main.lua zbstudio "${argv[@]}") &
 fi
```
Please have a look at if, if it may lead to a solution

**Comment by pkulchenko** [comment]
That's exactly what I was thinking as one of the options; thank you for putting it together! This still needs to be extended to cover Windows (it will need to be done in `build/win32_starter.c` script).

Another option I'm considering is to capture the original directory and pass it as an additional parameter to the main.lua script (along with the file names). The application can then combine it with the relative paths to get absolute names. The advantage of this is that it's consistent between all platforms and will fall back to the current logic if not provided. Unfortunately, the starter script on windows still needs to be modified, but the changes should be simpler than the always-absolute-names option.

**Comment by jjvbsag** [comment]
Just to mention it, I just observed `realpath` is not installed on minimal linux/ubuntu environments.

**Comment by pkulchenko** [comment]
@jjvbsag, can you take a look at the changes I pushed to https://github.com/pkulchenko/ZeroBraneStudio/tree/load-file-from-current-dir? It should fix this issue on all platforms and make it work for relative and absolute files, but I'd be interested if others would give it a try before I merge. Thanks!

**Comment by jjvbsag** [comment]
@pkulchenko Now I got the time to look at it, yes thats fine. Verified with Windows7/64 and xubuntu 16.04. Even passing complexe path such as ../anotherdir/./myproject/../anotherproject/somefile.lua is handled correctly :+1:

**Comment by pkulchenko** [comment]
Sounds good. I'm finishing testing on macOS and will merge shortly.
