### ISSUE TITLE
String Concatenation Formatting Error

### ISSUE THREAD

**Issue by dbaileychess** [pkulchenko/ZeroBraneStudio#831]
When using .. to concatenate a string with an numerical value, the formater incorrectly groups the second . with the number. It thinks it is a leading decimal place.

Example:

`print("Hello"..30)`

![image](https://user-images.githubusercontent.com/1477247/32875336-482bc60c-ca4c-11e7-918d-15e5020655ea.png)

**Comment by pkulchenko** [comment]
I noticed the same thing, but I don't think there is an easy fix. Lua lexer comes from Scintilla, where operators defined as `CharacterSet setLuaOperator(CharacterSet::setNone, "*/-+()={}~[];<>,.^%:#&|");` and number is defined as `CharacterSet setNumber(CharacterSet::setDigits, ".-+abcdefpABCDEFP");` and the check for number is simple and has precedence over operators:

```
		if (sc.state == SCE_LUA_DEFAULT) {
			if (IsADigit(sc.ch) || (sc.ch == '.' && IsADigit(sc.chNext))) {
				sc.SetState(SCE_LUA_NUMBER);
```

This may be *possible* to fix, but will require a change in Scintilla and wxwidgets/wxlua upgrade to get it in.

I also looked at the Lua lexer included with the IDE (lualibs/lexers/lua.lua), but it has exactly the same issue. I think the following patch may fix it for this lexer:

```diff
diff --git a/lualibs/lexers/lua.lua b/lualibs/lexers/lua.lua
index fba4600..e4a8018 100644
--- a/lualibs/lexers/lua.lua
+++ b/lualibs/lexers/lua.lua
@@ -141,7 +141,7 @@ local identifier = token(l.IDENTIFIER, l.word)
 local label = token(l.LABEL, '::' * l.word * '::')
 
 -- Operators.
-local operator = token(l.OPERATOR, S('+-*/%^#=<>&|~;:,.{}[]()'))
+local operator = token(l.OPERATOR, P('..')+S('+-*/%^#=<>&|~;:,.{}[]()'))
 
 M._rules = {
   {'whitespace', ws},
```

You can replace the scintilla one with this one using something like this in the config `ide.specs.lua.lexer = "lexlpeg.lua"`.
