### ISSUE TITLE
Auto indent immediately after typing

### ISSUE THREAD

**Issue by tjakubo2** [pkulchenko/ZeroBraneStudio#832]
Hello, I love the IDE but have a little problem - I'll be grateful for any possible solution/plugin idea/config tweak.

When typing in blocks by first opening and closing it (leaving space for its body), the closing "end" is not getting auto indented unless RET is clicked (where often newline is not wanted). Additionally, after manually de-denting the "end" with backspace, next TAB click inside the newly created block indents one level too deep.

I've created a short video demonstrating those problems:
https://gfycat.com/PhysicalSaneDikkops
Maybe someone would have an idea on how to have the "end" auto-indented (marked (1)), maybe a plugin, as well as somehow dealing with that two level indent marked (2).

**Comment by pkulchenko** [comment]
@tjakubo2, it's a bit tricky, but if you just want to check for the first `end` on the line, then something like this may work (add this to the config file):

```lua
package {
  onEditorCharAdded = function(self, editor, event)
    local ch = event:GetKey()
    if ch ~= string.byte("d") then return end

    local line = editor:GetCurrentLine()
    local pos = editor:GetCurrentPos()
    local linestart = editor:PositionFromLine(line)
    if editor:GetLine(line):sub(1,pos-linestart):find("^%s*end") then
      local tw = editor:GetUseTabs() and editor:GetTabWidth() or editor:GetIndent()
      local indent = editor:GetLineIndentation(line)
      editor:SetLineIndentation(line, indent - tw)
    end
  end
}
```

This is a package, but you can specify it in the config file too.

This is not going to work in all cases, as you may have a variable that starts with `end`, which will get deindented as well, but there is no general solution for that case (as it's not known when deindent until the next character is seen).

**Comment by tjakubo2** [comment]
Thanks a lot @pkulchenko, you rock. ZB's API is amazing, I'm loving it more and more every day.

I've come up with the following code to suit it better for my application (tho it's not as light as your version above) - just added "undo indent" if you type something after the "end" so it also handles all the vars starting with it. Very happy with the outcome.
```lua
-- Line that was auto-indented beucause it started with "end"
local indentedLine = nil
local function tabWidth(editor)
  return editor:GetUseTabs() and editor:GetTabWidth() or editor:GetIndent()
end

return {
  onEditorCharAdded = function(self, editor, event)
    local ch = event:GetKey()
    if ch ~= string.byte("d") then 
      -- Un-indent if continuing and "end"
      if indentedLine and indentedLine == editor:GetCurrentLine() then
        local indent = editor:GetLineIndentation(indentedLine)
        editor:SetLineIndentation(indentedLine, indent + tabWidth(editor))
        indentedLine = nil
      end
      return 
    end
		
    -- Indent if typed "end"
    local line = editor:GetCurrentLine()
    local pos = editor:GetCurrentPos()
    local linestart = editor:PositionFromLine(line)
    if editor:GetLine(line):sub(1,pos-linestart):find("^%s*end$") then
      local indent = editor:GetLineIndentation(line)
      -- Prevent bottom level ends from messing with un-indent
      if indent > 0 then
        editor:SetLineIndentation(line, indent - tabWidth(editor))
        indentedLine = line
      end
    end
  end
}
```

<3

**Comment by pkulchenko** [comment]
Very good! I think you can extend it to cover more keywords than just `end`; you can put them in a table and check if the typed character matches the last character for any of them and then check if that keyword was typed.

Re-indenting is interesting as well. You can probably check for the letter being typed right after the keyword (instead of keeping track of the indent line), as the indent line may not work if you type `end` twice and then come back to one of them to add something more ;).

Feel free to wrap it into a plugin and send a pull request for the plugin repository: https://github.com/pkulchenko/ZeroBranePackage.
