### ISSUE TITLE
Opening double square brackets within block comments

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pkulchenko/ZeroBraneStudio#833]
It seems that there is a small bug in the coloring, when one opens double square brackets within a block comment. ZeroBrane only recognizes that the block comment has ended when all opened double square brackets are closed. Lua considers the first closing double square brackets as the end of the comment. For example, the following code:

```lua
--[[
abc
[[ def
]]
print("aaa")
--]]
print("bbb")
```

is show in ZeroBrane as below. The first print is shown as a comment (line 7), but it executes properly in Lua.

![screen shot 2017-11-17 at 15 33 18](https://user-images.githubusercontent.com/8777631/32960636-cfc442f4-cbac-11e7-8e5f-ccfaa7ab5ca2.png)

I'm using ZeroBrane version 1.7 in Mac.

**Comment by pkulchenko** [comment]
I agree, it's a bug, but unfortunately, it's a bug in the Lua lexer that comes with Scintilla, so it's not going to be fixed until it's updated upstream, new version included in wxwidgets, and then wxwidgets/wxlua upgraded, so it's going to take a while.

The workaround is to use the lexpleg-based lexer by setting `ide.specs.lua.lexer = "lexlpeg.lua"`, which doesn't have this issue. There may be side effects (let me know if you find some), but so far it's the best workaround I can suggest.

**Comment by pedro-andrade-inpe** [comment]
Thanks. There is no hurry for me, I just wanted to register the problem.
