### ISSUE TITLE
When passing a new project directory as command-line argument, the previous project is unnecessarily loaded

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#834]
Example output from my maketoolbar plugin:
```
maketoolbar::onRegister()
maketoolbar::onProjectPreLoad("/home/proj/Lua/oldproject/")
maketoolbar::onProjectLoad("/home/proj/Lua/oldproject/")
maketoolbar::onProjectClose("/home/proj/Lua/oldproject/")
maketoolbar::onProjectPreLoad("/home/proj/Lua/newproject/")
maketoolbar::onProjectLoad("/home/proj/Lua/newproject/")
```
This may delay the start of ZBS quite heavy, if /home/proj/Lua/oldproject/ is big and will be parsed by for ex. a version-system plugin (like my subversion plugin, which is still in progress)

**Comment by pkulchenko** [comment]
I'm aware of this, but it may be a bit problematic to change as the settings (which store information about projects) are processed before files and directories that were passed as command line arguments are processed.

I also think this is correct (logically), as there may still be passed file names that need to be processed in the context of already loaded project.

Also, if the processing is going to take significant amount of time, I don't think it needs to be done on ProjectLoad, as it's going to delay and block UI for any project switching. What you should probably do is to store the project on ProjectLoad, but delay its processing using `onIdle` or `onIdleOnce` event, which will make it happen on the first IDLE event when the project is already initialized and the UI processing is completed. If the project is switched multiple times, only the last one will be stored and re-initialized only once.

**Comment by jjvbsag** [comment]
Yes. This "load last project on start" is an option, which I'd like to have **configurable** (just like almost all other IDE's have). I had several issues with the in the past. (Before I got aware of _this_ issue)

Opened (by accident) ZBS on a huge (really huge) tree, it was'n usable any more. I had to kill the process. But after restart the same happened, because ZBS had already remembered the problematic path. I had to manually remove the project from `~/.ZeroBraneStudio` to get ZBS working again.

I had similar problems on Windows, when there is a project 
- located on a network share and
- the server for the network share is offline

ZBS tries to access this and windows has long (very long) timeouts. During this time, one can only kill the (invisible) ZBS Process. This seems to happen, even if the share is only in the `projectsession` list.

If one could switch ZBS to a new project without loading the old project before, it would solve these problems.

**Comment by pkulchenko** [comment]
> Opened (by accident) ZBS on a huge (really huge) tree, it was'n usable any more. I had to kill the process.

I think there are several things in play. Having a configuration option won't help in this case, as it should still work on large trees with a default configuration. Do you have more details on what happened in this particular case? Large trees should not affect the initial load significantly, as the tree is not being scanned, only one level of files is read, so it shouldn't take long even on a complex tree. I can see why it may get slow on a network share (especially if it's offline), but in other cases it shouldn't be a problem.

I think the directory scanning should check for timing delays and abort the read if a file open operation takes a long time. This will return incomplete results, but will allow to switch a project directory to a different (properly working) one.

**Comment by jjvbsag** [comment]
Ok, I will try to investigate for more details on whats happening. I will come back to you then.

**Comment by pkulchenko** [comment]
@jjvbsag, sounds good. I'm not sure how to re-create this locally, so if you could check the time it take for `dir:Open(path)` and `dir:GetFirst(...)` calls in `util.lua`, it would be great. You can simply add `os.clock()` calls around it to show how much time it took. I'm interested in whether to detect it after `Open` or `GetFirst` calls, as I'd prefer to limit the number of places for this check.

**Comment by jjvbsag** [comment]
Ok, did some tests. In an empty directory created a bunch of files with
```lua
for i=1,10000 do
	local fd=assert(io.open("file"..i..".txt","w"))
	fd:write(i)
	fd:close()
end
```
Then I benchmarked the directory reading
```lua
require"wx"
require"socket"
local t0=socket.gettime()
local d=wx.wxDir('.')
local ok,entry=d:GetFirst('*',wx.wxDIR_DIRS+wx.wxDIR_FILES)
while ok do
	ok,entry=d:GetNext()
end
d:Close()
local t1=socket.gettime()
print(t1-t0,"sec")
```
Output is `0.053748846054077 sec` (on a REAL fast system: Ryzen7 1800X+M.2 SSD Samsung 960Pro,xubuntu 16.04) This may be a bit slower on a harddisk.

Now starting ZBS without any packages (renamed the packages directory away) takes _several seconds_. I guess, the penalty is in filling the tree control. 

I know, this is a bigger task, but I would suggest the following at ZBS startup.

- Create IDE with all Windows/Menus/Controls, but without any project load
- Show it to the user (so he can see, the program has been started)
- Begin loading the project/filetree based on the command line arguments (maybe with a busy-cursor)

Just a start for a discussion, if you mind. :beers:

**Comment by pkulchenko** [comment]
> Create IDE with all Windows/Menus/Controls, but without any project load
> Show it to the user (so he can see, the program has been started)
> Begin loading the project/filetree based on the command line arguments (maybe with a busy-cursor)

I tried that before; unfortunately populating controls that are already visible is much slower than populating "invisible" controls (even when controls are "freezed"), which contributes to overall launch time to be slower (even for those cases that are sufficiently fast now).

I have a plugin that I use to measure the startup time; you may try running it to see what numbers you get. For example, this is what I have one the second run of the IDE (only showing methods that take longer than 5ms):

```
0.078 started
0.265 OnRegister
0.281 0.265+0.016 fillTips@src/editor/autocomplete.lua:98
0.281 0.265+0.016 generateAPIInfo@src/editor/autocomplete.lua:173
0.281 0.265+0.016 reloadAPI@src/editor/autocomplete.lua:315
0.281 0.265+0.016 ReloadAPIs@src/editor/autocomplete.lua:321
0.281 0.265+0.016 selectInterpreter@src/editor/menu_project.lua:56
0.281 0.265+0.016 ProjectUpdateInterpreters@src/editor/menu_project.lua:103
0.296 0.281+0.015 selectInterpreter@src/editor/menu_project.lua:56
0.296 0.281+0.015 ProjectSetInterpreter@src/editor/menu_project.lua:82
0.296 0.281+0.015 SettingsRestoreEditorSettings@src/editor/settings.lua:544
0.312 0.296+0.016 StylesApplyToEditor@src/editor/style.lua:290
0.312 0.296+0.016 SetupKeywords@src/editor/editor.lua:1705
0.312 0.296+0.016 NewFile@src/editor/commands.lua:16
0.312 0.296+0.016 StoreRestoreProjectTabs@src/editor/commands.lua:790
0.328 0.312+0.016 PrependStringToArray@src/util.lua:18
0.343 0.328+0.015 GetFileExt@src/util.lua:42
0.343 0.328+0.015 ismatch@src/util.lua:118
0.359 0.343+0.016 ismatch@src/util.lua:118
0.374 0.359+0.015 ismatch@src/util.lua:118
0.390 0.328+0.062 getDir@src/util.lua:146
0.437 0.328+0.109 GetFileList@src/util.lua:66
0.468 0.453+0.015 FindSpec@src/editor/package.lua:935
0.468 0.453+0.015 getIcon@src/editor/filetree.lua:54
0.484 0.468+0.016 getIcon@src/editor/filetree.lua:54
0.499 0.484+0.015 getEventHandlers@src/editor/package.lua:22
0.515 0.499+0.016 GetFileExt@src/util.lua:42
0.515 0.499+0.016 getIcon@src/editor/filetree.lua:54
0.531 0.515+0.016 GetProject@src/editor/package.lua:341
0.531 0.515+0.016 getIcon@src/editor/filetree.lua:54
0.546 0.531+0.015 GetProject@src/editor/package.lua:341
0.546 0.531+0.015 getIcon@src/editor/filetree.lua:54
0.578 0.562+0.016 getIcon@src/editor/filetree.lua:54
0.593 0.578+0.015 getEventHandlers@src/editor/package.lua:22
0.609 0.593+0.016 GetFullPathIfExists@src/util.lua:269
0.609 0.593+0.016 getIcon@src/editor/filetree.lua:54
0.609 0.328+0.281 treeAddDir@src/editor/filetree.lua:69
0.624 0.328+0.296 treeSetRoot@src/editor/filetree.lua:148
0.843 onAppLoad
0.968 onIdleOnce
```

One the first start it takes about 1s to load the executable and the dll, so about 2s overall. Populating the project tree takes a significant chunk of that time (`0.624 0.328+0.296 treeSetRoot@src/editor/filetree.lua:148`), so improvements there may help, but I'm not sure if showing the IDE before populating it would help. I'll check if delaying the tree to some later time help with the performance, but unfortunately there are some calls that may need to be handled/removed as the tree is updated when editors are loaded and in some other cases as well...

Here is the plugin (I plan to push it to the repository soon):

```
local log = {}
local call = {}
local function logit(msg) table.insert(log, ("%.3f %s"):format(os.clock(), msg)) end

logit('started')
return {
  name = "Measures startup performance",
  description = "Measures IDE startup performance up to the first IDLE event.",
  author = "Paul Kulchenko",
  version = 0.1,

  onRegister = function(self)
    logit('OnRegister')
    debug.sethook(function(event, line)
      local src = debug.getinfo(2, "Sn")
      local name = src.name
      if not name then return end

      if event == "call" then
        call[name] = os.clock()
      else
        -- we may be returning from methods we haven't seen
        if not name or not call[name] then return end

        local calltime = os.clock()-call[name]
        if calltime >= 0.005 then
          logit(("%.3f+%.3f %s"):format(call[name], calltime, name..src.source..':'..src.linedefined))
        end
      end
    end, "cr")
  end,

  onUnRegister = function(self) debug.sethook() end,

  onAppLoad = function(self)
    debug.sethook()
    logit('onAppLoad')
  end,

  onIdleOnce = function(self)
    logit('onIdleOnce')
    ide:Print(table.concat(log, "\n"))
    log = {}
  end,
}
```

**Comment by pkulchenko** [comment]
> Now starting ZBS without any packages (renamed the packages directory away) takes several seconds. I guess, the penalty is in filling the tree control.

(I missed that comment). Yes, if you are running on a project folder with 10,000 files, then populating the tree control will definitely take time, even though the reading of the files is actually fast (50ms).

If you *do* have so many files, but are not interested in seeing them, then adding them to the [excludelist](https://studio.zerobrane.com/doc-general-preferences#file-exclusion-lists) (using a mask) may be a good solution.

**Comment by jjvbsag** [comment]
@pkulchenko I will close this issue, because the case of thousands of files is not typical and I will live with the behavior. And the issue with long delay in accessing network shares from offline computers is surely a windows problem, you can't fix.

We can still continue discussion here, if you mind.
