### ISSUE TITLE
Very slow lexing when opening large XML files

### ISSUE THREAD

**Issue by Silverlan** [pkulchenko/ZeroBraneStudio#835]
I've tried to open a fairly large file with ZeroBrane, which caused it to freeze completely. I forced it to close using the TaskManager, but it kept freezing again every time I tried to start it (Presumably because it tried to restore the last session and therefore open the file again). I was able to start it again properly by renaming the file, so it's not a huge issue, just somewhat irritating.

I've only been able to replicate it with this specific file: https://pragma-engine.com/sharex/session.xml

**Comment by pkulchenko** [comment]
I suspect there is something wrong with the xml lexer for lexlpeg (lualibs/lexers/xml.lua), as when I use the internal Scintilla lexer, the file is loaded without much delay. I've tried on a smaller version of the file and it's loaded, but there seems to be some quadratic slowdown, which make the processing really slow on large files. I'll take a quick look, but may need to report to the author of Scintillua.

For now the workaround is to use the internal Scintilla lexer; you may install [XML package](https://github.com/pkulchenko/ZeroBranePackage/blob/master/xml.lua) to enable this.

**Comment by pkulchenko** [comment]
Just to capture some numbers: it takes several seconds on a smaller copy of the original file (200Kb); the original size is 1.1Mb.
