### ISSUE TITLE
After a few days of use, ZeroBrane begin to flash back

### ISSUE THREAD

**Issue by chenbohua3** [pkulchenko/ZeroBraneStudio#836]
After a few days of use, ZeroBrane seems to be having some problems.

When i open it in dash, it will flash back. And when i cd /opt/zbstudio and run sh zbstudio.sh, an error has occurred:

bin/linux/x86/lua: error loading module 'wx' from file 'bin/linux/x64/clibs/libwx.so':
	bin/linux/x64/clibs/libwx.so: wrong ELF class: ELFCLASS64
stack traceback:
	[C]: at 0x080b42d7
	[C]: in function 'require'
	src/main.lua:38: in main chunk
	[C]: at 0x0804c095

And i use zbstudio-uninstall to uninstall it and re-install, same problem will happen.
Can you tell me how to fix it？Thanks for your patience:) 

(version is 1.70 system is ubuntu 16.04).

**Comment by pkulchenko** [comment]
> After a few days of use, ZeroBrane seems to be having some problems.

Just to confirm, it was working initially and then stopped working? What changed on your system?

> bin/linux/x64/clibs/libwx.so: wrong ELF class: ELFCLASS64

This may happen if a 32bit executable tries to load a 64bit library.

Is your linux 32bit or 64bit? What does `uname -n` return on your system?

**Comment by chenbohua3** [comment]
Yes, i could see my code appeared which was opened last time i used zerobrane(about 0.5 seconds) then it flashes back.
my linux is 64bit and it seems that i did not do anything to my system.
and uname -n return face-linux:

    face@face-linux:~$ uname -n
    face-linux

**Comment by pkulchenko** [comment]
> my linux is 64bit and it seems that i did not do anything to my system.

Given the original message you sent (`bin/linux/x86/lua: error loading module 'wx' from file 'bin/linux/x64/clibs/libwx.so':`), it looks like it's misdetected from the shell script (as it loads 32bit lua executable), but is detected correctly from the Lua code itself (and that's why it tries to load the 64bit library).

Could you also include output of `uname -m` and `uname`? For some reason the following fragment in `zbstudio.sh` is misdetecting the platform:

```
  case "$(uname -m)" in
    x86_64)  ARCH=x64;;
    armv7l)  ARCH=armhf;;
    aarch64) ARCH=aarch64;;
    *)       ARCH=x86;;
  esac
```

**Comment by chenbohua3** [comment]
plz wait for a while, i am checking the output.

**Comment by chenbohua3** [comment]
The output are listed below
face@face-linux:~$ uname
Linux
face@face-linux:~$ uname -m
x86_64

**Comment by pkulchenko** [comment]
```
face@face-linux:$ uname -m
x86_64
```

This looks correct; I don't see how it may get wrong in the script then.

Can you save the following in a file `test.sh`, run, and copy the output here:

```
case "$(uname -m)" in
    x86_64)  ARCH=x64;;
    armv7l)  ARCH=armhf;;
    aarch64) ARCH=aarch64;;
    *)       ARCH=x86;;
esac
echo bin/linux/$ARCH/lua

if [[ "$(uname -m)" == "x86_64" ]]; then ARCH="x64"; else ARCH="x86"; fi
echo bin/linux/$ARCH/lua
```

There should be two lines in the output. Thank you.

**Comment by chenbohua3** [comment]
this is the output:
face@face-linux:~$ ./test.sh
bin/linux/x64/lua
bin/linux/x64/lua

**Comment by pkulchenko** [comment]
This is exactly what should be expected. I'm not sure what's wrong then with the output you shown in the first message.

> cd /opt/zbstudio and run sh zbstudio.sh, an error has occurred:

Can you do the following:
1. cd /opt/zbstudio
2. open zbstudio.sh and add line `echo bin/linux/$ARCH/lua` before the last line that starts with `(cd...`
3. run ./zbstudio.sh

This should return the same error you saw, but also print the path of the executable. What is that path?

**Comment by chenbohua3** [comment]
some strange things happen: this time i open my linux, when i open the zerobrane in odd times, it works well, and in even times, it flushes back...... now i am going to reboot my linux end check the result again.

**Comment by pkulchenko** [comment]
keep this line there and maybe add showing the result of `uname -m` as well. I'm interested in the results when starting the script fails.

**Comment by chenbohua3** [comment]
i did not reboot my system and do what you said, the result is :
face@face-linux:/opt/zbstudio$ ./zbstudio.sh
bin/linux/x64/lua
face@face-linux:/opt/zbstudio$ ./zbstudio.sh: 行 5:  4124 段错误               (核心已转储) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"

face@face-linux:/opt/zbstudio$ uname -m
x86_64

do i need to switch system language to english?

**Comment by pkulchenko** [comment]
> face@face-linux:/opt/zbstudio$ ./zbstudio.sh: 行 5: 4124 段错误 (核心已转储) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"

Where does this line come from? Is this some kind of error message? Can you paste your zbstudio.sh script?

**Comment by chenbohua3** [comment]
zbstudio.sh in /opt/zbstudio/

#!/bin/bash

if [[ "$(uname -m)" == "x86_64" ]]; then ARCH="x64"; else ARCH="x86"; fi
echo bin/linux/$ARCH/lua
(cd "/opt/zbstudio"; bin/linux/$ARCH/lua src/main.lua zbstudio "$@") &

**Comment by chenbohua3** [comment]
did i add the line in wrong position?

**Comment by chenbohua3** [comment]
After language changed, the result comes to be 

face@face-linux:~$ cd /opt/zbstudio/
face@face-linux:/opt/zbstudio$ ./zbstudio.sh
bin/linux/x64/lua
face@face-linux:/opt/zbstudio$ ./zbstudio.sh: line 5:  3081 Segmentation fault      (core dumped) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"

**Comment by chenbohua3** [comment]
sorry for my careless， when i use sh zbstudio.sh, same error returned:

face@face-linux:/opt/zbstudio$ sh zbstudio.sh
zbstudio.sh: 3: zbstudio.sh: [[: not found
bin/linux/x86/lua
face@face-linux:/opt/zbstudio$ bin/linux/x86/lua: error loading module 'wx' from file 'bin/linux/x64/clibs/libwx.so':
	bin/linux/x64/clibs/libwx.so: wrong ELF class: ELFCLASS64
stack traceback:
	[C]: at 0x080b42d7
	[C]: in function 'require'
	src/main.lua:38: in main chunk
	[C]: at 0x0804c095

**Comment by pkulchenko** [comment]
yes, `sh` doesn't include `[[`command, which is `bash` specific. When you use `./zbstudio.sh`, it uses `bash` (as it's specified on the first line), but when you call `sh zbstudio.sh`, you'll get the error you see.

Try using bash and it should work.

**Comment by chenbohua3** [comment]
face@face-linux:/opt/zbstudio$ bash zbstudio.sh
bin/linux/x64/lua
face@face-linux:/opt/zbstudio$ zbstudio.sh: line 5:  3865 Segmentation fault      (core dumped) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"

same error occured (appear for about 0.5s then close automatically)

**Comment by pkulchenko** [comment]
Remove `&` on the last line and run it again; it should print the error message.

**Comment by chenbohua3** [comment]
face@face-linux:/opt/zbstudio$ bash zbstudio.sh
bin/linux/x64/lua
zbstudio.sh: line 5:  4862 Segmentation fault      (core dumped) bin/linux/$ARCH/lua src/main.lua zbstudio "$@"

**Comment by pkulchenko** [comment]
Don't see any issue; can you run: `cd "/opt/zbstudio"; bin/linux/x64/lua src/main.lua zbstudio`? do you get the same error?

**Comment by chenbohua3** [comment]
face@face-linux:~$ cd "/opt/zbstudio"; bin/linux/x64/lua src/main.lua zbstudio
Segmentation fault (core dumped)

same error...

**Comment by pkulchenko** [comment]
> What surprised me was that it sometimes opened normally, sometimes repeating the above scenario

I can't say definitively what's happening here, especially when it sometimes works and sometimes doesn't. There were some messages about Nvidia driver issues in the crash dump that you provided earlier, but I'm not sure if they are related to this issue or not. It looks like there is some problem initializing GTK during some of the launches, but I can't say what's contributing to that.

You may try two things. Clone a copy of the repository and try running from a cloned folder. If this still crashes, then recompile the wxwidgets library with debug info (`cd build; bash build-linux.sh lua wxwidgets wxlua debug`) and check the stack trace; this may help with figuring out what's going on. Upgrading gtk libraries to the latest 2.x may help (if you are not on the latest one).

**Comment by chenbohua3** [comment]
thanks for the advice, i will try them to fix the problem~

**Comment by pkulchenko** [comment]
@chenbohua3, closing for now; you can update the ticket if you had a chance to test the earlier suggestions.
