### ISSUE TITLE
Custom build can't find wxlua library (FreeBSD)

### ISSUE THREAD

**Issue by yurivict** [pkulchenko/ZeroBraneStudio#839]
It fails with these messages:
```
	no field package.preload['wx']
	no file 'lualibs/wx.lua'
	no file 'lualibs/wx/wx.lua'
	no file 'lualibs/wx/init.lua'
```

I first thought that wxLua is needed (http://wxlua.sourceforge.net/), but it doesn't install this file.

**Comment by pkulchenko** [comment]
You don't need wx library as it is included with the IDE itself. What platform are you running on? What version of the IDE are you using? How did you install it? How do you launch it?

Somehow it looks like it's only checking for the .lua file and not for .dll or other dynamic library.

**Comment by yurivict** [comment]
I am trying to create the FreeBSD port for it. Version is 1.70. I installed it with cmake.
Launching it with ```zbstudio``` command.

**Comment by yurivict** [comment]
Sorry, the original error is:

```
$ zbstudio 
/usr/local/bin/lua52: src/main.lua:38: module 'wx' not found:
	no field package.preload['wx']
	no file 'lualibs/wx.lua'
	no file 'lualibs/wx/wx.lua'
	no file 'lualibs/wx/init.lua'
	no file '/usr/local/share/lua/5.2/wx.lua'
	no file '/usr/local/share/lua/5.2/wx/init.lua'
	no file '/usr/local/lib/lua/5.2/wx.lua'
	no file '/usr/local/lib/lua/5.2/wx/init.lua'
	no file './wx.lua'
	no file 'bin/linux/x86/clibs/libwx.so'
	no file 'bin/linux/x86/clibs/wx.so'
	no file '/usr/local/lib/lua/5.2/wx.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './wx.so'
stack traceback:
	[C]: in function 'require'
	src/main.lua:38: in main chunk
	[C]: in ?
```

It doesn't install ```wx.lua``` or anything like ```*wx.so```.

**Comment by pkulchenko** [comment]
> I installed it with cmake.
> Launching it with zbstudio command.

I'm confused; you'll need to be more specific. What did you install it with cmake? zerobrane studio? wxlua?
 
> no file 'bin/linux/x86/clibs/libwx.so'

This is where the library should be. Is this the right architecture? Are you running x86 or x64? One reason may be that the architecture is mis-detected. What does `uname -m` return on your machine? Is it 64bit or 32bit?

I'm not sure how you are building wxlua, but you can use the scripts that come with the IDE itself; you'll need to run `(cd build; ./build-linux.sh lua wxwidgets wxlua)` to build wx library.

**Comment by yurivict** [comment]
> I'm confused; you'll need to be more specific. What did you install it with cmake? zerobrane studio? wxlua?

Both zerobrane studio and wxlua are built with cmake.

wxLua actually builds it and installs it here: ```/usr/local/lib/libwx.so```, so it looks like this is a path
mismatch.

**Comment by pkulchenko** [comment]
> wxLua actually builds it and installs it here: /usr/local/lib/libwx.so, so it looks like there is a path
mismatch.

You'll need to copy it to `bin/linux/x86/clibs/libwx.so` (assuming x86 is the correct architecture).

> /usr/local/bin/lua52: src/main.lua:38: module 'wx' not found:

You seem to be using lua52 to run the IDE itself and I have never tested this configuration; having said that, I don't see why this wouldn't work, but if you run into any compatibility issues, let me know.

> Do you know what determines the library path.

The IDE adds its internal paths, but it also uses `package.cpath`, so whatever is configured should be used. You check for `/usr/local/lib/lua/5.2/wx.so`, but install the file into `/usr/local/lib/libwx.so`; if you fix the references, I expect that things start working.

**Comment by pkulchenko** [comment]
I'm closing this, as I don't see anything that needs to be done in the IDE to support this configuration; feel free to update the ticket if you run into any compatibility issues and I'll take a look.
