### ISSUE TITLE
Crash on macOS 10.13.1 upon launch

### ISSUE THREAD

**Issue by qgxqgx** [pkulchenko/ZeroBraneStudio#841]
when I start the ZeroBranceStudio on mac os 10.13.1 , it crashed :

com.apple.xpc.launchd[1] (com.ZeroBrane.ZeroBraneStudio.29012[7109]): Service exited with abnormal code: 1

**Comment by pkulchenko** [comment]
@qgxqgx, what version of the IDE are you using? If it's not v1.70, you should upgrade as there were fixes for 10.13.x
