### ISSUE TITLE
Set SCI_SETENDATLASTLINE.

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#842]
Is it possible set [SCI_SETENDATLASTLINE](http://www.scintilla.org/ScintillaDoc.html#SCI_SETENDATLASTLINE)

May be there exits way to set arbitrary scintilla settings?

**Comment by pkulchenko** [comment]
@moteus, yes,  you can call `ide:GetEditor():SetEndAtLastLine(false)` to set the value. For example, you can wrap it into a plugin this way (add this to the config file):

```
package {
  onEditorNew = function(self, editor) editor:SetEndAtLastLine(false) end,
  onEditorLoad = function(self, editor) editor:SetEndAtLastLine(false) end,
}
```

I'll consider adding a configuration setting for it.
