### ISSUE TITLE
Shortcut for clear output.

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#844]
Currently `ID.CLEAROUTPUT` uses for switch flag to clear output before run
And same ID uses for output popup menu to actually clear output.
So it is not possible assign shourtcut key for this ID to do clear output.
I suggest add new ID for switcher and use `CLEAROUTPUT` for new menu item

**Comment by pkulchenko** [comment]
I agree; I think it's the right way to handle this. I considered it last time I was looking at this change, but there were some considerations against it, mainly because of compatibility with other code that may be using/referencing the existing ID. May still be worthwhile though.

**Comment by pkulchenko** [comment]
@moteus, this should be resolved now.
