### ISSUE TITLE
Replace base file path

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#846]
Some time i need change base filepath on remote system and on my
I implement this 
```Lua
function debugger:ActivateDocument(file, line, activatehow)
....
  local dir_map = ide.config.debugger and ide.config.debugger.dir_map
  if dir_map then
    for _, map in ipairs(dir_map) do
      local n
      file, n = string.gsub(file, map[1], map[2])
      if n > 0 then break end
    end
  end
...
```
and in config I put this
```Lua
debugger.dir_map = {
  {"^/usr/share/", ""};
}
```

**Comment by pkulchenko** [comment]
Could you describe the use case for this? I believe this has been discussed on the maillist already, but the remapping should be handled "automatically" by the IDE.

**Comment by moteus** [comment]
In my case I have code in `/usr/share/...`. This is my Docker test system where I install and run my app.
So to be able auto open files during debuging in my local (dev) machine I have to convert path to somethink like `/home/moteus/project/...`

**Comment by pkulchenko** [comment]
If that's the case, then you actually don't need to do anything. As long as the project path you set matches the one in the docker container, everything will work automatically for you. For example, if the path in the container is `/usr/share/project/...` and the path you are debugging with is `/home/moteus/project/...`, then just set the project directory to `/home/moteus/project/...` and it will work. You'll see a message like `Mapped remote request for ... to ...` in the Output window when the debugging is started, which will include two paths that have been remapped.

If this doesn't work, then re-open the ticket and provide full path for the project, the project directory set in the IDE, the directory in the application, and the content of the Output window during debugging. You may also want to set `debugger.verbose=true` and include that output as well.

**Comment by moteus** [comment]
Whell. In my case I have actually 2 `project` one of which I develop and second one is `server` part.
I can not edit this server project and install script installs it from repo on docker during configure test env.
So in docket I have `~/myproject` which map to my project and `/usr/share/server` which should map on second project. And some time when I debug my project I want to be able to step in in to a server code.
