### ISSUE TITLE
Export wxEVT_CHAR event to packages API

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#850]
I Add this one
```Lua
  editor:Connect(wx.wxEVT_CHAR,
    function (event)
      if PackageEventHandle("onEditorKey", editor, event) == false then
        -- this event has already been handled
        return
      end
      event:Skip()
    end)
```
And be able port [smartbraces.lua](https://bitbucket.org/scite-ru/scite-ru.bitbucket.org/src/ec9e67562336df397628b358c84b770064c60a9a/pack/tools/smartbraces.lua?at=default&fileviewer=file-view-default) script from [Ru-Scite](https://bitbucket.org/scite-ru/scite-ru.bitbucket.org/wiki/Home) project.
Its more robust version then autodelimitersurroundselection.lua package

**Comment by pkulchenko** [comment]
@moteus, why does it need a new handler? I looked at the code, but after a quick glance don't see anything that requires `EVT_CHAR`.

**Comment by moteus** [comment]
Just put my ports for some [packages](https://github.com/moteus/zbs-package) from ru-SciTE project.
smartbraces script uses this event to be able to handle user input and discard it in some cases.
When user input `(` then this script add `)` and put cursor between braces.
And then if user try input `)` then this script discard it and just moves cursor so there no second close brace.
May be it possible handle in other way but for me it was faster just add this handler and make one to one port.

**Comment by pkulchenko** [comment]
@moteus, it should be possible without any additional handlers, as [autodelimiter](https://github.com/pkulchenko/ZeroBranePackage/blob/master/autodelimiter.lua) plugin is doing just that (I thought you already looked at it). I'm closing this ticket, but feel free to update if you still have an issue with removing duplicates.
