### ISSUE TITLE
Confirmation for moving files in the project tree

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#855]
Please add confirm dialog to move file/folder in the project tree.
Now it possible move file with mouse from one dir do another without any notes

**Comment by pkulchenko** [comment]
Hm, I don't think it's a good idea. I have a confirmation for destructive actions (like deletion), but I don't think moving warrants a confirmation dialog. I'm aware that sometimes the movement may be too sensitive and the files will be moved when not intended, but it's easy to move them back. You can also disable the movement completely by setting `filetree.mousemove=false`.

**Comment by d9k** [comment]
I don't want to disable file moving with mouse move (how can I move file from IDE in another way?).
But I use laptop touchpad instead of mouse and I often accidentally move files instead of double click.

@pkulchenko, please make option `filetree.confirm_mousemove` enabling showing confirmation dialog before file move.

**Comment by pkulchenko** [comment]
You don't need a new setting for this, as you can make a new package that shows a confirmation box using existing callback.

Try adding the following to the config:

```lua
package {
  onFiletreeFilePreRename = function(self, tree, itemsrc, source, target)
    return wx.wxMessageBox(("Do you want to move '%s' to '%s'?"):format(source, target),
      "Move/Rename file", wx.wxYES_NO + wx.wxCENTRE, ide:GetMainFrame()) == wx.wxYES
  end
}
```

**Comment by d9k** [comment]
@pkulchenko, many thanks!
Your IDE and Lua are awesome!  :heart_eyes:

**Comment by pkulchenko** [comment]
Good; thanks for the feedback!
