### ISSUE TITLE
Reset hotkeys set in plugin.

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#857]
in onRegister method in plugin I call `ide:SetHotKey(handler, 'Ctrl-Q')`
And it works.  But at some point of time ZBS seems to reset this setting and
starts use one from the configuration file.
Maybe it is related to `cloneview.lua` plugin.

**Comment by pkulchenko** [comment]
That shouldn't happen, as the shortcuts are (mostly) installed when menus are created, which happens before onRegister handler is called. Does it reset it back to the "original" value? Can you see `Ctrl-Q` next of the `File | Exit` menu item when this happens?

Can you remove all other plugins and try it again? `cloneview` shouldn't be causing this, as it doesn't change any shortcuts or menu handlers (at least not in the main menu).

**Comment by moteus** [comment]
After start zbs all works fine. But at some point all my hotkeys are reset.
They back to values defined in config (I define Ctrl-Q to do comment in my user.lua file)
Not sure about cloneview at all.

**Comment by pkulchenko** [comment]
> But at some point all my hotkeys are reset.

Do you know how quickly this happens?

I can't reproduce this. Here is what I added to the config:

```lua
package{onRegister=function()ide:SetHotKey(function()ide:Print("Ctrl-Q")end,'Ctrl-Q')end}
```

I don't have anything else in the config and no other plugins. Pressing `Ctrl-Q` prints the message in the Output window. I don't get any other changes and I've tried for several minutes. I'll wait for a bit longer, but so far I haven't been able to reproduce this.

**Comment by pkulchenko** [comment]
I'd add some output to onRegister and onUnregister events to see if the second one is being called. it may be worthwhile to also add some output to `SetHotKey` if it's indeed called by the IDE itself.

**Comment by moteus** [comment]
I have no time to debug it. But it happens when I press Ctrl-Shift-A (Full screen mode)

**Comment by pkulchenko** [comment]
I can confirm both of the aspects: not removing the shortcut in the menu and also resetting it after `Ctrl-Shift-A`. I'm not sure what exactly happens, but will check if the accelerator table needs to be reset as a workaround on Linux.

**Comment by pkulchenko** [comment]
Here is a patch that fixes the accelerators after Ctrl-Shift-A:

```diff
diff --git a/src/editor/commands.lua b/src/editor/commands.lua
index b2ef107..9b968a8 100644
--- a/src/editor/commands.lua
+++ b/src/editor/commands.lua
@@ -673,6 +673,11 @@ function ShowFullScreen(setFullScreen)
       uimgr:Update()
     end
   end
+
+  -- accelerator table gets removed on Linux when setting full screen mode, so put it back
+  if ide.osname == 'Unix' and setFullScreen then
+    ide:SetAccelerator(-1) -- only refresh the accelerator table after setting full screen
+  end
 end
```

This doesn't fix the presence of the shortcut on the menu item, but it's clearly a wxwidgets problem, as I noticed a similar issue with setting bitmaps on menu items (the bitmap was not set). I'll try to remove and re-insert the menu items, but I vaguely remember there was some issue with that as well. This one is not critical to fix, as the shortcut is not actually used (even though it's present), but would be nice to fix still.

**Comment by moteus** [comment]
https://github.com/wxWidgets/wxWidgets/commit/16d3262deec34cdae9833ba8b0079729f4597eac

**Comment by pkulchenko** [comment]
Yes, it's been fixed in wxwidgets; here is the ticket with the discussion: https://trac.wxwidgets.org/ticket/18053. It will get included in the next wxwidgets upgrade (whenever it happens), but the workaround that was put in place should be sufficient for now.
