### ISSUE TITLE
Fail to start zbstudo (current master)

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#859]
```
bin/linux/x64/lua: src/editor/commands.lua:702: attempt to compare nil with number
stack traceback:
	src/editor/commands.lua:702: in function 'fntab'
	src/editor/settings.lua:180: in function 'SettingsRestoreFileSession'
	src/main.lua:588: in main chunk
	[C]: at 0x00404f08
```
Code is 
```Lua
      if doc.content then
        editor:SetTextDyn(doc.content)
        if doc.filepath and opendoc.modTime and doc.modified < opendoc.modTime:GetTicks() then
          ide:Print(TR("File '%s' has more recent timestamp than restored '%s'; please review before saving.")
            :format(doc.filepath, opendoc:GetTabText()))
        end
      end
```

in this example `doc.modified` is nil so i just add `and doc.modified` condition

**Comment by pkulchenko** [comment]
It looks like some inconsistency in the recovery record, but I can't quite figure out how it could happen. Do you still have the [.ini file](https://studio.zerobrane.com/doc-general-preferences#session-configuration) it happens with? If you do, can you email it to me?

**Comment by moteus** [comment]
No. I just `fix` source and start ZBS.
If it helps. Its happen after I press `restart` button (`ide:Restart(true)`).

**Comment by pkulchenko** [comment]
Did you have some unsaved changes in a new buffer or an updated buffer for an existing file?

**Comment by moteus** [comment]
Not sure about new file. But unsaved changes were there for sure.
