### ISSUE TITLE
wxlua runtime error. After I add the "torch7.lua" plugin for zbs, it happens. 

### ISSUE THREAD

**Issue by TKZC0615** [pkulchenko/ZeroBraneStudio#862]
Lua: Error while running chunk
packages/torch7.lua:152: attempt to call method 'SetOptions' (a nil value)
stack traceback:
	packages/torch7.lua:152: in function 'frun'
	src/editor/menu_project.lua:228: in function 'ProjectDebug'
	src/editor/menu_project.lua:336: in function <src/editor/menu_project.lua:336>
	[C]: at 0x7f9c977d8502
	src/main.lua:731: in main chunk
	[C]: at 0x004054e8

On the Internet for a long time, there is still no solution. Expect your reply, thanks.

**Comment by pkulchenko** [comment]
@TKZC0615, what version of the IDE are you using? This shouldn't happen on any version after 1.40, as SetOption method was added in that version. The plugin has a dependency check, but the check is disabled on the development version, so if you are using an old version from the repository, you may see this error.

**Comment by TKZC0615** [comment]
Thank you very much for your reply. I used the old version-"zbs-torch". Thank you again.

**Comment by pkulchenko** [comment]
@TKZC0615, thank you for the update; closing.
