### ISSUE TITLE
zerobrane studio does not obey windows theme

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#865]
hello I am posting here because I would like a way to customize zerobrane's gtk appearance in window 7.

I now that this obeys linux gtk styles but in windows 7 it just looks bad

I suggest that zerobrane studio gets a gtk editor where you can edit the look of it's widgets.
this would allow using colors, images, and 9slice margins to make each widget look the way we want it to.

the default behavior would still be to detect gtk styles but just in case you don't have one this could be an alternative.

**Comment by pkulchenko** [comment]
@Shadowblitz16, most of what you see in the IDE is configurable, including the colors, images, and some other elements, like border width, with the exception of several colors for menus and statusbar that are taken from the OS theme. If you can include a screenshot with details on what elements you want to change, I can tell you if it's configurable or not.

**Comment by Shadowblitz16** [comment]
how would I change the editor to a flat dark gray theme?

**Comment by pkulchenko** [comment]
You mean like this: http://notebook.kulchenko.com/zerobrane/zerobrane-studio-in-black? You need to select `TomorrowNightBright` color scheme; here are the details on how this can be done: https://studio.zerobrane.com/doc-styles-color-schemes#color-schemes. This is also [covered in the FAQ](https://studio.zerobrane.com/doc-faq#how-to-change-the-color-scheme-in-the-editor).

Note that this only sets some of the colors in the IDE; as I said earlier, there are still colors that are controlled by the OS color theme and are not configurable from the IDE.

**Comment by Shadowblitz16** [comment]
I'm not talking about the code editor. I'm talking about the widgets of the ide
and I don't want to only edit the  colors but the way it looks too.

in linux the whole theme obeys the way linux is themed but in window it does not.
![untitled](https://user-images.githubusercontent.com/2453707/35578816-fc97090c-0599-11e8-903a-a0ed250e000b.png)

**Comment by Shadowblitz16** [comment]
so are you saying if I made a custom theme for window 7 it would changed the style of this part?
![untitled](https://user-images.githubusercontent.com/2453707/35579081-a9073784-059a-11e8-8958-cdca37c5d66f.png)

**Comment by pkulchenko** [comment]
> so are you saying if I made a custom theme for window 7 it would changed the style of this part?

Correct. The parts you highlighted are controlled by the OS color theme (to allow the application to stay consistent with the OS style). This is how it was done for that Linux screenshot. I'll make sure the documentation reflects that.

**Comment by moteus** [comment]
I think it is possible but. Just tested with my custom dialog.
But have no time to deal with it
![image](https://user-images.githubusercontent.com/1804306/35609871-3623eed4-0670-11e8-8a39-e0227a0977a4.png)

**Comment by pkulchenko** [comment]
It's most definitely possible; I just find text files much easier to deal with (and requiring less development). I'm thinking along the lines of what [VS Code provides](https://code.visualstudio.com/docs/getstarted/settings).
