### ISSUE TITLE
Provide preference panel to configure the IDE

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#866]
please add gui based source control within the ide.
I'm not the best with command prompts and I think this could attract more people to use it

**Comment by pkulchenko** [comment]
If you mean using gui controls (like a preference window) to configure colors and styles used in the IDE, it's not likely to happen any time soon, but others may contribute it as a plugin if they want to, as all the mechanisms are in place to support this. I am working on a more convenient way to update the configuration, but it's not going to be using preference panels.
