### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by flamendless** [pkulchenko/ZeroBraneStudio#868]
How to disable the esc button quitting zbs? Also how to stop debugging server on startup?

**Comment by pkulchenko** [comment]
By default `ESC` doesn't quit the IDE and debugger server doesn't start on startup. You might have installed all plugins with one of them being `quitonescape`, which may be causing this. You should only install those plugins that you need and if you remove that plugin, the issue should go away.

**Comment by pkulchenko** [comment]
@flamendless, did removing the plugin fix the issue?

**Comment by flamendless** [comment]
Yes, thank you
