### ISSUE TITLE
Tab background is not styled according to the Windows theme (part2)

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#869]
so I'm making a new issue because I can't reopen my old one but I got my computer up and running again and when I switched to windows classic mode the tabs and tabbar do not obey the windows theme

![pic](https://user-images.githubusercontent.com/2453707/35880110-da8a4822-0b31-11e8-85c4-8a9ffd773a1e.png)
 can this be changed?

**Comment by pkulchenko** [comment]
What's your expected result? I see them being consistent with the toolbar and menu background.

**Comment by Shadowblitz16** [comment]
they should be window classic themes which is more rectangular and doesn't have a gradient

**Comment by pkulchenko** [comment]
Try running this in the console: `ide:GetEditorNotebook():SetArtProvider(wxaui.wxAuiSimpleTabArt())`. Is this what you are looking for?

**Comment by Shadowblitz16** [comment]
it looks better but it only changes the code editor tabs.
also its still not specifically windows classic styled.

are tabs and tab bars suppose obey desktop themes or do they use a internal style within the source code?

**Comment by pkulchenko** [comment]
They use internal style as well as the colors from the OS. This is as close as we can get to the Windows classic style.

**Comment by Shadowblitz16** [comment]
is there a documentation on how to change the ide looks with commands like..
ide:GetEditorNotebook():SetArtProvider(wxaui.wxAuiSimpleTabArt())

**Comment by pkulchenko** [comment]
I don't think so; it may be somewhere in wxwidgets (wxAuiNotebook component), but I don't think they have screenshots for this exact configuration.

**Comment by Shadowblitz16** [comment]
thats too bad hopefully the style problem can be resolved in the future
