### ISSUE TITLE
can't delete folders in zerobrane even while running in admin mode

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#870]
title basically tell the issue..
the delete button is grayed out when I right click a folder..
![pic](https://user-images.githubusercontent.com/2453707/35953545-03e2210a-0c3a-11e8-8ee8-7eed41d1f13c.png)

**Comment by pkulchenko** [comment]
It's a feature; since it doesn't delete to trash, but removes files/folders completely, it will only remove empty folders.

**Comment by Shadowblitz16** [comment]
thats a pretty bad design decision then when you can just use a popup window confiming the deletion

**Comment by pkulchenko** [comment]
You can easily add "Delete Folder" item to the menu and apply whatever logic you think is appropriate, but I'm not going to offer a way to remove folders recursively unless there is an option to recover the files (even with a confirmation dialog).

**Comment by Shadowblitz16** [comment]
@pkulchenko can't you just make it move it to trash?

**Comment by pkulchenko** [comment]
This functionality is not yet in wxwidgets; see a proposed Move to Trash ticket: https://github.com/wxWidgets/wxWidgets/pull/1521

**Comment by Pechu317** [comment]
@pkulchenko you could make it a setting that you have to enable in user.lua

**Comment by pkulchenko** [comment]
@Pechu317, not yet, because this functionality is not available in wxwidgets.
