### ISSUE TITLE
code folding folds whitespace after "end" keyword

### ISSUE THREAD

**Issue by Shadowblitz16** [pkulchenko/ZeroBraneStudio#871]
title basically explain it.
the white space after the end keyword gets folded making code less readable

**Comment by pkulchenko** [comment]
See `editor.foldcompact` setting: https://studio.zerobrane.com/doc-editor-preferences.

You can ask the question on the maillist or the IRC channel as described here: [CONTRIBUTING](../blob/master/CONTRIBUTING.md).

**Comment by Shadowblitz16** [comment]
thankyou
