### ISSUE TITLE
Copy/Cut behavior with nothing selected

### ISSUE THREAD

**Issue by DrPeeps** [pkulchenko/ZeroBraneStudio#878]
When copy/cut is used and no text is selected, the entire line that the cursor in currently on is copied/cut. This even happens on empty lines.

I expect this may be by design, but I find it annoying. Quite often I'll hit Ctrl+C instead of Ctrl+V by mistake, and this will overwrite the contents of the clipboard with an empty line. The only option at that point is to undo back to the point when I cut the original selection, sometimes losing several lines of work in the process, and start over.

I can understand why some users might like to copy/cut entire lines without having to select them first, but should this shortcut also apply to empty lines? I can't see how that's a useful feature.

I am using ZeroBrane Studio 1.70 in a Windows 10 environment.

I wonder if there is a chance the closed issue "Cut and copy commands only work part of the time #759" might be related to this, if the user was sometimes accidentally pressing Ctrl+X twice in a row and ending up with nothing in the clipboard.

**Comment by pkulchenko** [comment]
This is by design and it has been this way for quite some time (probably at least since 2013).

I don't mind making it configurable, but I'll probably keep the same behavior for all the lines, without checking if they are empty or not. So, I'll have an option that when turned off, will *not* copy/cut the current line unless it's selected.

BTW,  there is [clippy](https://github.com/pkulchenko/ZeroBranePackage/blob/master/clippy.lua) plugin that manages a history of clipboard values.

**Comment by DrPeeps** [comment]
Configurable would be great. I understand why the behaviour should remain consistent - other users would wonder why removing consecutive lines with Ctrl+X doesn't work on blank lines! Thanks for the clippy tip (I'm still a fairly new user).

**Comment by pkulchenko** [comment]
@DrPeeps, the following patch should implement what you need:

```diff
diff --git a/src/config.lua b/src/config.lua
index 807bafea..cbc6fe52 100644
--- a/src/config.lua
+++ b/src/config.lua
@@ -20,6 +20,7 @@ return {
     fontname = nil,
     fontsize = nil,
     indentguide = true,
+    linecopy = true,
     linenumber = true,
     modifiedprefix = "âœ± ", -- U+2731 \xe2\x9c\xb1 HEAVY ASTERISK
     nomousezoom = false,
diff --git a/src/editor/menu_edit.lua b/src/editor/menu_edit.lua
index 6526dc30..ceb95174 100644
--- a/src/editor/menu_edit.lua
+++ b/src/editor/menu_edit.lua
@@ -123,8 +123,12 @@ local function onEditMenu(event)
 
   local spos, epos = editor:GetSelectionStart(), editor:GetSelectionEnd()
   if menu_id == ID_CUT then
-    if spos == epos then editor:LineCopy() else editor:CopyDyn() end
     if spos == epos then
+      if ide.config.editor.linecopy then editor:LineCopy() end
+    else
+      editor:CopyDyn()
+    end
+    if spos == epos and ide.config.editor.linecopy then
       local line = editor:LineFromPosition(spos)
       spos, epos = editor:PositionFromLine(line), editor:PositionFromLine(line+1)
       editor:SetSelectionStart(spos)
@@ -132,7 +136,11 @@ local function onEditMenu(event)
     end
     if spos ~= epos then editor:ClearAny() end
   elseif menu_id == ID_COPY then
-    if spos == epos then editor:LineCopy() else editor:CopyDyn() end
+    if spos == epos then
+      if ide.config.editor.linecopy then editor:LineCopy() end
+    else
+      editor:CopyDyn()
+    end
   elseif menu_id == ID_PASTE then
     -- first clear the text in case there is any hidden markup
     if spos ~= epos then editor:ClearAny() end
```

You'll need to add `editor.linecopy=false` to the config to change the default. Can you check and let me know if you notice any issues with it?

**Comment by DrPeeps** [comment]
> Can you check and let me know if you notice any issues with it?

No issues with it so far. Thanks so much for adding this! (And so fast!)

**Comment by pkulchenko** [comment]
Sounds good; I'll push the changes and the doc update shortly.
