### ISSUE TITLE
Tabs behaviour not consistent across Lua files

### ISSUE THREAD

**Issue by DrPeeps** [pkulchenko/ZeroBraneStudio#884]
I have eight Lua files in my project, all in similar format, all with the ".lua" extension. For some reason, ZeroBrane is treating the tabs in two of my files as spaces (I can move through them one space at a time with left/right arrow keys, etc.), but not in the other six files, which work as expected.

Nothing I do seems to change this. I've manually replaced every tab just to be sure they are actual tabs, I've closed/reopened the files and the application. I've also just noticed that editing "Settings: System" uses tabs and "Settings: User" uses spaces (despite neither configuration file containing any tabs unless I enter some).

I use ZeroBrane 1.70 in Windows 10. I use the following ZeroBrane user settings:

```
editor.usetabs = true
editor.autotabs = true
editor.tabwidth = 4
```

How is ZeroBrane deciding which files to treat as tabbed?

**Comment by pkulchenko** [comment]
I think it's related to the combination of autotabs and usetabs settings. If you have autotabs, then the tabs are on if: (1) there is at least one tab in the current file OR (2) usetabs is `true` and no line starts with space. This means that if you have a file that starts with spaces, then autotabs will turn tabs off unless the file also includes tabs. If you always want to use tabs, the set `editor.usetabs=true` and `editor.autotabs=false`.

Note that this only applies to files that already have some content when loaded. New files are set based on `usetabs` setting.

If you have examples of the files where this logic doesn't work, I'll definitely review them.

**Comment by DrPeeps** [comment]
Setting `editor.autotabs=false` fixed my issues. Thanks. I guess I misunderstood how that setting worked.
