### ISSUE TITLE
Step into rock fail

### ISSUE THREAD

**Issue by d9k** [pkulchenko/ZeroBraneStudio#885]
Hello!
I try to debug sailor (https://github.com/sailorproject/sailor) application with `mobdebug` and ZeroBraneStudio.
Can't step into function calls which implementation is located in rocks.
For example can't step into line `sailor.launch()`. I expect source code from file `~/.luarocks/share/lua/5.2/sailor.lua` to load into IDE for debugging it starting from function `launch` when I step into line `sailor.launch()`.

But when I hit "step into" while debug cursor is on the line `sailor.launch()` nothing happens, debug freezes, but ui of IDE is responsive (I can stop debug and restart debug server in IDE).

versions:
ZeroBraneStudio 1.70 with MobDebug 0.702
Lua v. 5.2.4
installed rocks:
* mobdebug v. 0.70-1
* sailor v. 0.5-4
* xavante v. 2-4-0.1

**Update**: when I manually open required source file located in `~/.luarocks` before "step into" (for example by command `zbstudio ~/.luarocks/share/lua/5.2/sailor.lua`) debug continues normally.

**Comment by pkulchenko** [comment]
You do need to have the files open, or have `editor.autoactivate` option enabled to load those files. Also, this post may be of interest: http://www.juliengilli.com/2013/01/03/debugging-lua-web-applications-using-zerobrane-studio-and-xavante/.

**Comment by d9k** [comment]
@pkulchenko, thanks! Maybe `editor.autoactivate = true` should be `true` by default?
I see nothing about this option at the [link you privided](http://www.juliengilli.com/2013/01/03/debugging-lua-web-applications-using-zerobrane-studio-and-xavante/).

**Comment by d9k** [comment]
@pkulchenko, I think some kind of warning must be shown that file is not loaded into IDE. Maybe debug process should even stop.

**Comment by pkulchenko** [comment]
In terms of the documentation, it's covered in both the [debugging overview](https://studio.zerobrane.com/doc-lua-debugging#how-debugging-works) and the [FAQ](https://studio.zerobrane.com/doc-faq#why-stepping-into-function-calls-doesnt-work-in-some-cases).

In terms of this being a default setting, I don't think it's a good choice for the majority of the use cases, as it would then attempt to step into any library call for functions that have Lua sources. Right now the compromise is to open a file if you want to step into it or to configure the IDE to auto-activate the resources for you. In fact, you can change it at any time by running `ide.config.editor.autoactivate=true or false` in the Local console.
