### ISSUE TITLE
Search in current file some time does not work

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#887]
![image](https://user-images.githubusercontent.com/1804306/36914712-48b7c3fc-1e5f-11e8-8fb5-a0aa5c88bb80.png)

I can not reproduce it. Sometimes it starts working after switch tab.
Sometimes I have to restart ZBS. Also, search in files works and find
same text in current file as well

**Comment by pkulchenko** [comment]
I don't have a good explanation other than that the search was happening in Output or Console windows (those are searchable as well). I'll see if I can add the tab text to the message, so it's clear where the search was happening.

If it's something else and you are sure that the tab has the focus, I can check on that file, but at this time I don't have any ideas why it wouldn't be working.

**Comment by pkulchenko** [comment]
@moteus, can you try with the following patch?

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index 9a0c66a5..7662f32d 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -207,6 +207,12 @@ function findReplace:Find(reverse)
     if posFind == wx.wxNOT_FOUND then
       self.foundString = false
       msg = TR("Text not found.")
+      local parent = editor:GetParent()
+      if parent and parent:GetClassInfo():GetClassName() == 'wxAuiNotebook' then
+        local nb = parent:DynamicCast("wxAuiNotebook")
+        local index = nb:GetPageIndex(editor)
+        if index ~= wx.wxNOT_FOUND then msg = nb:GetPageText(index)..": "..msg end
+      end
     else
       self.foundString = true
       local start = editor:GetTargetStart()
```

It should add the tab name to the status line when the content isn't found, so it should be easy to see where the search is being made.

**Comment by pkulchenko** [comment]
@moteus, can you still reproduce the issue? The patch should indicate what tab is being searched, which should remove any ambiguity.
