### ISSUE TITLE
64 Bit Integer Addition Error

### ISSUE THREAD

**Issue by MarkoPaul0** [pkulchenko/ZeroBraneStudio#888]
I am using ZeroBrane 1.70 (ModDebug 0.702) on both MacOS and Windows 10.
When trying to compute the following:
`71776119061217280 + 281474976710655 `
I get 72057594037927936 when the correct result 72057594037927935. If I use the Lua executable located in Zerobrane's binary folder to compute this addition the result I get is correct.
This is a rather important issue because all my 64-bit integer calculations are wrong when running my scripts in Zerobrane.

**Comment by pkulchenko** [comment]
See [this SO question for discussion and details](https://stackoverflow.com/questions/49098445/lua-addition-error).
