### ISSUE TITLE
Trying to debug premake with ZeroBrane

### ISSUE THREAD

**Issue by redorav** [pkulchenko/ZeroBraneStudio#890]
I've been trying to get premake to work with ZeroBrane with little success. I'm using the latest version in the repository which has Lua 5.3 embedded. I've created a script as the documentation says, it looks as follows:

```lua
local zbPath = "C:/Program Files/ZeroBrane Studio"

local cpaths =
{
    zbPath.."/bin/?.dll",
    zbPath.."/bin/clibs53/?.dll",
}

package.cpath = table.concat(cpaths, ';')

local luaLibsRelativePath = zbPath.."/lualibs/"

local paths =
{
	luaLibsRelativePath.."?.lua",
	luaLibsRelativePath.."?/?.lua",
	luaLibsRelativePath.."?/?/?.lua",
        package.path,
}
package.path = table.concat(paths, ';')

print("Loading mobdebug")
local mobdebug = require('mobdebug')

print("Starting mobdebug")
mobdebug.start()
```

I then have a debug version of premake execute a premake5.lua file (the file it uses to generate the solution) and at the top of the file I run this script. At the point of require('mobdebug') it stops for a bit while it loads and then errors while trying to load socket.core. I've made sure it's finding the Lua 5.3 dll but still gives me the following error:

> Error: error loading module 'socket.core' from file 'C:/Program Files/ZeroBrane Studio/bin/clibs53/socket\core.dll':
>         The specified module could not be found.

I'm not quite sure what else to do at this point. How can I get more information as to why it's failing to load?

**Comment by pkulchenko** [comment]
Assuming that `clibs53/socket/core.dll` is the correct location, my next guess would be the same as yours: lua53.dll is not found for some reason. Does premake come with a statically compiled interpreter or does it have lua53.dll next to its executable?

You may try [dependency walker](http://dependencywalker.com/), as it has "profiler" mode that tells you about all the issues with dll loading; you just need to start the process as you'd normally do and pass it parameters you need (a lua file in this case).

**Comment by redorav** [comment]
I'm fairly sure premake links statically with lua, and doesn't load the dll that comes with ZeroBrane. Does it need to load both as dll?

**Comment by pkulchenko** [comment]
If premake links statically, then the only option is to have the Lua API exported from the executable and to add a proxy DLL that will forward requests from the DLL to the exported methods in the executable.

Do you know if the symbols are exported and is it 32bit or 64bit application? You can get the list of exported symbols using `dumpbin /EXPORTS premake.exe`; `dumpbin` is shipped with Visual Studio (including the free version).

**Comment by redorav** [comment]
The executable is 32-bit. Running dumpbin it seems like the executable exports no symbols, as all I get is this:

```
Summary

        1000 .00cfg
        3000 .data
        1000 .gfids
        2000 .idata
       4D000 .rdata
        E000 .reloc
        1000 .rsrc
      1B3000 .text
       D4000 .textbss
```

while for the Lua53.dll there's a big list of lua functions.

I guess I still don't really understand why linking Lua statically in premake shoudn't work. I've looked at a project that branched off of premake called genie, and they seem to also embed Lua statically, exporting no symbols and yet in their github main page (https://github.com/bkaradzic/GENie) state they manage to debug using ZeroBrane with simple instructions.

**Comment by pkulchenko** [comment]
> I guess I still don't really understand why linking Lua statically in premake shoudn't work.

Because the interpreter has to load luasocket library, which is linked against lua DLL. For static linking to work, there are only two options: (1) include the library into the statically linked executable (so add luasocket to it), and (2) export Lua API calls, so it's possible to use a Proxy DLL, which will forward the requests to the exported Lua API calls. If you just make Lua DLL available to the library to load, you'll end up with two Lua VM loaded into the same process, which is likely to trigger "multiple Lua VM's detected" error.

I'm not sure how GENie does this; I asked in #641.

**Comment by madmaxoft** [comment]
@pkulchenko There is a third option that I assume "works", but is super-fragile: Having the exact same sources for both the statically-linked Lua and the Lua DLL (including the C++ runtime). Since the code is the same, it behaves exactly the same on the input data (theoretically), so although the LuaState is created in the EXE, it is then passed through to the DLL transparently by LuaSocket, and the DLL performs the same operations as the EXE would.

**Comment by pkulchenko** [comment]
Right, that's the option that would normally lead to "multi-VM detected error". It can probably work sometimes, but I'm not sure if we can rely on it working. Although if it doesn't lead to any issues, then why not...

It's interesting that it does *not* trigger the multi-VM error, as the check relies on comparing in-memory values, so two instances of the interpreter would definitely have different addresses for those.

**Comment by redorav** [comment]
I'll wait till there's a reply at the genie issue, but the most straightforward thing to do based on your suggestions I think is compile luasocket with premake and bundle them together, perhaps only in a debug build.

**Comment by pkulchenko** [comment]
@redorav, yes, this should work. You can still try @madmaxoft's suggestion; you just need to copy `lua53.dll` next to the premake executable (adding `"/bin/?.dll"` to cpath doesn't help here as the library is not loaded by require, but only as the dependency from another DLL and that search is using different paths).

**Comment by redorav** [comment]
I quicky tried @madmaxoft's idea but the program went from not loading socket.core to just crashing. I guess it would have been a fantastic coincidence that both sources were exactly the same :)

**Comment by pkulchenko** [comment]
I agree; I've see a similar crash with a similar setup, so it *may* work, but only coincidentally and probably only when the versions of Lua embedded and available as a DLL are exactly the same.

I guess we'll have to wait for some details from GENie developers...

**Comment by redorav** [comment]
Ok, so thanks to your kind suggestions I've been able to make some progress! I embedded luasocket into premake, and after a bit of fiddling around (I'm a total beginner with Lua, especially how it interfaces with C) I managed to make premake load socket.core so it's gone beyond that. I managed to get it to complain with the following:

> mobdebug.lua:1057: attempt to call a nil value (field 'tcp')

I went to that line and I figured that the function call tcp() must not be registered with Lua so I went and did just that, by adding it to the function table. However, the same line of code is now failing with a different message,

> Error: attempt to index a function value      ...   mobdebug.lua:1057: in function 'mobdebug.connect'

I don't quite know what this means and the error message doesn't seem very clear to me. Any suggestions on what I'm missing? It feels like I'm so close to getting this working...!

**Comment by pkulchenko** [comment]
Maybe you registered it incorrectly, as it seems like `socket` value is a function, whereas it should be a table. Try calling `local socket = require "socket.core"; print(type(socket))`; it should print `table`. If it's a table, then check the value of `socket.tcp`.

**Comment by redorav** [comment]
Ok, so this is what I have

```lua
local socket = require "socket";
print(type(socket)) -- prints table
print(type(socket.tcp)) -- prints function
print(socket.tcp) -- prints function: 00D9D4B8 (I guess the function pointer address?)
socket.tcp() -- prints error
```

So everything *seems* to be loading fine, but then calling the function is a problem.

**Comment by pkulchenko** [comment]
Looks correct so far. So, what error does it print? It can't be `attempt to call a nil value (field 'tcp')`, since the value is not `nil`...

**Comment by redorav** [comment]
No, it's the second error I put before. Let me put the full stack here:

> Error: attempt to index a function value
> stack traceback:
>   ...ram Files/ZeroBrane Studio/lualibs/mobdebug/mobdebug.lua:1057: in function 'mobdebug.connect'
>         ...ram Files/ZeroBrane Studio/lualibs/mobdebug/mobdebug.lua:1082: in function 'mobdebug.start'
>         C:/Users/redor/Desktop/premake-core/debug.lua:30: in main chunk
>         [C]: in ?
>         [C]: in function 'dofile'
>         C:/Users/redor/Desktop/premake-core/premake5.lua:1: in main chunk
>         [C]: in ?
>         [C]: in function 'dofile'
>         C:/Users/redor/Desktop/premake-core/src/_premake_main.lua:197: in field '?'
>         ...sers/redor/Desktop/premake-core/src/base/_foundation.lua:111: in function 'premake.callArray'
>         C:/Users/redor/Desktop/premake-core/src/_premake_main.lua:376: in function '_premake_main'

**Comment by pkulchenko** [comment]
Ignore mobdebug for now; just run the script as is and `print` the values returned by `socket.tcp()` call.

**Comment by redorav** [comment]
Sorry, my bad, I put the wrong error. The result is the same, but let me print it out anyway.

> Error: attempt to index a function value
> stack traceback:
>         C:/Users/redor/Desktop/premake-core/debug.lua:25: in main chunk
>         [C]: in ?
>         [C]: in function 'dofile'
>         C:/Users/redor/Desktop/premake-core/premake5.lua:1: in main chunk
>         [C]: in ?
>         [C]: in function 'dofile'
>         C:/Users/redor/Desktop/premake-core/src/_premake_main.lua:197: in field '?'
>         ...sers/redor/Desktop/premake-core/src/base/_foundation.lua:111: in function 'premake.callArray'
>         C:/Users/redor/Desktop/premake-core/src/_premake_main.lua:376: in function '_premake_main'

**Comment by pkulchenko** [comment]
So, what's in debug.lua on line 25?

**Comment by redorav** [comment]
Just a call to socket.tcp()

**Comment by pkulchenko** [comment]
I'm confused; I thought we were trying to make the 5-line script to work; it has socket.tcp() call on line 5, right? Or if it's not a complete script, can you show the entire script? Also, try to run that 5-line script to see if it works.

I don't see where this error would be thrown and socket.tcp() call should go right to the C code, so I wouldn't expect to see a Lua error there.

What happens with other socket methods, like `settimeout()`? can they be called?

**Comment by redorav** [comment]
I apologize if I'm not being too clear, it's the call to socket.tcp() that fails, even though it's recognized as a function. The last error message I printed is just those 5 lines trying to run (because the program doesn't go any further)

After looking for function settimeout in the C code, I've realized I think I've not bound the correct C function at all: it seems like I've bound a module with the tcp_open function to the tcp function. Upon further inspection, tcp_open adds the tcp function to the table. So I think all I need to figure out now is how to register these modules?

**Comment by redorav** [comment]
Right, @pkulchenko sorry about all the questions but I really appreciate your help. I've realized that I was pushing the luaopen_socket_core into the global functions table, but I don't think it was doing what I was expecting when calling require("socket")

If instead I call requiref at the start of the program like the following:

```lua
luaL_requiref(L, "socket", luaopen_socket_core, 1);
lua_pop(L, 1);
```

then the subsequent call in mobdebug to load the library does actually load the necessary functions such as tcp and settimeout and succeeds. I know have a

> Could not connect to localhost:8172: connection refused

so I think I'm now in a better position to investigate a bit further. Thank you very much for your assistance!

**Comment by redorav** [comment]
Oh and I'm debugging premake now with ZeroBrane!! Thanks a lot, I really couldn't have gone this far without your help. Feel free to close this now if you want.

**Comment by pkulchenko** [comment]
Great! So, you were able to link it statically and just start debugging (which would load the socket module)?

`Could not connect to localhost:8172: connection refused` error usually means that the debugger server is not started in the IDE. Just use `Project | Start Debugger Server` (which you probably already figured by now).

Do you mind posting your C code in case someone runs into the same issue? I'll close the ticket, but will update when I hear any additional information on this.

**Comment by pkulchenko** [comment]
Sounds good; just make it available as a plugin, so it can be put in the repository. The docs: https://studio.zerobrane.com/doc-plugin#registering-an-interpreter.

**Comment by redorav** [comment]
> Sounds good; just make it available as a plugin, so it can be put in the repository
Will do. I'll let you know as soon as I have it
