### ISSUE TITLE
Markdown syntax highlight: how to change color of code block?

### ISSUE THREAD

**Issue by d9k** [pkulchenko/ZeroBraneStudio#891]
Hello! I use dark theme (TomorrowNight).
When I open markdown file the code block text color is `#000000`. It's totally unreadable on the dark background. How to change code block text color?

See screenshot:

![screenshot from 2018-03-11 03-59-45](https://user-images.githubusercontent.com/7331988/37248338-e987dec0-24e0-11e8-963d-5a33c8970c4a.png)

My `~/.zbstudio/user.lua`:

```
styles = loadfile('cfg/tomorrow.lua')('TomorrowNight')
stylesoutshell = styles -- apply the same scheme to Output/Console windows
styles.auxwindow = styles.text -- apply text colors to auxiliary windows
styles.calltip = styles.text -- apply text colors to tooltips

editor.fontsize = 12 -- this is mapped to ide.config.editor.fontsize
editor.fontname = "Terminus (TTF)"
```

My OS is Linux Mint 18.3 Sylvia, cinnamon shell, dark theme.
ZeroBraneStudio 1.70

No similar problems with highlighting when I open `.lua` files in zbstudio.

**Comment by pkulchenko** [comment]
I'll have to check how exactly this is styled. I see some other issues with .md styling (for example, with links), so this may be related.

**Comment by pkulchenko** [comment]
@d9k, this doesn't answer your question directly, but it should fix the issue of having the text hidden or improperly styled. There was a style conflict, which led to that result.

Ideally, there would be a mechanism to style custom styles that may be unique to specific lexers (like markdown), but it's not available at the moment. I'll have to think of how to better implement this.

**Comment by d9k** [comment]
@pkulchenko, I've add patch from https://github.com/pkulchenko/ZeroBraneStudio/commit/be69f0a649cc505e16fbe1d50a2bbeb6920510ff and markdown files lost highlighting:

![Uploading Screenshot from 2018-03-13 02-58-18.png…]()

**Comment by pkulchenko** [comment]
Right, that's expected. It's because the markdown styles are unique and don't overlap with anything else, so any styling for them needs to be done individually. That's the mechanism that needs to be implemented that I mentioned in my previous comment.

**Comment by d9k** [comment]
@pkulchenko, thanks for the temporary fix!
Please open a new issue (something like "custom styles for specific lexers") and mention there this one.
I'm interested in the news and I would subscribe to the new issue.
