### ISSUE TITLE
Edit/Source/Sort fails with files containing ISO strings without any notice

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#893]
If there are any none utf8 characters in the file (e.g opening a file with ISO strings), there is no possibility to sort this in ZBS.
To reproduce:
```lua

local function randtext(min,max,len)
	local result=""
	for i=1,len do
		result=result..string.char(math.random(min,max))
	end
	return result
end

local fd=assert(io.open("text-ascii.txt","w"))
for line=1,10 do
	fd:write(randtext(65,72,10),"-",randtext(65,72,4),"-",randtext(65,72,10),"\n")
end
fd:close()

local fd=assert(io.open("text-iso.txt","w"))
for line=1,10 do
	fd:write(randtext(65,72,10),"-",randtext(128,255,4),"-",randtext(65,72,10),"\n")
end
fd:close()
```
Creates two test samples
- `text-ascii.txt` can be sorted with ZBS
- `text-iso.txt` cant.

I don't really see a reason for this, would be great if it could be made possible.

But if no fix is possible, then at least a warning should be shown _"Cant sort because ...."_

**Comment by pkulchenko** [comment]
I think this is expected, as the sorting is using `table.sort`, which is not Unicode-aware, so the strings are sorted as byte arrays.

It may be possible to add `onEditorSort` event, which you can plug into to provide your own sorting (using one of the Unicode libraries for comparison).

**Comment by jjvbsag** [comment]
table.sort is **_not_** the problem. As you write, table.sort does sort by binary data. Prove:
```lua
local function randtext(min,max,len)
	local result=""
	for i=1,len do
		result=result..string.char(math.random(min,max))
	end
	return result
end

local function makeascii()
	return randtext(65,72,10).."-"..randtext(65,72,4).."-"..randtext(65,72,10)
end
local function makeiso()
	return randtext(65,72,10).."-"..randtext(128,255,4).."-"..randtext(65,72,10)
end
	
local function test(func)
	local values={}
	for i=1,10 do
		values[i]=func()
	end
	print("==== unsorted ====")
	print(table.concat(values,"\n"))
	table.sort(values)
	print("==== sorted ====")
	print(table.concat(values,"\n"))
end

test(makeascii)
test(makeiso)
```
Output (copied from command line, because ZBS denies to copy from output window
```
==== unsorted ====
GDGGHBCGCE-DFCE-HHFFBEABBG
BDBAHBEGEC-FEDH-CGEGDHCCGH
AHEABFHCAA-DABH-HGCEDGEFEA
DHHFCFFCFB-DHGC-BHCFHEFGDH
DGFHDBHHBH-FDEC-GCDBBCEDBH
ABDGHHFDFC-CBEB-BFBGBFAHAE
BBGFFHFGAB-EAAB-DGEGABHBHB
HAGAAHEBBD-HGCE-EDFAEGCHEH
FFAFGHGGHF-HHFD-BGHAFBFBFC
CBAFBFEHCE-FADE-HDCGDACEGB
==== sorted ====
ABDGHHFDFC-CBEB-BFBGBFAHAE
AHEABFHCAA-DABH-HGCEDGEFEA
BBGFFHFGAB-EAAB-DGEGABHBHB
BDBAHBEGEC-FEDH-CGEGDHCCGH
CBAFBFEHCE-FADE-HDCGDACEGB
DGFHDBHHBH-FDEC-GCDBBCEDBH
DHHFCFFCFB-DHGC-BHCFHEFGDH
FFAFGHGGHF-HHFD-BGHAFBFBFC
GDGGHBCGCE-DFCE-HHFFBEABBG
HAGAAHEBBD-HGCE-EDFAEGCHEH
==== unsorted ====
FDDCFBEADF-�Ѭ�-EFFCFBHFFC
EACHFAACEE-դ��-CBHAGCBDHH
GFAFDGHHGB-�Ʀ�-HGDEBCGDDG
DCBFFBEDGF-���BCCHHEGGDC
DFECBAAFCC-����-ECFGDBHFEB
EDGDBCFFHC-򑴀-GGCAGFADHF
BDGAADCFGB-����-FDAEEEECCH
DBEEEEBGAA-����-GCCHCGFACG
FGCBBEAFGF-����-BDEBEADDCF
CFEHFGFCFA-����-EDCFGFBAAF
==== sorted ====
BDGAADCFGB-����-FDAEEEECCH
CFEHFGFCFA-����-EDCFGFBAAF
DBEEEEBGAA-����-GCCHCGFACG
DCBFFBEDGF-���BCCHHEGGDC
DFECBAAFCC-����-ECFGDBHFEB
EACHFAACEE-դ��-CBHAGCBDHH
EDGDBCFFHC-򑴀-GGCAGFADHF
FDDCFBEADF-�Ѭ�-EFFCFBHFFC
FGCBBEAFGF-����-BDEBEADDCF
GFAFDGHHGB-�Ʀ�-HGDEBCGDDG
```

But then comes my question again: If table.sort **_does_** sort, why does ZBS not???

**Comment by moteus** [comment]
May be because of zbs expect file in utf8 encoding ?

**Comment by pkulchenko** [comment]
I think it's related to `ReplaceTarget` method not having `Raw` counterpart, which deals with Unicode characters; I'll have to look at it.

> because ZBS denies to copy from output window

Why does it deny copying from the Output window? It should be copied in a normal way (as it does everywhere in the editor).

**Comment by pkulchenko** [comment]
I expect this patch to fix it; I added a workaround, but it was indeed related to ReplaceTarget not having Raw equivalent.

```diff
diff --git a/src/editor/menu_edit.lua b/src/editor/menu_edit.lua
index ceb95174..da6a6689 100644
--- a/src/editor/menu_edit.lua
+++ b/src/editor/menu_edit.lua
@@ -271,12 +271,12 @@ frame:Connect(ID_COMMENT, wx.wxEVT_COMMAND_MENU_SELECTED,
   end)
 
 local function processSelection(editor, func)
-  local text = editor:GetSelectedText()
+  local text = editor:GetSelectedTextDyn()
   local line = editor:GetCurrentLine()
   local posinline = editor:GetCurrentPos() - editor:PositionFromLine(line)
   if #text == 0 then
     editor:SelectAll()
-    text = editor:GetSelectedText()
+    text = editor:GetSelectedTextDyn()
   end
   local wholeline = text:find("\n$")
   local buf = {}
@@ -305,11 +305,11 @@ local function processSelection(editor, func)
         for line = #buf, 1, -1 do
           editor:SetTargetStart(line == 1 and ssel or editor:PositionFromLine(sline+line-1))
           editor:SetTargetEnd(line == eline-sline+1 and esel or editor:GetLineEndPosition(sline+line-1))
-          editor:ReplaceTarget((buf[line]:gsub("\r?\n$", "")))
+          editor:ReplaceTargetDyn((buf[line]:gsub("\r?\n$", "")))
         end
       else
         editor:TargetFromSelection()
-        editor:ReplaceTarget(newtext)
+        editor:ReplaceTargetDyn(newtext)
       end
       editor:EndUndoAction()
     end
diff --git a/src/editor/package.lua b/src/editor/package.lua
index bf06559d..c5e1793f 100644
--- a/src/editor/package.lua
+++ b/src/editor/package.lua
@@ -443,7 +443,9 @@ function ide:ReportError(msg)
 end
 
 local rawMethods = {"AddTextDyn", "InsertTextDyn", "AppendTextDyn", "SetTextDyn",
-  "GetTextDyn", "GetLineDyn", "GetSelectedTextDyn", "GetTextRangeDyn"}
+  "GetTextDyn", "GetLineDyn", "GetSelectedTextDyn", "GetTextRangeDyn",
+  "ReplaceTargetDyn", -- this method is not available in wxlua 3.1, so it's simulated
+}
 local useraw = nil
 
 local invalidUTF8, invalidLength
@@ -461,6 +463,13 @@ function ide:CreateStyledTextCtrl(...)
     end
   end
 
+  if not editor.ReplaceTargetRaw then
+    editor.ReplaceTargetRaw = function(self, ...)
+      self:ReplaceTarget("")
+      self:InsertTextDyn(self:GetTargetStart(), ...)
+    end
+  end
+
   -- map all `GetTextDyn` to `GetText` or `GetTextRaw` if `*Raw` methods are present
   editor.useraw = useraw
   for _, m in ipairs(rawMethods) do
```

Let me know if it works for you.

**Comment by jjvbsag** [comment]
Confirm! The patch does fix the problem.

**Comment by jjvbsag** [comment]
>> because ZBS denies to copy from output window

>Why does it deny copying from the Output window? It should be copied in a normal way (as it does everywhere in the editor).

Yes it should, but it doesn't. Please try to run my second script from inside ZBS and then try to copy the text from the output window. There will be nothing, you can paste anywhere from the clipboard (at least on linux).

I assume, the wx-controls have trouble with the none-utf8-conform content here too. If you want me to, I can open a separate issue for this.

**Comment by pkulchenko** [comment]
ok; thank you for confirming.

> Please try to run my second script from inside ZBS and then try to copy the text from the output window. There will be nothing, you can paste anywhere from the clipboard (at least on linux).

Works for me on Win8. What platform are you on?

> I assume, the wx-controls have trouble with the none-utf8-conform content here too. If you want me to, I can open a separate issue for this.

That's correct. Most of the controls (like search boxes) don't accept anything unicode invalid, only the editor tabs (and Output/Console) can deal with it to some degree. There is no need to open a ticket, as it's unlikely to get fixes, as it's by design (not working with invalid unicode).
