### ISSUE TITLE
Temporarily hihglight file

### ISSUE THREAD

**Issue by d9k** [pkulchenko/ZeroBraneStudio#894]
Many IDEs have ability in their main menu to temporarily choose lexer for currently choosen document tab.
It's useful feature when some file have no proper extension (for example cli entry point scripts: like https://github.com/sailorproject/sailor/blob/master/sailor).

How can I manually choose lexer for currenty displayed file in zbstudio?

**Comment by pkulchenko** [comment]
Hm, how exactly is this selection done? Do you have a snapshot/example? The IDE supports 110+ formats, so the dropdown menu doesn't seem to be very practical ;).

**Comment by pkulchenko** [comment]
The current method is to run `ide:GetEditor():SetupKeywords(ext)` in the console; for example, `ide:GetEditor():SetupKeywords("lua")` will set the current file to use the same style/keywords as the "lua" file.

**Comment by d9k** [comment]
@pkulchenko,

> `ide:GetEditor():SetupKeywords("lua")`

- it works! Thanks, this solution suits my case well because I don't need this functional very often.

> the dropdown menu doesn't seem to be very practical

I agree. Maybe dialog window with autocomplete field for lexer would be more helpful.

**Comment by pkulchenko** [comment]
Sounds good; If you need to use it regularly, you can add several menu items for specific formats you need and then switch to them as needed.

**Comment by d9k** [comment]
@pkulchenko, I added

```
(...).colorize = function (lexer_name)
  lexer_name = lexer_name or 'lua'
  ide:GetEditor():SetupKeywords(lexer_name)
end
```

function at the end of  `~/.zbstudio/user.lua` to call it from ide console (as `colorize()`) and I'm happy with this solution.

Thanks for help at the `irc://irc.freenode.net:6697/channel?zerobrane`!

**Comment by pkulchenko** [comment]
@d9k, thank you for the update. Just to follow-up on this: if you have `package {}` in front of `(...).colorize`, it's parsed as `package({}(...))` first, so it looks like a function call on a table. Either add parenthesis (`package({......})`), insert `;` after `package` call, or wrap one of the expressions in `do..end`.
