### ISSUE TITLE
Provide raspberry pi builds (ARMv7)

### ISSUE THREAD

**Issue by RamiLego4Game** [pkulchenko/ZeroBraneStudio#895]
Hello, is it possible to provide ARMv7 builds for the raspberry pi ( 3B )? It would be a very nice thing !

I've tried to install the standard linux build, but it fails to run, because of the pre-compiled lua libraries.

I'll try to build ZBS on my pi, and will provide the results, it's still nice to have ready baked version for it :)

**Comment by pkulchenko** [comment]
I don't plan to provide ARMv7 builds for now (as I don't even have rpi3B), but it shouldn't be too difficult to compile the binaries using the build scripts that come with the IDE. See #599 for details on earlier work on this.
