### ISSUE TITLE
Complex numbers get parsed with FFI

### ISSUE THREAD

**Issue by dvdvideo1234** [pkulchenko/ZeroBraneStudio#896]
Consider this code
```lua
print(pcall(function() return (4+6i) end))
print(pcall(function() return (4i+6i) end))

local a = 4i

print(type(a))
print(getmetatable(a))
```

Why does ZeroBrane parses 4i and 6i to a complex, but I cannot add them to each other ?

```
false	...myprograms\test-me\main.lua:1: attempt to perform arithmetic on 'number' and 'complex'
false	...myprograms\test-me\main.lua:2: attempt to perform arithmetic on 'complex' and 'complex'
cdata
ffi
```

**Comment by pkulchenko** [comment]
That's a limitation of the LuaJIT implementation; according to the [docs](http://luajit.org/ext_ffi_semantics.html), it's not available:

> Other missing features:
>   Arithmetic for complex numbers.

So the numbers are parsed, but if you want the arithmetic on them, you need to implement it yourself.
