### ISSUE TITLE
"debug.traceback" in  mobdebug.lua  depends on "print"

### ISSUE THREAD

**Issue by nneesshh** [pkulchenko/ZeroBraneStudio#898]
when user redefined "print" function, then "debug.traceback('xxx', 2)" will return nil, it is confused.
so maybe "debug.traceback()" always return something is a good idea.

**Comment by pkulchenko** [comment]
@nneesshh, can you provide a more complete example? Does `print` function not exist at all or does it do something different from the default? Are you using Lua 5.1?

**Comment by nneesshh** [comment]
Hi @pkulchenko, it is not a serious problem, but just confused. Here is the situation: In an exist project, set "print = function() end" when DEBUG == 0, just print nothing except dump traceback info to a file. In this situation, debug.trackback() can output normaly, but debug.traceback('xxx', 2) return nil

**Comment by nneesshh** [comment]
ps: I am using lua5.1, zbs is ZeroBraneStudioEduPack-1.70-win32

**Comment by pkulchenko** [comment]
I see this happening, but there is not much to be done, short of disabling the handler completely. If the `print` output is not suppressed, then the default case will see double results returned/printed.

I think the simplest way to address this for you is to save the traceback function and reset it after `start`:

```lua
local tb = debug.traceback
require('mobdebug').start()
debug.traceback = tb
```

Another option is to move your `print` update before starting the debugging (or move debugging start after the `print` update), as the comparison is done with the value captured when `mobdebug` is loaded.
