### ISSUE TITLE
“Mapped remote request” doesn't work?

### ISSUE THREAD

**Issue by nneesshh** [pkulchenko/ZeroBraneStudio#899]
My project is just a simple test -- "d:\client\zbslua" is my base directory contains lua.exe and "d:\client\zbslua\src" is my code directory contains lua, see below

d:\client\zbslua
│  lua.exe
│  lua51.dll
│  zbs.debug - main.bat
│  zbs.debug - test_remote_debug.bat
│
└─src
        main.lua
        test_remote_debug.lua

----------------
1、when I set "d:\client\zbslua" as project directory, the debug works ok.
2、when I open "main.lua" and select "Set project directory from current file" through ZBS menu button, the project directory change to "d:\client\zbslua\src" now.
3、after step 2, the debug stop working, and it only prompt:"Debugging suspended at 'src/main.lua:3' (couldn't activate the file).". IT DOES NOT prompt “Mapped remote request”

4、if I replace "main.lua" with "test_remote_debug.lua" and repeat step2, the debug will still NOT working, bug it will prompt "Mapped remote request for 'src/' to 'D:\client\zbslua\src\'."

So I wonder: 
    a) why "main.lua" is not prompted as "test_remote_debug.lua", is "main.lua" a magic file?
    b) why “Mapped remote request” is prompted but the debug is still NOT woring? How can I make it works?

**Comment by nneesshh** [comment]
YES, @pkulchenko, thansk for you great works.
 I just curious about that why the "main.lua" is not treated as common file(behavior is not same for one file if it named "main.lua" or others, it is really should response same output), and “Mapped remote request” is prompted, but it doesn't help the debugging, maybe I DONE something wrong?

**Comment by pkulchenko** [comment]
@nneesshh, I tried both scenarios and in both cases I get the message `Mapped remote request`; the message is shown because the project directory is set to `src/` folder, but you open the file from its parent folder as `src/main.lua`. If you launch the Lua interpreter from the src folder or set the project directory to `zbslua/` folder, everything will work and you won't see this message.

Even when you see the message, it should still work, as the message is a warning about a mismatch between the path received and the local project directory that has been successfully resolved.

**Comment by nneesshh** [comment]
I final figure out the problem:
In file "editor/debugger.lua" line 773
"if not activated and (not wx.wxFileName(file):FileExists()
                                or wx.wxIsAbsolutePath(file)) then
            if debugger:mapRemotePath(basedir, file, line, activate.NOREPORT) then
              activated = true
            end
          end
"
"wx.wxFileName(file):FileExists()" for "src/main.lua" is always true because the CWD is zbs path, and "src/main.lua" exists in zbs path, So it will not prompt “Mapped remote request”.

So maybe "wx.wxFileName(file):FileExists()" use the full path is a good idea

**Comment by pkulchenko** [comment]
> "wx.wxFileName(file):FileExists()" for "src/main.lua" is always true because the CWD is zbs path, and "src/main.lua" exists in zbs path, So it will not prompt “Mapped remote request”.

This shouldn't happen assuming you set the project directory pointing to the location of your project files (and not the IDE files). I think it should work as expected if the project directory is set for your project.
