### ISSUE TITLE
error loading module 'socket.core'

### ISSUE THREAD

**Issue by AlexK-IL** [pkulchenko/ZeroBraneStudio#902]
I followed your [tutorial here](http://notebook.kulchenko.com/zerobrane/debugging-openresty-nginx-lua-scripts-with-zerobrane-studio) and I get an error on `require('mobdebug')`:
```
error loading module 'socket.core' from file '/usr/local/ZBS/bin/linux/x64/clibs/socket/core.so':
    Error relocationg /usr/local/ZBS/bin/linux/x64/clibs/socket/core.so: __longjmp_chk: symbol not found
```
I am using the [alpine docker image of open resty](https://github.com/openresty/docker-openresty).  
How can it be fixed?  
Thanks in advance.

**Comment by pkulchenko** [comment]
@AlexK-IL, have you tried with luasocket that comes with openresty? I don't have anything else to suggest at the moment.

**Comment by pkulchenko** [comment]
@AlexK-IL, did you find a problem that was causing the error?

**Comment by ak-il** [comment]
I'm sorry I have not. I have moved on since then so I don't need it anymore but thank you for trying to help.
