### ISSUE TITLE
Messed up user config file

### ISSUE THREAD

**Issue by imbadforya** [pkulchenko/ZeroBraneStudio#904]
Hi, I messed up the user config lua file you can access from the menu and Zerobrane won't launch anymore.  ("Uncaught lua script exception" error).

Uninstall/reinstall doesn't change anything.
Seems like Zerobrane saved the screwed up user config info out of its install folder somewhere (so it survived the uninstall/reinstall) but can't figure where.

Another option would be to lauch Zerobrane in command line and pass it some parameter to tell it to ignore user config but I can't find how to do that either.

 What can I do ?

**Comment by pkulchenko** [comment]
You can remove that file, but I'd be interested to look at it to see why exactly it fails and what the error is. See this FAQ entry for information on removing the ini file that keeps this configuration: https://studio.zerobrane.com/doc-faq#how-do-i-restore-default-configuration-for-recent-files-projects-and-editor-tabs. You can email the file to the support email address at the footer of the FAQ page.
