### ISSUE TITLE
Watch/Stack windows are not visible in Windows Remote Desktop Connection

### ISSUE THREAD

**Issue by 0xD1E60** [pkulchenko/ZeroBraneStudio#906]
1. Use Windows Remote Desktop Connection to login to a remote Windows 10 machine
2. Open up ZBStudio (latest)
3. Open watch/stack windows (the windows are not rendered!)

**Comment by pkulchenko** [comment]
@0xD1E60, not sure what happens, but it's possible that remote desktop only displays the main window, which will make stack/watch to not show. You can still dock the windows (for example, to the bottom panel), which will make them visible. Here are the details on docking: https://studio.zerobrane.com/doc-tips-and-tricks#merge-and-split-windows-and-tabs.
