### ISSUE TITLE
feature request: hide mouse pointer

### ISSUE THREAD

**Issue by sircola** [pkulchenko/ZeroBraneStudio#908]
Please add an option to be able to hide mouse pointer while typing. Ty.

**Comment by pkulchenko** [comment]
@sircola, how do you see it working? I can probably hide mouse on every click and then show after Xms pass, but not sure if that's what would be expected in this case. Also pressing Ctrl and Alt will hide the pointer in this case, which is probably not what you want if you want to do some mouse selection. It also need to be shown on mouse movement.

I'm curios, what's the reasoning for it?

**Comment by pkulchenko** [comment]
Here is an experiment on how it may look like:

```diff
diff --git a/src/editor/package.lua b/src/editor/package.lua
index c5885dff..58371c17 100644
--- a/src/editor/package.lua
+++ b/src/editor/package.lua
@@ -683,10 +683,15 @@ function ide:CreateStyledTextCtrl(...)
 
   function editor:SetupKeywords(...) return SetupKeywords(self, ...) end
 
+  editor:Connect(wx.wxEVT_MOTION, function(event)
+      editor:SetSTCCursor(0)
+      editor:SetSTCCursor(-1)
+    end)
   editor:Connect(wx.wxEVT_KEY_DOWN,
     function (event)
       local keycode = event:GetKeyCode()
       local mod = event:GetModifiers()
+      if not mod or mod ~= wx.wxMOD_SHIFT then editor:SetCursor(wx.wxCursor(wx.wxCURSOR_BLANK)) end
       if (keycode == wx.WXK_DELETE and mod == wx.wxMOD_SHIFT)
       or (keycode == wx.WXK_INSERT and mod == wx.wxMOD_CONTROL)
       or (keycode == wx.WXK_INSERT and mod == wx.wxMOD_SHIFT) then
```

This is not a complete implementation, as it doesn't have a setting and conflicts with scratchpad processing, but it's good enough to see the effect of it. Maybe I'll wrap it into a plugin...

**Comment by sircola** [comment]
ah, very nice, ty it works.
Could you please change it so that it hides the pointer above the whole window not just the editor?

**Comment by pkulchenko** [comment]
That's unlikely, as each window handles (or may handle) its own mouse cursor separately, so hiding it in the editor is probably the easiest way to deal with it. I'll wrap it into a plugin for now.

**Comment by madmaxoft** [comment]
For Windows, hiding the mouse cursor while typing is an OS-level feature, program wouldn't need to do anything to support it. I'd be surprised if other OSs didn't have a similar setting.

**Comment by pkulchenko** [comment]
I added a plugin that implements this.
