### ISSUE TITLE
osx $PATH is not correct

### ISSUE THREAD

**Issue by stuta** [pkulchenko/ZeroBraneStudio#911]
```os.execute("echo $PATH")``` prints /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin in console. So I can't call normal command line tools when debugging.

**Comment by pkulchenko** [comment]
It's not the IDE issue, as it's the limitation of macOS. See #356 for details and the workaround.

**Comment by stuta** [comment]
Thaks, that workaround  worked well.
