### ISSUE TITLE
Strange binary files caching behavior

### ISSUE THREAD

**Issue by d9k** [pkulchenko/ZeroBraneStudio#912]
OS: Linux Mint 18.3 Sylvia (basically, Ubuntu 16.04)

Tried openning local copy of file
https://github.com/golgote/neturl/blob/master/tests/query_test.lua
with ZeroBraneStudio, got "binary file is shown as read-only as it is only partially loaded" warning at console.

I edited file with external editor, restarted ZeroBraneStudio and... there was PREVIOUS version of file loaded! How can this even be possible?.. Do ZBS use files cache?

Fixed binary warning by editing https://github.com/golgote/neturl/blob/master/tests/query_test.lua#L80: replaced `[NUL][NUL][NUL]` in string with `string.char(0):rep(3)`.
But still stunned by unexplainable file caching...

I think if ZBS uses file caching for binary files it must be reset after binary file external edit (or after IDE restart, at least).

**Comment by pkulchenko** [comment]
Closing as I expect this to be fixed by #1012 that changes the handling of binary files.
