### ISSUE TITLE
Need to reset Window Layouts (outputclone.lua)

### ISSUE THREAD

**Issue by bluetardis** [pkulchenko/ZeroBraneStudio#913]
Have changed my layout and I can no longer see the outputwindow clone.
Its the latest version of the package and zbstudio
It shows up in Expose and I suspect its there but has done something odd with the sizing.

I have tried deleting and reinstalling everything however there must be a local cache as it remembers recent files and screen layouts.

How can I resolve this - I suspect the easiest way is to reset the cache but alternatively if I can create a "minimum" sized output window that would also help...

**Comment by pkulchenko** [comment]
You have two options: (1) selecting `View | Default Layout` should restore the default layout (see [FAQ item](https://studio.zerobrane.com/doc-faq#how-do-i-restore-default-configuration-for-ui-elements)), although it may not affect the layout of panels added by plugins and (2) [restore default configuration](https://studio.zerobrane.com/doc-faq#how-do-i-restore-default-configuration-for-recent-files-projects-and-editor-tabs) for projects and tabs. One of these two options should work.

**Comment by bluetardis** [comment]
Thanks Paul - Option 2) restore default configuration
<https://studio.zerobrane.com/doc-faq#how-do-i-restore-default-configuration-for-recent-files-projects-and-editor-tabs>
did
the trick.


PB

Peter Bishop
------------------------------------------
peter@bluetardis.com.au
+61-(0)412-27-2793
