### ISSUE TITLE
<!DOCTYPE html> disappearing in .html and .xml files

### ISSUE THREAD

**Issue by max1220** [pkulchenko/ZeroBraneStudio#915]
I'm running ZeroBrane Studio 1.70 on debian stable(Installed via the release archive).
I noticed that I couldn't write the <!DOCTYPE html> required for modern HTML pages in the editor:
After the last character, '>' the text just disappeared. When saving the file, and checking it's contents with cat from the terminal the <!DOCTYPE html> is there. Opening an html file has the same issue.
Writing the same string in a Lua file works as expected, but writing to a .xml file seems to trigger a similar bug; everything but the last '>' disappears.

**Comment by pkulchenko** [comment]
@max1220, thank you for the report. Could you provide the shortest example I can test this with?

**Comment by max1220** [comment]
Sure.
Minimum steps to reproduce:
* Open Zerobrane, Create an empty document
* Enter the following string without parenthesis: "<!DOCTYPE html>"
* Save file as .html
Expected behavior:
The content of the editor does not change by saving the file with an ,.html extension.
Actual behavior:
The entered text just disappears.

**Comment by pkulchenko** [comment]
It seems like the string didn't come through ;)

**Comment by max1220** [comment]
Yes, I just noticed that github seems to hide it as well :O
The string is
"<!" "DOCTYPE" "html>"
concatinated without parenthesis.

**Comment by pkulchenko** [comment]
Strange; I don't have access to debian, but I tried on a different system and don't see the text disappearing. Is it just the DOCTYPE element that disappears?

I see that it's styled as a comment and there was a style conflict that made some of the styles disappear, but it's supposed to be fixed before 1.70 release. Could you check if the comments disappear as well (as they use the same style) and if this also happens on the current master version (you can grab it from the repository)?

**Comment by madmaxoft** [comment]
(You can use backticks (ascii code 96) to make GitHub show the string properly: `<!DOCTYPE html>` )

**Comment by max1220** [comment]
I cloned the repo and tried this in master. Seems to work normally.
I'll test this on my other debian machine and my windows setup now, but this seems to be resolved already.

**Comment by pkulchenko** [comment]
@max1220, sounds good; thanks for the update. I'd expect this to be fixed in b46a5856, but maybe it was a slightly different issue that was fixed in be69f0a6, as the former would already be included in 1.70. If so, could be related to #891.

**Comment by max1220** [comment]
I don't think this is just a color/style issue.
I can't select the text, the cursor is placed like there is not text at all.
I made a small screen recording:
https://www.youtube.com/watch?v=pKpqUZNbqA4

**Comment by pkulchenko** [comment]
@max1220, thanks for the recording, but I think it was still the style issue. It's just there are some styles for comments that hide text and would have a very similar effect to what you are showing.

For example, type `something -- [more](less)` into a .lua file and you'll see `more` to become a link and `less` to completely disappear along with brackets. I think there was a style conflict that caused some of the existing markup styles to be applied in cases where they were not supposed to be applied. In the case in #891 it made the text color to be the same as the background, but in your case it made the comments invisible.
