### ISSUE TITLE
Suggetion - Start debug then run directly until break point

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#918]
Currently, start debug will begin step at the first line.
I think this is not necessary, because user could put break point at first line if they need.
As the title said, maybe 'Start debug then run directly until break point' is more handy.

**Comment by pkulchenko** [comment]
@robertlzj, yes, it's available if you set `debugger.runonstart=true`. You'll need to set a breakpoint to stop the application where you want. See https://studio.zerobrane.com/doc-general-preferences#debugger
