### ISSUE TITLE
Stepping "captures" values to prevent them from being garbage collected

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#919]
Sorry, I didn't extract any demo yet (a little hard..). Only some fragment bellow. The actual references is complex than this.
`new table A → new table B`, which B strong reference A, the expect GC order is first B then A.
But if set the breakpoint somewhere and debug with _step over_ / _run_ (not use _step into_, although will not step into any function except `__gc`), then the GC order became first A then B, also other GC order changed a little randomly.
A little more detailed:
``` lua
B=nil; collectgarbage("collect")
--If not break here, then B will GC correctly, then GC A bellow.
--But if break here and use step over / run, then B will not GC until the very very  end after A.
A=nil; collectgarbage("collect")
```

This would cause issue in user resource release.
Eh.. is these information enough? Or I have to find a demo..

**Comment by pkulchenko** [comment]
Yes, I'd like to see a simple demo script, as I don't quite follow as to what the issue is and what error will happen.

**Comment by robertlzj** [comment]
I can't believe the demo is so independent of my work flow, and so short...
```lua
local A=setmetatable({},{__gc=function() print'gc.' end})
A=nil;collectgarbage("collect")  --set breakpoint here
print'done.'
```
Normal order without breakpoint is `gc-done`, otherwise is `done-gc`!

**Comment by robertlzj** [comment]
```lua
local isInScope=true
local A=setmetatable({},{__gc=function()
		print'gc.'
		assert(isInScope,"This won't trigger error ?!")
	end}) --'local' is main factor!
A=nil;collectgarbage("collect")  --Set breakpoint here.
isInScope=false
print'done.'
```
Although GC happened at the end after 'done.' where `isInScope` is fasle, but won't raise assert fault?!

**Comment by pkulchenko** [comment]
```lua
local A=setmetatable({},{__gc=function() print'gc.' end}) --'local' is main factor!
A=nil;collectgarbage("collect")  --set breakpoint here, then use run/step into whatever.
print'done.'
```

I have figured out what happens in this example. The debugger (mobdebug) captures locals and upvalues before each step to (1) execute commands in the correct context and (2) restore them after the command is done. In this case `A` is "captured" and will not be garbage collected, as it's stored in the table, until the next step is executed, but it's executed after `collectgarbage` is executed, so `A` value ends up not collected until the end of the script. If you split the second line into two lines (so that `collectgarbage` is executed separately), you'll not have this issue.

Having said that, I think it's possible to "weaken" the values, so that they can still be garbage collected. try the following patch:

```diff
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index 89be1045..e95efb20 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -454,7 +454,7 @@ local function capture_vars(level, thread)
   -- including access to globals, but this causes vars[name] to fail in
   -- restore_vars on local variables or upvalues with `nil` values when
   -- 'strict' is in effect. To avoid this `rawget` is used in restore_vars.
-  setmetatable(vars, { __index = getfenv(func), __newindex = getfenv(func) })
+  setmetatable(vars, { __index = getfenv(func), __newindex = getfenv(func), __mode = "v" })
   return vars
 end
```

**Comment by Clyybber** [comment]
Will this be fixed upstream in @pkulchenko / mobdebug ?

**Comment by pkulchenko** [comment]
For sure; this was just a patch to test the changes.
