### ISSUE TITLE
In Clone view (plugin), 'Complete Identifier' won't work.

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#922]

**Comment by pkulchenko** [comment]
@robertlzj, I can't reproduce this issue; auto-complete works for me in both the original and the cloned window, so if you could provide a detailed list of steps, it may help with reproduction. Do you have any other plugins installed?

**Comment by robertlzj** [comment]
I set `acandtip.nodynwords = false` in `user.lua`, which could effect this problem here.
I test with or without package included.

**Comment by pkulchenko** [comment]
Yes, it does seem to be related to the combination of CloneView with `acandtip.nodynwords = false`; I'll check what may be going on.

**Comment by pkulchenko** [comment]
@robertlzj, I figured out the issue: when two windows have the same content, the gathered dynamic words include those that are being typed and since the list already includes the word typed, no autocomplete suggested are being offered.

I've added logic to skip gathering dynamic words from cloned windows, but this requires some changes to the plugin as well; see the following diff:

```diff
diff --git a/cloneview.lua b/cloneview.lua
index a1a906f..42bd005 100644
--- a/cloneview.lua
+++ b/cloneview.lua
@@ -3,8 +3,8 @@ return {
   name = "Clone view",
   description = "Clones the current editor tab.",
   author = "Paul Kulchenko",
-  version = 0.17,
-  dependencies = "1.60",
+  version = 0.18,
+  dependencies = "1.71",
 
   -- release document pointer for closed tabs
   -- remove from the list of clones (in either direction) this closed editor
@@ -13,6 +13,9 @@ return {
 
     if clones[editor].pointer then
       clones[editor].editor:ReleaseDocument(clones[editor].pointer)
+    else
+      -- closing the "source" editor of the close; restore dynamic words
+      clones[editor].editor:UseDynamicWords(editor:UseDynamicWords())
     end
     -- remove the editor this one clones from the list of clones
     clones[clones[editor].editor] = nil
@@ -45,6 +48,7 @@ return {
       clones[e2] = {editor = e1, pointer = docpointer}
       clones[e1] = {editor = e2}
       e2:SetDocPointer(docpointer)
+      e2:UseDynamicWords(false)
       ide:GetEditorNotebook():Split(notebook:GetSelection(),
         event:GetId() == idhorz and wx.wxRIGHT or wx.wxBOTTOM)
       notebook:SetSelection(index)
```

These changes will be applied after the next release is out.
