### ISSUE TITLE
Suggestion. Record and replay route of function call stack for debug purpose.

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#926]
Sometimes in debug, I will make a little change which won't effect code execute path (said function invoked procedure) much.
But, to **redo** the debug to the target position may be tediously long.
So, could **record** and **replay** the path as long as it can.

I think the **path** could refer stack, like:

> h(..) at line xxx  <--
> g(..) at line xxx
> f(..) at line xxx

Go a step further, could **rollback** the code to lower stack frame like `g(..)` above, make change, then continue from the changed position, even goes to other branch than `h(..)`.
It's a deeply embed record and replay support, like **scratchpad** works on stack frame?

**Comment by pkulchenko** [comment]
This is interesting suggestion, but difficult to implement and probably won't work the way you expect. I've been looking into something similar (record and replay debuggers), but this is not something I have plans to tackle on right now. This shouldn't stop you from giving it a try if you want to though.
