### ISSUE TITLE
Can't count Cos or Sin if it is equals 0

### ISSUE THREAD

**Issue by AlexN1ght** [pkulchenko/ZeroBraneStudio#928]
**Run**: 
`math.cos(math.pi*0.5)`
will get:
6.1230317691118863e-017

**The same story with **
`math.cos(math.pi*1.5)`
will get:
-1.8369095307335659e-016

And so on...
`math.cos(math.rad(270))`
will get:
-1.8369095307335659e-016

The same story with sin 
`math.sin(math.rad(180))`
will get:
1.2246063538223773e-016

What do I do Wrong? (ZeroBrane Studio 1.70)

**Comment by pkulchenko** [comment]
Why do you think you do something wrong? This is the same answer I get from stock Lua interpreters (I checked Lua 5.1-5.3).

**Comment by AlexN1ght** [comment]
Because cos of 270 equals 0, not this! This is mean that 
(math.cos(math.rad(270) == 0) is false. Is this a bug or what? Or, at least, how can I compare thees values?

**Comment by madmaxoft** [comment]
Most likely a precision problem.
https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems

**Comment by AlexN1ght** [comment]
Thanks a lot. It IS this, but is kind of frustrating._.

**Comment by pkulchenko** [comment]
@madmaxoft is right; it's because `math.pi` has limited precision, so it's not enough to get close to 0.
