### ISSUE TITLE
Outline of the cloned tab is not refreshed until edited

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#929]
![outline of clone view](https://user-images.githubusercontent.com/7419030/43175387-51d97f94-8ff1-11e8-99f9-859b2f464075.png)
The clone one can't unfold.
`cloneview.lua` version = 0.17.

**Comment by pkulchenko** [comment]
@robertlzj, this should be fixed now. You need to get the latest master branch code and the latest cloneview plugin.
