### ISSUE TITLE
Treat more extensions as Lua files?

### ISSUE THREAD

**Issue by tjakubo2** [pkulchenko/ZeroBraneStudio#931]
Is it possible to configure ZB to treat both ``.lua`` and some other arbitrary extensions as Lua files (syntax highlighting)? A few games I know have some different extensions to note it's their script files but syntax is regular Lua. It would be nice to be able to work on those directly in ZB.

Cheers!

**Comment by pkulchenko** [comment]
@tjakubo2, yes, it should be fairly simple to do; there are a couple of ways to do this. The simplest one is to associate the extension with the lua lexer using `specmap` configuration setting: `editor.specmap.foo = "lua"`. This will associate `.foo` extension with "lua" lexer and will apply syntax highlighting, auto-complete and all other lua-related settings to .foo files. I'll make sure this is reflected in the documentation.

**Comment by tjakubo2** [comment]
Holy, that's a fast response!
Thanks a lot, I looked over the docs and tried to search something like ``.lua`` in the repo but couldn't find this (still, posible that it;s there but I just missed it).

Thanks a lot!
