### ISSUE TITLE
[Request] Command line argument to immediately jump to line number for specific file

### ISSUE THREAD

**Issue by Silverlan** [pkulchenko/ZeroBraneStudio#932]
When there's a Lua error in my program, I'd like it to automatically open the Lua-file in ZeroBrane and go to the line in which the error occurred.

As far as I can tell you can't specify line numbers in the command line arguments right now, so I'd like to request this feature. :)

**Comment by pkulchenko** [comment]
> you can't specify line numbers in the command line arguments right now, so I'd like to request this feature. :)

You most definitely can: use `filename:<line>` or `filename:p<pos>` (https://github.com/pkulchenko/ZeroBraneStudio#usage) ;).
