### ISSUE TITLE
zeroBraneStudio doesn't open, mac

### ISSUE THREAD

**Issue by paulocleon** [pkulchenko/ZeroBraneStudio#939]
Mac Sierra:

The IDE was working fine, bur suddenly shut down and I couldn't open it again. I uninstalled it a pull it from github and the same continues to happen. Any idea?

P.

**Comment by pkulchenko** [comment]
Not sure what's happening. Can you try running the following commands (adjust for the location of the ZeroBrane Studio folder):

```sh
$ cd /Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio
$ export DYLD_LIBRARY_PATH=`pwd`/bin; bin/lua src/main.lua
```

It may provide some additional information on the failure to launch the application.

**Comment by paulocleon** [comment]
The first one:
(while uninstalled) No such file or directory
The 2d one:
(while uninstalled) -bash: bin/lua: No such file or directory
The first one:
(once installed) ZeroBraneStudio $
The 2d one:
(once installed):
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
bin/lua: src/editor/editor.lua:777: wxLua: Expected a 'string' or 'wxString' for parameter 2, but got a 'boolean'.
Function called: 'AutoCompSetFillUps(wxStyledTextCtrl, boolean)'
01. wxStyledTextCtrl::AutoCompSetFillUps(wxStyledTextCtrl(self), string)
stack traceback:
	[C]: in function 'AutoCompSetFillUps'
	src/editor/editor.lua:777: in function 'CreateEditor'
	src/editor/commands.lua:18: in function 'NewFile'
	src/editor/commands.lua:848: in function 'StoreRestoreProjectTabs'
	src/editor/filetree.lua:856: in function 'updateProjectDir'
	src/editor/filetree.lua:886: in function 'fntab'
	src/editor/settings.lua:231: in function 'SettingsRestoreProjectSession'
	src/main.lua:589: in main chunk
	[C]: at 0x00001c80

**Comment by paulocleon** [comment]
About the result: I recall that before the IDE crashed I was typing some commands to improve autocomplete (pasted from your page) into the user file (I wanted to improve autocomplete functions).

**Comment by pkulchenko** [comment]
@paulocleon, it looks like you might have specified `acandtip.fillups=true` instead of `acandtip.fillups=".("` or something similar. It's still strange that the application doesn't open, as it should show an error in a popup window, but removing that line from `user.lua` or fixing it should resolve the issue.

**Comment by paulocleon** [comment]
You right. I just find the file on bash shell and edited in emacs.
I could instantly launch Zero again.

Thanks for the feedback!
