### ISSUE TITLE
Indent mistake in if else

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#942]
```
	if a then b=1
	else b=2 end--press Enter to get newline here, will reduce indentation to
--else b=2 end 
```

**Comment by pkulchenko** [comment]
Yes, but the expectation is that `else` would be indented at this point, which will make the indentation correct. You can fix this indentation by using `Ctrl-I`.

**Comment by robertlzj** [comment]
The result of `else` indentation is not correct.
Updated demo:
```lua
do
	if a then b=1
	else b=2 end
end
```
Enter after `else` will reduce indentation one level less than `if`.
```lua
do
	if a then b=1
else b=2 end
end
```

**Comment by robertlzj** [comment]
Understand now. I had thought it is dynamic align.
Currently, can't use more Enters after `else`, `end`. Where sometimes may  append something after `end`, then `enter`.
If `ctrl-I` could correct this, I think auto fix the level after enter is possible?

**Comment by robertlzj** [comment]
Thanks for the prompt.
Also, I see the left margin marks all the block with match begin - end pairs.
Only fix current line of end each time is enough I think. No need to scan from first position?

**Comment by pkulchenko** [comment]
> And I didn't use ctrl-I, because there may has some customer / temporary indent. End matches (use the same indent level of) Begin seems enough.

You can apply it to a block; as you said, you can scan to the previous unindented line and start selection there, then apply `Ctrl-I` to "fix" the selection. Other combinations are possible as well.
