### ISSUE TITLE
Scratchpad consuming 100% CPU on compilation error

### ISSUE THREAD

**Issue by evg-zhabotinsky** [pkulchenko/ZeroBraneStudio#944]
Whenever code "running" in a scratchpad has an error that prevents its compilation, there is almost 100% CPU usage by zbstudio process, plus extra ~50% by system graphics stack. Stopping the scratchpad or fixing all compilation errors brings system back to near-zero load.

My guess is it's constantly trying to recompile the code, and thus constantly refreshes displayed error log.

Interpreter is set to "Lua". System is 64-bit Linux, with Lua 5.2 as default.

Could also have been the real cause of #735, not sure.

---

Also, not sure if it should be a separate issue, putting it here for now:

There seems to be no built-in functionality to restart scratchpad whenever some input data files are modified, so I wrapped my code in a loop and put `os.execute('inotifywait -qq file.txt')` in its end.

The problem is, whenever I modify code, it seems that IDE fails to kill inotifywait process, and causes ~150% CPU load, same as on compile error. Only when said process dies (if I start it with timeout, or modify the watched file, or just kill it manually) will the scratchpad be restarted.

**Comment by pkulchenko** [comment]
@evg-zhabotinsky, not sure why it's happening, as the scratchpad shouldn't be refreshed on failed compilation, but can you try the following patch:

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index e94a2688..cd8d7f62 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -1770,7 +1770,10 @@ function debugger:ScratchpadRefresh()
     and scratchpadEditor.spec.apitype == "lua"
     and not ide.interpreter.skipcompile
     and not CompileProgram(scratchpadEditor, { jumponerror = false, reportstats = false })
-    then return end
+    then
+      debugger.scratchpad.updated = false
+      return
+    end

     local code = StripShebang(scratchpadEditor:GetTextDyn())
     if debugger.scratchpad.running then
```

**Comment by pkulchenko** [comment]
> There seems to be no built-in functionality to restart scratchpad whenever some input data files are modified

That's correct, although making some innocuous change should be enough to get the script re-evaluated.

**Comment by evg-zhabotinsky** [comment]
The patch does help with compile errors, but not when debugged script refuses to die.
I looked around a bit, and it seems that `debugger.scratchpad.updated` being true causes some busy loop (which I failed to find...), which starts `ScratchpadRefresh()` over and over.

I changed the code to set `scratchpad.updated` to false after telling debugger to stop, and back to true when the thread that runs scratchpad terminates. (`debugger:handle("run")` blocks, so the thread hangs until debugger is stopped) It seems to work just fine now, with barely any CPU load.

_Note:_ The thread terminates prematurely if I pause debugger manually, but then I cannot step through code or even see where it stopped, so it seems broken anyway... Is "Pause" button even supposed to be enabled in scratchpad mode?

The changes:
```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index e94a2688..c78a2710 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -1770,19 +1770,20 @@ function debugger:ScratchpadRefresh()
     and scratchpadEditor.spec.apitype == "lua"
     and not ide.interpreter.skipcompile
     and not CompileProgram(scratchpadEditor, { jumponerror = false, reportstats = false })
-    then return end
+    then
+      debugger.scratchpad.updated = false
+      return
+    end
 
     local code = StripShebang(scratchpadEditor:GetTextDyn())
     if debugger.scratchpad.running then
       -- break the current execution first
-      -- don't try too frequently to avoid overwhelming the debugger
-      local now = ide:GetTime()
-      if now - debugger.scratchpad.running > 0.250 then
-        debugger:Break()
-        debugger.scratchpad.running = now
-      end
+      debugger:Break()
+      debugger.scratchpad.updated = false
+      ide:Print('Waiting for scratchpad to pause...')
     else
       local filePath = debuggerMakeFileName(scratchpadEditor)
+      --ide:Print('Loading "'..filePath..'" into scratchpad...')
 
       -- wrap into a function call to make "return" to work with scratchpad
       code = "(function(...)"..code.."\nend)(...)"
@@ -1821,6 +1822,7 @@ function debugger:ScratchpadRefresh()
         local prefix = extloop and TR("Scratchpad error") or TR("Compilation error")
 
         if not err then
+          --ide:Print("Scratchpad running...")
           _, _, err = debugger:handle("run")
           prefix = TR("Execution error")
         end
@@ -1835,6 +1837,8 @@ function debugger:ScratchpadRefresh()
             ..":\n"..err:gsub('stack traceback:.+', ''):gsub('\n+$', ''))
         end
         debugger.scratchpad.running = false
+        debugger.scratchpad.updated = true
+        --ide:Print('Scratchpad paused.')
       end
 
       copas.addthread(reloadScratchpadCode)
```

**Comment by evg-zhabotinsky** [comment]
As for why debugger refuses to pause immediately: A comment in `debugger:Break` that's used here says "this will only break on the next Lua command". `os.execute(cmd)` does not return from C code until the command finishes, so that has to be it.

> making some innocuous change should be enough to get the script re-evaluated

Yeah, it does. But it's way cooler to just edit the input and see watches change :P  With zero CPU load thanks to `inotifywait` and the above patch, may I add.
(I'm using runtime watches plugin, which I patched to actually parse variable values so that I can unfold tables in watches list. I had to copy half of `debugger:updateWatchesSync` to make it happen, though... `AddWatch` only sets arbitrary text value.)

**Comment by evg-zhabotinsky** [comment]
> Any idea why the script "refuses to die"?

When scratchpad is reloaded, it's only paused instead of stopped, and that can only be done when in Lua code. Maybe there is an alternative to using `debugger:Break()` for that?

> shouldn't updated value stay the same without any need to re-evaluate?

Well, a different flag could be added, but right now it seems that `scratchpad.updated` really means "Run `ScratchpadRefresh()` ASAP", so leaving it on for whatever reason causes a busy loop and high CPU usage.

Also, maybe stopping the debugger can be moved into the thread that runs code in the scratchpad? Then a flag like `scratchpad.dying` can tell that we only need to clear `updated` flag, without starting another thread.

**Comment by evg-zhabotinsky** [comment]
Turned out my patch was broken: scratchpad was restarted immediately whenever it terminated, I just didn't notice that.

<details><summary>Here is the new patch: [click]</summary>

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index e94a2688..77b577ec 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -1764,28 +1764,36 @@ end
 
 function debugger:ScratchpadRefresh()
   local debugger = self
-  if debugger.scratchpad and debugger.scratchpad.updated and not debugger.scratchpad.paused then
+  if debugger.scratchpad and debugger.scratchpad.updated
+  and not debugger.scratchpad.paused and not debugger.scratchpad.pending then
     local scratchpadEditor = debugger.scratchpad.editor
     if scratchpadEditor.spec.apitype
     and scratchpadEditor.spec.apitype == "lua"
     and not ide.interpreter.skipcompile
     and not CompileProgram(scratchpadEditor, { jumponerror = false, reportstats = false })
-    then return end
+    then
+      debugger.scratchpad.updated = false
+      return
+    end

-    local code = StripShebang(scratchpadEditor:GetTextDyn())
+    debugger.scratchpad.pending = true
+
+    local function reloadScratchpadCode()
+      local debugger = debugger
-    if debugger.scratchpad.running then
-      -- break the current execution first
-      -- don't try too frequently to avoid overwhelming the debugger
-      local now = ide:GetTime()
-      if now - debugger.scratchpad.running > 0.250 then
+      if debugger.scratchpad.running then
+        -- break the current execution first
+        ide:Print('Waiting for scratchpad to pause...')
         debugger:Break()
-        debugger.scratchpad.running = now
+        while debugger.scratchpad.running do
+          copas.sleep(.1)
+        end
       end
-    else
+      debugger.scratchpad.pending = false
+
       local filePath = debuggerMakeFileName(scratchpadEditor)
 
       -- wrap into a function call to make "return" to work with scratchpad
-      code = "(function(...)"..code.."\nend)(...)"
+      local code = "(function(...)"..StripShebang(scratchpadEditor:GetTextDyn()).."\nend)(...)"
 
       -- this is a special error message that is generated at the very end
       -- of each script to avoid exiting the (debugee) scratchpad process.
@@ -1795,8 +1803,7 @@ function debugger:ScratchpadRefresh()
       -- store if interpreter requires a special handling for external loop
       local extloop = ide.interpreter.scratchextloop
 
-      local function reloadScratchpadCode()
-        local debugger = debugger
+      do -- That's just to keep indentation for shorter diff.
         debugger.scratchpad.running = ide:GetTime()
         debugger.scratchpad.updated = false
         debugger.scratchpad.runs = (debugger.scratchpad.runs or 0) + 1
@@ -1839,6 +1846,7 @@ function debugger:ScratchpadRefresh()
 
       copas.addthread(reloadScratchpadCode)
     end
+    debugger.scratchpad.updated = false
   end
 end
 
```
</details>

Basically, I moved `debugger:Break()` and related code into the thread and block until scratchpad stops running. I also moved getting editor contents and processing them after that point.

_Note_ that `scratchpad.pending` is supposed to be a set of all scripts waiting to be restarted, I'm just not sure of what the keys should be and where to initialize the set.

Also, I'm not sure what happens if the tab is closed before the thread picks up its contents. (Nothing bad seems to happen if it's the only tab in scratchpad, and I can't find "Add to scratchpad" menu entry any more...)

**Comment by pkulchenko** [comment]
@evg-zhabotinsky, should this be closed with the changes already committed or is it still an issue? I'd prefer not to add one more flag (`pending`) if possible, but if this is still an issue, I can check for some other options.

**Comment by evg-zhabotinsky** [comment]
I guess it'll have to do. CPU load is at zero, except when edited scratchpad source compiles successfully but the scratchpad process is stuck in a C call and thus cannot be paused. Nothing can be done about that last part, I'm afraid.

As for why the scratchpad process can get stuck in a C call, it's mostly waiting for something to happen. Examples are read() on stdin / pipe / socket waiting for data, or os.execute() waiting for child to terminate. As I currently understand, things like that are out of the scope of scratchpad, since it's intended to inject code into game engine and let it be, i.e. the code should terminate rather quickly.

A couple final related suggestions (to be moved into a new issue?):
1. Add ability to re-run scratchpad only on save? As opposed to on every single edit. Should probably still compile it on every edit to show syntax errors, just not run until it's saved. Currently that can be sort-of achieved by introducing deliberate syntax errors, but that's not very convenient.
2. Add ability to "Add to Scratchpad (run other script)". Place in the context menu, next to the normal variant, and allow to choose a different script when clicked. The effect would be that the chosen script is executed whenever the file is edited. (E.g. whenever a non-Lua resource file is edited, run a Lua script that makes the engine reload that resource.) Maybe instead of / in addition to this allow running scripts on modification of arbitrary files. (I.e. when inotify triggers.)

**Comment by pkulchenko** [comment]
> I guess it'll have to do. CPU load is at zero, except when edited scratchpad source compiles successfully but the scratchpad process is stuck in a C call and thus cannot be paused. Nothing can be done about that last part, I'm afraid.

I agree; will close.


> Add ability to re-run scratchpad only on save? As opposed to on every single edit. Should probably still compile it on every edit to show syntax errors, just not run until it's saved. Currently that can be sort-of achieved by introducing deliberate syntax errors, but that's not very convenient.

This should be possible to do from a plugin, but it gets tricky, as the changes can be made in multiple editors, with only one being saved and unfortunately `debugger:ScratchpadRefresh()` only checks the last updated editor. It may need to be extended to accept the editor as a parameter and then check that editor against the list of "scratchpad-enabled" editors.

> Add ability to "Add to Scratchpad (run other script)". Place in the context menu, next to the normal variant, and allow to choose a different script when clicked. The effect would be that the chosen script is executed whenever the file is edited. (E.g. whenever a non-Lua resource file is edited, run a Lua script that makes the engine reload that resource.) Maybe instead of / in addition to this allow running scripts on modification of arbitrary files. (I.e. when inotify triggers.)

This should be possible from a plugin as well. In fact, it may be possible to have "Add to Scratchpad (on save)" option to the menu that will track Save events or monitor the file changes and refresh the scratchpad for it (assuming `debugger:ScratchpadRefresh()` is modified to take the editor or even a filename as a parameter).

Let me know if you are interested to play with it and I'll make a new branch with `debugger:ScratchpadRefresh()` changes for you to work with.
