### ISSUE TITLE
Outline incorrect when there is a repeat..until loop

### ISSUE THREAD

**Issue by theRealsteveRoll** [pkulchenko/ZeroBraneStudio#946]
When there is a repeat..until loop inside checkMoves():

![image](https://user-images.githubusercontent.com/40004112/46908280-70549400-cf29-11e8-8fcf-9044af8c59f4.png)

After the loop is removed (this is what the outline is supposed to show):

![image](https://user-images.githubusercontent.com/40004112/46908299-ab56c780-cf29-11e8-971f-e6cadc5477ad.png)

**Comment by pkulchenko** [comment]
@theRealsteveRoll, thank you for the report.

Do you have a small example with the loop that demonstrates the issue? I tried adding `repeat...until` to a function, but it doesn't create the issue.

**Comment by theRealsteveRoll** [comment]
I got it. It seems that this happens when the loop is just before an `else` in an if..else statement.
This:
![image](https://user-images.githubusercontent.com/40004112/46908888-012f6d80-cf32-11e8-81fa-7262a80b13c6.png)
does this:
![image](https://user-images.githubusercontent.com/40004112/46908894-12787a00-cf32-11e8-9b7f-865435738480.png)
However, this:
![image](https://user-images.githubusercontent.com/40004112/46908910-45227280-cf32-11e8-952e-77e84327079a.png)
does this:
![image](https://user-images.githubusercontent.com/40004112/46908914-53708e80-cf32-11e8-83a0-279e040ed4ad.png)

**Comment by pkulchenko** [comment]
ok, this seems to be the shortest example:

```lua
local function a1()
  if true then
    repeat
    until false
  else
  end
end

local function a2()
end
```

Both `repeat` and `else` are needed to get the "invalid" case. I'll take a look at what's going on. Thank you for the example!

**Comment by pkulchenko** [comment]
@theRealsteveRoll, the following patch fixes the issue for me:

```diff
diff --git a/lualibs/lua_parser_loose.lua b/lualibs/lua_parser_loose.lua
index 09a7110c..c63a4c18 100644
--- a/lualibs/lua_parser_loose.lua
+++ b/lualibs/lua_parser_loose.lua
@@ -82,10 +82,10 @@ function PARSE.parse_scope(lx, f, level)
     -- Detect end of previous statement
     if c.tag == 'Eof' -- trigger 'Statement' at the end of file
     or c.tag == 'Keyword' and (
-       c[1] == 'break' or c[1] == 'goto' or c[1] == 'do' or c[1] == 'while' or
+       c[1] == 'break' or c[1] == 'goto' or c[1] == 'do' or c[1] == 'while' or c[1] == 'else' or
        c[1] == 'repeat' or c[1] == 'if' or c[1] == 'for' or c[1] == 'function' and lx:peek().tag == 'Id' or
-       c[1] == 'local' or c[1] == ';' or c[1] == 'until' or c[1] == 'return' or c[1] == 'end') or
-       c.tag == 'Id' and
+       c[1] == 'local' or c[1] == ';' or c[1] == 'until' or c[1] == 'return' or c[1] == 'end')
+    or c.tag == 'Id' and
            (cprev.tag == 'Id' or
             cprev.tag == 'Keyword' and
                (cprev[1] == ']' or cprev[1] == ')' or cprev[1] == '}' or
```

Could you check if it works correctly for your case as well?

**Comment by theRealsteveRoll** [comment]
Yup, this fixed my case too! Thanks a lot!
