### ISSUE TITLE
Debian stretch: Won't launch with kernel/userspace mismatch

### ISSUE THREAD

**Issue by nrnrnr** [pkulchenko/ZeroBraneStudio#947]
### Issue

Long story, but I run a 32-bit userspace on top of a 64-bit kernel.

I've edited zbstudio.sh to force the architecture to x86, but it's picking up x64 from some other source.
I'm hoping you'll be able to look at this grep output and suggest what I should edit:

````
build/build-linux.sh:           ARCH="x64"
CHANGELOG.md:  - Upgraded Lua 5.3 interpreter to 5.3.1 on Linux (x86 and x64).
CHANGELOG.md:  - Added linux binaries with support for x86 and x64 (helps #89).
lualibs/fs.lua:local x64 = ffi.arch == 'x64' or nil
lualibs/fs.lua:  if x64 then
lualibs/lexers/go.lua:  'bool', 'byte', 'complex64', 'complex128', 'error', 'float32', 'float64',
lualibs/sha2.lua:  H[7] = 0x64f98fa7
src/main.lua:      x86_64  = "x64",
src/util.lua:    local archvals = {x64 = true, x86 = true}
zbstudio/zbstudio.in:if [[ "$(uname -m)" == "x86_64" ]]; then ARCH="x64"; else ARCH="x86"; fi
````

### Info requested in contribution guidelines

OS version:

````
Linux homedog 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
````

Using commit b3dd4c34100c594ce02afa93625ac394037d7992

steps to reproduce the issue: download, edit `zbstudio.sh` to force x86 architecture, run `zbstudio.sh`:

````
nr@homedog ~/n/ZeroBraneStudio> ./zbstudio.sh
nr@homedog ~/n/ZeroBraneStudio> bin/linux/x86/lua: error loading module 'wx' from file 'bin/linux/x64/clibs/libwx.so':
        bin/linux/x64/clibs/libwx.so: wrong ELF class: ELFCLASS64
stack traceback:
        [C]: at 0x080b42d7
        [C]: in function 'require'
        src/main.lua:38: in main chunk
        [C]: at 0x0804c095
````

I'm not aware of having used a nonempty config or plugins.

**Comment by pkulchenko** [comment]
@nrnrnr, If `uname -m` returns `x86_64`, then try replacing "x64" with "x86" in `main.lua` line 22 (`x86_64  = "x64"`). I don't think anything else needs to be modified. Let me know if this still doesn't work.

How can 32-bit userspace be detected?

**Comment by nrnrnr** [comment]
Brilliant!  That resolves it exactly.

As for detecting a 32-bit userspace, I did a little searching and I found a brilliant trick in the sources for Chromium: run `file $SHELL`.  Here's the output on my platform:

````
/usr/bin/fish: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5289ae684242b83d265b8ab0c414643e8eae3130, stripped
````

**Comment by nrnrnr** [comment]
@pkulchenko I'm never sure how github notifications work, but the previous comment answers your question about detecting a 32-bit userspace.

**Comment by pkulchenko** [comment]
@nrnrnr, yes, thank you. I'll likely make a patch based on your answer, so that this case can be detected automatically. I'll update the ticket when it's ready and may ask for help with testing...
