### ISSUE TITLE
Error on opening files from non ASCI folder name that can't be mapped to a short name (Windows)

### ISSUE THREAD

**Issue by D0NM** [pkulchenko/ZeroBraneStudio#948]
![image](https://user-images.githubusercontent.com/11454242/47523454-7e9f9a00-d8b1-11e8-8ee1-2f9d0ca14f94.png)

ZB Studio 1.70 had no such an issue. I just run it to test.
Enabling / disabling of the custom cfg/user.lua doesn't help.

PS In short now I cannot run Lua scripts from a folder with a Cyrillic characters.
like this  **!ЛАБПРОГ**

**Comment by pkulchenko** [comment]
It actually works, but only for those drives that allow short name generation. It wouldn't work in 1.70 either, as it fails on showing message. See if this patch fixes it:

```
diff --git a/interpreters/luabase.lua b/interpreters/luabase.lua
index 3c27f792..754c974e 100644
--- a/interpreters/luabase.lua
+++ b/interpreters/luabase.lua
@@ -26,7 +26,7 @@ local function shortenIfNeeded(filepath)
       :format(filepath))
     ide:Print(
       ("You can enable short names by using `fsutil 8dot3name set %s: 0` and recreate the file or directory.")
-      :format(wfilename:GetVolume()))
+      :format(wx.wxFileName(filepath):GetVolume()))
   end
   return filepath
 end
```

It seems like the mapped drive you are using is not configured to allow for the short name conversion.

**Comment by D0NM** [comment]
Thank you for the solution... 

but it somehow works with my 1.70 

![image](https://user-images.githubusercontent.com/11454242/47527086-1786e300-d8bb-11e8-95b4-f011903c8003.png)

PS this folder is a part of DropBox Cloud.

**Comment by pkulchenko** [comment]
Interesting; what do you see in the Output window when you do Run in 1.70 and 1.80? I wouldn't expect any difference, but if you see some different paths, I'd be curious to see what they are. Thanks!

**Comment by D0NM** [comment]
both versions were run with ORIGINAL
cfg/user-sample.lua
renamed to user.lua

with 1 changed line. I commented out the path to Lua   
```
-- to specify full path to lua interpreter if you need to use your own version
-- path.lua = 'd:/lua/lua'

```

**Comment by pkulchenko** [comment]
Can you apply the patch from this ticket and show the output for 1.80?

**Comment by D0NM** [comment]
1.8 works after the patch:

![image](https://user-images.githubusercontent.com/11454242/47529630-c4fcf500-d8c1-11e8-885d-ab2e3e65fc3a.png)

**Comment by pkulchenko** [comment]
So it works the same way as it worked in 1.70, right? It can't get the short name, but is still being able to launch the script...

**Comment by D0NM** [comment]
Right. I'm pretty satisfied with this.
Thank you.

**Comment by pkulchenko** [comment]
ok; will push the change then. Thank you for the report!
