### ISSUE TITLE
Strange output truncation

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#949]
Take the following simple code:
```lua
local sprintf=string.format
local function printf(...)
	io.write(sprintf(...))
	io.flush()
end

for i=1,1000 do
	printf("%d\t%d\n",i,i*i)
end
printf("DONE\n")
```
Run with [F6]. The output ends - as expected - with
```
994	988036
995	990025
996	992016
997	994009
998	996004
999	998001
1000	1000000
DONE
Program completed in 0.02 seconds (pid: 3853).
```

now change the limit from 1000 to 8000.
Run with [F6], the output is truncated...
```
6840	46785600
6841	46799281
6842	46812964
6843	46826649
6844	46840336
6845	46854025
6846	468Program completed in 0.10 seconds (pid: 3858).
```

Is there a reason for this? Any configurable limit? Or just a bug?

(ZeroBrane Studio 1.70 on xubuntu 18.04.1 LTS)

**Comment by jjvbsag** [comment]
@moteus: Could you please explain your comment, because I really don't understand, what you want to say.

I use a standard xubuntu installation and a plain ZBS. Enter a script and execute it inside ZBS and the output is truncated. The same script started with lua or luajit from a terminal has no truncation, neither has it when run from inside SciTE (which was my favorite Lua-Editor before ZBS).

I don't cross compile for this issue, I just use, what comes with ZBS installation. And even if I did, I would not know, where to place a 'g' or 'd' modifier, so please give me a clue.

**Comment by jjvbsag** [comment]
Its getting more strange: Increasing the limit to 10000 again returns an _untruncated_ output. :question: :question: :question:

**Comment by pkulchenko** [comment]
@jjvbsag, interesting. Do you get the same result when you run the same command (as copied from the Output window)?

**Comment by jjvbsag** [comment]
@pkulchenko I tried the command line 
`"/opt/zbstudio/bin/linux/x64/lua" -e "io.stdout:setvbuf('no')" "/home/temp/lua/PrintLines.lua"` 
in a terminal window. No truncation.

In the meantime I also tried the same on W7x64 platform. No issue there. Output is complete, even in ZBS. So this seems to be linux-specific. Someone should verify this on macOS.

**Comment by pkulchenko** [comment]
ok, I'll test it on macOS and Linux. Are we talking about the script in the first comment?

**Comment by jjvbsag** [comment]
Yes. This first script. But also the simplified script in https://github.com/pkulchenko/ZeroBraneStudio/issues/949#issuecomment-433729216 shows the same effect. I believe, it depends only on the amount of output. There seems to be a critical window of size, where the output wont be displayed.

**Comment by jjvbsag** [comment]
@pkulchenko I'm still investigating on my side too.
It also has something to do with timing. 
```lua
for i=1,8000 do
	io.write(i,"#############\n")
end
print("DONE")
```
truncates the output
```lua
local socket=require"socket"
for i=1,8000 do
	io.write(i,"#############\n")
	socket.sleep(0.001)
end
print("DONE")
```
does NOT. :confused:

**Comment by pkulchenko** [comment]
Does it only happen on Linux?

**Comment by ardje** [comment]
>
> The most important question is:

if you move the socket.sleep to the end and not in the loop, does it still
truncate?
if you instead do the setvbuf at the end and do a final print, does it
still truncate.
There are 2 possibilities:
1) the program stops witthout the software being able to flush the output
buffers to the pipe.
2) the program stops with the software being able to flush the output.
Zerobrane has not processed all input, but gets the child exited signal and
return value and closes the pipe.

I opt for 2) :-).
Can't test it since I still have to compile the armhf (desktop) and arm64
(chromebook container) versions.

**Comment by jjvbsag** [comment]
@pkulchenko Yes, only Linux. I tried on different machines

- xubuntu 16.04.1 LTS with AMD Ryzen 7 : truncation :heavy_minus_sign: 
- xubuntu 18.04.1 LTS with Intel Core I7 : truncation :heavy_minus_sign: 
- Windows7/x64 with intel Core I5 : complete output :heavy_check_mark: 
- Windows7/x64 with intel Core I7 : complete output :heavy_check_mark: 

Someone should do the test on MacOS...

**Comment by jjvbsag** [comment]
I did another test using 
```lua
local fd=assert(io.open("out.txt","w"))
for i=1,8000 do
	io.write(i,"#############\n")
	fd:write(i,"#############\n")
end
print("DONE")
fd:close()
```
The file is complete, but the visual output is truncated. I believe, this is another prove for 2)

**Comment by pkulchenko** [comment]
I think @ardje is correct about option 2. What happens is that when the process is terminated, there is `getStreams()` check for it to read what's left:

```
out:Connect(wx.wxEVT_END_PROCESS, function(event)
    local pid = event:GetPid()
    if (pid ~= -1) then
      getStreams()
```

However, as part of the `getStreams` logic, the input is processed in (limited) batches to make sure that other events in the IDE are not blocked by a "busy" loop, so only about 40k of output can be processed without stopping:

```
local readonce = 4096
local maxread = readonce * 10 -- maximum number of bytes to read before pausing
```

Since normally the reading would be resumed on the next `IDLE` process, this is not a problem, but for terminated processes it's never resumed, so part of the output goes missing.

@jjvbsag, can you try with the following patch to see if this resolves the issue:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index 6313e41f..15923ac6 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -290,12 +290,12 @@ ide:GetCodePage() -- populate the codepage value if auto-detection is requested
 
 local readonce = 4096
 local maxread = readonce * 10 -- maximum number of bytes to read before pausing
-local function getStreams()
+local function getStreams(all)
   local function readStream(tab)
     for _,v in pairs(tab) do
       -- periodically stop reading to get a chance to process other events
       local processed = 0
-      while (v.check(v.proc) and processed <= maxread) do
+      while (v.check(v.proc) and (all or processed <= maxread)) do
         local str = v.stream:Read(readonce)
         -- the buffer has readonce bytes, so cut it to the actual size
         str = str:sub(1, v.stream:LastRead())
@@ -354,7 +354,7 @@ end
 out:Connect(wx.wxEVT_END_PROCESS, function(event)
     local pid = event:GetPid()
     if (pid ~= -1) then
-      getStreams()
+      getStreams(true)
       streamins[pid] = nil
       streamerrs[pid] = nil
       streamouts[pid] = nil
```
