### ISSUE TITLE
Markdown formatting in calltips

### ISSUE THREAD

**Issue by stdgregwar** [pkulchenko/ZeroBraneStudio#953]
Since there is already Markdown formatting in lua comments, It would be nice to have also markdown formating into calltips. This way our nice apis descriptions can contain links to actual documentation or smart formatting.

**Comment by pkulchenko** [comment]
@stdgregwar, I think it would be nice to have, but I don't think it's supported by Scintilla. If you find how to do it, I'll see how it can be used ;) (http://www.scintilla.org/ScintillaDoc.html).
