### ISSUE TITLE
Several shadowed variables

### ISSUE THREAD

**Issue by mingodad** [pkulchenko/ZeroBraneStudio#959]
Hello !
I'm the author of https://github.com/mingodad/ljs and did a port of ZeroBraneStudio to it https://github.com/mingodad/ZeroBraneStudioLJS and found several places where duplicated variable declaration shadows variables declared in outer scopes, including finding this bug in luajit https://www.freelists.org/post/luajit/Probably-a-bug-of-duplicated-variable-declaration due to the same problem.
The port I did is somehow working so far and I'll look at it with more detail later and make some pull request for the findings.
Meanwhile if someone else want to try it and also help with fixes, please be my guest.
Cheers !

**Comment by pkulchenko** [comment]
@mingodad, do you have any further details on this?
