### ISSUE TITLE
REQ: enable libtiff for wxwidgets

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#963]
For some scripts I need tiff support in wxwidgets.
I tried the followings patch 
```diff
diff --git a/build/build-linux.sh b/build/build-linux.sh
index 8973afd7..43ced2f6 100755
--- a/build/build-linux.sh
+++ b/build/build-linux.sh
@@ -266,7 +266,7 @@ if [ $BUILD_WXWIDGETS ]; then
 
   ./configure --prefix="$INSTALL_DIR" $WXWIDGETSDEBUG --disable-shared --enable-unicode \
     --enable-compat28 \
-    --with-libjpeg=builtin --with-libpng=builtin --with-libtiff=no --with-expat=no \
+    --with-libjpeg=builtin --with-libpng=builtin --with-libtiff=builtin --with-expat=no \
     --with-zlib=builtin --disable-richtext --with-gtk=2 \
     CFLAGS="-Os -fPIC" CXXFLAGS="-Os -fPIC"
   make $MAKEFLAGS || { echo "Error: failed to build wxWidgets"; exit 1; }
```
it compiles fine on linux and works flawless.

libwx.so increases by 4k, which isn't much for a 4MB library.
I did not test for windows builds, because I migrate from W7 to ubuntu avoiding the W10 spy-OS :-1:

**Comment by pkulchenko** [comment]
I get 300K difference on Windows for 9M binary. Not a huge deal, but not 4k either. Not sure why the difference between the platforms though.

**Comment by pkulchenko** [comment]
@jjvbsag, how did you test that it works, btw? I'd like to check to confirm as well.

**Comment by jjvbsag** [comment]
@pkulchenko I'll have to remember, why I did this. I'll come back to you soon...

**Comment by pkulchenko** [comment]
Thank you. My preference would be only to include what's used in the IDE (and what may be used in the nearest future), as it's always possible to compile your own version if you need to use some other wxwidgets functionality.

**Comment by jjvbsag** [comment]
@pkulchenko 
Ok, I found my testscript. It's a simple image identifier:
```lua
#!/usr/bin/lua
require"strict"
require"wx"

local BITMAP_TYPES={}
for k,v in pairs(wx) do
	if k:match("wxBITMAP_TYPE_") then
		BITMAP_TYPES[v]=k
		--print(k,v)
	end
end

local dir=wx.wxDir('images')
local ok,entry=dir:GetFirst('*',wx.wxDIR_FILES)
while ok do
	local image,msg=wx.wxImage('images/'..entry)
	if image and image:IsOk() then
		print(entry,image:GetWidth(),image:GetHeight(),BITMAP_TYPES[image:GetType()])
	else
		print(entry,"failed")
	end
	ok,entry=dir:GetNext()
end
dir:Close()
```
Example output:
```
warning-sign.png	90	80	wxBITMAP_TYPE_PNG
warning-sign.tif	failed
warning-sign.jpg	90	80	wxBITMAP_TYPE_JPEG
warning-sign.bmp	90	80	wxBITMAP_TYPE_BMP
```
after the patch the output is
```
warning-sign.png	90	80	wxBITMAP_TYPE_PNG
warning-sign.tif	90	80	wxBITMAP_TYPE_TIF
warning-sign.jpg	90	80	wxBITMAP_TYPE_JPEG
warning-sign.bmp	90	80	wxBITMAP_TYPE_BMP
```

> My preference would be only to include what's used in the IDE

Understood. Because I often deal with PDF files, analysing their structure and extracting/identifying the images inside them and TIF is a really heavy used format inside PDF, I need this in wx.
If the size penalty is to big for you, I must and can accept this. But life would be much easier, if your wx installed with ZBS would include TIF support :wink: 

I'll attach the image folder for your reference:
[images.tar.gz](https://github.com/pkulchenko/ZeroBraneStudio/files/3333895/images.tar.gz)

**Comment by jjvbsag** [comment]
> I get 300K difference on Windows for 9M binary. Not a huge deal, but not 4k either. Not sure why the difference between the platforms though.

I cant recall, where I got the 4k from. `du -k libwx*.so` currently gives
```
14024	libwx-orig.so
14576	libwx.so
```
so it's about 552k penalty in my current system

**Comment by jjvbsag** [comment]
@pkulchenko you can close.
https://github.com/pkulchenko/ZeroBraneStudio/issues/966#issuecomment-550962895 shows, this will be solved in the next release
