### ISSUE TITLE
loading apis in external packages fails

### ISSUE THREAD

**Issue by pixeljetstream** [pkulchenko/ZeroBraneStudio#965]
newer versions of zbstudio don't seem to work with loading "apis" from external packages, as done in https://github.com/pixeljetstream/zbstudio-graphicscodepack 

upon loading the specs it complains that the apis referenced cannot be found, it uses the api directories relative zbstudio exe, rather than the package's directory. (the linked project complains about glsl/hlsl apis not found)

**Comment by pkulchenko** [comment]
Seems to be broken by e5beb2aa; will fix. Thank you for the report!

**Comment by jjvbsag** [comment]
@pkulchenko Could this also cause, that my additional interpreters in `~/.zbstudio/interpreters/` do not load with ZBS 1.80 ?

**Comment by jjvbsag** [comment]
@pkulchenko Please forget about it. I cannot recall, when and how it worked and I'm not sure, if I made a mistake, when migrating to a new PC. I only noticed, a project I used a long time ago, now failed. I now made - as you suggested - a plugin using `AddInterpreter` and it works flawless.

**Comment by pkulchenko** [comment]
@pixeljetstream, should be fixed now.

@jjvbsag, thank you for the update.
