### ISSUE TITLE
Unknown error on run command in plugin

### ISSUE THREAD

**Issue by olueiro** [pkulchenko/ZeroBraneStudio#973]
Hi!
I found an unknown error in interpreter API (Windows 7)

How to reproduce:

1. Create a plugin;
2. Paste this code:

```lua
local interpreter = {
  name = "issue",
  description = "issue",
  frun = function(self, wfilename, rundebug) end,
  hasdebugger = false
}
return {
  name = "...",
  description = "...",
  author = "...",
  version = 0.1,
  onRegister = function(self)
    ide:AddInterpreter("issue", interpreter)
  end,
  onUnRegister = function(self)
    ide:RemoveInterpreter("issue")
  end,
  onInterpreterLoad = function(self, interpreter)
    CommandLineRun(
      "help",--cmd
      nil,--wdir
      true,--to out
      false,-- no hide
      function() end, -- str cb
      "h", --iud
      function() end-- end cb
    )
  end,
}
```

Select this interpreter and restart ZBS.

**Comment by paul-reilly** [comment]
It looks like the issue is that your string callback `function() end --str cb` is not returning a string. The function is also supplied with a string so if you change:

    function() end, -- str cb

… to …

    function(str) return str end, -- str cb

You should be good to go.

**Comment by pkulchenko** [comment]
@paul-reilly, this is a good point; thank you for taking look at this! I agree that this fix should work, but it can probably be better handled in the IDE as well; I'll check.

**Comment by paul-reilly** [comment]
No worries, it's lucky I looked at it because it revealed a(nother) schoolboy error in my PR with assuming that there's always an API loaded.  :) 40959c1

**Comment by pkulchenko** [comment]
@paul-reilly, added patch that handles callbacks that may not return strings; thank you for the suggestion!

@olueiro, should be fixed now.
