### ISSUE TITLE
error loading module 'wx' on linux

### ISSUE THREAD

**Issue by xiexikui** [pkulchenko/ZeroBraneStudio#981]
bin/linux/x64/lua: error loading module 'wx' from file 'bin/linux/x64/clibs/libwx.so':
	libGL.so.1: cannot open shared object file: No such file or directory

**Comment by pkulchenko** [comment]
@xiexikui, it looks like you are missing libGL library. What's your OS version? You may try running `sudo apt install libgl1-mesa-glx`

**Comment by pkulchenko** [comment]
Closing; @xiexikui, let me know if you have any additional information, but I think it comes down to missing the GL library.
