### ISSUE TITLE
codepage problem on IDE output - displays fault on non ASCII characters from 'print' and 'os.execute'

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#984]
```lua
os.execute'ver'
print('version 版本')
```

If 'codepage=nil/true/false' then get this which `execute` display error.
![image](https://s2.ax1x.com/2019/04/10/ATfVVH.png)
If 'codepage=936' then, which `print` display error.
![image](https://s2.ax1x.com/2019/04/10/ATfjQf.png)

related: #663 #804

**Comment by pkulchenko** [comment]
@robertlzj, what's the current codepage setting in your OS? What does `chcp` command return?

I don't think there is anything that I can do, as it seems like the results of os.execute are in one encoding (as the Lua executable is not using Unicode versions of system calls) and the output from the Lua script is using another.

The only strange thing is that I expect the results of `codepage=true` and `codepage=936` to be the same (assuming 936 is indeed set as the current codepage), but they appear to be different in your results.

**Comment by robertlzj** [comment]
`chcp` returns 936.
Use lua.exe directly.
![image](https://s2.ax1x.com/2019/05/06/EBa74K.png)

**Comment by robertlzj** [comment]
Some notes:
My `chcp` is **cp936** (GBK GB2312 Chinese), and script file is UTF8.
So, interface/pipe from `os.execute`, `io.popen` would get encode problem.
One walk around is `io.popen('chcp 65001 |  ..command..)` to set codepage of command line to fit script. (Maybe could use it to convert codepage?)
Also, some repository in pure lua could help [utf8_filenames.lua in gist.github](https://gist.github.com/Egor-Skriptunoff/2458547aa3b9210a8b5f686ac08ecbf0#file-utf8_filenames-lua)

**Comment by pkulchenko** [comment]
Two questions:

1. What does `ide:GetCodePage()` return from the console when you set `codepage=true` in the config? It should detect the codepage and return 936, but I'd like to doublecheck.
2. Can you set `codepage=936`, apply the following patch and then try your test with ver/version commands:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index f8d90052..70bc7375 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -300,9 +300,9 @@ local function getStreams(all)
         -- the buffer has readonce bytes, so cut it to the actual size
         str = str:sub(1, v.stream:LastRead())
         processed = processed + #str
-
+ide:Print("read", #str)
         local codepage = ide:GetCodePage()
-        if codepage and FixUTF8(str) == nil and winapi then
+        if codepage and winapi then
           -- this looks like invalid UTF-8 content, which may be in a different code page
           str = winapi.encode(codepage, winapi.CP_UTF8, str)
         end
```

**Comment by robertlzj** [comment]
1. return 936.
2.`os.execute'ver'` in editor with both `cp936` or `codepage=ture` returns correctly on one of my computer before the patch.
Also test applying patch.
```lua
read	2
read	43
Microsoft Windows [版本 10.0.19041.508]
```

**Comment by pkulchenko** [comment]
What does the following test return with the path (and `codepage=936`):

```
os.execute'ver'
print('version 版本')
```

**Comment by robertlzj** [comment]
On notepad, `codepag=true`, `codepag=936` both.
```lua
read	60

Microsoft Windows [版本 10.0.18363.1082]
version 鐗堟湰  --not correct
```

**Comment by pkulchenko** [comment]
@robertlzj, one more thing, can you change `ide:Print("read", #str)` to `ide:Print("read", #str, str)` in the patch, as I'd like to see the "original" string as well?

**Comment by robertlzj** [comment]
On notepad, codepag=true, codepag=936 both.
![image](https://user-images.githubusercontent.com/7419030/93276876-5eee2380-f7f3-11ea-987c-3d27328912e2.png)
The 2#, -1# line is uncorrect.

I can't copy correctly, it became garble completely:
```lua
敲摡㘉र਍楍牣獯景⁴楗摮睯⁳끛뇦₾〱〮ㄮ㌸㌶ㄮ㠰崲਍敶獲潩⁮觧겜਍ഊ䴊捩潲潳瑦圠湩潤獷嬠觧겜ㄠ⸰⸰㠱㘳⸳〱㈸൝瘊牥楳湯鞐ꃥ낹
```

**Comment by pkulchenko** [comment]
@robertlzj, I think I figured out what happened. It looks like the results of `print` and `os.execute` commands are in different encodings, but because they get concatenated together into one string, they always get processed together and it turns `correct,wrong` into `wrong,correct` result depending on whether the patch is applied or not. The fix would be to process each line independently. Can you try the following patch and let me know if it generates correct results:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index f8d90052..a161c923 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -303,8 +303,12 @@ local function getStreams(all)
 
         local codepage = ide:GetCodePage()
         if codepage and FixUTF8(str) == nil and winapi then
-          -- this looks like invalid UTF-8 content, which may be in a different code page
-          str = winapi.encode(codepage, winapi.CP_UTF8, str)
+          -- this looks like invalid UTF-8 content, which may be in a different code page;
+          -- replace it with the UTF8, but do it line-by-line,
+          -- as it may be a buffered mix of different commands
+          str = str:gsub("[^\r\n]+", function(s)
+              return FixUTF8(s) == nil and winapi.encode(codepage, winapi.CP_UTF8, s) or s
+            end)
         end
 
         local pfn
```

**Comment by robertlzj** [comment]
Test done, results is correct.

**Comment by pkulchenko** [comment]
Thanks for checking; merged.
