### ISSUE TITLE
IDE incorrectly handles files with non-latin ASCII characters

### ISSUE THREAD

**Issue by AVBL** [pkulchenko/ZeroBraneStudio#986]
I have a plain 8-bit text file with non-Latin characters in comments and strings (Russian letters in Windows OEM 866 codepage). This file is perfectly processed by the LUA interpreter.

When you open the same file in ZBS, editor instead of non-Latin characters displays garbage - partly hex-codes, partly hieroglyphs. When you try to execute this file, in the Output tab in ZBS  same garbage is also shown.

Sample file:
print "тест"

Editor shows:
print "xE2xA5xE1xE2"

Output tab:
xE2xA5xE1xE2

PS: If I copy text from a file through a buffer, in ZBS it will be shown correctly, but after saving to file it will be in the UTF encoding and will work incorrectly with the LUA interpreter.

**Comment by pkulchenko** [comment]
@AVBL, you can set the code page to 866; for example, add the following to the config `codepage=866`. You can also set `codepage=true`, which should auto-detect your codepage.

This won't fix the editor content, but will fix what the Output window shows.

The editor uses UTF-8 encoding by default, although you should be able to change the setting if you want. I tried calling `ide:GetEditor():SetCodePage(866)` from the console, but this completely hides the printed text, not sure why.

**Comment by pkulchenko** [comment]
@AVBL, actually, according to the Scintilla documentation `ide:GetEditor():StyleSetCharacterSet(wxstc.wxSTC_LUA_STRING, wxstc.wxSTC_CHARSET_OEM866)` should be used in this case, but the table doesn't indicate that 866 is supported on windows (https://www.scintilla.org/ScintillaDoc.html#SCI_STYLESETCHARACTERSET), so it seems like you may need to change the encoding if you want to see the text correctly in the editor.

**Comment by pkulchenko** [comment]
@AVBL, I'm closing the ticket, but feel free to update with the new information if none of the suggestions help.
