### ISSUE TITLE
Key shortcuts don't always work 

### ISSUE THREAD

**Issue by bleuge** [pkulchenko/ZeroBraneStudio#987]
Using ZeroBrane Studio (1.80; MobDebug 0.705) in Windows 7 x64

Sometimes keys (as ctr+f / find or ctrl+s / save) don't work while editing. 
In fact, the standard combo, ctrl+f, start typing what you want to search, just insert the text in the document, I try again ctrl+f, nothing. 

When this happens, no other combo keys work. 

Is there any option or thing that does this? 
Could I debug this in any way, maybe it's in my part. 

Thanks

**Comment by pkulchenko** [comment]
@bleuge, that's unusual. I'm also mostly on Windows (x64 as well), but have never seen this happening.

Did you notice any specific circumstances when this happens? Do you see "Find" buttons in the toolbar become disabled? Do you see menu items getting disabled if you go to "Search" menu item?

**Comment by bleuge** [comment]
It was strange, I've not use too much ZB later, but these days it worked ok. 
Probably was something related to my system, If I got this again I'll try to get why  it happens. 
Thanks dev!
