### ISSUE TITLE
PB loading baselib.lua

### ISSUE THREAD

**Issue by FullGas1** [pkulchenko/ZeroBraneStudio#991]
Hello,

When I launch ZBS, this one start, but I have an error message "Error while loading API file :cannot open F:\Outils_développement\ZeroBrane\api\lua\baselib.lua: No such file or directory.

When à look in this path, there is the File, and he is normaly formed (I can open it in Notepad.

Can someone please tell me what I can do for fix this problem ?

Thank's

**Comment by madmaxoft** [comment]
I would venture a guess that the international letter in the path could a problem. If you temporarily move ZBS to a different path with no `é` in it, does it work?

**Comment by pkulchenko** [comment]
@FullGas1, @madmaxoft is likely to be correct. I think I fixed this issue in 2687a4aa (that was fixing #965), but you'll need to use the current version from the repository or avoid unicode characters in the name.

**Comment by FullGas1** [comment]
Thank's for your help, and sorry for my question.

It was not a bug, I had made an error in my LUA_PATH. When corrected, it's OK.

**Comment by pkulchenko** [comment]
no problem; thanks for the update.
