### ISSUE TITLE
Upgrade to wxwidgets 3.1.3+; add support for 64bit macOS binaries

### ISSUE THREAD

**Issue by pkulchenko** [pkulchenko/ZeroBraneStudio#999]
Recompile wxwidgets/wxlua binaries with the following changes:

- add support for the latest wxwidgets release (3.1.3)
- add 64bit binaries on macOS; removed relying on DYLD environment variable, as it doesn't work from macOS Catalina sandbox; replaced it with setting @rpath in the binaries for lua and ssl libraries.
- add support for Dark mode (on macOS Mojave+, Linux, and Windows 10); this includes dynamic switching between dark and light modes where supported
- add GTK3 support on Linux; updated glibc to 2.23+ (compiled on Ubuntu 16.04+)
- add AddPrivateFont support on all platforms
- add d2d support on Windows (needed for font ligatures)

Things to consider:
- +Test and add `AddPrivateFont` support on all platforms
- +Switch to 10.9 as the target platform on macOS instead of 10.7; may not be needed if 10.9+ compilation is supported with `--with-cxx=11` configure option. This is now done with `-std=c++11 -stdlib=libc++` and 10.7 as the target.
- +Include `tiff` library for more complete image support (#963)
- +Include xml/xrc support
- +Update tab closing marker on Linux similar to the one on MacOS update
- +Retest printing that is disabled on Linux to check if the canvas issue is fixed. This seems to be working, so will be enabled.

Open issues:
- (macOS) Inactive tab font has low contrast with the background. Not sure how big of an issue it is, as it's based on system-provided colors, but it's different from the behavior on <=10.13 and only happens on macOS 10.14+
- (GTK3) status message in the Search bar (Use `Escape`...) is not on one line (at least initially)
- **fixed in wxwidgets**; (Win) Sticky buttons are not shown as sticky (for example, in the search toolbar and in the main toolbar for live coding); [wxwidgets ticket 18496](https://trac.wxwidgets.org/ticket/18496)
- **fixed with a workaround**; (GTK3) wxtree has the selected/inactive node as white background
- **fixed in wxwidgets**; (macOS) `UserListShow` crashing from tests; can't reproduce from the regular IDE code, so may be related to a call sequence or some strange context; [wxwidgets ticket 18434](https://trac.wxwidgets.org/ticket/18434)
- **acceptable**; (macOS) active/bold font in the notebook tabs has a strange shadow
- **fixed in wxwidgets**; (Win) `EnsureVisible` doesn't scroll the tree item into view when wxTreeCtrl is frozen; [wxwidgets ticket 18435](https://trac.wxwidgets.org/ticket/18435)

Related tickets: #1017, #1012, #997, #982, #966, #963, #960,  #907, #856, #816, #712, #721, #680.

**Comment by pkulchenko** [comment]
Opened wxwidgets tickets for some of the issues with wxwidgets 3.1.3: https://trac.wxwidgets.org/ticket/18434 and https://trac.wxwidgets.org/ticket/18435 (fixed).

**Comment by Oozlum** [comment]
@pkulchenko, Since you're rebuilding wxlua anyway, can I ask for XML support to be enabled in the config?  I have a project that uses XRC files and it's a bit of a pain that ZBS doesn't support it.  (wx.wxXmlResource is nil)

**Comment by pkulchenko** [comment]
@Oozlum, pushed windows binary with xml and xrc support: https://github.com/pkulchenko/ZeroBraneStudio/tree/binary-xml-xrc-no-gl. Give it a try and let me know how it works for you. macOS will be available as well, but there are some wxlua changes that need to be applied, so if you get a chance to test on Windows, let me know if it does or doesn't work for you.

**Comment by gusals3587** [comment]
Hello, any plan to merge this with the master soon? The macOS Catalina now disallow 32-bit app from running, so I can't run ZeroBraneStudio now.

**Comment by pkulchenko** [comment]
@gusals3587, you can definitely run the IDE right now on Catalina. You can use [all-binaries-190c](https://github.com/pkulchenko/ZeroBraneStudio/tree/all-binaries-190c) branch and either clone the repository and checkout that branch or download the archive with that branch and unzip it (just make sure to run it from under your HOME folder and not `Downloads`, `Documents`, or `Desktop`, as Catalina is limiting access to binaries from those folders).

I do plan to merge the changes and do a release in the near future, but there are still several issues that need to be resolved as well as changes in components that the IDE depends on that I'm waiting for to happen.

**Comment by cup** [comment]
https://github.com/pkulchenko/ZeroBraneStudio/issues/1034

**Comment by pkulchenko** [comment]
These changes have been merged into master.
